Readme.md
Trivial changes to the README to get it in a more readable state.
=> Fix README typos.

openlibrary/plugins/upstream/utils.py
Small improvement to solve the issue
https://github.com/internetarchive/openlibrary/issues/164
it needs to be doublechecked before merge and deployment
=> Select events other than update for the "Around The Library" footer.

static/robots.txt
=> robots.txt : disallow /api

openlibrary/solr/data_provider.py, openlibrary/solr/update_work.py
FIX: update_work.py was failing connecting to the ia_db
ADD: added some validation
=> SOLR_UPDATER: some improvements on scape validation and bug FIX

openlibrary/templates/admin/people/view.html
=> fix typo in html

openlibrary/templates/lib/site_legal.html
This was on the longstanding "todo" list and am finally getting around to it.
=> longstanding typo fix in footer

openlibrary/plugins/worksearch/code.py
Fixes issue https://github.com/internetarchive/openlibrary/issues/291
The following queries
https://openlibrary.org/search.json
https://openlibrary.org/search.json?unrecognised=something
will now return:
```
{
start: 0,
num_found: 0,
numFound: 0,
docs: [ ]
}
```
Instead of all results, which happened previously.
The logic now checks whether there is at least one of `q=`, `title=`, `isbn=`, `author=` etc search terms in a worksearch, and if not returns no results.
To explicitly query for everything, the following will work:
https://openlibrary.org/search.json?q=*:*
https://openlibrary.org/search.json?title=*  (this returns everything with a title field, apparently there are entries in the db without titles?)
A single asterisk in `q=*` will **not** work, and return 0 results due to the way …
=> null search queries now return no results rather than all

openlibrary/templates/authors/index.html
change details about author merge to indicate that it's admin-only for now
=> author merge admin-only

.gitignore, openlibrary/templates/lib/analytics.html, openlibrary/templates/site/footer.html, openlibrary/templates/site/head.html
Implement same analytics as are used on Archive.org
=> Add anonymized site analytics

openlibrary/templates/email/waitinglist_book_available.html
HOW HAS THIS TYPO BEEN HERE FOR SO LONG!??!
=> 😳 typo fix - pls merge at earliest convenience

openlibrary/templates/lib/search_foot.html, openlibrary/templates/lib/search_head.html, openlibrary/templates/work_search.html
Also slightly clean up indentation and whitespace
=> Remove Search Inside (aka Search Across) public touchpoints

openlibrary/templates/account.html
The Settings page has said "coming soon" forever. I decided to make the page more accurate and useful and add a link to the contact page that was more visible.
=> rm "coming soon" that is not coming soon.

openlibrary/plugins/upstream/tests/test_utils.py, openlibrary/plugins/upstream/utils.py, openlibrary/templates/type/author/view.html, openlibrary/templates/type/edition/view.html, openlibrary/templates/type/list/view.html, openlibrary/templates/type/work/view.html
=> Fix issue with Unicode chars in titles and URLs of author/work/edition/list pages

Quickstart.md, openlibrary/i18n/messages.pot, openlibrary/i18n/te/messages.po, openlibrary/templates/lib/search_foot.html, openlibrary/templates/lib/search_head.html, openlibrary/templates/search/inside.html, static/css/master.css
Note that there are global search forms at the top and bottom of each page.
=> Add "Search inside" link to global search form

openlibrary/templates/work_search.html
=> fixes 334 daisy links w/ duplicate work in url

openlibrary/plugins/openlibrary/js/ol.js, openlibrary/plugins/worksearch/code.py, openlibrary/templates/lib/search_foot.html, openlibrary/templates/lib/search_head.html, openlibrary/templates/work_search.html, static/css/master.css, tests/integration/README.md, tests/integration/test_search.py
Global search form routes to metadata search or full-text search, depending on checkbox value
=> Add checkbox for full-text search to global search form at top right

openlibrary/templates/support.html
Based on email numbers, changed the topics to better fit what people contact us about and some other minor language changes.
=> updated support.html

openlibrary/plugins/openlibrary/pages/config_edition.page
added a structured data entry for Canadian National Catalog
=> update with AMICUS

openlibrary/templates/lists/widget.html, static/css/master.css
This addresses @jessamynwest's comment that the lists on editions pages have the wrong font-size. I think we want to keep the list items indented (so they are consistent with the other section). Also, made "Lists" section header consistent with the other headers and moved heart logo up.
=> Fixing list font size and heart + list header section

scripts/2009/01/sitemaps/sitemap.py
Removes editions from sitemap at @brewsterkahle's request
=> updating sitemap to remove editions and include full slug

openlibrary/templates/site/head.html
Fixes for @rchrd2, renders IE9 content correctly (before was duplicating copy within banner)
=> fixing donations banner to work w/ IE9

openlibrary/templates/home/read.html, openlibrary/templates/home/returncart.html
Let's not merge these in yet, I'll have them on a feature demo branch
=> updating section headers to be more clear on landing

openlibrary/plugins/openlibrary/home.py, openlibrary/templates/home/index.html, openlibrary/templates/home/popular.html, openlibrary/templates/home/waitlist.html
adding modern waitlisted books to landing, fixes for popular carousel
=> Popular Waitlist Carousel

openlibrary/plugins/upstream/account.py, openlibrary/templates/account/email/forgot.html, openlibrary/templates/login.html, static/css/master.css
[WIP] Adds "forgot email" utility and changes styling and copy to make it more obvious email is required in place of username
=> [WIP] Hotfix/use email banner

openlibrary/accounts/model.py, openlibrary/core/lending.py, openlibrary/core/waitinglist.py, openlibrary/macros/LoanStatus.html, openlibrary/plugins/upstream/account.py, openlibrary/plugins/upstream/borrow.py, openlibrary/plugins/upstream/models.py, openlibrary/templates/account/borrow.html, openlibrary/tests/core/test_waitinglist.py, tests/integration/__init__.py, tests/integration/test_auth.py, tests/integration/test_loans.py
Opening a PR to initiate discussion on the implementation
=> Change OL to initiate and report loans from IA accounts rather than OL accounts

openlibrary/plugins/upstream/account.py, openlibrary/templates/account/verify/success.html
- fixes activation email link to use email instead of username
=> adds ability to check @itemname

Quickstart.md
This is a documentation fix related to #442
=> update quickstart with correct testing credentials

openlibrary/macros/EditButtons.html
=> https link to actual CC0 license

openlibrary/plugins/admin/code.py
Unblocking @rchrd2 on accessing webpy error reports
=> adding ui for viewing errors as admin

openlibrary/plugins/upstream/utils.py
@tfmorris, re https://github.com/internetarchive/openlibrary/pull/480#pullrequestreview-34987310
=> fixing array index typo @tmorris spotted

openlibrary/plugins/upstream/account.py
This must have been fixed on another branch (as I recall fixing this issue)
=> fixing indentation error

openlibrary/core/lists/model.py, openlibrary/core/models.py, openlibrary/plugins/upstream/models.py, openlibrary/templates/type/list/view.html
Fix for issue #449 , work counts in editions were set to zero.
=> Better? fix for #449

openlibrary/plugins/inside/code.py, openlibrary/plugins/worksearch/code.py
@mek, this fixes what you reported at #427 , a similar code change will hopefully fix #361 at line https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/inside/code.py#L47
There are maybe more places where the encoding needs to set for urlencode, I have not yet checked
=> fix unicode subject and search inside issues

openlibrary/plugins/openlibrary/js/availability.js
=> handles the daisy case; i.e. book not_lendable

openlibrary/core/helpers.py, openlibrary/templates/books/carousel_item.html
resolves: error in processing template: TypeError: object of type 'NoneType' has no len()
=> addresses homepage NoneType has no len() bug

openlibrary/accounts/model.py, openlibrary/plugins/upstream/account.py, openlibrary/templates/account/email/forgot-ia.html, openlibrary/templates/account/email/forgot.html, openlibrary/templates/account/password/forgot.html, openlibrary/templates/login.html, static/css/master.css
@bfalling; further testing required
=> [WIP] Migrates OL auth to use IA creds only

openlibrary/macros/databarView.html, openlibrary/plugins/upstream/tests/test_utils.py, openlibrary/plugins/upstream/utils.py, static/css/master.css
attempting to fix None type append problem, also adding pinterest share link
=> Fixing web.ctx exception + adding pinterest share btn

openlibrary/plugins/books/code.py
in response to https://github.com/internetarchive/openlibrary/issues/329#issuecomment-332766171
=> cors fix for /api/books.json

tests/integration/README.md
Fix formatting of command blocks. Add virtualenv, MacPorts and missing pyYAML depenency.
=> Fix integration test instructions

openlibrary/plugins/openlibrary/js/autocomplete.js, openlibrary/plugins/openlibrary/js/automatic.js, openlibrary/plugins/upstream/addbook.py, openlibrary/templates/books/edit.html, openlibrary/templates/books/edit/edition.html, openlibrary/utils/__init__.py, static/css/jquery.autocomplete.css, static/css/master.css
Depends on #660 . Ignore the first 2 commits, since they're the refactoring done there. Resolves #654.
- It doesn't seem like solr is automatically updated, but needs some more research
- Creating a new work from the editions page is not implemented
- Doesn't check if moving last edition from a work
=> Change work from edition page

openlibrary/core/cache.py, openlibrary/core/models.py, openlibrary/plugins/admin/code.py, openlibrary/plugins/openlibrary/home.py, openlibrary/plugins/openlibrary/js/availability.js, openlibrary/templates/stats/readinglog.html, openlibrary/views/loanstats.py, static/css/master.css
Addresses issue #724 Reading Log Stats Page
=> adding basic stats UI for reading log feature

openlibrary/plugins/openlibrary/js/automatic.js
Fixes #696 (although there is still a strange flash / refresh, not sure if this just happens on dev)
=> fixes recentchanges page jquery-ui tabs

openlibrary/core/lending.py, openlibrary/plugins/openlibrary/home.py
=> added feature to bring user to random edition

openlibrary/templates/books/edit.html
=> Fix author autocomplete showing death = birth

CONTRIBUTING.md, Readme.md
Gist for ref: https://gist.github.com/mekarpeles/d4268370aceb14fd1cd648fc1a1ee6f8
=> Add CONTRIBUTING.md from mekarpeles' gist

openlibrary/templates/account/create.html
Closes #629 
Messaging added near the Password Field as well!
=> Added Password Requirements Messaging Near Account Creation Page

Quickstart.md, openlibrary/plugins/recaptcha/recaptcha.py, openlibrary/templates/account/create.html, openlibrary/templates/books/add.html, openlibrary/templates/books/edit.html, openlibrary/templates/site/head.html
Closes #802 
Successfully made the transition to reCAPTCHA v2. Code tested on local machine. Kindly add Public and Private key in the yml file for production use!
=> Migrated to reCAPTCHA v2 from reCAPTCHA v1

openlibrary/plugins/worksearch/code.py
This should reduce the number or errors in SOLR log files so I can continue tracking down why solr isn't updating in all cases. I don't think this fixes all the problems, but this was making the logs very noisy.
=> Fix common solr error, fixes #823

PULL_REQUEST_TEMPLATE.md
Closes #821 
* I feel we can try this out. If we feel it's really unneeded and annoying maybe remove it at a later commit. 
* Also using the word Closes in the Pull Request Description does not close the Issue immediately. For example you can take a look at the [Pull Request](https://github.com/internetarchive/openlibrary/pull/825#discussion_r173618426) and this [Issue](https://github.com/internetarchive/openlibrary/issues/817). The Issue will only be closed when the Pull Request is merged. So that solves us a lot of problems.
=> Pull Request Template Added

openlibrary/templates/covers/book_cover.html
=> Minor tweak to cover alt text

openlibrary/i18n/cs/messages.po, openlibrary/i18n/messages.pot, openlibrary/i18n/te/messages.po, openlibrary/plugins/upstream/account.py, openlibrary/templates/account/password/reset_success.html, openlibrary/templates/account/verify.html, openlibrary/templates/account/verify/activated.html, openlibrary/templates/account/verify/success.html, openlibrary/templates/work_search.html
Small update to messages in templates
=> Unify some i18n messages

scripts/bootstrap.sh
=> fixed symlink for less

openlibrary/i18n/fr/messages.po
Hi,
here is the French translation.
=> update French translation.

openlibrary/plugins/openlibrary/pages/config_edition.page
Re-Closes #881
- Fixed missing @ in https://github.com/internetarchive/openlibrary/pull/881#discussion_r175651543
- Adds "ASIN" as note for amazon
=> adding missing @

openlibrary/i18n/cs/messages.po
=> Update cs messages.po

openlibrary/i18n/fr/messages.po
This takes into account the work of @LeoBoudet and another proof-reader. It would be great if we could see the French version on the website: it would help a lot with the context.
=> update French translation

conf/solr/conf/schema.xml, openlibrary/solr/update_work.py, scripts/new-solr-updater.py
Closes #848
* author records have their alternate_names fields added to the Solr search index
=> Index author alternate_names in Solr

openlibrary/core/lending.py, openlibrary/plugins/upstream/borrow.py, openlibrary/plugins/upstream/models.py, openlibrary/templates/account/borrow.html
=> reverting ia bridge changes since openlibrary.php polyfilled

openlibrary/i18n/fr/messages.po
- Some style improvements.
- Fixed some typos.
=> Partial proofreading

conf/openlibrary.yml
=> adding realtime availability defaults in dev

openlibrary/templates/widget.html
closes #698 (part 2)
Links open in new window
=> make links open in new windows

openlibrary/catalog/add_book/__init__.py, openlibrary/plugins/importapi/code.py, scripts/manage-imports.py
Closes #950
Fixes OL id writebacks to IA after new books are imported into Open Library from Archive.org
=> fixes OL id writeback/sync to IA

openlibrary/plugins/openlibrary/js/automatic.js
Closes #934
Added event to disable save button after click
=> Fix #934 disable save button after click

openlibrary/templates/books/edit/edition.html
Closes #743
Translated from dropdown is now working again
=> [743/hotfix/fix-translated-from-dropdown]

openlibrary/macros/databarWork.html, static/css/master.css
Closes #962 
* Modified some html code to move buy section into sidebar
* Changed the relevant css code in order to be consistent
=> Moved buy section into side bar and fixed the relevant css

openlibrary/i18n/te/messages.po
Closes #885 
* Telugu translations done for i8n Translations
Translations done till Line 626
=> Telugu Translations Done

openlibrary/plugins/openlibrary/js/ol.js
Closes #613
1. Modified the HTTP request parameters which get appended in POST request in order to match the required as shown in #613 
2. Fixed a typo in change_url function
=> Add missing HTTP request parameters when saving profile edits.

openlibrary/templates/stats/readinglog.html, openlibrary/views/loanstats.py
=> adding readinglog stats for star ratings

openlibrary/plugins/openlibrary/code.py, openlibrary/plugins/openlibrary/design.py, openlibrary/templates/design.html, static/css/design.css, static/css/master.less
Closes #658 
MVP Adds a new endpoint /developers/design
=> Design pattern library @ /developers/design

static/css/colors.less, static/css/master.less
Contributes towards #968
* Resolve invalid search input background color
* Correct the main red color across the board (currently red and dark red are the same)
=> Fix color regressions from PR/997

static/css/master.less
=> fixing missed } in design-template merge

openlibrary/templates/work_search.html
=> loans + waitlists didn't have default val when user not logged in

openlibrary/templates/lib/nav_foot.html, static/css/master.less
Contributes towards #1005 
* Add an empty alt attribute to the logo in the footer (validates ARIA checks and will still be ignored by  screen readers) and add an aria-hidden attribute also
* Move duplicated element Id for `#footer-icons` to a new parent element to validate the HTML, and updated the CSS accordingly
* Add appropriate accessible title tags to the font-awesome icons in the footer
=> Resolve footer accessibility issues

openlibrary/templates/site/footer.html
=> fixing erroneous removal of analytics

openlibrary/core/schema.sql
We added 3 inserts to `schema.sql` so that we initialize the `bookshelves` db with the 3 kinds of bookshelves!
=> add inserts to schema.sql to make bookshelves

tests/screenshots/.gitignore, tests/screenshots/README.md, tests/screenshots/index.js, tests/screenshots/package-lock.json, tests/screenshots/package.json
To give us some more confidence in changing HTML and CSS. 🎨
This will give us an HTML report for a given commit, like this:
(In this example I just added some exclamation points to a header message to show what a diff would look like.)
=> Add basic manual screenshot testing 📸

scripts/ipstats.py
=> fixing ipstats

openlibrary/core/bookshelves.py, openlibrary/core/models.py, openlibrary/core/ratings.py, openlibrary/templates/type/edition/view.html, static/css/colors.less, static/css/master.less
Closes #1004 
- builds off of @maurachur's PR, adds styles, fixes edge-cases
=> Maurachur maura add work stats

scripts/ipstats.py
=> fixing date str formatter to ref correct nginx log file

static/css/master.less
Closes #992
- fixed infogami navigatio (inline, no discs)
=> fixing infogami navigation styling so its inline without discs

openlibrary/plugins/openlibrary/pages/config_edition.page
=> fix invalid json .page

static/css/books-edit.less, static/css/components/tablet/header-bar.less
Follow up to #1086
Don't want to cause other confusion in patchsets - exactly why we need #1089!
=> Hygiene: Fix some linting issues

openlibrary/macros/WorldcatLink.html, openlibrary/macros/databarWork.html, openlibrary/plugins/openlibrary/code.py, openlibrary/utils/isbn.py, static/css/master.less
- added library.link library lookup to books page which uses isbn13
=> Adding Library-link as a physical library lookup partner

Makefile, static/css/components/borrowTable.less, static/css/components/carousel.less, static/css/components/desktop/resultsCovers.less, static/css/components/diff.less, static/css/components/editions.less, static/css/components/form.olform.less, static/css/components/header-bar.less, static/css/components/mybooks-list.less, static/css/components/readinglog-stats.less, static/css/components/resultsCovers.less, static/css/master.less
Some new patches that contribute to #1085 and #1092 (but don't completely fix either)
Since we're using lessc right now, as a short term solution I propose using lessc's deprecated but built in minifier while we work out a more long term solution.
The other two commits just add documentation and shift LESS styles relating to the carousel's that use jcarousel, so please check they look okay to you and merge.
Thanks in advance!
=> Saturday hacking

openlibrary/catalog/marc/tests/test_parse.py
=> update parse tests to use pytest

openlibrary/catalog/get_ia.py
fixing dev by rm hard-coded config statement
=> removed unnecessary hard-coded config statement

openlibrary/templates/books/custom_carousel.html, openlibrary/templates/home/categories.html, openlibrary/templates/home/stats.html, openlibrary/templates/lib/nav_head.html, openlibrary/templates/site.html, openlibrary/templates/site/footer.html, openlibrary/templates/site/head.html, openlibrary/templates/site/stats.html, static/css/components/buttonBtn.less, static/css/components/buttonGhost.less, static/css/components/header-bar.less, static/css/components/page-banner.less, static/css/js-all.less, static/css/page-home.less
1) fix the nav menus without JS
2) standardise the buttons in the navigation component (don't use generic-button classes)
3) remove repaints due to JS
4) Move JS to bottom of page on the homepage, so that it doesn't block rendering
Result:
A lightning fast homepage.
=> Unblock home render

openlibrary/templates/books/custom_carousel.html, openlibrary/templates/home/categories.html, openlibrary/templates/lib/nav_head.html, static/css/common.less, static/css/components/book.less, static/css/components/carousel--js.less, static/css/components/carousel.less, static/css/components/category-item.less, static/css/components/desktop/header-bar.less, static/css/components/header-bar.less, static/css/js-all.less, static/css/lib/slick-theme.css, static/css/lib/slick.css
Closes #1177 AND #1173
* several changes to make the home page render better
* fix the hamburger without JavaScript
* some header cleanup
=> Carousel reflowing painting

openlibrary/plugins/openlibrary/js/ol.js, openlibrary/templates/work_search.html
Closes #1002 
* Modified parts of ol.js in order to alter mode functionality.
* Modified work_search.html to make a checkbox and hide elements
=> Test branch

openlibrary/plugins/openlibrary/js/ol.js, openlibrary/templates/work_search.html
This should have been labeled `WIP` and contains a breaking change
Reverts internetarchive/openlibrary#1176
=> Revert "Test branch"

static/css/components/carousel.less
Follow up to 9c2f726
Fixes: #1181
=> Border should not apply to carousel buttons

static/css/components/chart.less, static/css/legacy.less
Shuffling code.
This has no impact on rendering, just changes where file is sourced from.
=> CSS refactor: Identify chart component

openlibrary/plugins/admin/code.py
- fixes /admin to redir to /stats
=> fixes /admin to point to /stats

openlibrary/templates/type/list/embed.html
Closes #1212
Fixes broken /lists/OL...L/:title/embed pages; e.g.:
https://dev.openlibrary.org/people/mekBot/lists/OL103955L/Childhood_Favorites/embed?debug=true
=> fixing people/:name/lists/:title/embed endpoint

.stylelintrc.json, static/css/components/borrowTable-adminUser.less, static/css/components/buttonGeneric.less, static/css/components/buttonsAndLinks.less, static/css/components/carousel.less, static/css/components/datatables.less, static/css/components/desktop/header-bar.less, static/css/components/desktop/resultsCovers.less, static/css/components/editions.less, static/css/components/wmd.less, static/css/legacy.less
Updates #1100
Added max-empty-lines rule and fixed offenders which builds up to completing our white space issue of css.
Added no-eol-whitespace rule and fixed offenders which builds up to completing our white space issue of css.
=> Added max-empty-lines and no-eol-whitespace rule

openlibrary/i18n/README.md
Closes #1236 
Created a README.md file in openlibrary/i18n/ with the information in [this wiki page](https://github.com/internetarchive/openlibrary/wiki/Contributing-to-Internationalization-(i18n)) and with the comments [in this file](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/i18n/__init__.py)
=> Create README.md for internationalization wiki page

.stylelintrc.json, static/css/components/Tools.less, static/css/components/borrowTable-adminUser.less, static/css/components/header-bar.less, static/css/components/header.less, static/css/legacy.less, static/css/page-admin.less, static/css/page-edit.less, static/css/page-form.less, static/css/page-plain.less, static/css/page-user.less
Closes #1118
- Update .stylelintrc.json with "selector-max-specificity": "1,4,0"
- Disable the rule for any present offenders of above
=> Update stylelintrc with selector-max-specificity rule and disable for present offenders

openlibrary/templates/borrow/index.html, openlibrary/templates/borrow/read.html, openlibrary/templates/search/authors.html, openlibrary/templates/search/editions.html, openlibrary/templates/search/publishers.html, openlibrary/templates/search/subjects.html
Closes #1253 
* Removed redundant inline style from various templates.
=> Remove inline style from templates.

openlibrary/templates/books/custom_carousel.html
Fixes: #1171
I'm having issues locally, with loading images from https://archive.org/services/img/Strategies_00_Malk but I'm also seeing that issue before this change.
=> Carousel images should be lazy loaded

Readme.md
Towards #1134
- updates readme to include docker setup instructions + how to contribute to docker development
=> updating main readme to include docker setup docs

static/css/components/borrowTable.less
Closes #1226 
* added css rule to fix overlapping buttons in loans page
=> Fix overlapping buttons in loans page

openlibrary/templates/subjects.html, openlibrary/templates/subjects/index.html, package.json, static/css/components/cbox.less, static/css/components/dropper.less, static/css/components/link-box.less, static/css/components/rating-form.less, static/css/js-all.less, static/css/legacy.less, static/css/lib/helpers-common.less, static/css/lib/helpers-misc.less
This continues #1092
This shouldn't change anything other than how the code is organised.
The big difference is we now will load colorbox styles in the JS stylesheet. This shouldn't impact any existing pages, as we're loading that stylesheet as render blocking any way.
This is strategic and will be useful as we port pages to v2.
=> More components

static/css/components/rating-form.less, static/css/legacy.less
Moves to desktop styles into a media query and closes #1259 to fix the linting problems
=> Some desktop restricted styles

openlibrary/plugins/openlibrary/code.py, openlibrary/templates/books/custom_carousel.html
Closes #1280
- followup to @jdlrobson's #1280 PR to replace magic number w/ const + docs
=> followup to #1280, rm magic number

static/css/components/shareLinks.less
Resolves:
```
static/css/components/shareLinks.less
37:5  ✖  Unexpected duplicate        declaration-block-no-duplicate-properties
"display"                                                            
56:1  ✖  Unexpected missing          no-missing-end-of-source-newline         
end-of-source newline
```
=> addressing travis-ci 438940766 style issues

.stylelintrc.json
Closes #1097
commit cee702e64da98d8d9d7eb8e7c07d820020d80037 (HEAD -> ISSUE-1097, origin/ISSUE-1097)                                                         
Author: devbox <cbolgiano625@gmail.com>                                                                                                         
Date:   Tue Oct 9 19:17:59 2018 -0400                                                                                                           
ISSUE-1097: Follow up that makes whitespace consistant.                                                                                     
M       .stylelintrc.json
=> ISSUE-1097: Follow up that makes whitespace consistant.

openlibrary/templates/search/inside.html
Closes #1079 
In this Pull Request I have made the following changes:
Initialize num_found to 0
=> Initialized num_found to 0

openlibrary/templates/type/work/editions_datatable.html, package.json, static/css/components/Tools--tablet.less, static/css/components/Tools.less, static/css/components/dropper--tablet.less, static/css/components/dropper.less, static/css/components/page-banner--tablet.less, static/css/components/page-banner.less, static/css/legacy.less, static/css/page-home.less
These improvements make more of our components (identified and "legacy" styles) more mobile friendly.
=> Tablet styles

static/css/legacy.less
These styles prepare us for transitioning books and works pages to mobile.
=> Mobile styles books and works

requirements.txt
=> upgrading to pyOpenSSL==17.5.0 (deployed)

openlibrary/core/processors/readableurls.py, openlibrary/macros/RelatedWorksCarousel.html, openlibrary/macros/databarWork.html, openlibrary/templates/books/custom_carousel.html, openlibrary/templates/books/edition-show.html, openlibrary/templates/covers/change.html, openlibrary/templates/lists/widget.html, openlibrary/templates/subjects.html, openlibrary/templates/type/edition/view.html, openlibrary/templates/type/work/editions_datatable.html, openlibrary/templates/type/work/view.html, static/css/legacy.less
I'm well and truly stuck.
The remaining thing to make this page mobile friendly+v2 and I can't for the love of me work it out.
Someone please help me find a sane way to pass v2 to the page. All my work in this area is stalled until I can find a safe/sane way to do this :(
```
diff --git a/infogami/utils/view.py b/infogami/utils/view.py
index 45511b0..52102d7 100644
--- a/infogami/utils/view.py
+++ b/infogami/utils/view.py
@@ -161,6 +161,8 @@ def set_error(msg):
context.error += '\n' + msg
def render_site(url, page):
+    # HACK!!!!
+    page.v2 = True
return render.site(page)
@public
```
=> Books and Works page = v2

openlibrary/i18n/messages.pot, openlibrary/macros/MergeHistory.html, openlibrary/macros/RecentChanges.html, openlibrary/macros/RecentChangesUsers.html, openlibrary/templates/admin/ip/view.html, openlibrary/templates/admin/people/edits.html, openlibrary/templates/history.html, openlibrary/templates/recentchanges/render.html, openlibrary/templates/recentchanges/updated_records.html, openlibrary/templates/type/list/editions.html
Make Open Library serious again :)
=> renaming que -> comment in edit messaging

openlibrary/templates/lists/widget.html
Closes #1274
- fixes template + js issues which prevented user list interaction from succeeding
=> resolves 1274 broken user lists

openlibrary/templates/diff.html
=> adding clearfix to diff view

static/css/components/buttonLink.less, static/css/components/buttonsAndLinks.less, static/css/components/edit-toolbar--tablet.less, static/css/components/edit-toolbar.less, static/css/legacy.less
For: #1092
Please review #1333 first. This patch needs it.
=> Component: Edit Toolbar

static/css/components/buttonCta.less, static/css/components/buttonsAndLinks.less
=> Component: buttonCta

openlibrary/plugins/openlibrary/js/autocomplete.js, openlibrary/plugins/openlibrary/js/jquery.repeat.js
* Fix a css selector
* Use "on" instead of "live"
* Use "show" rather than setting display to ''
* Remove some empty JS blocks with long forgotten TODOs - these
just lead to code confusion
Closes: #1346
=> Fix the book editor (Upgrade jquery-repeat plugin for jquery v2 compatibility)

requirements_common.txt
Closes #1324 
added flake8 and pyflakes to docker config file, "requirements_common.txt"
=> added flake8 and pyflakes to docker config file

static/css/components/listLists.less, static/css/legacy.less
=> Component: ListLists

static/css/components/rating-form.less, static/css/legacy.less
star messaging styles belong to this component
See #1092
=> Component: Add star messaging styles to RatingForm

openlibrary/templates/languages/view.html, openlibrary/templates/publishers/view.html, openlibrary/templates/subjects.html, static/css/components/widget-box.less, static/css/legacy.less
=> Component: WidgetBox

.eslintrc.json, package-lock.json, package.json
Closes #1360 
- Add `eslint` check for javascript files
=> Add eslint check

openlibrary/macros/AffiliateLinks.html
=> fixes bwb price rendering, behaves like amz now

static/css/base/headings.less, static/css/components/category-item.less, static/css/components/cbox.less, static/css/components/wmd.less, static/css/legacy.less
Followup on #1395 #1383
Several fonts referenced which were not defined.
=> Fixing mentions of font w/o definitions

Readme.md
Closes #1321 
1. Added step to check line endings are set to input so git will change CRLF to LF on commit.
2. Added steps to check symlinks enabled or not. If not provided step to enable it.
3. Then provided step to hard reset the repo to HEAD so proper symlinks will be created.
=> Fixed #1321 - Update documentation for Windows Developers

Readme.md
=> fixes link for docker video!

openlibrary/core/fulltext.py
Closes #1434 
Verify if ```ocaid``` of each ```edition``` is in ```ocaids``` list.
=> Select fulltext search queries breaking #1434

openlibrary/catalog/add_book/__init__.py, openlibrary/core/vendors.py, openlibrary/utils/isbn.py, requirements.txt, requirements_common.txt
=> fixes amazon isbn lookup to work w/ isbn13

openlibrary/catalog/importer/load.py, openlibrary/catalog/utils/__init__.py
Closes #1453 
* Remove unused function `catch_and_mail_exception`
* Also removes unnecessary `error_mail` import
=> Removed dead code catch_and_mail_exception

static/css/components/navEdition.less, static/css/legacy.less
Add this small component
as documented in https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#navedition
See: #1092
=> Component: NavEdition

openlibrary/macros/LoanStatus.html, static/css/components/buttonBtn.less, static/css/legacy.less
See https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#modifiers
=> Buttonbtn: Add button--large modifier

static/css/legacy.less
Fixes: #1388
We forgot to add it!!
=> Load listList styles in the legacy stylesheet

openlibrary/plugins/openlibrary/code.py
Closes #1409 
changed the way opds was imported.
=> import of opds changed

static/css/components/page-banner.less
Closes #1371 
the page banner is hidden on mobile
=> hide banner on mobile

openlibrary/catalog/add_book/__init__.py, openlibrary/catalog/utils/__init__.py, openlibrary/plugins/importapi/code.py, openlibrary/tests/catalog/test_utils.py
Closes #1531 
* Fixes some data issues triggered by re-importing orphaned editions
* Improves the ability of authors to be associated with existing works on re-import
* Moves and re-enables existing tests for catalog/utils, mainly dealing with author name transforms
=> Fix and improve author re-importing

.eslintrc.json, openlibrary/plugins/openlibrary/js/add_new_field.js, openlibrary/plugins/openlibrary/js/availability.js, openlibrary/plugins/openlibrary/js/utils.js
This applies the changes by @redpfire to add no-redeclare
protection to our eslinting
Fixes: #1420
=> 101 unusual uses of undeclared variables

openlibrary/plugins/upstream/account.py
Closes #1512
Accounts page made v2
=> Account page made v2

requirements_common.txt
https://pypi.org/project/internetarchive
=> Update Python dependencies: internetarchive

.eslintrc.json, openlibrary/plugins/openlibrary/js/jquery.repeat.js, openlibrary/plugins/openlibrary/js/jsdef.js, openlibrary/plugins/openlibrary/js/loadStyle.js, openlibrary/plugins/openlibrary/js/ol.js, openlibrary/plugins/openlibrary/js/template.js, openlibrary/plugins/openlibrary/js/utils.js, openlibrary/plugins/openlibrary/js/validate.js
Closes #1516 
##Description
Edited eslintrc.json to cause an error for trailing whitespaces & spaces in parens and fixed existing errors.
=> Edited eslintrc.json & Removed Trailing spaces and spaces in parens.

openlibrary/plugins/openlibrary/js/ol.js
The form doesn't have an action.
Since 7c98cea JavaScript is updating it to have some useless URI.
To fix this, let's not touch the URL when not set.
Fixes: 1568
=> Fix login form.

openlibrary/plugins/upstream/recentchanges.py, openlibrary/templates/admin/ip/view.html, openlibrary/templates/admin/people/edits.html, openlibrary/templates/recentchanges/render.html, static/css/legacy.less
Closes #1513 
v2 tag has been added for the page but the list items need to be made mobile friendly will check them out.
=> Mobile responsive recentchanges page

docker/README.md
This needs to be made clearer to new contributors. It's
confused at least 2 of us!
Fixes: #1545
=> Document building of assets in Docker

openlibrary/core/processors/readableurls.py, openlibrary/templates/books/custom_carousel.html, openlibrary/templates/publishers/view.html
* Descope the carousel a la subjects page
and migrate it to slick (without facets -
see f534362)
* Remove some inline styles
Fixes: #1554
=> Publisher page is v2

openlibrary/plugins/worksearch/code.py, openlibrary/templates/work_search.html
Closes #859
Passed the v2 attribute to the search page
=> Mobile search page made v2

requirements_common.txt
https://pypi.org/project/simplejson  This upgrade is still worth testing despite #1451
=> Update Python dependencies: simplejson

openlibrary/templates/publishers/view.html
Follow up to 07b60c5
* Removes the non-functional sort facets
* graph no longer interacts with carousel so remove code that
tries to do this.
Fixes: #1554
=> Follow up to publisher migration to v2

openlibrary/plugins/search/code.py
=> Use list comprehension to replace filter(lambda)

requirements.txt
As recommended at https://pyup.io/account/repos/github/cclauss/openlibrary/
=> requirements.txt: Upgrade Jinja to fix security flaw

requirements.txt
Remove the only instance of the text __anyjson__ in the entire repo: https://github.com/internetarchive/openlibrary/search?q=anyjson
Related to #1129
=> requirements.txt: Remove the unused anyjson

requirements.txt
Remove the only instance of the text __amqplib__ in the entire repo: https://github.com/internetarchive/openlibrary/search?q=amqplib
Related to #1129
=> requirements.txt: Remove the unused amqplib

scripts/2011/03/sample_bulkwrite.py
Without this change the code is a syntax error.
=> Add missing closing brace in list comprehension

openlibrary/templates/subjects/index.html, package.json, static/css/base/helpers-common.less, static/css/components/link-box.less, static/css/layout/v2.less, static/css/legacy.less
Fixes the issues we are seeing with broken subject pages.
=> Subject index

.eslintrc.json, openlibrary/plugins/openlibrary/js/jquery.repeat.js
Protect against this again with an eslint rule
=> No console.log statements!

openlibrary/core/processors/readableurls.py, openlibrary/templates/type/author/view.html, static/css/components/Tools--tablet.less, static/css/components/dropper.less
* Disable ratings on authors page
* Simplify HTML of the rating container
* Generalise some dropper styles and remove some styles
Closes #1658
=> Fix ups to the author page

openlibrary/templates/subjects.html
Fix ReferenceError
Fixes: #1650
=> Remove parseHash/handle_ebook code

openlibrary/templates/type/user/view.html
The page is v2 so jQuery is not available in inline javascript
Fixes: #1614
=> Address reference error on people pages

openlibrary/plugins/openlibrary/code.py
=> Return true if no user-agent is set

docker/README.md
=> Removed TODO section from docker instructions

requirements_common.txt
https://github.com/benjaminp/six/blob/master/CHANGES
=> requirements_common.txt: Upgrade to six==1.12.0

openlibrary/plugins/openlibrary/js/ol.analytics.js, openlibrary/plugins/openlibrary/js/ol.js, openlibrary/templates/site/footer.html
hotfix + refactor for broken current user analytics 
Not 100% sure the ordering of analytics js dependency are correct, but can't be more broken than they were; will test on prod
=> fixing + refactoring analytics, banner stats

openlibrary/macros/LoanStatus.html
hotfix Closes #1235
straight-forward
https://dev.openlibrary.org/books/OL9493025M/Jeff_Bezos
=> turning no ebook available into btn

openlibrary/templates/covers/saved.html
hotfix
moves jquery on load to window.q.push
add bookcover on dev and click "Finished" btn
=> fixes finished button on bookcover change

static/css/components/Tools.less
=> prevents wordbreaks in buy options

docker/README.md
Adds a title for clarity so that it's clear what linux users should skim over in the instructions.
Read the markdown
=> Add Docker Title Line for Clarity

openlibrary/plugins/openlibrary/js/automatic.js, openlibrary/templates/site/body.html, static/css/components/flash-messages.less, static/css/js-all.less, static/css/legacy.less
=> Make flash messages show on v2 pages

Makefile, openlibrary/macros/LoanStatus.html, openlibrary/macros/databarWork.html, openlibrary/templates/type/edition/view.html, package.json, static/css/base/common.less, static/css/base/dl.less, static/css/base/headings.less, static/css/components/Tools--tablet.less, static/css/components/Tools.less, static/css/components/buttonBtn.less, static/css/components/buttonCta.less, static/css/components/link-box.less, static/css/components/listLists.less, static/css/components/navEdition.less, static/css/components/read-panel.less, static/css/components/readerStats.less, static/css/components/shareLinks.less, static/css/components/work--tablet.less, static/css/components/work.less, static/css/layout/index.less, static/css/legacy.less, static/css/page-book.less
Fixes: #1313 
but please review #1731 first!
=> Books CSS is cut from 30+kb to less than 7kb.

static/css/legacy.less
According to the issue #1726 the page is made responsive to tablets.
Hope this fixes the issue. Please let me know if there is some error.
Closes #1726
=> Make responsive webpage

openlibrary/core/lending.py
Closes #1761 
Not the best solution, it swallows other AttributeErrors which we might want to catch
https://dev.openlibrary.org/books/OL24239956M/Harry_Potter_and_the_Sorcerer's_Stone
=> prevent author cache fails from impacting UX

openlibrary/macros/LoanStatus.html, static/css/components/read-panel.less, static/css/components/ui-tabs.less, static/css/js-all.less, static/css/legacy.less
Make http://localhost:8080/books/OL10031082M/UK_Continental_Shelf_Oil_Well_Records look like https://openlibrary.org/books/OL10031082M/UK_Continental_Shelf_Oil_Well_Records
=> Books fixups

openlibrary/plugins/openlibrary/js/availability.js, static/css/components/mybooks-list.less, static/css/components/mybooks-menu.less, static/css/components/mybooks.less, static/css/components/searchResultItemCta.less, static/css/legacy.less
=> Optimise /account/books/want-to-read for mobile and cleanup some CSS while at it

static/css/components/illustration.less
=> centering missing bookcover border on mobile

openlibrary/macros/LoanStatus.html, static/css/base/helpers-misc.less, static/css/components/read-panel.less, static/css/components/work.less
Closes #1788
https://dev.openlibrary.org/books/OL26425541M/The_make-ahead_cook
=> fixed unwaitlist button, strong display block, and h3 sizes

.eslintrc.json, openlibrary/plugins/openlibrary/js/account.js, openlibrary/plugins/openlibrary/js/add_new_field.js, openlibrary/plugins/openlibrary/js/automatic.js, openlibrary/plugins/openlibrary/js/bookreader_direct.js, openlibrary/plugins/openlibrary/js/jquery.others.js, openlibrary/plugins/openlibrary/js/jquery.repeat.js, openlibrary/plugins/openlibrary/js/loadStyle.js, openlibrary/plugins/openlibrary/js/ol.analytics.js, openlibrary/plugins/openlibrary/js/ol.js, openlibrary/plugins/openlibrary/js/subjects.js, openlibrary/plugins/openlibrary/js/utils.js, openlibrary/plugins/openlibrary/js/validate.js
=> Consistent indents in our JavaScript

static/css/components/dropper.less
=> Add list widget shouldn't overlap lists

static/css/base/common.less
latest donation banner is not full width, this PR fixes width by adding a rule to common.less
=> fixing donations banner

docker/Dockerfile.oldev, scripts/dev-instance/create-dev-db-pgdump.sh, scripts/dev-instance/dev_db.pg_dump
**Description**: Rename 'vagrant' db user to 'openlibrary' [refactor]
Progress towards #1134
=> Rename 'vagrant' db user to 'openlibrary'

openlibrary/templates/lib/nav_head.html, static/css/base/common.less, static/css/components/header-bar--desktop.less, static/css/components/header-bar--tablet.less, static/css/components/header-bar.less
Testing if this resolves issues on dev
Reverts internetarchive/openlibrary#1794
=> Revert "Header-bar class to avoid donate banner hack"

openlibrary/templates/type/edition/view.html, static/css/components/buttonCta.less, static/css/components/read-panel.less, static/css/components/work.less
feature adds IA/OL ids sync button and admin bar to editions page
=> adds ia/ol sync options to admin editions page

openlibrary/templates/lib/nav_foot.html
Closes #1780 
Nothing special
Verify the link to "Report A Problem" (previously "Contact and Support") points to current url path.
=> [fix #1780]

static/css/components/buttonLink.less, static/css/layout/index.less
=> Fix edit button alignment on mobile and desktop

openlibrary/plugins/openlibrary/js/availability.js, openlibrary/plugins/openlibrary/js/subjects.js
Follow up to 0f9030c10
Without this btn's do not behave or look as they should do
Closes #
=> Availability buttons should be cta-btn's as well

openlibrary/templates/search/publishers.html
Closes #1836 
Similar to #1821 for publishers search
=> (hotfix/#1836): Fix publishers search render

openlibrary/plugins/openlibrary/js/ol.js
Instead of emptying the results before doing a search, apply an opacity
and empty them just before rendering the results.
Since search is asynchronous this is much less jarring to the user.
Also, clicking anywhere outside the search should close it.
Additional changes:
* Replace deprecated $.ready with $(fn)
* DRY up some CSS selectors so they are only located once
* Update the selector for the search input so it does not apply
to other inputs such as the submit button.
Closes #
> **Evidence**: If this PR touches UI, please post evidence (screenshot) of it behaving …
=> Improve search user experience - Searching should be less jarring

openlibrary/templates/account/books.html
=> OpenGraph tags on reading logs

openlibrary/templates/books/custom_carousel.html
=> Fix cover URL construction from IA identifiers

openlibrary/templates/books/edition-sort.html, static/css/legacy.less
Followup to #1111 -- adds library.link to works page
=> add library.link to works pages

openlibrary/templates/work_search.html
> **Description**: What does this PR achieve? [hotfix]
Tidies up the search page
http://0.0.0.0:8080/search
=> Tidy search page

openlibrary/plugins/openlibrary/js/autocomplete.js, openlibrary/plugins/openlibrary/js/availability.js, openlibrary/plugins/openlibrary/js/bookreader_direct.js, openlibrary/plugins/openlibrary/js/jquery.repeat.js, openlibrary/plugins/openlibrary/js/ol.js, openlibrary/templates/lib/analytics.html, openlibrary/templates/lists/widget.html
> **Description**: What does this PR achieve?
Please fix all instances in:
* openlibrary/plugins/
* openlibrary/templates/
Closes #1851
=> Update all occurrences of jquery .live() method /templates and /plugins

openlibrary/macros/FulltextResults.html, openlibrary/plugins/openlibrary/js/availability.js, openlibrary/templates/books/check.html, openlibrary/templates/search/editions.html, openlibrary/templates/search/lists.html, openlibrary/templates/type/author/view.html, openlibrary/templates/type/list/embed.html, openlibrary/templates/type/list/view.html, openlibrary/templates/type/work/editions.html, static/css/components/search-result-item.less, static/css/components/searchResultItemCta.less
hotfix for searchresults component
=> fixing searchresult component adding list-books style

openlibrary/plugins/openlibrary/js/autocomplete.js, openlibrary/plugins/openlibrary/js/availability.js, openlibrary/plugins/openlibrary/js/bookreader_direct.js, openlibrary/plugins/openlibrary/js/jquery.repeat.js, openlibrary/plugins/openlibrary/js/ol.js, openlibrary/templates/lib/analytics.html, openlibrary/templates/lists/widget.html
Testing whether this fixes the issues on dev
Reverts internetarchive/openlibrary#1867
=> Revert "Update all occurrences of jquery .live() method /templates and /plugins"

openlibrary/plugins/openlibrary/js/autocomplete.js, openlibrary/plugins/openlibrary/js/availability.js, openlibrary/plugins/openlibrary/js/bookreader_direct.js, openlibrary/plugins/openlibrary/js/jquery.repeat.js, openlibrary/plugins/openlibrary/js/ol.js, openlibrary/templates/books/edit/edition.html
=> migrating jquery from using live to on

openlibrary/plugins/openlibrary/js/availability.js, openlibrary/templates/books/edit/edition.html, static/css/components/buttonCta.less, static/css/components/form.olform.less, static/css/components/search-result-item.less, static/css/legacy-wmd.less, static/css/legacy.less
=> fixing availability btn style names in availability.js

openlibrary/templates/messages.html
=> follwup to #1831, adding back necessary template

openlibrary/templates/messages.html
Documentation follow up to 729fa08e4ca0b02e7da2366483e6588b64661e53
Closes #
=> Explain how messages template is being used

static/css/components/merge-form.less, static/css/legacy.less
- Document another component
- Make it responsive so it is usable on mobile
- Reduce some specificity on selectors
=> Component: Merge form

.stylelintrc.json, static/css/base/dl.less, static/css/legacy.less, static/css/less/font-families.less
feature:- Add linting rule for consistent string quotes
Closes #1498 
This may give merge conflicts. Those need to be resolved by converting single quotes to double.
=> Add linting rule for consistent double quotes and fix the offenders

conf/openlibrary.yml
Small change to remove an duplicate entry I noticed while checking something else
=> remove dupe dev feature, and alpha-sort the rest

openlibrary/core/lending.py, openlibrary/macros/RelatedWorksCarousel.html
=> forwarding client info to elastic search for QoS

openlibrary/core/lending.py, openlibrary/macros/AvailabilityButton.html, openlibrary/macros/LoanStatus.html, openlibrary/macros/daisy.html, openlibrary/plugins/worksearch/subjects.py, openlibrary/templates/subjects.html
Our subject page is super broken. Availability faceting is wring. There's no lazy loading. This to be combined with @tabshaikh's #1871
=> Fixing subjects carousels, adds correct availability to API

openlibrary/templates/covers/change.html
Fixes js problem of multiple form upload.
To solve the problem the content was cleared before adding new content.
Closes #1911 
n/a
Needs testing 
Earlier:
Earlier each time on reopening the modal after closing, a new set of form was added.
Now:
=> Fix multiple forms issue (#1911) in image upload

openlibrary/plugins/openlibrary/js/ol.js
Closes #1961 by re-applying @ShreyashApp's solution from #1967 
Correct solution was https://github.com/internetarchive/openlibrary/pull/1967/files
Regressed by https://github.com/internetarchive/openlibrary/pull/1983/files#diff-646b5f5368729e8810166d209c25e50dL258
=> re: issue #1961, re-applies #1967, accidentally undone by #1983

openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/js/ol.js, openlibrary/templates/lists/widget.html, static/css/components/cbox.less
Fix display, UI and functionality of the "add to list" feature.
=> Colorboxlists

static/css/components/buttonCta--js.less, static/css/components/cbox.less, static/css/components/flash-messages.less, static/css/components/jquery.autocomplete.less, static/css/components/ui-tabs.less, static/css/legacy-datatables.less, static/css/less/index.less, static/css/lib/slick-theme.css
- Remove a broken URL
- Remove an invalid line of CSS with an empty URL
- Make all import paths relative
This is all needed to load this CSS inside Webpack
(see 7f1bfb33c) and an added benefit of doing so!
Closes #
=> Correct import paths

openlibrary/plugins/openlibrary/js/ol.js, static/css/components/dropper.less
> **Description**: What does this PR achieve? [feature]
Closes #1147
=> Show dropdown only when javascript is enabled

openlibrary/plugins/openlibrary/js/ol.js, static/css/components/dropper.less
Fixes #2008 by  undoing 37f7273
=> undoes 37f7273 to unhide list button after list creation

openlibrary/templates/books/edit/edition.html, package.json, static/css/components/form.olform.less, static/css/legacy.less
Fixes: #2019 in the year 2019
Closes #
=> Restore columns to edit page (Desktop)

openlibrary/core/lending.py, openlibrary/plugins/openlibrary/js/carousels.js, openlibrary/templates/books/custom_carousel.html, openlibrary/templates/subjects.html, package.json, static/css/page-subject.less
=> Lazy-Loading Carousels & Subject Pages

openlibrary/core/lending.py, openlibrary/plugins/openlibrary/api.py
=> Expose ia carousel code as /browse.json api

openlibrary/plugins/openlibrary/home.py
Closes #1553 
We'll want to test this on local and dev and get @hornc's approval that it's behaving correctly on dev (seeing occasional traceback messages which I'd like another pair of eyes on)
I was seeing ~300ms load-time
=> Caching homepage to decrease TTFB

.github/ISSUE_TEMPLATE/bug_report.md
The labels for these shouldn't be HTML comments; converted to bullet points
=> Make details in bug report template bullet points

Makefile, scripts/copydocs.py, scripts/tests/test_copydocs.py
Feature; adds ability to import past versions of documents from openlibrary.
Closes #2120
I added some tests :)
=> Copydocs now accepts keys with ?v parameter

static/css/components/cbox.less
Hotfix 1) followup to @shreyansh23's modal fixes in #1973
=> Modal Cleanup

CONTRIBUTING.md
Adds PR/CR policy to contributing.md (as discussed on slack).
=> Add PR/CR policy

openlibrary/macros/StarRatings.html
Fixes a typo -- hopefully this is just cosmetic @mekarpeles ?
=> fix typo in ratings macro html

openlibrary/macros/databarAuthor.html, openlibrary/templates/lists/lists.html, openlibrary/templates/type/list/view.html, static/css/components/cbox.less, static/css/components/dropper.less, static/css/components/ui-dialog.less, static/css/legacy-jquery-ui.less
Followup on #2200 and Closes #2176
=> fixes colors from rm from list modal + background overlay

static/css/components/cbox.less
=> makes modal dropshadow black, not beige

package.json, static/css/base/common.less
hotfix
This pr fixes the unintended list-style which shows up on the main nav
=> Fix for unintended list-style showing up in main nav of master-sponsorship

openlibrary/core/sponsorships.py, openlibrary/plugins/upstream/account.py, openlibrary/templates/account/books.html, package.json, static/css/base/common.less
feature
Closes #2196 #2197 #2198
Updates #2168 
Implemented fake civicrm to show editions. Url is account/books/sponsorships
=> My sponsorship page added 

openlibrary/tests/catalog/test_utils.py
Relates to #756  adding tests to clarify what gives us good matches and to identify holes.
=> add tests for author date matching

openlibrary/core/vendors.py, openlibrary/plugins/openlibrary/api.py
* Closes #2037 feature
* also closes #1807 by now handling multiple product responses from the API, which was the cause of this issue.
=> Import by ASIN

openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/js/jquery.repeat.js, package.json, tests/unit/js/html-test-data.js, tests/unit/js/test.jquery.repeat.js
Fixes #2026
The jQuery repeat issue was made easy thanks to @cdrini  excellent replication step - a test is written capturing these and a fix makes it pass.
Coverage slowly creaks forward.
Closes #2026
Is in the patch :)
I don't want to rely on screenshots here. Please pull down the patch and follow the replication steps in both tickets. A screenshot won't help you test this :)
=> Add tests, fix jquery repeat (#2026)

openlibrary/macros/LoanStatus.html, openlibrary/plugins/openlibrary/js/ol.js
feature
Updates #2166
Archive.org direct flow created according to figma diagram https://www.figma.com/file/Oh1CZQOx5JZSzVIbSigbRy59/Book-Sponsorship-Modal?node-id=80%3A242 and parameters passed to archive.org/donate with url like this https://archive.org/donate?context=ol&userid=$(user_id)&campaign=pilot&type=book-sponsorship&isbn=$(isbn)
=> Archive direct flow created and parameters passed to archive.org/donate page

.eslintrc.json, openlibrary/plugins/openlibrary/js/account.js, openlibrary/plugins/openlibrary/js/add_new_field.js, openlibrary/plugins/openlibrary/js/autocomplete.js, openlibrary/plugins/openlibrary/js/automatic.js, openlibrary/plugins/openlibrary/js/availability.js, openlibrary/plugins/openlibrary/js/bookreader_direct.js, openlibrary/plugins/openlibrary/js/carousels.js, openlibrary/plugins/openlibrary/js/i18n.js, openlibrary/plugins/openlibrary/js/jquery.repeat.js, openlibrary/plugins/openlibrary/js/jsdef.js, openlibrary/plugins/openlibrary/js/ol.js, openlibrary/plugins/openlibrary/js/python.js, openlibrary/plugins/openlibrary/js/subjects.js, openlibrary/plugins/openlibrary/js/template.js, openlibrary/plugins/openlibrary/js/utils.js, openlibrary/plugins/openlibrary/js/validate.js, tests/unit/js/test.jquery.repeat.js
Programmatically make our quote usage in JavaScript consistent 
Closes #2085
=> Consistency quoting 

openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/js/subjects.js, openlibrary/plugins/openlibrary/js/utils.js, openlibrary/templates/books/edit/excerpts.html, tests/unit/js/test.subjects.js
Important: Please review  and merge #2224 before this one!!
2507cfa expands on @koderjokers work making some minor adjustments so we repeat the benefits of her tests!
=> Add koderjoker's subjects tests

.eslintrc.json, openlibrary/plugins/openlibrary/js/account.js, openlibrary/plugins/openlibrary/js/add_new_field.js, openlibrary/plugins/openlibrary/js/autocomplete.js, openlibrary/plugins/openlibrary/js/availability.js, openlibrary/plugins/openlibrary/js/bookreader_direct.js, openlibrary/plugins/openlibrary/js/carousels.js, openlibrary/plugins/openlibrary/js/jquery.repeat.js, openlibrary/plugins/openlibrary/js/ol.js, openlibrary/plugins/openlibrary/js/plot.js, openlibrary/plugins/openlibrary/js/subjects.js, openlibrary/plugins/openlibrary/js/template.js, openlibrary/plugins/openlibrary/js/utils.js, openlibrary/plugins/openlibrary/js/validate.js, package-lock.json, package.json
Fixes https://github.com/internetarchive/openlibrary/issues/2244.
Added a `template-curly-spacing: error` rule. You can't have `never`. This PR has fixes for the exposed issues as well.
Running `./node_modules/.bin/eslint openlibrary/plugins/openlibrary/js/ --fix` should do.
Above.
=> Adding eslint template-curly-spacing never rule

.travis.yml
=> Travis CI: Start testing on dist: bionic in allow_failures mode

openlibrary/templates/type/author/edit.html
=> Apply book edit styles to author edit styles

openlibrary/core/sponsorships.py, openlibrary/macros/LoanStatus.html
- Fixes policy-check (bwb price + work-level availability)
- moves policy-check to its own function
=> fixes availability, moves policy check to sponsorship method

openlibrary/core/bookshelves.py, openlibrary/plugins/upstream/account.py, openlibrary/templates/account/books.html
Closes #1740 
Builds on the ideas of #2272 (closing)
=> Fixing 1740 with tabish, adding pagination

openlibrary/plugins/upstream/code.py, openlibrary/templates/viewpage.html
[hotfix|fix]
Fixes https://github.com/internetarchive/openlibrary/issues/2217.
Have added revert access for librarians exposing proper checks
Please find librarian user image below.
=> Add revert access for librarians

.travis.yml
As discussed at https://github.com/internetarchive/openlibrary/issues/2268#issuecomment-520668700
=> Travis CI: Remove allow_failures on Python 2.7 on bionic

package.json
webpack watch watches changes to files meaning it's quicker to
make modifications and test the JavaScript
Closes #
=> Add a npm command for quicker development

openlibrary/templates/type/author/view.html
Fixes: #2248
@hornc note I haven't tested this but hopefully this will address the issue you are seeing!
=> Allow hide/reveal on merge controls

openlibrary/macros/LoanStatus.html
feature
Updates #2306 
tracking the number of clicks on the sponsorship button
=> Add tracking to the sponsorship button

openlibrary/macros/LoanStatus.html, openlibrary/plugins/upstream/account.py
Hotfix for civicrm to work on localhost and valid book sponsorship learn more link 
Updates @tabshaikh's PRs #2337 and #2336 
Fixes #2265 #2211
=> fixing learn more link, fixing civicrm mock endpoint

openlibrary/plugins/admin/code.py, static/css/components/buttonCta.less, static/css/page-admin.less
=> removing deprecated /admin/services endpoint

openlibrary/macros/AvailabilityButton.html, openlibrary/macros/BookPreview.html, openlibrary/macros/DownloadOptions.html, openlibrary/macros/LoanStatus.html, openlibrary/macros/WorldcatLink.html, openlibrary/macros/daisy.html, openlibrary/macros/databarWork.html, openlibrary/plugins/openlibrary/js/ol.js, openlibrary/templates/books/edit.html, openlibrary/templates/books/edition-sort.html, openlibrary/templates/covers/change.html, package.json, static/css/components/buttonCta.less, static/css/components/cbox.less, static/css/components/preview.less, static/css/components/read-panel.less, static/css/legacy.less, static/css/page-plain.less
=> Adding IA ebook preview button

Readme.md
Fixed Typography in Readme.md. **Removed Colon**
=> Fixed Typography in Readme.md: Removed Colon

package.json
=> update less size limits

setup.py
A simple change to improve PEP8 compliance.  Replaces #2407 which got into a bad git state.
=> Remove wildcard (*) imports for PEP8 (again)

.eslintrc.json, openlibrary/plugins/openlibrary/js/autocomplete.js, openlibrary/plugins/openlibrary/js/automatic.js, openlibrary/plugins/openlibrary/js/availability.js, openlibrary/plugins/openlibrary/js/bookreader_direct.js, openlibrary/plugins/openlibrary/js/carousel/Carousel.js, openlibrary/plugins/openlibrary/js/editions-table/index.js, openlibrary/plugins/openlibrary/js/jquery.repeat.js, openlibrary/plugins/openlibrary/js/ol.analytics.js, openlibrary/plugins/openlibrary/js/ol.js, openlibrary/plugins/openlibrary/js/subjects.js, openlibrary/plugins/openlibrary/js/utils.js, tests/unit/js/test.jquery.repeat.js, webpack.config.js
1. Add eslint rule quote-props = as-needed
2. Fix any offenders detected
Closes #2323
=> Consistency: eslint quote-props as-needed

openlibrary/plugins/openlibrary/js/graphs/plot.js
=> fixing js lint issues

package.json
Noticed while reviewing #2323
Closes #
=> Tooling: npm run lint:fix should fix eslinting as well

openlibrary/core/vendors.py, openlibrary/tests/core/test_vendors.py
=> split amazon title into title + subtitle and remove parens

openlibrary/macros/AffiliateLinks.html, openlibrary/macros/WorldcatLink.html, openlibrary/macros/daisy.html, openlibrary/macros/databarWork.html, openlibrary/plugins/upstream/models.py, openlibrary/templates/books/edition-sort.html, static/css/components/read-panel.less, static/css/legacy-tools.less
- Adds "includes shipping" message for betterworldbooks
- cleans up sidebar macros
- shows a link to betterworldbooks title search (if no isbn available for pricing)
- shows buy options on works table
- fixes discovered broken isbn for buy option + local libraries
=> Improve Buy Options UI + BWB markup

openlibrary/core/sponsorships.py, package.json, static/css/components/buttonCta.less
Closes #2267 
We still need some way @hornc to make it so partners don't give us duplicate books of those we've sponsored
=> incorporates promises, sponsorships in dwwi decision

openlibrary/accounts/__init__.py, openlibrary/core/models.py, openlibrary/core/vendors.py, openlibrary/plugins/openlibrary/api.py
Merging into sponsor-waitlist on origin
=> Sponsor waitlist cr

openlibrary/accounts/__init__.py, openlibrary/core/models.py, openlibrary/core/vendors.py, openlibrary/macros/EnrollUsergroup.html, openlibrary/plugins/openlibrary/api.py
Closes #116 (again) for sponsorship
feature
This PR DRYs out privilege escalation (i.e. the ability to change users to e.g. `ImportBot` to run a function) and in particular DRYs / generalizes the existing `/isbn/{isbn}` endpoint as well as introduces logic to add a user to a usergroup as the user `archive_support`.
1. Test that book imports via amazon are not broken by going to Amazon new releases (https://www.amazon.com/gp/new-releases/books/), find a book which is not yet on Open Library and use the https://dev.openlibrary.org/isbn/{isbn} API to import it. Success will show the book imported by `ImportBot` and the user should appear to remain logged in as themselves (or not logged in). Since there are two paths (not logged in, logged in) both should be tested to ensure e.g. the user is …
=> ability to add patron to usergroup/sponsor-waitlist as archive_support

docker/README.md
=> Mention support for Docker 19.* and mention small size of dev database

openlibrary/plugins/openlibrary/js/account.js, openlibrary/plugins/openlibrary/js/index.js, openlibrary/templates/account/email.html, openlibrary/templates/account/password.html
Run validatePassword() and validateEmail unconditionally and drop the globals.
The code is already there but needs to be modified so it returns early if the elements are not there.
Then shift from the HTML into the JS entry point. Two more script tags down.. hurrah.
Closes #
=> Run validate functions unconditionally on all pages

openlibrary/core/civicrm.py, openlibrary/core/models.py, openlibrary/core/sponsorships.py, openlibrary/macros/LoanStatus.html, openlibrary/plugins/upstream/account.py, openlibrary/templates/account/books.html, openlibrary/utils/isbn.py, static/css/base/common.less, static/css/components/buttonCta.less, static/css/less/colors.less
=> Master sponsorship cr

openlibrary/core/sponsorships.py
Prefers amazon book length over openlibrary for better protection and accuracy
=> pull page count from amz first, since ol data can be changed

openlibrary/core/sponsorships.py
Updates eligibility API to ensure isbn13 always available to petabox
=> adding isbn to eligibility

openlibrary/templates/type/about/view.html
Closes #2463 
removed div contentQuarter and changed other element from contentQuarter to contentHalf
=> removed unused div contentQuarter

openlibrary/core/sponsorships.py, openlibrary/tests/core/test_sponsors.py
hotfix for unexpectedly no longer working config_ia_domain variable. infogami related???
=> hotfix on sponsorship config

openlibrary/templates/history.html
Closes #2279 
refactor
Another compare button is added on top of history
=> Added compare button on history page

static/css/components/editions.less
=> fixes the audio button size on work editions table

openlibrary/plugins/openlibrary/js/availability.js, tests/unit/js/test.availability.js
Fixes: #2177
This is untested as I couldn't setup Docker (purely test driven development). Please verify this fix solves the issue. If not feed back to me and I'll take a closer look at next available opportunity!
The test passes and didn't before I wrote it :)
=> getAvailability function should take into account query string in URL

openlibrary/templates/lists/widget.html, openlibrary/templates/type/edition/view.html, static/css/components/dropper.less, static/css/components/work.less
Follow ups to #2586 
While reviewing #2586 I noticed some design inconsistencies on mobile and code we can remove!
cc @mekarpeles 
Before:
After:
Visit the local url equivalent of https://openlibrary.org/books/OL25930651M/The_Three-Body_Problem
=> Consistency of borrow and want to read buttons on mobile on books page

Readme.md, docker/README.md
This is my attempt at improving the README for first-time contributors (being one myself), and I'm open for feedback.
When trying to setup the development library I had quite a few problems, which stemmed from the fact that I ignored the recommendation of using docker, thinking I could easily set it up myself.
The problem is, the linked wiki article is completely outdated, with the setup.py commands not working [due to being removed over 4 years ago](https://github.com/internetarchive/openlibrary/commit/88ea3e4b8d794e688e637b2088757671d70372f4). I also didn't find any concise description of how any solr or memcached instance would have to be setup, and the Backend Guide allready assumes you are using docker.
**In conclusion:** there is no way I can easily get this running without docker, …
=> Improve README for first-time contributors

openlibrary/catalog/onix/parse.py
=> likely dead code, but fixing typo

.travis.yml, requirements_common.txt
=> Travis CI: Upgrade from Python 3.7 to 3.8

requirements_common.txt
Matches internetarchive/infogami#54
=> requirements_common.txt: Upgrade web.py only on Python 3

static/css/legacy.less, static/css/less/colors.less
Refactor: Remove some dead css; we recently remove the flickr thing, and there's no reference to flickr anywhere.
@jdlrobson
=> refactor: remove dead flickr css

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
Improve templates based on discussion during community call (see https://docs.google.com/document/d/16eAABOSLrmCbOkRbwVXzis2x4dz2gEQWJsXK-crDCqg/edit?pli=1#heading=h.8rgom57i8pkn ):
- add "Steps to reproduce" section to bug template
- add "Related files" section to bug template (to make it easier for new contributors)
- add stakeholders section to all templates
@guyjeangilles @hornc
=> Improve issue/PR templates

requirements_test.txt
=> requirements_test.txt: Upgrade our testing tools

Makefile, docker/Dockerfile.olbase, package-lock.json, package.json
It's a long time coming! Let's do the simplest possible thing but don't use outdated and unsupported dependencies so we don't see those pesky deprecation notices.
This will require another global install, so I've added that to the Makefile for next deployment.
Fixes: #1123
=> Long term solution to CSS minification

requirements.txt
Updating requirements.txt to remove broken dependency (rebuilt python dependencies on dev while deploying)
=> updating requirements.txt, removing broken dependency

openlibrary/i18n/es/messages.po
Fixed misspellings and some translations.
Closes #
=> Updated Spanish translation

openlibrary/plugins/upstream/account.py
=> rm vagrant text

openlibrary/core/sponsorships.py
instead send an empty array
Fixes: #2731
Closes #
=> If sponsorship available do not throw exception

openlibrary/plugins/openlibrary/pages/config_edition.page
=> remove LCCN from classifications config

openlibrary/templates/books/edition-sort.html
=> Fix read button not showing listen button

openlibrary/core/processors/readableurls.py
=> adding exclusion processor

conf/nginx/sites-available/openlibrary.conf
=> rm deprecated vagrant mention

openlibrary/plugins/openlibrary/js/availability.js
=> slimmed down hotfix of #2767

openlibrary/i18n/es/messages.po
Fixed some typos in the Spanish translation.
=> Fixed some typos in Spanish translation

openlibrary/i18n/de/messages.po
In the current state of the website and the mass of missing strings, I am not sure whether it is even sensible to merge new translations, but here it is.
=> German translation

.travis.yml
=> Travis CI: vendor/acs4_py is ready for Python 3

openlibrary/utils/__init__.py, openlibrary/utils/compress.py, openlibrary/utils/olcompress.py, openlibrary/utils/olmemcache.py
=> from six.moves.urllib.parse import quote_plus

openlibrary/catalog/marc/get_subjects.py, openlibrary/catalog/marc/parse.py, openlibrary/catalog/marc/tests/test_data/bin_expect/histoirereligieu05cr_meta.mrc, openlibrary/catalog/marc/tests/test_data/bin_expect/wwu_51323556, openlibrary/catalog/marc/tests/test_data/xml_expect/nybc200247_marc.xml, openlibrary/catalog/marc/tests/test_data/xml_expect/soilsurveyrepor00statgoog_marc.xml, openlibrary/catalog/marc/tests/test_parse.py
=> Don't import MARC local notes

docker/README.md
No specific issue, just documentation update
refactor of docker/README.md
This PR simply adds an "Updating the Docker Image" section to the docker README.
Cmd to rebuild the static assets after a developer has done ```git pull```
=> update docker README: how to update docker image after git pull

openlibrary/coverstore/code.py, openlibrary/coverstore/coverlib.py
=> from openlibrary.coverstore import config, db

openlibrary/api.py, openlibrary/plugins/oltemplates/olmanage.py
=> Py3: from six.moves.configparser import ConfigParser

openlibrary/utils/compress.py
These changes were originally landed in #2868 but those changes were lost in a subsequent PR.
Closes #2868
=> Re-update compress.py for Python 3

openlibrary/core/vendors.py, openlibrary/tests/core/test_vendors.py
Closes #2312 
New unit test added.
=> Only add ASIN identifier if it is not the ISBN

.travis.yml, openlibrary/catalog/marc/marc_xml.py
=> Python3 fixes in pytest order again

.travis.yml, Makefile
Remove unneeded comments and commands related to Python 3.
Closes #
=> Travis CI: Remove unneeded comments and commands

openlibrary/catalog/merge/names.py, openlibrary/core/init.py, openlibrary/core/inlibrary.py, openlibrary/core/olmarkdown.py
Four more absolute imports to close pytests failures on Python 3.
```
_____________ ERROR collecting openlibrary/tests/core/test_init.py _____________
ImportError while importing test module '/home/travis/build/internetarchive/openlibrary/openlibrary/tests/core/test_init.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
openlibrary/tests/core/test_init.py:3: in <module>
from openlibrary.core.init import Init
openlibrary/core/init.py:17: in <module>
import formats
E   ModuleNotFoundError: No module named 'formats'
__________ ERROR collecting openlibrary/tests/core/test_olmarkdown.py __________
ImportError while importing test module '/home/travis/build/internetarchive/openlibrary/openlibrary/tests/core/test_olmarkdown.py'.
Hint: make sure your test …
```
=> Next Py3 pytest fix: absolute imports for normalize, formats, cache, helpers

openlibrary/i18n/fr/messages.po, openlibrary/i18n/messages.pot
I think this only affected people who were waitlisted and now
have loans which are available for the next few hours, but it's
possible that it was a general problem with the page.
I think this only affects folks who recently came off a waitlist, so I have no affective way of testing it, but at least one problem is fixed by this PR.
@JeffKaplan @cdrini
=> Fix My Loans page i18n for loans which are available.

openlibrary/core/models.py
=> models.py: from openlibrary.core import helpers as h

openlibrary/plugins/upstream/borrow.py, openlibrary/plugins/upstream/utils.py, openlibrary/solr/update_work.py
=> Next Py3 pytest fix: absolute imports for acs4, render_template

openlibrary/plugins/upstream/account.py
=> from openlibrary.plugins.upstream import borrow, forms, utils

openlibrary/plugins/upstream/addbook.py
=> from openlibrary.plugins.upstream import utils

openlibrary/plugins/openlibrary/stats.py
=> import openlibrary.plugins.openlibrary.filters as stats_filters

openlibrary/core/models.py
=> from openlibrary.core.lists.model import ListMixin, Seed

openlibrary/accounts/model.py, openlibrary/core/processors/readableurls.py, openlibrary/plugins/openlibrary/code.py, openlibrary/plugins/search/solr_client.py, openlibrary/plugins/worksearch/searchapi.py
https://github.com/internetarchive/openlibrary/pull/2416#issuecomment-535998852
Closes #
=> web.utf8() -> web.safestr()

openlibrary/plugins/inside/code.py
Closes #3003 
As suggested at https://github.com/internetarchive/openlibrary/pull/3003#discussion_r376822172
Closes #
=> Remove unused imports httplib and urllib

openlibrary/plugins/search/code.py
=> from openlibrary.plugins.search import solr_client, stopword

.travis.yml
As suggested at https://github.com/internetarchive/openlibrary/pull/3024#discussion_r378518574
Closes #
=> Travis CI: Move `make lint` to the script of the lint run

openlibrary/i18n/README.md
Closes #
specific intructions to open translated version of the Open Library website in the browser
@cdrini
=> add instructions to see transl. version in browser

openlibrary/catalog/improve/improve_data.py
=> Typo in variable name: author_keys --> author_key

openlibrary/templates/diff.html
This pr converts the valign property in the html to css vertical align property.
=> html valign prop to css property.

openlibrary/catalog/people/build_object.py
=> Typo in variable name: line --> marc in test_consort()

openlibrary/templates/lib/nav_foot.html
adding /volunteer link to footer
Nothing
N/A
@cdrini @bfalling
=> Add Volunteer link to site footer

requirements_common.txt
https://pypi.org/project/pymarc
Release notes: https://gitlab.com/pymarc/pymarc/-/tags
Closes #
=> requirements-common.txt: Upgrade pymarc

openlibrary/core/sponsorships.py
Closes #3114 
added 'scope':'all' for sponsorship
@mekarpeles
=> added scope:all for sponsorship

openlibrary/core/lending.py, openlibrary/core/vendors.py, openlibrary/plugins/upstream/borrow.py, requirements_common.txt
Closes #2908 
refactors amz paapi 4.0 -> 5.0 API
~XXX Uses a modified version of https://github.com/sergioteula/python-amazon-paapi5~
Now uses a standard version of this library
@hornc  @cdrini
=> migrating from paapi 4 to 5

openlibrary/core/vendors.py, openlibrary/macros/AffiliateLinks.html
Followup to #3125, hopefully makes books pages faster to load by only asking for price info from amazon API.
=> added faster price-only amz lookup for books pages

openlibrary/core/vendors.py, openlibrary/macros/AffiliateLinks.html
Closes #3092 
Falls back to BWB for amz price (fewer calls to amz for books pages)
tested on dev
@cdrini @hornc
=> where available, use bwb for market price (e.g. amz)

static/robots.txt
=> Allow '/people' in robots.txt

openlibrary/plugins/worksearch/code.py, openlibrary/utils/__init__.py, openlibrary/utils/tests/test_utils.py
Closes #2487 ; this was blocking #1067 , since it seems like the new solr is also affected by this issue.
- Next step would be to switch to requests, or maybe to use solr_client or something; but that can be done in a future PR.
- ✅ Tested title search: https://dev.openlibrary.org/search?q=title%3A+%22harry+potter%22&mode=everything
- ✅ All search: https://dev.openlibrary.org/search?q=sun+is+also+a+star&mode=everything
- ✅ Search with Unicode in it: https://dev.openlibrary.org/search?q=title%3A+%22am%C3%A9lie%22&mode=everything
- ✅ Search with facet: https://dev.openlibrary.org/search?q=title%3A+%22am%C3%A9lie%22&author_key=OL3300143A&mode=everything
- ✅ Search with multiple types of facets: https://dev.openlibrary.org/search?q=title%3A+%22am%C3%A9lie%22&author_key=OL3300143A&first_publish …
=> Fix solr queries not correctly encoding parameters

openlibrary/api.py, openlibrary/catalog/add_book/__init__.py, openlibrary/catalog/add_book/load_book.py, openlibrary/catalog/amazon/import.py, openlibrary/catalog/amazon/parse.py, openlibrary/catalog/merge/build_db.py, openlibrary/catalog/utils/__init__.py, openlibrary/data/dump.py, openlibrary/data/solr.py, openlibrary/plugins/books/dynlinks.py, openlibrary/plugins/ol_infobase.py, openlibrary/plugins/openlibrary/code.py, openlibrary/plugins/openlibrary/connection.py, openlibrary/plugins/search/solr_client.py, openlibrary/plugins/upstream/merge_authors.py, openlibrary/plugins/worksearch/subjects.py, openlibrary/records/matchers.py, openlibrary/records/tests/conftest.py, openlibrary/records/tests/test_functions.py, openlibrary/solr/update_work.py, openlibrary/templates/lib/history.html, openlibrary/templates/merge/editions2.html, openlibrary/utils/solr.py
Closes 34 failing pytest on Python 3.
=> dict.iteritems() -> dict.items() for Py3 in 24 files

openlibrary/plugins/upstream/models.py, scripts/test-py3.sh
=> Fix plugins/upstream/models.py for Python 3

openlibrary/tests/core/test_cache.py, openlibrary/tests/core/test_helpers.py, openlibrary/tests/core/test_init.py, openlibrary/tests/core/test_models.py, openlibrary/tests/core/test_ratings.py, openlibrary/tests/core/test_sponsors.py, openlibrary/tests/core/test_waitinglist.py
removed unused imports
@cclauss
=> Removed unused imports from openlibrary/test

openlibrary/i18n/fr/messages.po, openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/js/availability.js, openlibrary/templates/type/list/embed.html, openlibrary/templates/type/list/exports.html, openlibrary/templates/type/list/view.html, scripts/i18n-messages
The string extractor wasn't looking at the List type at all,
so this is all new. Also fixes the bugs in #3076
Closes #3076
None of the list functionality was apparently tested last time around, so it should be scrutinized as completely new code.
@mekarpeles
=> Clean up i18n of Lists - fixes #3076

requirements_test.txt, scripts/test-py3.sh
https://docs.pytest.org/en/latest/changelog.html
And restore catalog tests now that #3150 has landed 
Closes #
=> Upgrade pytest and restore catalog tests

openlibrary/catalog/add_book/tests/test_add_book.py, scripts/test-py3.sh
Closes on failing pytest on Python 3
=> Fix test_add_book.py for Python 3

.travis.yml
=> Travis CI: make lint-diff first, not last

openlibrary/plugins/openlibrary/tests/test_stats.py, scripts/test-py3.sh
Closes one pytest on Python 3.
=> Fix test_stats.py for Python 3

package-lock.json, package.json
Closes #2951
- @cclauss tested rebuilding olbase
- Tested running `npm run build-assets`
@cclauss @hornc @jdlrobson
=> Remove node-gyp; looks unused

requirements_common.txt
=> Security update of Pillow to 7.0.0

openlibrary/plugins/openlibrary/js/ol.js
=> removing unneeded hijacking of GET params m=edit, etc

openlibrary/conftest.py, requirements_common.txt
Reverts internetarchive/openlibrary#3241
=> Revert "Upgrade to web.py==0.50"

openlibrary/solr/solrdump.py, openlibrary/tests/accounts/test_models.py
Fix indentation that contains tabs instead of spaces or odd indentation.
=> Fix indentation in two Python files

openlibrary/mocks/mock_ol.py, openlibrary/mocks/tests/test_mock_infobase.py
Removes unused imports from openlibrary/mocks
@cclauss
=> Removed unused imports from /mocks

openlibrary/core/vendors.py
Closes #3195 
hotfix
API throttling is still wonky in this version
try importing a book which doesn't yet exist on OL (either isbn 10 or 13)
http://dev.openlibrary.org/isbn/9781258051372 this title was added
@hornc, @cdrini
=> Fixing /isbn import, publishers and product_group

requirements_common.txt
Several buffer overflow issues resolved...
https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst
Like #3204
Closes #
=> Security update of Pillow to 7.1.1

openlibrary/i18n/fr/messages.po, openlibrary/i18n/messages.pot, openlibrary/macros/AvailabilityButton.html, openlibrary/macros/DownloadOptions.html, openlibrary/macros/LoanStatus.html, openlibrary/templates/account/books.html, openlibrary/templates/account/borrow.html, openlibrary/templates/books/edit.html, openlibrary/templates/books/edition-sort.html, openlibrary/templates/history/comment.html, openlibrary/templates/lib/history.html, openlibrary/templates/lists/header.html, openlibrary/templates/lists/home.html, openlibrary/templates/merge/editions2.html, openlibrary/templates/notfound.html, openlibrary/templates/publishers/notfound.html, openlibrary/templates/publishers/view.html, openlibrary/templates/recentchanges/index.html, openlibrary/templates/search/publishers.html, openlibrary/templates/subjects.html, openlibrary/templates/type/author/view.html, openlibrary/templates/type/edition/view.html, openlibrary/templates/type/work/editions.html, openlibrary/templates/type/work/editions_datatable.html, openlibrary/templates/type/work/view.html, openlibrary/templates/widget.html, openlibrary/templates/work_search.html, scripts/i18n-messages
Includes the following:
* Add parameter names for i18n substitution parameters
* Clean up missing or bad i18n in touched modules
Closes #2998 #849
Blocks #2997 #2936/#3033
@cdrini @dcapillae @elizaLU
=> Clean up first pass i18n

openlibrary/i18n/es/messages.po
Updated Spanish translation after the last changes in i18n files.
=> Update Spanish translation

openlibrary/catalog/utils/__init__.py, requirements_common.txt, scripts/test-py3.sh
Closes #3037  A second attempt at that PR now that the iteritems() and dict.keys() PRs have landed.
Close more pytests on Python 3.
=> The cmp argument again

openlibrary/plugins/worksearch/code.py, openlibrary/templates/work_search.html
Refactor: Remove some dead code in worksearch/code.py . Follow along commit-by-commit for most simplicity
Mostly centralized any constants to the top of the file, and remove unused methods/constants.
=> Prep refactor for adding lcc: and ddc: to search

openlibrary/templates/site/body.html
Currently on prod as a hot-deploy, in response to good feedback from @jessamynwest
Updates Sponsorship banner to k-12 student library.
On prod.
=> Updating banner text to k-12

openlibrary/templates/lib/nav_head.html
refactor of nav bar, especially the browse menu, to contain more options for search & discovery
nav menu items all work
=> updating browse nav menu

openlibrary/i18n/es/messages.po
Closes #
Updated Spanish translation: fixed some typos.
=> Typo fixes on author and other pages

openlibrary/macros/AvailabilityButton.html, openlibrary/macros/LoanStatus.html
Hotfix: Small fixes in i18n
- https://dev.openlibrary.org/books/OL26927016M/I_know_numbers!
@tfmorris
=> Fix i18n: template typo in waitlist buttons

scripts/test-py3.sh
=> test-py3.sh: Let’s look for Python bare exceptions

Readme.md
Added this in: 
After reading the tech and developments for a background on Infogami, the most recent files can be viewed and worked on.
- [Infogami master files](https://github.com/internetarchive/infogami)
=> Was missing the location of the master files that many people ask for in the overview

package.json, static/css/page-user.less
Closes #3287
Markup was added by @cdrini by editing the page.
=> Subject Page changed into columns

static/css/page-user.less
Closes #3287 
[hotfix]: subjects page renders correctly on mobile
@mekarpeles
=> Media queries breakpoint added

openlibrary/templates/books/author-autocomplete.html, openlibrary/templates/books/edit.html, static/css/page-user.less
Solves #1920 With JS disabled delete icons show but are not clickable
> done with the <noscript> part ..and I'm trying to disable the while JS is disabled by using `disabled` attribute...
> my approach is keeping disabled =true as default and using `document.getElementById('author-$i').disabled = false;` in the scripts portion in `author-autocomplete.html` ..
> but when I do so, the input field disappears... Could you please tell me where I'm going wrong?
@jdlrobson
=> disabled delete icons show checkpoint

openlibrary/plugins/admin/code.py
Closes #3445 
n/a simple fix
tested using a librarian / non-admin account
@seabelis
=> let librarians admin staffpicks

openlibrary/core/lending.py
=> lending.py: Deal gracefully with no account

openlibrary/tests/catalog/test_get_ia.py
=> test_get_ia.py: assert url

openlibrary/plugins/upstream/account.py, openlibrary/templates/account/books.html, openlibrary/templates/lib/nav_head.html, openlibrary/templates/type/user/view.html
Closes #3461 
**Redirection:**
/account/books/[^/]* -> /people/user/books/
/account/books -> /people/user
**page/user edited to add manage privacy button**
Visit the /people/user/books page:
Visit the /people/user page:
@mekarpeles
=> Redirecting /account/books/[^/]* to /people/user/books/

bundlesize.config.json, package.json
Closes #2636 ; refactor.
`npx bundlesize` still works :+1:
@jdlrobson
=> Move bundlesize config into own file

openlibrary/templates/site/body.html, static/css/components/page-banner.less
trivial fix, adds banner + message for #3500 followup
=> Adds banner w/ link to lending changes blog

openlibrary/core/ia.py
Updating our import checks to not import from test / debug collections
=> updating collections checks for metadata import

openlibrary/templates/site/body.html
Hotfix: curly quote breaking i18n
Not tested
@mekarpeles
=> Fix curly quote breaking i18n

openlibrary/plugins/upstream/account.py
xauth now returns s3 keys as well so those need to be mocked
Tested logging in on docker
@mekarpeles
=> Fix logging in on docker

openlibrary/plugins/upstream/borrow.py
Fixes unresolved lending issues related to #3500
Switches borrow, return, and waitlists to use @rchrd2's s3 endpoints 
Tested on dev
=> Refactors borrowing, Fixes return button logic

openlibrary/accounts/model.py
=> fixes s3 login flow for openlibrary-client

package-lock.json, package.json
new version of jquery datatable will enable search filtering and changing # page results for #684 
updates npm packages
non visible changes
=> adding new datatable npm pkg

openlibrary/core/lending.py
Remove noise from logs related to this.
=> Avoid making useless network requests when provided with no OCAIDs

openlibrary/templates/lists/widget.html, static/css/legacy-tools.less
=> Fix lists double add/remove requests

openlibrary/plugins/openlibrary/js/carousel/Carousel.js
Closes: https://github.com/internetarchive/openlibrary/issues/2501
@mekarpeles
=> Fixes unnecessary AJAX calls when carousel ends

openlibrary/plugins/admin/code.py, openlibrary/plugins/admin/mem.py, openlibrary/plugins/books/code.py, openlibrary/plugins/books/readlinks.py, openlibrary/plugins/upstream/code.py
Closes #
Do absolute imports to be compatibile with both Python 2 and Python 3.
=> Absolute imports in openlibrary.plugins.admin & books

static/css/layout/index.less
trivial fix, tested on dev, staging on prod.
=> fixing img max-width for infogami

openlibrary/plugins/upstream/code.py, openlibrary/plugins/upstream/covers.py, openlibrary/plugins/upstream/recentchanges.py
Closes #
More absolute imports for Python 3
More absolute imports for Python 3
=> More absolute imports for Python 3

openlibrary/templates/books/custom_carousel.html
=> Fix custom carousel cover url

openlibrary/tests/catalog/test_get_ia.py
=> Typo in assertion output

static/css/components/rating-form.less
Updates: #3561 
Aligned CLEAR RATING button in BOOK'S Page.
@tabshaikh
=> Aligned Clear Rating Button in Book's Page

openlibrary/accounts/model.py, openlibrary/core/lending.py, openlibrary/macros/Pager.html, openlibrary/plugins/worksearch/code.py, openlibrary/utils/solr.py
=> Encoding payloads and using integer division

openlibrary/templates/lists/widget.html
=> Fixed List adding button

static/css/components/work.less
=> Aligning Books in List

.gitmodules, openlibrary/plugins/upstream/tests/test_models.py
Add tests related to #3633
Test some of the unintuitive aspects of Storage, Things, and Works
=> Add /plugins/upstream/tests/test_models.py

openlibrary/plugins/worksearch/code.py
Closes #3613 
What does this PR achieve? refactor
@cdrini
=> Fix Param Mutable Assignment

requirements_test.txt
https://docs.pytest.org/en/latest/changelog.html
=> requirements_test.txt: Upgrade Pytest on Python 3 only

Makefile
Closes #
- ✅ Docker hub build still passes
- ✅ `make git` does something in local image
@cclauss @aasifkhan7
=> Fix make git never running

docker/Dockerfile.oldev, docker/README.md
Closes #
- ✅ `docker-compose build` works
- ✅ `docker-compose up -d` works
@aasifkhan7  @cclauss
=> Switch to using dockerhub for olbase

docker-compose.infogami-local.yml, docker-compose.yml
=> Create docker-compose for infogami local

openlibrary/i18n/es/messages.po, openlibrary/i18n/fr/messages.po, openlibrary/i18n/messages.pot, openlibrary/plugins/upstream/forms.py
Fix; got a request to update this markup from Jenica to be consistent.
Tested English/Spanish both work
@jbuckner
=> Update markup for newsletter checkbox

openlibrary/plugins/openlibrary/js/editions-table/index.js
Closes #3712
Remember the #editions. 
=> Honor the editions settings

conf/openlibrary.yml, openlibrary/core/lending.py
archive.org is deprecating the /beta endpoint
@mekarpeles
=> Switch to non-beta archive loans API

Makefile
=> Add 16 pytests to `make test-py`

conf/openlibrary.yml, openlibrary/plugins/openlibrary/code.py, openlibrary/plugins/openlibrary/sentry.py, requirements_common.txt
Closes #23
Hooks to IA's sentry, and lets us store our error logs there for easy/fast searching/aggregating.
On dev.openlibrary.org  and logging events!
=> Add support for sentry to backend

docker/Dockerfile.olbase
https://realpython.com/python-wheels/
[_If the thunder don't get you then the lightning will..._](http://artsites.ucsc.edu/gdead/agdl/wheel.html) Listen [here](https://archive.org/details/gd1976-06-03.139643.sbd.betty.pcm.kreider.miller.clugston.fixed.flac16/Gd76-06-03FixedT22TheWheel.flac)
Let's get rid of...
```
Using legacy setup.py install for DBUtils, since package 'wheel' is not installed.
Using legacy setup.py install for pymarc, since package 'wheel' is not installed.
Using legacy setup.py install for simplejson, since package 'wheel' is not installed.
Using legacy setup.py install for PyYAML, since package 'wheel' is not installed.
Using legacy setup.py install for eventer, since package 'wheel' is not installed.
Using legacy setup.py install for validate-email, since package …
```
=> Docker: python3 -m pip install wheel

openlibrary/templates/type/edition/view.html
Closes #3564
https://dev.openlibrary.org/works/OL10667890W/Sofia_Petrovna should now work
@LeadSongDog + @cdrini
=> Fixing #3564 rendering editionless works

scripts/solr_builder/Dockerfile.olpython, scripts/solr_builder/README.md
=> Switch solrbuilder to use new docker image

openlibrary/plugins/openlibrary/js/editions-table/index.js
Closes [#3712 ](https://github.com/internetarchive/openlibrary/issues/3712)
Original solution created a new entry in local storage for each work that was visited by a user.  This PR creates a single entry that is applied for all works.
@tabshaikh @seabelis @jessamynwest @cdrini
=> Number of results displayed  globally set

openlibrary/templates/books/edit.html
Hotfix to issue reported by @JeffKaplan 
- https://dev.openlibrary.org/books/OL30087569M/Guad/edit?debug=true Loads on dev (errors on prod)
@JeffKaplan
=> Fix unicode encoding of byline on edit page

openlibrary/tests/solr/test_update_work.py, requirements_test.txt
=> Fix test_update_work

requirements_common.txt
https://github.com/getsentry/sentry-python/blob/master/CHANGES.md
Closes #
=> requirements_common.txt: Upgrade sentry-sdk==0.17.5

package.json
=> Fix trailing whitespace in package.json

Readme.md
=> making it easier for new contributors

openlibrary/core/sponsorships.py, openlibrary/templates/admin/sponsorship.html
trivial fix, adds `donor` column to sponsorship table
=> adds uploader field to sponsorships table

docker-compose.staging.yml, docker-compose.yml, docker/ol-web-start.sh
Create docker-compose file for staging (which is connected to production).
=> Add docker compose file for staging

openlibrary/core/lending.py
=> refactor openlibrary/core/lending.py to use requests

requirements.txt
Closes #3856
It rectifies the requirements file.
=> rectified requirements

static/css/components/header-bar.less
=> Corrected dead space errors in dropdown menus on homepage.

scripts/2010/01/report_errors.py, scripts/2011/08/expire_accounts.py, scripts/2011/09/generate_deworks.py, scripts/2012/dump-ia-items.py
As discussed at https://github.com/internetarchive/openlibrary/issues/1449#issuecomment-622580346
Changes for Python 3 compatibility plus flake8, isort, and black.
=> Python 3 compatibility for four files in /scripts

.travis.yml, Makefile, package.json
Refactor. This should make all the python jobs run faster (no more npm i for every job!), as well as make the logs easier to read.
- Also cleaned up those silly curly quotes
- Organized the package.json scripts a bit more (linting != testing)
- Reduced `make test` commands
@cclauss
=> Separate Node build/test into separate Travis Job

requirements_common.txt
=> requirements_common.txt: Replace the non-ascii space

openlibrary/templates/site/body.html
trivial change, removed announcement bar w/ outdated messaging
=> removing announcement

Readme.md
=> docker setup video link fixed

openlibrary/templates/admin/index.html
Never load http on https. Don't assume https either - use whatever
the current protocol is.
Closes #
=> Use protocol relative URIs for images

openlibrary/templates/admin/index.html
Reverts internetarchive/openlibrary#3933
=> Revert "Use protocol relative URIs for images"

Makefile, openlibrary/plugins/openlibrary/js/vue.js, openlibrary/plugins/upstream/utils.py, openlibrary/templates/site/body.html, webpack.config.js
Small fixes shared between #3408 and #3829 . See commit-by-commit
=> Small vue fixes

Readme.md
trivial change, current video links to item (which selects wrong video)
=> fixing video link

openlibrary/catalog/add_book/load_book.py, openlibrary/catalog/amazon/crawl.py, openlibrary/catalog/amazon/list_done.py, openlibrary/catalog/amazon/load_merge.py, openlibrary/catalog/edition_merge/find_easy.py, openlibrary/catalog/edition_merge/merge.py, openlibrary/catalog/edition_merge/merge_works.py, openlibrary/catalog/edition_merge/run_merge.py, openlibrary/catalog/get_ia.py, openlibrary/catalog/importer/olwrite.py, openlibrary/catalog/marc/parse.py, openlibrary/catalog/marc/parse_xml.py, openlibrary/catalog/marc/tests/test_get_subjects.py, openlibrary/catalog/merge/index.py, openlibrary/catalog/olwrite.py, openlibrary/catalog/utils/edit.py, openlibrary/core/lending.py, openlibrary/core/minicron.py, openlibrary/core/models.py, openlibrary/core/stats.py, openlibrary/core/vendors.py, openlibrary/core/waitinglist.py
Related to #3483
refactor removed unused imports will commit 2 files at a time
@cclauss
=> Removed unused Python standard library imports

docker-compose.yml
See #3960. Fix: Make solr autorestart.
=> Make solr restart always

openlibrary/core/helpers.py
As discussed at https://github.com/internetarchive/openlibrary/pull/3906/files/d39febad16aa35e73218160f11747560160174c2#r513082774
Closes #
=> Remove an out-of-date comment in helpers.py

openlibrary/admin/numbers.py, openlibrary/catalog/amazon/other_editions.py, openlibrary/coverstore/utils.py, openlibrary/plugins/admin/code.py, openlibrary/plugins/admin/services.py
Closes #2852
related to #3694 
@cclauss clubbed `.read()` to `.content` or `.text` here
=> Refactor .read() to use requests

requirements_test.txt
Upgrade some Python test dependencies.
=> Upgrade flake8, pymemcache, and pytest

openlibrary/plugins/importapi/code.py
=> Changed encodestring to encodebytes and added fallback to python 2 if found

openlibrary/plugins/worksearch/code.py
A developer from project Koha noticed Open Library search failing for queries of the form:
https://openlibrary.org/search?author=Potter+Will&title=Green+is+the+new+red+%3A
Closes #3943
@mekarpeles
=> Fix punctuation error in search queries

openlibrary/plugins/worksearch/code.py
Reverts internetarchive/openlibrary#4008
Wasn't working properly on ol-web1
=> Revert "Provide better error messages in plugins/worksearch/code.py"

openlibrary/plugins/upstream/utils.py
=> Replace donate.php endpoint with iframe + donate.js

openlibrary/templates/site/body.html
rm llf announcement (trivial change)
=> removing announcement bar for now (LLF is over)

docker-compose.production.yml, docker-compose.staging.yml
=> Add restart: always + hostname to web prod

scripts/solr_builder/README.md
=> Update some solrbuilder timings

openlibrary/plugins/openlibrary/code.py, openlibrary/templates/work_search.html
=> Fix search facets

scripts/setup_web1.sh
Change automated setup to match https://github.com/internetarchive/openlibrary/wiki/Deployment-Guide#ol-web1
=> setup_web1.sh: Update docker deploy commands

requirements_common.txt
https://github.com/webpy/webpy/releases
=> requirements_common.txt: Upgrade to web.py==0.62 on Python 3 only

scripts/pull-templates.py
Hi openlibrary, this is a typo or not? it' seems deactivated for a several reason?
=> rebuilder default_plugin

openlibrary/plugins/upstream/borrow.py
=> Change PY3 to PY2 in borrow.py

scripts/run_olserver.sh
Were there other notes on changes that needed to be made to `scripts/run_olserver.sh`?
=> No quotes on $SERVICE in scripts/run_olserver.sh

openlibrary/catalog/add_book/__init__.py
Closes #4083
Also, https://sentry.archive.org/sentry/ol-web/issues/9042
A similar solution as #3973
Adding a cover image is raising a TypeError on Python 3
=> Fix add_cover is raising TypeError

docker-compose.production.yml
=> Set COVERSTORE_CONFIG for production

requirements.txt
https://pypi.org/project/flup/
https://pypi.org/project/flup-py3/
```
flup==1.0.3; python_version < '3.0'
flup-py3==1.0.3; python_version >= '3.0'
```
Closes #4116
=> requirements.txt: Add flup and flup-py3

openlibrary/templates/covers/author_photo.html, openlibrary/templates/site/body.html, openlibrary/templates/type/author/view.html
Closes #3231 
Add schema markup tags for the authors and improves the search result.
As suggested in the comment of the issue, [here](https://github.com/internetarchive/openlibrary/issues/3231#issuecomment-602078002). I have made the changes, although I was confused as to what should be the `itemprop` in line `72` of my made changes, should it be `author` or `name` property?
The second para of the comment(except the `subjects` property) asks us to change this file:https://github.com/internetarchive/openlibrary/blob/1e31269adcc7118642e591e9dcfc04f400bdf658/openlibrary/macros/SearchResultsWork.html#L40
I don't know if I should add some more markup in this file too, so I did not do any changes. If I should do it in this same PR, do tell me, I would be happy to do it.
The `alternateName` …
=> Add schema markup to Authors to improve search results.

openlibrary/plugins/upstream/utils.py
Closes #4122 
@mekarpeles @cclauss
=> Hotfix: Python 2 throwing errors for meta tags

.github/FUNDING.yml
Hover over the ❤️ Sponsor button...
=> Fix errors were encountered when parsing FUNDING.yml

requirements.txt, requirements_common.txt
Closes #4117 by moving from `requirements.txt` to `requirements_common.txt`
=> Move flup to requirements_common.txt

docker-compose.production.yml
=> Mount volume 1 on covers and infobase

conf/infobase.yml
Closes #4061 Add dummy dsn for Sentry
=> Add Sentry to infobase.yml

conf/openlibrary.yml, docker-compose.override.yml, docker-compose.production.yml, docker-compose.yml, docker/Dockerfile.oldev, docker/covers_nginx.conf, docker/nginx.conf, docker/ol-covers-start.sh
Closes #
Tested this works if we comment out all the olsystem requirements locally.
=> Add nginx covers to allow covers scalability + port 80 exposing

docker-compose.yml, openlibrary/coverstore/coverlib.py, openlibrary/plugins/upstream/covers.py
Closes #
- Tested uploading a cover on py3 works with py3 covers on local
- Tested uploading a cover on py2 with production covers
=> Fix uploading covers on py3

docker-compose.infogami-local.yml, docker-compose.override.yml, docker-compose.production.yml, docker-compose.staging.yml, docker-compose.yml, docker/Dockerfile.oldev
Closes #
- ci does a "clean" install; i.e. it remove node_modules and installs everything from scratch. We don't need that (especially since node_modules will likely already exist for local environments, and will be mounted over :/ ) This command is _super_ slow.
@mekarpeles @cclauss
=> Fix covers prod yml + use npm i in oldev

openlibrary/i18n/hr/messages.po
Initial and complete release of Croatian (hr) translation
=> Croatian (hr) translation

openlibrary/i18n/es/messages.po
This pull request do not close any former PR
* minor fix in line 553
* minor fix in line 557
* proposed translation in line 688
* minor proposal in line 1053
* proposal in line 2276 
* proposal in line 2647
* minor proposal in line 3342
* translation proposal in line 3373
* translation proposal in line 3563
There is no break on code, since is focused on a particular language: spanish
=> Typo fixed (line 459) plus others fixes in spanish translation

openlibrary/templates/account/email/forgot.html, openlibrary/templates/account/import.html, openlibrary/templates/admin/inspect/thing.html
=> indentation in things.html and bug fixed in things.html

openlibrary/coverstore/code.py
Closes #4161
Fixes guard for conditional logic to not be True when value is 0
@cclauss @cdrini
=> fixes guard in covers logic

openlibrary/templates/admin/loans.html, openlibrary/templates/books/check.html, openlibrary/templates/books/edit/edition.html, openlibrary/templates/books/edit/web.html
=> some bugs fixed related to missing tags and uneven orgering of tags

openlibrary/templates/borrow_admin_no_update.html, openlibrary/templates/covers/saved.html, openlibrary/templates/history.html, openlibrary/templates/home/stats.html
=> onClick to onclick and tags error fixed

openlibrary/templates/lib/markdown.html, openlibrary/templates/lib/search_head.html, openlibrary/templates/lists/preview.html
=> manually indent preview.html

openlibrary/templates/search/authors.html, openlibrary/templates/type/edition/view.html, openlibrary/templates/type/i18n/edit.html
=> some more manual bugs fixed

openlibrary/templates/type/macro/edit.html, openlibrary/templates/type/work/editions.html
=> HTML Validation

openlibrary/i18n/hr/messages.po
- just some corrections after reviewing the "staging" pages
Just as a side note: there are still many untranslated strings in the "staging" pages
=> Updated Croatian translation

docker-compose.production.yml, docker/covers_nginx.conf
=> Add SSL certs to covers_nginx

openlibrary/core/lending.py, openlibrary/core/models.py, openlibrary/macros/LoanStatus.html, openlibrary/plugins/openlibrary/home.py
Uses new https://archive.org/services/availability?identifier=highercreativity00harm API
Updates Open Library logic to use more accurate keys and status code
This PR is presently broken
=> Draft: integrating updated bulk services/availability API

openlibrary/core/lending.py, openlibrary/core/models.py, openlibrary/macros/LoanStatus.html, openlibrary/plugins/openlibrary/home.py
Reverts internetarchive/openlibrary#4170
=> Revert "Draft: integrating updated bulk services/availability API"

openlibrary/core/lending.py, openlibrary/core/models.py, openlibrary/macros/LoanStatus.html, openlibrary/plugins/openlibrary/home.py
Reverts ... revert  internetarchive/openlibrary#4213
=> PR to unrevert "integrating updated bulk services/availability API""

openlibrary/templates/covers/add.html
=> Change Cover Guidelines to Image Guidelines

openlibrary/core/cache.py, openlibrary/core/models.py, openlibrary/coverstore/disk.py, openlibrary/coverstore/tests/test_webapp.py, openlibrary/mocks/mock_memcache.py, openlibrary/mocks/mock_ol.py, openlibrary/plugins/importapi/import_edition_builder.py, openlibrary/plugins/ol_infobase.py, openlibrary/plugins/openlibrary/opds.py, openlibrary/plugins/openlibrary/tests/test_listapi.py, openlibrary/plugins/openlibrary/tests/test_ratingsapi.py, openlibrary/plugins/search/solr_client.py, openlibrary/plugins/upstream/adapter.py, openlibrary/plugins/upstream/tests/test_merge_authors.py, openlibrary/plugins/upstream/utils.py, openlibrary/tests/core/test_connections.py, openlibrary/tests/solr/test_update_work.py, openlibrary/utils/httpserver.py
Related to #4227 
Create a new object each time the function is called, by using a default arg to signal that no argument was provided.
@cclauss
=> Fixed dangerous default argument

requirements_common.txt
Closes security issues in https://pypi.org/project/lxml
=> Security update to lxml=4.6.2

openlibrary/templates/admin/memory/index.html
=> Replace HTML valign with CSS vertical-align

openlibrary/templates/type/edition/view.html, openlibrary/templates/type/work/editions_datatable.html
Closes #3760, #4051
https://openlibrary.org/books/OL21692921M/Catharisme?debug=true
http://openlibrary.org/books/OL18314559M/Nineteen_eighty-four?debug=true
http://openlibrary.org/books/OL14412099M/Nineteen_eighty-four?debug=true
http://openlibrary.org/books/OL9096223M/Nineteen_Eighty-Four?debug=true
http://openlibrary.org/books/OL18314559M/Nineteen_eighty-four?debug=true
https://sentry.archive.org/sentry/ol-web/issues/3695
https://sentry.archive.org/sentry/ol-web/issues/9712 ?
=> Python 3: list index out of range -- Fix IndexError in templates/type/edition/view.html

openlibrary/templates/type/edition/view.html, openlibrary/templates/type/work/editions_datatable.html
Reverts internetarchive/openlibrary#4052
As discussed on Slack, this does not seem to be fixed when running on staging.
=> Revert "Python 3: list index out of range -- Fix IndexError in templates/type/edition/view.html"

.eslintrc.json
Closes #4231
It will help in updating eslint-plugin-vue to 7.2.0 
@cdrini
=> Disables "vue/no-mutating-props" rule

scripts/run_olserver.sh
* Dev and staging nodes
* Covers? (Can/do we use `requires`)
* Infobase? (Can/do we use `requires`)
Closes #
=> Update scripts/run_olserver.sh to use $COMPOSE_FILE

.github/workflows/javascript_tests.yml, .github/workflows/test_javascript.yml
=> javascript_tests.yml: push: [ master ], pull_request: [ master ]

scripts/make-integration-branch.sh
Feature (See #3859)
Tested `echo "Complete; dev-merged created (SHA: $(git rev-parse --short HEAD))"` works locally
@cclauss
=> Add SHA to make-integration-branch

conf/openlibrary.yml, openlibrary/macros/UserMetadata.html, openlibrary/plugins/openlibrary/js/patron-metadata/index.js, openlibrary/plugins/upstream/utils.py, static/css/components/work.less
Resolves review notes from PR #3912
A lot of changes were made since the original PR was merged, so I thought that it would be best to open a new one.
The Best Book On URL has been updated and is now defined in `openlibrary.yml`.  A new function has been created to fetch the URL from a template.
Inline styles have also been removed.
@mekarpeles
=> Improvements to Crowd-Sourced Characteristics 

openlibrary/plugins/upstream/account.py
=> Python 3: Convert Goodreads csv from bytes to str

requirements_test.txt
Substantial improvements https://docs.pytest.org/en/stable/changelog.html
Closes #
=> requirements_test.txt: Upgrade to pytest 6.2.0

openlibrary/plugins/worksearch/code.py
Fix MULTI-KEYWORD search in AUTHORS PAGE.
Seacrch for a book using more than 1 word in authors page.
@mekarpeles  @tabshaikh
=> Fix multi-word search

static/css/components/category-item.less, static/css/components/home.less
Closes #4063 
1) Removed grayscale filter
2) Removed margin from h3 tag in order to align it properly
@jamesachamp
=> Removed grayscale filter

openlibrary/plugins/worksearch/code.py, openlibrary/templates/lists/widget.html
Closes #4215, closes #4121 
Fixes author pages. Necessary for hotfixing #4215. Tested on dev. treating as P0
=> Author page fixes: #4215, #4121

scripts/new-solr-updater.py
Closes #4246
Hotpatched this onto ol-home; confirmed it's now running without getting stuck.
=> Make new-solr-updater handler new infobase edge cases

openlibrary/templates/type/edition/admin_bar.html
Prep for #4286 
see: https://github.com/internetarchive/openlibrary/pull/4286#issuecomment-747217856
=> prereq for orphaned editions fix in #4286

scripts/setup_olserver.sh
Closes #3859
Ran the new command with `echo` and it worked.
@cclauss
=> Option to add to docker group in setup_olserver.sh

openlibrary/templates/recentchanges/index.html
Partially addresses #2640
feature
Verified the link takes you to a page that shows recent book edits.
@BrittanyBunk @jamesachamp @cdrini
=> Add link to /recentchanges/edit-book from /recentchanges.

openlibrary/api.py
Addresses #2308
Refactor to replace simplejson with python json in openlibrary/api package.
Refactor to replace simplejson with python json in openlibrary/api package.
Unit tests run.
N/A
@cclauss
=> Replace simplejson with python json in openlibrary/api for 2308

scripts/solr_builder/Dockerfile.olpython, scripts/solr_builder/docker-compose.yml, scripts/solr_builder/solr_builder/solr_builder_main.py
Hit some http errors while testing solrbuilder with py2; switching to py3 fixed them.
Tested this locally by running solrbuilder outside of Jenkins. You likely won't be able to test it easily 😓 So just asking for a code review on this one, I guess.
@cclauss
=> Py3-ize solrbuilder

openlibrary/plugins/upstream/account.py, openlibrary/plugins/upstream/adapter.py, openlibrary/plugins/upstream/addbook.py, openlibrary/plugins/upstream/borrow.py, openlibrary/plugins/upstream/jsdef.py, openlibrary/plugins/upstream/merge_authors.py, openlibrary/plugins/upstream/models.py, openlibrary/plugins/upstream/recentchanges.py, openlibrary/plugins/upstream/utils.py
Addresses #2308
Refactor to replace simplejson with python json in package `openlibrary.plugins.upstream`.
Replaced `simplejson` with `json`.
Unit tests pass.
N/A
@cclauss
=> Replace simplejson with python json in plugins/upstream for 2308

docker-compose.infogami-local.yml, docker-compose.yml, docker/ol-home-start.sh, scripts/solr_builder/docker-compose.yml
Closes #4249
https://git-scm.com/book/en/v2/Git-Tools-Submodules 
```sh
cd vendor/infogami
git fetch
git merge origin/master
git submodule update --remote vendor/infogami
git diff --submodule
git commit -am"Update infogami submodule to master"
git push
```
=> Update infogami submodule to master

openlibrary/templates/type/edition/view.html
Closes #3713 
Table for Contributor Section
=> Table for contributors section

openlibrary/data/__init__.py, openlibrary/data/db.py, openlibrary/data/dump.py, openlibrary/data/sitemap.py, openlibrary/data/solr.py
Addresses #2308
Refactor to replace simplejson with python json in openlibrary/data package
Refactor to replace simplejson with python json in openlibrary/data package
Unit tests pass.
N/A
@cclauss
=> Replace simplejson with python json in openlibrary/data package for 2308

openlibrary/templates/lib/nav_head.html, static/css/components/header-bar--desktop.less, static/css/components/header-bar.less
Closes #
#2754 
browser dropdown overlap bug in IE11 is fixed
@jdlrobson
=> fixes browser dropdown overlap bug in IE11

openlibrary/plugins/openlibrary/lists.py, openlibrary/templates/lists/home.html, openlibrary/templates/lists/preview.html, openlibrary/templates/lists/snippet.html, openlibrary/templates/type/list/embed.html, openlibrary/templates/type/list/view.html
Closes #
Replaced seeds with Books (Lists page)
@mekarpeles
=> Replaced "seeds" with "items"

openlibrary/plugins/openlibrary/js/index.js, openlibrary/templates/lib/nav_head.html
Closes #4082 
Improves WAVE accessibility score
@mekarpeles @bfalling
=> Fix to improve WAVE accessibility score

openlibrary/core/vendors.py
small change to make it easier to test amazon API / search
tested on dev
=> adds search feature to amz cls

docker-compose.production.yml
=>  Remove /openlibrary volume mount from docker-compose.production.yml

openlibrary/core/civicrm.py, openlibrary/core/sponsorships.py, openlibrary/plugins/admin/code.py
Emails patrons (via civi email fetch) when book is complete
Should probably be a PR before this to update quotes (to reduce noise)
=> sponsorship admin sync: get civi by isbn + send email

bundlesize.config.json, static/css/components/header-bar.less
=> Fixed dropdown overlap

docker/Dockerfile.olbase, docker/Dockerfile.oldev
A sub-task of #4060
```
docker-compose build --pull && docker-compose up -d && docker exec -it openlibrary_web_1 /bin/bash
vi
emacs
```
=> Add vim and emacs to Dockerfile.olbase

openlibrary/plugins/importapi/code.py
Closes #4340
```python
if b'<?xml' in data[:10]:
```
=> Ensure that parse_data() compares bytes with bytes

static/css/components/list-entry.less, static/css/page-user.less
=> Fixed lists alignment error

openlibrary/templates/lib/nav_foot.html, openlibrary/templates/lib/nav_head.html, static/css/components/header-bar.less, static/css/components/work.less
Closes #1514 
Merged my books and user menu. 
@jdlrobson
=> Merged My Books and user menu

requirements_common.txt, requirements_test.txt
* https://github.com/pytest-dev/pytest/releases
* https://github.com/pyupio/safety/blob/master/HISTORY.rst
* https://github.com/getsentry/sentry-python/blob/master/CHANGES.md
=> Upgrade testing dependencies: pytest, safety, sentry-sdk

openlibrary/plugins/worksearch/code.py
Related to  #2308 
Refactor to replace simplejson with json.
Also remove unused import opposite_isbn
And unused variables in except catches.
Some fixes for lint applied regarding unused import and unused variables.
Unit tests run.
N/A
@cclauss as requested from #4298
=> Replace simplejson with json in plugins/worksearch/code.py

bundlesize.config.json, openlibrary/templates/books/edition-sort.html, static/css/components/editions.less, static/css/components/read-panel.less
Closes #4408
Added Worldcat link
@seabelis
=> Added Worldcat link to the edition list

docker-compose.production.yml, docker-compose.yml, docker/ol-solr-updater-start.sh
Solr-updater now runs on ol-home0 \o/
=> Fix errors with solr-updater service configs

openlibrary/api.py
Closes #4459
Reverts one change made in #4338 to get our imports working again.
=> Fix OpenLibrary.import_ocaid() by returning str, not bytes

openlibrary/plugins/upstream/addbook.py
Closes https://github.com/internetarchive/openlibrary/pull/4286#issuecomment-747756726
=> Remove duplicate orphaned edition code from addbook.py

scripts/generate-api-docs.py
=> Removed unused plugin references: "heartbeat"

openlibrary/macros/AffiliateLinks.html, openlibrary/plugins/openlibrary/js/carousels_partials.js, openlibrary/templates/lib/nav_head.html, openlibrary/templates/type/edition/publisher_line.html, openlibrary/templates/type/edition/view.html
Closes #4440 and #3881
Fix validation errors on books page
only duplicate id error is remaining that can be fixed on the homepage issue
@jdlrobson
=> Fix validation errors on books page

openlibrary/utils/bulkimport.py
Addresses #2308 
Refactor to replace simplejson with json.  And fixes an indent problem.
Refactor to replace simplejson with json.  And fixes an indent problem.
I'm not sure how to test this.  It doesn't seem to be covered under unittests, and the `__main__` test does not work even if I have it connect to the db.
N/A
@cclauss
=> Replace simplejson with json for 2308 in bulkimport

openlibrary/templates/type/list/view.html
Closes #4473 
Fixes users list HTML validation errors
@jdlrobson
=> Fixes users list HTML validation errors

scripts/oclc_to_marc.py
Regarding #2852 
Refactor to replace urlopen and simplejson with requests.
This is a script, see testing below.
Test with an oclc in openlibrary for _Stellaluna_ OL30777090M
```bash
openlibrary@41cb7a6fa789:/openlibrary$ python scripts/oclc_to_marc.py 1089251450
1089251450	/books/OL30777090M
```
Test a book without an oclc _Catcher in the Rye_: OL28698765M
```bash
openlibrary@41cb7a6fa789:/openlibrary$ python scripts/oclc_to_marc.py 1155635839
```
N/A
@cclauss @hornc
=> Replace urlopen and simplejson with requests.

scripts/copydocs.py
Subtask of #2308
@dherbst
Closes #
=> Remove simplejson from scripts/copydocs.py

scripts/migrate_db.py
Subtask of #2308
@dherbst
Closes #
=> Remove simplejson from scripts/migrate_db.py

scripts/jsondump.py
=> Remove simplejson from scripts/jsondump.py

static/css/legacy.less
=> Removed unused plugin references: "theme"

scripts/make-integration-branch.sh
Will make the jenkins flow a little more robust.
@mekarpeles
=> make-integration-branch doesnt fail on merge conflict

scripts/deployment/deploy.sh
=> deploy.sh: Comment on git SHA tag to Docker image
