- openlibrary/macros/databarWork.html
- openlibrary/plugins/openlibrary/home.py
- openlibrary/templates/books/edition-sort.html
- openlibrary/templates/lib/covers.html
- openlibrary/templates/type/author/view.html
OverDrive urls have changed from:
search.overdrive.com/SearchResults.aspx?ReserveID=
to
www.overdrive.com/search?q=
Verified that using the second format with existing OverDrive ID's resolves to the correct title on overdrive.com.
Sample:
http://search.overdrive.com/SearchResults.aspx?ReserveID={0649E54A-657E-4342-AD7D-5BAEE9153A44}
http://www.overdrive.com/search?q={0649E54A-657E-4342-AD7D-5BAEE9153A44}
This appears to be a change throughout the entire OverDrive site.
> fix overdrive link errors due to overdrive site change

- conf/init/ol-solr-updater.conf
the /etc/init/ol-solr-updater.conf file contains invalid conf file locations that causes the solr updater to fail immediately, as in https://github.com/internetarchive/openlibrary/pull/218#issuecomment-69619680
updated with the correct one.
> updated  /etc/init/ol-solr-updater.conf with a valid location for the config file

- Makefile
- setup.sh
I fixed a typo in the documentation for setup.sh (changed 'udpate' to 'update').
> Fix typo in setup.sh

- openlibrary/core/waitinglist.py
The get_waitinglist_size() function was always returnsing 0 as it was looking
for size of waitinglists stored in OL instead of querying archive.org. Updated
that function to return correct size.
> Fixed "checkouts caught in loop" issue.

- scripts/infobase-server
Suspected that the memory leaks are caused by multiplexed=True option passed
to flup fastcgi server. Switched to multiplexed=False now to see if that helps.
> Attempt to fix memory leaks in infobase fastcgi.

- Makefile
- openlibrary/core/tests/test_waitinglist.py
- openlibrary/core/waitinglist.py
- openlibrary/plugins/upstream/tests/test_forms.py
I have just started playing with the Open Library codebase, and this is my attempt to get the tests passing on Travis after successfully setting up a vagrant dev instance.
This is started as an effort to solve issue https://github.com/internetarchive/openlibrary/issues/236
I found 2 causes of failing tests:
1. It looks like the waitinglists were moved from the local db to an external api here: https://github.com/internetarchive/openlibrary/commit/b2703037996d7947653caecd1337858aaf0823f7
but the tests were not updated to reflect this.
These waitinglist tests should either be removed or updated if this PR passes.
2. The forms validate test was erroring with `AttributeError: 'site'` from 
```
def get_spam_domains():
>       doc = web.ctx.site.store.get("spamwords") or {} …
```
> Fix tests to allow Travis CI to pass

- openlibrary/templates/type/author/rdf.html
- openlibrary/templates/type/edition/rdf.html
- openlibrary/templates/type/work/rdf.html
@bencomp ,This is your PR https://github.com/internetarchive/openlibrary/pull/136 rebased against my recent test fix. I have not looked closely at the content of your changes, I have simply replayed your changes to the templates over the latest code and passing tests, I believe this is what you wanted to do for issue https://github.com/internetarchive/openlibrary/issues/223 ?
I did this quickly, and surprisingly smoothly. Someone who knows about the RDF issues should probably review to be sure I have not missed anything. The tests pass locally, and I manually checked that the `foaf:name` changes you made to the work rdf export were present in my dev instance, I have not tested the changes any further than that.
I realise the original PR was raised a long time ago, but I am re-raising this …
> Rebased PR 136: RDF changes: consistent URIs without trailing "/", more FOAF, rdf:about=""

- openlibrary/templates/admin/people/edits.html
Hi @gdamdam, could you please review this change to an admin template?
This adds the ability to paginate the list of user edits in the admin interface. The new feature is the "Older | Newer" links at the bottom of this screenshot.
Previously it was not possible to navigate to changes beyond the most recent 100, which meant for account blocks that error on automatic reverts, there was no way to check which edits were un-reverted beyond that.
I have also added the ability to manually specify a limit other than the default of 100 to assist with reverting larger sets of spam if needed.
example url:
`admin/people/<username>/edits?limit=10&page=2`
I have tested this locally with limited test data.
> Paginate Admin People Edits view

- openlibrary/plugins/upstream/spamcheck.py
If a spammer has been blocked _and_ reverted, it no longer registers as an account.
Deleted users return nothing for `user.get_account()`, and this was allowing the spamcheck to pass.
Active and Blocked users are `<Thing: u'/type/user'>`
but deleted users are `<Thing: u'/type/delete'>`
There is probably a way to pull all the logic together to catch all of the scenarios in a neater fashion. I'll look into it later.
> prevent deleted users from editing

- .travis.yml
Looks like updating to the new travis infrastructure allows the tests to pass.
The previous
```
before_install:
- sudo apt-get install -qq python-lxml python-yaml python-psycopg2 libgeoip-dev
```
section was giving problems, and the new way does not support use of `sudo`.
The upgrading guide was relatively straightforward: https://docs.travis-ci.com/user/migrating-from-legacy/
and all the required packages appear to be on the whitelist.
> update travis config to use new container-based infrastructure

- openlibrary/plugins/upstream/utils.py
- openlibrary/templates/recentchanges/default/message.html
- openlibrary/templates/recentchanges/edit-book/message.html
This only affects the `recentchanges_v2` feature enabled recent changes.
I've added code in two places to make sure deleted / unwanted edits aren't advertised in the Around The Library footer. (generated via the message.html templates)
This won't affect the full Recent Changes page list though, I find it useful to see deleted records or spam if I go looking for it, we just shouldn't be advertising the spam / housekeeping edits on the front page!
> Don't show deleted authors or deleted items in Around The Library

- openlibrary/api.py
- openlibrary/templates/admin/solr.html
- openlibrary/templates/lists/widget.html
Addresses #227 by disabling the list widget's list creation form after a request is submitted. The form is reenabled by adding a 'complete' callback to the ajax request. Also prevents adding an item to a list multiple times by disabling the add-list click event handler for that list while the request is pending.
Also included are some minor typo fixes
> Issue 227 List widget can create duplicate requests

- openlibrary/templates/borrow/navigation.html
for now, removing "register library" options where found. Users find this confusing and it's not an active feature.
> rm nav code we are not using

- openlibrary/templates/search/subjects.html
- openlibrary/templates/subjects/index.html
Remove the trailing `&search=` from the query mentioned in this issue https://github.com/internetarchive/openlibrary/issues/103
by bringing these template inline with those in `openlibrary/templates/search/*.html` and `openlibrary/templates/*/index.html`
> Issue #103, standardise subject search buttons

- openlibrary/core/lending.py
- openlibrary/core/tests/test_waitinglist.py
- openlibrary/plugins/recaptcha/recaptcha.py
- openlibrary/plugins/upstream/models.py
- openlibrary/plugins/upstream/utils.py
- openlibrary/plugins/worksearch/code.py
- openlibrary/plugins/worksearch/search.py
- openlibrary/plugins/worksearch/subjects.py
- openlibrary/templates/type/author/view.html
- openlibrary/utils/solr.py
Add some quick exception handling for the most egregious offenders which cause OL to fall on its face when Archive.org or SOLR are unavailable.
These changes could really use tests, but without a good mocking framework in place, this is not trivial. Let's get this basic protection up first.
> Catch HTTP exceptions from key external dependencies

- openlibrary/core/lending.py
- openlibrary/i18n/messages.pot
- openlibrary/i18n/te/messages.po
- openlibrary/plugins/openlibrary/home.py
- openlibrary/templates/lib/search_foot.html
- openlibrary/templates/lib/search_head.html
- openlibrary/templates/search/inside.html
- static/css/master.css
Moving "Search inside" link to above search form instead of below
> Add "Search inside" link above global search form

- openlibrary/templates/search/inside.html
This makes the Search Inside results page render like greased lightning!
> Change Search Inside results to use returned metadata, not IA calls

- openlibrary/core/models.py
- openlibrary/macros/LoanStatus.html
- openlibrary/macros/databarWork.html
- openlibrary/plugins/openlibrary/js/bookreader_direct.js
- openlibrary/plugins/upstream/borrow.py
- openlibrary/templates/books/carousel_item.html
- openlibrary/templates/books/edition-sort.html
- openlibrary/templates/lib/covers.html
- openlibrary/templates/search/inside.html
- openlibrary/templates/type/author/view.html
- openlibrary/templates/type/edition/view.html
- openlibrary/templates/type/list/view.html
- openlibrary/templates/work_search.html
- static/css/master.css
Generally, all links where the user should be able to *read the book* now go directly to BookReader. OTOH, if a user tries to go to a book which has been checked out, they'll reach the old Borrow page, which has waitlist options; in that case, can't send them to BookReader directly because the special backdoor which allows OL users to interact with BookReader without needing an Archive account doesn't come into play.
In addition, the Read/Borrow links were made to look more like buttons. These links now open in `target="_blank"` since they go "offsite" to Archive.org. And public-domain BookReader links now add a `ref=ol` parameter so BookReader in the future can configure its Back button to point back to OL instead of Archive.
> Eliminate Borrow interstitial page in favor of direct-to-BookReader links

- openlibrary/macros/LoanForm.html
- openlibrary/templates/borrow.html
- openlibrary/templates/lib/covers.html
- openlibrary/templates/type/author/view.html
- openlibrary/templates/type/list/view.html
- openlibrary/templates/work_search.html
- Papering over erroneous borrow status icons in search results, list details, author pages, etc. Now they all say “Read” and attempt to hit BookReader! :slightly_smiling_face:
- Removing the PDF/ePub options from the OL Borrow page, since these downloadables should be done from BookReader
- Changing the Borrow page logic so that even if you have borrowed via PDF/ePub options, you won’t be blocked on that page from opening BookReader
> Address a few loan status presentation bugs

- Makefile
- openlibrary/core/helpers.py
- openlibrary/core/lending.py
- openlibrary/core/models.py
- openlibrary/macros/databarWork.html
- openlibrary/plugins/openlibrary/home.py
- openlibrary/plugins/upstream/tests/test_borrow.py
- openlibrary/templates/account/borrow.html
- openlibrary/templates/books/edition-show.html
- openlibrary/templates/books/edition-sort.html
- openlibrary/templates/borrow.html
- openlibrary/templates/home/index.html
- openlibrary/templates/type/author/view.html
- openlibrary/templates/type/edition/view.html
- openlibrary/tests/core/test_models.py
- tests/integration/test_search.py
If an Archive book item is in a private collection (as defined in `openlibrary/core/helpers.py:private_collections()`), then don't show an IA identifier on the Edition page, and block attempts to read the items via the Borrow page. As a convenience, also remove Read links from the Edition and Work pages.
Also adds a few code defenses from bad return values and fixes an unclosed HTML tag.
> New private collections: prevent linking to them from Open Library

- openlibrary/plugins/upstream/utils.py
Fixes a bug whereby closing the donation banner doesn't silence its appearance on future page visits
> Make donation banner injector pass site cookies to banner source endpoints

- openlibrary/macros/databarWork.html
- openlibrary/plugins/openlibrary/pages/config_edition.page
- openlibrary/templates/books/edition-sort.html
- openlibrary/templates/borrow/about.html
- openlibrary/templates/type/edition-history/view.html
- static/openbook/openbook.js
This should address issue #422, by making OCLC number the preferred search parameter to Worldcat when it exists, and falling back to ISBN only when it does not.
> Prioritize oclc over isbn for physical copy searches

- openlibrary/templates/lib/site_legal.html
A small change to use https for all links in the footer. Issue #324 
https://archive.org/web/ appears to be the canonical URL for the wayback machine, this change avoids unnecessary redirects between sites controlled by the IA.
> use https and avoid redirects on site footer links

- conf/init/ol-solr-updater.conf
- openlibrary/solr/update_work.py
Since ia_db isn't defined in the config, update_work.py throws an exception causing upstart to continually respawn ol-solr-updater resulting in CPU thrashing as the process continuously respawns.
Solve the respawning problem by checking to see if the ia_db key exists in the first place, and protect against future respawn-storms with a respawn limit. This allows ol-solr-updater to start, although I don't have any idea what it does functionally to it (ie: does it still work in the devel vagrant image or just die somewhere else?).
> Stop ol-solr-updater from spinning

- openlibrary/core/olmarkdown.py
- openlibrary/tests/core/test_olmarkdown.py
This fixes the failing tests uncovered in PR #450 by @jack17529 , which happens to show the issue raised in #457 about https links not appearing on the wiki.
Strangely, this post made years ago by @anandology on a different forum helped me fix the issue: https://bugs.launchpad.net/infogami/+bug/193622  thanks! :)
Looks like a bug in infogami's markdown parser which is still current. The regex's in the olmarkdown.py that match `https` are for a link _PRE_ processor -- when the https url is passed on to the actual markdown processor, it hits the bug and is stripped.
I added in the http version of the test to ensure the markdown parser is backwards compatible and can support any urls when editing the wiki. I agree that the OL source should not publish https urls, but the http in the test is …
> Allow wiki to display https links

- openlibrary/templates/type/language/view.html
Currently language pages have broken search links that return no results, e.g: https://openlibrary.org/languages/eng
This PR corrects the search url.
Language pages can be navigated to from edition pages that have their written-in language set.
> fix /type/language page search links

- openlibrary/core/schema.py
I noticed this typo was causing errors on Travis CI which were being ignored, see https://travis-ci.org/internetarchive/openlibrary/builds/214360046#L792
I'm not sure of the production implications of this change, or whether the production db has the same problem and needs to be fixed by some other mechanism?
@mekarpeles, can you please review this and check whether this typo is a problem in the production `import_item` table that needs addressing?
> fix typo in import_item table

- openlibrary/core/ia.py
- openlibrary/plugins/importapi/code.py
Test case:
Archive.org itemid / ocaid: `PrivateWealthAndPublicEducation`
Previously failed w/ `no-imagecount`.
Repeatable via the following on ol-dev0
```sudo -u openlibrary /olsystem/bin/olenv HOME=/home/openlibrary OPENLIBRARY_RCFILE=/olsystem/etc/olrc-importbot python /opt/openlibrary/openlibrary/scripts/manage-imports.py --config /olsystem/etc/openlibrary.yml import-ocaids PrivateWealthAndPublicEducation```
```0.0 (1): UPDATE import_item SET status = 'failed', error = 'no-marc-record', import_time = '2017-04-28T00:57:40.400094', ol_key = NULL WHERE id=573748```
In this case, it still fails by not having a MARC, but this is a separate issue (and check which occurs after the `imagecount`)
> Resolving importbot issue where imagecount accidentally omitted

- openlibrary/utils/solr.py
The POST body was not correctly recognising the encoding.
Setting charset=UTF-8 fixes the problem so now subjects containing unicode characters will produces results from posted solr queries
> Subjects with unicode fails to load any results, Fix #317

- openlibrary/catalog/marc/test_work_subject.py
@mekarpeles I made this change when I was testing the MARC tool, it updates these tests for a data move that happened a long time ago. Not very useful, but I thought it better to commit than discard the changes.
> Correct location of test data

- openlibrary/plugins/upstream/code.py
- openlibrary/templates/type/delete/view.html
- openlibrary/templates/viewpage.html
Making it so only admins can delete + revert
cc: @JeffKaplan
> preventing non-admins from reverting deleted pages

- openlibrary/templates/books/carousel_item.html
Without $:, the click trackers are being rendered as literal strings including quotes
> fixing tracking pixel, using $:

- openlibrary/plugins/upstream/addbook.py
This is a quick change to take covers and subjects from an orphaned edition when creating a new work via the UI.
Most orphaned editions have a cover, and many have subjects that are more useful at the work level.
> better works created from edition records

- openlibrary/plugins/openlibrary/js/autocomplete.js
The enabled-by-default `matchSubset` option on the author's autocomplete widget (thing) was causing the "Create new author" option to disappear when the user typed slowly (see #513).
Resolved by disabling this option. This means that 2 network requests will be made if a user quickly types "John Ste" and then "John Steinb", whereas previously only 1 network request would be made, because the results from the "John Ste" query would be cached and filtered to match the new query. This could result in a rise in traffic to the author autocompletion endpoint.
> Disable matchSubset option for author autocomplete

- openlibrary/core/models.py
- openlibrary/plugins/upstream/borrow.py
This is in attempt to address a problem @JeffKaplan is having where waitlisted users whose turn it is to borrow click the link in their email but aren't able to get their book. It reverts code changes which were made to simplify the /borrow logic and also to have editions page display more accurate borrow status
> [WIP] reverting user_can_borrow login on OL to pre v2

- openlibrary/plugins/recaptcha/recaptcha.py
(Sorry for the dupe PR, had a typo in my branch name -_-)
Did some digging related to #595 , and it looks like recaptcha already has a fallback for when javascript is disabled. ~I think the fallback just had a bug in it (a bug present on the official documentation page! https://developers.google.com/recaptcha/old/docs/tips ). The names of the inputs look wrong (needed to be swapped).~
~@mek Could you put this on dev before merging? It's a little hard to test this locally.~
I think the 'bug' is that the textarea for the no-js recaptcha starts with 4 spaces in it. When the user pastes the code from the recaptcha into the text area, they don't remove the spaces, so the captcha is considered wrong.
> Fix recaptcha failing when js disabled

- openlibrary/plugins/upstream/addbook.py
- openlibrary/utils/__init__.py
A lot of results appear in the author autocomplete, making it hard to find the right one if you're searching for a common name ("John Smith", anyone?). This adds support for searching by an author key.
> Author autocomplete supports search by key

- openlibrary/plugins/openlibrary/js/autocomplete.js
Fix the add books page author autocomplete "Create new author" option disappearing if there are more than 11 results. Cause by #589 (looks like that slice was also there for another reason!). This should complete #513.
> Show create author option when many autocomplete results

- openlibrary/plugins/openlibrary/js/autocomplete.js
- openlibrary/templates/books/edit.html
- static/css/master.css
I realized I'd inadvertently partially resolved #174 with #606 , so decided to finish it up. Added some markup to the edit page so this can be discovered and made sure "Create Author" doesn't appear when searching by olid. This solution should work (until someone names their kid `OL1A`, anyways).
> Author autocomplete search-by-olid: ui tip + hide create author

- openlibrary/macros/LoanStatus.html
- openlibrary/plugins/upstream/borrow.py
This should be the final patch (for now) which fixes lending + waitlists across the board for OL
- uses realtime archive.org/metadata endpoint w/ dontcache=1 (for instant results w/o lag)
- replaced outdated db code w/ more accurate checks
> refactoring waitlist logic to answer my_turn_to_borrow correctly

- openlibrary/catalog/get_ia.py
- openlibrary/catalog/marc/test_parse.py
- openlibrary/catalog/marc/test_work_subject.py
- openlibrary/tests/catalog/test_get_ia.py
Following on from the recent discoveries about the import path, this PR allows imports to use the IA MARC XML files which have better handling of unicode characters.
Previously attempts to retrieve the MARC XML were failing because many did not have
the `<?xml` substring that the code was looking for...
> BUGFIX: allow import to get MarcXML

- conf/openlibrary.yml
- docs/design/feature-flags.rst
- openlibrary/plugins/upstream/merge_authors.py
To enable this feature toggle in production, the following lines will need to be added/modified in `config/openlibrary.yml`:
```
merge-authors:
filter: usergroup
usergroup: /usergroup/librarians
```
and `/usergroup/librarians` revised to include all the users who should have access to this feature.
> Allow trusted users to merge-authors

- openlibrary/plugins/openlibrary/js/autocomplete.js
- openlibrary/plugins/openlibrary/js/automatic.js
- openlibrary/templates/books/edit.html
- openlibrary/templates/books/edit/edition.html
- static/css/jquery.autocomplete.css
- static/css/master.css
Decided to do this as a separate PR first to make it easier to review.
Things to note:
- There could be a styling issue if something includes `master.css` without `jquery.autocomplete.css`, but I couldn't find anywhere where that would matter. I've left more general styling in `jquery.autocomplete.css`, and moved author/language specific styling to `master.css`
- `openlibrary/templates/type/edition/edit.html` uses the old `setup_autocomplete` method, but I can't find anywhere this template is being used
> Refactor autocomplete code

- openlibrary/macros/DownloadOptions.html
- openlibrary/macros/LoanStatus.html
- openlibrary/macros/SocialShare.html
- openlibrary/macros/daisy.html
- openlibrary/macros/databarWork.html
- openlibrary/templates/books/edition-sort.html
- openlibrary/templates/type/work/view.html
- static/css/master.css
addresses #721, shows daisy download if there's an ocaid but no lending or read options
> Re-show DAISY on books page with ocaid when no read/borrow options

- openlibrary/plugins/upstream/addbook.py
- openlibrary/plugins/upstream/models.py
- openlibrary/templates/books/edit/edition.html
- Markup now includes an example of an OpenLibrary ID
- Autocomplete results include subtitle; no longer just title
- Work page now queries database for editions if solr is outdated (which it will be after changing an edition's work)
> Change work from edition page fixes

- openlibrary/plugins/upstream/addbook.py
@cdrini , @mekarpeles This is a minimal change to fix #760 
The new feature added `works = None` to `edition_data` when previously there was no `works` key.
in https://github.com/internetarchive/openlibrary/blob/352b6cb833386875acd95141e221f8bbd84a3a64/openlibrary/plugins/upstream/addbook.py#L433
`self.edition.update(edition_data)`
`self.edition.works` was set correctly to the new work ID, but then it was being overwritten by the new `edition_data.works = None` in the `update()`.
This PR sets `edition_data.works` to the new ID, so the `update()` works as intended. Hopefully I have not broken any other use cases!
>  fixes #760

- openlibrary/plugins/openlibrary/js/ol.js
- openlibrary/templates/lib/nav_head.html
@mekarpeles The options for search were being translated and that was breaking the facet search, this is a quick fix to prevent that. 
The js changes below allow the 'Search by' label to show up in the target language. I have tested locally and search now looks good in Czech. There is a strangeness where `title: keyword` appears  in the search bar for title search that doesn't occur on any other facet, but I'm guessing there is a reason for that?
Would be good to test search further in dev. Please review, thanks!
> HOTFIX: I18n broke search bar

- openlibrary/plugins/upstream/models.py
> Wikipedia Citations updated

- openlibrary/i18n/fr/messages.po
On PR #801 @LeadSongDog attached a [strings.fr ](https://github.com/internetarchive/openlibrary/files/1732458/strings.fr.txt) , this is my attempt to move those strings to fr/messages.po  (as per #871) 
Tagging @roptat who expressed interest in helping with a French translation?
Please be aware that the source template has been recently updated, I've tried to tidy it as much as possible, but there will still unfortunately be some near duplicate messaging, probably unused strings, and missing messages. I'd love help to surface these sorts of issues and make the messaging better for _all_ languages (including English!) 
I'd suggest starting small, incremental addtions are prefectly OK at this stage, and focusing on the most important parts of UX.
> Start a French translation file

- openlibrary/plugins/openlibrary/pages/config_edition.page
Closes #725 & #811. Replaces #840.
This copies the current production https://openlibrary.org/config/edition.json and then overlays that HTTP -> HTTPS changes from #725 and adds an entry for Wikidata to resolve #811.
It is likely that something additional is needed to get this deployed back to the production servers. It also probably needs to be updated in the bootstrap database for the developers' vagrant.
> Sync production config/edition with git & add HTTPs & Wikidata

- openlibrary/plugins/upstream/code.py
Closes #805
- adds `/works/OL...W/{title}/merge?olids=` endpoint (which can be used to merge works and editions into this work) to `plugins/upstream/code.py` as `merge_work`
> Adding merge works endpoint

- openlibrary/templates/type/author/view.html
relates to #853 
* Displays ISNI if stored against an author under `remote_ids`
* The format expects ISNI to be stored _without_ spaces. Spaces are added for display.
* I have changed the existing VIAF and Wikidata link display so that only the id is clickable, which will hopefully make selecting and copy the id easier if a user just wants to get the id.
* enables a few more strings to be translated, e.g. 'Links'
> Display ISNI for Author records

- openlibrary/templates/type/author/view.html
Fixes author isni issue. At some point, a single space was introduced before the definition of `$ isni` within the template, causing it to be out of scope for the next line (which was not indented to the same depth)
> Fixing a spacing issue which was breaking isni for authors

- openlibrary/plugins/openlibrary/js/automatic.js
Closes #934 
re: #954 
Cc: @Num170R 
Hotfix to previous commit; should have targeted action `submit` instead of `click` (which seems to have been catching the click and preventing the submit
> original fix should have targeted submit, not click

- openlibrary/macros/LoanStatus.html
- openlibrary/plugins/openlibrary/js/availability.js
- openlibrary/plugins/upstream/models.py
- openlibrary/templates/books/edition-sort.html
Closes #844 
Previously, in order to render an openlibrary `work` page, we fetched all the work's editions and then individually checked their availability, one at a time. Now, we fetch all the work's editions, filter them to those which have archive.org IDs, and then send these ids in bulk, as a single request, to the availability v2 API. This drastically improves the load time of books pages
> fixing works page to load availability of all editions in one go

- openlibrary/macros/AvailabilityButton.html
- openlibrary/macros/SearchResultsWork.html
- openlibrary/plugins/openlibrary/js/availability.js
- openlibrary/plugins/worksearch/code.py
- openlibrary/templates/work_search.html
- static/css/master.css
Closes #733 
TL;DR: Fixing search to rm flickering, availability check moved to backend
When `ebooks` mode was selected, we used to rely on availability.js to filter out all books which didn't have ebooks. This is because our openlibrary solr things anything with an ocaid (i.e. archive.org ID) is an ebook, whereas many of these are printdisabled and can't be ready by the user. This availability check process was incorporated into the backend over our search results to prevent the interface from visually pruning records.
Also, fixes search results so they correctly show the user's waitlist + loan status on relevant titles.
> Fixing search to rm flickering, availability check moved to backend

- static/css/master.less
Contributes to #968, hotfixes some errors introduced by #1010 
* Fix invalid CSS properties: Autoformat clobbered some CSS property hacks, and this stops the Less from compiling properly.
> Hotfix: Fix some invalid css properties that came from the autoformatting

- openlibrary/accounts/model.py
Closes #834 
Integrates `service` param into `xauthn` API so archive.org activation success page can link back to the correct service for login (e.g. `service=openlibrary` should show an archive.org activation page which redirects to openlibrary.org)
> use xauthn service param, have archive.org activation redir to OL

- openlibrary/core/cache.py
- openlibrary/core/lending.py
- openlibrary/macros/AffiliateLinks.html
- openlibrary/plugins/openlibrary/code.py
- openlibrary/plugins/upstream/code.py
Amazon API is 503'ing, only allows 1 req / sec (baseline)
This PR:
- increases cache TTL from half day to one week
- re-caches if cached value is `None`
- doesn't generate price info for bot user_agents
> First round of fixing cache, no bots, re-cache

- docker/Dockerfile.olbase
- docker/Dockerfile.oldev
- docker/Dockerfile.olsolr
- docker/README.md
- docker/docker-compose.yml
- docker/ol-docker-start.sh
Added a solr image for docker. I had to update the openlibrary.yml file to make it point to the correct endpoint though, so this can't be merged yet without breaking vagrant. Any ideas on what the best way to handle those differences might be? I'm thinking creating a copy might be easiest, since that file is used in a lot of places.
> Solr Docker image

- openlibrary/plugins/openlibrary/pages/config_edition.page
Corrected the name "Regensburger Verbundklassifikation" and also the website. (plus http→https for Wikipedia)
> name correction "Regensburger Verbundklassifikation"

- .dockerignore
Small improvement to help when volume mounting local dev dir into a running container, to ignore the resulting .pyc and pycache dirs.
> dockerignore .pyc files

- static/css/components/editions.less
Follow up to 81252b7
When porting to the editions component this one CSS rule was missed.
> Retain list-style-none rule

- openlibrary/accounts/model.py
This is a small fix for an issue I was seeing in dev environments caused by stale cookies where the site thought a user was logged in but couldn't find an internetarchive itemname. All the account header info and login/logout buttons would fail to load.
Opening the site in an incognito window was a workaround.
This PR uses the pre-existing `itemname()` method to get the itemname or return `None` without errors.
I was actually testing #1133 and needed a small issue to debug and fix to see how editing and reloading code would work. This was an obvious error in dev.
> fix account header errors on dev

- openlibrary/core/bookshelves.py
- openlibrary/core/cache.py
- openlibrary/core/lending.py
- openlibrary/core/ratings.py
- openlibrary/core/stats.py
- openlibrary/plugins/openlibrary/home.py
- openlibrary/plugins/upstream/code.py
- openlibrary/templates/admin/index.html
- openlibrary/templates/stats/readinglog.html
- openlibrary/utils/dateutil.py
- openlibrary/views/loanstats.py
- static/css/master.less
Closes #742 
- makes a public version of /admin available as /stats
- updates the offerings of the /stats page and /stats/readinglog
- consolidates time CONSTs into utils/dateutil.py
> refactoring stats, making admin/stats public

- package.json
Adding a little script to run on `npm test` that
will make sure our CSS file doesn't grow in size.
If a commit is added that makes the CSS asset 'all.css' grow
in size, that commit will be rejected.
Fixes: #1124
> Limit the maximum size of all.css to 152.4kb

- static/css/components/dropper.less
Follow up to 980151a
.dropit is not a child of div.dropper
Thus CSS rules were not being invoked.
> Fix CSS regression relating to dropper height

- conf/openlibrary-docker.yml
- conf/openlibrary.yml
- docker/Dockerfile.olbase
- docker/Dockerfile.oldev
- docker/README.md
- docker/docker-compose.yml
- docker/ol-docker-start.sh
Closes #1063 
makes some changes related to ;) #1064 
and hopefully #1065
* Clarifies the split between `olbase` and `oldev` 
* `olbase` is a single application standard image that will run OL as the `openlibrary` user, needs to be deployed sensibly to be useful
* `oldev` has whatever else we need to operate our dev environment, i.e. pre-populated dev db, other services and tools. `oldev` may, and _should_, be reduced over time as we split out services.
* Volume mounts local dev directory and creates docker compose volumes to retain the js + css that was created at build time, and the `vendor` dir that is used to fetch git submodules, which is also populated on build.
* Uses a new `openlibray-docker.yml` config file to not interfere with vagrant, and avoids using `sed` to fix things. I'd …
> Docker-compose dev environment

- conf/openlibrary.yml
- openlibrary/templates/site/head.html
- package.json
Not having the viewport on some pages is making it hard to test
how it works in mobile. I'd like to turn it on in dev mode so that
I can focus on specific problems with pages.
Fixes: #1142
> Debug: In dev mode add viewport to all pages

- openlibrary/templates/lib/nav_head.html
- static/css/master.less
Rather than reinvent the wheel for asking to be hidden, make use
of the ".hidden" class and remove the now redundant CSS rule.
> account-dropdown uses common hidden class

- static/css/common.less
Closes #1181 
* Modified less file in order to make visible the save button
> Modified css in order for save button to be visible

- static/css/components/carousel.less
Avoid button flash on carousel
On slower connections, buttons are added to the carousel by JS
before JS styles have loaded. To avoid a jarring display keep
these transparent until the button loads.
Follow up to eaf3080
Fixes: #1182
> Button regress2

- static/css/components/footer.less
Closes #1196
changed footer.less to add the space between the footer text and github version
> Added margin between the footer text and github version

- openlibrary/templates/subjects.html
- openlibrary/templates/subjects/index.html
Right now the h2 element encapsulates a lot more than the heading
Be consistent with how the subject heading works
(the margin is redundant as inline elements do not have margins)
> Publishing history is an inline heading

- openlibrary/plugins/books/code.py
- openlibrary/plugins/openlibrary/code.py
For a while we've been relying on https://github.com/internetarchive/openlibrary/wiki/Endpoints#list-of-all-routes for an idea of what routes are active on OpenLibrary.org
closes #1211
There's also #1160 which was created in attempt to make it easier to centralize where routes live.
Unfortunately, this solution doesn't leave an artifact in the repository (e.g. no central routes file, as #1160 kind-of did). But you can go to `https://dev.openlibrary.org/developers/routes` and see a list of active routes and their handling classes.
cc: @jdlrobson, @cdrini, and @bfalling, @tabshaikh, @salman-bhai who may find this useful
> adds /developers/routes endpoint

- openlibrary/macros/databarDiff.html
- openlibrary/macros/databarHistory.html
Closes #1200 
The inactive buttons were as follows:
Now the buttons to lead to their expected functionality:
Fixed Inactive buttons
> WIP:Fixed Inactive buttons

- .stylelintrc.json
- static/css/components/Tools.less
- static/css/components/borrowTable-adminUser.less
- static/css/components/borrowTable.less
- static/css/components/buttonsAndLinks.less
- static/css/components/category-item.less
- static/css/components/cbox.less
- static/css/components/chart.less
- static/css/components/datatables.less
- static/css/components/diff.less
- static/css/components/dropper.less
- static/css/components/footer.less
- static/css/components/form.olform.less
- static/css/components/header-bar.less
- static/css/components/header.less
- static/css/components/headings.less
- static/css/components/home.less
- static/css/components/illustration.less
- static/css/components/resultsCovers.less
- static/css/components/ui-tabs.less
- static/css/components/wmd.less
- static/css/legacy.less
- static/css/page-book-widget.less
- static/css/page-design.less
- static/css/page-edit.less
- static/css/page-form.less
- static/css/page-plain.less
Closes #1099  
- Add removal of leading zeroes linting rule in `.stylelintrc.json`.
- Fix all offenders in `/static/css` that contained leading zeros by running `npm run lint:fix`.
> Omit leading zeros in css fractions

- openlibrary/templates/work_search.html
Closes #1224 
* Changed search bar width so that all adjacent choices are on a single line
> Remove inline style so that choices in search page are on the same line

- openlibrary/catalog/add_book/__init__.py
- openlibrary/core/ia.py
- openlibrary/plugins/importapi/code.py
- openlibrary/solr/update_work.py
This brings `/api/import` in line with recent improvements and error reporting added on `/api/import/ia`, removes duplicated code, and re-enables + improves the orphaned edition fixing on reimport functionality.
It also adds a method to _remove_ indexed fake-works for orphaned editions once the data is cleaned up. Previously they would remain in search results even after the data was fixed.
> /api/import Import refactor + enable orphan reimport

- openlibrary/templates/lists/widget.html
- openlibrary/templates/subjects.html
Lists still seem functional and are used in production on certain people's
list, so having an option to keep lists but exclude rating forms seems useful.
This removes the broken rating form from subject pages
Closes: #1244
> Ratings form removed from subject pages

- static/css/components/shareLinks.less
These rules are overly specific and will not be compatible
with the v2 version of this page.
Rules are simplified, reducing amount of CSS and improving
readability.
This will help me close out #1249
> Simplify the shareLinks styles

- static/js/vendor.jsh
In v2 pages (currently only home page) we will exclusively use the slick carousel. Use of
jCarousel on these pages will be forbidden. We only need one carousel to rule them all.
> Remove jCarousel from vendor v2 bundle

- openlibrary/macros/FulltextResults.html
On failure `results` is [] rather than a dict containing `hits`. This probably represents a larger issue further up the call-stack (where results should return `{hits: []}` instead. For now, this fixes a failure case on production.
> resolving issue where fts results failed

- static/css/components/dropper--tablet.less
Closes #1301 
- removes dropper styling which was causing css regression for reading log btn
> resolves 1301 readinglog dropper btn regression

- static/css/components/Tools--tablet.less
- static/css/components/Tools.less
On mobile the margins are unnecessary and take away valuable
screen real estate.
Due to vertical stacking contentBody's padding is all that's needed
here.
> Tools margins are set in tablet

- .stylelintrc.json
- package.json
- static/css/components/editions.less
- static/css/components/footer.less
- static/css/components/rating-form.less
We've been making good use of variables for color and z-index
but some have sneaked back in (presumably merge conflicts)
Let's prevent these happening any more.
Fixes: #1178
> Certain properties require variables

- static/css/components/Tools.less
- static/css/components/dropper.less
Closes #1218 
* Modified css rule to match the correct element so that dropdown menu not to overlap adjacent elements.
> Modified css rule to match correct element.

- Makefile
> fix flake8 error on build

- docker/Dockerfile.olbase
- scripts/bootstrap.sh
re-closes #1311
adds libffi-dev as docker + vagrant dep
> adding libffi-dev as apt dependency vagrant docker

- openlibrary/templates/covers/add.html
- openlibrary/templates/covers/manage.html
- openlibrary/templates/lib/covers.html
- openlibrary/templates/site/body.html
- static/css/page-form.less
- static/css/v2.less
Changes:
* Pages with id "form" no longer have a header in v2
or any banners
* No margin at the top of pages without a header
* Upgrade some $.ready calls to us the window.q
* Remove some jCarousel code which wasnt functioning before
the migration to v2 and continues not to function
* "three ways" => "two ways". presumably, we used to allow
selection of covers from a carousel, but it doesnt look like
that was working (at least for me locally) prior to making the
page v2
* Remove the float on the manage covers element - it was breaking
compatability with jquery ui. This forces it onto a new line.
Fixes: #1329
Fixes: #1199
> Fix add-cover and manage-covers

- package.json
A few changes to the edit toolbar styles in 06e64d7
and history component (04e229760) bumped up the bundle sizes
by a few bytes
This is blocking all changes in master.
> Bundlesizes for plain and user pages increased

- openlibrary/templates/books/edit.html
- openlibrary/templates/books/edit/addfield.html
- openlibrary/templates/books/edit/edition.html
- openlibrary/templates/books/edit/excerpts.html
- openlibrary/templates/books/edit/web.html
When we ported the books page to v2 we also ported all the other
books subpages, the code for which is tightly coupled.
Previously the covers feature was broken and now this was
identified.
Lesson learned... and we'll have to be more careful with that
in future.
Luckily making these edit pages v2 compatible is much more
straightforward.
Fixes: #1328
Fixes: #1346
> Restore JS on book editor

- openlibrary/templates/lib/covers.html
Fix subject page
Restore initialisation of the carousel on the subject page which
was removed in 9be3e32
This is shared between the cover manager and carousel but only needed
for the latter. At the time of removal it was throwing errors in the
former and thus removed. The actual right way to do this is to check
whether the functions are present in the page.
Closes: #1349
> Fix JS on subject page (1349)

- openlibrary/plugins/upstream/account.py
- openlibrary/templates/account/create.html
For #1248 
I'm pretty new, so please let me know if there were other tests I should be performed before submitting this pull request. It looks like everything works as before.
> Set the v2 and wrapped in window.q handler for issue #1248

- .stylelintrc.json
- package-lock.json
- static/css/components/Tools.less
- static/css/components/borrowBookForm.less
- static/css/components/cbox.less
- static/css/components/datatables.less
- static/css/components/diff.less
- static/css/components/dropper.less
- static/css/components/editions.less
- static/css/components/footer.less
- static/css/components/header-bar.less
- static/css/components/header-legacy.less
- static/css/components/headings.less
- static/css/components/home.less
- static/css/components/jquery.autocomplete.less
- static/css/components/link-box.less
- static/css/components/rating-form.less
- static/css/components/resultsCovers.less
- static/css/components/shareLinks.less
- static/css/components/ui-tabs.less
- static/css/components/wmd.less
- static/css/legacy.less
- static/css/page-form.less
- static/css/page-plain.less
Partial fix for #1119
Added `no-descending-specificity` rule to stylelint config and rearranged CSS selectors in 16 files to have selectors with lower specificity come first.
> Fix stylelint source order/specificity offenders

- openlibrary/plugins/openlibrary/js/jquery.repeat.js
Follow up to a199194 - the jquery.repeat plugin breaks with old
versions of jQuery
e.g. author edit page
This is because I didn't understand when writing that patch that
elements will be added to the interface after the code has run and
the document is ready.
Restore live, and its more modern counterpart in jQuery
1.11.0
Fixes: #1396
> jquery-repeat needs to support both active versions of jQuery

- package.json
c8dccf4 got past the censors.
We should be more careful when merging as all patches are now
failing validation which is confusing to new users.. :(
> JS bundlesize increases in size

- openlibrary/plugins/upstream/addbook.py
Closes #761 
* the /works/_autocomplete endpoint will exclude results that have a fake work key that actually represents an edition like `/works/OL12345M`
> exclude fake works that actually have an edition key from works autocomplete

- openlibrary/plugins/upstream/account.py
> emergency hotfix for account creation, v2

- package.json
- static/css/components/cover.less
- static/css/components/read-statuses.less
- static/css/js-all.less
- static/css/legacy.less
This component is only needed for JS so is loaded in the js-all
entry point.
Rather than use the nostyle-btn (not used anywhere else), we
style the generic button class
See: #1092
> Component: Read-statuses component

- static/css/components/header-bar.less
Add a max-width per @glatteis to the search dropdown
Tested on non-JavaScript browsers and this continues to
work as before on v2 pages.
v1 pages although functional, appear a little broken before
this patch and will continue to do so, but do not regress
Closes: #1347 
Previously:
Now:
> Search bar dropdown now has correct size

- static/css/components/listLists.less
I use !important per the detailed inline comment as this is
unavoidable until the legacy css can be safely removed.
Closes #1388
> xListList's should have no list-style

- openlibrary/catalog/add_book/__init__.py
- openlibrary/catalog/add_book/test_add_book.py
fixes #950
Now the imported will writeback an olid edition and work if the data matches an existing OL record and the import data contains an ocaid.
It will attempt to write back to archive.org regardless if it is making any modifications to the OL record.
This should also write back open library ids when re-importing an orphaned edition -- the work will be created , the edition updated, then `update_ia_metadata_for_ol_edition()` will send both the work and edition id to archive.org.
> writeback olids on import matching existing OL record

- openlibrary/plugins/books/dynlinks.py
- openlibrary/plugins/books/tests/test_dynlinks.py
Closes #1014 
API endpoint https://openlibrary.org/api/books?callback=func
was duplicating the callback -- `format_result()` was wrapping the result in the callback while the API was also handling the callback fn, so the results were doubled: e.g.
`func(func({}););`
This PR fixes it so now it returns:
`func({});`
or an example with results:
http://0.0.0.0:8080/api/books?bibkeys=OCLC%3A221499958&callback=func
```func({"OCLC:221499958": {"bib_key": "OCLC:221499958", "preview": "full", "preview_url": "https://archive.org/details/odysseybookiv00home", "info_url": "http://0.0.0.0:8080/books/OL24755423M/Odyssey_book_iv"}});```
> fixes #1014

- openlibrary/templates/publishers/view.html
Closes #1390 
removed the star ratings widget from publishers page
> WIP:Removed star ratings from the publishers page

- .travis.yml
There are several dependencies that are currently failing the __pip install__ on Python 3 (#1454, etc.) so let's run flake8 earlier in the process so we can see if this repo's code is Python 3 before moving on to the dependencie.
> Travis CI: make lint before pip install

- openlibrary/catalog/lang.py
- openlibrary/catalog/onix/xmltramp.py
- openlibrary/plugins/bookrev/code.py
Yet another subset of #1466 which lowers our __make lint__ Python 3 syntax errors from 19 down to 17.
This one is attempting to fix TabErrors that we see when we __make lint__ on Python 3:
```
./openlibrary/plugins/bookrev/code.py:43:72: E999 TabError: inconsistent use of tabs and spaces in indentation
edition = db.get_thing(form.d.edition, db.get_type('type/edition'))
^
./openlibrary/catalog/lang.py:47:15: E999 TabError: inconsistent use of tabs and spaces in indentation
if box.empty:
^
```
Python 3 treats a mix of tabs and spaces in indentation as a syntax error.  This fix was accomplished but running __reindent.py openlibrary/catalog/lang.py openlibrary/catalog/onix/xmltramp.py openlibrary/plugins/bookrev/code.py__ where __reindent.py__ is a file that ships in the __Tools/scripts__ …
> Fix TabErrors for Python 3

- .eslintrc.json
- openlibrary/plugins/openlibrary/js/add_new_field.js
- openlibrary/plugins/openlibrary/js/autocomplete.js
- openlibrary/plugins/openlibrary/js/lazy.js
- openlibrary/plugins/openlibrary/js/subjects.js
- openlibrary/plugins/openlibrary/js/utils.js
A few people have attempted to fix these warnings. Instead of continuing
to warn, let's document why these issues exist, and switch from a warning
to an error for future usages.
Also take the time to disable linting altogether on  lazy.js which should
be moved to vendor
Short term solution for #1489
> Avoid confusion with js linting

- openlibrary/plugins/openlibrary/tests/test_home.py
- openlibrary/tests/core/test_processors_invalidation.py
Yet another subset of #1466 that removes Python 3 syntax errors from two different files.  This is caused because __01__ meant octal 1 in Python 2 but this was not intuitive and resulted in difficult to debug errors as discussed [here](https://github.com/internetarchive/openlibrary/pull/1466#discussion_r229902687).
To remedy this situation, Python 3 treats __01__ as a syntax error and so __0o1__ the correct way to write octal 1 in both Python 2 and Python 3.
> Remove octal dates for Python 3

- openlibrary/templates/type/edition/view.html
We use the class shift to indent text (I'm guessing for screen readers)
This could be potentially bad for SEO, so I'd recommend against doing
this.
> Removed "shifted" content from HTML for ebook link

- openlibrary/catalog/lc_updates/update.py
- openlibrary/catalog/utils/edit.py
- scripts/2009/07/delete_spam_users.py
- scripts/solr_author_merge_work_finder.py
These fixes are modifications to Python files that use functions from Standard Library modules but do not actually import those modules.  This leads to an _undefined name_ situation which has the potential to raise __NameError__ at runtime if other Python files have not already imported the modules in question.
To defuse these _ticking timebomb_ situations, this PR advocates that all Python files explicitly import the Standard Library modules that they use.
These issues were discovered via a command that is _temporarily_ disabled in our __make lint__:
$ __python2 -m flake8 . --count --show-source --statistics --select=F821__
```
./openlibrary/catalog/utils/edit.py:56:22: F821 undefined name 'json'
prev = unmarshal(json.load(urllib2.urlopen(url)))
^ …
```
> Fix missing Python Standard Library imports

- openlibrary/catalog/merge/amazon.py
- openlibrary/catalog/merge/merge.py
- openlibrary/catalog/merge/merge_marc.py
- openlibrary/catalog/merge/names.py
Yet another subset of #1466 which deals with the fact that Python 3 requires explicit tuples in the "__in__" clause of a list comprehension.
This PR represents the output of __futurize -f lib2to3.fixes.fix_paren -w__ which adds the missing parentheses which works as expected in both Python 2 and Python 3.
424 days until Python 2 end of life.
> Explicit tuple in Python 3 list comprehensions

- openlibrary/macros/LoanStatus.html
- openlibrary/templates/books/edition-sort.html
- static/css/legacy.less
Read eBook button no longer needs to be a "read-btn"
This class is making the button appear smaller than it needs to be now
that it's using btn--large now (the standardised button style going forward)
The works page is the only other consumer of the read-btn and that looks
like a btn primary.
There are no references to read-btn in JS
so goodbye read-btn!
Fixes: #1499
> Goodbye read-btn (conflicts with btn--large)!!

- static/css/components/cbox.less
(This minor change cleans up the CSS a little by making it more obvious how components are supposed to behave)
Rather than rely on helper class "shift" which I want us to move
away from, I want to explicitly make the shifting of the close icon
happen inside the cbox component.
> Hide label of cbox close icon for floaterShut

- openlibrary/templates/type/edition/view.html
- openlibrary/templates/type/work/view.html
- static/css/components/link-box.less
Closes #1323 
- The works and books pages have been updated to use the linkbox component styling
- HTML markup has been updated to reflect existing usage, in order to take advantage of the styling rules
- Redundant CSS classes have been removed
- `.contentQuarter` and `.linkBox` classes have been separated in order to make the linkBox component more versatile
> Refactor works and books pages to use linkbox component

- openlibrary/catalog/onix/xmltramp.py
- openlibrary/plugins/openlibrary/stats.py
- openlibrary/plugins/upstream/borrow.py
Yet another subset of #1466 which deals with the fact that __dict.has_key(key)__ was removed from Python 3 in favor of __key in dict__.
This PR represents the output of __futurize -f lib2to3.fixes.fix_has_key -w o*.__ which adopts  the __"in"__ syntax which works as expected in both Python 2 and Python 3.
424 days until Python 2 end of life.
> Fix has_key() for Python 3

- requirements_common.txt
Yet another subset of #1466 as discussed at: https://github.com/internetarchive/openlibrary/pull/1466#discussion_r230570214
We are going to need six (or similar) to get to Python 3 compatibility without breaking Python 2.
> Requirements: six==1.11.0

- openlibrary/templates/subjects.html
- static/css/components/chart.less
- static/css/legacy.less
The chart component as featured on the subject page, doesn't work
well at mobile resolutions.
We limit the problematic styles to the desktop breakpoint
Additional changes:
* The count style is also problematic on mobile, so we moves its
whitespace property in the legacy file. The styles stay in legacy
as I'm hoping to see these removed in the revised page stylesheet.
> Mobile friendly chart component

- openlibrary/catalog/utils/__init__.py
- openlibrary/plugins/search/facet_hash.py
- openlibrary/plugins/upstream/account.py
- openlibrary/solr/facet_hash.py
- scripts/ol-solr-indexer.py
The builtin __xrange()__ was removed in Python 3 in favor of __range()__ so this PR uses [__six.moves.range()__](https://six.readthedocs.io/#module-six.moves) as a replacement that works as expected in both Python 2 and Python 3.
> Builtin xrange() was removed in Python 3

- openlibrary/plugins/bookrev/dev.py
- openlibrary/plugins/bookrev/utils.py
The builtin __raw_input()__ was removed in Python 3 in favor of __input()__ so this PR uses [__six.moves.input()__](https://six.readthedocs.io/#module-six.moves) as a replacement that works as expected in both Python 2 and Python 3.
> Builtin raw_input() was removed in Python 3

- openlibrary/plugins/openlibrary/dev_instance.py
The builtin __execfile()__ was removed in Python 3 so this PR opens the file in question and then calls __exec()__ on its contents which should work as expected on both Python 2 and Python 3.
> Builtin execfile() was removed in Python 3

- static/css/components/dropper.less
Closes #1507  
Description:
Previously the Reading list-dropdown was displacing other content on the page. It's no longer the case.
> Fix Reading list dropdown displacing other content.

- static/css/base/helpers-misc.less
These helpers all do the same thing. Since these are helpers, where
they are not using !important, make them use !important
In future we will look to reduce these helpers or remove them
> You won't believe the redundancy hidden in our helper files!

- openlibrary/plugins/openlibrary/js/ol.js
If the form element has no 'action' property set, then
a JavaScript error is thrown. Guard against this from
happening.
Fixes: #1529
> Protect against error where form action is undefined

- openlibrary/coverstore/utils.py
The builtin type __file__ was removed in Python 3 so this PR uses __io.IOBase__ as a replacement that should work as expected in both Python 2 and Python 3.
> Builtin file was removed in Python 3

- requirements_common.txt
See https://pypi.org/project/argparse for a discussion about how __argparse__ has moved into the Python Standard Library for all currently supported versions of Python.
> Remove argparse from requirements_common.txt

- openlibrary/coverstore/code.py
- openlibrary/plugins/search/solr_client.py
These are syntax errors in Python 3...  See __make lint__ when run on Python 3 for confirmation.
This is yet another in a long list of subsets of #1466.  It represents an edit of a partial set of the fixes that would get executed via __futurize -f lib2to3.fixes.fix_tuple_params -w .__.  This set of changes is about __functions__ while to other set is about __lambdas__ but those changes were deemed to have readability issues so they will be addressed in a separate PR.
> Function parameters may not be explicit tuples in Python 3

- openlibrary/templates/site/alert.html
- openlibrary/templates/site/donate.html
In the past, we've had issues with search engines (bots) indexing our donation banner code. Ideally we'd have the right metadata so donations banners don't show up. In this PR, we don't render donation banner code if the useragent is a known bot.
> don't show donation banner for bots, seo

- openlibrary/templates/work_search.html
- static/css/components/search-result-item.less
- static/css/components/search-results-container.less
- static/css/legacy.less
A few changes have been made to the CSS:
* .resultTitle h3.booktitle only matches on the search
pages. Other pages which use booktitle do not match resultTitle, so
css rule can be expressed in terms of the new search-result-item component
* searchResultItemCTA is not going to be needed going forward, so although
right now this is used to style this component it will not do so in future.
A general padding/margin rule for direct descendants of search-result-item
will be used in its place.
* A new more descriptive class matching the component name will be used
going forward (search-results-container)
See: #1092
> Stop your searching: The latest component on the block is a stunner!

- Makefile
- openlibrary/plugins/worksearch/subjects.py
- openlibrary/templates/subjects.html
- package.json
- static/css/base/common.less
- static/css/base/helpers-common.less
- static/css/base/helpers-misc.less
- static/css/components/form.olform.less
- static/css/components/page-heading-search-box.less
- static/css/legacy.less
- static/css/page-subject.less
Flesh out page-subject with its components
* subject page now ships 5.9kb of CSS (down from 25kb)
* slight increase in home page css to account for
the very useful #contentHead
Fixes: #1541
> You won't believe how much I reduced the subject page CSS from 25kb to...!

- static/css/components/buttonBtn.less
Depending on where the button is defined, it can have different
font sizes if using ems. We want this to always to be this many
pixels
> Set a fixed font-size for btn--large

- openlibrary/catalog/onix/thread_utils.py
This is yet another subset of #1466. [__six.reraise()__](https://six.readthedocs.io/#six.reraise)
> six.reaise() will reraise exceptions in Python 2 and 3

- openlibrary/utils/form.py
This is yet another subset of #1466.  Old style exceptions are syntax errors in Python 3 while new style exceptions work as expected in both Python 2 and Python 3.
> Raise new style exceptions in form.py

- openlibrary/coverstore/warc.py
This is yet another subset of #1466. Old style exceptions are syntax errors in Python 3 while new style exceptions work as expected in both Python 2 and Python 3.
> Raise new style exceptions in warc.py

- openlibrary/plugins/upstream/utils.py
This is yet another subset of #1466. Old style exceptions are syntax errors in Python 3 while new style exceptions work as expected in both Python 2 and Python 3.
> Raise new style exceptions in utils.py

- openlibrary/plugins/openlibrary/js/ol.js
On mobile the only way to reveal a menu is to click it.
These JavaScript event handlers close it. You may have noted
how its really hard to click menus on mobile (and sometimes desktop)
and this code appears to be the reason why.
The code doesn't seem to do anything useful. It looks to me like it
was written back in a time when these menus were not implemented via
CSS.
Fixes: #1575
> Remove menu JavaScript

- openlibrary/plugins/search/code.py
- openlibrary/plugins/search/collapse.py
- openlibrary/plugins/search/solr_client.py
Yet another subset of #1466 which deals with the fact that Python 3 prohibits parentheses around lambda parameters.
This PR represents the output of __futurize -f tuple_params -w .__ which works as expected in both Python 2 and Python 3.  https://github.com/python/cpython/blob/master/Lib/lib2to3/fixes/fix_tuple_params.py
> Python 3: Fix tuple_params

- openlibrary/templates/publishers/notfound.html
- openlibrary/templates/subjects/notfound.html
by not using them, in the v2 format where certain styles are not loading
, they become misaligned.
Fixes: #1605
> Publishers and subject pages use page-heading-search-box component

- openlibrary/templates/lists/lists.html
- openlibrary/templates/type/list/embed.html
- openlibrary/templates/type/list/view.html
- static/css/legacy.less
The list page has transitioned to v2 (accidentally?)
but it's JS is broken.
This patch fixes the JS calls and removes some unnecessary CSS
that breaks mobile (and desktop!) display
Fixes: #1427
> Fix v2 list page

- openlibrary/plugins/copyright/copyrightstatus/ca.py
- openlibrary/plugins/search/code.py
- openlibrary/plugins/search/solr_client.py
The __with__ syntax is supported Python >= 2.6 so this anachronistic import statement is not longer required in currently supported versions of Python.  https://docs.python.org/2/library/__future__.html
> Remove from __future__ import with_statement

- openlibrary/core/processors/readableurls.py
- openlibrary/plugins/openlibrary/design.py
- openlibrary/plugins/openlibrary/status.py
- openlibrary/plugins/openlibrary/support.py
- openlibrary/plugins/worksearch/code.py
- openlibrary/templates/design.html
- openlibrary/templates/forgot_password.html
- openlibrary/templates/improve_search.html
- openlibrary/templates/showamazon.html
- openlibrary/templates/showia.html
- openlibrary/templates/showmarc.html
- openlibrary/templates/status.html
- openlibrary/templates/support.html
- openlibrary/templates/widget.html
- openlibrary/views/showmarc.py
- static/css/base/common.less
The following pages are now v2
* /status
* /support
* /show-records/<id>
* /developers/design
* /improve_search
* /advancedsearch
Given there lack of JavaScript the transition to v2 was
trivial.
Additional changes:
* A style is added to ensure that long words are broken onto new
lines where necessary
* Document how certain templates are accessed
> Transition simple pages to v2

- scripts/copydocs.py
Closes #1587 
The problem was that the copydocs script used the default port 8080 for the destination, rather than 80.
This PR corrects that.
The Docker container does have external network access
> dev environment copydocs script to use port 80 as the local default to match Docker environment

- .travis.yml
Before this change apt installs the older python-lxml and python-yaml and then [pip reinstalls lxml and PyYAML](https://github.com/internetarchive/openlibrary/blob/master/requirements_common.txt#L9-L17).  This PR proposes to reduce the clutter by removing the former and keeping the latter because that gives us more control over which versions get installed.
> Travis CI: Remove redundant apt install of lxml and yaml

- requirements.txt
__ordereddict__ is part of the Python standard library in all versions of Python supported by OpenLibrary so a separate pip install is no longer required.  https://pypi.org/project/ordereddict
https://github.com/internetarchive/openlibrary/search?q=ordereddict
> requirements.txt: Remove unused OrderedDict

- static/css/base/common.less
Fixes #1642
Removed `height:auto` from `static/css/base/common.less`
> Fixing homepage bookcover height

- openlibrary/catalog/edition_merge/merge_works.py
- openlibrary/catalog/marc/db/web_marc_db.py
- openlibrary/catalog/utils/__init__.py
- openlibrary/catalog/works/by_author.py
- openlibrary/catalog/works/find_works.py
- openlibrary/catalog/works/live.py
Related to #890
__cmp()__ was removed in Python 3 so this PR conditionally defines in Python 3.
> Define cmp() in Python 3

- openlibrary/plugins/openlibrary/js/jquery.repeat.js
In a1991944062a7f6daf4b4703476038e0e0eecda0 I fixed a broken selector
which surfaced a new bug. Looking at this some more it is likely
trying to clear the input fields for the link so they don't get
added multiple times. Fix how this works by making it a side effect
of formdata in lieu of a big rewrite.
Add some documentation so the next person understands a bit better
what this is trying to do.
Fixes: #1663
> Fix link adding on author and book edit pages

- openlibrary/plugins/upstream/utils.py
Feature, Closes #1671 
There are security consequences (people being able to load code into openlibrary from their client)
Change your local archive.org VM (e.g. www-brenton) and add `dev_host` as a GET parameter:
e.g. https://openlibrary.org/?ymd=2018-11-28&dev_host=www-brenton
You should see your version of `includes/donate.php` (from petabox)
> enable archive.org-ers to test promo banners w/o reload

- openlibrary/catalog/amazon/parse.py
__unichr__ was removed in Python 3 so this PR proposes to use [__six.unichr__](https://six.readthedocs.io/#six.unichr) instead.
> Undefined name: unichr() --> six.unichr()

- scripts/manage-imports.py
__ia_id__ is an undefined name in this context so this PR recommends using __ocaid__ instead so as to mirror the logic of lines 130-134.  Related to #1508 and #1684 @YBthebest Your review please.
> Undefined name: 'ia_id' --> 'ocaid'

- scripts/lc_marc_update.py
__from openlibrary.catalog.importer.scribe import BadImport__ resolves four _undefined names_ from #1508 and #1684  @YBthebest, your review please.
> Undefined name: BadImport

- requirements_common.txt
Let's assume that #1679 and #1680 have landed (they have NOT)...  What dependency next blocks the Python 3 build on Travis CI?  __Answer: python-memcached==1.48__
* https://travis-ci.org/internetarchive/openlibrary/jobs/464533444#L788
> requirements_common.txt: Upgrade python-memcached==1.59 for Python 3

- openlibrary/catalog/get_ia.py
These two functions are marked DEPRECATED for the same issues that flake8 raises.  Related to #1684
> Add # noqa linter directives to DEPRECATED functions

- requirements.txt
- requirements_common.txt
- requirements_test.txt
This issue is directly related to #1679, #1680, #1638, #1694, #1687 and indirectly related to #1522 and #1634.
Certain Python dependencies do not currently have an acceptable Python 3 equivalent and they block our Travis CI build process in the install step.  This PR proposes to use the conditional capabilities of _requirements.txt_ files to only install these modules on legacy Python and not install them on Python.  This _should_ allow us to get past the install step and start running our PyTests.
[__$ pip install -r requirements_test.txt__](https://travis-ci.org/internetarchive/openlibrary/jobs/465262458#L745)
```
Ignoring Genshi: markers 'python_version < "3.0"' don't match your environment
Ignoring iptools: markers 'python_version < "3.0"' don't match your environment
Ignoring …
```
> Disable problematic requirements only on Python 3

- openlibrary/plugins/oltemplates/olmanage.py
'__error__' is an _undefined name_ in these contexts so a __NameError()__ will be raised.  This PR proposes to instead raise a more appropriate __ValueError()__ with a message about the value in question. Related to #1684.
$ __make lint__  # returns...
```
./openlibrary/plugins/oltemplates/olmanage.py:25:9: F821 undefined name 'error'
error
^
./openlibrary/plugins/oltemplates/olmanage.py:41:9: F821 undefined name 'error'
error
^
./openlibrary/plugins/oltemplates/olmanage.py:54:9: F821 undefined name 'error'
error
^
./openlibrary/plugins/oltemplates/olmanage.py:66:13: F821 undefined name 'error'
error
^
./openlibrary/plugins/oltemplates/olmanage.py:77:9: F821 undefined name 'error'
error
^
```
> Raise informative ValueError() instead  of unhelpful NameError()

- static/css/components/illustration.less
hotfix Closes #1704 
May not be the best css solution
See issue: go to any editions page, the bookcover
Before:
After:
> fixing bookcover size on editions page

- docker/Dockerfile.olbase
While installing the python packages (through Dockerfile.olbase) if the net connection is slow then the installation of packages fails due to [ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443)].
Thus to overcome this problem if we make the changes in the image file(Dockerfile.olbase) then the packages will be installed smoothly without any error
Closes #
In the **dockerfile.olbase** I changed
RUN pip install -r requirements_common.txt
to-
RUN pip install --default-timeout=100 -r requirements_common.txt
(100 is the the number of seconds pip'll wait for the reconnect after losing connection)
> fix ReadTimeOutError while installing python packages

- openlibrary/templates/account/borrow.html
Remove an inline style.
contentHalf has a max-width of 439px on tablet devices defined
in the stylesheet so this is unnecessary
This completes the optimisation of the loans page
Fixes: #1510
Closes #
> Optimise loans page for mobile

- openlibrary/core/helpers.py
- openlibrary/tests/core/test_helpers.py
- openlibrary/tests/core/test_olmarkdown.py
- requirements_common.txt
Closes #1455
This adds an optional encoding parameter to `helpers.sanitize()` with a default value of None (same as Genshi 0.7.1). Normally callers should provide unicode strings, but this may allow them to specify the encoding easily if they have bytes. The test suite has been updated to pass Unicode strings, but I have *not* inspected all the calls to `sanitize()` to see if there are any likely problems spots. Since they're often using the results of some other code, inspection won't be easy, so we'll probably just need to find problems as we go.
> **Evidence**: If this …
> Upgrade to Genshi 0.7.1

- static/css/components/read-panel.less
This style makes the table take up 100% of the width of the component
and aligns the price to the right. This maximises the space between
the label and the price.
Fixes: #1752
Closes #
> ReadPanel alignment issues

- openlibrary/core/helpers.py
hotfix which switches the default encoding for sanitize from None to "utf8" where None means Python unicode strings (ie already decoded).
This needs a test, but creating the patch first since it's time critical.
Closes #1758
> Switch default to sanitize(encoding=utf8) Fixes #1758

- openlibrary/core/helpers.py
Followup to
- encoding in python2 can no longer be None, should be 'utf8'
- https://genshi.readthedocs.io/en/latest/upgrade/#upgrading-from-genshi-0-6-x-to-the-development-version
related to  #1758
assumes we're ok w/ falling back to utf8
> Cleans up helper.py styles

- openlibrary/core/lending.py
- openlibrary/plugins/openlibrary/api.py
- openlibrary/plugins/openlibrary/home.py
- openlibrary/plugins/upstream/models.py
- openlibrary/templates/books/custom_carousel.html
- openlibrary/templates/type/work/editions_datatable.html
- python errors due to cache miss
- len(editions) check when editions None
- editions pluralization on works page (for len(works)==1)
- prepares search results for showing "no ebook available" disabled btn
> fixes misc python errors

- openlibrary/templates/type/author/view.html
- openlibrary/templates/type/edition/view.html
The medium sized images falls under the guidelines for Facebook
and on social media the better quality the image the better (clients
for both Facebook and Twitter scale these down as necessary)
Fixes: #1778
Closes #
> Use large images on author and books page for og:image tag

- openlibrary/templates/search/authors.html
- static/css/legacy.less
Search results on authors should not break mobile display
Fixes: #1786
Wrap Author search results in contentBody
A clear fix is added to cancel floating on tablets/desktop
Fixes: #1790
> Author search fixes

- openlibrary/plugins/openlibrary/js/jsdef.js
In 2f58b99 we removed a duplicate htmlquote function but took
away a crucial line that is being used by template.js
After trying to resolve the issue inside template (which uses
eval!!) without any luck I decided to document the function
signature to make it clear why this is needed.
Fixes: #1796
Fixes: #1795
Closes #
> Fix compatibility with jQuery repeat add forms

- openlibrary/templates/lib/nav_head.html
- static/css/base/common.less
- static/css/components/header-bar--desktop.less
- static/css/components/header-bar--tablet.less
- static/css/components/header-bar.less
Follow up to f0514f94
The donate banner hack uses a header element so the styles inside
header-bar are too generic. We don't want to restore the id selector
as id's are restrictive and not reusable rules (while we probably don't want more
than one header-bar... you never know.
So instead, we add a new class header-bar on the element and use that
for styling
Closes #
> Header-bar class to avoid donate banner hack

- .dockerignore
- .gitignore
**Description**: Remove vagrant from .ignore files [refactor]
**Technical**: You should now delete the .vagrant folders (run `vagrant destroy` first!), if you still have them! Don't accidentally commit them :P
Progress towards #1134
> Remove vagrant from .ignore files

- static/css/base/common.less
- static/css/components/read-panel.less
Alter the rules around tables on mobile - they remain display
block but we reverse the media query and apply block to the other
table elements.
A rule is needed in read-panel to ensure that the columns take up
50% of the space for the price table.
Fixes: #1752
Closes #
> Read-Panel price table

- static/css/components/ui-dialog.less
- static/css/js-all.less
- static/css/legacy.less
Fixes: #1559
Restores the ui-dialog by pulling it onto pages which are not using the legacy.less file.
It moves CSS from one file to the other.
> Component: UI-Dialog

- openlibrary/plugins/upstream/addbook.py
- openlibrary/templates/books/edit.html
- openlibrary/templates/books/edit/edition.html
**Description**: Edits to a work are ignored if moving an edition.
Closes #1662
**Testing**: I'll run the following manual tests on dev as well. @hornc Any direction on how/where these tests could be added to the code?
| Test | Local | Dev |
|------|-------|-----|
| Editing a work | ✔️ | |
| Editing an edition | ✔️ | |
| Moving Edition | ✔️ | |
| Edits to Work are ignored when moving an edition | ✔️ | |
| Spamming save button when moving edition doesn't strip work of data | ✔️ | |
| Editing a work and an edition at the same time | ✔️ | |
> Prevent work edits when moving an edition

- openlibrary/templates/type/edition/view.html
- static/css/components/illustration.less
- static/css/components/readerStats.less
- static/css/components/ui-tabs.less
- static/css/js-all.less
- static/css/legacy-jquery-ui.less
- static/css/legacy.less
This tidies up legacy.less  a little, moving JS specific styles off the critical path and restoring a subtle styles for the rating stars.
Before:
After:
> Legacy rules cleanup

- openlibrary/macros/AvailabilityButton.html
- openlibrary/macros/LoanStatus.html
- openlibrary/templates/books/edition-sort.html
- static/css/base/helpers-common.less
- static/css/components/buttonCta.less
- static/css/components/searchResultItemCta.less
- static/css/legacy-tools.less
- static/css/legacy.less
Styling a cta-btn is complicated. This minimises the number of
classes needed and changes the classes to use BEM notation
It should be easier going forward. While it was tempting to create
a macro, it didn't seem to add much given the fact that cta-btn's can
be inputs or anchor tags and thus have various other attributes.
> Component CtaBtn: Consolidate cta-btn rules

- requirements_common.txt
__supervisor__ does not yet have an official Python 3 release but this gets us as close as we can be without grabbing the HEAD.
> requirements_common.txt: Upgrade to supervisor==3.3.4

- openlibrary/macros/SearchResultsWork.html
- openlibrary/templates/lists/lists.html
- openlibrary/templates/lists/preview.html
- static/css/components/search-result-item.less
- static/css/components/searchResultItemCta.less
- static/css/legacy.less
> **Description**: What does this PR achieve? [hotfix]
- Prevents thumbnails from getting squished in lists (mobile view)
- Thumbnails getting cut off resolved by PR #1838 by @jdlrobson 
Closes #1762 
http://0.0.0.0:8080/people/openlibrary/lists
http://0.0.0.0:8080/account/books/want-to-read
Lists (mobile view)
Want to read
Want to read (mobile view)
> Fix squished thumbnails on list pages

- static/css/legacy.less
A search of the templates and JS within the repo and its
submodules yields no results for the following:
.olPopupContent
.olPopup
ul.contributors
.formFieldsDecoration
.formFieldsErrorMsg
.authorlinks
.indent
ul.serp
div#adminTwitter
table.records
.olControlAttribution
.tweet_user
.searchSuggest
.word-corner-badge
.recordsAdd
div#emailLoading,
div#emailResult,
div#usernameLoading,
div#usernameResult
.optionsScript
.gradient
.contentLists.results
.facet-options
div.pingList
ul.urlList
.bookMeta
.Year
.Publisher
div#listsWork
.branches
.box-shadow-menu
.lists-loader
.myreads-options
.mybooks-list-options
.reading-lists-title
As a result, those styles and all their nested selectors are
removed.
All remaining legacy styles are documented so it's clear where to
look when componentising them.
> …
> Note usages in legacy and remove unused CSS selectors

- openlibrary/templates/books/edit/edition.html
- static/css/base/common.less
- static/css/components/form.olform.less
- static/css/components/ui-tabs.less
- static/css/legacy.less
TitleAuthor only ever appears on the book edit page, so these
styles are migrated and generalised inside form.olform
The float, clear and width of .TitleAuthor
are unnecessary (serving no purpose) so are dropped completely
The label rule is also unnecessary as
it is overriden by the more specific .olform .label label
and TitleAuthor is only ever used in the edit page.
Closes #
> Migrate/remove some CSS in legacy associated with edit form

- openlibrary/core/vendors.py
- openlibrary/plugins/openlibrary/api.py
Fixes /prices API (it used to be /prices/isbn/xxx and is now /prices?isbn= or ?asin=). Currently, asin doesn't work, however the plan is for @hornc to extend this to work with isbn, asin, title, authors.
This patch needs to be merged because otherwise the /prices API physically breaks when importing new amazon works.
> fixes price API, isbn now passed as GET param

- openlibrary/templates/type/edition/view.html
Adds the correct affiliate tag to all ID Number links to Amazon domains from the Edition view page.
to test using this book with multiple international amazon identifiers: https://openlibrary.org/books/OL25443597M/City_Times_Other_Poems
> add amazon affiliate tag to ASIN id links

- static/css/components/dropper.less
fixes height padding of want-to-read list drop-down for orphaned editions
> fixing add-to-list dropdown for orphaned editions

- openlibrary/plugins/openlibrary/js/ol.js
It used to be the case that if you had the reading log / lists dropdown expanded and clicked outside of the area, that it would not collapse. Now it does!
It uses a `$(document).on('click', ...)` which maybe isn't an ideal implementation as it will run on all clicks. This should only be included on certain pages but is currently in `plugins/openlibrary/js/ol.js`
> fixing click-outside readinglog btn

- scripts/copydocs.py
> **Description**: Changes copydocs script default destination to `localhost`, as it is more convenient for users.
Closes #1906 
> **Testing**: use `copydocs.py` without any dest argument. It should copy to localhost.
I also changed the usage of copydocs in the wiki.
> Changed copydocs default destination to localhost

- openlibrary/plugins/openlibrary/js/autocomplete.js
- openlibrary/templates/books/author-autocomplete.html
Closes #1901 
Previous update to `live` methods did not properly bind click events to the parent container, so any newly added elements did not have click events bound or listening to the elements. Additionally, a class of "hidden" was present on the add author and remove links. Removing those classes allowed the controls to be visible.
See above.
> Fixes author add and remove controls

- requirements.txt
based on comments on https://github.com/internetarchive/openlibrary/pull/1634
> **Description**: What does this PR achieve? [refactor]
Removes requirement dependencies that are only used for the specific production setup we are trying to deprecate and standardise. I believe these particular requirements are overridden by the specifics of olsystem / the production environment anyway, so they are just noise in this codebase.
There are probably other items from this requirements.txt that can be removed -- due to either an oversight, or deliberate policy of only moving known used requirements to `requirements_common.txt` the `requirements.txt` file is never actually used in creating any of the Docker images for the dev …
> remove non-Docker non OL requirements

- openlibrary/plugins/openlibrary/pages/languages.page
Closes #1558 
Adds the language Mirandese to the list of languages. This is _NOT_ complete as this needs to be loaded into thing store so it can be returned by `web.ctx.site.things({"type": "/type/language", "key~": "/languages/*", "limit": 1000})`    Need to be sure that this takes effect in both production and dev.
> add new language, Mirandese

- static/css/legacy-wmd.less
- static/css/page-edit.less
hotfix
Closes #1912 
> **Earlier Mobile View**
> **Evidence (Now)**: 
Desktop View
Mobile View
> Correct faulty css in edit form make it completely responsive

- static/css/legacy-wmd.less
The textareas overspill the viewport due to these rules
in legacy-wmd
With this change, the entire form fits into a mobile viewport.
Hurrah!
Fixes: #1585
Closes #
> Edit page is now fully responsive

- docker-compose.yml
based on discussion https://github.com/internetarchive/openlibrary/pull/1856/files#r253220282
Uses the latest spec recommended spec for docker-compose. I'm not sure what problem the downgrade to 2 was solving, but I think @cdrini, me, and anyone else who edited the docker-compose.yml were relying on v3 definitions. If there is something in there that isn't valid as part of v3, it should be updated to be valid in v3.
See https://docs.docker.com/compose/compose-file/compose-versioning/  for official statement on recommended version and a link to the spec.
> Reinstate recommended Docker-Compose v3

- openlibrary/templates/books/edit/edition.html
- static/css/legacy.less
> **Description**: What does this PR achieve? 
Feature modification: always enabling librarian mode.
Also removes unused code for toggling librarian mode.
Correct faulty css for "Classifications" field
Closes #1934 
**Evidence**: If this PR touches UI, please post evidence (screenshot) of it behaving correctly:
Earlier:
Now:
> Edit Page: Always enable librarian mode and remove unused code

- static/css/components/mybooks-list.less
> CSS corrected
Closes #1913 
> **Evidence**:
> list overflow corrected

- openlibrary/plugins/importapi/code.py
- openlibrary/plugins/openlibrary/types/local_id.type
- openlibrary/templates/type/local_id/view.html
Generalises the local_id importing to store searchable organisation `local_ids` with MARC records imported from that organisation. 
New optional API param: https://github.com/internetarchive/openlibrary/wiki/Endpoints#importing for bulk MARC imports.
```
"local_id": <id>
```
> Use local_id type lookup for partner bulk_marc sources

- static/css/components/edit-toolbar.less
- static/css/legacy.less
Hotfix: Styles editTools block and child elements to be more mobile friendly
Closes #1874 
Added code passes linter, but it seems code was introduced 2019/02/11 to static/css/components/search-result-items.less that throws errors.
Visit a title's show page within the mobile breakpoint (< 768px width)
> Styles editTools block for mobile breakpoint

- openlibrary/catalog/add_book/__init__.py
- openlibrary/core/vendors.py
- openlibrary/plugins/worksearch/code.py
closes #1783 and closes #1461, relates to #1457
> fixing amz isbn lookup to use ImportBot

- openlibrary/macros/LoanStatus.html
- openlibrary/templates/books/custom_carousel.html
before the buttons said "borrow ebook", "join waiting list" and "read ebook". Now they say:
"read", "borrow", or "join waitlist"
> simplify & standardizing copy for all cta buttons

- conf/coverstore.yml
- docker/Dockerfile.oldev
- openlibrary/catalog/add_book/__init__.py
Closes #1910
developers will need to rebuild just the `oldev` image to use this fix locally:
docker build -t oldev:latest -f docker/Dockerfile.oldev .
You can now POST directly to local dev coverstore using curl, e.g.:
curl -XPOST --data "source_url=https://archive.org/download/9788578793319/9788578793319/page/title.jpg" http://0.0.0.0:8081/b/upload2
Expected response:
{"ok": "true", "id": 1}
And the covers will be available at:
http://0.0.0.0:8081/b/id/1-S.jpg
http://0.0.0.0:8081/b/id/1-M.jpg
http://0.0.0.0:8081/b/id/1-L.jpg
> Fix dev environment Coverstore upload

- openlibrary/core/ia.py
- openlibrary/plugins/importapi/code.py
- openlibrary/templates/history/comment.html
Improves the metadata importing from Archive.org items that do no have MARC records.
The following item,  https://openlibrary.org/books/OL26746219M , was imported using the https://github.com/internetarchive/openlibrary/wiki/Endpoints#importing `POST /api/import/ia` endoint `"require_marc": "false"` option, and had some issues / missing metadata. This PR fixes those.
* Correct language format: `/languages/por` instead of `por`
* Import _all_ subjects
* Import description, if available
* Import publisher and publication date
* Import other identifiers if avaialable (ISBN, OCLC, LCCN)
* Change history message for archive.org imported items to: "Initial record created, from Internet Archive item record." to avoid saying …
> Non-MARC import from archive.org

- openlibrary/templates/books/edition-sort.html
- openlibrary/templates/type/work/editions_datatable.html
- package.json
- static/css/base/helpers-common.less
- static/css/components/editions.less
- static/css/legacy-datatables.less
- vendor/js/jquery-datatables/jquery.dataTables.min.js
> **Description**: What does this PR achieve? [hotfix]
Makes the edition component responsive
Closes #1339
For laptops screens
For mobile
> Make edition component responsive

- static/css/less/colors.less
> **Description**: What does this PR achieve?
The following pr changes the banner color (hsl of link-blue) to a darker one in order to make it more accessible.
(As posted by @mekarpeles on slack)
> Change banner colour for accessibility

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
[feature] 
Making use of github's feature of having separate issue template for bug report and feature request.
These templates have more features which can utilized by editing the YAML part in the templates.
Closes #1974 
n/a
This is can be tested on master branch by creating a new issue. Github will prompt for type of issue. Issue opener can even opt for a blank issue template.
**Screenshots**
feature request template:
bug report template:
> [DISCUSS] Add separate issue templates for feature report and bug report (#1974)

- static/css/components/cbox.less
- static/css/legacy.less
Fixes:    The cross button goes out of the box
Fixes:    The content inside the modal starts touching the border
Closes #1971 
n/a
n/a
Earlier:
Now:
> Fix css in cover image modal

- openlibrary/plugins/openlibrary/js/ol.js
This reverts commit f990541030f061c4d5e461b01433e5f9d8ba255b.
Quick fix not final solution
Related to #1970 
Please note this is not the final solution. The real objective [f9905410](https://github.com/internetarchive/openlibrary/commit/f990541030f061c4d5e461b01433e5f9d8ba255b) needs to be fulfilled. 
Please do not close #1970. @jdlrobson is helping me find resolve the actual problem.
The PR is because hundreds of list are not able to created. 
n/a
> Revert "Cleanup/document dropclicker behaviour"

- docker/Dockerfile.olbase
webpack is required for production too (used in the Makefile js task)
this installs webpack from package.json
less is installed globally separately because not doing so results in
errors from vendor submodules vendor/js/wmd
> **Description**: What does this PR achieve? [feature|hotfix]
Allows the base Docker image to be successfully built after the addition of webpack to the js Makefile task.
I'm not completely certain that `npm install` needs to be in the Dockerfile.oldev file. Perhaps we should audit what npm dependencies are required for production vs. dev. It's probably ok for now, and not urgent.
There are probably other ways to get the same effect as `&& npm install -g less` but it is required because without it …
> npm install using package.json for base Docker image

- static/css/base/common.less
- static/css/components/dropper.less
Closes #1968
-webkit-any-links default styling was being applied to this link which is the source of the underline. I've added two properties to dropper.less.
visit openlib_url/subjects/fantasy#sort=date_published&ebooks=true . You should see a dropper with no underline. **Note**: I wasn't sure if it should be completely removed so I created an on hover property. The idea being users see there is functionality behind the button. ¯\_(ツ)_/¯
> added default styling to <a> tag 

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- PULL_REQUEST_TEMPLATE.md
Replaces block quotes in issue templates with HTML comments. 
Closes #2010
> replace block quotes with html comments in issue templates

- openlibrary/templates/work_search.html
hidden is an !important style. It will only stop being applied if
it's removed.
Fixes: #2074
Closes #
> Fix the search facets

- static/css/components/category-item.less
When tapping a category a single box is shown instead of 3 boxes like before.
Closes #1195
Just added display:block to the anchor element as suggested
All tests passed
Before
After
> Fix highlight on category items inside carousel

- docker-compose.yml
- docker/Dockerfile.olbase
- docker/Dockerfile.oldev
- docker/README.md
Refactor. Simplify docker build by:
- Use `docker-compose build` commands where possible
- Reorganize Dockerfile layers so pip/npm installation is only required when `requirements*.txt` or `package*.json` changes are made. This means rebuilding the images will be much faster if only a random file in the repo has been changed.
- Updated docs
> Use docker-compose build + reorganize Dockerfile layers

- openlibrary/templates/site/body.html
Closes #2075
Hi, this is my first pull request on this repository. The feature is already documented on this page: https://openlibrary.org/dev/docs/bookreader
I removed the banner from the page, but another approach could be to hide it using inline styles.
Tests run without problems
Before
After
Before
After
> New feature banner removed

- openlibrary/solr/update_work.py
Fix; I noticed solr updater erroring a lot a while back at this line locally. Possibly related to #870 . Found this while working on #1843 .
This is a workaround because of https://github.com/internetarchive/openlibrary-client/issues/126
Sample error:
```
2019-01-03 17:55:37,202 [ERROR] failed to update work /works/OL17807410W
File "/openlibrary/openlibrary/solr/update_work.py", line 1149, in update_work
d = build_data(w)
File "/openlibrary/openlibrary/solr/update_work.py", line 679, in build_data
authors = SolrProcessor().extract_authors(w)
File "/openlibrary/openlibrary/solr/update_work.py", line 370, in extract_authors
if any(a['type']['key'] == '/type/redirect' for a in authors):
File "/openlibrary/openlibrary/solr/update_work.py", line 370, in …
```
> Make solr-updater not error on malformed authors

- openlibrary/plugins/upstream/addbook.py
- openlibrary/templates/books/edit/edition.html
Fix: Makes it possible to move an edition to a work which has a subtitle. Closes #2111 .
When an item was selected, it was triggering a new solr query which would yield 0 results. This would make nothing be selected, so on save the edition became an orphan.
> Fix edition becoming an orphan when moving to subtitled work

- openlibrary/plugins/upstream/addbook.py
- openlibrary/plugins/upstream/tests/test_addbook.py
- openlibrary/templates/books/edit/edition.html
Fix (NOT A HOTFIX). Would like this FULLY tested on dev and code reviewed before going to prod. I don't want to have this turn into another P0 bug :P 
Closes #961; closes #730; closes #1891 
Unless I'm missing something, it seems like orphan editing never worked? Could someone confirm/deny this?
Lisa's list of broken orphans for testing: https://openlibrary.org/people/seabelis/lists/OL129155L/broken
| Test | Local | Dev | Testing Cases? |
|------|-------|-----|----------|
| Editing a work | ✔️ |  | ✔️ |
| Editing an edition | ✔️ |  | ✔️ |
| Moving Edition | ✔️ |  | ️️✔️ |
| Edits to Work are ignored when moving an edition | ️️✔️ |  | ✔️ |
| Editing a work and an edition at the same time | ️️✔️ |  | ✔️ |
| Editing orphan (should create new work) | ️️️️️️️✔️️️️️ ️| ✔️️️️️ | ️️️️️️️✔️️️️️ ️| …
> Orphans can now be edited + moving orphans won't create works

- openlibrary/catalog/add_book/merge.py
fix, some imports are failing because the code is undeleting authors from potentially matching editions, example:  https://openlibrary.org/authors/OL3963499A?b=3&a=2&_compare=Compare&m=diff
Which seems to be because an almost matching edition was found https://openlibrary.org/books/OL12620372M?v=1 when trying to import this MARC record:
https://openlibrary.org/show-records/marc_openlibraries_phillipsacademy/PANO_FOR_IA_05072019.mrc:47968820:954
The correct record to match has the same title: https://openlibrary.org/works/OL7578514W/Schumann, and I believe the problematic record would have been discarded from the matching pool. 
I can't see the reason for modifying an edition that is part of the potential matching pool. Deleted authors were deleted for a reason, and un-deleting them in …
> Prevent import from undeleting bad authors

- openlibrary/plugins/openlibrary/js/availability.js
Closes #2124 
Removed the jquery event listener hack for the waiting list submit listen case, replaced with a button submit which doesn't require js.
go to authors page https://dev.openlibrary.org/authors/OL2674263A/Muriel_Jensen and click join waiting list
tested by @JeffKaplan 
Context: we discovered a bug where only on the authors book listing page the waitlist isn’t working. It’s because we’re using some funky JS to add the button after page load. Really, no js is needed (so this whole “hotfix” will soon get tossed)
I wouldn’t put too much emphasis on code style in (only) this case as I’m very confident in the next month the file is going to supplanted by availability checking done on the backend (a PR for this is WIP)
> fixes availability.js, working waitlist on author pages

- .vscode/launch.json
- docker-compose.yml
- docker/Dockerfile.oldev
- openlibrary/plugins/admin/code.py
- openlibrary/templates/admin/attach_debugger.html
- requirements_test.txt
Feature. Allow for remote debugging the local site. Closes #2076 . Logging in doesn't seem to work with only 1 gunicorn worker (for some reason), so the flow is a bit awks, but I think still useful.
In action (sorry mouse is invisible):
Not crazy over the magic `/attach_debugger` endpoint; ideally I'd like to show a "Dev Tools" button visible on the homepage toolbar if the site is running locally, but not sure how to access configs from the template (if anyone has info on that). I think still this is worth merging as is, BUT WANT SOMEONE TO TRY IT BEFORE IT GETS MERGED. @hornc @mekarpeles One of you would be great candidates :)
This requires VS Code + its Python extension. To use:
1. `docker-compose up -d` as usual and login as admin. Then `docker-compose down`.
2. Open the repo in VS …
> Remote debugging of openlibrary site in docker

- openlibrary/solr/update_work.py
- openlibrary/tests/solr/test_update_work.py
Fix: Make `update_work` handle redirected works. We still need an issue to fix all the ones that are currently missing, but that won't be an issue once we reindex.
Closes #2139 .
First did a light refactor, so look at the commits separately for simplicity. We now also throw an error if an unexpected type is found.
We can try forcing a re-index of the example on #2139 . I tested locally before/after the change, and it works as expected.
> Fix solr not indexing work redirects

- openlibrary/plugins/importapi/code.py
When importing local_ids, some partner MARC records have multiple
fields, and not all have the expected subfield:
example: https://openlibrary.org/show-records/marc_openlibraries_sanfranciscopubliclibrary/sfpl_chq_2018_12_24_run05.mrc:26324164:8452
has a 945 field without the expected $i:
```
945    $a327.1273$bG8554n$d  -  -  $e  -  -  $f0$g0$h  -  -  $j0$00$k
-  -  $lm8aaa$ol$p$27.00$q-$r-$se
$t0$u0$v0$w0$x0$y.i78405312$z07-29-14
```
> FIX: local_ids; don't assume every target field has the expected sub-field

- .dockerignore
- .gitignore
- conf/openlibrary.yml
- docker/Dockerfile.olbase
- docker/Dockerfile.oldev
- docker/ol-docker-start.sh
- openlibrary/core/users.sql
- scripts/new-solr-updater.py
Fix: Creates a readonly postgres user for solrupdater so there's a stronger guarantee that when we run this on logs ~1mo out-of-date (for the last phase of #1843 ) it won't be causing any unintentional database edits.
- In our local environment, the default authentication for users is [`peer`](https://www.postgresql.org/docs/9.5/auth-methods.html#AUTH-PEER); this requires us to create a system user but means we don't need a password (good for dev). On production we'll have to give the postgres user a password somehow?
- Solution based on https://gist.github.com/oinopion/4a207726edba8b99fd0be31cb28124d0
- Note that it's a `readcreate` user; it can still create new tables. Removing this seemed like more trouble than it's worth (especially if we want to keep prod in sync), so didn't bother. …
> Create readonly postgres user for solrupdater

- openlibrary/core/lending.py
- openlibrary/macros/AvailabilityButton.html
- openlibrary/tests/core/test_lending.py
fix: handles the case where an OCAID is invalid so that search still renders correctly.
Closes #2001 
Added some test!
> Handle invalid OCAID availability response

- .eslintignore
- openlibrary/templates/work_search.html
- static/css/legacy.less
Fix: Display pagination directly below results instead of below facet search on mobile.
Closes #2015
- Only moved the paginator; the facets being hard to access is still a problem.
- Only tested on Firefox 67 (latest), but there aren't any big CSS changes, so I expect it should be fine.
| Platform | Picture | Picture 2 |
|---|---|---|
| Desktop | ![image](https://user-images.githubusercontent.com/6251786/58364901-94962d00-7e89-11e9-8f6e-ee466ef8e114.png) | ![image](https://user-images.githubusercontent.com/6251786/58364945-52212000-7e8a-11e9-978d-72d3430dfbab.png) |
| Mobile | ![image](https://user-images.githubusercontent.com/6251786/58364897-7a5c4f00-7e89-11e9-99d5-02d00b6b160d.png) | ![image](https://user-images.githubusercontent.com/6251786/58364916-e939a800-7e89-11e9-9f97-115716fd4fa1 …
> Show pagination directly below search results

- openlibrary/plugins/importapi/code.py
Fixes instances where non-book items were being imported from bulk MARC files.
Modifies existing reject non-book code to provide the offset and length of the next record which is required to allow the import process to continue.
Tested locally with SFPL data,
```
docker-compose exec web scripts/copydocs.py /type/local_id
docker-compose exec web scripts/copydocs.py /local_ids/sfpl
```
To set up the require local id
Tested with the following MARC item: https://openlibrary.org/show-records/marc_openlibraries_sanfranciscopubliclibrary/sfpl_chq_2018_12_24_run06.mrc:188734629:1625
With this PR the response becomes:
```
b'{"next_record_offset": 188737851, "error_code": "item-not-book", "next_record_length": 2541, "success": false, "error": "Item rejected"}'
```
Which is a clear rejection, no …
> Prevent bulk MARC import from importing non-books

- openlibrary/templates/books/edit/edition.html
- static/css/components/form.olform.less
ol.form `select` elements should be 100% unless otherwise specified
so that they do not spill outside the viewport
(see https://github.com/internetarchive/openlibrary/issues/2100#issuecomment-497307864)
Fixes: #2100
Closes #2100
> Ensure `select` elements are not larger than viewport

- openlibrary/plugins/worksearch/code.py
- openlibrary/utils/__init__.py
- openlibrary/utils/isbn.py
- openlibrary/utils/tests/test_isbn.py
- openlibrary/utils/tests/test_utils.py
Refactor and improvements to allow /isbn/ search to locate either form (ISBN10 / ISBN13) of isbn in the metadata when searching for a single ISBN.
An example which failed:
https://openlibrary.org/isbn/9780679744825 => 404
should find
https://openlibrary.org/isbn/0679744827
Existing tests moved and renamed to confirm exisiting functionliaty
> Improvements to ISBN search code

- openlibrary/templates/books/edit/edition.html
- static/css/components/form.olform.less
Realized we missed the `weight` field in #2158 . Fixed that. Also learned about `step="any"`, which lets people enter any precision, and makes the up/down buttons move in steps of 1. Switched to that instead.
Closes #2095 
Made some slight tweaks to css of these as well.
Tested on Windows Firefox/Chrome/IE latest.
> Make dimension inputs "any" precision

- openlibrary/templates/site/alert.html
Another small change, helps with HTML5 compatibility on all site pages. HTML5 img width are all in pixels, `px` gives a validation error.
> HTML5 img width

- openlibrary/templates/site/head.html
Chrome frame was discontinued in 2014
small change for review.
> remove old IE plugin support discontinued in 2014

- openlibrary/plugins/upstream/utils.py
Closes #2102 
Not 100% sure why this is casuing problems -- I think the issue is to do with  webpy's unicode support. This clears up the issue on affected items in dev -- they had HTML meta tag descriptions that included unicode characters, and something in the multiple 'websafe'-ing methods was complaining. This ensures the values are recognised as utf8 encoded.
> Fix templates/site/neck.html unicode error

- openlibrary/plugins/upstream/addbook.py
Reduce recaptcha exemption from 2 years to 1 month.
Closes #2185
> Reduce recaptcha exemption from 2yrs to 1mo

- openlibrary/catalog/add_book/__init__.py
- openlibrary/templates/books/edit/about.html
Will prevent case differences from creating duplicate subject keywords when importing new books. It will also remove parenthesised text from comparisons (but not from the eventually added subject)
Closes #2029 
Subject comparisons are now normalised using the existing method that is used to normalize titles for comparison.
I have changed the edit form to refer to the subjects as "Subject keywords" rather than tags. @seabelis , hopefully that is better now -- what do you think?
> Prevent imports from duplicating subjects

- .eslintrc.json
- openlibrary/plugins/openlibrary/js/account.js
- openlibrary/plugins/openlibrary/js/add_new_field.js
- openlibrary/plugins/openlibrary/js/autocomplete.js
- openlibrary/plugins/openlibrary/js/automatic.js
- openlibrary/plugins/openlibrary/js/availability.js
- openlibrary/plugins/openlibrary/js/bookreader_direct.js
- openlibrary/plugins/openlibrary/js/carousels.js
- openlibrary/plugins/openlibrary/js/jquery.repeat.js
- openlibrary/plugins/openlibrary/js/jsdef.js
- openlibrary/plugins/openlibrary/js/ol.js
- openlibrary/plugins/openlibrary/js/subjects.js
- openlibrary/plugins/openlibrary/js/template.js
- openlibrary/plugins/openlibrary/js/utils.js
- openlibrary/plugins/openlibrary/js/validate.js
- package.json
Refactor moving variable declarations to top of function block.
Closes #2086
Regarding comments in the issue thread, I leaned toward resolving linting violations by doing the exact equivalent of what Javascript would do (go back and define the variable at the top of scope) rather than the cleaner way (e.g. moving `event.preventDefault();` down past variable declarations that are probably fine but technically different)
Ran `npm test` and came back with same css linting errors that previously existed.
> Enable `vars-on-top` eslint rule

- openlibrary/core/models.py
- openlibrary/macros/LoanStatus.html
- openlibrary/plugins/openlibrary/js/ol.js
- package.json
- static/css/base/common.less
- static/css/components/buttonCta.less
- static/css/less/colors.less
feature
Closes #2162
The sponsor ebook button still needs to be added on the search and work-editions table
> Adds a sponsorship button 

- openlibrary/templates/books/edit/edition.html
I don't like having these events hidden in the templates but I'm
not quite sure how to generalise this code right now.
The `hidden` class now applies !important so needs to be removed
when ever doing this fadeIn/out programmatically.
Fixes: #1892
Closes #
> Fix reveal of translation information

- openlibrary/macros/LoanStatus.html
- openlibrary/plugins/openlibrary/js/ol.js
Feature
Updates #2194 
Policy Api v1 implemented which does not include archive.org policy requirements. 
Writing unit tests for the policy check api left
It considers a book eligible only when the book:
- has a book cover
- must not have ocaid / archive.org id
- has valid isbn	
- has a publish date
- has bwb price + price < $15
Check on multiple editions that the `Sponsor eBook` button shows up on the right places
> Policy Api check added 

- package.json
Previously our unit tests were not being run by Travis.
They were also picking up non-tests so I've changed the wildcard
> Fix npm run test:unit and enforce coverage

- openlibrary/templates/work_search.html
When `ebooks` mode selected, on the backend we filter OL items to display based on availability. This Archive.org availability API (e.g. ervices/availability/?identifier=p1diegesetzedera02greauoft,bookreadymadesp00bookgoog,bookhealth00bookgoog) should accept a list of 100 items. However, either because of a change/regresison/or other factors, it fails silently by responding that all items are "not found" if what it thinks of as "too many ids" are provided. When this happens, the openlibrary.org search results page interprets the error by hiding all the book results (assuming they are unavailable).
#search
The fix is to reduce the items returned from 100 to 20 (also closes #2151)
availability query was breaking, too many results, lowering SERP item…
Closes #2151
> hot-fixing search results

- openlibrary/plugins/openlibrary/js/nonjquery_utils.js
- openlibrary/plugins/openlibrary/js/ol.js
- openlibrary/plugins/openlibrary/js/subjects.js
- openlibrary/plugins/openlibrary/js/utils.js
- tests/unit/js/html-test-data.js
- tests/unit/js/test.jquery.repeat.js
- tests/unit/js/test.nonjquery_utils.js
- tests/unit/js/test.ol.js
Refactor to remove the `debounce` dependency injection of `initReadingListFeature`, as discussed here: https://github.com/internetarchive/openlibrary/pull/2224#discussion_r306035603
- Why does this have a debounce anyways? It causes the list to appear/vanish sluggishly.
- Tested locally that the reading log still opens/closes correctly
> Refactor debounce into separate file

- openlibrary/templates/books/edit/edition.html
Fixes: #2090
An element needs to be revealed using JS so using display: none
Closes #
> Allow validation errors to display when editing identifiers

- openlibrary/plugins/upstream/code.py
- openlibrary/templates/viewpage.html
Fix #2217. [feature]
Gives revert access for librarians.
- Librarians should see history on top right side
- They can revert till a revision listed
> Add revert access for librarians

- openlibrary/plugins/upstream/code.py
- openlibrary/templates/viewpage.html
This reverts commit 4b4f8a9c5477e211b3c438a4f50c6ee33cf3aca4.
The commit makes references to undeclared variables and should
never have been merged.
Fixes: #2261
> Revert "Add revert access for librarians (#2228)"

- openlibrary/core/lending.py
- openlibrary/macros/LoanStatus.html
- openlibrary/plugins/openlibrary/js/ol.js
- package.json
- static/css/components/buttonCta.less
feature
Updates #2194 
This piece of code checks for qualifying editions. An edition is work-level qualifiable if itself and any other editions of the work are unavailable
This is a false positive so `Sponsor ebook` button should not be shown on any of its `non available editions` https://dev.openlibrary.org/works/OL5735363W/The_Hunger_Games
> work-level availability check and hotfix sponsorship button

- openlibrary/templates/account/books.html
Public reading log broken on production https://openlibrary.org/people/mekBot/books/want-to-read?debug=true because the open graph avatar tries to call the currently logged in user's archive.org id (to fetch avatar) -- i.e. `ctx.user.id` rather than use the user passed in to the template.
> corrects avatar for public reading log + works for logged out user

- openlibrary/templates/type/i18n/edit.html
Not sure how this broke but `_` doesn't refer to the thing it's
supposed to refer to. Possibly something set this as a global
before. There are likely many other pages impacted but this
fixes the reported one.
Fixes: #943
Closes #
> Replace _. with i18n to fix rendering (but not functionality)

- conf/openlibrary.yml
- openlibrary/core/lending.py
- openlibrary/core/sponsorships.py
- openlibrary/macros/LoanStatus.html
- openlibrary/plugins/upstream/account.py
- openlibrary/templates/account/books.html
Closes #2199 and Re-closes #2168 and #2163 
By default openlibrary repo openlibrary.yml now has an API endpoint for civi crm which is pinned to https://dev.openlibrary.org/internal/fake/civicrm. You can add `entity=Contact` or `entity=Contribution` to emulate which necessary fields + format would be returned by production CiviCRM.
On production, olsystem overrides openlibrary.yml and uses the official civicrm API endpoint w/ credentials. So theoretically this feature should be primed to work on localhost or dev + production.
This is currently not yet possibly to fully test on localhost (because it requires `/usergroup/sponsors` to work, which only exists in the prod db). Also, the example book isn't in the local instance by default. To test on dev/production:
1. have an admin add your …
> integrates CiviCRM API for fetching patron's sponsored books

- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/plugins/openlibrary/js/jquery.toggleText.js
- openlibrary/plugins/openlibrary/js/utils.js
- openlibrary/plugins/search/templates/advanced_search.html
pending further testing and exploration I don't think the
advanced_search template is in use. If this is the case,
given that this template is the only consumer of jquery.toggleText
toggleText can be removed
@mekarpeles and @cdrini how can we determine which pages (if any?) use this template. Do we have any way to programatically do that from the site map?
Update: http://localhost:8080/developers/routes  suggests this route is not in use anywhere (assuming that is comprehensive list)
Fixes: #2243
Closes #
> Remove jQuery.toggleText and advanced_search template

- openlibrary/macros/databarView.html
Fix; edit button now consistently edits the object being viewed.
Closes #2033
- Nothing to note.
- Tested edit button functions for works with more than one edition
- Locally removed an edition from http://192.168.99.100:8080/works/OL61982W/Odyssey and tested the button behaved as expected
- No UI change.
> Make edit button edit work even if only has 1 edition

- openlibrary/data/sitemap.py
Refactor. Fix `flake8` error: `./openlibrary/data/sitemap.py:76:10: F821 undefined name 'doc'` ( https://travis-ci.org/internetarchive/openlibrary/jobs/571136885#L286 )
Related to #1684
- Removed the entire `find_path` method; PyCharm found no references, and the string `find_path` does not appear anywhere in the repo.
No special testing required.
No UI changes.
> Resolve undefined name “doc” in site map.py

- .travis.yml
If Travis is running Python 3, then create a legacy Python instance to enable the installation of npm/node.
Helps with #2293
After this PR lands, our progress on Python 3 will be blocked because this repo contains a __stale__ symlink into the __internetarchive/infogami__ repo which contained a legacy __print__ statement back when that symlink was created.  This Python 3 syntax error has since been fixed in that repo but the symlink needs to be updated to access that newer version.
This is Travis CI so it is all about testing.
See the Travis results.
> Travis CI: When on Python 3, do a pyenv install 2.7.14 for nmp/node

- Makefile
- openlibrary/catalog/onix/xmltramp.py
- openlibrary/plugins/upstream/tests/test_addbook.py
- openlibrary/tests/core/test_init.py
This adds more tests about runtime safety and correctness to our flake8 run in __make lint__ which is executed by Travis CI on all code changes and can also be run locally by contributors.  E9 runs all E9xx tests, E63 runs all E63x tests, etc.  https://lintlyci.github.io/Flake8Rules
On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead these __tests are focused on runtime safety and correctness__:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled …
> make lint -- Add more flake8 tests

- openlibrary/plugins/upstream/merge_authors.py
This will help help troubleshooting author merge problems, and enable further API use.
relates to #2248
The UI does not test for the success of this request, because the js is now v2 and async with #1609.
I'll need to join up the response, but at least the js has something to sensible to look for. Previously this error was not properly handled, causing a 500 HTTP reponse with no details, so all info was lost, and the 500 error was swallowed by the view page.
Now the JSON error details are at least visible in browser network tab on the
POST to merge.json
This relates to the author's view page, with parameters
/authors/OL..A?merge=true&duplicates=OL..A
example response on error (for the example in #2248):
```
{
'message': 'expected /type/author, found /type/redirect',
'at': {'property': …
```
> Correct status and detailed response for merge_authors API

- openlibrary/templates/account/create.html
- openlibrary/templates/account/email.html
- openlibrary/templates/account/password.html
- openlibrary/templates/books/edit.html
- package.json
- static/js/vendor.jsh
refactor:
This is some pre-work for 2305.
Closes #
No bug associated.
This is removing dead code that's not being utilised anywhere.
Not sure what evidence would be useful for this.
> Remove dead code

- .travis.yml
Allows the Travis CI run on Python 3 (only) to test against the current __acs4_py__ and __infogami__ git submodules while the Python 2 runs continue to use the stale versions.  This allows the Travis CI Python 3 to pass __npm install__ and attempt __make test__ while leaving the Python 2 runs unaffected.  Special thanks to @cdrini for syntax suggestions at https://github.com/internetarchive/infogami/issues/25#issuecomment-521358254
```
if Travis is running Python 3, then
refresh the git submodule ./vendor/acs4_py
refresh the git submodule ./vendor/infogami
git commit those changes into this pull request
TODO: flake8 ./vendor --select=E9,F63,F7,F82 to unsure new versions pass
create a legacy Python for npm/node until nodejs/node#25789 is resolved
```
This is stopgap code that will …
> Travis CI: Update vendored submodules only on Python 3

- openlibrary/plugins/openlibrary/js/Browser.js
- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/plugins/openlibrary/js/ol.js
- tests/unit/js/test.Browser.js
Refactor. Move `Browser` object out of `ol.js` into own file.
Split from #2285
Also wrote tests for the module and removed an unused function.
Tested `&facet=author` on homepage updates search bar url parameter
No UI changes.
> Move Browser object from ol.js into own file

- openlibrary/core/lending.py
- openlibrary/core/models.py
- openlibrary/core/sponsorships.py
- openlibrary/macros/LoanStatus.html
- openlibrary/plugins/openlibrary/api.py
- openlibrary/utils/isbn.py
closes #2194
- calls out to 3rd party library for eligibility check, gracefully falls back
- enables sponsorship when not logged in, when ?sponsorship=true params present
- adds a /sponsorship/eligibility/{isbn} json endpoint for archive.org/donate
- DRYs archive.org url, moves to config
Incorporates & supplants #2291 
- punts eligibility checking to 3rd party tool
- adds /sponsorship/eligibility endpoint for archive.org/donate
> book sponsorship eligibility check

- CONTRIBUTING.md
Feature. Updating the CONTRIBUTING doc with details about the new PR assignee flow we discussed on the community call.
Closes #
(No technical/testing/evidence for this one)
> Add PR assignee flow to CONTRIBUTING

- openlibrary/plugins/upstream/data.py
- openlibrary/templates/lib/nav_foot.html
While debugging issues with the ol data dumps https://openlibrary.org/developers/dumps I noticed they were cycling through an unnecessary layer of redirects, caused by the hardcoded URLs `www.archive.org`  which redirects to `archive.org`
This PR uses the `openlibrary.yml` configured value, which uses https. 
Also corrects the link to the data dumps on the nav footer to link directly to https://openlibrary.org/developers/dumps
Tested in local dev, check that Archive.org URL does not have the `www.` prefix.
> prevent unnecessary redirects on data dump links

- vendor/js/json2/Readme.txt
Refactor. The JSON2 js library has been removed, so this file is no longer needed.
- Documentation change, so no testing
> Remove residual json2 README

- openlibrary/core/vendors.py
- openlibrary/plugins/openlibrary/api.py
* Adds an admin / librarian only endpoint that can be used to look up book prices by title and author (for investigating what data is provided from the Amazon search API)
* Refactors the existing price lookup API to make this possible (split some code out to a new `_serialize_amazon_product()` method) and structure the code in a more usable fashion. This is potentially going to help with #2332, and unifying our data source usage
* Minor improvements around date handling, results not found exception handling, and API response format, which will also apply to the standard price lookup results, which does affect every Edition page for books with ISBN.
I did this work as part of a data investigation task, and it seems a shame to throw away the code. The refactor is the main useful aspect of …
> Experimental amazon lookup API and existing API refactor

- openlibrary/plugins/openlibrary/js/automatic.js
- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/plugins/openlibrary/js/markdown-editor/index.js
- package.json
Previously wmd code was run on an empty jquery set. We can check the
length of the set before enabling the code and pull out a modest
bit of JS from the critical path for all pages that do not have an editor.
Size is crucial in this entry point. Especially as we add to it!
I considered adding a class 'markdown--progressively-enhanced' but I favoured doing the minimum possible to get this working.
markdown elements appear on all editing interfaces
Editing a book or edition
Make sure the preview works when you focus the text area.
I've been using this code:
```
test **test**
````
on these pages:
* http://localhost:8080/works/OL53924W/The_complete_works_of_Mark_Twain/edit
* http://localhost:8080/people/openlibrary?m=edit
> Editor code is limited to pages with textarea.markdown

- openlibrary/plugins/openlibrary/js/markdown-editor/index.js
- openlibrary/plugins/openlibrary/js/ol.js
- package.json
As @cdrini points out this code can be moved here! Hurrah! This code makes sure the preview shows when you focus the textarea.
Closes #
http://localhost:8080/works/OL53924W/The_complete_works_of_Mark_Twain/edit
> Move markdown.textarea code from ol.js to feature folder

- Makefile
Fix. They were erroring when run with docker, because docker uses root, which psql doesn't recognized as a registered user.
Run `docker-compose exec web make reindex-solr`
> Fix make reindex-solr commands

- openlibrary/core/vendors.py
Closes #2334 
need to confirm that `product._safe_get_element_text('ItemAttributes.PublicationDate')` is the correct way to access the raw string form of `product.publication_date`
Needs deployment and testing on dev.openlibrary.org
Test examples:
Search for https://dev.openlibrary.org/_tools/amazon_search?title=Tax%20Credits%20Bill
The results will NOT contain `publish_date: "Sep 09, 2019",` where `Sep 09` is today's date. The correct and expected result is `publish_date: "2019",`  for item `amazon:B07QVK7X22`
https://dev.openlibrary.org/_tools/amazon_search?title=The%20Water%20Dancer for a recent book with day and month publish date.
> Fixes #2334, Amazon API results give overspecific (made up) day and month for older books

- openlibrary/core/vendors.py
If BWB only has a new price book (new used) then the vendor code previously failed `if` condition to return price info.
> fixing bwb new price

- openlibrary/plugins/openlibrary/js/carousel/Carousel.js
- openlibrary/plugins/openlibrary/js/carousel/index.js
- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/templates/books/custom_carousel.html
- openlibrary/templates/covers/add.html
- openlibrary/templates/home/categories.html
- package.json
- static/css/components/carousel--js.less
- static/css/js-all.less
Carousel code will no longer be loaded on pages that do not have Carousels. A lightweight Carousel object is created that will lazy load the code when invoked. Less JS is loaded for pages that do not feature carousels.
Some code inside openlibrary/templates/covers/add.html unrelated to
carousels is intentionally ignored for the time being as it doesn't relate to the carousels themselves.
A carousel can be registered now using a data-config attribute and the class `carousel--progressively-enhanced`
Note the additive approach might cause problems where we cache HTML as the carousels will not load on pages without the data attribute/class. Carousels do degrade gracefully however so they are still useable, and a refresh will deal with these. I think it's is acceptable but we may need to …
> Code splitting: Carousels

- openlibrary/plugins/openlibrary/code.py
- openlibrary/templates/books/custom_carousel.html
An endpoint for determining the "best" edition to show a user (given only a work ID). e.g. a readable edition, an available edition, an edition w/ a certain isbn, an edition in a certain language
> For work carousels, resolve 'best' edition

- openlibrary/templates/type/work/view.html
Closes issue #2330 
Checked if the edition count is greater than 1 and used edition in place of editions accordingly
The same test case as in the issue #2330 can be used to check.
> Fixes issue #2330

- openlibrary/catalog/add_book/__init__.py
- openlibrary/catalog/add_book/test_add_book.py
- openlibrary/mocks/mock_infobase.py
- openlibrary/mocks/tests/test_mock_infobase.py
- openlibrary/tests/catalog/test_utils.py
- openlibrary/tests/core/test_vendors.py
Using the results of investigating #2436 , this PR uses the correct method of forming a 'all works by an author' infobase query when checking for existing works.
It also modifies the `mock_site` test mock used in many tests to behave the same way in this respect. Previously tests were showing works were being matched because the query worked for the mocked object when they didn't on the real site. 
Added a direct test to test work matching and confirmation that the saved objects do actually match, not just that the returned status is as expected, since that was fake in the case of Author `modified`. 
Fixes #2434 
Closes #2436 
Hopefully it also
Closes #1621
Closes #947 
Here is one book imported on dev that found an existing work match, prior to this code, the test batch of 100 did not …
> Fixes find_matching_work()

- openlibrary/templates/account/create.html
Fix.
Remove the text next to the _password_ and _confirm password_ inputs on the account creation page. It's misleading, because the site does in fact allow symbols in passwords.
> Remove misleading duplicated text

- openlibrary/templates/type/user/view.html
Fixes issue with accounts made previous to readlogs when viewing profiles.
Closes #2347 
Updated the condition on line 42 of view.html to make sure settings is not null and replaced settings.get('public_readlog') == "yes" with settings.get('public_readlog', 'no') == "yes".
1. Do not log in and view the account of someone with readlog set to not public.
2. Do not log in and view the account of someone with readlog set to public.
3. Log in and view the account of someone with readlog set to not public.
4. Log in and view the account of someone with readlog set to public.
5. Log in and view your account with readlog set to not public.
6. Log in and view your account with readlog set to public.
Public:
Not Public:
> Fixes issue with accounts made previous to reading logs erroring when viewing profiles

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
Closes #2239 
this moves the `Closes` text to the top of the PR template
this also removes the "fluff" header before description so it's
easier to see the actual description in the tooltip
There is no code implementation within this PR.
I used the template from the PR to create this PR.
> make issue and PR templates clearer

- openlibrary/templates/site/donate.html
Our jQuery version is much older than the comment suggests. Drop this polyfill.
Closes #
Checkout my code.
Verify that $('body').prop still is a function.
> Drop unnecessary $.prop polyfill

- openlibrary/macros/EditButtonsMacros.html
- openlibrary/templates/type/edition-history/view.html
openlibrary/macros/EditButtonsMacros.html:
No references to Dialog or deleteVerify either in any templates
or the global namespace
edition-history/view.html
No global slidePanels function
Closes #
Removes dead code.
Grep. Confirm what I believe that this code is not used anywhere
> Remove dead JS

- openlibrary/templates/site/footer.html
- openlibrary/templates/site/head.html
Closes #
Drops firebug support.
It's 2019.
Who uses Firebug anymore?
> Drop firebug script support like its 2019

- openlibrary/plugins/worksearch/code.py
Closes #2443 
Feature: This adds a handler for subject search that provides `JSON` encoded documents.
The subjects search at https://openlibrary.org/search/subjects.json?q=teen will now return JSON instead of HTML.
This is implemented in the same way that the `author_search` has been implemented to support `JSON` encoded results.
Verified that the search works the same before and after the patch.  Verified that the search results page has the same results in both HTML and JSON encoded results pages.
HTML View of the Astronauts Subject in Dev:
JSON View of the Same Page:
> add JSON response for subject search

- webpack.config.js
When viewing the homepage I see requests for carousel.js and
vendors~carousel.js. This was not intended and adds an additional
request. `vendors-carousel` is also not listed in package.json so
we're not tracking the bundlesize correctly without this.
I didn't raise a ticket. Can raise one if needed.
Webpack configuration yay!
Load homepage and look at network tab. Before this patch you should see requests for carousel.js and vendors~carousel.js
After this you'll only see one (larger) request.
> Do not split out vendors into separate bundles

- openlibrary/macros/BookPreview.html
- openlibrary/macros/databarAuthor.html
- openlibrary/plugins/openlibrary/js/dialog.js
- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/templates/books/edit/addcover.html
- openlibrary/templates/covers/add.html
- openlibrary/templates/covers/author_photo.html
- openlibrary/templates/covers/book_cover.html
- openlibrary/templates/covers/book_cover_single_edition.html
- openlibrary/templates/covers/book_cover_work.html
- openlibrary/templates/covers/change.html
- openlibrary/templates/covers/manage.html
- openlibrary/templates/lib/markdown.html
- openlibrary/templates/lists/widget.html
- openlibrary/templates/type/edition/view.html
From now on simply adding a class .floaterShut to an element will make it close an open dialog.
.floaterShut--parent will request the parent element closes it.
Previously we did this via inline JavaScript which made it really hard to determine which pages should run this code. Having it in a central place also allows us in future to defer the loading of jquery ui off the critical path. This is the most simple first step!
Visit http://localhost:8080/works/OL53924W/The_complete_works_of_Mark_Twain#addImage and click "change cover". The close icon should close the dialog
> Dialogs: Move click handler from templates to JS

- openlibrary/plugins/worksearch/subjects.py
hotfix. This reverts commit 2d54f0662a6fc44b80370ad9f30b6d5c88187ce2.
Getting 504s on prod, and `maximum recursion` exceed errors when trying to view large subjects/publisher pages.
> Revert "Fixes Publishers page displaying only 2 pages of works (#2471)"

- openlibrary/core/sponsorships.py
- openlibrary/macros/LoanStatus.html
refactors books sponsorship to relax $50 limit. Cost of book + scanning is presented to the user.
N/A, removed $50 limit
https://dev.openlibrary.org/books/OL27351643M/The_Subtle_Art_of_Not_Giving_a_! should display as sponsorable (despire being > $50)
> Now any eligible book can be sponsored (no cost limit)

- openlibrary/core/sponsorships.py
- openlibrary/macros/LoanStatus.html
Followup on #2485
Refactor
eligibility endpoint now pulls data from amazon to augment the archive.org edition if insufficient metadata available to make a decision (e.g. no cover or number_of_pages)
The result is many more books will become available for sponsorship
https://dev.openlibrary.org/sponsorship/eligibility/0062884026
> more eligible books, pulls missing metadata from amz

- openlibrary/templates/type/list/embed.html
There are very few reasons to use this especially we shouldn't do it in
such a blanket way for all links in a page. Respect the users
browser defaults...
Closes #
Visit https://openlibrary.org/people/maggien/lists/OL127552L/Never_Read_Again/embed equivalent.
Links should open in the current page.
> Don't use target blank in list embed

- openlibrary/plugins/worksearch/code.py
Related to #2443
Feature:  This adds a handler for `lists` search that provides JSON encoded documents.
The subjects search at https://openlibrary.org/search/lists.json?q=beauty will now return JSON instead of HTML.
The `lists` return is very different from the values returned from SOLR for `subjects` because it's pulled from the database models instead of from SOLR.
Tested the search in the docker-compose development environment.
HTML
JSON
> add JSON format to list search

- openlibrary/templates/type/work/view.html
The colorbox triggers a cbox_closed event, but it must be associated with an element that is a colorbox.
$() will match nothing and will not run on every time a colorbox
is closed.
Closes #
This is more dead code elimination. It should have no effect on the site.
Visit a works page, add a console.log and open and close all the dialogs on the page and verify this code has no purpose.
> Drop non-functional on-colorbox close event usage

- openlibrary/macros/LoanStatus.html
Sponsorship deploy went smoothly overall, except that the button (which is not fully hooked up) is appearing for all users because a check to permit`?sponsorship` which was misconfigured.
This fix has been tested on dev.openlibrary.org and resolves the issue. As a stop-gap, the fix was done on ol-web3 and ol-web4 (so things are currently behaving correctly in production).
> hotfix to restrict access to sponsorship beta

- openlibrary/coverstore/tests/test_doctests.py
Resloves the following errors that were noticed on dev.openlibrary after updating to the latest Infogami:
```
ImportError while importing test module '/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/coverstore/tests/test_doctests.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../venv/local/lib/python2.7/site-packages/six.py:709: in exec_
exec("""exec _code_ in _globs_, _locs_""")
openlibrary/coverstore/tests/test_doctests.py:2: in <module>
from infogami.infobase.tests.test_doctests import find_doctests, run_doctest
E   ImportError: cannot import name find_doctests
```
Removes the dependency on Infogami test helper methods (that were removed / refactored in the recent python3 / modern pytest updates)
Now the coverstore tests runs its …
> remove infogami dependency for coverstore doctests

- openlibrary/core/processors/readableurls.py
- openlibrary/core/sponsorships.py
- openlibrary/macros/AvailabilityButton.html
- openlibrary/macros/LoanStatus.html
- openlibrary/macros/SearchResultsWork.html
- openlibrary/macros/SponsorCarousel.html
- openlibrary/plugins/openlibrary/code.py
- openlibrary/plugins/openlibrary/home.py
- openlibrary/plugins/openlibrary/tests/test_home.py
- openlibrary/plugins/upstream/models.py
- openlibrary/templates/account/borrow.html
- openlibrary/templates/books/custom_carousel.html
- openlibrary/templates/home/index.html
- openlibrary/templates/site/body.html
- static/css/components/buttonCta.less
Changes for this weekend + week of October 23 (celebration). Goal is to make it easier (but not too easy) to discover book sponsorship (by eliminating work v. edition confusion).
Search results link to "best" edition instead of work (experiment)
This also fixes a tiny bug with sponsorship (where you get added to the waitlist of a book which is not in lending, breaking the https://openlibrary.org/account/loans page
> search results go to edition, everyone in sponsorship

- openlibrary/core/civicrm.py
Similar to unexpected sponsorship config issue, civi config vars can seemingly no longer be loaded directly and instead are imported visa vi `lending`. Hotfix to repair Reading Log account page.
> hotfix issue with civi config loaded direct from lending

- openlibrary/core/sponsorships.py
The openlibrary_edition and openlibrary_work were swapped in the eligibility API
hotfix
n/a/
Hit the eligibility API (e.g. https://openlibrary.org/sponsorship/eligibility/OL25211152M) and ensure that the edition ends with an `M` and the work ends with a `W`
See testing link above
> hotfix: edition and work swapped in eligibility API

- openlibrary/plugins/openlibrary/home.py
web.ctx.env is (classic problem) not available within the ThreadedDict cacheable version of the cached sponsorable books function. We added the `if not 'env' in web.ctx` logic (as is customary in such cacheable methods which require using web.ctx.site) to get around this.
hotfix
forced re-caching of the homepage
> fixing sponsor carousel cacheing

- openlibrary/plugins/openlibrary/js/graphs/index.js
- openlibrary/templates/home/stats.html
These ids are very generic - in fact the id ebooks is being used on
the publishers page and causing a bug
Fixes: #2519
Closes #
1) Check the /stats page - and ensure all graphs render
2)  Visit a publishers page with ebooks available - https://openlibrary.org/publishers/MIT_Press and make sure no JS errors and graph renders.
> Use unique ids for graphs

- openlibrary/macros/BookPreview.html
- openlibrary/macros/databarAuthor.html
- openlibrary/plugins/openlibrary/js/automatic.js
- openlibrary/plugins/openlibrary/js/dialog.js
- openlibrary/templates/books/edit/addcover.html
- openlibrary/templates/books/edit/addfield.html
- openlibrary/templates/covers/add.html
- openlibrary/templates/covers/author_photo.html
- openlibrary/templates/covers/book_cover.html
- openlibrary/templates/covers/book_cover_single_edition.html
- openlibrary/templates/covers/book_cover_work.html
- openlibrary/templates/covers/change.html
- openlibrary/templates/covers/manage.html
- openlibrary/templates/lib/markdown.html
- openlibrary/templates/lists/widget.html
- openlibrary/templates/type/edition/view.html
- static/css/components/cbox.less
Standardise names per discussion in https://github.com/internetarchive/openlibrary/pull/2421#discussion_r330673319
* Remove floaterClose class
* floaterShut is renamed dialog--close
* close-popup becomes dialog--close
* .floaterShut--parent becomes dialog--close-parent
Closes #
> Standardise dialog close wire ups

- openlibrary/templates/history.html
fix
Tested history appears with only 2 buttons on http://192.168.99.100:8080/books/OL2058361M/The_wit_wisdom_of_Mark_Twainsadf?m=history
| -- | -- |
| ![image](https://user-images.githubusercontent.com/6251786/67723088-2c97c580-f998-11e9-95c3-e9af3065ccae.png) |
> fix compare button appearing once per every history row

- openlibrary/macros/AvailabilityButton.html
- openlibrary/macros/SearchResultsWork.html
- openlibrary/macros/daisy.html
- openlibrary/plugins/openlibrary/js/availability.js
- openlibrary/plugins/upstream/models.py
- openlibrary/plugins/worksearch/code.py
- openlibrary/plugins/worksearch/subjects.py
- openlibrary/templates/books/custom_carousel.html
- openlibrary/templates/type/author/view.html
- static/css/components/searchResultItemCta.less
- static/css/legacy.less
Closes #623 
Closes #2177 
Availability.js has been disabled for authors pages. Availability is injected directly into author's works on the backend. Page-size for authors works has been reduced to 20 (from 100) to avoid overflowing the availability v2 API w/ too many IDs.
This PR also removes `?edition=best` resolver as this was likely interfering w/ Availability js lookups (as noted by @jdlrobson in #2541 which should likely also be merged, though we're close to being able to deprecate availability.js :tada: )
https://dev.openlibrary.org/authors/OL31353A/Ursula_K._Le_Guin
> Disables availability.js for authors, fixes author availability

- openlibrary/macros/AvailabilityButton.html
- openlibrary/macros/LoanStatus.html
- openlibrary/macros/ReadButton.html
- openlibrary/plugins/upstream/borrow.py
- static/css/components/buttonCta.less
- static/css/components/editions.less
This PR allows us to generically use/apply the "Listen" button decoration to Read and Borrow buttons across the website.
Refactors read/borrow button into a macro
Go to editions, works, and search page on dev.openlibrary.org
> refactor listen experience, add to search page

- openlibrary/templates/type/edition/view.html
- static/css/components/work.less
Closes #2531 
**Feature:** Show the borrow CTA on mobile above the fold. Hide extra borrow CTA on tablet + desktop.
Placed this above the `lists/widget` on the `templates/type/edition/view` template, but open to placing it elsewhere.
1. Navigate to an Edition page (such as [this one](https://openlibrary.org/books/OL25930651M/The_Three-Body_Problem))
2. Resize browser to mobile width (or open a mobile view with devtools)
3. See borrow button appear on mobile only
**Mobile view:**
**Tablet:**
Chose to hide the button beginning with tablet breakpoints as I felt it wasn't necessary here.
**Note**
As you can see above, I chose to have the button `display: block` so it would expand the width of the `editionCover` div. Here's what it looks like with `display: inline-block`. I can do whichever …
> 2531: show borrow CTA above fold on mobile

- openlibrary/macros/BookSearchInside.html
- openlibrary/macros/LoanStatus.html
- openlibrary/macros/ReadButton.html
- openlibrary/plugins/books/code.py
- openlibrary/plugins/upstream/borrow.py
Closes #2590 
For public domain and open/unrestricted editions, a new button appears which enables patrons to go directly into the archive.org book using a search query.
We leverage the openlibrary.org/borrow/ia endpoint by passing along a GET parameter of `q=` in order to pass/propagate a search-inside query along to the archive.org/stream bookreader. This further DRY's our process so `/borrow/ia` is the only way to read, borrow, or search inside. We couldn't just form submit a GET from the editions page to /stream because the BookReader uses/hijacks the `#` operator to denote search (e.g. `#page/104/mode/2up/search/thinking`) and forms (at least w/o javascript) can only submit form and GET parameters, not dynamically map an input to the hash (and encode, decode).
- only shows up on open …
> Search-Inside button on Editions for unrestricted books

- openlibrary/plugins/upstream/borrow.py
We need to protect against the case where `i.q` is not defined (`AttributeError`) by setting its default in `web.input(q="")`
> Make sure i.q doesnt' AttributeError on q

- openlibrary/macros/WorldcatLink.html
Hotfix required by our partners @ librarylink. The current isbn10to13 is failing because we have since normalized edition pages to use (i.e. pass in) isbn13.
> Fix librarylink isbns

- LICENSE
- Readme.md
Including the text version allows GitHub to display the license name:
Additionally the FSF recommends including the full text: 
[You should also include a copy of the license itself somewhere in the distribution of your program.](https://www.gnu.org/licenses/gpl-howto.html)
Also I think that the license doesn't need to be mentioned in the TOC, as it slows down when skimming through the text.
> Use text version of the license

- openlibrary/plugins/openlibrary/js/graphs/plot.js
Closes #2483 
Replaces non-working i18n placeholders in JS files with the actual English string, until a proper frontend i18n system is implemented. This obviously bypasses any translation system, but it's still better than cryptic placeholders for now.
The python babel i18n that is currently in use fundamentally does not work with JS files. I.e. even if you could statically replace the placeholders before the JS files get delivered, it could cause problems with dynamic language switching and caching.... A separate system for the client-side should be evaluated and implemented (#2353 seems to be a collection of issues/ideas about that).
Follow the steps described in issue #2483 .
> Remove ineffective i18n placeholders from JS files

- openlibrary/macros/BorrowTrouble.html
- openlibrary/macros/TypeChanger.html
- openlibrary/macros/WorkInfo.html
- openlibrary/plugins/openlibrary/js/index.js
Use `aria` attributes to describe the relationship between these links and the elements they reveal. Remove a `hidden` class when
impacts its functionality.
Closes #
This fixes a bug in 3 "slideToggle" links hidden in obscure parts of the UI. It gets more JS out of templates and into the entry point.
Visit http://localhost:8080/about.en?m=edit and click "Huh?"
and ensure it reveals information
> Replace onclick handler with a JS wireup.

- openlibrary/macros/BookPreview.html
- openlibrary/macros/BookSearchInside.html
- openlibrary/macros/LoanStatus.html
- openlibrary/plugins/openlibrary/js/ol.js
- openlibrary/templates/type/edition/view.html
- static/css/components/buttonCta.less
Closes #2612
Hotfix: Fixes preview button not opening floater
**Recommend [hiding whitespace changes](https://github.com/internetarchive/openlibrary/pull/2614/files?utf8=%E2%9C%93&diff=split&w=1)**; the diff looks larger than it is.
The issue was that there were 2 floaters being rendered with the same ID, and that one of them was inside the `mobile-borrow-cta` div. This div is hidden on desktop, so it the floater would never display.
Fixed by:
- Add option to render the floater; not super elegant, but gets the job done with minimal tech debt
- Remove id on preview button; since that is bound via jquery, it's technically undefined behaviour to try to select multiple elements with the same ID, so it's uncertain what would happen
- made the class `cta-btn--preview` exclusive to the preview …
> hotfix: preview button doesn't open floater

- openlibrary/templates/admin/index.html
Makes the stats on https://openlibrary.org/stats clearer and fixes some HTML validation errors raised by
https://validator.w3.org/nu/?doc=https%3A%2F%2Fopenlibrary.org%2Fstats
> Clearer stats and fix img validation errors

- openlibrary/macros/databarAuthor.html
- openlibrary/plugins/openlibrary/js/dialog.js
- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/plugins/openlibrary/js/tabs.js
- openlibrary/templates/account/borrow.html
- openlibrary/templates/books/edit.html
- openlibrary/templates/covers/author_photo.html
- openlibrary/templates/covers/book_cover.html
- openlibrary/templates/covers/book_cover_single_edition.html
- openlibrary/templates/covers/book_cover_work.html
- openlibrary/templates/covers/change.html
- openlibrary/templates/lib/history.html
- openlibrary/templates/lib/markdown.html
- openlibrary/templates/lib/message_addbook.html
- openlibrary/templates/lists/widget.html
- openlibrary/templates/merge/authors.html
- openlibrary/templates/type/author/edit.html
- openlibrary/templates/type/author/view.html
- openlibrary/templates/type/edition-history/view.html
- openlibrary/templates/type/edition/view.html
- package.json
Inside various templates we call $.tabs, $.colorbox and $.dialog - these will now be invoked inside JavaScript and only when the element is clicked to minimise the intial JS execution.
In the case of the dialog for changing covers, the use of $.tabs is delayed until just before the dialog is presented to the user
This is helping us work towards fixing #2340
This shifts code from templates to the client.
1) Confirm that the code moved from templates is now accounted for in the JS.
2) Visit https://openlibrary.org/books/OL18141225M/Snow_crash/edit and confirm that the tabs are shown and usable (what's it about? add excerpts links )
3) Confirm that when hovering over a cover shows "manage cover" on https://openlibrary.org/books/OL18141225M/Snow_crash . When clicked a dialog should open with …
> Pull dialog and tabs code from templates

- .dependabot/config.yml
Make automated PRs for JavaScript dependencies like we already have for Python.
https://github.com/internetarchive/openlibrary/pulls/app%2Fdependabot-preview
> Dependabot: Add JavaScript dependency checking

- openlibrary/templates/type/edition/view.html
Closes #2405
Feature: AggregateRating microdata
- Corrected `itemprop` `In language` to `inLanguage` as per spec.
- Added `exampleOfWork` microdata linking back to the work
- Forced the ratings to appear by adding `$ rating_stats = {'avg_rating': 4.6, 'num_ratings': 12}` to html template
- Copied the rendered HTML into https://search.google.com/structured-data/testing-tool/u/0/ ; got:
- No visible changes
@jdlrobson
> Add aggregate rating microdata to editions page + small microdata fix

- static/js/jquery-ui-1.12.1.min.js
This is built from vendor. Having this file here leads to confusion that it can be used.
This file is currently unused. We use the one in vendor folder.
No PR. Removing it was easier than writing an issue.
@cdrini
> Dev: Drop jquery ui file in static folder

- openlibrary/plugins/openlibrary/js/automatic.js
- openlibrary/plugins/openlibrary/js/dialog.js
- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/plugins/openlibrary/js/tabs.js
- openlibrary/plugins/openlibrary/js/utils.js
- openlibrary/templates/lists/lists.html
- openlibrary/templates/lists/widget.html
This sets up the stage for finally moving jQuery UI off the critical path (#2340) and moving the large major JS feature into webpack (#2468). This reorganises code relating to tabs and dialogs to more suitable logical places.
This shifts code. The important change it makes is that dialogs will now only be initialised when they are clicked rather than on initial JS execution.
Make sure you test the add cover workflow and tabs therein.
@cdrini
> Tab dialog code organisation

- openlibrary/plugins/openlibrary/js/editions-table/index.js
- openlibrary/plugins/upstream/models.py
- openlibrary/templates/books/edition-sort.html
- openlibrary/templates/type/work/editions_datatable.html
Closes #806
Fix: Edition tables now sort as intended (although still using only year data).
- fix edition table's sort by publication date (I think it was a race condition where the JS was trying to change the ordering of the HTML elements by setting the `count` element's HTML, while the dataTables library was also simultaneously re-ordering them)
- refactor Work.get_sorted_editions for better readability and to actually do what it says
- always show publisher section in editions table, since the code handles all the cases
- Copydocs some data:
```sh
docker-compose exec web python scripts/copydocs.py -r /works/OL1100007W /books/OL6904901M /books/OL23349009M /books/OL11088183M /books/OL13936862M /books/OL9207799M /books/OL16819841M /books/OL7189111M /books/OL7111251M /books/OL6942515M …
```
> Fix edition table's sort by publication date + small cleanups

- CONTRIBUTING.md
Feature. Edit contributing to:
1. Limit merge/PR owner access to maintainers
2. Avoid having author=assignee
3. In the case where a special deploy is required, the assignee will label it as `Needs: Deploy Approval`. The assignee must then get confirmation from the deployer before merging in the PR.
(As discussed on slack)
> Edit instructions on merging pull requests

- openlibrary/catalog/add_book/__init__.py
- openlibrary/olbase/tests/test_ol_infobase.py
- openlibrary/plugins/ol_infobase.py
- openlibrary/utils/isbn.py
- openlibrary/utils/tests/test_isbn.py
- openlibrary/utils/tests/test_utils.py
to aid with matching _and_ ensure correct format ISBNs are saved if a
new record is created.
Closes #49 
Investigating the remaining tasks I added on #49, I have discovered:
* openlibrary/plugins/importapi/code.py DOES NOT perform any ISBN cleanup or validation. (this is probably ok)
* Next part of the import openlibrary/catalog/add_book/__init__.py only temporarily cleans the ISBNs for comparing with existing records...
* it DOES NOT strip hyphens when / if the ISBNs are saved
This PR moves the hyphen stripping code to an early point in the `load()` matching process so the stripping is only done once, and is retained if the edition is actually saved.
This fix is somewhat hypothetical since the original problem was reported specifically on code that has not run in years, and I cannot find …
> Normalise ISBNs early on load() attempt,

- openlibrary/templates/books/edit/edition.html
Closes #2454 
Fixes lack of detail in help text of edit form.
The wording of the FAQs is likely to change, but the link should be added in any case.
Go to edition edit form pagination section. You should see a 'Help' link to FAQs wiki.
http://localhost:8080/books/OL2058361M/The_wit_wisdom_of_Mark_Twain/edit
> Add link to pagination help FAQ

- openlibrary/macros/AvailabilityButton.html
- openlibrary/macros/LoanStatus.html
- openlibrary/templates/books/edition-sort.html
Closes #2346
Fixes confusing text.
I have changed the text from "No ebook available" to "Not in Library".
Go to a Work page to see if "Not in Library" text appears for editions that are not in Open Library.
http://localhost:8080/works/OL54120W/The_wit_wisdom_of_Mark_Twain
http://localhost:8080/books/OL3421846M/The_wit_and_wisdom_of_Mark_Twain
http://localhost:8080/search?q=title%3A+%22the%22&mode=everything
@cdrini
> Changed 'no ebook available' to 'not in library'

- openlibrary/templates/books/custom_carousel.html
- package.json
- static/css/components/carousel.less
Closes #2247 (continuation of #2368)
Fix: Works without covers now get an HTML-cover with title/author text.
Note this only affects cases where there is no cover; not cases where the cover errors.
1. Go to a subjects page e.g. http://localhost:8080/subjects/science
2. Observe that instead of blank covers, covers with text are displayed.
e.g. http://localhost:8080/subjects/science
@hornc @jdlrobson
> When no cover show title and author

- CONTRIBUTING.md
- Readme.md
Closes #2743
Adds a link from CONTRIBUTING.md to wiki page of GitHub tips for beginners. This was discussed on the community call held December 10, 2019.
> Add link to GitHub tips for beginners.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question_template.md
Closes #2671
The validity of the `State: Backlogged` label is still be discussed so this PR is still blocked by #2671 
@brad2014
> Make issue templates compliant with #2671 (Replaces #2672)

- static/css/components/page-history.less
- static/css/layout/index.less
This makes all wiki pages (with large images) fit to the width of parent and not overflow.
Closes #2747
> fixing wiki pages e.g. sponsorship to work on mobile

- openlibrary/plugins/openlibrary/js/autocomplete.js
- openlibrary/plugins/upstream/addbook.py
- openlibrary/plugins/upstream/tests/test_addbook.py
- openlibrary/templates/books/edit/edition.html
Closes #2138 
Feature: Adds an option for librarians to create a new work when moving and edition.
- Also now displays JSON errors that come up in addbook (previously just suppressed)
TODO: I've been trying to get this on OJF so that I don't have to do the testing all by my self, but am completely blocked by the fact that you can't create a new account in the local dev env (#2667) :(
- ✅ Moving edition from one work to another works
- ✅ Associating an orphan with an edition works
- ✅ Editing an orphan creates a work
- ✅ Select "move to new work" for an orphan creates a work
- ✅ Select "move to new work" for a regular edition creates a work
@seabelis
> Add librarian option to create new work when moving edition

- static/css/components/header-bar.less
Closes #1881 ; fix profile image appearing uneven if not square
Just set the CSS to `background-position: center`
Go to any page logged in; e.g. http://localhost:8080/books/add
@jdlrobson
> center profile image in header

- openlibrary/plugins/openlibrary/code.py
Closes #2706 ; Fix dev.openlibrary.org appearing in search results
- uses the `feature.dev` option in `openlibrary.yml` to determine which robots file to load.
- Checked this config is enabled for dev.openlibrary.org, and not present for prod
1. Go to `http://localhost:8080/robots.txt` ; should disallow all
2. Change `openlibrary.yml` to remove `feature.dev: enabled`, and restart dev instance
3. Go to `http://localhost:8080/robots.txt` ; should not disallow everything
No UI changes
@mekarpeles
> Load norobots.txt when in a dev instance

- Makefile
- package.json
- webpack.config.js
Closes #2692 ; hotfix to make sure the latest JS files are loaded after a deploy
- Two line change - ~2 hours of reading webpack docs 😅 
- docs: https://webpack.js.org/configuration/output/#outputchunkfilename
1. Run `make js`
2. Confirm generated JS files have hashes
3. Confirm carousels load on http://192.168.99.100:8080/
No UI changes
@jdlrobson
> Make dynamic JS files include cache-busting hashes

- openlibrary/core/vendors.py
A regression either on OL or BWB's side (relating to urllib2) is causing BWB API calls to fail. This PR is a `P0` hotfix which  switches `urllib2` to use `requests` in `core/vendors.py`.
Minimum repro case:
```
import urllib2
BWB_API = 'https://products.betterworldbooks.com/service.aspx?ItemId='  # or "http"
req = urllib2.Request(BWB_API + '9780375806704')
f = urllib2.urlopen(req)
```
results in:
```
File "<stdin>", line 1, in <module>
File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
return _opener.open(url, data, timeout)
File "/usr/lib/python2.7/urllib2.py", line 404, in open
response = self._open(req, data)
File "/usr/lib/python2.7/urllib2.py", line 422, in _open
'_open', req)
File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain …
```
> hotfixing urllib2 + bwb API

- openlibrary/macros/databarView.html
Closes #2637
Fix
First PR but I think it's fairly straightforward.
Follow the steps in the issue or navigate to any non work/author/edition page (or any page that does not have a set URL) and click history. Previously the history link would refresh the page, now it correctly navigates to the history page.
> Fixes history link on pages without url

- openlibrary/templates/borrow_admin.html
Works on #2798
Fixes html validation issues in `openlibrary/templates/borrow_admin.html`
Proposed:
Visit https://openlibrary.org/books/OL812375M/Sense_and_sensibility/borrow_admin
@jdlrobson @mekarpeles @koderjoker
> Resolve HTML validation issues with borrow_admin

- static/css/components/cbox.less
Closes #2583 
Just increasing the padding to increase the touch area would have misaligned the dialog title and made the header bigger:
Instead we have left the title and close button in the same place as before the fix:
It would be possible to make the click area exactly 44x44 by using decimals on the margin/padding values but seems unnecessary since as mentioned [here](https://www.w3.org/WAI/WCAG21/Understanding/target-size.html) _"Ensuring that touch targets are at least 44 by 44 CSS pixels."_ is enough.
> Remove underline and increase touchable area on dialog close button

- openlibrary/templates/site/head.html
Feature: Google Search Console is a tool that tracks a site's SEO performance. E.g.:
- Keywords used to find openlibrary
- Page-specific SEO audits
- JS errors that occurred while google bot was indexing the site
- load time estimates of the site
NOTE: This _does not_ in any way send any data to Google. This _gives us_ access to the data Google already collects about the site when its Googlebot does its indexing. The only change is a key in the HTML which gives my archive.org account permission to view that data.
There are three ways to enable this:
1. Edit the DNS config
2. Use GA account - Can't do this because openlibrary doesn't load the GA JavaScript to protect user privacy
3. Add the key as a meta tag
We already have a few other verification keys in the site's `head.html`, so 3 …
> Get google search console access

- openlibrary/macros/SocialShare.html
- openlibrary/macros/databarWork.html
Fix: Add GA tracking to share embed button
See diff w/o whitespace: https://github.com/internetarchive/openlibrary/pull/2764/files?utf8=%E2%9C%93&diff=split&w=1
- also some small refactoring/code quality fixes
Go to http://192.168.99.100:8080/books/OL2058361M/The_wit_wisdom_of_Mark_Twain and click "embed" button
No changes
> Add google analytics to ShareEmbed button + misc cleanups

- openlibrary/plugins/openlibrary/home.py
- openlibrary/templates/home/index.html
Closes #2820 
removed `preset:children` and added `subject(Juvenile Fiction)` in query
@mekarpeles
> No more inappropriate content in kids carousel 

- openlibrary/i18n/de/messages.po
hotfix: fix German translations; otherwise the translations won't appear at all.
The issue was the format of the date; I fixed the other issues mentioned in #2818 while I was here.
1. Run `docker-compose exec web make i18n`; confirm all compile
2. Go to http://loclahost:8080/?lang=de
Dev: https://dev.openlibrary.org/?lang=de
@tfmorris
> Fix German .po file syntax error

- openlibrary/plugins/worksearch/languages.py
- openlibrary/plugins/worksearch/publishers.py
- openlibrary/plugins/worksearch/subjects.py
- openlibrary/templates/publishers/view.html
- scripts/copydocs.py
closes #314
also
fixes #2249 
with this change
https://github.com/internetarchive/openlibrary/pull/2684/files#diff-6c3e80b6749b6b6a0af58257952db8aaR107
**Sets subject API limits:**
example, if client specified `limit=10000` , the site performs poorly.
https://openlibrary.org/subjects/history.json?limit=100&has_fulltext=false&sort=editions
This is a metadata subject value = "History" which has confused past attemtps at investigating this issue.
An equivalent URL is 
https://openlibrary.org/subjects/games.json
Without specifying a limit, the default response contains 12 results.
Now the API response will be:
```
{"error": "Specified limit exceeds maximum of 1000."}
```
with headers (from local env):
```
HTTP/1.1 400 Bad Request
Server: gunicorn/19.9.0
Date: Tue, 17 Dec 2019 04:57:14 GMT …
```
> set max subject API limit to 1000

- openlibrary/core/sponsorships.py
- openlibrary/core/vendors.py
- openlibrary/plugins/admin/code.py
- openlibrary/templates/admin/menu.html
- openlibrary/templates/admin/status.html
- openlibrary/tests/core/test_vendors.py
Right now BWB price API only returns things directly in BWB holdings (not third party or partners, i.e. "other sellers"). BWB prefers this because the BWB API is intended for affiliates and these "other seller" books are not good candidates for affiliate sales.
This said, the Internet Archive would like to enable as many books to be sponsored as patrons want, and so (instead of hitting the API) we provide a mechanism to say -- if the BWB price API fails, attempt to hit the live BWB website for price and quality information.
We only use this mechanism when we suspect a book may be eligible for sponsorship (i.e. it passes a bunch of other checks). This won't be displayed to the average user on the website.
**Risks**
The regex check for scraping the site is somewhat fragile. If the BWB …
> Updates Sponsorship to scrape bwb site for price data if API fails (to include other sellers) 

- openlibrary/conftest.py
fix: Got stuck on this for a good while while working on the #2791 ; so to help the next folk, make the error message clearer :)
- Tested the message appears if `requests.get` is called
@hornc
> Network requests are blocked in tests; make error message clearer

- openlibrary/core/helpers.py
Closes #2840 
Required because of https://travis-ci.org/internetarchive/openlibrary/jobs/635160585#L890
https://six.readthedocs.io
> from six.moves.urllib.parse import urlsplit

- openlibrary/i18n/__init__.py
Closes #2840 
Required because of https://travis-ci.org/internetarchive/openlibrary/jobs/635159854#L889
https://six.readthedocs.io/#six.StringIO
> from six import StringIO

- openlibrary/catalog/add_book/__init__.py
- openlibrary/core/ia.py
- openlibrary/mocks/mock_ia.py
- openlibrary/plugins/books/dynlinks.py
- openlibrary/plugins/books/readlinks.py
- openlibrary/plugins/books/tests/test_dynlinks.py
- openlibrary/plugins/importapi/code.py
- openlibrary/plugins/openlibrary/home.py
- openlibrary/plugins/upstream/models.py
- openlibrary/solr/process_stats.py
- openlibrary/tests/core/test_ia.py
- scripts/2011/09/generate_deworks.py
* Closes at least part of #2621, I cannot reproduce the bulk MARC errors from the issue locally, so I may have fixed the problem. 
* This does fix the import errors failing in https://openlibrary.org/admin/imports caused by not finding a cover image on archive.org. 
* This PR also enables more covers to be found and added to coverstore, in fact I think it will put an end to some imports from archive.org having to pull covers from archive.org because they don't have coverstore covers. We could try a reimport of all items with ocaids and no cover, then remove all the code tasked with loading the previews from archive org?
* Refactor of the `ia` module and import api code so that archive.org specific code is more consolidated.
There are very many infobase errors occurring on imports 
``` …
```
> Use cover.jpg if title.jpg does not exist, and never send empty covers to infobase

- openlibrary/plugins/upstream/utils.py
Closes #2839 
hotfix: Disabled donation banner until fix is finished on IA's side.
- To be re-enabled once bug on IA's side is fixed in https://github.com/internetarchive/openlibrary/issues/2839
- Leave enabled on dev so that they can still continue testing
- ✅ Check http://localhost:8080/?ymd=2019-12-06 displays banner locally
- ✅ http://localhost:8080/?ymd=2020-01-06 does not display banner
@mekarpeles
> Temporarily disable donation banner on prod

- openlibrary/plugins/worksearch/code.py
Closes #2846 
- Fix existing response header for - `/search.json?q=isbn:9780062935045&mode=everything`
- There is no `Content-Type` property
- Edited `openlibrary/plugins/worksearch/code.py` to apply header
- Execute locally via docker
- Browse to `http://localhost:8080/search.json?q=isbn:9780062935045&mode=everything`
- Open Inspector and catch the call in `Networks` tab
**Screenshots**
Live version - 
PR version -
@cdrini
> Edit API to add Content-Type, fixes #2846

- openlibrary/templates/type/edition/view.html
Closes #2382
Before:
After:
@cdrini
> Remove Work description if edition description is present 

- Makefile
- openlibrary/i18n/__init__.py
Previously, `make i18n` wouldn't provide any info about what caused an error, and would not fail the build.
Diff ignoring whitespace: https://github.com/internetarchive/openlibrary/pull/2835/files?utf8=%E2%9C%93&diff=split&w=1
- I added this while working on #2834 , and it caused an error to be thrown on `make i18n`
- Modify `/de/messages.po` to have an invalid date in "last modified". Running `make test` should result in a failure.
@tfmorris
> Don't silence i18n errors

- openlibrary/mocks/mock_ol.py
Closes #
```
ImportError while loading conftest '/home/travis/build/internetarchive/openlibrary/openlibrary/conftest.py'.
openlibrary/conftest.py:18: in <module>
from openlibrary.mocks.mock_ol import ol
openlibrary/mocks/mock_ol.py:11: in <module>
from mock_infobase import mock_site, MockConnection
E   ModuleNotFoundError: No module named 'mock_infobase'
```
> from openlibrary.mocks.mock_infobase import mock_site, MockConnection

- openlibrary/catalog/add_book/__init__.py
- openlibrary/core/ia.py
- openlibrary/mocks/mock_ia.py
- openlibrary/plugins/books/dynlinks.py
- openlibrary/plugins/books/readlinks.py
- openlibrary/plugins/books/tests/test_dynlinks.py
- openlibrary/plugins/importapi/code.py
- openlibrary/plugins/openlibrary/home.py
- openlibrary/plugins/upstream/models.py
- openlibrary/solr/process_stats.py
- openlibrary/tests/core/test_ia.py
- scripts/2011/09/generate_deworks.py
Closes #2891
We tried this on ol-web3 for 30 minutes and memory usage looked stable. This appears to resolve #2891. We may want to carefully reapply #2838 incrementally to determine where our issues may be coming from (in a later commit)
Tested the works, editions, and /isbn import path.
n/a -- memory usage lowered
@hornc, @cdrini
> Reverting get_metadata code, caused memory leak on prod

- openlibrary/core/civicrm.py
- openlibrary/core/sponsorships.py
- openlibrary/core/vendors.py
- openlibrary/tests/core/test_sponsors.py
Closes #2879
Removes unnecessary `urlencode()` calls and fixes up the import for the remaining one that's needed.
@cdrini for `vendors.py` @tabshaikh for the others - as mentioned in the issue, I think this is your code, so please review. 
@mekarpeles
> 2879 requests cleanup

- openlibrary/plugins/openlibrary/home.py
Closes #2707
This changes the key for the cached home page from 'home.homepage' to 'home.homepage.{lang}'
> Cache the home page by language

- openlibrary/accounts/model.py
- openlibrary/admin/numbers.py
- openlibrary/app.py
- openlibrary/config.py
- openlibrary/core/cache.py
- openlibrary/core/db.py
- openlibrary/core/ia.py
- openlibrary/core/iprange.py
- openlibrary/core/lending.py
- openlibrary/core/msgbroker.py
- openlibrary/core/processors/invalidation.py
- openlibrary/core/processors/readableurls.py
- openlibrary/core/schema.py
- openlibrary/core/waitinglist.py
- openlibrary/data/dump.py
- openlibrary/olbase/events.py
- openlibrary/records/functions.py
- openlibrary/solr/solrdump.py
- openlibrary/templates/lib/markdown.html
- openlibrary/utils/bulkimport.py
- openlibrary/utils/form.py
- openlibrary/utils/processors.py
- openlibrary/utils/solr.py
Fix some typos discovered via [codespell](https://github.com/codespell-project/codespell).
```
python3 -m pip install codespell
SKIP=./openlibrary/catalog/*,./openlibrary/i18n/*,./openlibrary/macros/*,./openlibrary/plugins/*
codespell . -L ba,referer,te --skip=./.*,${SKIP},./.scripts/20*,*.gif,*.js,*.pg_dump,*.png,*.xsd
```
This PR only addresses some of the typos discovered so more work could be done in separate PRs.
> Fix some typos discovered via codespell

- openlibrary/mocks/mock_ol.py
Compatible with both web.py 0.3.9 and 0.4.0 as discussed at https://github.com/internetarchive/openlibrary/pull/2416#issuecomment-536190367
Closes #
> Make mock_ol.py compatible with old and new web.py

- openlibrary/macros/SocialShare.html
Hotfix: the embed share link was pointing to e.g. https://openlibrary.org/books/OL18768980M/widget instead of https://openlibrary.org/books/OL18768980M/-/widget , causing the iframe code to render the full page instead of just the widget
- ✅ Visit https://dev.openlibrary.org/books/OL18768980M/The_one_minute_manager , and copy/paste the embed code to see if it works.
@mekarpeles
> fix embed sharelink using wrong url

- openlibrary/plugins/importapi/code.py
that will be fully replaced by #2909
short term fixes #2915
Closes #
Addresses a missing constant that got dropped in the revert of a change which caused a memory leak but refactored away the requirement for an archive.org URL in this file. This adds the URL back so the code can temporarily function. #2909 will resolve the problem also, but this change allows us to revert #2909 if there are still memory leaks if we really need to, and still have working imports.
@cdrini if you can review and merge this, I will re-base #2909
> HOTFIX: temporaily re-add URL 

- openlibrary/templates/account/borrow.html
- openlibrary/templates/type/work/view.html
Closes #2925 . Hotfix to 2 issues:
- Loans page referencing undefined function (commit pulled from @tfmorris ' PR #2926)
- Excerpts showing uninterpolated markup
- ✅ Adding excerpts works/they get displayed correctly
- ✅ Excerpts by multiple people display correctly
- ✅ Excerpts display on https://dev.openlibrary.org/works/OL81613W/It
- ✅ Test https://dev.openlibrary.org/account/loans renders
@tfmorris
> Hotfix to some i18n bugs

- openlibrary/accounts/model.py
- openlibrary/tests/accounts/test_models.py
Fix: Previously was following the guidelines from https://www.peterbe.com/plog/jsondecodeerror-in-requests.get.json-python-2-and-3 , but it looks like the correct python 2/3 compatiable was is in the docs https://2.python-requests.org/en/master/api/#requests.Response.json ; i.e. except ValueError
Note that functionally this won't really make a difference, since in Python 2 it used to fallback to ValueError anyways, but this just makes it more python 3 compatible.
- Added a test to ensure this is working as expected
@hornc @tfmorris
> fix requests error handling in account registration

- openlibrary/core/processors/__init__.py
Absolute import that fixes 4 pytest failures when running on Python 3:
```
__________ ERROR collecting openlibrary/tests/core/test_processors.py __________
ImportError while importing test module '/home/travis/build/internetarchive/openlibrary/openlibrary/tests/core/test_processors.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
openlibrary/tests/core/test_processors.py:2: in <module>
from openlibrary.core.processors import readableurls as processors
openlibrary/core/processors/__init__.py:1: in <module>
from readableurls import ReadableUrlProcessor
E   ModuleNotFoundError: No module named 'readableurls'
___ ERROR collecting openlibrary/tests/core/test_processors_invalidation.py ____
ImportError while importing test module …
```
> Next Py3 pytest fix: import ReadableUrlProcessor

- openlibrary/accounts/model.py
- openlibrary/plugins/upstream/account.py
- openlibrary/plugins/upstream/forms.py
- openlibrary/templates/account.html
- openlibrary/templates/account/create.html
- openlibrary/utils/form.py
Closes #858. Feature: Add option to subscribe to IA newsletter on signup
~Based on #2912 ; merge that first. This is the _real_ diff: https://github.com/internetarchive/openlibrary/pull/2822/files/c8dcaf6406a31d955ec2c388dbb3385a3bb21f06..ebd528c409e2759cbfbd4f61be6029c771c68a6b?utf8=%E2%9C%93&diff=split&w=1~
- tested that the intent is recorded in the user's IA account object
- tested that the intent is **not** recorded in the users IA account object
- ~[ ] Emails should include an "unsubscribe" link that works~
- no clue how to test this :/
- includes a link to IA's user settings page
- ✅ Creating an account with "notifications" ticked results in xauth `info` calls returning `notifications: 'announce-general'` in response (! not an array?!)
- ✅ Creating an account **without** …
> Add option to subscribe to IA newsletter on signup

- openlibrary/accounts/model.py
- openlibrary/core/ia.py
- openlibrary/core/lending.py
- openlibrary/core/models.py
- openlibrary/macros/LoanStatus.html
- openlibrary/plugins/upstream/borrow.py
- openlibrary/templates/type/edition/view.html
- openlibrary/tests/core/test_ia.py
- static/css/components/read-panel.less
Adds a visual indication that a book has been sponsored
Closes #2567 of #2566
This needs to piggy-back on the existing availability check which OL is doing for the edition (to avoid 2 http requests being made to/for archive.org metadata). Refactors book availability check by injecting ia metadata call into edition template (rather than later/burried deeper in the LoanStatus macro)
You can see the changes on https://dev.openlibrary.org/books/OL25448615M/Reinventing_Organizations
> Adds sponsorship message to Edition page (refactors ia metadata call)

- openlibrary/plugins/upstream/utils.py
Closes #2889
[`UserDict.DictMixin`](https://docs.python.org/2/library/userdict.html#UserDict.DictMixin) was removed in Python 3 so use [`collections.abc.Mapping`](https://docs.python.org/3/library/collections.abc.html#collections.abc.Mapping) instead as we did in internetarchive/infogami#45.
> Replace deprecated UserDict.DictMixin with Mapping

- openlibrary/catalog/amazon/arc_view.py
- openlibrary/catalog/lang.py
- openlibrary/catalog/oca/parse.py
- openlibrary/catalog/onix/xmltramp.py
- openlibrary/core/middleware.py
- openlibrary/coverstore/tests/test_code.py
- openlibrary/coverstore/warc.py
- openlibrary/plugins/openlibrary/libraries.py
- openlibrary/plugins/search/solr_client.py
- openlibrary/plugins/upstream/addbook.py
- openlibrary/tests/core/mocklib.py
- openlibrary/tests/solr/test_update_work.py
- scripts/jsondump.py
Closes #
Run the following commands to find `StringIO.StringIO` issues:
1. `grep -r StringIO.StringIO .`
2. `grep -r "from StringIO" .`
Then change to import to `from six import StringIO` in alignment with https://six.readthedocs.io/#six.StringIO
---
Run `grep -r cStringIO .` to find `cStringIO.StringIO` issues and then change to import to
`from six.moves import cStringIO as StringIO` in alignment with https://six.readthedocs.io/#module-six.moves
> from six import StringIO for Python 2 and 3

- openlibrary/catalog/marc/build_record.py
Tell the flake8 linter to ignore this deprecated file.  Adding this flake8 directive removes 32 of the _undefined names_ that `make lint` discovers so that we can focus on resolving those that remain.  See #1684
Closes #
https://travis-ci.org/internetarchive/openlibrary/jobs/643480952#L342-L437
> Resolve 32 undefined names from `make lint`

- openlibrary/templates/history.html
Issue solved #2798
Fixes HTML validation issues in
openlibrary/templates/history.html
Proposed:
Replace HTML valign with CSS vertical-align
Stakeholder
@koderjoker
> replacing html valign with css vertical-align

- openlibrary/plugins/upstream/models.py
- openlibrary/plugins/upstream/utils.py
Closes #2957 
Fixes errors on loading any Edition page.
#2957 needs to be fixed before next deploy!
Uses MutableMapping from https://docs.python.org/3/library/collections.abc.html
to replace https://multidict.readthedocs.io/en/stable/multidict.html#multidict.MultiDict.update which is used in our code.
adds `__len__` and `__iter__` as was done in https://github.com/internetarchive/infogami/pull/45/files but missed out on #2935 
Tested locally in dev Docker.
> use MutableMapping which supplies update(), fix errors

- openlibrary/plugins/upstream/addbook.py
- openlibrary/templates/books/add.html
- openlibrary/templates/books/author-autocomplete.html
- openlibrary/templates/books/check.html
- openlibrary/templates/books/edit.html
Closes #1716 ; Fixes bug where adding a book would ignore the entered author.
- make author-autocomplete.html more configurable: In order for the author-autocomplete template to be used on both the add page and the edit page, one needs to be able to specify the paths of the form fields.
- Change the /book/add POST form to accept `authors` and `author_names` in the same format as edit page
- Since that means `authors` is now an array of objects, unflattens the input
- Updated anywhere this input item was passed to handle the new fields
- Previously was using the type-prefixed OLID for matching records in solr, which doesn't work
- Consolidate the author creation logic inside /books/add and edit page
- DRY up anywhere a new record is created to use same helper
- ✅ Creating new author from …
> Fix addbook endpoint ignoring author

- openlibrary/core/models.py
- openlibrary/i18n/fr/messages.po
- openlibrary/i18n/messages.pot
- openlibrary/macros/databarHistory.html
- openlibrary/macros/databarView.html
- openlibrary/templates/lib/history.html
Closes #2973
- created a util method to render an html link from a user object.
- ✅ Tested user links are correct in top left:
- http://localhost:8080/books/OL2058361M/The_wit_wisdom_of_Mark_Twain?lang=fr
- http://localhost:8080/books/OL2058361M/The_wit_wisdom_of_Mark_Twain
- ✅ Tested user links are correct in bottom table:
- http://localhost:8080/books/OL2058361M/The_wit_wisdom_of_Mark_Twain?lang=fr
- http://localhost:8080/books/OL2058361M/The_wit_wisdom_of_Mark_Twain
- ✅ Tested user links are correct in history table:
- http://localhost:8080/books/OL2058361M/The_wit_wisdom_of_Mark_Twain?lang=fr&m=history
- http://localhost:8080/books/OL2058361M/The_wit_wisdom_of_Mark_Twain?m=history
@tfmorris
> Fix "last edited by" link broken

- openlibrary/plugins/openlibrary/code.py
Relates to #2857
This is to get all the whitespace and quotation mark changes I'd make as part of this work out and merged in one go.
Double spaces between classes etc help me navigate the file faster, and are in PEP8 https://www.python.org/dev/peps/pep-0008/#blank-lines
> style and whitespace changes before fixing endpoint logic

- openlibrary/core/bookshelves.py
- openlibrary/plugins/openlibrary/api.py
Closes #2963 
- turns out for JSON endpoints we _don't_ need the `/-/`, so this lives at  `/works/OL1W/bookshelves.json`
- ✅ Shows all 0 for book not on any reading log
- ✅ After adding a book to want to read, count=1 for that field
- ✅ After adding a book to currently reading, count=1 for that field
- ✅ After adding a book to already read, count=1 for that field
> Add GET /works/OL1W/bookshelves.json API to get bookshelf counts

- openlibrary/solr/inside/index_gevent.py
`solr_src_host` is defined on line 36 and commented out so use `solr_host` defined with the same value on line 37.
This code is under `if False:` so can safely be ignored.
Closes #
> Remove undefined name: solr_src_host

- openlibrary/admin/templates/admin/index.html
Issue solved #2798
Fixes HTML validation issues in
openlibrary/admin/templates/admin/index.html
Issues:
1. In this index.html file the table data , strong , and br did not have closing tags.
2. the indentation was not proper.
What is done:
1.Made the indentation proper. (as now it is much easier to understand)
2. gave the closing tags.
Stakeholders:
@koderjoker
> some tags did not have closing tags and indentation was not proper in this file

- openlibrary/templates/borrow_admin.html
- openlibrary/templates/borrow_admin_no_update.html
- openlibrary/templates/type/author/view.html
relates to #2955
https://dev.openlibrary.org/authors/OL18524A/G._K._Chesterton
gives an error with the code from #2955 
```
/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/templates/type/author/view.html: error in processing template: NameError: global name 'get_library' is not defined (falling back to default template
```
Easy fix is to remove the `library` variable which is not used anywhere on that page.
This PR does that.
> remove unsused get_library() reference errors

- .travis.yml
This will ensure that PRs do not introduce new Python 3 errors.  Travis CI's current Python 3 run is done in __allow_failures__ mode so a PR can add a Py3-only syntax error without warning.  This PR adds a quick (< 1 minute) check to avoid such breakage.
A partial solution to #2300 and #3011
Closes #
> Travis CI: Run make lint on Python 3

- openlibrary/catalog/lc_updates/update.py
- scripts/lc_marc_update.py
As discussed to https://github.com/internetarchive/openlibrary/pull/3040/files#r379621016, `internal_error` and `no_bucket_error` are defined with identical values in [upload_arc.py](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/amazon/upload_arc.py#L15-L16) and in [upload.py](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/amazon/upload.py#L33-L34) but they are both ___undefined names___ in the files on this PR.  Here we copy the existing definitions to resolve the _undefined names_.
> Define internal_error and no_bucket_error

- openlibrary/data/dump.py
1. There is no mention of this function anywhere in this repo:
* https://github.com/internetarchive/openlibrary/search?q=pmap
2. This code overwrites the unused `Pool` (title case)
* `subprocess` has `no Pool.map_async()` but `multiprocessing` does https://docs.python.org/2/library/multiprocessing.html#multiprocessing.pool.multiprocessing.Pool.map_async
3. Line 138 contains two _undefined names_ `pool` (lowercase) and `results`.
```
./openlibrary/data/dump.py:138:13: F821 undefined name 'pool'
r = pool.map_async(f, tasks, callback=results.append)
^
./openlibrary/data/dump.py:138:47: F821 undefined name 'results'
r = pool.map_async(f, tasks, callback=results.append)
^
```
Closes #
> Remove unused pmap() function

- openlibrary/plugins/upstream/addbook.py
Helps with, but doesn't c.l.o.s.e #2107
These former 'system' subjects `["Accessible Book", "Lending Library", "In Library", "Protected DAISY"]` are no longer used by the system to indicate lending status and have been deprecated as they are not technically subjects. See #2107 
This PR allows any user / librarian to clean these from records if they encounter them.
Deletes code => reduces complexity.
> Don't protect deprecated system subjects

- openlibrary/catalog/marc/marc_binary.py
Fix undefined name with:
[`re_isbn = re.compile(r'([^ ()]+[\dX])(?: \((?:v\. (\d+)(?: : )?)?(.*)\))?')`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/marc/marc_base.py#L3)
https://github.com/internetarchive/openlibrary/pull/3040#discussion_r379621016 says that this solution is wrong but I am unable to [find a better one](https://github.com/internetarchive/openlibrary/search?q=re_isbn).
```
./openlibrary/catalog/marc/marc_binary.py:197:17: F821 undefined name 're_isbn'
m = re_isbn.match(f.line[3:-1])
^
```
Closes #
> Fix undefined name re_isbn

- openlibrary/tests/core/test_sponsors.py
```
./openlibrary/tests/core/test_sponsors.py:69:16: F821 undefined name 'mock_site'
work = mock_site.quicksave("/works/OL1W", "/type/work", title="Foo")
^
```
Closes #
> Fix undefined name mock_site

- openlibrary/catalog/marc/html.py
- openlibrary/catalog/marc/tests/test_marc_html.py
Fixes #3064 and adds doctests.
Closes #
> Undefined names: html_subfields() and html_line()

- openlibrary/macros/BookPreview.html
- openlibrary/plugins/openlibrary/js/ol.js
- static/css/components/preview.less
Closes #2841
Fix: Make the editions page only load the iframe when the modal is opened.
- It's non-trivial to have a generic solution to "do something when this element becomes visible", so opted to make this solution specific to the colorbox that needs it.
- ✅ http://192.168.99.100:8080/books/OL6179353M/Slide_rule Does not log "soundmanager" stuff (part of IA bookreader) on page load
- ✅ Clicking the preview button console.log "soundmanager" stuff (and shows preview)
- ✅ Closing the preview does not log anything
- ✅ Opening preview again does nothing logs the stuff (and shows preview)
@mekarpeles
> Make editions page lazy load IA preview iframe

- openlibrary/core/models.py
hotfixing lending
Closes #3028
`lendinglibrary` is a deprecated collection, `inlibrary` is what we wanted. `inlibrary` was accidentally removed because it looked related to the PR in https://github.com/internetarchive/openlibrary/pull/2955/files#diff-6b8bedf4a9d4d4148e6b17b3e2b92a9fL288-R287 but was not.
Borrowing should now succeed (go to borrowed book) not bring up a preview on archive.org, re-asking patron to borrow.
cc: @cdrini
> Hotfix lending not single-click borrowing

- openlibrary/plugins/importapi/code.py
- openlibrary/plugins/importapi/import_opds.py
- openlibrary/plugins/importapi/import_rdf.py
Use absolute imports in the plugin importapi for compatibility with both Python 2 and Python 3.
> importapi: Use absolute imports

- openlibrary/plugins/search/code.py
- openlibrary/plugins/search/solr_client.py
- openlibrary/plugins/worksearch/code.py
Use absolute imports in the plugin search for compatibility with both Python 2 and Python 3.
These changes close 5 out of our current 9 open pytest errors on Python 3.
> search: Use absolute imports

- openlibrary/plugins/search/solr_client.py
`search()` is an undefined name in this context but `self.search()` is defined 7 lines below.
```
./openlibrary/plugins/search/solr_client.py:207:17: F821 undefined name 'search'
s = search(self, query, start=loc)
^
```
Closes #
> Undefined name: search(self) --> self.search()

- openlibrary/utils/bulkimport.py
In Python 3 variables created inside a comprehension are not available outside that comprehension.
This change avoids the comprehension to ensure that `doc` is available to be printed in the except clause.
```
./openlibrary/utils/bulkimport.py:133:24: F821 undefined name 'doc'
print(repr(doc))
^
```
Closes #
> Py3 has stricter scoping rules for list comprehensions

- scripts/new-solr-updater.py
Feature. Add option for solr-updater to exclude edits: specifying e.g. `--exclude-edits "fake subjects"` excludes edits containing the text "fake subjects".
- Bulk edits bring solr updater to a near stand still; sometimes it might be better to just ignore these edits, knowing they'll be added when a full re-index is done at some point in the near future.
(for previous iteration, but should still work; not re-testing).
1. ✅ Add junk text to [some work](http://192.168.99.100:8080/works/OL53924W/The_complete_works_of_Mark_Twain) ; confirm shows up when searching for that junk text
2. ✅ Add junk text to [some other work](http://192.168.99.100:8080/works/OL5702375W/Three_cups_of_tea); confirm shows up when searching for that junk text
3. ✅ Add junk text to [some other …
> Add solr-updater option to skip edits

- scripts/new-solr-updater.py
Hotfix: Accidentally forgot to update references to this arg after updating it argparse name -\_-
> hotfix: fix incorrect arg name in new-solr-updater.py

- scripts/copydocs.py
Closes #2942
Uses absolute import to resolve pytest on Python 3 result:
```
_______________ ERROR collecting scripts/tests/test_copydocs.py ________________
ImportError while importing test module '/home/travis/build/internetarchive/openlibrary/scripts/tests/test_copydocs.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
scripts/tests/test_copydocs.py:1: in <module>
from ..copydocs import copy, KeyVersionPair
scripts/copydocs.py:18: in <module>
import _init_path
E   ModuleNotFoundError: No module named '_init_path'
```
We want to be able to run:
1. `scripts/copydocs.py`
2. `python2 scripts/copydocs.py`
3. `python3 scripts/copydocs.py`
> Absolute import: from scripts import _init_path again

- openlibrary/accounts/model.py
- requirements_common.txt
Closes #2945
Replaces obsolete and unmaintained `lepl` parser module (which was way overkill) with the `validate_email` module.
This also cuts down on a huge number of deprecation warnings in our Python 3.8 CI tests.
@hornc Note that this requires a dependency update.
> Replace lepl with validate_email

- static/css/page-dev.less
The dev stylesheet is only loaded when dev is enabled in
openlibrary.yaml
This is explicitly disabled on production (note that no page-dev.css
file loads)
Additional change:
* Limit banner styling so it's easier to develop.
Fixes: #2129
> Make dev.openlibrary.org visually distinct from production openlibrary

- openlibrary/core/sponsorships.py
N/A -- bulk items do not have a repub_state -1 so we update our checks s.t. book which need purchasing have a -1 repub_state (set by book sponsorship flow) 
Minor refactor to make it easier to test our sponsorship query results.
tested on dev, affects admin only
Query can be tested on `ol-dev0` via:
```
import infogami; from openlibrary.config import load_config; load_config('/opt/openlibrary/olsystem/etc/openlibrary.yml'); infogami._setup(); from openlibrary.core.sponsorships import get_sponsored_books;
```
@cdrini
> book needs_purchase only if no price AND repub_state -1

- Makefile
This is the uncontroversial bit of #3120  I'm trying to run the linting Makefile tasks locally and node_modules + the acs4 symlink are blocking.
> exclude node modules from linting

- openlibrary/catalog/marc/marc_binary.py
This PR fixes 63 failing pytests on Python 3.
$ python3
```
>>> range(15 / 3)
File "<stdin>", line 1, in <module>
TypeError: 'float' object cannot be interpreted as an integer
>>> range(15 // 3)
range(0, 5)
```
Closes #
> Use integer division for Python 3

- openlibrary/core/vendors.py
hotfix to add error handling to last amazon #3125 which resulted in
```
ApiException: (400) Reason: Bad Request HTTP response headers: HTTPHeaderDict({'x-amzn-RequestId': 'c935a5db-2f02-4608-9586-58e759bfbfb1', 'Content-Length': '180', 'Vary': 'Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent', 'Server': 'Server', 'x-amz-rid': 'VQ7MYA1E7CB0YN6981NE', 'Connection': 'keep-alive', 'Date': 'Fri, 06 Mar 2020 05:15:12 GMT', 'Content-Type': 'application/json'}) HTTP response body: {"__type":"com.amazon.paapi5#ValidationException","Errors":[{"Code":"InvalidParameterValue","Message":"The value [9791186701072] provided in the request for ItemIds is invalid."}]} (falling back to default template)
```
> fixing amazon call, error handling

- openlibrary/templates/admin/sponsorship.html
Fixes /admin/sponsorships page print-slips link to only include isbns in 'needs-digitize' state (otherwise too many isbns)
> printslips now only considers needs-digitize books

- openlibrary/templates/covers/add.html
- openlibrary/templates/covers/change.html
- static/css/components/carousel.less
- static/css/components/cbox.less
- static/css/components/throbber.less
- static/css/components/ui-tabs.less
- static/css/js-all.less
- static/css/legacy.less
- static/css/page-form.less
Fixes: #2132 #2373
Restores the orange border to selected carousel covers. Improves display on mobile.
Note: if you don't like the design - this is out of scope - that can be done as a follow up :)
Click the change cover button and select different covers.
> Restore orange select border in change cover dialog / add responsive behaviour

- openlibrary/plugins/upstream/addbook.py
Closes #906 and follows up on the work of #2990
While logged out, go to dev.openlibrary.org/addbook. You should be redirected to login with a referrer of /addbook (once logged in)
@user404d
> fixing addbook if not logged in via login redir

- openlibrary/plugins/admin/code.py
- openlibrary/plugins/upstream/addbook.py
- openlibrary/plugins/upstream/tests/test_addbook.py
- openlibrary/templates/books/edit.html
- openlibrary/templates/books/edit/edition.html
- openlibrary/templates/type/edition/view.html
Closes #2329 - enables Librarians to perform operations like removing archive.org ID and syncing with Archive.org OLIDs.
refactor
permissions related
As a librarian / non admin, try syncing an edition's `olid`s.
@seabelis
> Librarian Permissions

- openlibrary/plugins/upstream/account.py
Closes #2985 
When a patron registers for an OpenLibrary.org account, activates, and then logs in, successful login should **not** redirect the patron back to `referrer` (if referrer was archive.org/account/verify.php). This PR resolves this edge case. (some times upon login we may want to send to a remote referrer)
N/A
Registered an account on dev.openlibrary.org, activated via archive.org, was presented with a link to login via openlibrary.org (edited this url in the page source to point to **dev.openlibrary.org**, clicked this link, logged in, and was presented with openlibrary.org (as expected) -- not redirected back to archive.org.
@cdrini
> don't redirect back to archive.org after activate + login

- openlibrary/core/cache.py
- openlibrary/coverstore/disk.py
`string.letters` was removed in Python 3 in favor of `string.ascii_letters`
https://docs.python.org/2/library/string.html
https://docs.python.org/3/whatsnew/3.0.html#library-changes
Closes two failing pytests on Python 3.
> Python 3: string.letters --> string.ascii_letters

- openlibrary/plugins/worksearch/code.py
Fixes issue where searches for numbers (e.g. 1984) falsely interpreted as isbns
Assumes the normalized isbn (e.g. removes dashes) is of len 10 or 13
https://dev.openlibrary.org/search?q=1984
https://dev.openlibrary.org/search?q=1984
@cdrini, @tfmorris , @hornc
> fixing search for non-isbns numbers

- openlibrary/core/vendors.py
- openlibrary/macros/AffiliateLinks.html
In some cases, BWB API returns empty list `[]` as `market_price` (esp. when `isbn` is `None`). 
(a) the check needs to be fixed (to return the 1st element, not the empty list, in these cases)
(b) the Affiliate macro needs to be updates so prices are always in scope when no isbn
https://dev.openlibrary.org/books/OL9315560M/1984?debug=true
> fixing bwb price when no isbn or market_price

- openlibrary/macros/LoanStatus.html
Closes #2829 
N/A
Here's an example of such a printdisabled book for testing:
https://dev.openlibrary.org/books/OL22691653M/Software_engineering
Example of a sponsorable of books
https://dev.openlibrary.org/books/OL2719185M/Linear_and_nonlinear_circuits
@cdrini
> adds preview for printdisabled books

- Makefile
- openlibrary/templates/site/head.html
- package.json
- static/css/components/carousel.less
co-authored w/ @cdrini: updates the Makefile w/ agplv3 license information so that openlibrary.org passes [librejs](https://www.gnu.org/software/librejs/) validation for @brewsterkahle's talk. :)
Closes #3154 
When librejs is enabled in firefox, we are noting that some js libraries (e.g. slick) are not loading fonts correctly when the characters are utf8 (namely → and ←) so `important` tags are used in our less to ensure these are gracefully set correctly.
Install [librejs](https://ftp.gnu.org/gnu/librejs/librejs-7.20.1.xpi) xpi for firefox, make sure to "pass" (i.e. whitelist) the archive.org includes (which are only included as dev dependencies and may be safely ignored) and then hopefully note that there is a green check next to librejs extension icon.
@cdrini tested w/ me
@bfalling
> updating makefile, generate librejs fsf agplv3 licenses + fix utf8 css

- openlibrary/core/lending.py
- openlibrary/plugins/worksearch/code.py
Closes #2141 ; Fix: Choose a better ia id when displaying work availability instead of random.
- Solr records store an ia id in "lending_identifier" which is less likely to be print-disabled-only; prefer that when getting availability to choosing the first ia id (which is ~random).
- HOWEVER, that field does not include freely available books, so it would show a "Borrow" button even when a work is PD. Unfortunately there is no accurate way to determine if a work is PD via solr info, so using a hack for now. The only long term solution to this would likely involve a full re-index of solr, with more information stored therein.
- The other possible solution would involve making multiple requests to IA for availability data, or ~doubling the number of OCAIDs sent to IA for availability …
> Less erroneous availability for works

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question_template.md
Part of #3161 
Removes `State:Backlogged` from issue templates
> Remove `state:backlogged` label from issue templates

- openlibrary/macros/AvailabilityButton.html
- openlibrary/macros/BookPreview.html
- openlibrary/macros/BookSearchInside.html
- openlibrary/macros/LoanStatus.html
- openlibrary/macros/ReadButton.html
- openlibrary/macros/databarHistory.html
- openlibrary/macros/databarTemplate.html
- openlibrary/macros/databarView.html
- openlibrary/plugins/openlibrary/js/availability.js
- openlibrary/templates/books/edition-sort.html
- openlibrary/templates/widget.html
Closes #2795 
Normalizes how we track analytics across Open Library for cta (call-to-action) buttons. (e.g. read, borrow, etc)
Verify on dev.openlibrary.org that on the following pages use the right `CTAClick` syntax:
- search results pages
- works / editions pages
- authors pages
- list pages
@cdrini
> Standardizing CTA Button metrics

- openlibrary/plugins/openlibrary/api.py
Closes #2517
Technical
Checked if not an eligible edition should throw an error
Testing
Go to https://dev.openlibrary.org/sponsorship/eligibility/97802992042042 and check if the API throws an error gracefully
Stakeholders
@cdrini here is the updated pr as I messed up the previous branch in merging from master
> Made Eligibility API to fail gracefully

- openlibrary/solr/update_work.py
The earliest possible `pub_year` should be 9223372036854775807 BC.
https://stackoverflow.com/questions/12971631/sorting-list-by-an-attribute-that-can-be-none
1. Convert all instances of `None` to the year -9223372036854775807
2. Convert all values to `int()` because some are `str` while others are `int`
* Python2: 'a' > 1  # True
* Python3: 'a' > 1  # TypeError: '>' not supported between instances of 'str' and 'int'
Closes ~8 failing pytests on Python 3
>  pub_year = -sys.maxsize: Py3 refuses to sort None

- openlibrary/core/cache.py
- requirements_test.txt
- scripts/test-py3.sh
This PR leaves Python2 unmodified but changes Python 3 to pass pytests.
Use [`from pymemcache.test.utils import MockMemcacheClient`](https://pymemcache.readthedocs.io/en/latest/apidoc/pymemcache.test.utils.html) on Python 3 because `mockcache` only supports legacy Python.
Closes #3183
> Use pymemcache MockMemcacheClient instead of mockcache on Python 3

- static/css/components/wmd-button-bar.less
Closes #2624 
Fix for Help button not going to the external link when clicked
There is a library called wmd used with <textarea> tag to give it extra functionalities, Help button has tag which has height and width of 0 X 0 so when we click the help button then anchor tag is not getting clicked. CSS is used to make sure that anchor tag occupies 20 X 20.
Clicking on the help button will now take you to the new page link.
@mightysood
> Fixed Markdown help button does not do anything #2624

- openlibrary/macros/LoanStatus.html
- static/css/components/buttonCta.less
Closes #2972
The issue was more general and not limited to read and return buttons.(borrow, join_waitlist)  
Also, one of the form tags was not closed. The PR adds a top-margin: 5px to all .cta-buttons to add space.
```css
.cta-button-group {
....
.cta-btn {
margin:0;
...}
```
The above CSS snippets set all margins to 0 including the margin-top: 5px. I set a default margin-top: 5px for all cta-buttons, now Read and Listen are part of .cta-button-group hence their top margin will be set 0, but other buttons will have a margin of 5px at the top like Return.
In the web version, the error only appears to exist in edition pages:/works only but in smartphones, the error exists in the edition tools panel: /books/ of a borrowed book.
Before:
After:
> Read & Return Ebook buttons sep internetarchive#2972:v1

- static/css/components/readerStats.less
Closes #3219
The color of the Reading log stats modified to black.
&.reading-log-stat {
color: @black;
}
> Reading log stats modified internetarchive#3219:v1

- openlibrary/plugins/openlibrary/borrow_home.py
Closes #3194 ; Fixes borrow stats graph stuck at 0
Longer term fix for #3216
Turns out the data was no longer getting recorded in the DB! The flow here is super awkward; it looks like there's a `stats` postgres tables that stores info about loans, _and also_ a solr instance which stores this same info, indexed for efficient query. The database was updated by the event hooks in the `setup` method of `libraries.py`, which was removed in #2955 . This means that unfortunately the borrow data for 02-13 to 03-19 will be permanently missing. But we have that data in graphite, so it's ok. This fix re-instates the necessary methods from libraries.py in `borrow_home.py`.
Fix is currently live on ol-web3 and ol-web4
@cdrini
> fixing borrow stat graph regression

- openlibrary/templates/books/custom_carousel.html
Google PageSpeed and Lighthouse Audit reveal that Open Library isn't doing a great job at lazyloading images and pre-loading fonts:
https://developers.google.com/speed/pagespeed/insights/?url=openlibrary.org
Approach may only work for newer browsers, should gracefully fallback
Tested homepage, subjects page, and books page (works, editions)
@cdrini
> lazy loading carousels + preloading carousel fonts

- openlibrary/conftest.py
- requirements_common.txt
Fixes #3192  Upgrade to web.py==0.50 on both Python 2 and Python 3.  This is the last release that is planned to support legacy Python.  https://github.com/webpy/webpy/releases
Blocked by https://github.com/internetarchive/infogami/blob/master/infogami/utils/view.py#L70
Closes #
> Upgrade to web.py==0.50

- openlibrary/core/admin.py
- openlibrary/core/cache.py
- openlibrary/tests/core/test_cache.py
Temporary fix to #3194 until logs catch up again in ~1mo. Mek has a PR in progress to fix that. Hits graphite for data instead of data base if not on dev (so dev should show the "broken" graphs, but prod should show the functioning graphs).
- Caches graphite request in memory
- On dev, change `"dev" in config.feature` → `"dev" not in config.feature`, then reload homepage without memcache
@mekarpeles
> Temporary patch to fix empty borrows graph via graphite data

- openlibrary/plugins/admin/code.py
Gives librarians access to reindex solr entries
Passes `librarian` permissions through to admin plugin
As a librarian, go to https://dev.openlibrary.org/admin/solr
Tested w/ @seabelis 
@seabelis , @cdrini
> granting librarians solr admin access

- docker/Dockerfile.olbase
- docker/Dockerfile.oldev
Closes #2081. This updates the Docker dev environment from Node 8, which is end-of-life, to Node 12 LTS. 
It is based on and includes #2911 (since the build doesn't work with the old version of pip).
It also includes an `npm audit fix` for all our modules to resolve the hundreds of vulnerabilities which are flagged (but there are still a couple of critical ones, e.g. jQuery, which need manual updates)
It switches from `npm install` to `npm ci` for better reproducibility of versions.
All automated tests pass and cursory testing on a local dev build looks ok, but it should be more thoroughly tested.
@jdlrobson
> Update to Node 12

- openlibrary/solr/update_work.py
Alternative to #3075
Closes ~6 failing pytest on Python 3.
> UpdateRequest.toxml() should return str, not bytes (alt)

- openlibrary/core/models.py
- openlibrary/plugins/openlibrary/code.py
Fixes /isbn to consider both isbn10 or isbn13 (currently it only searches the exact isbn you provide it)
Find a book w/ an isbn 10 on Open Library. Try /isbn endpoing with both the isbn10 and the isbn13 version of this book. Do the same for another book with isbn13.
Tested on dev.
co-authored with @cdrini
> /isbn endpoint works w/ isbn10 or 13

- openlibrary/macros/AffiliateLinks.html
- openlibrary/macros/databarWork.html
Hotfix -- our increase of traffic is causing 13% increase in affiliate price lookups against BWB and affecting their service availability.
They've adjusted on their side. Suggesting we merge this PR, out-of-cycle deploy, and re-visit next-steps for next Tues release.
Disables price-lookup on editions page (via affiliate macro) should not affect sponsorship.
Clear cache on dev via `/etc/init.d/restart mecache` and then visit https://dev.openlibrary.org/books/OL18141225M/Snow_crash (load time should be reasonable, price should not appear, link to BWB **should**).
tested on dev
@bfalling @cdrini
> hotfix disable price lookup due to traffic increase, help bwb

- openlibrary/templates/work_search.html
Closes # TODO . Don't auto full-text search on failed search; instead show text directly to fts.
This was causing performance issues on FTS servers because of high load on OL during global lockdown.
- Tested locally:
- ✅ a search with results shows results https://dev.openlibrary.org/search?q=tacos
- ✅ a search without results shows text + link to search inside https://dev.openlibrary.org/search?q=gobbly+gook
- ✅ link to search inside takes you to/performs search inside https://dev.openlibrary.org/search/inside?q=title%3A+%22gobbly+gook%22
- ✅ searching directly for "Text" goes to search inside. https://dev.openlibrary.org/search/inside?q=gooky&mode=printdisabled&m=edit&m=edit&has_fulltext=true&subject_facet=Protected+DAISY
@mekarpeles
> Temporarily disable falling back to full-text search results

- openlibrary/macros/LoanReadForm.html
- openlibrary/templates/account/borrow.html
- static/css/components/borrowTable.less
Closes #3225
Removes the redundant newline to fix misaligned Loan Actions buttons.
Instead of using br for newline, the following is added to provide proper space between buttons.
.LoanReadForm {
margin-top: 10px;
margin-bottom: 10px;
}
> Alignment Error between the buttons internetarchive#3225:v1

- static/css/components/buttonCta.less
- static/css/less/colors.less
Closes #2610 
It includes an increase on the font size as mentioned on the issue comments.
Both the borrow button and the arrows are affected (but the arrows have lower opacity). 
Chrome insists on using #0376b8 although the correct hsl value was given on the file: hsl(202, 96%, 37%):
Audit results:
> Improve borrow button accessibility

- openlibrary/plugins/openlibrary/js/ol.js
Closes #3285. Although /search/inside.json isn't defined, it hits the regular /search/inside endpoint! So each character typed while "Text" was selected would trigger a _very_ expensive call to IA's FTS.
Nothing to note.
- ✅ Typing in search box with "Title" selected shows autocomplete
- ✅ Typing in search box with "Text" selected makes no network requests
No ui changes.
@mekarpeles @gdamdam
> Disable autocomplete requests for search inside

- openlibrary/macros/LoanStatus.html
- openlibrary/macros/databarWork.html
We're hitting a new case where Open Library pages have a non-existent ocaid
Implementation not ideal (semantically), DownloadOptions moved into LoanStatus because it needs the availability information which is fetched there. 
This title should not appear as "readable" `OL26483859M`
Tested on dev
@cdrini
> code now has correct availability for missing items

- openlibrary/templates/admin/sponsorship.html
Relies on a fragile anti-pattern of assuming the sponsored book IDs start with `isbn_` which they should (unless it's a bulk sponsorship). Either way, it should fail gracefully.
Internal only. Testable at dev.openlibrary.org/admin/sponsorship
Tested printslips w/ @cdrini 
@cdrini
> fixes printslip url and direct links to /editxml

- openlibrary/plugins/openlibrary/code.py
- openlibrary/plugins/openlibrary/stats.py
- openlibrary/plugins/openlibrary/status.py
Closes #3283
Fix/feature: Add more graphite stats for pageloads, internal-errors, and exceptions. This will let us easily drill down into specific endpoint data if we see a large number of errors, as well as perf regressions.
- The format for pageloads is:
`ol.requests.(started|completed).(GET|POST|...).(400|404|...).(logged_in|not_logged_in).[first_level_path].[page_class].(10ms|100ms|...).count`; e.g.:
- `ol.requests.started.GET.200.not_logged_in.books.class_book_edit.unknown.count`
- `ol.requests.completed.GET.500.not_logged_in.books.class_book_edit.5000ms.count`
- For errors and exceptions, the format is:
`ol.internal-errors-segmented.[first_level_path].[page_class].[error_file_in_ol].[error_name].count`; e.g.:
- `ol.internal-errors-segmented.books.book_edit.class_books_edit_html.Synta …
> Add more graphite state (specifically for errors)

- openlibrary/templates/site/head.html
fixes #3234 
Added the meta description and keywords for the home page
The keywords I have used have relatively higher search volume and are relatively less competitive.
> Add meta description and keywords on the landing page of OL

- openlibrary/solr/update_work.py
- openlibrary/tests/solr/test_update_work.py
- scripts/test-py3.sh
Closes failing pytests on Python 3
Python 2 and Python 3 do not agree on the order of elements in a set or keys in a dict.
```
% python2 -c "print(list(set('abcdefg')))"
['a', 'c', 'b', 'e', 'd', 'g', 'f']
% python3 -c "print(list(set('abcdefg')))"
['d', 'a', 'b', 'c', 'g', 'f', 'e']
% python2 -c "print(list({key: value for value, key in enumerate('abcdefg')}))"
['a', 'c', 'b', 'e', 'd', 'g', 'f']
% python3 -c "print(list({key: value for value, key in enumerate('abcdefg')}))"
['a', 'b', 'c', 'd', 'e', 'f', 'g']
```
However, our tests are currently hardcoded to the Python 2 order.  To make these tests pass on both Python 2 and Python 3, we need to sort the output ~either in the code file or~ in the test file. 
__Which should we do?__
Modify the tests, not the code.
> Use sorting to fix solr update_work

- openlibrary/plugins/upstream/utils.py
- openlibrary/templates/lists/widget.html
- openlibrary/templates/type/edition/view.html
**Why is this change necessary:** 
This change fix the severe bug XSS in page add-blog of OpenLibrary"
**How does this commit address the issue:** 
The issue was that the URL in anchor was formatted as string in ungettext which was causing the problem, so removing the ungettext causes the template broken error and disturb the blog title, so alternatively the URL is filtered to remove the bad character from the user input
**What effects does this change have:** 
This change solve the XSS vulnerability and encode the URL and title safely
_My first commit in OpenLibrary, really enjoyed to contribute and looking further for more contribution_
Closes #3080 
1.Click  Add Book
2. In Title --->  "'><script>alert(/Ultra Security/)</script>
3. Create and load the page
> Fixed XSS in work/edition title

- scripts/test-py3.sh
Mandate that all pytests in `openlibrary/tests` pass on both Python 2 and Python 3.
Closes #
> 'pytest openlibrary/tests' must pass on Python 3

- openlibrary/plugins/upstream/merge_authors.py
- openlibrary/plugins/upstream/tests/test_merge_authors.py
A subset of #3134 created to simplify the review process.
Closes pytests on Python 3
$ `python3`
```
>>> {}.keys() + {}.keys()
File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'dict_keys' and 'dict_keys'
>>> list({}) + list({}) == []
True
>>> {}.keys() == []
False
>>> list({}) == []
True
>>> {"a": 0, "b": 1}.keys() == ["a", "b"]
False
>>> list({"a": 0, "b": 1}) == ["a", "b"]
True
```
> Fix test merge authors.py

- openlibrary/plugins/openlibrary/stats.py
Hotfix: During 2020-04-07 deploy, noticed stutters in graphite graphs; seemed to go away once new stats were turned off.
- New pageview/exception stats disabled; new internal-error stats, and server restart notes still live.
@mekarpeles
> Temporarily disable new graphite stats

- openlibrary/templates/home/stats.html
Closes #3232
Redirects to the correct stats page
Before: It was getting redirected to an irrelevant page.
After: Now when "Ebooks Borrowed" is clicked, it redirects to the correct stats page.
> Redirect to the correct stats page

- openlibrary/utils/ddc.py
- openlibrary/utils/lcc.py
- openlibrary/utils/tests/test_ddc.py
- openlibrary/utils/tests/test_lcc.py
Part 1 of #3290
Adds utils for normalizing LCCs and DDCs to standard format that allows for sorting (this is essential for being able to do queries like `lcc:[PR1 TO PR10]`.
- This normalization is needed for sorting because solr does lexicographical sorting. Without normalization, `lcc:[PR1 TO PR10]` would _not_ match `PR2`, since lexicographically, `PR2` comes after `PR10` (similar to how in a dictionary, `B` comes after `Aa` and `Ab`). We resolve this by making LCCs fixed-length, so `PR10` → `PR-0010.00000000`. For fixed length strings, lexicographic sorting is equivalent to integer sorting. (Side note: Integers grow/sort right-to-left, whereas text/decimals grow/sort left-to-right. I wonder if this has something to do with the fact that we use Arabic numerals? 🤷‍♂ ).
- ✅ imported 1000 …
> Add utils for normalizing classifications

- openlibrary/macros/QueryCarousel.html
- openlibrary/plugins/openlibrary/code.py
- openlibrary/plugins/openlibrary/js/carousel/Carousel.js
- openlibrary/plugins/worksearch/code.py
- openlibrary/templates/books/custom_carousel.html
- package.json
Relates to #602 and #3180 
Enables any OpenLibrary infogami page to include a `{{QueryCarousel(query="some search")}}`
macro to generate book carousels from arbitrary search queries
The /search.json endpoint can now be used like the /subjects.json endpoint to `load_more` and lazy load infinite carousels.
It refactors the search.json endpoint so that we can turn any arbitrary OpenLibrary search query into a carousel.
Most of the code is existing, just moved out of a route, into a separate function which can be called from a template.
See the carousel on:
https://dev.openlibrary.org/Marley-Dias-1000BlackGirlBooks-Library
> Macro carousel powered by arbitrary openlibrary search query

- openlibrary/plugins/openlibrary/js/carousel/Carousel.js
- openlibrary/templates/books/custom_carousel.html
It turns out the IA carousels (pre #3180) don't have enough information to definitively tell availability (so we use a heuristic to check). When we merged #3339, code was introduced to fix availability for these new query carousels, however this regressed the homepage hack.
This heuristic (re-introduced in this branch) is necessary (until #3180 lands) so `related` and `homepage` carousels approximately show correct availability.
Hotfix merging as this followup needs to make it in prior to Tues deploy. 
Tested both old-style and new style carousels on editions page, homepage (without cache) and on https://dev.openlibrary.org/Marley-Dias-1000BlackGirlBooks-Library (new-style) carousels.
> re-patching homepage carousels missing info for availability check

- openlibrary/i18n/es/messages.po
- openlibrary/i18n/fr/messages.po
- openlibrary/i18n/messages.pot
- openlibrary/macros/LoanStatus.html
- openlibrary/templates/publishers/view.html
- openlibrary/templates/search/authors.html
- openlibrary/templates/search/subjects.html
- openlibrary/templates/subjects.html
Hotfix: Addendum to #3173 . Fixes errors in Author search and in Sponsorable editions, and publishers view
See commit messages for more details.
@dcapillae @tfmorris
> Fix some i18n bugs

- openlibrary/templates/covers/book_cover.html
Closes #2144
Fixes issue of Book covers appearing fuzzy on high-resolution displays
Technical
Added srcset attribute alongside src for templates/books/show.html &
templates/books/works-show.html
Testing
Tested on locally run docker container and chrome dev console using toggle device toolbar
Stakeholders
@jdlrobson @cdrini
> fixes low quality CoverImage render

- openlibrary/utils/__init__.py
- scripts/test-py3.sh
Closes #3347  This is a better solution as it fixes the problem, not the test.  This approach generates the same dicthash for both `{"a": 1, "b": 2}` and `{"b": 2, "a": 1}` on both Python 2 and Python 3.  It sorts the keys to circumvent Python 3's order preserving dicts.
> Deterministic dicthash() regardless of key order

- .pre-commit-config.yaml
- Makefile
- scripts/flake8-diff.sh
This PR adds a `.pre-commit-config.yaml` file which will cause `make lint-diff` to be executed each time a `git commit` is run on your local system.  If the lint-diff test fails then the commit fails.  This prevents contributors from creating commits that will fail our Travis CI tests.  More elaborate tests could be added to the pre-commit workflow but this test was chosen because it is both fast and easy to understand.
Closes #
How to use:
1. Install https://pre-commit.com with either:
* `brew install pre-commit` or
* `python3 -m pip install pre-commit`
2. Make a git commit on one of your branches.
* The first run might be slow but subsequent runs should be fast.
Yes.
> Add a pre-commit to run `make lint-diff`

- openlibrary/accounts/__init__.py
- openlibrary/core/vendors.py
- openlibrary/plugins/worksearch/code.py
Searching for an isbn used to resolve to an existing edition page (if successful). Now, searching for an isbn works exactly like the /isbn endpoint where an import will be performed if necessary.
The risk is behavior when amazon API times out (but the experience should fail gracefully)
This only enhanced current/existing behavior.
Test a search for an isbn which does and doesn't exist (isbn10, 13 for both cases).
https://dev.openlibrary.org/books/OL27941660M/If_It_Bleeds was imported by this codepath on dev -- by searching for the keyword `1982137975`.
Searching for `1982137975` a second time navigates patron to the right page, without re-importing -- as does `9781982137977`.
@hornc @cdrini
> fixes isbn searching to import and work like /isbn

- openlibrary/accounts/__init__.py
- openlibrary/accounts/model.py
- openlibrary/admin/numbers.py
- openlibrary/admin/stats.py
Removed unused imports from `openlibrary/accounts` and `openlibrary/admin`
@cclauss
> removed unused import from admin and accounts

- scripts/ipstats.py
Closes #2481 
Somewhere down the road, changes to ipstats resulted in presume circular dependency and inability to import infogami. By moving infogami import to after _init_path main function, it appears this issue has been resolved.
Tested the cron lines manually on ol-www1 with success
@cdrini
> Fixes ipstats cron

- openlibrary/templates/lists/widget.html
Closes #2943
Sorts the user reading lists by most recently modified in the add book dropdown.
1. Create 2 reading lists (at least).
2. Go to a book page (e.g. [Book Example](https://openlibrary.org/books/OL22450756M/The_Principles_of_Exercise_Therapy)
3. Click the arrow next to `Want To Read` and instead add to one of the two Reading Lists.
4. Go to a different book page (e.g. [Book Example 2](https://openlibrary.org/books/OL1175816M/Never_mind)
5. Click the arrow again, and verify that the list you added a book to is on top.
6. Add the book to another reading list than you did in step 3.
7. Navigate to a different book (e.g. [Book](https://openlibrary.org/books/OL9298653M/Ergonomics)
8. Repeat step 5 and verify that the list you most recently added a book to is now on top.
> Sorts reading lists by most recently modified

- openlibrary/macros/AffiliateLinks.html
Closes #3069 ; Feature: Add Bookshop.org link to edition "Buy" section
- Preparatory refactor to make expansion easier
- Also add Google Analytics tracking for these
- ✅ Displays links when a book is available on Bookshop.org https://dev.openlibrary.org/books/OL3307263M/
- ~ Also displays if no copy is available on Bookshop.org :/  https://dev.openlibrary.org/books/OL967995M/
@mekarpeles
> Add Bookshop.org link to editions

- docker/Dockerfile.oldev
Closes #2046 
feature
Adding `--quiet` flag to `psql` utility. What flag dies described here: https://www.postgresql.org/docs/9.5/app-psql.html.
To verify changes you can try to build `oldev` image with `docker build -f docker/Dockerfile.oldev .` and check that build output does not contain lots of 'garbage' messages as described in issue.
See step output after change below. While it still includes a bunch of results printouts of copy operations with setval function used, it is now much cleaner.
```
---> Running in 43231f953f34
* Starting PostgreSQL 9.5 database server
...done.
setval
--------
132
(1 row)
setval
--------
1
(1 row)
setval
--------
31
(1 row)
setval
--------
175
(1 row)
setval
--------
665
(1 row)
setval
--------
44
(1 row)
setval
--------
1
(1 row)
setval
--------
1
(1 …
```
> Tell psql to do it's work quetly

- openlibrary/templates/type/author/view.html
Trivial change `?mode=ebook` should be `?mode=ebooks`
Go to authors page and click ebooks only on dev:
https://dev.openlibrary.org/authors/OL6951711A/Tom_Clancy?mode=ebooks
@cdrini
> Adds missing 's', fixes authors ebooks only mode

- conf/openlibrary.yml
- conf/solr/conf/schema.xml
- openlibrary/solr/update_work.py
- openlibrary/tests/solr/test_update_work.py
Part 3 of #3290 . Updates indexing code to include LCC/DDC
| ~Based on #3302 ; that must be merged first! This is the diff you seek: https://github.com/internetarchive/openlibrary/pull/3338/commits/64d3e3ef848699636ebf03bce70d94d9d90293bf~ |
| -- |
- Adds 4 new fields to solr
- Since the new fields haven't been deployed yet, add them behind a config flag (we can't deploy those fields until we have solr-updater running with this new code, (unless we want to do 2 full reindexes (no thank you)).
- I tested by adding print statements to the code in question, and confirming that: (1) when flag set to false, the code is not run, (2) when set to true, it is run.
- Tested by running a _full_ solr reindex, and analysing result here: here: …
> Index LCC/DDC into solr

- openlibrary/core/waitinglist.py
Fix slow borrows 504ing
Closes #3401 
For books with many active loans, calls to loan.sync can be very slow / 504.
It looks like, these two functions are handled on the IA side, and don't actually
need to be called from Open Library. Disabling as a patch deploy for now; can
likely remove remove in the near future.
> Remove slow call to loan.sync

- openlibrary/plugins/worksearch/code.py
Hotfix. Increase solr timeout from 3s to 10.
- This API regularly takes longer than 3 seconds, and results in an incomprehensible error.
- The new solr looks like it might also take longer for complicated requests; perhaps because of the ~4M new records. Most average queries look to take about the same though. A strict timeout here causes some weird "pipe discontinued" errors on solr, which seem to make it even slower, so increasing the timeout to prevent that as well.
Tested queries taking longer than 3s no longer error.
@mekarpeles
> Increase solr timeout

- openlibrary/templates/books/custom_carousel.html
Hotfix. Apparently the slick font preload wasn't preloading! Got an error in the lighthouse
- Getting this error from Chrome's Lighthouse:
> Warnings: A preload <link> was found for "https://openlibrary.org/static/css/fonts/slick.woff" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
- Apparently fonts always need `crossorigin` for some reason https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#Cross-origin_fetches
- https://dev.openlibrary.org/collections/k-12 does not display the font loading warning in Lighthouse
@mekarpeles
> Fix slick font preload not working

- openlibrary/plugins/importapi/code.py
- openlibrary/plugins/openlibrary/code.py
Refactors importapi/code.py to move IA import logic outside of the route and into a class which can be called independently.
Hooks up /ia/xxx url endpoint so a book may be imported in the same way as /isbn/xxx.
First, 4 pieces of context
1. :openlibrary: has a special importapi plugin endpoint which our ImportBot uses to import books from Internet Archive every day
2. We have a very annoying artifact @bfalling, @JeffKaplan, and @alexisrossi are all too familiar with, where if you go to openlibrary.org/ia/xxx you get to a strange "fake" IA book page.
3. When a user types in /isbn/xxx, we attempt to use Amazon to fetch data + add to out catalog
4. We have about 50,000 books inlibrary which are not in Open Library (for a variety of reasons @hornc has enumerated here: …
> refactored import so /ia/xxx will now import from ia

- openlibrary/plugins/openlibrary/js/index.js
- package.json
Fix. Markdown editor JS being loaded indiscriminately + error in .wmd file.
| ✅ ~Merge https://github.com/internetarchive/wmd/pull/5  first; then will update to not point to my fork.~ |
| -- |
- It looks like the WMD editor was pulled out into `markdown-editor/index.js`, but the initial import never removed. Removed it.
- While working on #3408 , noticed some JS errors along the lines of "assignment to undefined reference WMDEditor". Adding `var WMDEditor = ...` fixed it.
- Updated the submodule
- Check markdown previews load with no JS errors on:
@jdlrobson
> Fix markdown editor JS being loaded indiscriminately + error

- openlibrary/plugins/worksearch/code.py
- openlibrary/plugins/worksearch/tests/test_worksearch.py
- openlibrary/utils/ddc.py
- openlibrary/utils/lcc.py
- openlibrary/utils/tests/test_ddc.py
- openlibrary/utils/tests/test_lcc.py
Part 2 of #3290; Feature: adds lcc: and ddc: fields when performing a search. Depends on #3302 and #3335 
- This will do nothing if the solr does not have lcc/ddc fields; so can be deployed
- Have to do normalization on prefix and range queries to be compatible with the way these are stored in solr (see #3302 for more details).
Imported a bunch of records and tested searching (see #3302 for script).
> Add lcc: and ddc: to search

- openlibrary/plugins/openlibrary/code.py
Hotfix. Apparently this is endpoint is being used by some book scanning code. This was causing errors in our last deploy as result of the /ia/xxx changes #3346 .
- Doesn't error for non-marc IA record: combatingdrugtra1094555588
- Import does work for valid IA record: https://dev.openlibrary.org/ia/youcantscaremegu0000unse ( from https://archive.org/search.php?query=publisher%3ATicktock%20AND%20%21openlibrary_work%3A%2A )
- Test imported book matches: https://dev.openlibrary.org/ia/youcantscaremegu0000unse
@mekarpeles
> Fix /ia/xxx import api throwing error instead of serving dummy wrapper page

- openlibrary/core/lending.py
Try to add more logging around https://github.com/internetarchive/openlibrary/pull/3350#issuecomment-615279522
A bare exception is hiding the fact that `compose_ia_url()` is returning an empty list for a URL which should be a `str`.  Adding logging so that we can see what input parameters are causing `compose_ia_url()` to fail.
> Log URL generation failures in lending.py

- openlibrary/plugins/openlibrary/pages/config_edition.page
Closes #3382
Adds LearnAwesome.org to the list of identifiers. A sample target page:  https://learnawesome.org/items/5c731d15-6a53-432e-82e4-a4de9fecb2d1-the-first-20-hours
> Fix 3382/feature/add-learnawesome-identifiers

- openlibrary/core/sponsorships.py
- openlibrary/templates/admin/sponsorship.html
Enables sorting of sponsored books by publicdate or status and adds collections into book data returned from archive.org
Tested /admin/sponsorships?sort=publicdate w/ @cdrini 
@cdrini
> enables sorting admin/sponsorships by ?sort=publicdate

- requirements_test.txt
- scripts/test-py3.sh
Related to lack of progress on #3364 
Run https://pypi.org/project/safety in _allow failures_ mode to look for security vulnerabilities in our Python dependencies without enabling dependabot like we do for JavaScript dependencies.  
We will need to run in allow failures mode because Python 2 and the versions of many dependency that support Python 2 are EOL and no longer receive updates even for known vulnerabilities.
```
+==============================================================================+
|                                                                              |
|                               /$$$$$$            /$$                         |
|                              /$$__  $$          | $$                         |
|           /$$$$$$$  /$$$$$$ | $$  \__//$$$$$$ …
```
> Check Python dependencies for security vulnerabilities

- openlibrary/utils/ia.py
Removes the unused import from `openlibrary/utils`
@cclauss  These are done!
Save for the end:
@cclauss
> Remove unused imports from openlibrary/utils

- openlibrary/templates/admin/sponsorship.html
Fixes the sponsorship dashboard (was breaking for a record w/ no title on archive.org)
https://openlibrary.org/books/OL7599497M/Twelve_Impossible_Things_Before_Breakfast (has title on OL, not IA).
> hotfix admin sponsorship dash, robust if IA book metadata missing title

- openlibrary/templates/books/author-autocomplete.html
Closes #3459 , Closes #3460 . Hotfix disabled "add new author" not working on works/edition pages.
Tested locally that clicking "Add author" creates an enabled JS input field.
@jdlrobson @seabelis
> Fix new author fields disabled

- openlibrary/templates/site/head.html
Checkoff's a point in #3227 
Closes: #3224 
If this does not work with analytics as highlighted by @mek we may want to use `dns-prefetch`
> Preconnecting to analytics

- openlibrary/macros/Metatags.html
- openlibrary/templates/account/books.html
- openlibrary/templates/site/head.html
- openlibrary/templates/site/neck.html
- openlibrary/templates/type/list/view.html
- openlibrary/templates/type/work/view.html
The head.html page of Open Library contained a generalized meta description that would be shown for all the pages. We would want the books, edition, authors, homepage to contain page-specific meta description so that we can portray our pages better on search engines. 
To test the pr inspect using chrome dev and check if the page contains page specific meta tag description
@mekarpeles
> Meta description made more specific to a page

- openlibrary/accounts/__init__.py
- openlibrary/accounts/model.py
- openlibrary/core/models.py
- openlibrary/plugins/upstream/account.py
Closes #2058
[feature]
1. There are two types of records for users, one is for their /people/xxx public `user`, the other is for their private `account` (e.g. encrypted password, email). Preferences and public settings, such as public_readinglog are stored on the `user` record.
2. An OpenLibraryAccount `account` record is not created for a user (nor their `user` record) until they have created + activated an InternetArchiveAccount and successfully logged in for their first time. At this point, the code we're adding will fetch the patron's **user** account and update their settings so their reading log is public by default.
Tested on dev (@mekarpeles + @tabshaikh)
> Enabling public reading log at account creation

- openlibrary/core/civicrm.py
@tabshaikh and I discovered a bug where reading log pages broke when Civi went offline. This deals with failed civi responses gracefully
> hotfix civi calls when civi is down

- openlibrary/accounts/model.py
Pulled out from #3498 . The "future" way to do borrows will be to use s3 keys in a POST request. This is a step in that direction.
- @mekarpeles  tested through commandline;
- @mekarpeles tested logging in on dev, and confirming keys were in the store db
- Tested keys _not_ in publicly available API
@mekarpeles
> saves archive.org s3 keys into user private keyval upon login

- openlibrary/macros/LoanStatus.html
Followup to #3500 
https://openlibrary.org/books/OL26440726M/On_tyranny?debug=true (hotfixed) was showing "Check Availability" on the **books** editions page. -- this happens when a book is only browsable but is checked out.
We're only checking if borrow_unavailable from availability without checking whether we have a more accurate answer from lending_st. This hotfix is patched on prod.
Add ?debug=true to the url and it will show more borrow stats to ensure it's working correctly
> only use check availability btn if no ground truth available

- openlibrary/plugins/upstream/borrow.py
Because of #3500, we are only tracking old borrow actions; this small PR adds graphite stats/analytics for browse-type borrows.
> adding analytics to track how many borrow are of type browse

- openlibrary/macros/LoanStatus.html
- openlibrary/macros/ReadButton.html
Followup to #3500
if we know a borrow is available but...
1) metadata says borrow_unavailable (then we know it's a browse which is available) or
2) loandb says it's not a borrow
Then we should present the button explicitly as only available for "1 Hour Borrow"
staged on prod
> adds 1 hour borrow cta-btn

- openlibrary/core/lending.py
- openlibrary/macros/LoanStatus.html
- openlibrary/plugins/upstream/borrow.py
Followup fix for #3500 
replaced existing return functionality with the loan service endpoint used by bookreader
confirmed on dev that this endpoint works from book + loans pages
@JeffKaplan @bfalling @cdrini
> hotfix: Enables returning of 1h or 2wk borrowable books

- openlibrary/plugins/upstream/code.py
Extracted from #3515 .
- Tested on dev.openlibrary.org while debugging a user's problem which was caused by such a redirect.
- Tested https://dev.openlibrary.org/account/loans still works
@mekarpeles
> Fix loans page displaying broken book due to redirect

- openlibrary/core/lending.py
Fix
- Turns out these operate in binding order, but public will still be able to get the correct `__name__` since the memoize method uses `functools.wrap`.
- Turns out key is mandatory, not optional. But don't worry it appends the args to the specified `key`
- Tested https://dev.openlibrary.org/books/OL23260146M/Matilda?debug=true takes <1s as opposed to https://openlibrary.org/books/OL23260146M/Matilda?debug=true , which takes ~20s
- Checked https://dev.openlibrary.org/books/OL26440726M/On_tyranny?debug=true shows as checked out
@mekarpeles
> Make get_cached_groundtruth_availability actually cache

- openlibrary/core/lending.py
- openlibrary/macros/LoanStatus.html
- openlibrary/plugins/openlibrary/api.py
- openlibrary/plugins/openlibrary/home.py
- openlibrary/templates/books/custom_carousel.html
- static/css/components/buttonBtn.less
- static/css/components/buttonCta.less
- Refactor: Make carousels use LoanStatus (DRY)
- Fix: Sponsorship button not working
- Note there is a copy of some of this in the JS which has _not_ been consolidated
- ✅ homepage (with clean memcache) displays correct availabilities
- ✅ https://dev.openlibrary.org/collections/tv-people-books (Carousels with potentially non in library books)
- ✅ https://dev.openlibrary.org/books/OL25101686M (Sponsorship button fixed)
- ✅* https://dev.openlibrary.org/collections/read-the-movie (Showing "Not in Library" incorrectly)
- ✅* https://dev.openlibrary.org/search?q=The+COlorado+Kid+king&mode=everything (Showing "Not in library" incorrectly)
- ✅** Lists https://dev.openlibrary.org/people/mrdynamite69/lists/OL149582L/Must_Reads
- ✅** Reading log
\* Problem caused by something else; was also …
> Make carousels use LoanStatus.html

- openlibrary/macros/LoanStatus.html
- openlibrary/plugins/openlibrary/home.py
- openlibrary/templates/books/custom_carousel.html
Fixes an issue w/ #3518 where for plugins/openlibrary/home.py `format_book_data` did not define work_url due to missing `work`
tested on dev
labeling as P1 because every IA book carousel item is showing work_url errors on the book pages; staging this change on production
> hotfixing carousels where work_key undefined

- openlibrary/plugins/upstream/account.py
Feature. Let's us provide a user-customized link to reading log stats.
- Confirmed localhost:8080/account/books/fooo -> localhost:8080/people/openlibrary/books/foo
@mekarpeles
> Extend /account/books redirect to include subpaths

- openlibrary/macros/LoanStatus.html
trivial fix, we were using `user` variable (which didn't seem to have a key)
@cdrini
> ctx.user has key (not user)

- openlibrary/core/lending.py
- openlibrary/core/models.py
- openlibrary/core/waitinglist.py
- openlibrary/macros/BookPreview.html
- openlibrary/macros/FulltextResults.html
- openlibrary/macros/LoanStatus.html
- openlibrary/macros/SearchResultsWork.html
- openlibrary/macros/daisy.html
- openlibrary/macros/databarWork.html
- openlibrary/plugins/openlibrary/js/editions-table/index.js
- openlibrary/plugins/openlibrary/js/ol.js
- openlibrary/plugins/upstream/borrow.py
- openlibrary/plugins/upstream/utils.py
- openlibrary/templates/books/custom_carousel.html
- openlibrary/templates/books/edition-sort.html
- openlibrary/templates/type/edition/view.html
- openlibrary/templates/type/work/editions_datatable.html
- openlibrary/templates/work_search.html
Refactor. Make the template dumber (i.e. take simpler parameters, make fewer deductions).
- Replace `editions_page` parameter with a few booleans for specifically what they enabled/disabled
- Removed `user` parameter entirely; it wasn't really used? Testing needed.
- ✅ Tested enabling `secondary_action` on search page, all preview buttons work correctly
No UI changes
@mekarpeles
> Refactor LoanStatus.html

- openlibrary/macros/QueryCarousel.html
Feature: `QueryCarousel` macro now support an extra option to allow display of both fulltext and not in library books.
Tested locally by creating a page with:
```
{{QueryCarousel(title="foo", query="key:(/works/OL73243W OR /works/OL54120W)", has_fulltext_only=False)}}
```
On dev: https://dev.openlibrary.org/collections/tv-people-books
@seabelis
> Allow query carousels to optionally display non in library books

- openlibrary/utils/solr.py
Hotfix needed while testing #3489
- Same reason we increased for worksearch; the way the timeout is handled on the python side looks like it causes performance issues for solr
- Was seeing in jump in errors from subjects pages when connected to new solr (which is a little slower). This caused the errors to go away.
- Subjects pages still load, and don't throw `NoneType has no attribute v2`
> Increase solr timeout for subject pages

- openlibrary/solr/update_work.py
Hotfix: Unbreak solr-updater crashing trying to encode '\'
Note this was _not_ affecting ol-home's solrupdater (for some reason). Only the ol-solr0 dev solrupdater
- We should use requests (automatic encoding!) but didn't want to do such a large refactor right now
✅ Ran solrupdater on dev and it stopped erroring! :)
> Fix solr-updater crashing trying to encode "edition_key:ia\:foo"

- openlibrary/plugins/openlibrary/js/ol.js
- openlibrary/templates/lists/widget.html
- static/css/components/dropper.less
- static/css/legacy-tools.less
- tests/unit/js/html-test-data.js
Closes #
Tested locally:
@mekarpeles
> Make lists widget standalone

- openlibrary/plugins/upstream/code.py
Fix. This was causing some issues in the local dev env (for some reason).
> Fix AttributeError when trying to fetch doc with broken key

- openlibrary/core/lending.py
- openlibrary/plugins/upstream/tests/test_utils.py
- openlibrary/plugins/upstream/utils.py
- openlibrary/plugins/worksearch/code.py
- openlibrary/templates/home/index.html
- Also fixes url encoding bug when trying to search inside with non-ascii characters
Closes #3467, Closes #3491
- Uses suggested algorithm from https://github.com/internetarchive/openlibrary/pull/3117/files#r390016993 (and its tests)
@hornc
> Fix IA availability requests having un-urlencoded params

- openlibrary/i18n/de/messages.po
On the German front page, there are two buttons named Anmelden. One for login, the other for registration. I changed the one to Registireren (register) which would be the better translation and is also used anywhere else.
Closes #
> Anmelden (Login) / Registrieren (Signup)

- openlibrary/plugins/upstream/models.py
- openlibrary/plugins/worksearch/code.py
- openlibrary/templates/type/author/view.html
Supplants #3534 and Closes #3446
Extends the work by @nsachin08 to add a search box on the authors page which allows patrons to filter an authors works by solr query.
The original PR searched against the /search page (instead of the /authors page)
The author-page model `author.works_by_author` has been modified to accept a query (which can be used to filter search results further than author)
@nsachin08 @tabshaikh @cdrini
> Add search bar

- openlibrary/macros/SearchResultsWork.html
- openlibrary/macros/SubjectTags.html
- static/css/components/work.less
Followup to #3553 which closed #684   
Fixes i18n (% and variable)
Removes `text-align: justify`, other than the main book page description
N/a
tested on dev
@cdrini
> i18n and style cleanup

- openlibrary/macros/EditionNavBar.html
`ungettext` string formatting breaking with `%d` on prod.
https://openlibrary.org/books/OL13350845M/The_Best_American_Short_Stories_1958?v=1&debug=true
tested on dev
https://dev.openlibrary.org/books/OL13350845M/The_Best_American_Short_Stories_1958?v=1&debug=true
@tabshaikh @seabelis
> Fixing edition count ungettext formatter %d -> %s

- openlibrary/macros/LoanStatus.html
- openlibrary/macros/SearchResultsWork.html
- openlibrary/templates/work_search.html
Hotfix search rendering failing on https://openlibrary.org/search?q=windcatcher&mode=everything due to invalid OCAID on https://openlibrary.org/books/OL25374638M/The_Wind-Catcher (ocaid since fixed).
@mekarpeles
> Fix search rendering failing when availability=None

- openlibrary/plugins/openlibrary/js/SearchBar.js
- openlibrary/plugins/worksearch/code.py
~Based on #2285~. Fix: Only fetch the solr fields needed to reduce response size and improve speed.
@mekarpeles
> Search autocomplete should only fetch needed info

- openlibrary/plugins/openlibrary/api.py
- openlibrary/plugins/openlibrary/borrow_home.py
- openlibrary/plugins/upstream/code.py
Closes #
The flake8 linter will raise F401 errors for `module imported but unused` but sometimes modules like `render_template` are imported for their runtime side effects.  This PR marks those imports with the linter directive `noqa: F401` to silence the linter and help future readers of the code.
> Importing render_template is used for its side effects

- .travis.yml
> Travis CI: Test on the current infogami master

- openlibrary/core/models.py
When passing ISBN 10 to the /isbn/ url even if we had the book in our collection we would do a amazon_fetch due to incorrect conversions of ISBN's
hotfix
Go to /isbn/ and try adding a print statement here https://github.com/internetarchive/openlibrary/blob/4f126e6a309bc7a9689d80b23264c2962bd6109a/openlibrary/core/models.py#L442 and the print statement should not show up for a book we have 
> Hotfix Amazon isbn lookup

- openlibrary/catalog/utils/query.py
- openlibrary/core/ia.py
- openlibrary/core/middleware.py
- openlibrary/plugins/upstream/code.py
- openlibrary/plugins/upstream/utils.py
- openlibrary/plugins/worksearch/subjects.py
- openlibrary/solr/solrwriter.py
- scripts/new-solr-updater.py
Closes #
Fixes to boot the server on Docker and display the home page w/ no Python 3 exceptions.
1. Fix an absolute import for Python 3
2. Convert a string literal to a bytes literal for Python 3
```
File "/openlibrary/openlibrary/solr/solrwriter.py", line 3, in <module>
import httplib
File "/openlibrary/openlibrary/plugins/worksearch/subjects.py", line 222, in get_subject
from search import work_search
ModuleNotFoundError: No module named 'search'
File "/openlibrary/openlibrary/plugins/upstream/code.py", line 70, in static_url
digest = hashlib.md5(open(fullpath).read()).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
File "/openlibrary/openlibrary/plugins/upstream/utils.py", line 716, in get_donation_include
html += opener.open(url_banner_source + param, …
```
> Fix absolute import and bytes for Python 3

- docker/Dockerfile.olbase
Hotfix. Because docker caches the various layers, it's possible for a copy of pyenv to have been installed that didn't include definitions for python 3.8.5. This ensure that pyenv is up-to-date before trying to install python.
Did a build and insured the `pyenv install 3.8.5` step worked
@cclauss @aasifkhan7
> Update pyenv before installs

- openlibrary/plugins/openlibrary/js/SearchBar.js
- openlibrary/plugins/worksearch/code.py
Autocomplete was still very slow; turns out it facets by default! -\_-. Disabled that.
Used underscores for the `_facet` and `_spellcheck_count` since we might want to make this behave differently in the future.
On dev; autocomplete works, and the requests made to solr (listening on logs) are _no longer_ including facets. (And are about ~15x faster :D 
@mekarpeles
> Don't need facets during autocomplete

- docker-compose.yml
- docker/ol-docker-start.sh
Now, you can specify `INFOGAMI=local docker-compose up -d` and modify `docker-compose.yml` to set the infogami volume mount, and then you can make changes to host infogami and see it reflected in real time! You can also check out whatever fork/branch you want in vendor/infogami, and it will now be correct.
- It's annoying that you need to modify the docker-compose.yml, but good enough for now (I couldn't think of a good quick alternative).
Checked out infogami master on my host, then used INFOGAMI=local + enable the volume mount. Got a bunch of errors 🎉 
@cclauss
> Make testing infogami changes easier

- Makefile
Useful for running just the python tests when testing infogami.
Only Travis
@cclauss
> Separate make test to test-py and test-js

- openlibrary/macros/CoverImage.html
- openlibrary/templates/covers/book_cover.html
- static/css/components/work.less
Updates #3561 - trapezoid-shaped cover looks distorted
fix
- Animation initial perspective changed
- Animation disabled for `Add Cover Image` button
> Trapezoid-shaped cover removed

- Makefile
- package.json
As discussed on Slack, if the Python tests fail then the JavaScript tests are never run.  The JS tests are faster and more stable, so this PR proposes to run them first, not last.
Also Adding separate tests for css and js
Closes #
> make test: test JavaScript before Python and seperate tests for css and js

- .travis.yml
[__Safety__](https://pypi.org/project/safety) is already run Travis CI on Python 3 in `scripts/test-py3.sh` which [currently only finds pyenv](https://travis-ci.org/github/internetarchive/openlibrary/jobs/708252529#L3748)
This PR adds a safety run Travis CI on Py2 which has older dependencies.  It [currently adds Pillow](https://travis-ci.org/github/internetarchive/openlibrary/jobs/710504108#L931).
> Discover insecure dependencies on Python 2

- openlibrary/coverstore/db.py
- openlibrary/coverstore/oldb.py
Use absolute imports in coverstore for Python 3.
This enables advanced search on Python 3 like http://localhost:8080/search?q=twain&debug=true
> Absolute imports for config in coverstore

- openlibrary/core/cache.py
- openlibrary/plugins/openlibrary/support.py
- openlibrary/templates/site/footer.html
- openlibrary/templates/site/head.html
- openlibrary/templates/support.html
Getting report of spam through the /contact endpoint; trying to limit it while still making it easy for people to file issues
- IP is stored in memcache md5 hashed for 15min
- Admins/librarians/users with accounts > 30 days should never see the recaptcha and always be allowed to send emails.
- Tested locally the g-recaptcha is added after second POST
- Test on dev
@mekarpeles @JeffKaplan
> Reduce /contact spam

- openlibrary/plugins/openlibrary/code.py
- requirements_common.txt
- requirements_test.txt
This PR:
* upgrades `flake8` and `six` on both Python 2 and Python 3.
* upgrades [web.py](https://github.com/webpy/webpy/releases/tag/0.60) and other Python dependencies on Python 3 only.
> Upgrade select Python dependencies

- .gitmodules
As discussed at http://www.nils-haldenwang.de/frameworks-and-tools/git/how-to-ignore-changes-in-git-submodules
Closes #
> .gitmodules: [submodule "vendor/infogami"] ignore = dirty

- conf/openlibrary.yml
Docker-based processes seem to work smoothly with `localhost` but not so much with `127.0.0.1`.
Closes #
> openlibrary.yml: Switch from 127.0.0.1 --> localhost

- openlibrary/templates/work_search.html
Replaces #3637 which got into a bad git state.
Closes #
> Use list(dict) instead of dict.keys() again

- Makefile
- docker/Dockerfile.olbase
- docker/hooks/build
- docker/hooks/post_checkout
Closes #3615
@cdrini Seems like DockerHub is itself able to pull the submodules before the any of the steps in Dockerfile are run (effectively doing git pulling of submodules before the docker build)
Hence another solution for this issue, in addition to https://github.com/internetarchive/openlibrary/pull/3628 might be to add a check - for the sake of checking if DockerHub has already recursively cloned the submodules, and run git submodule commands in `git` rule of `Makefile` only when `vendor/infogami` is empty implying that submodule hasn't yet been cloned (we could have chosen any of the 3 submodules for checking if they're empty, the choice of `vendor/infogami` is entirely random).
This seems a better fix to the DockerHub publishing issue rather than the related PR: …
> DockerHub fix #2

- openlibrary/plugins/upstream/models.py
Closes #
* python2 -m pytest --doctest-modules openlibrary/plugins/upstream/models.py
* python3 -m pytest --doctest-modules openlibrary/plugins/upstream/models.py
> Fix doctests of UnitParser for Python 2 and 3

- openlibrary/plugins/admin/code.py
- openlibrary/templates/admin/attach_debugger.html
Fixes #3680 which got in a bad git state.  My mistake was that I was doing `git commit -am"This is my commit message"` and the `-a` was picking up changes to `vendor/infogami`.  `-a` means all changes which is a good default but not what we want here.
When testing a version of Open Library, it is helpful to know which version of Python the OL web server is running on so this PR adds that information to the title of `http://localhost:8080/admin/attach_debugger`.
This page is only accessible by administrators so perhaps this information should be stored on a different page.
> Add Python version to Attact Debugger webpage again

- openlibrary/templates/history/sources.html
Closes #
Minor UI tweak to display 'Library of Congress' rather than 'marc_loc_2016' for the source of the most recent publicly available LOC MARC records.
https://archive.org/details/marc_loc_2016
> Add 2016 LOC MARC dump description to sources

- openlibrary/core/cache.py
Closes #3663 -- That PR got into a bad git state because of `/vendor/infogami` so this PR replaces it.
Fix.  The mockcache module that Python 2 uses has not been updated for Python 3 so substitute `pymemcache.test.utils.MockMemcacheClient`.
https://pymemcache.readthedocs.io/en/latest/apidoc/pymemcache.test.utils.html
> Fix mockcache for Python 3

- openlibrary/tests/core/test_lists_model.py
Put tests in place that pass on Python 2 but we expect to fail on Python 3.  Once these tests are in place we can fix an attempt to rewrite a property which is only allowed in old-style classes which no longer exist in Python 3.
> Add openlibrary/tests/core/test_lists_model.py

- .gitmodules
- openlibrary/core/lending.py
- openlibrary/plugins/upstream/acs4.py
- openlibrary/plugins/upstream/borrow.py
Closes #3055 
Closes #3119 assuming the correct answer is 'No, OL does not have a real dependency on acs4'
* Allows local dev linting to pass by avoiding the external vendor acs4.py code from outside this repo
* Removes a symlink (symlinks have caused problems on different OSs with Docker in the past)
* Removes a seemingly unused dependency from /vendors
A call was made to a single method 
https://github.com/internetarchive/acs4_py/blob/66780231ed8b32214d880b900ff275bb8379fbee/acs4.py#L561-L580
and the result was not used anywhere.
> Remove acs4 dependency

- openlibrary/plugins/upstream/models.py
Fixes http://localhost:8080/works/OL61982W/Odyssey?edition=odysseybookiv00home?debug=true on Python 3
```
2020-08-23 17:14:07 [openlibrary] [ERROR] Could not load donation banner
File "/openlibrary/infogami/utils/template.py", line 144, in saferender
result = t(*a, **kw)
File "/home/openlibrary/.pyenv/versions/3.8.5/lib/python3.8/site-packages/web/template.py", line 969, in __call__
return BaseTemplate.__call__(self, *a, **kw)
File "/home/openlibrary/.pyenv/versions/3.8.5/lib/python3.8/site-packages/web/template.py", line 880, in __call__
return self.t(*a, **kw)
File "/openlibrary/openlibrary/templates/type/work/view.html", line 18, in __template__
File "/openlibrary/openlibrary/plugins/upstream/models.py", line 681, in get_sorted_editions …
```
> Python3: Sort Publish date unknown

- openlibrary/plugins/openlibrary/code.py
Closes #3740
Logs should no longer fill up w/ theadeddict errors
@tabshaikh @cdrini
> Fixing cache of web.ctx for related carousels

- openlibrary/templates/lib/nav_head.html
Little feature I've been meaning to add; making reading stats easier to find by putting a link in the "My books" menu.
> Add reading stats link to "My books" menu

- conf/openlibrary.yml
- conf/solr/haproxy.cfg
- conf/solr/start.sh
- docker-compose.yml
- docker/Dockerfile.olsolr
- scripts/solr_builder/Jenkinsfile
- scripts/solr_builder/README.md
Closes #3435 ; Fix
- Copied haproxy.cfg from prod's ol-solr2
On local dev:
1. Comment out the memory mods in solr/start.sh (ain't got that much RAM!)
2. `docker-compose build solr`
3. `ENV=prod docker-compose up --no-deps -d solr`
4. `docker-compose down`
5. `docker-compose up --no-deps -d solr`
6. `docker-compose down; docker-compose up -d`
On on ol-solr0:
1. ~`docker-compose build solr`~ `sudo docker build --network=host -t olsolr:latest -f docker/Dockerfile.olsolr .`
2. `ENV=prod docker-compose up --no-deps -d solr`
@mekarpeles
> Add load balancing to new solr to fix new solr getting overwhelmed by prod traffic

- conf/coverstore.yml
- conf/infobase.yml
- conf/openlibrary.yml
- docker-compose.infogami-local.yml
- docker-compose.yml
- docker/Dockerfile.oldev
- docker/ol-covers-start.sh
- docker/ol-db-init.sh
- docker/ol-docker-start.sh
- openlibrary/coverstore/code.py
Closes #1068
Closes #2115
To test:
1. Run `docker-compose build`
2. Run `docker-compose up -d`
Tests:
> Split coverstore and postgres into separate docker services

- openlibrary/plugins/ol_infobase.py
- openlibrary/plugins/upstream/addbook.py
Error when editing this edition on Docker on Python 3 only:
`http://localhost:8080/books/OL24173003M/Travels_into_several_remote_nations_of_the_world/edit?debug=true`
```
web_1        | Traceback (most recent call last):
web_1        |   File "/home/openlibrary/.pyenv/versions/3.8.5/lib/python3.8/site-packages/web/application.py", line 280, in process
web_1        |     return self.handle()
web_1        |   File "/home/openlibrary/.pyenv/versions/3.8.5/lib/python3.8/site-packages/web/application.py", line 271, in handle
web_1        |     return self._delegate(fn, self.fvars, args)
web_1        |   File "/home/openlibrary/.pyenv/versions/3.8.5/lib/python3.8/site-packages/web/application.py", line 514, in _delegate
web_1        |     return handle_class(cls)
web_1        |   File …
```
> StringIO wants str, not bytes

- .travis.yml
A subset of #3743 which should be easier to review and merge.  This adds doctests and a job in __allow_failures__ mode for Python 3.9 release candidate 1 to ensure that our codebase is compatible with 3.9 which is scheduled to GA in one month.
Unlike #3743, this PR does not remove the run `Python 3.8 make lint and selected pytests` as discussed https://github.com/internetarchive/openlibrary/pull/3743/files#r478746380
> Travis CI: Add Python doctests and Python 3.9 release candidate again

- openlibrary/catalog/add_book/__init__.py
Closes #2916
While importing 2016 LOC data dumps I noticed that many of the records are being matched as already existing, but some don't have the LCCN in the existing record. This PR fixes that, and also adds the related LC classification (#2916 )
Tested in local docker dev env -- 
1) imported a record  from `marc_loc_2016` item (record was `created` with all fields as expected)
2) deleted the relevant fields `lccn`, `lc_calssifications`
3) reimported the same record 
Expected and observed: edition record was `modified` and the `lccn` and `lc_calssifications` were populated. Without this change the edition would have simply been `matched` and the two fields would not have been populated.
@cdrini
> Add LCCN and LC classification on reimport from MARC

- .travis.yml
- scripts/flake8-diff.sh
Improved automated testing
* Run 450+ Python doctests on all Travis CI runs
* Run tests on Python 3.9 release candidate 1 in `allow_failures` mode.
* Drop an obsolete Python 3.8 run that is surpassed by normal test runs.
> Travis CI: make lint-diff mandatory

- openlibrary/solr/update_work.py
- openlibrary/tests/solr/test_update_work.py
Closes #2852
related to #3694 
@cclauss Refactor only [`update_work.py`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/solr/update_work.py) and [`test_update_work.py`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/tests/solr/test_update_work.py)
> refactor update_work and test_update_work to use requests

- static/css/components/header-bar.less
Closes [#3796 ](https://github.com/internetarchive/openlibrary/issues/3796)
Corrects issue where work menu overlaps search results if several results are displayed.
Increased the z-index of the search bar component.  The z-index of the work menu and the search bar component were equal before this change.
> Increase search bar component z-index

- openlibrary/plugins/upstream/addbook.py
Closes #3806 with least resistance. Will likely break on py3. Reverts the part of #3752 causing the editing error.
No clue why it broke; no clue why it's fixed. Just reverting to unbreak editing.
Confirmed editing works on dev.openlibrary.org
@cclauss
> Revert changes from #3752 causing editing to break on prod

- openlibrary/i18n/es/messages.po
- openlibrary/i18n/fr/messages.po
- openlibrary/i18n/messages.pot
- openlibrary/templates/type/list/view.html
Closes [#3810](https://github.com/internetarchive/openlibrary/issues/3810) 
This fixes typo found in dialog that appears when a user tries to delete the last book in a list.
Existing i18n mappings have been updated as well.
1. Create and navigate to a list the contains a single book.
2. Select "Remove this item?"
3. Repeat steps one and two for French and Spanish language preferences.
> Correct dialog box typo

- openlibrary/templates/type/list/view.html
Closes #3565 
This corrects issue where entity code is present in confirm dialog button.
HTML encoding filter is now turned off for the strings that contain escaped apostrophes.
1. Log into the Open Library instance where you will be testing.
2. Create a list that contains two books.
3. Navigate to the list that you created.
4. Click on "Remove this item?" and confirm that the text is correct.
5. Remove the item by clicking "Yes, I'm sure"
6. Repeat step 4 for the remaining item.
Removing one item from a list with multiple items:
Removing the last item from a list:
> Remove HTML escaping

- openlibrary/core/lending.py
We were getting hundreds of these logged as separate events. Sentry uses the stack trace to determine whether to events are the same, but `logging.error` (unlike `logging.exception`) does not include the stack trace, so it only has the message to work off of. Sentry does, however, add any info in `extra` to its UI, so that's all still accessible.
Patch deployed on ol-web4, to stop the influx.
@mekarpeles @cclauss
> Make some lending logs less verbose to better group in Sentry

- openlibrary/plugins/openlibrary/js/SearchUtils.js
Closes #3822
Stores default search mode as 'everything' in local storage.
1. Navigate to Open Library.
2. In your browser's developer's tools, locate local storage and delete the data the is stored there.
3. Refresh the page.
4. Verify that `mode` is set to `everything`.
> Change default search facet to 'everything'

- openlibrary/plugins/openlibrary/js/SearchUtils.js
Closes #3665 
Manage covers was failing because `SearchUtils.addModeInputsToForm()` is being called for the add and manage covers form.  This function fails to set the URL for these forms, causing functionality to break.
All code within `addModeInputsToForm()` that relies on a defined URL is now nested inside of an `if` statement that checks if the URL exists.
1. Log into Open Library.
2. Navigate to a work.
3. Click on "Manage Covers" and attempt to add and remove a cover.
4. Test that search functionality is working properly.
> Correct undefined URL error

- CONTRIBUTING.md
Closes #3835 
Fixes wrong video link in the Quick Tour section of the CONTRIBUTING.md file.
changed the link to https://archive.org/embed/openlibrary-tour-2020/openlibrary.ogv
N.A
N.A
N.A
> Fixed wrong video link in the Quick Tour section.

- .travis.yml
We don't really need travis to run on pushes to non-master branches, since we only care about branches which have PRs open. This means fewer things in Travis, shorter queues, faster Travis runs.
> Make Travis only run on master/PRs

- openlibrary/plugins/openlibrary/status.py
Closes #
Add Python version to http://openlibrary.org/status.  Similar to #3681 but does not require administrative privileges to see the Python version.
Also, fix the issue where [`Software version is b'3580fcf'`](http://staging.openlibrary.org/status) instead of `3580fcf` on Python 3.
% ` python3 -c "import sys ; print(sys.version.split()[0])" ` # --> 3.8.5
> Add Python version to Server status page

- scripts/make-integration-branch-sample.txt
- scripts/make-integration-branch.sh
Now that we also have staging.openlibrary.org, it needs the same scripts as dev.openlibrary.org . Committing to repo.
- Note the command has changed slightly; it now also needs the branch name as a second parameter
@cclauss
> Commit dev integration branch scripts

- tests/unit/js/test.SearchBar.js
Closes #3870 
Triggering autocomplete in search bar unit tests is now done by invoking the focus handler.  This will ensure that our tests will continue to work properly when using newer versions of Jest.
@cdrini
> Refactor autocomplete unit tests

- openlibrary/i18n/README.md
- openlibrary/i18n/__init__.py
- scripts/i18n-messages
Update the i18n README to be more comprehensive.
- Clearer headings for what a translator might want to do
- Added `i18n-messages update` instructions
@bitnapper @dcapillae @tfmorris @hornc
> Update i18n README and fix/update some issues i18n code

- openlibrary/templates/stats/readinglog.html
Closes #988 
A couple of notes:
- After reading [i18n's README](https://github.com/internetarchive/openlibrary/tree/master/openlibrary/i18n) and [Frontend Guide - internationalization for programmers](https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide#internationalization-i18n---for-programmers), and after checking other internationalization commits, I still wasn't sure how to generate `messages.pot` or if it was my job or a maintainer's. After getting a "permission denied" when trying `docker-compose run web ./scripts/i18n-messages extract` I decided to give the PR a try and update with your feedback, if any.
- Also, even if under "Librarian resources", is https://github.com/internetarchive/openlibrary/wiki/Developer's-Guide-to-Data-Importing the way to go for programmers …
> Internationalize /templates/stats/readinglog.html

- openlibrary/templates/lib/history.html
Closes #3883, #3824 
Will resolve TypeError to render history section of `openlibrary/type/{page}`
`h` variable was not receiving the value from the `get_history_preview` function, as suggested by @mekarpeles [here](https://github.com/internetarchive/openlibrary/issues/3883#issuecomment-708747380). I have made the necessary changes mentioned in the comment linked above.
The local tests were passed successfully.
To reproduce this PR changes:
1. Go to `openlibrary/templates/lib/history.html` and replace the first 7 lines of code with the below code:
```python
$def with (page)
$ h = None
$if "superfast" in ctx.features and "history_v2" not in ctx.features:
$ h = page.get_history_preview()
$if not h:
$ h = get_history(page)
```
2. Now navigate to `0.0.0.0:8080/type/work`, the history section …
> Resolve TypeError to render History section of the Page.

- CONTRIBUTING.md
bad URL in [CONTRIBUTING.md](https://github.com/internetarchive/openlibrary/blob/master/CONTRIBUTING.md) previously loaded a blank screen.  changed the URL. problem resolved.
> fixed URL for the "Installing Open Library" video
