- static/css/components/category-item.less
Closes #3923 
Added padding-bottom
@cdrini @mekarpeles
> Added padding in category-count

- openlibrary/plugins/upstream/addbook.py
Closes #3752 #3806 #3807
Allow both Python 2 and Python 3 to produce identical results from `read_subject()`.
This leaves the Python 2 encoding/decoding in place but allows Python 3 to deliver the same results.
Added doctests that pass on both Python 2 and Python 3.
> addbook.py: Fix encoding/decoding for StringIO

- openlibrary/templates/merge/authors.html
- static/css/components/merge-form.less
- static/css/less/colors.less
Closes #668 
The following changes to the author merge UI in order to help librarians avoid merging incorrect records:
1. When a new primary record is selected, it is moved to the top of the list.
2. Previous primary record's merge checkbox is unchecked on primary record change.
3. All non-primary records that selected for merging now have a light yellow background color.
1. Navigate to the merge author page, ensuring that two or more author IDs are passed as keys.
2. Select a new primary record and ensure that the following occurs:
- The new primary is moved to the top of the list of records.
- The old primary record's checkbox is unchecked.
3. Check and uncheck the checkboxes of non-primary records, and ensure that the background color changes accordingly.
4. Merge records to ensure …
> Improve merge author UI

- openlibrary/templates/books/custom_carousel.html
- openlibrary/templates/home/categories.html
- openlibrary/templates/lib/nav_head.html
- openlibrary/templates/site/alert.html
Closes #3877 
- Removed data-lazy, did not find any use for that specific attribute anywhere else in the code, validator wants src attribute on every image. 
- `role="presentation"` is not recommended with images having a non empty alt tag. Source: [ARIA practices](https://www.w3.org/TR/2017/WD-wai-aria-practices-1.1-20170628/examples/presentation/PresentationRoleExamples.html), since alt is a more important attribute, decided to let it stay.
- `text-underline` has no style associated with it.
- The only error remaining is the `Stray start tag script` which the validator does not like is because the scripts in openlibrary/templates/site/footer.html are outside the `<body>` tag. Since all the scripts are related to analytics and therefore belong before the HTML page ends, we can ignore …
> Validation errors on homepage resolved

- openlibrary/templates/lists/lists.html
Closes #3813
I18n strings are now used for the text of the delete list dialog buttons.
This change overrides the buttons set in the `confirmDialog` function found in `openlibrary/plugins/openlibrary/js/dialog.js`.  `confirmDialog` takes two arguments: A callback function and dialog box options.
The callback is used to set the default behavior of the confirmation button.  I couldn't think of a clean way to override the buttons and reference the callback, so I passed an empty function as the callback and put the original logic in the `buttons` option.
1. Log into Open Library.
2. Create a list that contains at least one book.
3. Ensure that your language preference is set to Spanish or French (These are the only two translations available for these buttons as of writing).
4. Navigate to …
> Use i18n strings for list deletion dialog buttons

- openlibrary/plugins/openlibrary/code.py
Addresses half of #3818 -- removes caching. 3818 still requires fixing the javascript side of things.
Hit the partial endpoint
https://dev.openlibrary.org/partials?workid=OL16029764W&_component=RelatedWorkCarousel
@cdrini @tabshaikh
> don't cache relatedworkcarousel partial; filling memcache

- static/css/components/subNav.less
Closes #3046 
1. As suggested by @jdlrobson and agreed to the suggestions by @mekarpeles [here](https://github.com/internetarchive/openlibrary/pull/3207#pullrequestreview-383334434), I have made changes to the necessary file (static/css/components/subnav.less).
2. I added a margin-top of 10px on the sub-nav component of the above-mentioned file. If this was not what was expected to be changed, then, please do tell me, I will be happy to fix it.
3. Please do mention if I have done some mistakes, so that I can improve and not make those mistakes again. 
I have ran the `docker-compose exec web bash make test`, all tests were passed.
Image after the changes:
There were no assignees mentioned for this issue.
> Add margin to sub-nav to improve UI for Recent Changes Page

- docker/README.md
Windows users will now be significantly less likely to need Docker Toolbox; this was required since Windows Home didn't support Hyper-V (required for Docker Desktop). But Docker Desktop now can use WSL2 instead of Hyper-V to run.
These instructions were also confusing folks, and causing them to accidentally run docker using a VM
@jamesachamp
> Remove Docker Toolbox instructions

- .pre-commit-config.yaml
- docker-compose.yml
- docker/Dockerfile.oldev
- docker/README.md
- docker/docker-entrypoint.sh
- docker/ol-home-start.sh
Fix `docker-compose run --rm home make test` not working. Also remove `db` as a hard dependency of `home` service.
Previously, a sh subshell was opened when running something like `docker-compose run --rm home ./foo.sh`. This subshell would not have acces to the environment variables that make pyenv work, since it does not run .bashrc . We now specify a custom ENTRYPOINT that inits the right pyenv setup.
- Note: very slow, but as slow as `bash`-ing and and running `make test`
> Fix: docker testing cmd in README not working

- openlibrary/config.py
- openlibrary/plugins/admin/tests/conftest.py
Closes #3958
Removes YAML load warnings raised by pytest.
@cclauss
> Fix YAML Load warnings

- .travis.yml
Just use the non-Dev version of Python 3.9 now that Travis CI finally supports it.
> Travis CI now supports 3.9

- scripts/2010/01/report_errors.py
Closes #
https://github.com/internetarchive/olsystem/blob/master/etc/cron.d/openlibrary.allnodes#L22 runs this file in a cron job as discussed at https://github.com/internetarchive/openlibrary/pull/3880/files#r499755723 so this PR ensures basic Python 3 compatibility.
> Python 3 for scripts/2010/01/report_errors.py

- openlibrary/plugins/openlibrary/api.py
Closes #3948, #3950, #3955 
If `compose_ia_url()` returns an empty string for a URL then do not call `core.lending.get_available()` and set `works` to an empty list.
These three Sentry issues are all interrelated and happen a lot!
https://sentry.archive.org/sentry/ol-web/issues/5654 218k times in Sentry
https://sentry.archive.org/sentry/ol-web/issues/3807 522k times in Sentry
https://sentry.archive.org/sentry/ol-web/issues/3808 334k times in Sentry
> Deal with empty url in api.py browse

- .travis.yml
- docker/Dockerfile.olbase
Runs `pip list --outdated` in the Docker build process for olbase and in Travis CI so we can see which dependencies are not up-to-date.  This is a substitute for the automated approach suggested in #3580 and #3364.
> List outdated dependencies

- openlibrary/templates/search/advancedsearch.html
Works on #2798
Fixes HTML validation issues on /advancedsearch [link](https://validator.w3.org/nu/?doc=https%3A%2F%2Fopenlibrary.org%2Fadvancedsearch)
Front end / UI  of the page remains the same.
(Not sure, let me know who to tag in future PRs) @cdrini @mekarpeles
> Resolve HTML validation errors with advancedsearch

- openlibrary/plugins/worksearch/code.py
In support of #3296 
This PR creates a function that will return a number of random authors in JSON format.
This implementation queries Solr for any author, and uses the [random sort field](https://lucene.apache.org/solr/4_9_0/solr-core/org/apache/solr/schema/RandomSortField.html) to get random results.  A new seed is generated each time the function is called (the same seed will yield the same results each time).
@cdrini @ArunTeltia
> Create query for random authors

- openlibrary/plugins/upstream/covers.py
Closes #3687
Take the `str` output of `urllib.parse.urlencode()` and encode it as `bytes` before using it as the data payload in a `urllib.request.urlopen()` call.
There are two branches of functionality in this dialog:
1. Browse for a local image and
* `i.file.value` is  `bytes` that can not be decoded utf-8
* Still raises `{"error": "internal server error"}`
2. Enter the URL of a remote image
* The code in this PR solves the exception but the image does not come through.
> Minimal fix for Python 3: Add Cover Image hangs

- openlibrary/plugins/openlibrary/sentry.py
- openlibrary/plugins/openlibrary/status.py
Closes #3991  Add the git SHA to `sentry_sdk.init()` to simplify linking the software to Sentry issues.
As discussed at https://docs.sentry.io/product/releases the next step would be to open the integration between Sentry and GitHub but my current Sentry access rights do not allow me to do so...
`get_software_version()` was tested in the Python 2 REPL and Python 3 REPL
> Add release to Sentry init

- openlibrary/plugins/worksearch/code.py
https://sentry.archive.org/sentry/ol-web/issues/3768 has happened more than 10k times in the past month but is difficult to debug because `Error parsing empty search engine response` is logged in two different places and is logged too late to have the context of what solr_select or URL failed.  This  PR logs closer to the problem so we will have the context to debug worksearch issues.
> Provide better error messages in plugins/worksearch/code.py

- openlibrary/core/models.py
Getting an error on prod: /opt/openlibrary/deploys/openlibrary/824a904/openlibrary/templates/recentchanges/lists/comment.html: error in processing template: AttributeError: 'module' object has no attribute 'Seed' (falling back to default template)
Closes #4019 . Hotfix; looks like there's some python black magic going on here :/
> Add Seed back to models

- openlibrary/core/lists/model.py
Closes #4015
Adds an `@type_setter()` method to the Seed class to be able to read and write `Seed.type` .
> Python 3: Fix AttributeError in Seed.type

- docker-compose.production.yml
This was causing perf issues when we switched to web1 & web2
Deployed to web1 and web2 to curb excessive memory usage.
> Set max-requests for production gunicorn

- openlibrary/plugins/upstream/borrow.py
Closes https://sentry.archive.org/sentry/ol-web/issues/9699 and https://sentry.archive.org/sentry/ol-web/issues/9700 
Encodes the str `access_key` as bytes (if necessary) before calling [hmac.new](https://docs.python.org/3/library/hmac.html)
> make_ia_token access_key must be bytes

- openlibrary/plugins/worksearch/publishers.py
Closes https://sentry.archive.org/sentry/ol-web/issues/3879
Detect if `page = subjects.get_subject()` has failed and `page is None`.
> page is None in plugins/worksearch/publishers.py

- openlibrary/plugins/openlibrary/js/carousels_partials.js
Closes #3818
This PR ensures that the AJAX call for the related works carousels only occurs when the document has fully loaded.  Thanks to @shaneriley for identifying the issue, here: https://github.com/internetarchive/openlibrary/issues/3818#issuecomment-712361206
If `document.readyState === 'complete'` when the carousel partials are initialized, the related works AJAX call is made.  Otherwise, the AJAX call is attached as a callback to `window.onload`.
I was able to test both cases locally in Chrome.
Navigating directly to a book page typically caused the code inside of the `document.readyState === 'complete'` if block to execute. Navigating away from that page and pressing Chrome's back button typically caused the code in the `else` block to execute.
> Fetch related works when document is loaded

- openlibrary/core/helpers.py
Closes #4040
Reverts a change made in https://github.com/internetarchive/openlibrary/pull/3906#pullrequestreview-518213407 to reenable our internationalization of strings.
> from openlibrary.i18n import gettext as _

- openlibrary/catalog/add_book/__init__.py
Closes https://sentry.archive.org/sentry/ol-web/issues/3815
In `add_user`:
```
if not user:
raise RuntimeError("accounts.get_current_user() failed")
```
because unauthenticated users should not be allowed to add books.
> Fast fail if there is no user in add_book.py

- openlibrary/macros/Pager.html
Closes https://sentry.archive.org/sentry/ol-web/issues/9696 see the value for `half` which is a float, not int.
Use integer division to fix `TypeError: 'float' object cannot be interpreted as an integer`
> Use integer division for pagination in macros/Pager.html

- openlibrary/plugins/openlibrary/opds.py
Closes https://sentry.archive.org/sentry/ol-web/issues/9697 
Like #3744 
On Python 2 `bytes == str` so both have a `.decode()` method.
On Python 3 `bytes != str` and only `bytes` has a `.decode()` method.
Only `bytes` will be decoded.
> str.decode() to bytes.decode() in plugins/openlibrary/opds.py

- docker-compose.production.yml
- docker-compose.staging.yml
Modifies `docker-compose.production.yml` and `docker-compose.staging.yml` to ensure that:
1. `hostname` is properly set on both bash and zsh
2. $PYEVN_VERSION has a reasonable default if not set on the command line.
> Docker: Set reasonable defaults for hostname and pyenv_version

- openlibrary/core/processors/readableurls.py
Closes #4033 
- avoids clobbering `property` and `type` keywords
Uses urlencoding to get around unicode characters being encoded as invalid latin characters by webpy application.py
Tested on staging (works on python3) -- breaks on dev (python2)
> Fixing unicode urls in python3

- openlibrary/plugins/upstream/borrow.py
Closes #4068
Closes #4038
Supplants & closes #4069
https://sentry.archive.org/sentry/ol-web/issues/9699
https://sentry.archive.org/sentry/ol-web/issues/9700
presumably must use md5 (while less secure) to match keys + process on IA side? Tried sha1 and the flow reported malformed url response.
Incognito, logged out -- log in to non-admin account on OL, borrow a book, go to OL loans dashboard, click read of same book. Should log you in to archive.org automatically and show book (checked out)
@cclauss @cdrini
> closes #4068, closes #4038 supplants #4069 - fix hmac borrowing

- openlibrary/catalog/marc/fast_parse.py
- openlibrary/catalog/marc/html.py
- openlibrary/catalog/marc/tests/test_marc_html.py
Fixes the following errors:
```
<class 'TypeError'> at /show-records/marc_loc_2016/BooksAll.2016.part41.utf8:32007375:748
argument should be integer or bytes-like object, not 'str'
```
URL: 
https://openlibrary.org/show-records/marc_loc_2016/BooksAll.2016.part41.utf8:32007375:748
https://openlibrary.org/show-records/marc_loc_2016/BooksAll.2016.part41.utf8:32007375:748?debug=true
Closes #
> fix py3 bytes/str issue when viewing a MARC record

- openlibrary/core/lending.py
In plugins/upstream/borrow.py within borrow endpoint, the last step before we redirect to bookreader auth link (which performs IA login during redirect) is to fetch (what _was_ cached) loan data. If the book didn't exist in the loan data (which is possible, because of caching) then we'd redirect to the book on archive.org w/o performing the bridge authlink login.
NB: Another more performant solution (if this PR blows up production, which it might because book pages currently do a LoanStatus check which includes a hit to user.loans which was previously cached) then we can simply create a cached and uncached version and then have the borrow logic hit the _uncached_ version.
Related to #4068 -- testing complicated by the absence of easily reproducible lending.
> fix loans across workers to not cache

- openlibrary/core/helpers.py
- openlibrary/templates/type/user/view.html
Closes #4010
feature
This adds the 'noindex' meta tag to newer people pages but not list pages.
On dev, go to /recentchanges, click on a recently created people page, look at the source HTML, and search for "robots".  You should see:
```
<meta name="robots" content="noindex" />
```
If testing in a local dev instance, see below.
```
$ echo -- && grep days_since openlibrary/templates/type/user/view.html && curl -s localhost:8080/people/openlibrary | egrep "robots|Joined" && echo --
--
$if days_since(page.created) < 30:
<i>Joined March 20, 2013</i>
--
$ echo -- && sed -i 's/< 30/< 2800/' openlibrary/templates/type/user/view.html && grep days_since openlibrary/templates/type/user/view.html && curl -s localhost:8080/people/openlibrary | egrep "robots|Joined" && echo --
--
$if …
```
> Add 'noindex' meta tag to people pages that are less than 30 days old.

- openlibrary/plugins/openlibrary/code.py
Closes #4080 and https://sentry.archive.org/sentry/ol-web/issues/9042
Opens #4083 for the underlying TypeError.
Suppresses an AttributeError so that the underlying TypeError is visible.
> Exceptions don't have e.message attribute in Py3

- docker-compose.production.yml
Required for enabling sponsorship on docker prod web nodes
> adding booklending_utils to volume mounts

- openlibrary/core/stats.py
- openlibrary/plugins/openlibrary/stats.py
Closes #3782 
Any way to check to check this specific node is sending fewer memcached results?
Otherwise, I think we should soft-deploy / patch this on ol-web1, and ol-web2 and ping @samuel-archive 
@samuel-archive @cdrini @cclauss
> closes #3782 fixes statsd memcache sampling rate

- openlibrary/plugins/upstream/utils.py
Related to  #2181
When running with Python 3, meta tags are being corrupted (e.g. `<meta property="b'og:title'" ...>`). This is visible on openlibrary.org, e.g. view-source on https://openlibrary.org/books/OL18347472M/The_heart_of_the_matter. This patch removes the unnecessary `.encode` call to fix this.
Visit any page for a work, and check that the meta tags look like this:
```    <meta property="og:type" content="books.book" />```
instead of this (the current, incorrect behaviour):
```    <meta property="b'og:type'" content="b'books.book'" />```
> Fix meta tags on Python 3

- docker-compose.yml
Unintentional commit due to GH's misleading UI.
> Revert unintentional commit

- docker-compose.yml
- docker/ol-covers-start.sh
Refactor covers service yml so that we can configure it correctly for production.
Tested `docker-compose up -d` brings up covers, and it stays up.
@cclauss
> Make covers service configurable like web

- docker-compose.production.yml
- docker-compose.yml
- docker/ol-infobase-start.sh
Like #4112, #4113 but for infobase running on ol-home
`$INFOBASE_OPTS` is probably wrong!!
> Infobase running on ol-home

- openlibrary/utils/compress.py
Closes #4096, #4085 
Ensures `decompress(self, ctext: bytes):` because legacy Python does not support type hints.  If ctext is not bytes then it is encoded.
Also, changed the tests to align with pytest discovery rules and also self-doctesting.
> Compressor().decompress(ctext) must be bytes, not str

- openlibrary/templates/type/author/view.html
Fix. Causing an error because it would sometimes be undefined. Most authors are people, so we can lax this to only use Organization in the very rare case that org is explicitly defined.
http://staging.openlibrary.org/authors/OL3028905A/Jon_Richardson No longer throw the error it threw before.
@nk4456542 @hornc
> Fix entityTypeSchema undefined it no entity_type

- openlibrary/templates/site/body.html
Small fix for #3957 ; I missed this during testing!
@nk4456542
> Fix: bodyattrs should not be html escaped

- scripts/infobase-server
A subtask of #4059
Log that `flups.WSGIServer()` is being properly launched with `server.app.wsgifunc()` on the appropriate port.
> Add logging to scripts/infobase-server

- conf/coverstore.yml
- conf/openlibrary.yml
- openlibrary/coverstore/server.py
- openlibrary/plugins/openlibrary/code.py
- openlibrary/plugins/openlibrary/sentry.py
- openlibrary/plugins/openlibrary/status.py
- openlibrary/utils/__init__.py
- openlibrary/utils/sentry.py
- scripts/coverstore-server
Closes #4053
(Mostly) closes #3830 
Feature. Add sentry logging to covers.
Extracted shared logic into some utils, so adding to infobase shouldn't be very difficult.
Tested:
- ✅ Locally enabling sentry for covers on py3 + introduce a `1/0`; event logged with request info
- ✅* Locally enabling sentry for covers on py3 + introduce a handled `1/0`; event logged (but _without_ request info)
- Request info missing; but can fix in a future PR
- ❌ Locally enabling sentry for covers on py2 + introduce a `1/0`; event logged with request info
- It wasn't logged at all :( Not sure why
- ✅ Locally enabling sentry and try web (py2) node with error; error gets logged.
- ✅ Test on staging.openlibrary.org that errors logged
> Add Sentry to Coverstore

- openlibrary/plugins/upstream/addbook.py
Closes #3704, #4092 
Based on lessons learned from benoitc/gunicorn#2319
> urllib.parse.quote() Unicode urls on redirect

- openlibrary/catalog/add_book/__init__.py
Closes #1619
Adds a `source_records` metadata field (the same as used by editions) to indicate the source of a newly created Author.
This will be useful in tracking down ambiguities about author identity by anchoring the import to a specific external record. 
Previously the earliest imported edition of an Author had to be found to get the source. 
Local testing JSON result of a newly imported author, showing correctly formatted `source_records`
```
{"name": "Kokuritsu Gekij\u014d Okinawa. Ch\u014dsa Y\u014dseika", "source_records": ["marc:marc_loc_2016/BooksAll.2016.part40.utf8:48680251:1475"], "created": {"type": "/type/datetime", "value": "2020-10-27T23:40:31.463959"}, "last_modified": {"type": "/type/datetime", "value": "2020-10-27T23:40:31.463959"}, "latest_revision": 1, "key": …
```
> Adds source to Author initial imports

- openlibrary/macros/BookPreview.html
- openlibrary/macros/StarRatings.html
- openlibrary/macros/databarDiff.html
- openlibrary/macros/databarEdit.html
- openlibrary/macros/databarHistory.html
- openlibrary/macros/databarMerge.html
- openlibrary/macros/databarTemplate.html
- openlibrary/macros/databarView.html
- openlibrary/templates/recentchanges/header.html
- openlibrary/templates/type/edition/view.html
- static/css/components/edit-toolbar--tablet.less
- static/css/components/edit-toolbar.less
- static/css/legacy.less
Closes #163. 
Error regarding `workid` can be ignored, its a custom attribute.
Before: 
After: 
`text-underline` and `role:presentation` errors will be removed if PR #3878 is accepted. Proof: 
@cdrini
> Fixed validation errors on Editions page.

- scripts/dev-instance/dev_db.pg_dump
Closes #4090 
fix
This was generated using the instructions [here](https://github.com/internetarchive/openlibrary/issues/4090#issuecomment-728382622).  There is at least one encoding change and a lot of schema and permission changes (both changes to existing schema statements, as well as new schema and permission statements) included here, not just the creation of the beta-testers usergroup (which I did see a few new lines for).  Please review this carefully to make sure no unexpected schema changes are included here!
I reverted the work-around mentioned [here](https://github.com/internetarchive/openlibrary/issues/4090#issuecomment-728707141), ran ```docker-compose down``` and ```docker-compose up```, and I no longer get the error mentioned in the issue linked above.
The usergroup now …
> Add beta-testers usergroup to local dev database

- openlibrary/plugins/upstream/code.py
Closes #4089 
fix
This adjusts a permission check for page revert functionality.
Related past PRs: #2228 and #2280
Refer to the steps to reproduce in the issue.  Injecting frontend code to revert a page as a non-admin, non-librarian should no longer succeed.  Doing so as a logged out user should now return a permission denied page instead of an error/stacktrace. 
Logged in, non-admin, non-librarian now gets this:
A logged out user now gets this:
> Prevent non-admins / non-librarians from being able to revert pages to previous versions

- openlibrary/coverstore/code.py
Closes https://sentry.archive.org/sentry/ol-covers/issues/11156
Sometimes `covers` is stored as `[None]` or `[-1]` to indicate that there are no covers.  The current logic does `covers[0] <= 0` which will raise an uncaught TypeError when covers[0] is None.  This modification converts None to 0 to avoid the uncaught exception.
> Coverstore: Properly deal with covers = [None]

- openlibrary/macros/RecentPageList.html
- openlibrary/macros/SRPCoverImage.html
- openlibrary/macros/UserEditRow.html
> breaking commit of manually checking HTML_Validation

- openlibrary/plugins/upstream/covers.py
Closes #
Sentry shows us many have many JSONDecodeErrors which are often caused because we do not detect errors as they happen but instead wait until the json decoder raises. https://sentry.archive.org/sentry/ol-web/?query=JSONDecodeError
Here we will fast-fail by catching and logging `requests` errors while we still have enough context to debug those errors.
```
2020-11-25 19:20:58 [216] [openlibrary.logger] [INFO] solr request: http://ol-solr1:8983/solr/select?wt=json&q=key%3A%22%2Fworks%2FOL4226152W%22&start=0&fl=cover_edition_key%2Ccover_id%2Cedition_key%2Cfirst_publish_year%2Chas_fulltext%2Clending_edition_s%2Cchecked_out%2Cpublic_scan_b%2Cia
/openlibrary/openlibrary/plugins/upstream/utils.py:744: FutureWarning: This search is broken in 1.3 and earlier, and will be fixed in a future …
```
> Fix py2-web -> py3-covers bug + Improve error reporting in plugins/upstream/covers.py

- openlibrary/plugins/worksearch/subjects.py
Fixes: https://sentry.archive.org/sentry/ol-web/issues/3825 which occurs on both Python 2 and Python 3.
The filters might cause valid subjects not to be returned as evidenced by the test two lines further down.
NOTE: There is an open TODO on lines 56 and 57.
Closes #
> fix AttributeError: 'NoneType' object has no attribute 'v2'

- scripts/infobase-server
Closes #4061
Adds Sentry to infobase so that runtime errors are raised in https://sentry.archive.org/sentry/ol-infobase/
> Add Sentry to Infobase again

- docker-compose.override.yml
- docker-compose.production.yml
- docker-compose.staging.yml
- docker-compose.yml
- docker/infobase_nginx.conf
- requirements_common.txt
Closes #4130,#4132 plus fixes the $HOST issue and provides access to etc/ia.ini to the web nodes.
`deploy` will be ignored in our current environments but will become useful in environments when `restart` is ignored.
* https://hub.docker.com/_/nginx
* https://docs.docker.com/compose/compose-file/#deploy
* https://docs.docker.com/compose/compose-file/#restart
* https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/#nginx
Do we need to do something special with `/var` ?
> Define infobase_nginx and give web nodes access to ia.ini

- openlibrary/core/processors/readableurls.py
- openlibrary/plugins/inside/code.py
- openlibrary/plugins/openlibrary/design.py
- openlibrary/plugins/openlibrary/home.py
- openlibrary/plugins/openlibrary/lists.py
- openlibrary/plugins/openlibrary/status.py
- openlibrary/plugins/openlibrary/support.py
- openlibrary/plugins/upstream/account.py
- openlibrary/plugins/upstream/recentchanges.py
- openlibrary/plugins/worksearch/code.py
- openlibrary/plugins/worksearch/languages.py
- openlibrary/plugins/worksearch/subjects.py
- openlibrary/templates/site/head.html
- openlibrary/views/loanstats.py
- openlibrary/views/showmarc.py
- static/css/js-all.less
- static/css/layout/v2.less
Follow up to aad55eb2887572a766dd91
* All pages are v2 now and the variable which was previously used
inside openlibrary/templates/site/body.html is no longer used so
this can be safely removed
* Update the CSS comment in static/css/js-all.less to reflect the
current status quo for that LESS file.
Fixes: #4174
Closes #4174
> Drop mentions of v2

- openlibrary/coverstore/code.py
- openlibrary/coverstore/coverlib.py
Improve error reporting in key coverstore classes to make it easier to discover the root cause of issues like #4160
When an exception is raised, call logger.exception() and also call logger.error() on all errors.
> Improve error reporting in coverstore

- openlibrary/coverstore/code.py
- openlibrary/coverstore/oldb.py
- openlibrary/coverstore/tests/test_webapp.py
- openlibrary/coverstore/utils.py
Related to #2308
In coverstore, remove the third-party dependency [simplejson](https://pypi.org/project/simplejson) in favor of the Python standard library's [json module](https://docs.python.org/3/library/json.html).
> Remove simplejson from coverstore

- Makefile
It slows down testing _significantly_ locally; went from ~3min -> 1min :)
@cclauss
> Ignore node_modules when testing python

- docker-compose.production.yml
Closes #4059
A few last config updated to get infobase running on Python 3.8 on Ubuntu Fosa in Docker on ol-home0
> infobase golive mods

- docker-compose.production.yml
Closes #4054
Ensure we mount the correct coverstore nginx settings from olsystem.
As discussed in https://internetarchive.slack.com/archives/G014GGN2A5S/p1606864836087400 
$ `diff --git a/docker-compose.production.yml b/docker-compose.production.yml`
```
index 7e160c669..e9f320d3d 100644
--- a/docker-compose.production.yml
+++ b/docker-compose.production.yml
@@ -37,7 +37,7 @@ services:
- ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
- ./docker/covers_nginx.conf:/etc/nginx/sites-enabled/covers_nginx.conf:ro
-      - ../olsystem/etc/nginx/default-docker.conf:/etc/nginx/sites-enabled/default:ro
+      - ../olsystem/etc/nginx/sites-available/default-docker.conf:/etc/nginx/sites-enabled/default:ro
```
> coverstore golive mods

- openlibrary/plugins/upstream/spamcheck.py
Closes #4138 
feature
This incorporates ```re.search()``` into the spamcheck library.  I figure the cost of this vs. just a string match is negligible given the relatively low frequency of updates and the relatively small size of text being matched against each time.  This should probably be tested on dev first to make sure the existing spamwords still work.
Confirm this doesn't break existing functionality:
1. Go to /admin/spamwords and choose one of the lines/phrases to use in the test.
1. Go to /books/add and add that phrase to the title field.  Add anything to the publisher field and any year in the "When was it published?" field.
1. Click the 'Add' button.  The addition should still fail, like it does without this PR.
Confirm that regular expressions work now:
1. Go to …
> Add regular expression support to the spamcheck library.

- openlibrary/plugins/upstream/addbook.py
- openlibrary/plugins/upstream/code.py
Closes #4171 
feature
This moves the edit class out of addbook.py, since it relates to more than just adding books.  This utilizes the existing spamcheck library.  
1. If you want to see why this PR moves code out of addbook.py, then before applying this patch, visit the edit page for your account profile with the ```_profile=true``` URL parameter and search for "addbook" to confirm that it's used for more than book editing.
1. After applying this patch, pick a line from /admin/spamwords and try to add it to any text box in your profile.  The response should be an "Oops" page and the edit should fail.
1. Try adding a non-spamword to your profile page, and it should succeed.
@mekarpeles @cdrini @cclauss
> Extend admin spamwords checking to account profile pages

- docker-compose.staging.yml
trivial changes to staging docker compose to add `internetarchive` `ia.ini` and `booklending_utils` to staging volume mounts
> adding booklending_utils, ia.ini to staging

- .travis.yml
We hit Travis' new restrictions for public repos (see https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing ) last month, so trying to see if we can reduce how much time we spend running Travis. We hit the limit pretty late in the month though, on Nov 24th; so a few reductions might be all we need to do to get back into December.
Here I:
1) Only test on Xenial; that's what all our Dockerfiles use, and it's very unlikely we'll make a change that causes something to break on other versions of Ubuntu
2) Don't test on Python 3.9 ; it's very unlikely we'll introduce a change that causes 3.9 to break
That takes us from 6 jobs to 4 jobs :)
Python 3.9 was also the slowest (see e.g. https://travis-ci.com/github/internetarchive/openlibrary/builds/203778599 ), so this should reduce our total …
> Reduce travis file complexity

- openlibrary/templates/type/edition/publisher_line.html
It should be: This edition **was** published in 1998 by Bloomsbury in London, England.
> Fixed Grammatical error

- openlibrary/plugins/inside/code.py
- openlibrary/plugins/worksearch/code.py
https://docs.python.org/3/library/json.html#json.dump
> If indent is a non-negative integer or string, then JSON array elements and object members will be pretty-printed with that indent level. An indent level of 0, negative, or "" will only insert newlines. None (the default) selects the most compact representation. Using a positive integer indent indents that many spaces per level. If indent is a string (such as "\t"), that string is used to indent each level.
Closes #
> json.dumps(indent) is an int or str, not bool

- openlibrary/plugins/openlibrary/api.py
Fixes: https://sentry.archive.org/sentry/ol-web/issues/3856
`None` is the default parameter if the web page does not provide a value for bookshelf_id.  Calling `int(None)` will raise a TypeError, not a ValueError.
An alternative solution would be to make `1 the default value instead of `None`.
Closes #
> fix TypeError: int() argument must be a string or a number, not None

- docker-compose.production.yml
- docker-compose.staging.yml
- docker/ol-web-start.sh
Fix. This repo is needed on production, but not available/necessary for local dev.
- ✅ `docker-compose up --no-deps web` starts web without issue
- ✅ `docker-compose -f docker-compose.yml -f docker-compose.production.yml up --no-deps web` tries to install booklending
- ✅* Pip install works
- Need to set owner of booklending_utils to something docker has access to :/
- ✅* Service starts up
- There's some sort of perms issue with booklending_utils/ia? Made a local mod to booklending_utils to override this, but we can't commit a fix to that repo until we get feedback from its maintainer.
Tested: http://staging.openlibrary.org/sponsorship/eligibility/OL1099079M
@mekarpeles
> Pip install booklending_utils on prod/staging

- static/css/components/work.less
Closes #4046
Just changes the height according to the font-size which is 13px and have some padding round to 57px I just added 3px that approximate up to 60px
@jamesachamp @mekarpeles
> height bug fixed

- .github/workflows/test_javascript.yml
Related to  #4207,#4188
Because Travis CI no longer freely supports open-source projects.
> GitHub Action: Add test_javascript.yml

- scripts/make-integration-branch-sample.txt
- scripts/make-integration-branch.sh
When a fork is deleted, we can't pull down a PR's code! So add support for pulling down the patch.
@cclauss
> Add make-integration-branch support for GH patch links

- openlibrary/plugins/upstream/adapter.py
Closes #4227 
Fixed Dangerous default value convertions (builtins.dict) as argument
@cclauss
> Fixed Dangerous default argument

- openlibrary/plugins/upstream/account.py
Closes #4264
Fix to redirect `GET /account/import/goodreads` to `/account/import` (with `require_login` decorator`)
Followed the same pattern as class `import_books`
Verify that http://localhost:8080/account/import/goodreads redirects you to login page if not logged in, or `/account/import` when you are logged in.
N/A
> Redirect get to account/import for #4264

- openlibrary/templates/type/author/edit.html
Closes #4101 
Removes the duplicate delete button present in the edit authors page.
Removed the delete button present in the `openlibrary/templates/type/author/edit.html`.
I was not able to test this as the local setup is down, details in this issue #4090 
@seabelis
> Remove the Duplicate Delete Button on Edit Authors Page

- openlibrary/core/models.py
- openlibrary/templates/type/edition/view.html
Closes #3760, #4051, #4052, #4224
Avoid an index error if not `page.works` and then create a work from an orphaned edition.
> Make work from an orphaned edition

- openlibrary/plugins/upstream/account.py
Closes #4277
when a patron registers an account, they click an email to activate on Archive.org. Once activated, archive.org provides a link to login on Open Library. But Open Library is checking/setting the referrer incorrectly so that on OL login, the patron was being redirected back to IA (bad experience). This change-set updates the referrer check to prevent redir back to archive.org on login. 
The only case I can imagine this breaking is for borrows where patron is logging in to OL to then access some IA borrow/read link through OL, but I don't think such an exact case exists and unblocking creation / login flow is paramount to patron's experience.
Create an account on production and login (should be brought to OL)
@seabelis @cdrini @cclauss @bfalling
> update login referer check to prevent redir to IA

- openlibrary/templates/books/edit/edition.html
Closes #228
fix
Removes the is_admin check and admin-related styling from the "first sentence" section of the book edit page.
Added a test first sentence to a local book using the "Open Library" admin account.  Confirmed that the local AccountBot account was not an admin and could not see the "first sentence" edit box.
With this PR, AccountBot was able to see the edit box and successfully make an edit:
and it appears on the book page:
> Allow non-admins to edit the first sentence on a book page.

- openlibrary/templates/covers/change.html
Fixing the issue Regression - Cover change of work requires refresh to view #3395
Closes #3395
This enables refreshing the cover image in the works page "https://openlibrary.org/works/..." immediately after update without the need for refreshing the page.
openlibrary/templates/covers/change.html is changed. 'srcset' attribute in the img tag in bookCover class is also updated along with the 'src' attribute.
@tabshaikh @seabelis
> Display new cover image in works page without refreshing the page

- docker-compose.production.yml
- docker-compose.yml
Closes #4327 #4326
Repeat the error logging approach used for `solr` on the services web, covers, infobase, and home.  This keeps the error logs inside the Docker containers and limits their maximum size to 512M and their maximum number of files to four.
`infobase` production is a bit of a question because it contains:
```
volumes:
- infobase-writelog:/1/var/lib/openlibrary/infobase/log
- infobase-errorlog:/1/var/log/openlibrary/infobase-errors
```
> Keep trimmed logs inside Docker for web, covers, infobase, and home

- .gitignore
- docker-compose.infogami-local.yml
- docker-compose.production.yml
- docker-compose.yml
- docker/Dockerfile.oldev
- docker/ol-home-start.sh
- docker/ol-solr-updater-start.sh
Closes #4244 (which got in a bad git state and was closed)
Related to #4060
Borrows from https://github.com/internetarchive/olsystem/blob/master/etc/supervisor/conf.d/solr-updater.conf to build a Docker service that can be run from ol-home0 to execute solr-updater.
> Create solr-updater docker service AGAIN

- openlibrary/macros/LoanStatus.html
Closes #4360 which standardizes all borrow calls to action as "Borrow" rather than e.g. 1h since all borrows now originate as 1 hour.
Within the PR, the code block logic for available_to_browse and available_to_borrow not merged in case we do want different copy in the future.
@cdrini @bfalling @brewsterkahle
> standardizes call to action as "borrow"

- openlibrary/solr/db_load_authors.py
- openlibrary/solr/db_load_works.py
- openlibrary/solr/process_stats.py
- openlibrary/solr/read_dump.py
- openlibrary/solr/update_work.py
Addresses #2308
Refactor to replace simplejson with python json in openlibrary/solr package.  In most cases `simplejson` was being imported as `json` anyway.
Unit tests pass.
N/A
@cclauss
> Replace simplejson with python json in openlibrary/solr package for 2308

- docker/README.md
Documentation change. The recent change to the infogami submodule caused docker-compose up to fail for existing repos (since they would have a copy of the old infogami). These instruction fetch the latest configs.
@jdlrobson
> Add instructions for fully resetting dev environment

- openlibrary/code.py
- openlibrary/conftest.py
Removes the unused import from `openlibrary/code.py` & `openlibrary/conftest.py`
Save for the end:
> Remove unused imports from code.py & conftest.py

- static/css/components/carousel.less
- static/css/components/category-item.less
Closes #4012 
2px padding was added so that when one tab through the site the outlines are properly visible **but due to this "1 hour borrow" doesn't fit.** (check 3rd image)
@jamesachamp
> Fixed focus outlines hidden

- CONTRIBUTING.md
Updated CONTRIBUTING.md to reflect our new 10:00 am PT community call time.
Time has been updated in the wiki, and the community call link in the wiki sidebar links to the 2021 meeting minutes document.
> Update community call time

- .github/workflows/python_tests.yml
Closes #
Subtask of #4384
Remove Python 2 from our GitHub Actions testing
Yes.
> GitHub Actions: Remove legacy Python from testing

- .github/workflows/python_tests.yml
Closes [` The workflow is not valid. .github/workflows/python_tests.yml (Line: 12, Col: 25): Unexpected value '3.8' `](https://github.com/internetarchive/openlibrary/actions/runs/475086987) caused by #4385
hotfix
> Fix our currently invalid Python GitHub Action

- openlibrary/templates/type/edition/view.html
- static/css/components/work.less
> Fixed edition-header h3 spacing

- openlibrary/core/loanstats.py
Addresses #2852
Refactor to replace `urllib.urlopen` with `requests`.   Also cleaned up some lint/pycodestyle warnings about formatting.
Uses `requests.compat` to remove the `urllib` import and only use `requests`.
Manually tested to verify the code ran as expected, and unit tests pass.
N/A
@cclauss
> Replace urllib.urlopen with requests in loanstats.py for 2852

- openlibrary/code.py
Hotfix. Blocking the deploy. This was removed in a recent PR (cc @jdlrobson ), but caused the marc endpoint (e.g. https://openlibrary.org/show-records/marc_loc_2016/BooksAll.2016.part41.utf8:32007375:748 ) to stop working. 
@jdlrobson
> Restore showmarc actions

- openlibrary/templates/lists/header.html
- openlibrary/templates/lists/lists.html
Closes #4288
The list count is updated as soon as the list is deleted.
@jamesachamp
> Update list count on Deletion

- openlibrary/templates/books/edit/edition.html
Closes #4343 
Earlier in the books edit page, when entering ISBN 13, the validation function checked for 13 digits, but as per ISBN 13 standards, '-' dashes are also allowed. So, this PR fixes this problem.
@serv @cclauss
> Allow dashes when entering isbn

- openlibrary/core/fulltext.py
- openlibrary/tests/core/test_fulltext.py
Addresses #2852 
Refactor `openlibrary.core.fulltext` to replace urllib.openurl with requests.get.  Adds unittests for the exception cases.
The fulltext search api function is used in a couple of places;
- `plugins/inside/code.py`
- `plugins/worksearch/code.py`
Unit tests were added for exception cases.   You should also be able to do searches on staging in both "/search" and worksearch.
N/A
@cclauss
> Replace urllib with requests in openlibrary.core.fulltext

- openlibrary/plugins/openlibrary/js/index.js
Closes #4420 
Imported jQuery UI's Sortable widget in the main JS file.  Importing this widget fixes allows cover images to be added and removed without error.
1. Rebuild JS assets.
2. Navigate to a book page and attempt to upload a new book cover image.
3. Delete the newly uploaded image.
> Import jQuery-UI sortable widget

- openlibrary/templates/lib/nav_head.html
- static/css/components/header-bar.less
Closes #4200
Fix
I have tried using the [checkbox hack](https://css-tricks.com/the-checkbox-hack/) to fix the mobile hamburger issue. But it is not yet working as expected. The checkbox added to the [HTML file](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/lib/nav_head.html) and modified with the [CSS file](https://github.com/internetarchive/openlibrary/blob/master/static/css/components/header-bar.less) works as expected, but while inspecting the hamburger in the browser, its properties do not seem to change on trying to close it.  
1. Open openlibrary in development mode
2. Open the developer console and toggle to mobile view
3. Click on the "3-lines button" to open the menu
4. Click on it again to close it
-  **Expected**: Step 4 should close the …
> Use checkbox hack for the hamburger menu

- openlibrary/templates/type/edition/view.html
Closes https://internetarchive.slack.com/archives/C0ETZV72L/p1610879197058400
NOTE: Instead of `(edition or work).author_names` we can write `page.author_names`
Refer: https://internetarchive.slack.com/archives/C0ETZV72L/p1610978647060400?thread_ts=1610879197.058400&cid=C0ETZV72L
https://openlibrary.org/works/OL15690362W/Walt_Disney_fun-to-read_library_(duplicate)
https://openlibrary.org/works/OL17355493W/The_Generic_names_of_moths_of_the_world._n_Vol._5_p_Pyraloidea_c_edited_by_I.W.B._Nye_vol._5_by_D.S.
> Fix AttributeError: 'author_names'

- static/css/components/header-bar--desktop.less
- static/css/components/header-bar.less
Related to #4416 
Display more menu at mobile resolutions.
@jdlrobson
> Show More menu at mobile resolutions

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question_template.md
Right now it's hard to query for what issues require leads. In our new lead guide #4282 the procedure is to leave `Needs: Triage` and assign a `Lead: @lead`. This PR will make it easier to identify issue which need a Lead label.
> Add `Needs: Lead` label to Issue Templates

- openlibrary/core/observations.py
- openlibrary/plugins/openlibrary/api.py
- openlibrary/plugins/openlibrary/js/patron-metadata/index.js
Closes #4442 
Sends S3 keys to thebestbookon.com whenever a patron submits observations about a work.
POSTs to TBBO now come from Open Library's server instead of the client.
@mekarpeles
> Send S3 keys in observation POST messages

- openlibrary/core/vendors.py
Closes #
As reported by @seabelis [on Slack](https://internetarchive.slack.com/archives/C0ETZV72L/p1610379841273300)
Any idea what might cause this error?
```
/openlibrary/openlibrary/templates/type/edition/view.html: error in processing template:
JSONDecodeError: Expecting value: line 1 column 1 (char 0) (falling back to default template)
```
https://openlibrary.org/books/OL31849729M/Lolita
Open LibraryOpen Library
Lolita (2016-10-13 edition) | Open Library
Lolita by Vladimir Nabokov, 2016-10-13, Anagrama edition, Hardcover in Spanish / español (59 kB)
https://covers.openlibrary.org/b/id/10540617-L.jpg
cclauss
https://openlibrary.org/books/OL31849729M/Lolita?debug=true indicates that we got a Response [404] when querying Amazon.
```
/openlibrary/openlibrary/core/vendors.py in …
```
> Improve Amazon error detection

- openlibrary/core/cache.py
Subset of #4330
This code is ___only used in testing___ but it raises a RuntimeError on Apple Silicon M1 Macs.
See #4330 Screenshots, problem 4 for details.
Closes #
> cache.py: Avoid dict changed size during iteration

- openlibrary/macros/ReadButton.html
- openlibrary/plugins/openlibrary/js/ol.js
Merger note: Please merge #4456 after merging this one.
-----
Closes #4447 
refactor
Nit changes in the code. 
The look of the button and the task it is supposed to do is fine, if there's any weird cases involving the buttons, do let me know.
On prod: 
After change: 
[No change in the look] 
Validation errors due to these also go away: 
Before: 
After: 
@jdlrobson
> Changed read_ebook, borrow_ebook id's on buttons to classes

- openlibrary/accounts/model.py
Addresses #2308 
Remove simplejson import - and change JSONDecodeError catch to ValueError because requests will import simplejson first, and we cannot catch json.JSONDecodeError until we remove simplejson.
There isn't a unit test for this case.
Unit tests run.
N/A
@cclauss
> Remove simplejson dependency for 2308 in account/model

- openlibrary/macros/AffiliateLinks.html
consolidating vendors modified last by #3069
BK has asked to avoid a large list of vendors overwhelming the page. Suggestion is to consolidate as is mentioned in this PR.
Option to add a e.g. "other vendors" dropdown like goodreads
which shows more options.
See #4466
We could do something similar for libraries as well (similar to goodreads) Turn Worldcat + LibraryLink into a dropdown button + also (on click) load ~3 nearby libraries from librarylink API into that list 
@bfalling
> consolidating vendors back to core group

- openlibrary/templates/books/custom_carousel.html
Closes #4441 
@jdlrobson, I don't know why it's not working on the local env. Can you please review and guide me what all changes do I need to make?
@jdlrobson
> Fix validation errors on homepage

- openlibrary/templates/borrow_admin.html
- openlibrary/templates/lists/home.html
- openlibrary/templates/site/body.html
- static/css/legacy-borrowTable-adminUser.less
- static/css/less/colors.less
- static/css/page-admin.less
- static/css/page-book.less
- static/css/page-edit.less
- static/css/page-form.less
- static/css/page-home.less
- static/css/page-plain.less
- static/css/page-user.less
> Fix validation errors on lists page

- openlibrary/catalog/get_ia.py
- openlibrary/catalog/marc/marc_subject.py
- openlibrary/tests/catalog/test_get_ia.py
Addresses #2852 
This PR replaces #4388 
Removes urlopen and uses requests instead.
The MARC functions require a mixture of binary data and xml.  The code expects file type objects out of the helper function, but requests does not provide file type objects, so I've refactored to provide bytes instead.
It would be good to find out the urls that are used to be able to test this for the XML and binary cases - I haven't been able to get those yet.
For instance, what are example locators for a single MARC record, and a bulk locator?
What is `ia_base_url` set to?
N/A
@cclauss @hornc
> Refactor get_ia.py to use requests instead of urllib.urlopen

- openlibrary/templates/type/author/edit.html
Closes #3421 
Fixes uneditable date on author records.
Go to http://localhost:8080/authors/OL1095882A/Cid
Add birth or death date.
Save.
See if general date is displayed (should not be).
ALSO
Try to edit/remove general date field. Should no longer appear on profile once saved.
@SouthGoingZax @tfmorris @cdrini @hornc
> Conditionally display general date field on author profile

- openlibrary/coverstore/code.py
- openlibrary/plugins/openlibrary/code.py
- openlibrary/plugins/openlibrary/processors.py
Addresses #3399
Adds `Access-Control-Allow-Origin: *` to Open Library image API responses.  This only solves the issue for images coming from the coverstore.  Requests redirected to IA will not include this header in their response.
> Allow cross origin access for cover images

- openlibrary/coverstore/utils.py
These `urllib` imports are no longer required because we now use `requests`.
> Remove unused imports from coverstore utils.py

- openlibrary/utils/solr.py
We no longer need a json module because requests does it for us.
Subtask of #2308
@dherbst
Closes #
> Remove unused simplejson from openlibrary/utils/solr.py

- openlibrary/core/helpers.py
Closes: https://dev.openlibrary.org/admin/people/AliceKirk?debug=true
Fails only when it is run on legacy Python with `TypeError: can't multiply sequence by non-int of type 'str'`
This PR conditionally loads `simplejson` only if we are still running on legacy Python.
This is a Python 2-only issue with https://docs.python.org/2/library/json.html#json.dump where `indent` must be an int while Py3 https://docs.python.org/3/library/json.html#json.dump and simplejson https://simplejson.readthedocs.io/en/latest/index.html#simplejson.dump allow `indent` a str as well.
* `python3 -c "import json ; json.dumps({'a': 1}, indent='    ')" ` # no problems
* `python2 -c "import simplejson ; simplejson.dumps({'a': 1}, indent='    ')" ` # no problems
* `python2 -c "import json ; json.dumps({'a': 1}, …
> json.dump(indent) MUST be an int on Python 2

- static/css/page-edit.less
- static/css/page-form.less
page-form and page-edit both provide styles that override
the defaults specific for that page.
These will be cleaned up by the LESS compiler. To ensure that
the styles in this file override any defaults all imports must
be listed first.
This will address the issue with the change cover background not
being white.
Follow up to f996715949e5e370bf5b3bf28570beed680e4c3b
@cdrini  @Yashs911
> Imports should be at the top of the file

- openlibrary/templates/lists/widget.html
- static/css/components/dropper.less
- static/css/components/reading-lists.less
- static/css/components/work.less
- static/css/page-subject.less
Closes #3630 
feature
In [widget.html], div.reading-lists is moved out of div.dropper. This brought the User's list out of the fold and underneath the WantToRead Button. To remove formatting due to .dropper, the class name is changed to my-reading-lists. And further codes are added in dropper.less
make css
docker-compose up
Go to [http://localhost:8080/works/OL53924W/The_complete_works_of_Mark_Twain](http://localhost:8080/works/OL53924W/The_complete_works_of_Mark_Twain). Changes can be seen underneath Want to Read.
Before.
After.
@cdrini
> Userlist Brought under Want To Read Button #3630

- openlibrary/solr/process_stats.py
Blocked by #4387
Subtask of #4383
The solr/process_stats cron jobs will run in a Docker container on `ol-home0` but need to access a solar instance that is running on `ol-home`.  This PR removes the hardcoding of localhost in favor of using config to obtain `stats_solr` as it is defined in olsystem etc/openlibrary.yml
> Do not hardcode SolrWriter(host)

- docker/README.md
The home service now exits after its work is done, so `docker-compose exec` no longer works with it. Updated to be `docker-compose run --rm` where appropriate.
Closes #4540
@drakene
> Update docker instructions to use run for home

- static/css/components/buttonCta.less
Closes #4523
**Contrast Ratio**
Old : **2.84:1**
New : **5.74:1**
@bpmcneilly
> Fix color contrast issue for buttons

- openlibrary/views/showmarc.py
Related #2852 
Refactor showmarc to replace urlopen with requests.
Refactor showmarc to replace urlopen with requests.
Some pylint and pycodestyle changes for formatting.
```python
r0 = 0
r1 = 894
filename = 'CollingswoodLibraryMarcDump10-27-2008/Collingswood.out'
url = 'http://www.archive.org/download/%s' % filename
headers = {'Range': 'bytes=%d-%d' % (r0, r1)}
response = requests.get(url, headers=headers)
response.raise_for_status()
```
N/A
@cclauss @hornc
> Replace urlopen with requests in openlibrary/views/showmarc

- .stylelintrc.json
- openlibrary/macros/DonateModal.html
- static/css/base/headings.less
- static/css/base/helpers-misc.less
- static/css/components/buttonCta.less
- static/css/components/buttonsAndLinks.less
- static/css/components/chart.less
- static/css/components/donate.less
- static/css/components/edit-toolbar.less
- static/css/components/editions.less
- static/css/components/form.olform.less
- static/css/components/merge-form.less
- static/css/components/page-banner.less
- static/css/components/preview.less
- static/css/components/read-panel.less
- static/css/components/readerStats.less
- static/css/components/widget-box.less
- static/css/components/wmd-prompt-dialog--js.less
- static/css/components/work.less
- static/css/legacy-tools.less
- static/css/legacy.less
- static/css/page-admin.less
- static/css/page-barcodescanner.less
- static/css/page-user.less
Works on #4537, follow up to #4550
refactor 
After adding `"declaration-bang-space-before": "always",`, it was recognizing `!important` as its own font-family, hence ignored that in secondary options. 
Separated commits to go through the changes easier :) 
@jdlrobson
> Fixing linter errors continued

- openlibrary/solr/solrwriter.py
Contributes toward resolving #4542 
hotfix to only `.decode` in PY2.
Only necessary to `.decode` in PY2.
I think you have to hit the `add_field` function.
N/A
@cdrini @cclauss
> Do not .decode a str in PY3, only in PY2

- static/css/components/header-bar.less
- static/css/components/work.less
Closes #3796 
Increases thez-index for search-component and decreases the z-index for sticky-menu
> Fix Search Result Overlap

- openlibrary/templates/home/index.html
This field is deprecated, and now returns an error.
Closes #4570
Works on staging http://staging.openlibrary.org/
> Update deprecated loans__status__last_loan_date -> lending___last_browse

- openlibrary/templates/merge/authors.html
Changing term 'master' to 'primary' in auther merge. See #3795.
> change problematic terminology (#3795)

- static/css/less/colors.less
Related to #4522
New Contrast ratio: **4.53:1**
> Fix Advanced Search Color Contrast

- openlibrary/core/lending.py
Closes #4553 
Updated the Query to:
https://archive.org/advancedsearch.php?q=_exists_:openlibrary_work+AND+(lending___available_to_borrow:true%20OR%20lending___available_to_browse:true)&fl=identifier,openlibrary_edition&output=json&rows=1&sort[]=random
namely adding :true after lending___available_to_browse and lending___available_to_borrow so that they aren't interpreted as the actual query string.
Check https://openlibrary.org/random to verify
@mekarpeles
> Fix openlibrary/random

- openlibrary/core/waitinglist.py
- openlibrary/plugins/upstream/borrow.py
Closes #3403
This is a refactor to remove calls to `openlibrary.core.waitinglist.update_waitinglist` and a few other functions where their sole purpose was to call `update_waitinglist`.  There is some other pyflakes cleanup as well.
Removed the dead code after the `return` statements and calls to `update_waitinglist`.  When a function would have become a no-op, I removed the function and calls to it as well.
`make test-py` runs successfully.  
N/A
@mekarpeles
> Remove update_waitinglist because it is not necessary.  See #3403

- static/css/components/editions.less
Closes #4575 
Changed min-width to a fixed width.
**Old:** (minor glitch for Borrow button and major for Special Access)
**New:**
@jamesachamp @jdlrobson
> Fix Edition Table 'Listen' roll-over glitch

- openlibrary/accounts/model.py
- openlibrary/core/models.py
- openlibrary/macros/LoanStatus.html
- openlibrary/macros/ReadButton.html
- openlibrary/plugins/openlibrary/home.py
- openlibrary/plugins/upstream/account.py
Closes #4490 
Request from directors, have Open Library provide patrons with qualified print-disabilities an accurate depiction of which books are available to them. Dates back to our 2018 roadmap:
https://docs.google.com/document/d/1wpa4f-r8jBimam-36CAZGQ_QjApegm10XfH85eG7KAE/edit#
Uses the xauthn API which has been updates to return printdisability qualifications
Tested on dev.openlibrary.org (not yet on staging)
**May require care re: caching homepage carousel html!**
> Support special access btn for patrons w/ approved print-disabilities

- openlibrary/templates/work_search.html
- static/css/base/helpers-common.less
- static/css/legacy.less
Related to #4522 
1. Fix "more" and "less" color contrast (Search Result Page)
2. Fix missing "less" due to !important.
3. Fix color contrast of Search Inside Page
> Fix search result and search inside color contrast + Fix missing 'less' on search result page

- openlibrary/plugins/worksearch/code.py
- openlibrary/templates/work_search.html
Closes #3574
Adds ability to sort by lcc/ddc to /search and /search.json
- Note we're using the `ddc_sort`/`lcc_sort` fields, because solr does not support sorting on multi-valued fields, which is what `ddc` and `lcc` are. This does mean that some things will appear out of order when doing e.g. `ddc:8*` sorted by `ddc_sort`. So I also exposed `ddc_sort` as a search field we can use -- although this has the caveat that some works will be missing.
- Random sorting from the UI will (for now) always use the same seed, so that results are in a consistent order as you paginate. Longer term we might want a way to use another seed, or maybe use a seed that's relative to today, so that the order changes daily? The URLs do let you do e.g. `sort=random_my_seed` to get a new random.
- ~Title sorting …
> Ability to sort search results by classification, random

- openlibrary/plugins/openlibrary/js/carousels_partials.js
- openlibrary/templates/type/edition/view.html
- static/css/base/helpers-common.less
Closes #4592
PR ensures that `workid` is sent in `/partials` API calls, and the the `.hidden` CSS rule is honored.
`data-workId` was being changed to `data-workid` in the generated HTML, so the jQuery `.data()` call was returning nothing.  As a result, the work ID was not included in the `/partials` request's query string.
Additionally, the `.hidden` CSS rule was being overridden by the `.loadingIndicator`'s `display` rule, causing an endless loading animation.
2. Observe the related works carousel at the bottom of the page.
> Fix related works carousel

- openlibrary/macros/BookPreview.html
- openlibrary/macros/RecentChanges.html
- openlibrary/templates/admin/ip/view.html
- openlibrary/templates/admin/people/edits.html
- openlibrary/templates/history.html
- openlibrary/templates/lib/history.html
- openlibrary/templates/lib/nav_foot.html
- openlibrary/templates/recentchanges/new-account/path.html
- openlibrary/templates/recentchanges/render.html
Closes #2718
Refactor
1. Searched for occurrences of anchor tag with 'title' attribute.
2. If 'title' attribute is same as anchor text, deleted that particular 'title' attribute from the anchor tag.
@tabshaikh
> Remove duplicate anchor text

- openlibrary/templates/account/borrow.html
Closes #4642
There is only one image which needs to be fixed in the `Loans Page`
Fix for the alt attribute of Adobe logo:
The text beside the logo, explains the pusrpose of the image. An alt attribute describing the image will create repetition. So, it's better to assign `alt=""` .
@bpmcneilly
> Change alt attribute of adobe logo

- openlibrary/macros/FulltextResults.html
- openlibrary/macros/SearchResults.html
- openlibrary/templates/account/books.html
- openlibrary/templates/books/check.html
- openlibrary/templates/stats/readinglog.html
- openlibrary/templates/type/author/view.html
- openlibrary/templates/work_search.html
- static/css/legacy.less
> Id converted to class

- openlibrary/catalog/marc/fast_parse.py
- openlibrary/plugins/upstream/account.py
Closes pytest warnings on Python 3.10:
```
=============================== warnings summary ===============================
openlibrary/catalog/marc/fast_parse.py:216
/home/runner/work/openlibrary/openlibrary/openlibrary/catalog/marc/fast_parse.py:216: DeprecationWarning: invalid escape sequence \(
re_dates = re.compile('^\(?(\d+-\d*|\d*-\d+)\)?$')
openlibrary/plugins/upstream/account.py:416
/home/runner/work/openlibrary/openlibrary/openlibrary/plugins/upstream/account.py:416: DeprecationWarning: invalid escape sequence \.
if not (email and re.match('.*@.*\..*', email)):
```
> Fix DeprecationWarning invalid escape sequences

- openlibrary/plugins/openlibrary/js/index.js
There is no topNotice element on
/books/OL28775995M/Der_Todeskanal/manage-covers
or
/books/OL28775995M/Der_Todeskanal/add-cover
so there is no need to hide the element. This rule was copied across
from existing inline JS 55a6a39 but presumably relates to a time when
the Internet Archive header was rendered on these pages.
Fixes: #4665
> Drop redundant line

- Makefile
- docker/Dockerfile.olbase
Feature:
css: 34s -> 15s
components: 90s -> 20s
- NOTE: This will be a breaking change to all developers, since it touches the olbase file :/ Folks will need to run `docker-compose up --pull` to get the latest olbase (after this is merged). Let's merge this around the same time as a python version update or something to bundle the changes.
```sh
docker-compose run --rm -uroot home bash
```
```sh
apt-get install parallel
echo 'will cite' | parallel --citation 
make css # So fast!
make components # So snappier!
```
> Speed up make css and make components by ~2x using gnu parallel

- scripts/ipstats.py
- scripts/manage-imports.py
- scripts/solr_builder/README.md
- scripts/store_counts.py
Our cron jobs no longer need to rely on the defunct /olsystem/bin/olenv
> Remove references to /olsystem/bin/olenv

- openlibrary/plugins/openlibrary/js/carousels_partials.js
Addresses review notes from PR #4007
Removes conditional that checks `readyState` of the document.
This code is not loaded until the document is ready (evidenced [here](https://github.com/internetarchive/openlibrary/blob/5d00b71a745ceae062079842cc6c887191ce6b3a/openlibrary/plugins/openlibrary/js/index.js#L114)), making the `readyState` conditional redundant.
2. Using your browser's development tools, ensure that the call to `/partials` has been made successfully.  On success, the loading indicator animation will be hidden and the related works carousel  will contain a `div` with class `related-books`.
@jdlrobson 
@cdrini
> Remove carousel_partials.js load event

- openlibrary/components/LibraryExplorer.vue
- openlibrary/components/LibraryExplorer/components/BookCover3D.vue
- openlibrary/components/LibraryExplorer/components/BookRoom.vue
- openlibrary/components/LibraryExplorer/components/BooksCarousel.vue
- openlibrary/components/LibraryExplorer/components/Bookshelf.vue
- openlibrary/components/LibraryExplorer/components/FlatBookCover.vue
- openlibrary/components/LibraryExplorer/components/LibraryToolbar.vue
- openlibrary/components/LibraryExplorer/components/OLCarousel.vue
- openlibrary/components/LibraryExplorer/components/Shelf.vue
- openlibrary/components/LibraryExplorer/components/icons/SortIcon.vue
- openlibrary/components/LibraryExplorer/configs.js
- openlibrary/components/LibraryExplorer/lcc.json
- openlibrary/components/LibraryExplorer/utils.js
- openlibrary/plugins/worksearch/languages.py
- package-lock.json
- package.json
Add option to view covers without images; saves bandwidth, more accessible, and responding to feedback from survey.
- Depends on #4613 (and its deps); this is the diff you seek: https://github.com/internetarchive/openlibrary/pull/4613/files/13fbcfeeddcf22b39abf7d4a96d5f050fb564a6f..88b56b28aacd031c4115c7e10d49aedf97cab388
- The new style/colors are also applied for books without cover images.
> [library-explorer] Add text view option

- openlibrary/components/LibraryExplorer.vue
- openlibrary/components/LibraryExplorer/components/BookCover3D.vue
- openlibrary/components/LibraryExplorer/components/BookRoom.vue
- openlibrary/components/LibraryExplorer/components/BooksCarousel.vue
- openlibrary/components/LibraryExplorer/components/Bookshelf.vue
- openlibrary/components/LibraryExplorer/components/LibraryToolbar.vue
- openlibrary/components/LibraryExplorer/components/OLCarousel.vue
- openlibrary/components/LibraryExplorer/components/Shelf.vue
- openlibrary/components/LibraryExplorer/components/icons/SortIcon.vue
- openlibrary/components/LibraryExplorer/configs.js
- openlibrary/components/LibraryExplorer/lcc.json
- openlibrary/plugins/worksearch/languages.py
- package-lock.json
- package.json
- Closes #4362 
- Based of #4081 and #4608. This likely the diff you seek: https://github.com/internetarchive/openlibrary/pull/4609/files/b29c42f8e2747327090ee8e44bf5ee65064c4aae..6055423897f8e2d01042eb0d748737857c430a04
- Coordinates fetches so that fetches for things on the screen happen before things that are off screen
- To reduce memory usage, the number of off-screen carousels is now limited
- Reduce number of books on mobile devices
- Cleans up some broken LCC shelves
- Fixes carousels appearing blank in Chrome (#4362)
No visible changes (except perf!)
> [library-explorer] Perf tweaks/fixes

- openlibrary/components/LibraryExplorer.vue
- openlibrary/components/LibraryExplorer/components/BookRoom.vue
- openlibrary/components/LibraryExplorer/components/BooksCarousel.vue
- openlibrary/components/LibraryExplorer/components/Bookshelf.vue
- openlibrary/components/LibraryExplorer/components/LibraryToolbar.vue
- openlibrary/components/LibraryExplorer/components/OLCarousel.vue
- openlibrary/components/LibraryExplorer/components/Shelf.vue
- openlibrary/components/LibraryExplorer/components/icons/SortIcon.vue
- openlibrary/components/LibraryExplorer/configs.js
- openlibrary/plugins/worksearch/languages.py
- package-lock.json
- package.json
- Depends on #4607 for sorting fields
- Based off #4081 (This is the diff you seek: https://github.com/internetarchive/openlibrary/pull/4608/files/ab00389e8a98e51e1fa96e0fd1f8e29feefb7ebf..b29c42f8e2747327090ee8e44bf5ee65064c4aae )
- Some things still don't look right when sorting by shelf order, for the reasons mentioned in #4607 :/
- Also added option to set book label so that it matches sort
> [library-explorer] Add option to sort

- openlibrary/plugins/upstream/addbook.py
- openlibrary/plugins/upstream/models.py
Closes #2445
- Locally disable solr-updater to keep things from getting in solr: `docker-compose stop solr-updater`
- Useful testing links: http://localhost:8080/works/_autocomplete?q=OL1W ; http://localhost:8080/authors/_autocomplete?q=OL5A
@seabelis @LeadSongDog
> Entering an author/work ID into autocomplete will fetch from DB if missing from solr

- openlibrary/plugins/upstream/merge_authors.py
Closes #4225
Directly compose the [`web.seeother()`](https://github.com/webpy/webpy/blob/master/web/webapi.py#L156-L163) redirect URL to short circuit the database call.
> Fix merge authors with Unicode names

- openlibrary/templates/lib/nav_head.html
- static/css/components/header-bar.less
Closes #4444 
Fix
I have used the [checkbox hack](https://css-tricks.com/the-checkbox-hack/) to fix the toggle buttons of the mobile navbar menus. Also, removed the hover effect from the buttons, since they led to a not-so-friendly user interface.
1. Open OpenLibrary in development mode
2. Open the developer console and toggle to mobile view
3. Open the Browse menu/More options menu/Account dropdown
4. Click on it again to close it. 
I'm attaching a screencast for how it looks right now:
https://user-images.githubusercontent.com/52366674/106347861-a6c7a000-62e7-11eb-96fb-06e7cc33b7b0.mp4
> Removed hover effects and fixed mobile nav menus' toggle buttons

- openlibrary/i18n/README.md
Closes #3812
- Use home instead of web
- Use run instead of exec
- Use -uroot due to permission issues
Closes #
@jamesachamp
> Update i18n docker commands

- openlibrary/templates/admin/menu.html
https://openlibrary.org/admin/status does not exist but https://openlibrary.org/status does.
Closes #
> Admin menu: Fix the path to https://openlibrary.org/status

- openlibrary/plugins/openlibrary/js/SearchBar.js
Closes #4691
Fix broken thumbnails displayed in the dropdown when doing a search via the top search bar.
Fix author and work search.
Just in case, `alt=""` added if default image not available.
> Add default image for book cover and author in search dropdown

- openlibrary/plugins/importapi/code.py
Closes #
Allows some serials for which we have MARC records to be added to the catalog to enable lookup by `local_id` https://openlibrary.org/local_ids
This is a periodical / serial from the Claremont MARC data, one of the problem barcodes that was not recognised previously: 
10010417724
record data at:
marc_claremont_school_theology/CSTMARC1_multibarcode.mrc:63202416:5
It is now imported, with all volume barcodes present:
```
```
> Allow serials for scanning partner imports

- docker-compose.production.yml
Closes #4707
The root user should launch `cron-jobs` to avoid 
```
docker logs --tail=10 openlibrary_cron-jobs_1
cron: can't open or create /var/run/crond.pid: Permission denied
cron: can't open or create /var/run/crond.pid: Permission denied
...
```
> Fix failing cron-jobs in Docker

- openlibrary/core/lists/model.py
- openlibrary/macros/Profile.html
- openlibrary/templates/type/edition/view.html
- openlibrary/templates/type/list/view.html
Closes #4563 
A patch to prevent Lists from breaking when Works are merged -- Just In Time resolves Work redirects to the correct record.
> Fix redirects breaking list + list performance

- static/css/components/header-bar.less
- static/css/layout/v2.less
- static/css/less/z-index.less
Z-indexs are inherited so we need to set the header at a value
above the content area and make sure that the second row of items
and logo always appears below the dropdowns when open
There is no need for the z-index madness!
Fixes: #4685
Fixes: #4718
Closes #
> Simplify z-indexes in header

- openlibrary/tests/catalog/test_get_ia.py
- openlibrary/tests/catalog/test_utils.py
- openlibrary/tests/core/test_connections.py
- openlibrary/tests/core/test_fulltext.py
- openlibrary/tests/core/test_helpers.py
- openlibrary/tests/core/test_lists_model.py
- openlibrary/tests/core/test_olmarkdown.py
- openlibrary/tests/core/test_processors.py
- openlibrary/tests/solr/test_update_work.py
Starts to modernize Python syntax using [`pyupgrade  --py38-plus **/*.py`](https://github.com/asottile/pyupgrade) in our `openlibrary/tests` directory.  This utility will allow us to automate the removal of the `six` dependency and remove unneeded imports, syntax, etc.
Ensure that our automated tests continue to pass.
> pyupgrade  --py38-plus openlibrary/tests

- Makefile
- docker-compose.yml
- docker/Dockerfile.olbase
- docker/ol-web-start.sh
Closes #
This is being published to docker hub as `olbase:docker-test-olbase-optimization`. To test locally:
```sh
echo "FROM openlibrary/olbase:docker-test-olbase-optimization" | docker build -t "openlibrary/olbase:latest" -
docker-compose build
docker-compose up -d
```
> Remove some old dependencies from olbase

- openlibrary/plugins/worksearch/code.py
Feature. These are useful for things like carousels, where we might want them to shuffle regularly.
> Add random.hourly and random.daily sort options

- docker-compose.override.yml
- docker-compose.yml
Feature. This allows us to have multiple openlibrarys running from the same server, without having to modify any files!
> Make web port configurable via environment variable

- openlibrary/core/lists/model.py
- openlibrary/templates/lists/preview.html
This is making a lot of expensive requests to solr, and providing very minimal value.
Closes #3896
| Before | After | 
| --- | --- |
| ![image](https://user-images.githubusercontent.com/6251786/110182375-a33da200-7dda-11eb-95ac-803fc90657cc.png)  | ![image](https://user-images.githubusercontent.com/6251786/110182315-8c974b00-7dda-11eb-937a-96d9ab3184f1.png) |
@mekarpeles  @seabelis
> Improve user /lists page performance by remove top subjects

- conf/openlibrary.yml
Hotfix. Follow up to #4727 . Causing pages on the dev environment to error trying to hit fake auth servers.
> localhost:80 -> web:8080 in openlibrary.yml

- Makefile
- openlibrary/plugins/upstream/utils.py
Apparently these write to the same tmp file :/ The development builds haven't been that useful, so axing them to keep things fast.
This _must_ be merged before our next deploy.
Closes #4733
@cclauss
> Disable vue development builds due to concurrency bug

- .github/dependabot.yml
#3364 again now that we have dropped legacy Python
Reenable dependabot for Python dependencies.
> Reenable dependabot for Python dependencies

- Readme.md
Closes #4771 
Corrects a typo in https://github.com/internetarchive/openlibrary#developers-guide
it says "...refer the Developer's Quickstart Guide."  instead of "...refer to the Developer's Quickstart Guide."
> corrected a typo in readme

- Makefile
Aaaand this is why auto-merging is bad :P (Also: Why I need to go on holiday next week :D )  Continuations of #4749 
Vue was just building one component X times :( If you were lucky, it would be LibraryExplorer. Sometimes it would build HelloWorld 3 times :/
> Make vue builds run in sequence :( They must be stateful :(

- openlibrary/core/imports.py
Fixes #2316
Database table `import_item` may not exist on localhost so detect and log [`psycopg2.errors.UndefinedTable`](https://www.psycopg.org/docs/errors.html) and return a count of 0 or an empty list.
Is there a way to solve this with less code by creating an empty `import_item` database table?
Should we reduce or eliminate the logging?
Closes #
> Fix /admin/imports on localhost

- docker-compose.override.yml
- docker-compose.staging.yml
- docker-compose.yml
Subtask of #4423 that removes volume mounts from production deployments but keeps them in place for standing and localhost deployments.  The goal is to simplify production deployments and rollbacks.
> Remove OL and Infogami volume mounts from production

- openlibrary/core/lending.py
- openlibrary/plugins/upstream/borrow.py
Closes #4804
Fixes https://sentry.archive.org/sentry/ol-web/issues/10505/ which looks like it would be preventing patrons from performing various borrow operations on any book with utf8 encoded titles.
> URL encode redirect locations in headers on borrow 

- bundlesize.config.json
- openlibrary/macros/UserMetadata.html
- openlibrary/plugins/openlibrary/js/patron-metadata/index.js
- static/css/components/metadata-form.less
- static/css/less/colors.less
Closes #4781
This PR improves the book notes modal by nesting questions in collapsible sections, clearly dividing the book notes and observations sections, adding some additional details to the observations section, and making some styling changes.
Observations are nested using `<details>` elements, which are more a11y friendly than the [solution](https://github.com/Open-Book-Genome-Project/TheBestBookOn.com/pull/78) used in The Best Book On.
Toggling a details section doesn't resize the entire modal, only it's innermost div.  Colorbox's built in resize function was repositioning the modal lower on the page each time that it was called (regardless of the value of the `reposition` [setting](http://www.jacklmoore.com/colorbox/#setting-reposition)).  I've added a toggle handler to each …
> Improve book notes modal

- openlibrary/core/booknotes.py
Closes #4792 
Corrects KeyErrors that are thrown when an existing book note is updated.
KeyErrors were due to `work_id` not being present in the `vars` dictionary.
Attempt to update an existing book note.  If successful, you will see a JSON string with a success message on the `/notes.json` page.
@mekarpeles
> Fix BookNote update functionality

- Readme.md
I didn't see an issue about this. I can make one if needed.
This PR is just to improve documentation. There was a note in the readme about docker still being in active development. However, it linked to a close ticket and a label with no issues. As such, I don't think the note is needed anymore.
I'm not sure who the stakeholders are but if you do I would appreciate it if you tagged them.
> remove docker development note from readme

- scripts/deployment/are_servers_in_sync.sh
This utility script helps to ensure that the servers `ol-home0`, `ol-covers0`, `ol-web1`, and `ol-web2` have the same:
1. Git hash for /opt/olsystem
2. Git hash for /opt/openlibrary
3. Git hash for /opt/openlibrary/vendor/infogami
4. Git hash for /opt/booklending_utils -- NOTE: ol-covers0 does not need /opt/booklending_utils
5. Docker SHA for oldev:latest
This helps to determine if we have successfully completed all steps of `scripts/deployment/deploy.sh` and are ready to run `scripts/deployment/restart_servers.sh`.  A successful run looks like:
```
/opt/olsystem
ol-home0.us.archive.org
8dd5db642b42c3bda075487db10f1d1b1c043d3c
ol-covers0.us.archive.org
8dd5db642b42c3bda075487db10f1d1b1c043d3c
ol-web1.us.archive.org
8dd5db642b42c3bda075487db10f1d1b1c043d3c
ol-web2.us.archive.org …
```
> Add scripts/deployment/are_servers_in_sync.sh

- openlibrary/macros/SearchResultsWork.html
Closes #4883 
Fix book `name` from `URL` to `name`
Fix author `@type` from `Thing` to `Organization` 
I noticed that even changing `itemprop` from `name` to `URL` and back to `name` changes the URL domain, so I think we can go ahead with the solution???
@hornc
> Improve structured data for book name

- openlibrary/templates/work_search.html
- static/css/base/helpers-common.less
Closes #4625 
Fixed missing less facet. Added a new helper `.hidden-2` (we can use other names as well like `.hide-less-more`)
@jamesachamp
> Fix missing less facet

- openlibrary/plugins/openlibrary/js/ol.analytics.js
Works on #4596 
Follow up to #4860
refactor
Removed `.more_search` reference as there is no mention of it anywhere else in the code. Also discussed in #4860.
@jdlrobson
> Removed .more_search reference from ol.analytics.js

- openlibrary/core/helpers.py
Closes #4555
A second attempt after the solution proposed in #4557 proved to be too far-reaching and had to be reverted in #4591.
Convert a Nothing into an empty list before performing a json.dumps() on it to avoid TypeError: Object of type Nothing is not JSON serializable as described in #4555.
> Fix Nothing is not JSON serializable again

- openlibrary/plugins/upstream/account.py
Closes #4791 
As requested by a partner (Mark from our community who is developing a mobile reading experience for Open Library), adds json loans view
Some possible minor security implications
dev.openlibrary.org/account/loans.json
@cdrini, @bfalling
> adds a basic /account/loans.json endpoint

- openlibrary/catalog/add_book/__init__.py
- openlibrary/core/vendors.py
Hotfix. This was causing a security issue -- exposing sensitive ImportBot info when an error occurred.
> Hotfix: don't carry account variable around

- docker-compose.override.yml
- docker-compose.production.yml
- docker-compose.yml
- scripts/deployment/restart_servers.sh
- tests/test_docker_compose.py
Refactor to remove some no longer needed deploy steps now that we no longer mount the repo.
- Profiles let us simplify the `up` commands needed for each searver
- Since we're no longer using volume mounts, we no longer need to `down` before we `up`! Docker should automatically detect that oldev:latest has changed, and restart the right things.
- Also, no longer need `make i18n` since the built i18n files are in the image.
- Move dev only services to docker-compose.override.yml ; this makes things _way_ less error prone - it's now much harder to accidentally deploy a db service to prod.
- If a `profile` is not specified for a service, that service is _always_ started! Don't want that. Added a test to make sure no one accidentally does this.
1. Added a `profiles: ["foo"]` to web in …
> Use docker-compose profiles + cleanup old volume-mount cludges

- openlibrary/core/fulltext.py
- openlibrary/core/helpers.py
- openlibrary/data/dump.py
- openlibrary/plugins/upstream/addbook.py
- openlibrary/plugins/upstream/borrow.py
- openlibrary/plugins/upstream/code.py
- openlibrary/plugins/upstream/utils.py
- openlibrary/solr/solrwriter.py
- openlibrary/tests/core/test_fulltext.py
Manually remove uses of `six.PY2` and `six.PY3` from the codebase now that we have dropped support for legacy Python.
In later PRs we can use [`pyupgrade`](https://github.com/asottile/pyupgrade) to automatically remove other uses of the `six` module (like ~#4736~ and #4743) but it is better to first manually remove the uses of `six.PY2` and `six.PY3`.
> Remove uses of six.PY2 and six.PY3

- openlibrary/plugins/upstream/utils.py
Closes #4942
hotfix
Just added a '.' to the string used method looking for 'item' elements in the XML on line 748.  
Tested on local, so I'm not sure if this fix breaks anything on production.
> Fix for absolute path bug

- docker-compose.override.yml
- docker-compose.production.yml
- docker-compose.yml
These will let us easily let us start a specific version.
Work towards #4830 
```
$ docker-compose config | grep image
WARNING: The HOSTNAME variable is not set. Defaulting to a blank string.
image: oldev:latest
image: postgres:9.3
image: oldev:latest
image: oldev:latest
image: memcached
image: olsolr:latest
image: oldev:latest
image: oldev:latest
```
```
$ OLDEV_TAG=333 docker-compose config | grep image
WARNING: The HOSTNAME variable is not set. Defaulting to a blank string.
image: oldev:333
image: postgres:9.3
image: oldev:333
image: oldev:333
image: memcached
image: olsolr:latest
image: oldev:333
image: oldev:333
```
@cclauss
> Add OLDEV_TAG environment variable

- openlibrary/api.py
- scripts/manage-imports.py
The admin interface for Import logs all failures as `internal-error`
but the API is providing a specific reason, e.g.: 
`augsburghistoric0000unse {"success": false, "error_code": "item-not-book", "error": "Item rejected"}`
This PR attempts to capture and store the error-code from the HTTP response so we can get a better idea of why some of these imports are failing.
I'm not sure how to test this Import Bot script properly. I don't know that import bot can be run locally.
> Importbot -- log actual API error responses

- .github/workflows/python_tests.yml
We don't want _all_ our CI to break on an infogami update we haven't adopted yet.
P0. Our CI is all going fail.
@cclauss
> Make python CI not use infogami master

- openlibrary/templates/type/edition/view.html
As per Community Call discussion
Added work-subtitle in the topline. For all the pages (edition + work).
Do we want it only on the work page???
@seabelis
> Add work subtitle in topline of bookpage

- openlibrary/plugins/upstream/tests/test_models.py
`assert repr(work.any_attribute) in ('', '<Nothing>')` to align with internetarchive/infogami#151.
Closes #
> repr(Nothing()) —> "<Nothing>", not empty str

- openlibrary/templates/lists/home.html
Closes #4633 
Combined the `cover` Div and `name` Div because the cover image for a list is a book cover of the book present in that list but the alt attribute says alt="Cover of: listname" and according to @bpmcneilly the alt text needs to inform users where they will go if they activates the link. So the best solution was to bring the cover inside the name and make the `alt=""`.
**For more Reference:** https://github.com/internetarchive/openlibrary/issues/4633#issuecomment-783681715
@bpmcneilly
> Fix Lists Page Images Accessibility

- static/css/components/edit-toolbar.less
Fixes part of #4940 
This makes it so that the activity indicators in the [edit-toolbar](https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#edit-toolbar) are not cutoff.
I verified this works correctly on FF and Chrome for Mac.
I also used the dev tools in FF and Chrome to confirm that in the mobile view it looks fine.
The only edge case that I could come up with that might be why this css exists in the first place is a very long username.
This change to the css does have an impact on how very long usernames appear. Though, I'm not sure if the difference matters that much. See screenshots bellow.
| --- | --- | 
| ![image](https://user-images.githubusercontent.com/921217/113247189-37721c00-9256-11eb-90f6-6114ab94a757.png) | …
> remove overflow hidden from edit tools

- static/css/components/mybooks-list.less
Addresses first part of #4974
hotfix
Nothing remarkable here.
1. Create a list
2. Add a description with a very long word (or URL)
3. Visit the first three pages listed in the PR that are listed as issues to see that the text now longer wraps on mobile and desktop.
<details>
<summary>Spoiler</summary>
</details>
> Fix list description not wrapping long strings

- openlibrary/core/booknotes.py
- openlibrary/core/models.py
- openlibrary/core/schema.sql
- openlibrary/macros/UserMetadata.html
Adds `edition_id` to the `booknotes` table's primary key, enabling patrons to make notes for specific editions of a work.  
Also corrects a bug that was causing book notes submissions to fail.
`form` attribute was removed from book notes submission button.  This was preventing the form from being submitted.
`edition_id` defaults to -1 for work-level book notes.
The following queries should be executed before merging this code:
```
ALTER TABLE booknotes ALTER COLUMN edition_id SET DEFAULT -1;
UPDATE booknotes SET edition_id = -1 WHERE edition_id IS NULL;
ALTER TABLE booknotes DROP CONSTRAINT booknotes_pkey;
ALTER TABLE booknotes ADD PRIMARY KEY (username, work_id, edition_id);
```
1. Navigate to a book page for a work that has several editions.
2. Open the …
> Make BookNotes edition-level

- bundlesize.config.json
- openlibrary/core/observations.py
- openlibrary/plugins/openlibrary/api.py
- openlibrary/plugins/openlibrary/js/patron-metadata/index.js
- static/css/components/metadata-form.less
Closes #
Observations are now POSTed to the server every time an input is checked or unchecked in the book notes modal.  A section-level submission indicator is displayed in order to notify patrons of the submission status.
Details sections in observations form are also now open by default.
2. Open the book notes modal.
3. Click on any observation radio button or checkbox.
4. Ensure that you receive a success message.
5. Refresh the page.
6. Open the modal again, ensuring that the previously selected radio button or checkbox is selected.
Successful submission:
Failed submission:
**Note:** Timeout added in above examples to better show the pending indicator.
@mekarpeles 
@cdrini
> Remove submit button for observations in book notes modal

- openlibrary/plugins/inside/code.py
Closes #4999 . Fix ; this was not converting the string `i.limit` to an int.
@waldenn
> Fix /search/inside.json limit + rm unreachable code

- scripts/deployment/restart_servers.sh
Fixes #5007
Related to #4936
Correct the docker-compose command and properly set the ___remote___ hostname.
@cdrini  @dhruvmanila
Closes #
> fix: restart_servers.sh for docker-compose --profile and $HOSTNAME

- openlibrary/data/dump.py
Related to #4621
Should we read stdin as bytes?!?  https://stackoverflow.com/questions/32282448/read-stdin-as-binary
> Fix split_dump() to read in str, not bytes

- openlibrary/plugins/upstream/tests/test_models.py
This PR must land just _before_ internetarchive/infogami#166 (so its tests will pass) and then internetarchive/infogami#166 should land because the two PRs are linked and tests will fail in one repo or the other until both are landed.
> Define repr(Nothing()) and str(Nothing())

- openlibrary/core/stats.py
- setup.py
Completes the work started in #1486 and #2892 to remove [`pystatsd`](https://pypi.org/project/pystatsd/) which has not been released since 2013 with the more up-to-date [`statsd`](https://pypi.org/project/statsd/). 
This PR does not change the log names just in case those names are relied on elsewhere.
> Remove pystatsd in favor of statsd

- docker/Dockerfile.oldev
Fix. A relative path will cause problems when we set the working directory to something other than `/openlibrary`
> Make oldev entrypoint absolute path

- openlibrary/solr/update_work.py
- openlibrary/tests/solr/test_update_work.py
In new solr, key:/works/OL1W returns all the documents, with the matching document first. This seems like it's causing our `<delete>key:/works/OL1W</delete>` update queries to delete all documents! <delete><id>/works/OL1W</id></delete> seems to be recommended way now.
Note this works in Solr 3 as well, so just a refactor.
Extracted from #4337
> Make delete queries solr8 compatible

- .github/workflows/javascript_tests.yml
- .github/workflows/python_tests.yml
We will add cache to our Python tests which will store the entire virtual environment in which all our dependencies are installed.
The key for the cache will be the OS version and the hash of all the requirements.txt files (as the glob suggests). This means that if either the OS or any of the requirements file changes, the cache will be automatically updated.
Continuing from https://github.com/internetarchive/infogami/pull/161
Closes #
> feat: Add cache to GitHub actions

- openlibrary/plugins/openlibrary/js/graphs/plot.js
Closes #4925
Fix
A large z-index value needed to be added to the chart labels so that they are visible over the chart if we hover over the bars on the chart. This has been done inside the [`showTooltip()`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/js/graphs/plot.js#L55) function inside `plot.js` where the CSS properties of the label are defined.
Changes can be tested on visiting localhost after adding the changes. Also, running `npm test` shows all test suites as passed.
> Added z-index to chart labels to show them on top of chart on hover

- openlibrary/components/LibraryExplorer/components/Shelf.vue
Closes #5034
Fix keyboard focus on bookshelf in Library Explorer.
Focus first on shelf-label, then on shelf-carousel.
@bpmcneilly
> Accessibility/Library Explorer bookshelf keyboard focus fix

- .github/workflows/python_tests.yml
- Makefile
Fix. GitHub Actions uses `CI` instead of `CONTINUOUS_INTEGRATION`. Also GHA isn't finding master for `lint-diff` for some reason :/
- Useful list of all GHA env vars: https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables
https://github.com/internetarchive/openlibrary/pull/5049/checks?check_run_id=2348433992
@cclauss @dhruvmanila
> Fix lint-diff in GHA and fix CI var for make lint

- .github/workflows/python_tests.yml
We were getting errors on our workflows when trying to initialize the venv; it was complaining about `No such file or directory: '/home/runner/openlibrary_python_venv/bin/python'`. Disabling venv to fix master CI + unblock PRs.
Hotfix. We can switch back at our leisure once we figure out what went wrong :+1:
@cclauss @dhruvmanila @Yashs911
> Remove venv in python_tests

- bundlesize.config.json
- openlibrary/core/observations.py
- openlibrary/macros/EditionNavBar.html
- openlibrary/macros/UserMetadata.html
- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/plugins/openlibrary/js/patron-metadata/index.js
- openlibrary/templates/lists/widget.html
- openlibrary/templates/observations/stats_component.html
- openlibrary/templates/type/edition/view.html
- static/css/base/headings.less
- static/css/components/observationStats.less
- static/css/page-book.less
Closes #4867
Creates a new component for book pages which displays patron observation statistics for the work.  A new "Reader Observations" tab has been added above the editions table to provide quick access to the new component.
The book notes modal, `UserMetadata.html`, has been modified to accept a unique ID as a parameter.  This allows multiple modals to be displayed on a single page.  This may not be absolutely necessary for this PR, but it will be needed for the upcoming consolidated book notes view PR.
A modal link is included at the bottom of the new component, prompting patrons to leave their own observations about the work.  This link opens the login page for folks who are not already logged in.
Observation counts will not include deleted observation types and values.  The …
> Create aggregate observations component for book pages

- conf/openlibrary.yml
- openlibrary/core/observations.py
Sets default expiry time of one day for observations cache entries.
If the `observation_cache_duration` configuration is missing from `openlibrary.yml`,  `get_observations()` calls fail because `None` is being passed as the cache expiry time.  Setting a default time avoids this issue.
1. Remove the `observation_cache_duration` entry from `openlibrary.yml`.
2. Log in with an account that is a member of usergroup `beta-testers`.
3. Navigate to a book page and attempt to open the book notes modal.  If the modal is displayed, the `get_observations()` call has been successfully executed.
@mekarpeles
> Set default cache expiry

- openlibrary/i18n/__init__.py
- openlibrary/i18n/cs/messages.po
- openlibrary/i18n/de/messages.po
- openlibrary/i18n/es/messages.po
- openlibrary/i18n/fr/messages.po
- openlibrary/i18n/hr/messages.po
- openlibrary/i18n/ja/messages.po
- openlibrary/i18n/messages.pot
- openlibrary/i18n/pl/messages.po
- openlibrary/i18n/te/messages.po
- openlibrary/i18n/test_po_files.py
- openlibrary/templates/covers/add.html
- openlibrary/templates/lists/home.html
Fix. This prevents translations being added that could break the UI.
- Currently annoying to run for a specific language :/ Should refactor i18n-messages script to be locale specific, and somehow call the pytests from these for the provided locale. Thoughts for a future PR.
- Disabled tests for cs, hr, pl; they had errors I couldn't resolve. Will create issues for domain experts. (Although I'm wondering if I should first do a `i18n update`... That'll shuffle things around a bunch, and might even delete some strings).
@lephemere
> Add html/python cstyle string tests for po files

- scripts/deployment/deploy.sh
A trailing slash on the source changes this behavior to avoid creating an additional directory level at the destination. You can think of a trailing / on a source as meaning "copy the contents of this directory" as opposed to "copy the directory by name", but in both cases the attributes of the containing directory are transferred to the containing directory on the destination. In other words, each of the follow‐ ing commands copies the files in the same way, including their setting of the attributes of /dest/foo:
rsync -av /src/foo /dest
rsync -av /src/foo/ /dest/foo
Closes #
> Fix rsync in deploy.sh

- openlibrary/templates/lists/home.html
Closes #5069 
Fix broken list-name text
> Fix broken list name

- openlibrary/plugins/openlibrary/code.py
- openlibrary/templates/site/head.html
This is a prerequisite for #5013 to update https://github.com/internetarchive/openlibrary/blob/9a0a6e41e3a524d67cf6cce82aaccc6281407b57/openlibrary/templates/site/head.html#L4 so that it generically uses:
`<html xmlns="http://www.w3.org/1999/xhtml" lang="$get_lang()">`
> adding `lang` to html template globals

- openlibrary/templates/type/list/view.html
Closes #5004 
Fix
In summary, we were using headers like this:
- H1
- H3
- H6
- H6
- H6
- H2
Now, we're using them like this:
- H1
- H2
- H3
- H3
- H3
- H2
Which is better for user accessibility (details in #5004)
Since these elements are only used on this page and not shared there should be no risk of breaking other pages.
Check the html on a page to see that it is using the correct headers.
@bpmcneilly
> make header levels more accessible

- openlibrary/templates/books/custom_carousel.html
- openlibrary/templates/lists/widget.html
Closes #4632 
Fixes broken alt tag for list widget cover image.
Added alt="Book Cover" for Custom Carousel Books
@bpmcneilly
> Fix Individual Subject Page Images Accessibility

- static/css/components/buttonCta--js.less
- static/css/components/buttonCta.less
- static/css/page-book-widget.less
This PR updates the 'Join Waitlist' (`class="cta-btn--unavailable"`) & a few other related classes to ensure that they have sufficient color contrast.
The current colors involve `@white` text (`#ffffff`) on an `@orange` background (`#ffa238`). These two colors form a color contrast ratio of 2.004:1, which is below the 4.5:1 needed for normal sized text.
This PR updates the background colors for a few of the "waitlist" or "unavailable" content to appear in the existing `@red` less variable. Using this color, (`#de351b`) will have a contrast ratio of 4.534:1. On occasion the darker shade `@dark-red` (`#bf3722`) was used, and this creates a contrast ratio of 5.548:1.
The biggest issue with this PR is the visually breaking nature of the color change. In researching other colors that would …
> Unavailable color contrast

- openlibrary/plugins/worksearch/code.py
Closes #4996
Fix following filters in search API:
- author_key
- subject_facet
- person_facet
- place_facet
- time_facet
- first_publish_year
- publisher_facet
- language
- public_scan_b (EDIT: Default parameter added to mimic standard search  behaviour)
One misspelled string in `build_q_list` function (`contributor`).
Default non-working filters to list value in `web.input()`.
Solr logs with query `q=a&mode=everything&language=tel`:
- Web interface search giving `fq=language:"tel"`:
> INFO: [] webapp=/solr path=/select params={fl=key,author_name,author_key,title,subtitle,edition_count,ia,has_fulltext,first_publish_year,cover_i,cover_edition_key,public_scan_b,lending_edition_s,lending_identifier_s,language,ia_collection_s&fq=type:work&fq=language:"tel"&q.op=AND&start=0&rows=20&spellcheck=t …
> Fix search API non-working filters

- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/plugins/openlibrary/js/search.js
- openlibrary/templates/work_search.html
Closes `openlibrary/templates/work_search.html` point from #4474
Move inline JavaScript from work_search.html template to index.js and search.js.
Search Facets:
- expand available filter item list in the `Zoom in` area with the `more` button
- reduce available filter item list in the `Zoom in` area with the `less` button
- verify bullet between `more` and `less` button is hidden when `less` button is hidden
Admin Timing:
- Connect as admin
- Verify that `Read API call took XX seconds` message appears at the bottom of the search results
@jdlrobson
> Refactor/Move inline js from work_search template

- openlibrary/templates/type/user/view.html
Address for `openlibrary/templates/type/user/view.html`  #4474 
The JS that was there has no impact on the desktop view, which I tested extensively. I also checked on mobile and didn't see any difference.
You can try dropping in some code like:
```
console.log(Array.from($('ul#listResults span.imageLg img')).map(img=>img.height));
$('ul#listResults span.imageLg img').removeAttr('height');
console.log(Array.from($('ul#listResults span.imageLg img')).map(img=>img.height));
```
Then you can see that the image height part at least was not doing anything.
The other line for padding zero also didn't seem to have an effect since with JS disabled padding right is already zero.
Check if the lists on the user page look ok.
@jdlrobson
> remove inline js from user view

- docker-compose.override.yml
- docker-compose.production.yml
- docker-compose.staging.yml
- docker-compose.yml
- docker/Dockerfile.olbase
- docker/Dockerfile.oldev
- scripts/deployment/deploy.sh
As described in #5072 . ~Depends on #5082~
- olbase now creates the dirs needed by coverstore/etc
- No Dockerfile exposes ports anymore, since that's done via docker-compose
- New environment variable, `OLIMAGE` can be used to override the image (eg for rollbacks we'd be able to do `OLIMAGE=openlibrary/olbase:SHA docker-compose ...`
- deploy script now no longer needs to gzip images/etc; each node just pulls the latests olbase from docker hub
- deploy.sh now uses GNU parallel to make things faster (waiting for these downloads sequentially would be annoying).
- Test doing a deploy -- This will likely need to happen after merging :/
@mekarpeles
> Use olbase on prod instead of oldev

- .github/workflows/python_tests.yml
Closes #
Fixes the problem where the appropriate Python executable was not found.
When we create a virtual environment using `python3 -m venv ... `, it creates a bin directory which contains symlink to the original Python interpreter. In our case, actions/setup-python upgraded the Python version from `3.8.8` -> `3.8.9` which removes the old version from the tool cache (where it stores the files) and only keeps the latest one. So, when the virtual environment was restored using the cache, the symlink was broken and thus the error.
Quoting from https://github.com/actions/setup-python#available-versions-of-python (Point 1.3):
> If 3.8.1 is installed for example, and 3.8.2 is released, expect 3.8.1 to be removed and replaced by 3.8.2 in the tools cache.
@cdrini @cclauss
> fix(actions): Use exact Python version and update cache key

- docker-compose.production.yml
- docker-compose.yml
- docker/ol-solr-updater-start.sh
- openlibrary/solr/update_work.py
- scripts/new-solr-updater.py
Progress towards #3317 
- Refactor new-solr-updater to use FnToCLI + Remove some globals
- Add new option for setting solr_base_url via CLI
- Add solr-updater service pointed at solr1
- A refactor to simplify `new-solr-updater.py` and remove all the parse args.
- Add some new options to `new-solr-updater.py`
- Add `solr8-updater` service.
- Not tested 😬 ~Should be able to toss it onto staging with volume mounts to see if it works...~ Nope. Too annoying.
- In order to test this service, since there are code changes, I'd need to either rebuild olbase with the new code, or use volume mounts to get the new code. Don't want to use volume mounts on prod... Testing has volume mounts, but don't want to transfer secrets to testing server. Since the compose file is fully functional, the only things …
> Clean up new-solr-updater + add solr8-updater service

- static/css/legacy-wmd.less
Closes #4974
Fixes the markdown preview so long strings of text wrap to stay inside their parent.
This css will be applied to pages that use the markdown previewer. These can be found by looking a files using the class `markdown`. 
<details>
<summary>Here is a list of those files</summary>
Page in screenshot:
https://github.com/internetarchive/openlibrary/blob/a61250b4ade345430e406d99eb04ae102713899a/openlibrary/templates/type/list/edit.html#L33 
Has a width manually set
https://github.com/internetarchive/openlibrary/blob/a61250b4ade345430e406d99eb04ae102713899a/openlibrary/templates/admin/case.html#L97
Has a width manually set
https://github.com/internetarchive/openlibrary/blob/a61250b4ade345430e406d99eb04ae102713899a/openlibrary/templates/admin/case.html#L112 …
> add markdown preview word wrap

- CONTRIBUTING.md
This improves the documentation as mentioned in the [April 20th community call](https://docs.google.com/document/d/1YXh4SvaY9kyI-IIYnVQPDQIeDHoDcvvqvyHfkkTfPX8/edit#heading=h.rl2g3f40rflw).
Links to info on how we handle github issues and labels.
> add links to github workflow and label docs

- openlibrary/core/bookshelves.py
Add edition_id=edition_id to update method at line 189
Closes #4931
fix
Modifies the update call in the add method to update the edition_id field in addition to the bookshelf_id. In other use cases, where the edition_id is empty or unchanged, no behavior change will be seen. 
Add /books/OL24948639M/ to your reading log.
Submit a POST to  https://openlibrary.org/works/OL460810W/bookshelves.json with an add action and a specific edition_id: {'action':'add', 'redir':false, 'bookshelf_id':1, 'edition_id':'/books/OL7656518M', 'dont_remove':true}
If working correctly, the edition of the book on your reading log should change in the UI.
@mheiman
@mekarpeles
> Update add method in bookshelves.py to address issue #4931

- openlibrary/macros/LoanStatus.html
Closes #4715
[feature]
Simple Fix
Navigate to any borrow-only book to see the added Search Inside box underneath the Preview button.
@finnless @mekarpeles
> Closes #4715 adding Search Inside box to printdisabled books

- static/css/components/carousel.less
- static/css/components/home.less
Closes #4898 
- Fix partially hidden outlines.
- As mentioned here https://github.com/internetarchive/openlibrary/pull/4255#pullrequestreview-564799249 currently it is impacting the book covers (as for 6 books the width changes from 128px to 124px) but after https://github.com/internetarchive/openlibrary/pull/4926 the max-width will become 1060px and all bookcovers will have 130px width with some margins left so adding `padding: 2px;` will not change the width.
Tested on staging as currently its max-width is 1060px 
@bpmcneilly
> Fix Home Page Keyboard Accessibility

- openlibrary/templates/lists/snippet.html
- static/css/components/mybooks-list.less
- static/css/components/search-result-item.less
Closes #4794 
According to me, we should remove the No description from both the lists page and user lists.
**Before:**
**Now:**
@mekarpeles
> Fix Bad UI of User Lists

- openlibrary/templates/lists/widget.html
Closes #3630 
Display the patron's list contatining a particular work underneath `Want to Read Button`.  
This will help patron easily remove books from list already added.
Added `id = "list-lists"` alongwith `class = "listsLists"` in Line 296. This is because `class = "listLists"` is also used in Line 233. And we need to insert different lists in both `ul`. Hence separate query was needed.  
Added a new parameter `user_key`  to `render_widget_add`.  
Apart from that, can modify the name of `id` and renderer in Line 233 from `alreay-lists` [It sounds ambiguous].
Open [http://localhost:8080/books/OL7037695M/The_complete_works_of_Mark_Twain](http://localhost:8080/books/OL7037695M/The_complete_works_of_Mark_Twain)  
The changes can be seen beneath `Want to Read Button`.
@mekarpeles …
> Display lists patron's list in which the book is already added.

- static/css/components/buttonCta--js.less
- static/css/components/buttonCta.less
- static/css/page-book-widget.less
Reverts internetarchive/openlibrary#5085 . Preparing for a deploy, and this is just too red for me 😅 Makes the button look dangerous, like "Delete all files?" or something. Let's explore some of @bpmcneilly 's other options :+1:
> Revert "Unavailable color contrast"

- openlibrary/macros/UserEditRow.html
- openlibrary/plugins/openlibrary/js/edit.js
- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/templates/type/user/edit.html
- package.json
Addresses `openlibrary/templates/type/user/edit.html` for  #4474 with refactor
The function looks like it was originally made to be very generic but is only used on this one page.
I refactored it to simplify things a bit while moving code out.
Try adding / removing multiple websites from a user profile
https://user-images.githubusercontent.com/921217/116025599-9aa06580-a5ec-11eb-86c9-04f3eb27b109.mov
@jdlrobson
> remove inline js for user edit page

- openlibrary/plugins/openlibrary/js/index.js
No issue opened. Linked to #4474 and #4661.
**Hotfix**
`length` call on `getElementById()` leads to JS error when id not found.
https://github.com/internetarchive/openlibrary/blob/a6da21f277032f6c016219e9d1ece671f401e1d6/openlibrary/plugins/openlibrary/js/index.js#L174
@jdlrobson
> Hotfix/JS error from index.js 

- openlibrary/components/LibraryExplorer/components/LibraryToolbar.vue
Closes #5037
Fix keyboard navigation issue on bottom floating controls panel in Library Explorer.
CSS update tested on Firefox 87 and Edge 89.
@cdrini
> Library Explorer accessibility/Enable keyboard navigation on floating controls panel

- openlibrary/macros/Pager.html
- openlibrary/plugins/openlibrary/code.py
No associated issue.
Fix pagination when number of results is a multiple of 20.
See this [OL Search](https://openlibrary.org/search?q=incal&mode=everything&page=2&lang=eng) for example.
Generate search giving Nx20 results.
> Correct pagination generation

- openlibrary/plugins/upstream/addbook.py
@seabelis wants the ability to bless patrons who are not yet in the librarians group (but who are trusted for some librarian tasks) to be able to skip recaptcha, since they've been manually vetted. 
uses the account.has_tags function to check whether patron is `trusted-user`
This needs to go on staging and needs to be tested:
* librarians, admins, and trusted users should not see captcha
* others should see recaptcha unless they meet other pre-existing exemptions
> Exempt trusted-users from recaptcha

- openlibrary/solr/update_work.py
Solr 8 was complaining about Content Type missing (likely because `urlopen` was making a POST request). Switched it a regular `requests.get`.
- The first commit is semi-patch deployed; I patch deployed a version where I explicitly set `headers` as well, but don't believe that's necessary.
> Fix update_work bug with solr8

- openlibrary/templates/lib/history.html
Closes #
* Uses the more specific / book focused CS1 template https://en.wikipedia.org/wiki/Template:Cite_book
* Adds some i18n using existing strings
Why is the Wikipedia Citation buried in the History template? It was hard to locate. The "other data formats" tools are positioned _near_ the History section, but functionally they have nothing to do with History. I don't want to move anything as part of this small PR, but it would make sense to split them out into their own UI component / template at some point.
**EDIT** I found the commit where it was moved https://github.com/internetarchive/openlibrary/commit/519b4e7dbad27bb997973403b9b99de377fa1cdd -- makes technical sense to move from where it was, but conceptually it should be separate from History.
I'm deliberately choosing to not …
> Use the specific Cite book Wikipedia template for citations

- openlibrary/templates/search/inside.html
Efforts towards i18n - #791
Add i18n support for title in search/inside template.
Fix escaped html tag.
**Before:** No hits message with `strong` tag escaped
**After:** No hits message with escaped query and strong format
@cdrini
> Add i18n support to search/inside template

- openlibrary/templates/books/edit.html
- openlibrary/templates/books/edit/edition.html
- openlibrary/templates/books/edit/excerpts.html
- openlibrary/templates/books/edition-sort.html
- openlibrary/templates/covers/book_cover.html
- openlibrary/templates/covers/book_cover_single_edition.html
- openlibrary/templates/covers/book_cover_small.html
- openlibrary/templates/covers/book_cover_work.html
- openlibrary/templates/covers/change.html
- openlibrary/templates/lists/preview.html
- openlibrary/templates/lists/snippet.html
- openlibrary/templates/lists/widget.html
- openlibrary/templates/search/advancedsearch.html
- openlibrary/templates/search/lists.html
Efforts towards i18n - #791
Add i18n support for message in several templates:
- Book edit:
- books/edit.html
- books/edit/edition.html
- books/edit/excerpts.html
- books/edition-sort.html
- Cover `title` and `alt` attributes + rationalization:
- covers/book_cover.html
- covers/book_cover_single_edition.html
- covers/book_cover_small.html
- covers/book_cover_work.html
- lists/preview.html
- lists/snippet.html
- lists/widget.html
- Cover management:
- covers/change.html
- Search:
- search/advancedsearch.html
- search/lists.html
@cdrini
> Improve i18n support on templates

- openlibrary/templates/observations/stats_component.html
- static/css/components/observationStats.less
Closes #
This PR ensures that the observation statistics component only displays data if two or more people have submitted observations for a book.
Also, hard-coded strings in this component have been replaced with i18n strings.
This will cause a merge conflict with #5089.  I can rebase once either PR is merged.
Before deploying to testing, locate a book that only one patron has reviewed.
After deployment, while logged in as a beta-tester:
1. Navigate to the page that you previously identified and ensure that no observations are present in the component.
2. Navigate to a page where two or more people have submitted reviews, ensuring that the observations *are* present in the component.
@mekarpeles
> Observation statistics component improvements

- static/css/components/home.less
Closes part of #2380
This PR addresses the second part of the issue related to the stats charts at the bottom of the homepage:
> Fix the <a> link styling so that there isn't a little tail of underline extending to the left of the chart.
Turns out that the fix was not related to the `<a>` tag at all but to an extra 5px of padding on the `chartShow` div.  See [this screen recording](https://www.loom.com/share/07766921e4654660b82e6288ad291ef5) that shows the charts before and after removing padding.
UPDATE: To compensate for the lost padding in terms of indentation, I added a margin.  Thanks @Yashs911 !
1. Visit the homepage
2. Scroll to the bottom and examine the stats charts
3. None of them should have a little grey tail sticking out of the left side
The docker image doesn't have any stats …
> Fix set div padding to 0 to remove stats graph underline tail

- openlibrary/accounts/model.py
- openlibrary/plugins/upstream/account.py
The values for notifications (mailing lists) must be kept in sync with the values in
https://git.archive.org/ia/petabox/blob/master/www/common/MailSync/Settings.inc#L29-30
Currently, per the fundraising/development team, the announcements checkbox on signup forms should map to BOTH `ml_best_of` and `ml_updates`
> update Internet Archive mailing lists to match new values in petabox

- openlibrary/components/LibraryExplorer/components/Shelf.vue
Linked to #4908
Fix keyboard focus on subsection list in Library Explorer.
Focus first on subsection list when opened, then on shelf-carousel.
<details><summary>Original keyboard focus order</summary>
</details>
<details><summary>Modified keyboard focus order</summary>
</details>
@bpmcneilly
> Accessibility/Library Explorer subsection list keyboard focus order fix

- static/css/components/carousel.less
This PR slightly darkens the author name when a book cover is not present (`.carousel__item__blankcover--authors`) from the `@grey` variable (`hsl(0, 0%, 40%)`) to `@dark-grey-two` which is a slightly darker grey at `hsl(0, 0%, 35%)`.
The blank book cover background (`.carousel__item__blankcover`) uses `@lighter-grey` (`hsl(0, 0%, 87%)`). On this background color, the `@grey` text has a color contrast ratio of 4.23:1 while the `@dark-grey-two` text has a contrast ratio of 5.16:1. The minimum color contrast ratio for normal sized text should be 4.5:1.
- Verify the colors have adjusted appropriately, and that a color contrast ratio of at least 4.5:1 exists between the text & background color.
- [WCAG Success Criteria 1.4.3, color contrast …
> Ensuring Color Contrast for Author Names When Cover Is Not Present

- openlibrary/plugins/openlibrary/js/edit.js
- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/templates/books/edit/web.html
- package.json
Closes `openlibrary/templates/books/edit/web.html` point from #4474
Move inline JavaScript from books/edit/web.html template to index.js and edit.js.
Fix `link-errors` message not being displayed.
Open a work edit page and test the following in the `Links` section:
- Click `Add Link` with no link name entered => Name error message displayed
- Enter a name and click `Add Link` with no link url or 'http://' entered => Url error message displayed
- Enter a name and url and click `Add Link` => No error message
@jdlrobson
> Refactor/Move inline js from books/edit/web template

- openlibrary/core/cache.py
Closes #5156 
Fixes deprecation warnings in Python 3.10
> Use current_thread and access name attribute directly instead of deprecated access in Python 3.10.

- openlibrary/plugins/upstream/borrow.py
Fixes Search Inside to perform actual archive.org search inside rather than first trying to invoke a borrow
Related to #5142
> fixing search inside redirects

- static/css/components/buttonCta--js.less
- static/css/components/buttonCta.less
- static/css/less/colors.less
This PR is a follow up to the discussions on the closed / reverted #5085
After talking through color options this PR adjusts the previously existing orange to the burnt sienna color (`#C74405`). For these element's hover effect & `.cta-btn__badge` content, the `darken()` function is used to render the background as an even darker brown color (`#632102`).
Same as in previous PR, all color contrast for regular sized text should be at least 4.5:1. The default color, `#C74405`, has a color contrast ratio of 4.93:1 on the default white (`#ffffff`) text. The darkened version `#632102` has a contrast ratio of 12.01:1 on the white text.
Same as previous versions of this:
- Locate a book that is unavailable or otherwise unused
- Alternatively, take a book with `class="cta-btn cta-btn--available …
> Updating "Unavailable" Link Colors to "Burnt Sienna"

- openlibrary/templates/search/sort_options.html
- openlibrary/templates/type/author/view.html
- openlibrary/templates/work_search.html
- static/css/legacy.less
Closes #4662 
Move the sort options code to a new file (sort_options.html in template/search)
**Blockers:**
1. On selecting a sort option its color doesn't change.
@cdrini
> Refactor sort options on search and author page

- openlibrary/templates/lists/widget.html
Apparently we can't use default parameters in jsdef, because it gets converted to an es6 default param :/
> Fix lists widgets es5-ing

- static/css/components/edit-toolbar.less
Fix Edit Button Alignment
Before:
Now:
> Fix Edit Toolbar UI for Mobile View

- openlibrary/plugins/openlibrary/js/autocomplete.js
- openlibrary/plugins/openlibrary/js/edit.js
- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/templates/books/edit/edition.html
- package.json
Move autocomplete part of inline js for `openlibrary/templates/books/edit/edition.html` #4474
I'll make a separate PR for rest of inline JS since this alone was a lot. This will be much easier when this is written in Vue.
Moving some of the code generated server side to be generated client side was kind of a pain.
I'm following the advice in the main PR to use `data-*` attributes to pass data into the JS. Though it would be fantastic if there was a better way to do that.
Ideas for improving this would be appreciated but keep in mind the goal is to just move JS out of the python, not to change functionality.
After the next PR is done I'll be able to start #395
* Add a language
* Add a translation language
* Change the works
https://user-images.githubusercontent.com/921217/116959788-6ce59d00 …
> /move inline js for edition edit part 1

- openlibrary/templates/publishers/view.html
Refactor to remove inline js for `openlibrary/templates/publishers/view.html` #4474
As far as I can tell, this code is dead. I searched the codebase for usages, poked around with the debugger, and when I finally just deleted it nothing seems to have changed.
Go to [a publisher page](http://localhost:8080/publishers/Harper_&_Brothers) and see if there are any issues.
No UI changes
@jdlrobson
> remove inline js from publishers view

- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/plugins/openlibrary/js/merge.js
- openlibrary/templates/merge/authors.html
Refactor to move inline js for `openlibrary/templates/merge/authors.html` #4474
Nothing special. This was a straightforward change.
Go to a url like [this one](http://localhost:8080/authors/merge?key=OL18319A&key=OL22098A&key=OL81837A&key=OL20585A&key=OL9A&key=OL1434011A&key=OL1518080A&key=OL21774A&key=OL3437837A&key=OL3116423A&key=OL4A&key=OL1A&key=OL3A&key=OL18283A&key=OL24522A&key=OL2722241A&key=OL6848355A&key=OL19864A&key=OL2180017A&key=OL2660280A&key=OL2A&key=OL3116481A&key=OL3116644A&key=OL8A&key=OL6860521A&key=OL2622837A&key=OL2250A&key=OL1388798A&key=OL22122A&key=OL327356A&key=OL6A&key=OL1385835A&key=OL7A&key=OL2188410A) and follow steps in video.
https://user-images.githubusercontent.com/921217/118409971-d4332200-b628-11eb-8574-9c7e6e454fed.mp4
@jdlrobson
> move inline js for author merge page

- openlibrary/plugins/openlibrary/js/graphs/plot.js
Given our browser support we can assume `jQuery.support.opacity` is always true
so refactoring the code to fix alignment issue.
Before:
Now:
@jdlrobson
> Fix Chart Y-axis alignment

- openlibrary/templates/subjects.html
Related to #4474 
Removed the following inline JS
https://github.com/internetarchive/openlibrary/blob/d91dbadaf4d5ab6e7e63052f0e7a740954440692/openlibrary/templates/subjects.html#L27-L33
After some research, I found the same code (`var page = new Subject($:json_encode(page));`) was used in publishers page, which was later moved inside the `charts inline script` in [this PR (#1556 Publisher Page is v2)](https://github.com/internetarchive/openlibrary/pull/1556/files#diff-ff9e79ed2c805098f0d7966b45a41b17b07578e3b7004cc650560d4f8ee2d707L42-R60). After that, the whole `charts inline script` was removed from both the subjects and publishers page to a separate graphs.js file in #2360.
But as we never moved `var page = new Subject($:json_encode(page));` inside `charts inline script` for subjects …
> Remove inline JS from subjects.html

- openlibrary/plugins/openlibrary/js/search.js
Closes #5064
Fix show less facet function used on [Search page](https://openlibrary.org/search).
The `less()` function was able to hide all facets of a facet list in the `Zoom in` area when all available facets where displayed via the `more()` function.
`less()` function now reverts the `more()` function action when reaching the end of the facet list (Especially, when remaining hidden facet number < `facet_inc`).
Test for facet list with `5 + N * 10 + X` nb of items where:
- `N = 0` or `N > 0`
- `X = 0` or `0 < X < 10`
(Default nb of displayed facet is currently `5` and increment `10`)
@cdrini
> Fix show less facet function on search page

- openlibrary/plugins/worksearch/code.py
Needed for Solr 4+. Should cause no issue with Solr 3. Part of #4337.
> Escape forward slashes before sending to solr

- conf/openlibrary.yml
- openlibrary/plugins/worksearch/code.py
Closes #
- Here's a useful comparison place: https://codepen.io/cdrini/full/wvJqzaK (I needed https on testing to make this work :P )
- ✅ Results are better for popular books https://docs.google.com/spreadsheets/d/1BN5I7-OkTPaoTr2Es6jQ4O9ICWFmH0q9CP6kEgolCgg (books taken from Wikipedia's list of best selling books)
- ✅ Results are about the same for things like subjects.
- ✅ When no `solr8` in config, old weights applied
- ✅ When `solr8: false` in config, old weight applied
- ✅ When `solr8: true` in config, new weight applied
> [solr8] Tweak dismax params for all search

- openlibrary/plugins/openlibrary/js/jquery.customFade.js
- openlibrary/templates/type/author/view.html
Since upgrading to jQuery 3 feature, the browser detection is no
longer available. Given we support IE >=11 which supports opacity (filter was used < IE11 to do that)
this code is redundant and can be removed.
I get a JS error `Uncaught TypeError: t.browser is undefined` on http://localhost:8080/subjects/mathematics
The error resolves with this patch.
Missed in the jQuery 3 upgrade.
* Make sure no JavaScript errors on  http://localhost:8080/subjects/mathematics
* Create a new author Mark Twain 2 while logged in as an admin. Go to http://localhost:8080/search/authors?q=Mark+Twain and click merge authors. Click "Merge authors".  Make sure no javaScript error displays.
* 
@mekarpeles @cdrini  - deploy blocker I suspect.
> jQuery 3 follow ups: fix merge page and subjects error

- openlibrary/templates/site/stats.html
Related to #4474 
removed inline js from site/stats.html
@jdlrobson
> Remove inline JS from site/stats.html

- openlibrary/plugins/openlibrary/js/search.js
- tests/unit/js/test.search.js
Linked to PR #5109
Adds unit tests for functions `more()` and `less()` defined in [search.js](https://github.com/internetarchive/openlibrary/blob/d91dbadaf4d5ab6e7e63052f0e7a740954440692/openlibrary/plugins/openlibrary/js/search.js)
@jdlrobson
> Add tests for more/less functions from search.js

- openlibrary/plugins/openlibrary/js/edit.js
- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/templates/books/edit/edition.html
- package-lock.json
- package.json
Move validation part (the final part) of inline js for `openlibrary/templates/books/edit/edition.html` #4474
This PR is mostly a refactor.
It also fixes one small regression where validation notifications weren't showing up for roles or classifications.
This is following the patterns decided in #5136
To fix the regression of error messages not showing I simply copied the code that was working (for identifiers). Having inline styles is not ideal but while we have jquery which uses them it seemed ok. Open to ideas for a better solution but perhaps make a separate issue if it requires more than changing those two lines.
Check that validation works for roles, classifications, and identifiers on an edition edit page such as http://localhost:8080/books/OL24755423M/Odyssey_book_iv/edit
(see …
> move inline js for edition edit page validation

- openlibrary/templates/account/create.html
- openlibrary/templates/lib/nav_head.html
- openlibrary/templates/login.html
Closes #5256
Corrects login, logout, and account creation errors that are currently present in local development instances.
The `jQuery.trigger` function was replaced with vanilla `form.submit` calls in each of the modified files.
1. Attempt to login with valid credentials.
2. Once logged in, attempt to logout using the "Log out" option in the navigation menu.
3. Once logged out, navigate to the account creation page and attempt to submit the form.
> Correct login, logout, and account creation errors

- openlibrary/plugins/openlibrary/js/edit.js
- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/templates/books/edit.html
Closes openlibrary/templates/books/edit.html point from #4474
Move inline JavaScript from books/edit.html template to index.js and edit.js.
<del>Dead code removed (`$(#excerpt).keyup()` and associated `limitChars()`)</del>
`$(#excerpt).keyup()` and associated `limitChars()` repaired.
@jdlrobson
> Refactor/Move inline js from books/edit template

- openlibrary/plugins/openlibrary/js/add-book.js
- openlibrary/plugins/openlibrary/js/add_new_field.js
- openlibrary/plugins/openlibrary/js/covers.js
- openlibrary/plugins/openlibrary/js/edit.js
- openlibrary/plugins/openlibrary/js/jquery.repeat.js
- openlibrary/plugins/openlibrary/js/merge.js
- openlibrary/plugins/openlibrary/js/subjects.js
- openlibrary/plugins/openlibrary/js/tabs.js
- openlibrary/plugins/openlibrary/js/utils.js
- vendor/js/jquery-form/jquery.form.js
Related to https://github.com/internetarchive/openlibrary/pull/5201
1. :eq has been replaced with .eq()
Ref: https://api.jquery.com/eq-selector/
2. :first has been replaced to .first()
Ref: https://api.jquery.com/first-selector/
3. .bind() has been replaced to .on()
Ref: https://api.jquery.com/bind/
4. $.trim(f) has been replaced with f.trim()
@jdlrobson
> Fix jQuery deprecated methods

- openlibrary/plugins/openlibrary/lists.py
Closes #5215 . Hotfix ; replace removed function with `json.dumps`.
The function was removed in f9de97d  ; you can see that it was just a plain wrapper around simplejson.dumps, so just replacing it with json.dumps .
- ✅ Exporting the list now works: https://testing.openlibrary.org/people/dcapillae/lists/OL197248L/Rif_War/export?format=json
@dherbst @dcapillae
> Fix lists json export

- openlibrary/plugins/openlibrary/js/edit.js
- openlibrary/templates/books/add.html
- openlibrary/templates/books/author-autocomplete.html
Closes #5219. Hotfix. Apparently setting an input field to disabled causes it to not be sent in the POST. We want readonly.
- ✅  Confirmed can add an edition to an existing work.
- ✅ Confirmed can't modify the author when adding an edition to an existing work.
- ✅ Confirmed adding authors when editing work
- ✅ Confirmed adding author to new work/edition
The UI looks more confusing, but we can fix later.
| Before | After | 
| ------- | ------ | 
| ![image](https://user-images.githubusercontent.com/6251786/120036488-35b2a380-bfce-11eb-9158-b2dcaad1700e.png) |  ![image](https://user-images.githubusercontent.com/6251786/120036438-23d10080-bfce-11eb-839d-c74a1feb4ddb.png) |
@seabelis
> Fix add edition not working due to author_names being disabled

- openlibrary/solr/data_provider.py
- openlibrary/solr/update_work.py
- openlibrary/tests/solr/test_data_provider.py
- openlibrary/tests/solr/test_update_work.py
Closes #927 . This clears solrupdater's cache between calls to update_keys.
- ✅ Unit tests for the basic flow
- ✅ Patch deploy to ol-home0 and confirm subsequent edits are reflected.
- 1. put the code on ol-home0 and restart the docker container
- 2. Make an edit and wait for it to appear in search
- 3. Make another edit and see if it appears in search
> Fix solrupdater ignoring subsequent edits

- openlibrary/templates/lists/widget.html
Closes #5108
Corrects issue in which all of a patron's lists are briefly displayed under the reading log button on book page load.
All lists are briefly displayed due to a call to `render_already_lists` in the template.  This function is later called via Javascript, rendering only lists containing the page's book, which replaced the list.
Removing the initial `render_already_lists` call prevents the flash, and likely improves page performance.
While logged in as a patron with multiple reading lists:
1. Find a book that is in at least on of your reading lists, but not in all of the lists.
2. Navigate to that book's page.
3. Verify that all of the lists are not briefly displayed on page load.
**Page refresh before code change:**
**Page refresh after code change:**
@mekarpeles
> Fix reading list flash on book page load

- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/plugins/openlibrary/js/merge.js
- openlibrary/templates/type/author/view.html
Closes openlibrary/templates/type/author/view.html point from #4474
Move inline JavaScript from type/author/view.html template to index.js and merge.js.
@jdlrobson
> Refactor/Move inline js from type/author/view template

- openlibrary/templates/history.html
Related to #4474 
Use non JS method instead of inline JS
It basically selects two latest revision radio inputs (a10 and b11) and if only one revision is present then it selects (a1, b1)
@jdlrobson
> Remove inline JS from templates/history.html

- openlibrary/plugins/openlibrary/js/covers.js
Closes #4876
When a book cover is added, it requires a refresh to show the new cover. This PR removes this issue, now upon addition images appear as soon as the `submit` button is clicked.
@seabelis @jamesachamp
> Images refreshes automatically upon addition 

- .github/workflows/python_tests.yml
- bundlesize.config.json
- openlibrary/plugins/openlibrary/js/edit.js
Closes #5278
PPAs are often outdated as a result of not running apt-get update; not sure why this randomly started breaking though :/
> Fix CI failing due to PPA 404 & various JS lint failures

- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/plugins/openlibrary/js/ol.analytics.js
- openlibrary/templates/site/footer.html
Closes #5255 
Fix; ensure sendpageview sent after archive_analytics properly configured by ol.analytics.js. Note this might result in some of our server time metrics being a little longer.
- It looks like analytics.js no longer uses jquery! So don't need to order those in that way.
- ✅ Locally, pageview event fires with service=ol
- ✅ On testing, pageview event fires with service=ol
@jdlrobson
> Fix analytics pageview event being sent with wrong service

- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/templates/lib/nav_head.html
- static/css/components/header-bar.less
Closes #4929
To do:
Implemented details tag dropdown to fix keyboard accessibility.
Detailed Discussion: #https://github.com/internetarchive/openlibrary/pull/4977
https://user-images.githubusercontent.com/64412143/118355899-41df3f80-b590-11eb-8768-b84ac895f40b.mp4
@mekarpeles @jdlrobson @bpmcneilly
> Header Dropdown Accessibility

- openlibrary/plugins/upstream/account.py
hotfix
Now uses get_authors() and get_author_names() methods on Work to get cleaner author data and avoid serialization errors.
Load http://testing.openlibrary.org/people/seabelis/books/already-read.json?limit=1&page=62&debug=true
> Bug Fix account.py public_my_books_json to handle bad author data

- openlibrary/plugins/upstream/account.py
Rather than using get_authors() and get_author_names(), which generate a lot of server calls and are bad for performance, use the raw author keys but explicitly convert the author name into a string. The Nothing object which is causing serialization problems in this field should return an empty string.
http://testing.openlibrary.org/people/seabelis/books/already-read.json?limit=1&page=62&debug=true
should continue to load after applying the change (just faster)
> Performance improvement for account.py public_my_books_json()

- openlibrary/macros/LoanStatus.html
Presently, a registered printdisabled patron will see all accessible books as "Special Access".
For the purposes of testing, my account shows up as a printdisabled patron and so I am able to see what they see and I am often confused because, even as a print disabled patron, there are often times I / they may want to share a book and it's important to know which books may be available to them versus only available to me because of my account's "eligibility".
This PR makes a tweak to show "Read" and "Borrow" when such options are available, even if the underlying behavior may work differently for registered printdisabled patrons. It will only show "Special Access" for/on books for which only registered patrons with print disabilities may access.
Will include a screen shot once on testing. …
> only show Special Access if printdisabled-only

- openlibrary/plugins/openlibrary/js/carousel/Carousel.js
Upgrades our Carousel.js loadmore functionality to be more robust to values returned by API.
This fixes cases where:
1. our availability API returns `status: private` e.g. https://archive.org/services/availability?identifier=Hello.
2. prevents breakage when `book` doesn't have an `identifier` / `ocaid`
3. improves availability accuracy by looking for additional fields for availability options
Existing carousels should work without much change. @seabelis may have noticed some carousels which **don't** have `ocaid`s (e.g. Not In Library) likely break existing carousels when we try to Load More pages via ajax. This should be solved.
This PR is also a pre-requisite for passing list keys to `QueryCarousels`
@cdrini @jamesachamp
> primes Carousel.js to work w/ Lists + fixes existing bugs

- openlibrary/templates/lib/header_dropdown.html
- openlibrary/templates/lib/nav_head.html
- static/css/components/header-bar.less
Fixes: #5248
Follow up to #5181, makes dropdown component a template partial. This will allow us to experiment with using Vue.js in a follow up, and results in more standardized HTML between the different menus.
* Should be no noticeable UI regression between this patch and the last
* Notice the arrow to the right of the hamburger which adds consistency with the other menus and their functions.
@cdrini @Yashs911
> Use template partial for dropdown menus

- openlibrary/templates/lib/nav_head.html
Hotfix extension of #5287 . Looks like get_internet_archive_id can return `None` in local dev! 🙃 
- Recommend going commit by commit; the first commit is just a formatting change.
- Tested locally; header bar appears :+1:
@jdlrobson @jamesachamp
>  Fix header bar missing for local dev env when logged in 

- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/plugins/openlibrary/js/search.js
- openlibrary/templates/work_search.html
Refactor. As far as I can tell, this wasn't used for anything? Likely a residual from when we checked availability client side?
- Here's a sample request: https://openlibrary.org/api/volumes/brief/json/works/OL46125W|/works/OL46309W|/works/OL46390W|/works/OL46326W|/works/OL46224W|/works/OL1993999W|/works/OL46347W|/works/OL16063849W|/works/OL46369W|/works/OL46172W|/works/OL8004422W|/works/OL1001044W|/works/OL14854175W|/works/OL2633238W|/works/OL518262W|/works/OL5608342W|/works/OL5608343W|/works/OL158967W|/works/OL565229W|/works/OL1261147W?listofworks=True&no_details=True&stats=True
@mekarpeles
> Delete unused read api call

- openlibrary/templates/covers/add.html
Closes #5217
Sets the maximum number of covers displayed at once in the add covers modal carousel to three.
Explicitly passes number of books to be displayed to Carousel initialization function.
@seabelis
> Use appropriately sized cover images in add covers modal

- openlibrary/templates/covers/saved.html
- static/css/page-form.less
Closes #4889
Corrects issue in which the "Finished" button overlaps links in the saved image modal.
Image div and upload information div were nested within a div having `display: flex`.  Removed floats from both of the nested divs.  The `clearfix` div was removed from the template. A width attribute of `200` was added to the image.
Attempt to upload an image.  Upon success, ensure that none of the modal text is overlapped by any other elements in the view.
> Change layout of saved image modal

- openlibrary/templates/type/author/view.html
- static/css/page-user.less
The image being part of `contentOnethird` was placed below the works section for width<960px
Issue: Authors Page (mobile view)
Solution:
Mobile View:
Desktop View:
> Hoist image on authors page above the editions list on mobile view

- Makefile
- openlibrary/solr/update_work.py
- scripts/new-solr-updater.py
- scripts/solr_builder/Jenkinsfile
- scripts/solr_builder/index-type.sh
- scripts/solr_builder/solr_builder/fn_to_cli.py
- scripts/solr_builder/solr_builder/solr_builder.py
Extracted from #4337 . Various improvments to perf / error handling to solrbuilder and friends. Solr builder at this point should be considered Solr 8 only. I recommend reviewing commit by commit; easier that way.
The most recent full solr reindex was run with this code -- excluding last commit, and the fact that it was run on an older master.
Otherwise:
- ✅ Tested solr updater works correctly in local env with Solr 3
- ✅ Tested solr updater does not cache between update_keys calls (last commit)
@mekarpeles
> Solrbuilder/Solrupdater improvements in prep for Solr 8

- openlibrary/plugins/upstream/addbook.py
This should fix the issues where adding non-latin character books was
giving 'Internal Server Error' even though the book was being added.
The issue was that the url would contain those characters which
`gunicorn` did not like. Eg., `/books/OL10M/Вас_ил/edit?mode=add-work`.
So, to workaround that we will be encoding each individual parts of the
url path manually.
Big thanks to @cdrini for guiding throughout the process, learned a lot :)
Closes #4311
Related issue: #5308
@cdrini
> fix: error when adding non-latin character book

- openlibrary/core/bookshelves.py
- openlibrary/plugins/upstream/account.py
- openlibrary/templates/account/books.html
Closes #4267
Adding a new feature for sorting the Reading Log "Want to read" list of users by the date they have added their books.
Two filters added when being in the "Want to read" list, one for descending order and one for ascending.
1. Visit the Reading Log "Want to read" list
2. Two filters should appear, "Newest to Oldest" and "Oldest to Newest".
3. By clicking "Newest to Oldest" the books on the right should be sorted by the date the user has logged them in his list from newest logged to oldest logged. 
4. By clicking "Oldest to Newest" the books on the right should be sorted by the date the user has logged them in his list from oldest logged to newest logged. 
@mekarpeles, @jamesachamp
> Add ability to the user to filter lists by date added

- openlibrary/templates/type/author/view.html
Closes #5284
Adds LibriVox and Project Gutenberg links to author pages if a corresponding `remote_id` is present.
In addition to the `/config/author.yml` configurations outlined in #5093, two new identifiers must be added:
```
-   label: Project Gutenberg
name: project_gutenberg
notes: ''
url: https://www.gutenberg.org/ebooks/author/@@@
-   label: LibriVox
name: librivox
notes: ''
url: https://librivox.org/author/@@@
```
1. Add the correct LibriVox and Project Gutenberg IDs to an author's identifiers.
2. Confirm that the links are present in the "Links (outside Open Library)" section of the author page.
3. Confirm that the links navigate to the correct Project Gutenberg and LibriVox pages.
@RayBB @cdrini
> Add new remote ID links to author pages

- openlibrary/templates/type/edition/view.html
- static/css/components/iaBar.less
- static/css/components/mybooks-list.less
- static/css/components/work.less
- static/css/layout/v2.less
- static/css/legacy.less
Related to PR #4926 
Fixes:
1. IA Bar max-width
2. Books Page use display: flex; https://github.com/internetarchive/openlibrary/pull/4926#issuecomment-809811187
3. Fixes Author Page https://github.com/internetarchive/openlibrary/pull/4926#issuecomment-850661580
4. Fixes Subjects Page https://github.com/internetarchive/openlibrary/pull/4926#issuecomment-811632887
5. Fixes My Lists
@cdrini
> Fix bad UI related to increased max-width

- bundlesize.config.json
- openlibrary/plugins/openlibrary/js/covers.js
- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/plugins/openlibrary/js/tabs.js
Working towards #2340
* Removes some of the jquery ui off the critical path, constraining it to the covers feature and where tabs are used.
* Cleans up asynchronous loading of modules and bundle testing
* Reduces the critical path by around 10kb
Should not change any functionality - only concerned with when code is loaded.
* On a book page, click change cover. Check the covers are sortable and tabs display.
* On book edit page, check tabs are functional.
* 
@cdrini @mekarpeles
> [performance] Reduce the amount of critical path JavaScript  that is loaded

- openlibrary/plugins/openlibrary/js/index.js
Addendum to #5178 ; this was somehow causing covers to appear blank when logged in...
> Fix typo in index.js

- openlibrary/macros/Subnavigation.html
- openlibrary/templates/lib/nav_foot.html
I added `"home"` as one of the i18n nav items in testing on `ol-mek` to verify the i18n was working in e.g. Spanish.
Currently:
Will be:
With i18n:
@dcapillae @cdrini @jamesachamp
> fixes /dev subnav + adds i18n

- openlibrary/plugins/openlibrary/home.py
- openlibrary/templates/home/categories.html
Note ideally we would have subject entities with i18n in data, but considering that this is at the top of our homepage, and that subjects as entities are a waaaays away, this seems like a good compromise.
See https://github.com/internetarchive/openlibrary/issues/4679#issuecomment-872886934 .
- Tested homepage appears as usual locally.
- If a translation exists, it appears translated
English: 
French:
@milotype
> i18n subjects on homepage

- openlibrary/templates/site/head.html
Closes #5403 
Adds `noindex` header to testing/stage so we don't have testing/staging results showing up in search engines.
This also fixes some tiny whitespace issues on the `keywords` header. I can remove that if desired.
I couldn't figure out a simple way to access web.ctx.host so I just used the `$request.canonical_url` which uses web.ctx.host.
If this is a way we should access web.ctx.host feel free to fix or just let me know.
1. Are any openlibrary.org subdomains we don’t want excluded? (I assume blog.openlibrary.org won't be impacted)
2. Is there any chance someone else is hosting fork this and it will cause their site to stop being indexed?
I see it working locally by inspecting the html.
@cdrini
> add noindex header to anywhere but prd

- openlibrary/macros/EditionNavBar.html
- openlibrary/templates/type/edition/view.html
Closes #5404
Does not render the reader observations statistics component on book pages if an edition is orphaned.
1. Navigate to a book page of an orphaned edition.
2. Ensure that the page loads without any errors.
> Show stats component only if work key exists

- openlibrary/plugins/openlibrary/js/carousel/Carousel.js
Closes (Can't find the issue?). Fixes carousel "load more" not working.
- ✅ All carousels on homepage (except Classic Books) support scrolling
- ✅ Subjects pages support scrolling: http://testing.openlibrary.org/subjects/magic
- ✅ Publisher pages support scrolling: http://testing.openlibrary.org/publishers/Headline_Publishing_Group
- ✅ Query carousels work: http://testing.openlibrary.org/collections/k-12
@mekarpeles @jamesachamp @libjenner @seabelis
> Fix QueryCarousels not infinite scrolling

- openlibrary/templates/type/edition/view.html
Closes #5410
Removes the extra parenthesis that was showing up for user.
Parenthesis matching is hard to do by hand.
1. Go to edition page
2. Add excerpt
3. Check that no extra paren is showing.
@cdrini
> remove extra parenthesis from edition excerpts

- openlibrary/templates/account/readinglog_stats.html
Closes #5437
Link to author identifier docs from reading stats page
changed
Demographic statistics powered by Wikidata. Here's a sample of the query used.
To
Demographic statistics powered by Wikidata. Here's a sample of the query used.
Improve these stats by adding the Wikidata author identifier following (these instructions {link}).
> Link to author identifier docs from reading stats page #5437

- scripts/solr_builder/solr_builder/fn_to_cli.py
Closes #
Fixes bug in which `reindex-solr` call was failing after new Solr8 updates.
Incorrect type was being checked in `type_to_argparse` function, resulting in a `ValueError`.
@mekarpeles
> Fix local Solr reindexer

- openlibrary/macros/QueryCarousel.html
- openlibrary/plugins/upstream/utils.py
Closes #
When multiple carousels on a single page share the same key, they tend to be buggy in different ways.  The most visible bug causes a carousel to render without its "next" and "previous" buttons.  In some cases, carousels with the same key will fetch more books using another carousel's query string.
This PR seeks to avoid these bugs by attempting to create a unique key for all carousels created without a key.  It doesn't absolutely prevent duplicate keys on a single page, but should greatly reduce the amount that can occur.
In cases where carousels are created without a key, the absolute value of the carousel's hashed query string is used as the key.  This approach has some limitations:
1. Multiple carousels using the same query will have the same generated key.
2. My …
> Prevent duplicate default carousel keys

- openlibrary/core/lending.py
OL's get_availability call to Archive.org/services/availability bulk API was incorrectly assuming the json items returned would always be primary keyed by Archive.org ID (i.e. `ocaid` / `identifier`).
In most cases, we call this API with `identifier` (e.g. to add availability to our carousels and search results). However, this API can also be used to lookup `isbn`s, `openlibrary_work`s and `openlibrary_edition`s and when these IDs are provided, the Archive.org API keys the results according to the id-type specified (e.g. using `isbn` as the key will return results whose primary key is `isbn`, not archive.org `identifier`).
When a key other than `identifier` is used, the `ocaid` value must be extracted from the results, rather than the primary index key returned by the API. …
> hotfix get_availability for key types != archive.org 'identifier'

- CONTRIBUTING.md
- Readme.md
Ironically, no associated ticket. I'm just trying to improve our onboarding docs before adding anything about remote development (gitpods / github codespaces).
The improvements are generally:
* Putting linebreaks in long lines. (this has no visual changes)
* Wordsmithing - making descriptions shorter and hopefully clearer
* Removing links that aren't useful
* Add the docker command to the main readme
I try to err on the side of being as clear as possible for new users.
If you think anything should be phrased differently feel free to edit the pr directly, make a comment, or make a PR.
@jamesachamp
> update onboarding docs

- docker/README.md
Closes #
Updates Docker README to include information about Rosetta 2 installation, which is currently needed in order to run Docker on machines with an M1 chip.
> Add Rosetta 2 information to Docker README

- bundlesize.config.json
- openlibrary/core/booknotes.py
- openlibrary/core/models.py
- openlibrary/core/observations.py
- openlibrary/macros/NotesModal.html
- openlibrary/macros/ObservationsModal.html
- openlibrary/plugins/openlibrary/api.py
- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/plugins/openlibrary/js/modals/index.js
- openlibrary/plugins/upstream/account.py
- openlibrary/templates/account/books.html
- openlibrary/templates/account/notes.html
- openlibrary/templates/account/observations.html
- openlibrary/templates/lib/nav_head.html
- static/css/components/metadata-form.less
- static/css/components/notes-view.less
- static/css/page-user.less
Closes #4868
Allows patrons to view all of the book notes and observations that they have submitted.  Aggregate notes and observations views are displayed on the logged in patron's `/books` page.
Patrons are also given the ability to delete notes (using the notes modal), and observations (from the observations view).
This PR builds upon the work done in #5342.  It will likely need to be rebased once that PR is merged.  Leaving this as a draft until that happens.
*Updating a note in the new notes view*
*Deleting and updating observations in the new view*
@mekarpeles
> Create aggregate book notes and observations views

- .gitpod.yml
- Readme.md
In efforts to get GitHub Codespaces to work (#5438) I discovered gitpod.io and got it working.
In short, gitpod is an IDE that runs in the cloud and has a generous free plan. It has the major benefit of requiring zero setup for users to get started making small fixes.
As Mek [mentioned](https://internetarchive.slack.com/archives/C0ETZV72L/p1626992054477300), Open Library generally tries to avoid having tool specific files to the repo. However, adding this file will make it significantly easier for new users to start developing.
Right now, gitpod has a pretty generous free plan of 50 hours a month (or 100 hours for students). While we don't want to depend on that I'd say we should utilize it while we can. They also are an open source project so I'm hopeful they'll keep something nice going …
> add gitpod config

- openlibrary/i18n/__init__.py
- scripts/i18n-messages
Closes #
Adds `i18n-messages add` utility, which takes a locale code as a parameter and creates a new locale directory containing a `messages.po` file.  The new `messages.po` file is simply a copy of the `messages.pot` template file.
New directory and files are created only if they do not already exist.  `root` is the group and owner of new created files and directories in Ubuntu 18.04, and likely many other distros.  Because of this, `os.chmod` was used to relax permissions on the new directories and files.
1. Execute `i18n-messages add`, passing a new locale code as a parameter.
2. Ensure that the `i18n` directory contains a new directory with the same name as your locale code.
3. Ensure that the new directory contains a `messages.po` file, and that this file is a copy of …
> Create `i18n-messages add` for `.po` file generation

- openlibrary/macros/NotesModal.html
- openlibrary/macros/ObservationsModal.html
Updates the copy of book notes and book tags modals, with the hope that data privacy concerns are more clearly addressed.
_New copy for notes modal_
_New copy for tags modal_
@mekarpeles
> Update modal copy

- openlibrary/templates/observations/stats_component.html
Introduces the following improvements to the book tags statistics component, found on book pages:
1. Removes constraint requiring 2 patrons to review a work before statistics are displayed.
2. Lists number of respondents per aspect displayed.
3. Separates aspects with horizontal rules, making the component feel like less of a wall of text.
2. Either scroll to the bottom of the page, or click the "Reader Observations" tab found above the editions table.
3. Observe the reader observations component.
4. Make some new observations and refresh the page to see the changes reflected in the component.
_Work with multiple respondents_
_Work with no respondents_
Suggestions for copy/design improvements are welcome.
@mekarpeles
> Improve community book tags stats component

- openlibrary/macros/ListCarousel.html
- openlibrary/macros/QueryCarousel.html
- openlibrary/plugins/openlibrary/lists.py
- openlibrary/plugins/upstream/models.py
- openlibrary/plugins/worksearch/code.py
Allows List keys to be passed to `QueryCarousel` macro to power carousels
This PR extends `QueryCarousel` so a list key may be provided, such as `/people/mekBot/lists/OL104041L/` and the when https://github.com/internetarchive/openlibrary/compare/master...list-querycarousel#diff-a6072af04af429689c35331c2a4a35fa2c23317099533cc2161ef6d8ba79df90R1034 is called, the list will be expanded into a set of work_keys which are *then* passed through to solr.
Note: The limit and offset are necessarily for paging through the List, but we **don't** want the limit and offset to be applied to solr because solr is going to receive a discrete list of work_ids (from the already paginated/offset List) and we want to return all of these works from solr. 
Will likely be unnecessary once/if Lists are in solr …
> List + Solr work_key powered QueryCarousel

- .eslintrc.json
- openlibrary/plugins/openlibrary/js/SearchBar.js
- openlibrary/plugins/openlibrary/js/carousels_partials.js
- openlibrary/plugins/openlibrary/js/merge.js
- openlibrary/plugins/openlibrary/js/page-barcodescanner/LazyBookCard.js
- tests/unit/js/test.SearchBar.js
- tests/unit/js/test.search.js
Closes #5307
Added prefer-const rule:
This rule is aimed at flagging variables that are declared using let keyword, but never reassigned after the initial assignment.
npm run lint
@jdlrobson
> Add prefer-const eslint rule

- openlibrary/plugins/openlibrary/js/index.js
Closes #5504
Removes duplicate add and manage covers templates from the covers modal.
The covers initialization JS function was being called twice.
1. Navigate to a book page and click the manage cover link.
2. Ensure that there is only one template displayed.
3. Click the "Manage" tab, and ensure that only one template is displayed.
@RayBB
> Fix duplicate manage cover template in modal

- openlibrary/plugins/worksearch/code.py
Fixes a flood of errors causing all our metrics to break and our alerts to go haywire.
> hotfix for accessing `q` for ListQuery

- package-lock.json
- package.json
Hotfix. Getting errors about `npm ci` failing during building of olbase due to package-lock.json being out of date. 
- Just ran `npm i` to sync it up
> Fix package-lock.json out of sync with package.json

- openlibrary/i18n/__init__.py
- scripts/i18n-messages
Closes #5416
Multiple locale codes can optionally be added to the `i18n-messages update` command.  If codes are added, only the corresponding `.po` files will be updated.
Locale codes should be delimited by spaces.  For example, `i18n-messages update es de` will update the Spanish and German `.po` files.
Running `i18n-messages update` without any locale codes will update all `.po` files in the `i18n` directory, as per usual.
Any amount of locale codes can be included with an `update` call.  If there is not a corresponding `.po` file for a locale code, and error message is displayed and execution will continue normally.
1. Run `i18n-messages update` and ensure that all `.po` files are updated.
2. Run `i18n-messages update` with a single locale code.  Ensure that only the corresponding …
> i18n `update` accepts optional parameters

- openlibrary/templates/type/edition/view.html
Removes "Internet Archive" identifier from books page if the edition has a true `noindex` metadata attribute.
No data is modified by this PR --- Archive IDs are prevented from rendering if the item should not be indexed.
1. On testing, navigate to a book page of an edition that is designated `noindex`.
2. Scroll down the the edition details component.
3. Ensure that the "Internet Archive" ID is not displayed.
4. Confirm that all other expected IDs are present.
@mekarpeles
> Hide OCAID on book pages if edition has `noindex` flag

- bundlesize.config.json
- openlibrary/plugins/openlibrary/js/SearchBar.js
- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/templates/lib/header_dropdown.html
- openlibrary/templates/lib/nav_head.html
- static/css/components/header-bar--desktop.less
- static/css/components/header-bar--tablet.less
- static/css/components/header-bar.less
- static/css/components/iaBar.less
- static/css/layout/v2.less
- static/css/less/colors.less
- static/css/less/font-families.less
- static/images/hamburger-icon.svg
- static/images/search-icon.svg
Closes #5423; Closes #5212
Redesigned the Mobile Header Bar.
We want to make the header bar feel more like a native app's header.
- [Pending] Optional: swiping from the right edge from anywhere will open the drawer
Discussion: Do we want to lock the body scroll (shadow area)?
**Logged out users**
**Logged in users**
@cdrini @jdlrobson
> Redesign Mobile Header Bar

- static/css/components/edit-toolbar.less
Fixed the overflow issue of the edit button
Closes #5439
fix. This PR fixes the issue of the overflow of the edit button.
Though the most obvious thing on my mind was to limit the length of the text near it to a fixed limit and show ellipsis(...) after it.
But going through the CSS in the browser's dev tools, I found that the issue was that we didn't specify any specific bounds from the right which was an obvious thing to do since the container in which it's supposed to have some margin in the x-axis. So just adding some right margin was the solution. This may sound quite trivial but please refer to the screenshots where I have shown the effect of that.
Just run it :)
@RayBB @jimchamp
> Fixed the overflow issue of the edit button.

- static/css/components/header-bar.less
Closes #5520
- Confirmed working on browserstack/iOS 14, FF/Win10, Ch/Win10
> Fix header details tags showing ">" marker on safari!

- bundlesize.config.json
- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/plugins/openlibrary/js/modals/index.js
- openlibrary/templates/account/notes.html
- static/css/components/metadata-form.less
- static/css/components/notes-view.less
Removes notes modals from the notes list page, and places update and delete buttons under each note textarea.
1. Navigate to the notes list page.
2. Attempt to update a note.  Refresh the page to check if the note was persisted.
3. Delete a note. Ensure that the expected elements are removed from the UI. Refresh the page to ensure that the note was deleted.
@mekarpeles
> Remove notes modals from notes list page

- requirements.txt
In my analysis of requirements.txt, I found out that these are unused.
We will be testing it whether that is actually the case and there aren't any hidden/indirect usage. I tried building it locally and it seems to work.
Ref: https://github.com/internetarchive/openlibrary/pull/5162#issuecomment-841347300
Also, I found out even if we do not include them in the requirements.txt, they will be installed as they are indirect dependencies of some other packages:
```console
❯ dc exec web cat requirements.txt
amightygirl.paapi5-python-sdk==1.0.0
Babel==2.9.1
beautifulsoup4==4.9.3
DBUtils==1.3
Deprecated==1.2.12
eventer==0.1.1
flup-py3==1.0.3
Genshi==0.7.5
gunicorn==20.1.0
httpx==0.18.1
internetarchive==2.0.2
isbnlib==3.10.6
lxml==4.6.3
psycopg2==2.8.6
pymarc==4.1.0
python-dateutil==2.8.1 …
```
> build: remove unused dependencies from `requirements.txt`

- openlibrary/core/models.py
- openlibrary/templates/lists/widget.html
On book pages, the book notes modal link's text will indicate whether or not a patron has created a note for an edition.
Text does not update if a new note is added, nor if a note is deleted.
@mekarpeles 
@cdrini
> Indicate if note exists in modal link text

- openlibrary/macros/NotesModal.html
- openlibrary/plugins/openlibrary/js/modals/index.js
- openlibrary/templates/account/notes.html
- static/css/components/metadata-form.less
- static/css/components/notes-view.less
Updates styling of buttons and textareas in notes view and notes modals.  Dead CSS was also removed.
Save notes buttons are now anchor elements styled to look like buttons.
_Notes modal_
_Notes page_
@mekarpeles 
@cdrini
> Update notes form styling

- openlibrary/core/observations.py
- openlibrary/plugins/openlibrary/api.py
Updates book tags schema, and ensures that types and values marked as `deleted` are not displayed in the UI.
Observation values are cached.  The cache must be refreshed or observation values invalidated before these changes are reflected by the UI.
1. Navigate to a book page and open the book tags modal.
2. Ensure that the new schema is displayed.
3. Ensure that none of the old types and values are present in the statistics component at the bottom of the page.
4. In the aggregate book tags view, ensure that none of the deleted types and values are displayed.
@mekarpeles
> Update book tags schema

- openlibrary/macros/BookPreview.html
- openlibrary/macros/LoanStatus.html
- fixes printdisabled daisy links
- adds linkback option to BookPreview (don't visibly render archive.org linkback in preview if noindex)
- shows ocaid if privileged_user (for librarians tasks)
Incognito for no-index book:
When logged in as privileged user:
Incognito for indexed book:
@jimchamp @seabelis
> rm linkback for noindex unless librarian

- openlibrary/plugins/upstream/data.py
Work towards #3989 .
```
$ curl https://testing.openlibrary.org/data/ol_dump_ratings_latest.txt.gz -s -L -I -o /dev/null -w '%{url_effective}'
https://ia601503.us.archive.org/26/items/ol_dump_2021-08-11/ol_dump_ratings_2021-08-11.txt.gz
$ curl https://testing.openlibrary.org/data/ol_dump_reading-log_latest.txt.gz -s -L -I -o /dev/null -w '%{url_effective}'
https://ia801503.us.archive.org/26/items/ol_dump_2021-08-11/ol_dump_reading-log_2021-08-11.txt.gz
$ curl https://testing.openlibrary.org/data/ol_dump_editions_latest.txt.gz -s -L -I -o /dev/null -w '%{url_effective}'
https://ia801503.us.archive.org/26/items/ol_dump_2021-08-11/ol_dump_editions_2021-08-11.txt.gz
$ curl https://testing.openlibrary.org/data/ol_dump_editions_2021-08-11.txt.gz -s -L -I -o /dev/null -w '%{url_effective}' …
```
> Add helper eg /data/ol_dump_editions_latest.txt.gz links for ratings/readinglog

- docker-compose.production.yml
- docker-compose.staging.yml
- docker-compose.yml
- scripts/solr_builder/docker-compose.yml
Useful for #5493 . Fix. This lets us stop the containers, and not have them auto-restart eg when the host machine reboots. 
Note the containers will auto-restart if they are not manually stopped. Also note they will still restart-loop if they hit an error or something.
Tested:
1. Set `restart: unless-stopped` for solr in docker-compose.yml
2. `docker-compose up -d`
3. Restart docker daemon
4. ✅ Confirm solr is still running
5. Manually stop solr `docker stop openlibrary_solr_1`
6. Restart docker daemon
7. ✅ Confirm solr is not restarted
8. Start solr again `docker start openlibrary_solr_1`
9. Restart docker daemon
10. ✅ Confirm solr is still running
Tested:
1. Set `solr-updater` to `restart: unless-stopped, `command: echo blue`
2. `docker-compose up -d solr-updater`
3. ✅ Confirm restart …
> Switch production services to restart: unless-stopped

- conf/solr/conf/managed-schema
- openlibrary/solr/update_work.py
- openlibrary/tests/solr/test_update_work.py
- scripts/new-solr-updater.py
- Remove `text` field -- BREAKING CHANGE
- Add `number_of_pages_median` field
1.  docker-compose down
2. docker volume rm openlibrary_solr-data openlibrary_solr-updater-data
3.  docker-compose up -d
4. [x] http://localhost:8080/search.json?q=the&mode=everything does not have `text`, and _does_ have `number_of_pages_median` (might take a moment to not be empty though)
5. Edit http://localhost:8080/books/OL2058361M/The_wit_wisdom_of_Mark_Twain (to kick off solr-updater)
6. [x] http://localhost:8080/search.json?q=the&mode=everything does not have `text`, and does _not_ have `number_of_pages_median`
---
1. docker-compose down
2. docker volume rm openlibrary_solr-data openlibrary_solr-updater-data
3. Update docker-compose.override.yml to have `environment: [EXTRA_OPTS=--solr-next]` for …
> Tweaks to solr index schema

- openlibrary/plugins/openlibrary/js/modals/index.js
Displays a confirmation dialog when a patron attempts to delete a book note.  Note will only be deleted if patron confirms.
This PR only affects notes modal on a book page.  Notes page delete confirmations are handled in #5481.
While logged in as a beta tester:
2. If you haven't already submitted a note for the book, submit one.
3. Open the notes modal and click the delete button.
4. Confirm that the confirmation dialog appears.
5. Click "Confirm" to delete the note.  Ensure that the note is deleted.
@cdrini 
@mekarpeles
> Require confirmation before note deletion

- openlibrary/templates/type/author/view.html
Closes #5435
Tiny feature request to add olid to author pages.
Hop on an author page, like http://0.0.0.0:8080/authors/OL18319A/Mark_Twain and check out olid at the bottom of the sidebar.
@jimchamp 
Let me know if we'd rather have the olid in a different part of the sidebar.
> add olid to author page

- openlibrary/plugins/openlibrary/js/Toast.js
- openlibrary/plugins/openlibrary/js/modals/index.js
- static/css/components/toast.less
Fixes a number of issues with the toast component:
1. Keeps close icon from appearing close to the center of the component when a short toast message is displayed.
2. Allows multiple toast containers to exist on a page at a single time, preventing toast messages from being displayed on a hidden component (like a modal).
3. Allows a modal to be closed by the 'X' icon if it is overlapped by a toast container.
This PR also ensures that toast messages for observation type updates are capitalized.
Some background: Individual toast components are appended to an invisible toast container.  The container stretches the width of the page and allows multiple toast components to be displayed in a column.  The container itself is appended to a parent element, which is passed to the Toast constructor. …
> Various toast component bug fixes

- openlibrary/plugins/importapi/code.py
Closes #
Allows some MARC records to be re-imported from IA that are not technically marked as monographs.
This will enable 
* some past orphaned editions records to be repaired (the existing repair process is not triggering because some of these records are being rejected immediately)
* full scanning and metadata retrieval for scanning partners who have had map books, scores, multi-volume monographs, and other items rejected previously.
> Provide option to (re)import non-monograph MARC records if neccessary

- openlibrary/macros/EditionNavBar.html
- openlibrary/plugins/upstream/account.py
- openlibrary/templates/account/books.html
- openlibrary/templates/lib/nav_head.html
- openlibrary/templates/lists/widget.html
- openlibrary/templates/type/edition/view.html
Enable book tags features and views for all.
While logged in (preferably _not_ as a beta tester):
2. Attempt to open a book notes modal and leave a note.
3. Ensure that the "Review" tab is present above the edition table.  Click the tab.
4. Ensure that the review component is present.
5. Open the book tags modal and select some tags.
6. Click "My Book Notes" link in the account drop-down menu.
7. Ensure that the notes view has loaded and that your note is present.
8. Click the "My Observations" link in the sidebar. Ensure that the view renders without error and that your review is present.
@mekarpeles
> Remove book tags feature flags

- openlibrary/components/ObservationForm/components/CategorySelector.vue
Replaces heavy plus symbol with bullet symbol in book tags component.
@mekarpeles 
@cdrini
> Replace heavy plus symbol with bullet in book tags component

- openlibrary/components/ObservationForm.vue
- openlibrary/components/ObservationForm/components/CategorySelector.vue
When book tags component is open, a random category is now initially selected.
Page must be refreshed in order for new random category to be selected.
@mekarpeles 
@cdrini
> Display random category on component load

- openlibrary/core/observations.py
- openlibrary/templates/observations/review_component.html
Pills in review section now show percentages based on the total responses, instead of total respondents.
@mekarpeles 
@cdrini
> Display percentages of total responses in review section

- static/css/components/observationStats.less
- static/css/components/work.less
- static/css/less/breakpoints.less
- static/css/less/colors.less
Closes #
- Note: Changing of percentage meaning was not part of this PR; also font-size of the category label number is larger.
@jimchamp
> Observation section design tweaks

- openlibrary/i18n/__init__.py
- scripts/i18n-messages
Closes #5425
Adds `validate` command to our existing i18n utilities.  `i18n-messages validate` requires a locale code.  If a `.po` file exists for the given locale code, the file is checked for `fuzzy` flags.
If no `fuzzy` flags are found, a success message is printed and the function returns `True`.  Otherwise, messages containing the line number of flagged strings are printed and `False` is returned.  The function will also return `False` if an either an unknown locale code, or no locale code, is passed when the script is executed.
1. Run `i18n-messages validate` with a valid locale code.  Check the accuracy of the messages that are printed to the console.
@cdrini
> Add `i18n-messages validate` to check for fuzzy matching in `.po` files

- openlibrary/plugins/worksearch/code.py
- openlibrary/templates/authors/index.html
Closes #3296
What does this PR achieve?  It updates the authors search page from containing instructions that are not required, to displaying a list of 10 random authors.
> updating authors search page

- openlibrary/plugins/openlibrary/js/availability.js
Closes #5537
Removes badge count from join waiting list button.
Since `availability.js` will likely be replaced in the future (see #5419), I chose to remove badge rather than debug and fix null wait list count.
On testing:
1. Navigate to a list that contains a book that has a waiting list.
2. Ensure that the button does not have a badge.
@RayBB
> Remove badge from availability.js button

- openlibrary/templates/admin/inspect/memcache.html
Adds some instructions to the memcache admin UI.
@cdrini
> Include instructions in memcache admin UI

- openlibrary/macros/AffiliateLinks.html
- static/css/components/read-panel.less
This PR provides an update to contents in the Affiliate Links list. The HTML spec requires that list elements have only `li` elements as children, but previously we had both `p` & `details` elements as children of the `ul`.
- Adding an `li` element around the `details` / `summary` content ensures any more stores this will be rendered to users in the same list
- The style changes should result in no visual breaking changes on the page overall
- Ensure there are no visually breaking changes when "More" is displayed
@mekarpeles
> Ensuring Affiliate Links List Includes Only li Elements as Children

- openlibrary/templates/account/books.html
This was accidentally removed in PR #5353
1. Navigate to your "My Books" page.
2. Ensure that the import/export link is in the sidebar.
3. Ensure that the link takes you to the import/export page.
> Add import / export link to my books view

- .github/workflows/python_tests.yml
- Makefile
- openlibrary/i18n/__init__.py
- scripts/i18n-messages
Adds `test-i18n` rule to the makefile.  `test-i18n` does the following:
1. Reads in a list of valid locales from `/openlibrary/i18n/valid.txt`.
2. Runs `validate_translations()` for each locale, storing number of errors found.
3. Prints results and exits.
`valid.txt` is expected to contain one locale code per line (no commas or other special characters).  If `valid.txt` contains no locales, validation will pass (All zero locales listed passed validation).  Similarly, if `valid.txt` does not exist, validation is considered successful.
Exit Code Meanings:
0: All locales have passed validation.
1: Some locale files were not found.
2: At least one locale contains one or more invalid translations.
1. Add some valid locales to `/openlibrary/i18n/valid.txt`
- 'es', 'fr', and 'de' are valid on …
> Add i18n validation tests to the makefile

- openlibrary/core/schema.py
Adds a new indexed UNIQUE str db column called `data` to our `import_item` table schema so that our (currently IA-specific) import batch system can queue up and import [work with] arbitrary OL JSON book records
> adding UNIQUE data str col to import_item table

- openlibrary/api.py
- openlibrary/core/imports.py
- scripts/manage-imports.py
This is a followup of #5583 which should be **merged first** which updates the schema for the `import_items` table.
Closes first half of #5130
Allows manage-imports.py to add `{"data": {...}}` records in addition to `{"ia_id": "..."}`records to the https://openlibrary.org/admin/imports pipeline.
:warning:  **Please squash**
**`tty1`** 
```
ssh -A ol-home0.us.archive.org
sudo docker logs -f --tail 100 openlibrary_importbot_1
```
**`tty2`**
```
ssh -A ol-db1.us.archive.org
sudo -upostgres psql
delete from import_item where data is NOT NULL;
select * from import_item where data is NOT NULL;
```
**`tty3`**: 
```
ssh -A ol-home0.us.archive.org
sudo docker exec -uroot -it openlibrary_cron-jobs_1 bash
rm  /1/var/tmp/imports/2021-08/Bibliographic/2021-08-04/import.log
python3 …
```
> Data imports

- openlibrary/core/imports.py
When we serialize json data to string in import_items db, sort the keys for consistency to ensure unique constraint
Closes #
> enforce key sorting on `data` json.dumps

- .storybook/main.js
- .storybook/preview.js
- package-lock.json
- package.json
- static/css/base/common.less
- static/css/base/headings.less
- static/css/base/helpers-misc.less
- static/css/base/index.less
- static/css/components/buttonCta--js.less
- static/css/components/buttonCta.less
- stories/Button.stories.js
- stories/Introduction.stories.mdx
I'd like to migrate the documentation dfor our existing legacy components in
https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library to the actual code repository
and begin documenting any new Vue components that are being added (It's been difficult to make sense of the
new Vue code so I think having documented examples will help).
Allowing exploration of the UI components inside storybook is bound
to make development a lot easier, particularly for people coming
back to the codebase after a long absence (like me!)
We've been using storybook in Wikimedia Foundation for all our major
projects and it's been a huge help.
To make our LESS files compatible with both storybook and the less
bundler, a few modifications to imports are required, but these should
have no impact on …
> Setup a storybook

- openlibrary/plugins/upstream/covers.py
Closes #5637
Corrects issue where book covers can not be uploaded to Open Library.
The server checks for a default URL values and replaces it with an empty string.  The default URL in the covers modal was changed to in #5569, but the server was checking for the previous default URL.
1. Open the add covers modal for a book.
2. Attempt to upload a new book cover.  Ensure that this works without error.
3. Open another add covers modal.
4. Attempt to add a cover via URL to test for regressions.
5. Delete any cover images that were used for testing (unless they were the correct cover images).
@seabelis
> Fix image uploads

- openlibrary/core/imports.py
Every import queued by the patner bots will queue up the import with corresponding data of the book/edition in the `import_item` table. This will cause the size of the table to increase with every import. This change will clean up the data column once the import is succesful.
@mekarpeles
> Cleanup data after a successful import in the import_item table

- openlibrary/core/imports.py
- scripts/manage-imports.py
Rather than adding a new column for ID & type (since we have `ia_id` and all the infrastructure around it), I made it a requirement for a record to have an `ia_id` field.
This change makes it so, if you import a book by isbn, the `ia_id` is e.g. `isbn:0123456789` which cannot be a valid internet archive identifier (since it contains a `:`)
This also gets around requiring separate logic to determine which items have or don't have `ia_id`. It can now always do the unique check by the `ia_id` field. The determining factor will be whether a `data` field is present. If it is, the record will be imported as data. Otherwise, imported via `ia_id` which will fail if the ID is invalid.
1. We want the database to be performant. Checking `ia_id` instead of comparing large json strings for uniqueness …
> use isbn:{isbn} as ia_id, faster unique

- openlibrary/catalog/marc/marc_binary.py
- openlibrary/catalog/marc/parse.py
- openlibrary/catalog/marc/tests/test_marc_binary.py
- openlibrary/templates/history/sources.html
Enables  https://github.com/internetarchive/openlibrary-bots/issues/29
Adds the ability to import [Deutsche Nationalbibliothek](https://dnb.de/) (DNB) identifiers into Open Library from library MARC records (such as those made available to the public directly by DNB themselves, under a CC0 license).
This takes the DNB identifier from MARC field `016$a` (National Bibliographic Agency Control Number) if the `016$2` (source) is `DE-101`
* MARC21 `016` field description: https://www.loc.gov/marc/bibliographic/bd016.html
* DNB = DE-101: https://sigel.staatsbibliothek-berlin.de/en/suche/?q=DE-101
Source data for importing / testing: https://archive.org/details/marc_dnb_202006
Tested locally using the /api/import/ia endpoint -- newly imported DNB MARC record has the identifier as shown in the …
> Import DNB ids from MARC records

- .gitattributes
This PR should prevent MARC data (*.mrc) being counted as mIRC script by Github's [linguist](https://github.com/github/linguist) stats.
Documentation: https://github.com/github/linguist/blob/master/docs/overrides.md
Does not affect Open Library site behaviour.
> Stop MARC counting as mIRC script on github

- docker/README.md
We realized that the default docker ram on mac wasn't enough and it causing make js to be killed.
This updates the docs to share that.
Debugging thread:
https://internetarchive.slack.com/archives/C0ETZV72L/p1631630532094700?thread_ts=1631628824.088500&cid=C0ETZV72L
@cdrini
> add note about ram requirements

- static/css/components/buttonGhost.less
- static/css/components/iaBar.less
Closes #5153
It aligns donate button on Firefox.
**Chrome:**
**Firefox:**
> donate button aligned

- stories/Button.stories.js
refactor
uses string literals , as a crude way to recreate in plain html https://storybook.js.org/docs/vue/get-started/setup
@mekarpeles @jdlrobson
> Refactor button story to use string literals

- openlibrary/plugins/openlibrary/code.py
Closes #5403
Saw a staging.openlibrary.org URL in Google search 🤕 . Hotfix.
- ✅ http://localhost:8080/robots.txt serves norobots.txt
- ✅ http://testing.openlibrary.org/robots.txt serves norobots.txt
- ✅ https://openlibrary.org/search?debug=true&title=() lists host as `openlibrary.org` (scroll to bottom)
@mekarpeles
> Make staging/testing serve norobots.txt!

- conf/solr/conf/managed-schema
- conf/solr/conf/solrconfig.xml
- openlibrary/plugins/upstream/utils.py
- openlibrary/plugins/worksearch/code.py
Closes #178.
Closes #714.
Fix. **NOTE** this won't make a difference in production until the next full solr reindex (#5502 ), so all testing must be done in local env for now.
- includes a refactor of worksearch/code.py to allow for params to be used in solr request more easily.
- Change to /search/authors to search `name alternate_names` instead of `text` when no other fields are specified. Needed since only those fields have ICUFolding.
First reset the local solr env:
1. `docker rm -f openlibrary_solr_1`
2. `docker rm openlibrary_solr-data`
Then start it up and do a local reindex:
1. `docker-compose up -d`
2. `docker-compose exec web bash`
3. (inside container) `make reindex-solr`
Actual tests:
- ✅ http://localhost:8080/search?q=ghatti&mode=everything returns results
- ✅ …
> Author names should ignore diacritics in solr

- openlibrary/solr/types_generator.py
Looks like #5568 was slightly out of date.
> Add missing text_international to solr types generator

- openlibrary/catalog/add_book/__init__.py
- openlibrary/catalog/add_book/tests/test_add_book.py
Address part of my of proposal on #5650
Also a rework of #5651
This PR will deduplicate authors upon import.
I am not confident that when we get author dicts for import if they are duplicate.
If someone could check with something like `OL24626887W` that would be very helpful.
If they aren't identical (like lets say they also have a field for if they were illustrator or not) I'll need some sample data to come up with a specific implementation.
I added an automated test :)
@cdrini
> deduplicate authors on import

- .github/workflows/python_tests.yml
Closes #5661
Uses newer version of Ubuntu for our Python tests Github actions.
> Bump GitHub actions Ubuntu version

- openlibrary/i18n/messages.pot
Extracts all new i18n strings and adds them to the `.pot` file.
This file has been generated by using:
`docker-compose run --rm -uroot home scripts/i18n-messages extract`
@cdrini
> Extract new i18n messages

- openlibrary/plugins/upstream/utils.py
Hotfix; the dev_host url param was creating an XSS hole.
> Fix XSS attack with dev_host url parameter

- static/css/components/work.less
Closes #5658
Removes unnecessary transform from `.cover-animation` class, preventing glitch with image hover animation.
> Remove transform from cover image

- docker/nginx.conf
Closes #5653
Didn't test, but confirmed that TLSv1.3 has been supported in nginx since 1.13 (we have 1.19)
@mekarpeles
> Update nginx SSL protocols

- static/css/components/page-banner.less
Fixes a small annoyance. There is a small bit of beige at the top corners of the site due to border radius. I don't think it looks good against the black top bar.
Video shows the difference best.
Hope this change is welcome. 
Spin up an instance and see for yourself. 
https://user-images.githubusercontent.com/921217/133894648-28fae26f-51d5-46ba-9677-bf06f4f69345.mp4
@jdlrobson @jimchamp (I see you both listed as frontend leads)
> remove border radius from page banner

- static/css/components/work.less
Closes #5638
It fixes works page.
To make any flex box component scrollable, first we have to first add `overflow:hidden` to its parent component.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> works-page reformed

- openlibrary/plugins/openlibrary/code.py
- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/templates/login.html
Closes  #5440
Feature to autofill credentials for local development.
I decided to do the python/js hybrid approach because:
1. It will leave a trace in the html (the element id) to search for about autofill
2. In my opinion, it would be more messy and error prone to add the name/password in python
However, if someone wants to make a PR showing that the python only solution is cleaner I welcome it :)
Spin up a dev instance (you'll have to run `make js`) and see it auto fill on the login page.
Will need someone to test that this doesn't show up on testing/staging.
https://user-images.githubusercontent.com/921217/133849145-368ff9cb-9b6c-4ccb-8182-eddb43bc3196.mp4
@mekarpeles
> Autofill login for dev instances

- openlibrary/plugins/openlibrary/js/graphs/plot.js
- openlibrary/templates/admin/imports.html
Fixes broken import graph found in the admin imports dashboard.
While logged in as an admin:
1. Navigate to https://testing.openlibrary.org/admin/imports
2. Ensure that the graph is present.
@mekarpeles
> Fix broken graph on `/admin/imports`

- openlibrary/plugins/openlibrary/code.py
- openlibrary/plugins/upstream/utils.py
- openlibrary/templates/site/footer.html
This should improve our score here for subresource integrity: https://observatory.mozilla.org/analyze/openlibrary.org ; and potentially give us a speed boost, since not connecting to archive.org for these scripts.
> Serve archive.org JS files from openlibrary.org

- openlibrary/plugins/worksearch/code.py
Causing a small error in the latest deploy on http://openlibrary.org/authors
> Fix dangling ref to run_solr_search signature breaking /authors and subjects search

- conf/openlibrary.yml
- openlibrary/core/helpers.py
- openlibrary/core/models.py
- openlibrary/macros/SearchResultsWork.html
- openlibrary/plugins/openlibrary/home.py
- openlibrary/plugins/upstream/models.py
- openlibrary/plugins/upstream/tests/test_utils.py
- openlibrary/plugins/upstream/utils.py
- openlibrary/templates/covers/change.html
- openlibrary/templates/diff.html
- openlibrary/tests/core/test_helpers.py
Uploading covers locally doesn't work because in the local environment, the server needs to hit covers:7075, but the user's browser doesn't have access to that host. So we need a separate, public resource URL for that. In the local dev environment it's localhost:7075.
> Fix uploading covers on local environment

- openlibrary/core/imports.py
hotfix for ia imports. Tested on cron server
normalize_items was not working correctly when `item` was a string (instead of a dict)
> unbreaks ia imports (items submitted as ia_id)

- openlibrary/plugins/openlibrary/lists.py
Closes #5613
Patrons with hyphens in their usernames should now have full list functionality.
Original path regex for usernames was only capturing word characters (letters, numbers, and underscores).  This has been expanded to use more characters.
@seabelis 
@mekarpeles
> Update username regex in list paths

- docker-compose.staging.yml
Noticed that after an outage, memcached is not auto-restarting on testing.openlbirary.org, causing the site to be slow until it is manually restarted.
Not tested; Small change, I think it should be unlikely to cause an issue.
> Auto-restart memcached on staging

- openlibrary/macros/SearchResultsWork.html
Closes #5630 
Fixes long lists of authors for SearchResultsWork by slicing first 9 authors off authors array and rendering a small "view all authors" message when the authors array exceeds 9.
The `max_rendered_authors` is defined at the beginning of the template partial, in the event we feel the max should be changed.
1. Search for a work title whose author list exceeds 9 (you may need to edit a work locally and add authors in order to achieve this)
2. The search result for the work should show the first 9 authors and a "view all authors" link to the work's show page
3. Click the "view all authors" link
4. From the work show page, click the first author in the list
5. The author show page should display the work with the author list truncated to 9 and the same "view all authors" link …
> fix(SearchResultsWork): Limit displayed authors to 9

- openlibrary/plugins/openlibrary/code.py
The hypothesis is that because book_providers imports something important at the wrong time, it was causing the OL /account/login.json override to be registered at the wrong time, before infogami had setup its necessary hooks.
Closes #5815
```
curl -XPOST 'localhost:4444/account/login.json' -d '{"access": "***", "secret": "***"}'
```
Should return nothing; replace `localhost:4444` with whatever env you want to test.
> Fix /account/login.json not working

- .gitmodules
Our GitHub actions are failing on the `make git` step, due to the use of `git://` protocol in our submodules.  GitHub suggests using ssh or https in the future: https://github.blog/2021-09-01-improving-git-protocol-security-github/#git-protocol-troubleshooting
After this change, ol_home began throwing errors on start.  Rebuilding Docker corrected this issue, but there is probably a less extreme solution (maybe a recursive sync would work: `git submodule sync --recursive`).
> Update Git submodule protocol

- openlibrary/i18n/es/messages.po
- openlibrary/i18n/messages.pot
- openlibrary/templates/type/work/editions_datatable.html
A small correction to include the "?" sign as part of the translatable string.
I have modified the string in the messages.pot file and in the Spanish translation. I have not modified the other languages in order to avoid mistranslations.
A screenshot of the site page showing the only modified string.
Open Library translators team.
> Fix translatable string 'Add another edition' on work page

- openlibrary/plugins/upstream/addbook.py
Closes #143
Makes it so that contributors can be deleted. 
Previously, when you removed all contributors the form didn't send any contributor data. Because no contributor data was sent there was no update to remove all the contributors.
Now, if no contributor data is sent it will remove the contributors. This creates the intended UX
I originally tried `del self.edition.contributors` instead of setting to an empty array.
However that and would give this error:
<details>
<summary>Spoiler</summary>
Code
```
if 'contributors' not in edition_data and self.edition.contributors:
del self.edition.contributors
```
Error
```
| Traceback (most recent call last):
openlibrary-web-1           |   File "/home/openlibrary/.pyenv/versions/3.9.4/lib/python3.9/site-packages/web/application.py", line 280, in …
```
> allow deletion of contributors

- openlibrary/templates/covers/book_cover.html
Closes #5822
Truncates the title of a book when the book has no cover image.
Reduces the maximum length of a title string from 70 to 30 characters.
@JeffKaplan @mekarpeles
> Truncate book title when cover is missing

- openlibrary/plugins/openlibrary/api.py
Closes #5820 
Makes sure the delete work endpoint deletes all the ediitons of the work
One small technical note, the limit is arbitarily at 10000. I'm just trying to make sure we cover all editions.
@cdrini
> Increasing limit for work deletion and use can_write instead of checking perms manually

- .pre-commit-config.yaml
Relates to #5843 
Before this, the pre-commit hook was setup to only run on push and when it did run it gave the following error:
```Executable `/Users/ray/workspace/openlibrary/git` not found```
I changed the language to `system` because that's what worked. There may be a case to use `script` language but it was giving me problems  so if you can fix it please do.
Try running `pre-commt install` and committing code with extra spaces or something.
@cdrini @cclauss @jimman2003
> fix pre-commit hook for flake8

- openlibrary/solr/update_work.py
Closes #5852
Not sure why #5841 changed this from the generic `typing.List` to `list` but I don't think we need the generic one anyway.
Try running `docker-compose run --rm home make reindex-solr` on this branch and see if it works
@cdrini @cclauss @jimman2003
> fix #5852 reindex issue

- stories/Button.stories.js
Updates our CTA button stories such that the correct button HTML is displayed in each button's code block.
By default, Storybook displays the code used to generate a story as the component's code. For convenience, the HTML for each story is generated using a `ButtonTemplate` function, which does not exist in Open Library.  This PR replaces the incorrect `ButtonTemplate` code with the HTML that a developer would use to create the same button in OL.
1. Start Storybook and navigate to the Storybook site.
2. Click on the "Docs" nav item:
3. Expand the "Buttons" section in the sidebar.
4. Ensure that the correct HTML is displayed in each component's "Show code" section.
Before change:
After change:
> Display correct source code for CTA button stories

- openlibrary/plugins/upstream/tests/test_utils.py
- openlibrary/plugins/upstream/utils.py
- openlibrary/templates/lists/home.html
Closes #5341
Removes all HTML tags from list descriptions and truncates the results to 250 characters.  Truncated results are nested within a single `<p>` element.
This solution occurs server-side, and only affects list descriptions on the `/lists` page.
This one is tricky to test locally, but the code is live on testing.
1. Navigate to http://testing.openlibrary.org/lists
2. Ensure that any long list descriptions that may appear are truncated
3. Ensure that long list descriptions on list search and my list pages are not truncated
Full list can be found [here](http://testing.openlibrary.org/people/stillme/lists/OL193888L/Not_available_%E3%80%8A_UATF_%E3%80%8B).
@RayBB
> Truncate long list entry descriptions

- .pre-commit-config.yaml
- setup.cfg
Closes #5750
https://github.com/codespell-project/codespell is a lightning fast spellchecker than looks for common near-miss typos like one letter missing or two letters transposed.  See #5750 and #2905 to see the kinds of typos that it has found in the past in this codebase.
Give it a whirl and see how fast it is!
> Add codespell to pre-commit and setup.cfg

- docker-compose.production.yml
- docker/covers_nginx.conf
- docker/public_nginx.conf
Closes #5789 with a more slimmed-down version.
Blocked by #5840
* `public_nginx.conf` is configuration for public-facing Docker-based Nginx nodes.  Content was formerly in OLSystem.
> http2 for public facing nginx

- openlibrary/templates/home/categories.html
These are loading really early in the page, despite being at the bottom!
- Don't appear in networks panel anymore on first load!
> Make category images on homepage lazy

- .gitpod.yml
Related to #5843
Precommit hooks will be setup automatically for gitpod environments.
This is ONLY to get precommit hooks setup. Autoformatting code on save will be a different PR.
* `pyenv install` installs the version in `.python-version` as that's what's needed.
* `pip install pre-commit` will install precommit to the local environment (since it doesn't run from inside docker).
* `pre-commit install` actually installs the hooks.
You can test it out here: https://gitpod.io/#https://github.com/internetarchive/openlibrary/pull/5851
@cclauss @cdrini
> Precommit hooks for gitpod

- .gitpod.yml
- scripts/setup_gitpod.sh
In testing https://github.com/internetarchive/openlibrary/pull/5849 I realized that we needed to make some changes to the gitpod init step so that it will work with pre-commit hooks that require external libraries.
I decided to make it into a `.sh` file now to not have to worry about having the yaml formatted just right and have nice comments and ide linting for the script. 
I expect this script to grow as do do things like fix https://github.com/internetarchive/openlibrary/issues/5834
There isn't much to test here other then that pre-commit hooks still work. This is mostly important for #5849 which not work in gitpod until this is added.
@cclauss @cdrini
> add setup_gitpod.sh to prepare for pre-commit hooks

- scripts/setup_gitpod.sh
It takes over 1 minute for `pyenv install` to run on gitpod.
This change will make it so the pyenv install can happen in the background while docker starts building images.
This will cut ~1 minute off the init time for gitpod.
The syntax used is explained [here](https://stackoverflow.com/a/14612605/620699).
The downside to this is that the print statements for docker and the pre-commit stuff will be mixed together. Don't think it's worth trying to fix that.
Open this PR in gitpod and see it start in background and finish successfully. 
@cclauss
> run pyenv install in background for gitpod

- .pre-commit-config.yaml
Let's speed up our pre-commit jobs.  As discussed at https://github.com/internetarchive/openlibrary/pull/5849#issuecomment-968516899 running flake8 inside Docker is way too slow for a pre-commit job.  This PR enables pre-commit to run `scripts/flake8-diff.sh` in the local directory which completes quickly and finds all the same issues.
Edit any Python file in the repo and create an _undefined name_ (`test = this_thing_that_does_not_exist`) and commit that change.  Pre-commit should fail on a flake8 `F821 undefined name`.
> pre-commit: Run flake8-diff.sh outside of Docker

- .github/workflows/pre-commit.yml
Subtask of #5843
Blocked by #5870
Now that we have a pre-commit that runs fast, let's add a GitHub Action that runs it in parallel with our existing JavaScript and Python GitHub Actions.  Running this action assures that PRs that are created via the GitHub web UI or other means are tested with the same test that command-line developers use.  This could either be a standalone file (this PR) or these commands could be added as a parallel job in the Python Action.
___Fails___ because running flake8 inside a Docker container has its downsides.
> GitHub Action to run pre-commit

- .pre-commit-config.yaml
- requirements.txt
Adds https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/requirements_txt_fixer.py as a pre-commit hook.
> Add pre-commit requirements-txt-fixer

- openlibrary/components/LibraryExplorer/components/BookCover3D.vue
- openlibrary/components/LibraryExplorer/components/OLCarousel.vue
- openlibrary/components/LibraryExplorer/components/Shelf.vue
This removes a ton of fetches and complexity!
Here's how many requests we made in books 3d to get this information _before_...
> [libraryexplorer] Remove individual page count fetches; now in solr!

- docker-compose.production.yml
- openlibrary/solr/update_work.py
- scripts/new-solr-updater.py
Closes #5502
Now that the next version of solr has been cemented into production, we update solr-next. What was solr-next before, is now just normal solr, and the next solr-next has to be primed :)
> Make solr-updater --no-solr-next explicit

- static/css/components/mybooks.less
Closes #5876
Ensures that my books page renders properly on iPad Minis.
Media query for changing flow direction was different than the query for adjusting the sidebar's width, causing issues when the screen is exactly 768px wide.
> Use correct media query for my books page

- .github/workflows/javascript_tests.yml
These tests are a little slow, and are more often than not, not necessary for a lot of PRs!
- Note this is only for PRs ; merging in to master will always run JS tests.
@jimchamp @cclauss
> Only run javascript CI when javascript changed

- openlibrary/plugins/openlibrary/api.py
In support of The Best Book On, this PR creates a `/observations` GET endpoint which can be used to fetch observation data for a list of works.
Work OLIDs are expected to be sent via query string.  `openlibrary.org/observations?olid=OL123W&olid=OL456W` would fetch observation data for works OL123W and OL456W.
This can be tested by making GET requests to `/observations`.  Ensure that the `Accept` header is set to `application/json` when making the requests.
@mekarpeles
> Expose endpoint for works' observations

- openlibrary/book_providers.py
- openlibrary/plugins/openlibrary/code.py
- openlibrary/templates/type/edition/view.html
- openlibrary/utils/__init__.py
Closes #5802
- This approach is a little over-engineered, but I'm hoping it'll let us easily expand to things like preferring english works for english users, once we get that infra.
Would recommend pulling down #5907 for testing locally ; simplifies it a ton since that let's you copy an entire work (with editions)!
- Aliens book from issue now selects IA edition:  https://openlibrary.org/works/OL102584W
- providerPref now respected: `/works/OL252350W/The_Cave_in_the_Mountain?providerPref=gutenberg`
- Books with no readable editions not broken
- Books with _many_ editions not too slow
- There's a lot of sorting-y stuff happening!
- Imported ~920 editions of hamlet ; added about 0.42 seconds to the load :/ That's non-trivial, but the page already takes ~4s, so considering that ok for now. …
> Fix readable edition not selected when visiting work page

- openlibrary/templates/type/list/view_body.html
Closes #5903
Fixes width Issue in cards due to image align.
Added the `clearfix` class to the [view_html](https://github.com/homewardgamer/openlibrary/blob/43abb8df883eb149fd97d5584c2b7b7b26749750/openlibrary/templates/type/list/view_body.html) result list.
View this page https://openlibrary.org/people/dcapillae/lists/OL202672L/Origami_Collection and check the first card is smaller than the rest of them
@jimchamp
> Added the clearfix class to the list result in view_body.html file

- .pre-commit-config.yaml
Closes #
New type annotations will not be added until Python 3.11.  Importing annotations from `__future__` can sometimes cause other issues, as per @cdrini.  We use `pyupgrade` specifically to replace old-style type annotations.  Removing `pyupgrade` enforces our typing standards and prevents our checks from failing in GitHub.
@cdrini 
@cclauss
> Run pyupgrade --keep-runtime-typing in pre-commit

- openlibrary/data/dump.py
- scripts/oldump.sh
Closes #5893
Testing (stats as of November 2021):
The oldump cron job on `ol-home0` takes 18+ hours to process 192,000,000+ records in 29GB of data!!
These changes enable `scripts/oldump.sh` to `OLDUMP_TESTING=true` which will allow the script and `openlibrary/data/dump.py` to only process the first 1 million lines of the file instead of 192+ million lines. The first step of this script will still take 110 minutes to extract the 29GB of data from our database so it is ___highly recommended___ to save a copy of `data.txt.gz` to skip that step and accelerate the testing of subsequent job steps.
```
Call flow:
docker-compose.production.yml defines `cron-jobs` Docker container.
--> docker/ol-cron-start.sh sets up the cron tasks.
--> olsystem: /etc/cron.d/openlibrary.ol_home0 defines the …
```
> Given the long run times, make ol-dumps easier to test

- openlibrary/macros/SubjectTags.html
- openlibrary/templates/search/subjects.html
Closes #333
This is a review response to #5939  
The discussion on #333 has got way out of hand and seems to have lost focus since the original report from 2016.
The original report deals with the subject search page for the specific query:
https://openlibrary.org/search/subjects?q=business+economics&mode=everything
The two problem examples from the original report are the URLs:
* https://openlibrary.org/subjects/business_&_economics_/_finance
* https://openlibrary.org/subjects/business_&_economics_/_management
Which have the link texts:
* Business & Economics / Finance
* Business & Economics / Management
The correct working destinations for these two are:
* https://openlibrary.org/subjects/business_&_economics__finance
* https://openlibrary.org/subjects/business_&_economics__management …
> simple fix which closes #333

- openlibrary/templates/home/stats.html
- openlibrary/templates/lib/nav_foot.html
Closes #4630 (and I believe #4521)
Fixes the accessibility violations on the home page by adding alt text to images missing it
I removed the aria hidden attribute from the Open Library logo in the footer to allow the new alt text to show. I also used the title attribute to add the alt text for the 'Around the Library' graphs to avoid messing with their div coding.
Go to home page and inspect accessibility for 'Around the Library' graphs and the logo in the footer. See new alt text visible. 
Screenshots of no UI changes:
@bpmcneilly
> Adding Alt Text to Home Page Images

- scripts/partner_batch_imports.py
Attempts to address  #4151
Many of the notebooks in the data are hard to distinguish from real books -- there are many metadata fields available, but they are not used consistently, (many are left blank), there is a `primary format` field which does appear to be mandatory, and that contains one of 206(?) possible values. That looks like the best way of filtering non-books available in the source data.
This PR add a blacklist of the most non-bookish. A whitelist might be better, where we only allow certain kinds of best-book like types.
This is a start for a whitelist, which I could implement, if the community discussion mentioned on #4151 leans towards selective importing:
```
AP	UK- A Format Paperback
BD	Children's Board Books
BG	Big Book
BP	UK-B Format Paperback
BZ	Book, Other
DP	Digest …
```
> minimal attempt to avoid importing non-books

- openlibrary/core/ratings.py
- openlibrary/plugins/openlibrary/api.py
Work towards #3990 . Needed a way to test that the DB fetch of rating data was working correctly, so did this.
- https://testing.openlibrary.org/works/OL252350W/ratings.json
- https://testing.openlibrary.org/works/OL50231W/ratings.json
- https://testing.openlibrary.org/works/OL82563W/ratings.json (Harry potter)
> Add API for getting a work's ratings summary

- static/css/components/work.less
Closes #5944
Fixes sticky menu on book pages.
> Fix sticky menu on book pages

- openlibrary/macros/LoanStatus.html
Closes #5942
I have wrapped the"Not in Library" books within a `cta-button-group` div which solve the extra vertical height that the card was having.
Run the local setup on docker go to the main website, inspect the webpage using dev tools and verify.
@jimchamp
> Fixed layout of  `Not in library` button

- .github/workflows/javascript_tests.yml
Our JavaScript tests are automatically run only when certain files are modified.  However, sometimes it would be useful to run these tests on demand.  Adding GitHub Actions `workflow_dispatch` enables manually triggered tests of our JavaScript code.  https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
> Enable GitHub Action javascript_tests to be manually run

- openlibrary/core/sponsorships.py
This was causing errors on the site for most books, because it's missing a parameter.
- Already patch deployed.
@mekarpeles
> Fix eligibility_check having wrong signature

- .github/workflows/codegen_api_docs.yml
Put in place an on-demand GItHub Action that will enable testing of #5910 before it is ready to be merged.
The Python code at the end is from https://github.com/cclauss/Ten-lines-or-less/blob/master/platform_info.py
Closes #
> Create on demand GHA workflow codegen_api_docs.yml

- openlibrary/core/models.py
... from_isbn. Resolves 
Closes #5963
fix
Handled case where value returned from utils/isbn.py to_isbn_13 is None by checking if None and returning. This is essentially the same behaviour as for ISBN parameter not in correct lengths, so seems a reasonable approach to me without introducing dependency directly within models.py on third-party isbnlib validation functions.
See #5963, essentially ISBN handling currently results in error for invalid ISBN that's sufficiently like an ISBN. https://openlibrary.org/search?debug=true&isbn=1234567890
> to_isbn_13 can return a None value, handle that case in models.py

- scripts/deployment/patch_test_new_memcache_server.sh
From internetarchive/olsystem#145
```
```
Used in internetarchive/olsystem#138, internetarchive/olsystem#144, internetarchive/olsystem#145
> Create a deployment script to test a new memcache server

- docker-compose.infogami-local.yml
- docker-compose.override.yml
- docker-compose.production.yml
- docker-compose.staging.yml
- docker-compose.yml
- scripts/deployment/restart_servers.sh
Closes #5956 which got in a bad git state with vendor/infogami
To simplify both configuration and scaling up or down, this pull request enables `ol-covers` to use [Docker compose deploy replicas](https://docs.docker.com/compose/compose-file/compose-file-v3/#replicas) .
This PR also upgrades from Docker compose file v3.1 to v3.8
* https://docs.docker.com/compose/compose-file/compose-versioning/
Tested in #5951
> Enable ol-covers to use Docker deploy replicas again

- static/css/components/search-result-item.less
Closes #5959
Fixs List delete icon disappears on hover
Changed `background-position` value
All lists: `/account/lists`
List pages: `/people/{username}/lists/{list_olid}`
Go to either of the above listed pages.
Locate a green trash bin icon and hover over it.
Actual: The green trash bin icon disappears.
Expected: The red open trash bin icon is displayed.
@jimchamp
> Fix list delete icon disappears on hover

- scripts/oldump.sh
Fixes #5930
https://archive.org/services/docs/api/internetarchive/cli.html#upload
feature
* ~Should we create `*_files.xml` with code from `uploaditem.py` or with `ia`?~ Auto-created on IA
* ~Should we create `*_meta.xml` with code from `uploaditem.py` or with `ia`?~ Auto-created on IA
* Should we use parallels? 
I added only the basic metadata
verify that the cli does upload the correct files with metadata
@cclauss
> Switch to ia cli to upload dumps

- openlibrary/templates/site/footer.html
Closes #5974
Removes unnecessary data sent to frontend which increases code vulnerability.
Removed the console. logs for the success message but kept it in case of an error so that it will be easy to debug later down the line.
@jimchamp
> Removed unnecessary console.log

- openlibrary/i18n/es/messages.po
Button texts have been replaced by those suggested in the issue.
Another deficient translation has been corrected.
Closes #5754
> Update button texts that are cut off in Spanish

- openlibrary/components/LibraryExplorer/components/LibraryToolbar.vue
Closes #5042
Fix the language drop-down list filter not displaying correctly and behaving strangely when navigating with up/down arrow keys in the Library Explorer
Likeliest match is not near the input field anymore (as per comment in code), however likeliest match is still selected first.
Tested on FF95 only.
Go to `/explore`, open `Filter` in the control panel and open the list at `Other...`.
Navigate with up/down arrow keys in the drop-down list.
> Fix library explorer language filter display

- openlibrary/plugins/upstream/account.py
- openlibrary/templates/lists/widget.html
Closes #
This contains a few login-related bug fixes:
1. By default, patrons will be redirected to their loans page if no other redirect URL is POSTed.
2. Replaced incorrect `redir` query parameter used by the book page reading log dropper.
3. Do not render book note link if patron is not logged in (the link doesn't function for logged-out patrons).
We failed to account for the hidden `redirect` input in the login template in #5774.  This was populated by default with the `HTTP_REFERER` by the `/login` GET method.  `/account/loans` now replaces `HTTP_REFERER` as the default redirect value.
The main issue with this approach is that using the navbar login link on a book page will result in a redirect to the loans page.  Some may consider this behavior to be unexpected/undesired.  To remedy …
> Fix login redirect issues

- openlibrary/macros/TypeChanger.html
Closes #4581
Resolves the Issue of a `pageType` block showing in non admin mode
Instead of conditionally rendering the contents of `pageType` block I have rendered the entire pageType block conditionally. In case the user is not an admin I have removed the class `adminOnly` from the` pageType` div which makes it's `display:none` automatically.
User login: 
Admin login:
@jimchamp
> Fixed admin only feature showing on edit page

- requirements.txt
- scripts/import_standard_ebooks.py
Closes #3982
Creates a Standard Ebooks (SE) import flow.  Flow is as follows:
1. Make HEAD request to SE, capturing the last modified date.
2. Read time that job was last executed from local file.
3. If SE feed was modified after the last import job was executed, make GET request for SE feed.
4. For each feed entry that was updated after that last import job, map entry to OL import object.
5. Add JSON string representations of import objects to a new batch job.
This solution has a dependency on [feedparser](https://pypi.org/project/feedparser/).
> Create Standard Ebooks import job

- openlibrary/api.py
- scripts/copydocs.py
Makes it so that by default, when a work ID is specified, all its editions are also copied over.
- Also made it more resilient to partial errors, so one bad apple doesn't spoil the batch. We should create a new issue to discover why some of the batches are failing -- and maybe to make infobase give a better error than "Unable to connect to infobase server" :/
```sh
./scripts/copydocs.py /works/OL102584W
./scripts/copydocs.py /works/OL9170454W
```
TODO: Test some non-work things ; maybe also test `--no-editions` ? Does OptionParse define that?
@jimchamp
> Add entire work with copydocs.py

- static/css/components/illustration.less
Signed-off-by: Hitansh Shah <shah.hitanshsanjay.mat20@itbhu.ac.in>
Closes #5976 
I added a css property of `overflow-wrap: break-word;` under `.BookTitle` in static/css/components/illustration.less
Go to "https://openlibrary.org/works/OL25750067W/%C2%98Die%C2%9C_Hauptaufgaben_des_Volkswirtschaftsplanes_%C2%981974_%C2%9C_neunzehnhundertvierundsiebzig_und_der_Weg_zu_" and check the cover image of the book
@jimchamp
> Fixed the issue of title going out of bounds

- openlibrary/templates/login.html
Closes #5981 
Fixes padding Issue in the `login` button, now it works just the same as the `Sign Up` button.
Instead of using the `<input/>` tag in HTML, I have replaced it with `<button>` tag, this way the code is uniform with the signup page and the padding Issue is also solved.
@jimchamp
> Fixed padding issue in `Log In` button.

- openlibrary/templates/account/loans.html
- openlibrary/templates/books/custom_carousel.html
- openlibrary/templates/home/custom_ia_carousel.html
- static/css/components/mybooks-details.less
Closes #5979
If a patron has currently has no loans, display the following on the loans page:
- "Books We Love" carousel  [because of failure of creating the book we love carousel, instead I have replace it with 'Classic Books Carousel]
- "Browse by Subject" carousel
- link to our collections page (https://openlibrary.org/collections)
1. Add boolean paramater <compact_mode> to custom_ia_carousel, custom_carousel template which will determine the breaking behaviour
1.2 Set breaking [a:f] pareters [4, 4, 4, 3, 2, 1]for the compact design
2. Make css changes in mybooks-details.less to make my loan page's carousel's responsive
3. Add action button to my loan's page which redirects to collections page
1. Go to /accounts/loan 
2. DevTools Responsive Breakpoints
@jimchamp
> Fix add some useful components to empty loans pages

- openlibrary/core/sponsorships.py
- openlibrary/plugins/upstream/mybooks.py
- openlibrary/tests/core/test_sponsors.py
Closes #5801
Replaces CiviCRM call w/ Archive.org ElasticSearch queries (less reliance on additional services)
**NOTE:**
On staging, notes seems to be broken (but is working in production)
https://staging.openlibrary.org/people/mekBot/books/notes?debug=true
http://ol-dev1.us.archive.org:1337/people/mekBot/books/sponsorships
**When  on `sponsorships` tab**
**When not on `sponsorships` tab**
@cdrini @jimchamp @bfalling
> replacing civicrm call with elastic

- static/css/components/header-bar.less
- Will be able to logout properly after clicking
Closes #5982 
Fixes the logout button on the dropdown menu: makes the pointer cursor on hover and increases the width of the button
to actually logout on click.
Gave the form and button cursor: pointer; attributes and increased the width of the button to 100% of its parent (form).
Test by logging into openlibrary and hovering on the logout button/clicking it to make sure it logs out.
> fix(#5982) - Fixes pointer and width for the logout button

- static/css/components/footer.less
Closes #5986 
fix color of footer-icons 
Changes the css property from grey to dark-grey
@jimchamp
> fix Match color of page-banner and footer-icons

- openlibrary/plugins/openlibrary/js/carousel/Carousel.js
- openlibrary/plugins/openlibrary/js/graphs/plot.js
Closes #5955
Fix for UI regression
Largely inspired by the original functionality that got lost at some point, this restores the `plotselected` and `plotclick` event handlers but this uses events for communication between the graph module and the Carousel as the latter module has changed significantly since this functionality last existed in the codebase. The changes to Carousel should only come into effect when used on a publisher or subject page and should not affect it in any other way.
Fixes the UI regression described in #5955. Test filtering by clicking a year or dragging across a range of years, the Carousel should update with a suitable list of works from the selected date range or year.
> Restore date filtering functionality to publishers and subjects pages.

- openlibrary/plugins/upstream/covers.py
- openlibrary/templates/recentchanges/render.html
- static/css/legacy.less
Closes #29
Display newly added cover as comment in Recent Changes Table
Please check for any edge cases I missed.
1. Edit cover locally
2. Go to http://localhost:8080/recentchanges and check
@jimchamp @mekarpeles
> Display cover as comment in Recent Changes Table

- openlibrary/plugins/worksearch/code.py
Closes #4673
Fix book search sort. When work has no publish date and search result sorted by first published, work is sorted last.
Load books with and without publish date.
Search for these books and osrt by `First Published`.
Books without publish date should be displayed as last results.
I've used these OL books with no publish date for my testing:
- /books/OL13633902M
- /books/OL17326159M
- /books/OL17193542M
> Change old publish year sort request

- openlibrary/plugins/upstream/covers.py
Not sure what caused this to suddenly break linting; probably a mypy version update or something?
> Fix new lint error

- docker-compose.production.yml
- scripts/deployment/are_servers_in_sync.sh
- scripts/deployment/deploy.sh
- scripts/deployment/restart_servers.sh
- scripts/solr_restarter/Dockerfile
- scripts/solr_restarter/index.js
Closes #5343
This service responds to errors on the production endpoint, and restarts solr accordingly. This is ideally code we shouldn't have to write, but couldn't find how to make this work with docker's `healthcheck` -- it seemed like that was hard blocked for docker-compose users: https://forums.docker.com/t/unhealthy-container-does-not-restart/105822/3 . Since our healthcheck involves processing some JS as well, created a whole script for it :( 
1. Modify docker-compose.production.yml, and comment out `env_file` and `SEND_SLACK_MESSAGE=true`
2. Run `COMPOSE_FILE="docker-compose.yml;docker-compose.production.yml" docker-compose --profile ol-solr0 up -d`
3. Everything should start
4. Check the logs of solr_restarter ; should be saying "healthy".
5. Modify the TEST_URL to be …
> Add solr restarter service to autoheal solr

- openlibrary/book_providers.py
- openlibrary/plugins/upstream/models.py
- openlibrary/templates/type/edition/view.html
- openlibrary/templates/type/work/editions_datatable.html
Temporary shim for #4485 (to be replaced with a better solution (e.g. async editions table or iframe) later this quarter.
See performance plan notes:
https://docs.google.com/document/d/1buJASy3MbxQPYstoUGW_tAwC7UYTKfcejUm8xXsfAIc/edit#heading=h.doeu99u9fz8e
Some works on Open Library have 500+ editions, all of which get loaded in order to:
1. choose the best edition &
2. populate the editions table. 
This results in load times of up to 10 seconds. Halving this number would be a significant victory.
My experiences speaking to patrons and @JeffKaplan has given me some confidence that:
1. The average Open Library patron cares primarily about discovering readable books
2. The average patron uses the default editions table setting of "View 3" & won't notice any difference
3. Because of [1] …
> P1 book page performance fix

- openlibrary/plugins/upstream/borrow.py
Captures count of borrow failures due to outdated availability statuses. Will be used to determine if there is a spike of borrow failures after we disable the ground-truth availability checks for book page borrow buttons (PR #6078).
> Capture borrow failures

- openlibrary/macros/databarWork.html
- openlibrary/templates/type/edition/view.html
Adds additional profiling to the following book page components and functions.  Executions times for book page components can be found at the bottom of book pages that are served in debug mode.
| New Key | Description |
| --- | --- |
| databarWork: AffiliateLinks | Sidebar vendor links and prices |
| get_observation_metrics | Function for getching data that belongs in the review component |
| Review component | Component that displays review statistics for a work |
| databarWork: DonateModal | The sidebar DonateModal macro |
| databarWork: List widget | The sidebar lists/widget template |
| databarWork: LoanStatus | The sidebar LoanStatus macro |
| databarWork: Book provider | Time taken to fetch book provider and render download options |
In order to profile sidebar items, …
> Add more profiling to book page components

- openlibrary/plugins/openlibrary/api.py
Small hotfix. I often use `?limit=0` as a way to get only the size of the results, as a perf optimization.
- This is *technically* a breaking change to a public API, but hopefully no one is depending on it?
- ✅ Invalid limit doesn't error http://localhost:8080/authors/OL6848355A/works.json?limit=foo
- ✅ Limit of 0 works http://localhost:8080/authors/OL6848355A/works.json?limit=0
@jimman2003
> Allow ?limit=0 on author /works.json endpoint

- openlibrary/macros/StarRatings.html
- openlibrary/plugins/openlibrary/api.py
- openlibrary/plugins/openlibrary/js/Toast.js
- openlibrary/plugins/openlibrary/js/handlers/index.js
- openlibrary/plugins/openlibrary/js/index.js
Closes #
Attaches on submit listeners to all star ratings forms on a page.  On submit, the default page refresh is prevented and the ratings are submitted via JS.
If a submission fails, the rater is notified via toast message.
Replaced conditional rendering of "Clear my rating" button in template with conditional addition of `hidden` class, allowing the button's visibility to be toggled.
`FadingToast` constructor has been updated to prevent a `null` parent container being passed to the superclass Toast's constructor.
While logged in, do the following:
2. Leave a star rating.  Ensure that the "Clear my rating" button appears, the correct stars are filled,  and that the page does not refresh.
3. Refresh the page.  Ensure that the rating is as expected.
4. Clear …
> Async star ratings

- openlibrary/core/lists/model.py
- openlibrary/plugins/openlibrary/lists.py
- openlibrary/templates/lists/export_as_bibtex.html
- openlibrary/templates/lists/export_as_html.html
Closes #5868 
Modifies the current implementation for exporting lists, in which only **Edition** elements work as expected, as **Works* * and **Authors** don't work and give different results than expected respectively. This PR makes the export functionality follow the same behavior as the API.
From what I've gathered, the current implementation of the export functionality uses the following method:
https://github.com/internetarchive/openlibrary/blob/c63d733da0e1c9f294caa4eb3cbe341d1f3a4541/openlibrary/core/lists/model.py#L123
The way this method works, it searches for all of the editions related to a given author and work, which explains the reason that when exporting authors a complete list of all of their books is given. The reference for *works* is currently broken, that's why it …
> Add Excluded Works & Authors to List Exports

- openlibrary/plugins/openlibrary/js/partner_ol_lib.js
Closes #5586 
- Initially we were using archive.org APIs internally. This now switches them to use OpenLibraries APIs. 
- Instead of opening the borrow page of an edition directly like before, this changes it such that it opens the work page instead. From there, the edition to be borrowed can be picked by the patron. 
Here is a sample from BWB (no styling etc..)
@mekarpeles
> Migrating partner lib from archive.org to Openlibrary APIs

- openlibrary/plugins/upstream/covers.py
- static/css/legacy.less
Related to #5716 
I don't know why but on testing I can only see the covers changes done by me and not by anyone else.
I have tried to fix a few things which I noticed on testing.
Due to a PWA feature, any links with 404 image src will display OL Logo so adding height fixes the UI aspect
@jimchamp
> Improve Add Covers as Comment

- openlibrary/macros/EditionNavBar.html
- openlibrary/templates/type/edition/view.html
Closes #6096
Added `Lists` link to books page navbar after the `Reviews` link.
Added the id `lists` to the  [Lists containing this Book](https://openlibrary.org/works/OL16225732W/Life's_Handicap/lists) section.
@jimchamp  @mekarpeles
> Added Lists link to books page navbar

- openlibrary/templates/type/edition/view.html
Closes #6107
Removes the edition description from the #edition-details component.
@jimchamp
> Closes Remove repeated edition description from book pages

- openlibrary/core/formats.py
- openlibrary/core/helpers.py
Closes #5415
Creates custom JSON encoder which converts `Nothing` objects into `None`.  Adds encoder to `helpers.dump`.
`format.dump` appears to only be used in lists.py to return data related to lists.
This code is on testing now.  Compare the following list data in production and testing:
http://openlibrary.org/people/tmanarl/lists/OL197952L/seeds.json?debug=true
http://testing.openlibrary.org/people/tmanarl/lists/OL197952L/seeds.json?debug=true
The production link errors out, while the `Nothing` values have been replaced with `null` in the JSON string returned in testing.
> Create custom JSON encoder for Nothing values

- openlibrary/core/schema.sql
Change has been made on prod, shouldn't affect any existing code. Will be used for trending books, etc. next step is to loop over patrons w/ private reading logs and set books to be private, e.g. `http://openlibrary.org/query.json?type=/type/object&notifications.public_readlog=no`
Closes #
> adds privacy column to bookshelves_books

- openlibrary/core/vendors.py
Closes #6089 
hotfix
Currently added the file name of the placeholder image that we could find online, the filename might change in the future.
@jimchamp @mekarpeles
> Closes ImportBot importing non-covers (For Amazon Imports)

- openlibrary/core/bookshelves.py
- openlibrary/templates/stats/readinglog.html
- openlibrary/templates/trending.html
- openlibrary/utils/dateutil.py
- openlibrary/views/loanstats.py
- static/css/base/common.less
From 2022 Roadmap: build on https://openlibrary.org/stats/readinglog (prereq for following patrons #739 + #1964 #857 #3449)
Shows a ~realtime list of books being logged by patrons
**This should definitely be a homepage carousel, cached every 5 minutes!**
Try it here: http://ol-dev1.us.archive.org:1337/trending
> Adding trending view

- openlibrary/core/schema.py
- scripts/import_standard_ebooks.py
Include languages in the import item from standard ebooks feed.
> Make standard ebooks importer include language field + fix som errors

- openlibrary/templates/book_providers/standard_ebooks_download_options.html
This just in: Not all books are _As You Like It_ by William Shakespeare.
- Please squash these commits when merging.
- Try clicking on the Kobo link https://openlibrary.org/books/OL37044422M/The_Time_Traders  and on testing.
> Fix standard ebooks download links

- openlibrary/plugins/upstream/models.py
Closes #6134 
If no solr data for edition, bypass get data provider and instead use infogami
ol-dev1.us.archive.org:1337](http://ol-dev1.us.archive.org:1337/books/OL35552510M/Community-Based_Monitoring_in_the_Arctic?debug=true?
@jimchamp @seabelis
> fix books page get_sorted_editions w/o solr

- openlibrary/macros/LoanStatus.html
- openlibrary/macros/databarWork.html
- openlibrary/templates/type/edition/view.html
Disables ground-truth availability calls for book page main borrow buttons.  Adds additional profiling to LoanStatus.html.
@mekarpeles
> Disable ground-truth availability checks

- openlibrary/macros/SubjectTags.html
- openlibrary/templates/type/edition/view.html
Closes #6106
In order to help guide our book page redesign, we would like to understand how patrons are interacting with our book page subject links. More specifically, we'd like to know how often the subject links in the overview are clicked vs. the subject links in the work component, which is located below the fold.
Added the different tags through parameter in the `render_subjects` function in the SubjectsTags.html file. Also in order to find if the link is in the  **work** section or the **overview** section, an additional parameter named `location` is used in order to figure out where the link is.
@jimchamp @mekarpeles
> Added google analytics to subject clicks on book page

- openlibrary/templates/type/edition/view.html
Closes https://internetarchive.slack.com/archives/C075DJ6G1/p1644695599802139
> fix selected edition availability

- openlibrary/templates/type/edition/view.html
Closes #6150
Removes unused variable `book_description` from the edition page template.  Sometimes, `AttributeError`s are thrown when this variable is set.
> Prevent new book page rendering errors

- openlibrary/templates/type/edition/view.html
- openlibrary/templates/type/work/editions_datatable.html
Closes #6133
Ensures that the "Add another edition?" link is present, even if there are no editions.
Replaced `editions` check in `editions/view.html` with an `editions` check inside of the `editions_datatable.html` template.  Table in the template now only renders if there are editions present.
> Always render add edition link

- scripts/oldump.sh
The linux utility `logger` is blocking our monthly data dumps
Testing was done by @mekarpeles and @cclauss on ol-home0.
> Datadumps: logger is blocking the cron job

- scripts/oldump.py
- scripts/oldump.sh
- scripts/sitemaps/sitemap.py
Fixes #5402 
Run `oldump.py` on Python 3.9, not Python 2 or Python 3.5.
`#! /usr/bin/env python` --> `#! /usr/bin/env python3`
The trouble was that we have two versions of Python 3 on `ol-home0`:
* /usr/bin/python3 is v3.5.2
* /home/openlibrary/.pyenv/shims/python3 is v3.9.4
`root` sees the second but when we `su openlibrary` in the cron job, we go back to seeing the first.
Proposed solution: In `oldump.sh` ensure that we are using pyenv's Python v3.9.
> Fix shebang lines in scripts/oldump.py and scripts/sitemaps/sitemaps.py 

- scripts/setup_olserver.sh
- Olsystem component: https://github.com/internetarchive/olsystem/pull/147
I didn't test running the script, but ran each command individually while updating our prod servers
> Add internal-only ferm rule setup to provisioning script

- openlibrary/core/lending.py
- openlibrary/i18n/pl/messages.po
- openlibrary/templates/books/RelatedWorksCarousel.html
See on Sentry: 
- `get_availability failed` ; 50% of all errors -\_- https://sentry.ux.archive.org/organizations/ia-ux/issues/1152/?project=7&query=is%3Aunresolved
- Polish homepage erroring due to bad translation string https://sentry.ux.archive.org/organizations/ia-ux/issues/1199/?project=7&query=is%3Aunresolved
To create issues for:
- The `get_available` flow and related works carousel was suuuuper circuitious. We should
- update that to hit solr instead of IA; solr is faster + more reliable in this case
- Why is it making a second DB request for the work in the `partials` endpoint when we can just pass forward the subjects/authors in the lazy element? Or is it relying on memcache? Either way, we should remove remove that weird joint `get_author_and_subjects` function, passing it as …
> Fix high volume sentry errors

- openlibrary/templates/account/books.html
- openlibrary/templates/type/edition/view.html
Renames some component time keys on the books page.  No new profiling was added to this page.
Adds shallow profiling to 'My Books" page template (`.../templates/account/books.html`).
> Profiling updates

- openlibrary/macros/LoanStatus.html
Closes #6184
The root cause of this bug is that it is possible for `wlsize` to incorrectly be `None`.  Pulling the number of folks waiting from `waiting_loan` corrects the page not rendering, but other issues remain:
1. After joining the waitlist, the primary borrow button and the edition table borrow buttons are mismatched.
2. "Join Waitlist" button incorrectly states that you;l be the next to borrow the book.
Both issues can be observed in this screenshot:
For the edition referenced in the issue, bulk availability is not returning the waitlist count, but the ground-truth availability API is:
https://archive.org/services/availability?identifier=shadowbone0000bard
https://archive.org/services/loans/loan/?action=availability&identifier=shadowbone0000bard
Not sure if this is due to a data …
> Correct waitlist LoanStatus.html error

- scripts/partner_batch_imports.py
After some experimenting, some records may succeed. Now that the script is running again, will wait until next month to see how many records are successfully imported when author assertion is enabled. If none or few, will follow-up with partners and add a unit test for author v. missing author (same for publish_date which is currently listed as required)
Closes #
> re-enabling authors

- openlibrary/macros/daisy.html
Closes #6183
Removes reference to `page` in Daisy macro.  The macro appears to only be called from `LoanStatus.html` with a properly constructed URL.
@mekarpeles
> Remove reference to `page` in Daisy template

- openlibrary/templates/subjects.html
This minor change addresses the underlying complaint in issue #2375 — that the subject page is a dead-end from which it isn't possible to get to a list of all the works that match the subject (/time/place/person/etc), which is kind of what you expect the subject page to do. I'll let someone else decide whether it actually closes the issue.
This fix adds a link to the text "N works" next to the subject title; the link performs a work search for that subject. 
I would have liked to have formed the search URL based on the subject term slug in the page URL, but that value isn't trivially available in the environment, so I copied the behavior elsewhere on the template of using a minimally-encoded page name string.
Visit a variety of subject pages and see if the search link works as expected. …
> Make subject page work count a link to search results

- openlibrary/core/cache.py
Closes #5753 
fix
I have added code to check for variables of Nothing type and replace it with an empty array, before that variable gets passed into json.dumps. The change has been made in json_encode functions used while caching.
@jimchamp
> Encode Nothing values for memcache

- static/css/components/language.less
Language dropdown menu CSS was being applied to other menus and breaking them
@mekarpeles
> Fix Language Dropdown Menu CSS being applied to other menus

- docker/Dockerfile.olbase
- docker/Dockerfile.oldev
Closes #6224
Fix. Apparently:
> All new files and directories are created with a UID and GID of 0, unless the optional --chown flag specifies a given username, groupname, or UID/GID combination to request specific ownership of the copied content.
https://docs.docker.com/engine/reference/builder/#copy
Why this never broke stuff before? No clue. Could be because we updated to node 16. Could be because of a docker update.
- ✅ Test on gitpod
- Didn't test on linux ; but fixing gitpod is already win :P
> Fix EACCES errors with package*.json

- openlibrary/api.py
- scripts/copydocs.py
Useful for testing edition-level solr things
- Reviewing commit-by-commit is easiest:
- Switched this script to use FnToCLI
- Added a search cli argument
```sh
mkdir foo
PYTHONPATH=. ./scripts/copydocs.py --dest foo --search "publisher:librivox AND NOT title:blah AND edition_count:[1 TO 5]" --search-limit 5
```
@jimchamp
> Add ability to copydocs from solr search query

- .gitpod.yml
Don't need this running on all renovatebot's PRs; it's slow!
> Disable gitpod auto-build on self-PRs

- openlibrary/templates/type/edition/view.html
Closes #6172
Makes book page work descriptions collapsible.
1. Navigate to a book page that has a lengthy work description.
2. Scroll to the work details component, found below the editions table.
3. Ensure that the work description is truncated, and that a "Read more" link is present below the description.
4. Click the "Read more" link.  Ensure that the entire description is displayed, the "Read more" link is hidden, and a "Read less" link is present.
5. Click the "Read less" link.  Ensure that the description assumes its previous truncated form.
> Add collapsible work descriptions

- openlibrary/plugins/upstream/models.py
- openlibrary/templates/type/edition/view.html
Addresses performance issues on books pages w/ lots of editions + ebooks
By default, fetch up to 10 ebooks.
Otherwise, fetch 3 featured editions **with covers** (if possible)
Test https://testing.openlibrary.org/works/OL66554W/Pride_and_Prejudice
@cdrini @jimchamp @seabelis @mheiman
> phase 2 editions table perf

- .gitpod.yml
> Fix boolean set to wrong value

- openlibrary/plugins/upstream/utils.py
- openlibrary/templates/lib/nav_foot.html
Closes #6153 
The query parameters were not included earlier from the user's url while reporting a problem. This Pr fixes that by concatenating the query part of the url.
@cdrini Please review this and let me know if any change is to be done. :smile:
> query parameters are included in the url returned by report a problem

- openlibrary/templates/work_search.html
Prevents bookshelf query for search results if patron is not logged in.
> Prevent bookshelf queries when logged out

- openlibrary/core/bookshelves.py
- openlibrary/plugins/upstream/mybooks.py
- openlibrary/templates/work_search.html
Fetches all reading log entries at once on search results pages if the patron is logged in.
> Add bulk reading log query

- openlibrary/templates/type/edition/view.html
Use edition_count to ignore limit and show all books if total editions_count < 10.
Moved editions_count up (which hits solr). Can this ever fail? When it does, edition_count is set to 1. Can this cause problems?
> Show editions table w/o limit if < 10 editions

- openlibrary/solr/update_work.py
- openlibrary/tests/solr/test_update_work.py
get_pub_year already supports ISO dates, as well as simple year strings, so it is an easy fix for the issue described in #6021. I don't believe this can have any negative side effects, it will simply extend support to ISO 8601 formatted dates without affecting dates currently indexed normally as get_pub_year falls back to re_year.search if re_iso_date doesn't match.
Closes #6021
fix
This is a fix as currently the document indexed by SOLR for works with only ISO dates doesn't have the "first_published_year" attribute, causing the UI issue described in #6021.
Add a work and edition with an ISO 8601 format date and look at the SOLR index for that work, you should notice the lack of "publish_year" and "first_publish_year" attributes. This affects worksearch, and the UI as described in #6021. …
> Use SolrProcessor.get_pub_year to get edition years

- openlibrary/plugins/openlibrary/js/edition-nav-bar/index.js
The "Overview" navbar item was not being selected upon scrolling to the top of the page in Chrome and Safari, due to mishandling of bounds checking for zero-height elements.  This has been corrected.
> Fix navbar scroll listener

- openlibrary/plugins/worksearch/code.py
You can now search for number of editions; eg. `editions:10` or `editions:[* TO 100]`
> Expose edition_count as "editions" in search

- openlibrary/macros/SubjectTags.html
- openlibrary/plugins/openlibrary/js/readmore.js
- openlibrary/templates/site/head.html
- openlibrary/templates/type/edition/view.html
- openlibrary/templates/type/work/editions_datatable.html
- static/css/components/work.less
> Moving subjects up, show more, nojs

- .github/workflows/javascript_tests.yml
Because we cache the entire node_modules directory, we don't need to run npm install at all if there are no changes to package-lock files. So let's not! Saves ~30s (18%) on JS CI.
Following docs from https://github.com/actions/cache#Skipping-steps-based-on-cache-hit
> Skip npm install if cache hit in GHA

- scripts/oldump.sh
@cclauss for you to review + update pls
These changes may not clean up files correctly after running -- we may want to add this part to the cron rather than this file (so when the cron is kicked off, it cleans up if the step is necessary). We don't want to remove the files the top of this script because it will negate the work of saving our place and gracefully restarting if we hit + fix an error
One error we had was around admin collections permission for the /olsystem ia.ini role user s3 account (which has since been fixed). It needed permission for ol_export
Q: Can we (e.g. using `xauthn` make a request to see what our permissions are as a e.g. regressions rest)
cc: @jimbonator 
@cclauss  @cdrini
> fix oldumps

- openlibrary/core/lending.py
Fixes a problem introduced via https://git.archive.org/ia/petabox/-/merge_requests/3118
We still had code which was using `collections` to determine availability. Now Bulk Availability API (see https://archive.org/services/availability?identifier=lostfound0000coec) should be much more robust (includes new reliable fields)
> rm collection checks for Bulk Availability changes

- openlibrary/templates/type/edition/view.html
Closes #6271
Corrects error that occurs whenever an element is accessed from an empty `editions` list.
> Remove unneeded declaration

- openlibrary/templates/type/edition/view.html
This PR includes two book page changes:
1. Work descriptions are only displayed once per page.
2. Work-level classifications are removed altogether.
> Book Page: Deduplicate work description / Remove work-level classifications

- openlibrary/plugins/openlibrary/js/edit.js
Closes #6293
fix
Modified initEdit function to only trigger focus and scroll if explicitly requested in URL; 
also replaced deprecated substr() call with substring().
https://openlibrary.org/books/OL35615701M/The_Game/edit
should load the edit page with no jumping.
https://openlibrary.org/books/OL35615701M/The_Game/edit#edition/subtitle
should focus and jump to the edition subtitle field.
@cdrini @mheiman
> Disable "auto focus/scroll" on edit page

- openlibrary/core/lending.py
- openlibrary/core/waitinglist.py
Closes #6304
Prevents book page loan status and waiting list queries using obsolete usernames (having the format: `ol:${username}`)
Calls made to `userkey2userid` will return obsolete `ol:foo` user identifiers.  Seeing this function in our code should indicate that said code may need to be updated.
1. While `tail`ing the web logs, visit a book page.
2. Ensure that only one call each is made for loan status and waiting list status.
@mekarpeles
> Prevent loan/waiting list status calls with old-style username format

- openlibrary/core/lending.py
- openlibrary/macros/BookPreview.html
- openlibrary/macros/LoanStatus.html
Closes #6302
1. Before, Preview was not showing up on mek's account (because it uses print-disabled access for testing)
2. The `update_availability_schema_to_v2` adapter had an incorrect/incomplete definition for `is_lendable` which did not consider the `borrow_unavailable` cases, which resulted in us not showing the Checked Out
3. The changes to Bulk Availability API haven't been `pi`'d and so some books were returning `error` because Bulk Availability didn't have access to `printdisabled` scope and thus returned `error` status, causing Ground Truth API to be called. On testing, we used the deploy app from archive.org to confirm that values are now correct
> Fixes CTA + lending v2 fields

- openlibrary/macros/SubjectTags.html
- openlibrary/plugins/openlibrary/js/readmore.js
- static/css/components/work.less
Changes the cursor when hovering over a `.clamp`ed subject.  Toggles leading character to either `+` or `-` on click.
> Add visual feedback for subject clamp

- openlibrary/macros/LoanStatus.html
Tags on to #6303 (forgot to add this patch to PR) 
This should show "special access" for patrons with certified print disabilities when book is_lendable but borrow_unavailable
> tag-on to cta btn changes, fixes pd

- renovate.json
Fix eg `pytest` missing from #6234 .
> Configure renovate to read all requirements*.txt

- openlibrary/macros/EditionNavBar.html
- openlibrary/templates/type/edition/view.html
Consolidates the book page edition and work details components into a single component.
Redundant publisher line has been removed from the new component.
> Create details component for books page

- openlibrary/templates/type/edition/view.html
- static/css/components/work.less
Moves books page list section into the main content area.  Now the navbar will remain in view when the lists section is displayed.
> Move books page list section

- openlibrary/templates/type/edition/view.html
- static/css/components/work.less
In order to aid librarians, the following changes have been made:
- Important identifiers are now available above the fold (for usergroup `librarians`).
> Add book identifiers above the fold for librarians

- openlibrary/catalog/add_book/__init__.py
On reimporting existing editions:
* Prevents empty lists being written to the record
* Closes #4978
* Closes #5671
* Writes any new identifiers (e.g. DNB id) to a matched edition
* Writes OCLC numbers to a matched edition
Previously OCLC number and other identifiers were not added to existing editions if a match was found.
> Small import improvements

- openlibrary/coverstore/server.py
- tests/test_docker_compose.py
Convert Python type comments to [type hints](https://docs.python.org/library/typing.html)
Avoid `solr` related files because of Cython.
> Convert Python type comments to type hints

- static/css/components/work.less
Closes #6288
Offsets the sticky position for mobile books page navbars by the height of the header.  This prevents the navbar from being stickied "behind" the header.
> Fix books page sticky navbar for mobile views

- openlibrary/templates/type/edition/view.html
- openlibrary/templates/type/work/editions_datatable.html
- static/css/components/work.less
This PR attempts to resolve any feedback given for the recent books page PRs.  The following changes have been made:
- Prompt to see all editions moved above editions table
- Horizontal rule above editions table has been removed
- Singular case handled correctly when one featured edition is displayed in the table
- Removed OLID from omnibar
- Add border around table
> Implement books page feedback

- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/plugins/openlibrary/js/readmore.js
Solves issue where subject clamper functionality is only imported when there is a "Read more" link on the page.
@mekarpeles
> Initialize clampers independently

- openlibrary/utils/sentry.py
Convert Python type comments into type hints.
> Type hints for openlibrary/utils/sentry.py

- openlibrary/macros/EditionNavBar.html
- openlibrary/macros/SubjectTags.html
- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/plugins/openlibrary/js/readmore.js
- openlibrary/templates/site/head.html
- openlibrary/templates/type/edition/view.html
- openlibrary/templates/type/work/editions_datatable.html
- static/css/components/work.less
Followup re: #6277 
on http://ol-dev1.us.archive.org:1337/
@cdrini @seabelis @mekarpeles @jimchamp @mheiman @bfalling
> Books page integration

- openlibrary/templates/type/edition/view.html
Prevents redirect by using the correct archive.org URL for above-fold OCAIDs.
> Use correct archive.org URL

- conf/openlibrary.yml
- openlibrary/data/dump.py
- scripts/oldump.sh
As discussed in several issues related to #5402 our [data dumps](https://github.com/internetarchive/openlibrary/wiki/Generating-Data-Dumps) can be quite tricky so this PR logs data dump error output into [Sentry](https://docs.sentry.io/platforms/python) to ease debugging.
See the cron workflow at #5892
> Data Dumps: Add Sentry error logging

- scripts/oldump.sh
This folder exists in the tmpdir not in the parent of the tmpdir.
Ran the full data dump job as part of #6306 and it worked!
> [oldump] Fix oldumpsort location

- docker-compose.override.yml
- docker-compose.production.yml
- docker-compose.yml
- docker/Dockerfile.olbase
- docker/Dockerfile.oldev
- docker/README.md
- docker/docker-entrypoint.sh
- scripts/oldump.sh
- scripts/solr_builder/Dockerfile.olpython
Closes #5514
A second attempt at #5514 with sync to master plus mods to `conf/bashrc` and `scripts/setup_gitpod.sh`
Switch olbase to use [`python:3.9.4-slim` Docker image](https://hub.docker.com/_/python) instead of `ubuntu:xenial`
- Turns out this is a pre-existing issue unrelated to the changes here; tackle separately in #6316
> Switch olbase to use python:3.9.4-slim image instead of ubuntu:xenial -- AGAIN

- docker/Dockerfile.oldev
Addendum to #6306 . Running pytests failing locally.
- Oops I forgot to set commit message; please squash + merge and set the commit message to the name of the PR!
@cclauss
> Add pytest to local env PATH

- bundlesize.config.json
- openlibrary/macros/SubjectTags.html
- openlibrary/plugins/openlibrary/js/index.js
- openlibrary/plugins/openlibrary/js/readmore.js
Changes clamper symbols from "+" and "-" to a small right-pointing triangle and a small down-pointing arrow, respectively.
Only adds clamp symbol and click listener if the content is able to be clamped.
Blocked until #6323 is merged. Alternatively, this can be merged into the `books-page-integration` branch.
> Add subject clamping conditionally

- scripts/partner_batch_imports.py
in this commit a new function is added that checks a book's title and other attributes for known exclusions.
The effect of this commit is that, the importbot will discriminate low quality books
Closes #4151 
hotfix
This is not a complete solution yet, it is just an initial try
The importbot must be its periodic imports, filtering books that have the keyword "Notebook" in their titles and the publisher is independent publisher.
> importbot importing books that are of bad quality

- openlibrary/book_providers.py
- openlibrary/plugins/upstream/models.py
- openlibrary/templates/type/edition/view.html
Closes #6339 
The Books Page only requests a certain number of ebook editions by default when the work has more than e.g. 10 editions.
A problem occurs when a work edition is requested by url e.g. http://ol-dev1.us.archive.org:1337/works/OL17732W/Bible?edition=catholicyouthbib00wino but the corresponding edition with this edition identifier is not available / hasn't been fetched by get_sorted_editions (because of this limit).
As a result, a refactor was required which allows us to tell work.get_sorted_editions that we explicitly wish to include the aforementioned edition (having ocaid catholicyouthbib00wino) into the set of returned editions.
> Ensure requested work edition fetched

- openlibrary/templates/type/edition/view.html
Corrects the following book page issues:
1. Physical object data not present in work pages, even if best-fit edition has this data.
2. Some ISBNs missing from the omniline
3. Book Details component has needless `edition` check.
_Physical object data now present in book details._
_All ISBNs listed in omniline._
@seabelis
> Misc books page fixes

- openlibrary/data/dump.py
- openlibrary/tests/data/dump.py
Closes #6348 
* Partially revert https://github.com/internetarchive/openlibrary/commit/9403742e7a7509b2b0cb9aad24727e39a7850fae to make sure the process records is json.dumps and printed.
* Place filter in the righter ordering from https://github.com/internetarchive/openlibrary/commit/9403742e7a7509b2b0cb9aad24727e39a7850fae
* Add unit tests!
```sh
curl -L 'https://archive.org/download/ol_dump_2022-03-29/ol_dump_authors_2022-03-29.txt.gz' | zcat | grep -F '/a/' | head -n1
/type/author      /authors/OL6725672A     2       2009-09-08T12:14:54.827520     {"bio": {"type": "/type/text", "value": "Translator to English of [Astrid Lindgren](/a/OL24950A)'s <i>Pippi Longstocking</i> (from Swedish) and works by [Knut Hamsun](/a/OL41785A) (from Norwegian)."}, "name": "Gerry Bothmer", "created": …
```
> Fix wrong keys data dump + internal ID field in dumps

- openlibrary/templates/type/edition/view.html
The books page "Lists containing this Book" section typically has two rows: The first displays lists that contain the work; the second, lists containing the editions.  On work pages, both of the rows are the same.
This PR removes the edition lists from work pages.
> Render edition lists only on edition pages

- openlibrary/plugins/upstream/addbook.py
Closes #6346
Fixes the problem of line breaks in tag fields (subjects/places/times/people) causing items after the line break to be lost.
I had hoped that the csv.py library being used to parse tag data would have a configuration option to ignore line breaks, but the documentation indicates that the reader() method explicitly ignores attempts to redefine line breaks (which is what caused the bug in the first place).
Failing that, the best solution seemed to be to just strip out any line breaks immediately before parsing. I tested on both Mac and Windows to verify that the form is sending \r\n regardless of platform.
Edit a work subject list, adding a line break between entries. They should now all save correctly.
@seabelis @cdrini @mekarpeles 
Attribution Disclaimer: By proposing this …
> Handle newlines in tag editing

- openlibrary/core/processors/readableurls.py
Closes #
I noticed that the readable URL processor wasn't handling lists of people with dashes in their usernames.  This causes list URLs that contain the human-readable list name slug to fail with a `404` if the list creator has a dash in their username.  Updating the list URL pattern has corrected this issue.
The list pattern has been updated to allow dashes before the list OLID in the URL.
1. Navigate to the following URLs:
- Production: https://openlibrary.org/people/agent-lisa/lists/OL206833L/ala_challenged_2018_w
- Testing: https://testing.openlibrary.org/people/agent-lisa/lists/OL206833L/ala_challenged_2018_w
2. Observe that the production link results in a `404`, while the testing link renders as expected.
3. Visit some of your own list pages. Ensure that they render properly, and …
> Allow dashes in list URL pattern

- openlibrary/plugins/openlibrary/sentry.py
- openlibrary/plugins/openlibrary/stats.py
- openlibrary/plugins/upstream/account.py
Use [`com2ann -v 9 .`](https://pypi.org/project/com2ann) to convert Python type comments into type hints.  Avoid changes to `solr` code which uses Cython.
> com2ann: Convert Python type comments to type hints

- openlibrary/catalog/add_book/__init__.py
Apologies @mekarpeles , this needs one more fix.
The Edition model was hiding the raw `identifiers` dict, it looks like `Edition.dict().get('identifiers')` is the most reliable way to get the raw identifiers.
`Edition.get_identifiers()`  combines other values, and `Edition.identifiers` is always `None`.  
I have tested this locally now after getting the Docker images back up.
For matching, modifying, and creating new records from https://archive.org/details/marc_dnb_202006 MARC records.
> Fix for adding identifiers, correct modified / matched status

- openlibrary/plugins/openlibrary/home.py
According to Sentry, `home.readonline_carousel()` has returned `None` at least 33k times because one of the books does not have an `.is_readable` attribute.  https://sentry.archive.org/organizations/ia-ux/issues/24173 (2nd most common issue)
This PR would not store and return books that do not have `.is_readable` attribute but would allow other books which are readable to be stored and returned to the caller.
Closes https://sentry.archive.org/organizations/ia-ux/issues/24173
> Fix `readonline_carousel()` if any book has no `is_readable` attribute

- openlibrary/tests/data/test_dump.py
refactor
This uses a pytest fixture [capsys](https://docs.pytest.org/en/6.2.x/capture.html#accessing-captured-output-from-a-test-function)
These test should output the same results as the previous version
@cdrini
> Replace SpyPrint with capsys fixure

- openlibrary/data/dump.py
refactor
Make a successful dump :)
@cdrini
> Remove some unused functions in dump.py

- openlibrary/data/dump.py
refactor
print argument was used for tests, not really needed anymore
This change shouldn't require testing
@cdrini
> Remove print argument in print_dump

- openlibrary/plugins/upstream/utils.py
- openlibrary/templates/type/edition/view.html
Also properly i18n the list here
Closes #6406
- https://openlibrary.org/works/OL21191421W/Beginnings_of_the_Cult_of_Relics no longer leaks
- Tested on gitpod
- List of names now localize correctly: https://openlibrary.org/works/OL264243W/Famous_Modern_Ghost_Stories?edition=ia%3Afamousmodernghos00scar&lang=zh
@jimchamp @tfmorris
> Fix XSS in author name rendering

- openlibrary/i18n/cs/messages.po
- openlibrary/i18n/de/messages.po
- openlibrary/i18n/ja/messages.po
- openlibrary/i18n/pl/messages.po
- openlibrary/i18n/te/messages.po
Closes #3729 . This adds just the German additions to the messages.po file ; any changes to the strings were too difficult to untangle for me, so I just chose to use the default where available. This added ~1% coverage to our German translations! Some of the added strings are no longer part of our HTML unfortunately, but I they'll be handled correctly next time we regen the .po files.
I found some useful commands! Here's what I ran. I downloaded the final `messages.po` from #3729 , and then used a `gettext` function called `msgcat` to concatenate the two po files, choosing translations from the current master branch in cases where there was a conflict:
```sh
docker-compose run -u root --rm --no-deps web bash -c "
apt-get update && apt-get install -y gettext
su openlibrary -c '
msgcat …
```
> Apply bitnapper's German translation fixes

- static/css/base/common.less
Closes https://github.com/internetarchive/openlibrary/issues/6399
Accessibility
This pull request achieves fixing accessibility issues firstly in the Login page and other pages too. We noticed that the accessibility issue stated in #6399  applies to more pages and not only the Login page. So we removed the outline attribute from the common.less file to fix the issue in all the pages.
Removed the
```
button {
outline : none
}
```
from the common.less file.
Start from the top of the Login Page and using the tab button, while scrolling down, the login button does not get focus as it is supposed to. This applies to other pages to, such as the edit profile page.
@mekarpeles
@cdrini
Attribution Disclaimer: By proposing this pull request, I affirm to have made a best-effort and exercised my …
> Fix Accesibility issues on the Login page concerning a button not getting focus

- openlibrary/macros/StarRatingsStats.html
- static/css/components/readerStats.less
> Fix the 'When no star ratings on book, UI looks weird #6411' bug

- openlibrary/core/booknotes.py
- openlibrary/core/bookshelves.py
- openlibrary/core/db.py
- openlibrary/core/models.py
- openlibrary/core/observations.py
- openlibrary/core/ratings.py
- openlibrary/plugins/admin/code.py
- openlibrary/tests/core/test_db.py
- openlibrary/tests/core/test_models.py
- Each feature type (i.e. bookshelves, ratings, observations, booknotes) inherits from db.CommonExtras
- Result shows occurrences of redirect works per type (bookshelves, ratings, observations, booknotes)
- Handles chains of redirects
- _test=True / ?test=true flag to db rollback/abort transaction
Closes #5999 
**NB** For any given category (e.g. ratings, booknotes, bookshelves, observations -- let's pick ratings), there is an edge case that a work of type redirect (e.g. work OL123W) will need to resolve to its active work (e.g. OL234W) but this active work already has a db entry in the db (e.g. if the patron has a rating in the db for both OL123W and OL234W). In this case, the transaction of updating the redirect work (e.g. OL123W) to the active work (e.g. OL234W) will fail because of a …
> API to resolve redirects for single work

- static/css/components/book.less
Closes #6369
[Fix]
This PR sets the width for books on the publisher page that _don't_ have a cover image.
I updated the Less to set the width for anchor tags in the "book-cover" class to be a 100%.
> BUG: 6369 Add correct width to book covers with no image.

- openlibrary/templates/type/edition/view.html
Made the caption "Previews available in:" appear only when they are available preview languages.
Closes #6408 
@jimchamp
> Fix "Previews available in:" sometimes displayed without any preview languages #6408 

- static/images/icons/share.svg
In support of #4578
Adds a share icon to our static images.
> Add share icon

- openlibrary/templates/home/welcome.html
- [Fix Fulltext search card using wrong GA event](https://github.com/internetarchive/openlibrary/commit/51b4a799fca03a0bd53785131d90d69f1c89d8a7)
- [i18n fulltext onboarding card](https://github.com/internetarchive/openlibrary/commit/5b2e7797acee4b22c3be8c027cba89ec86807d73)
- [Place LibraryExplorer card before fulltext card](https://github.com/internetarchive/openlibrary/commit/4944a322605c8a02852d3b321453f187937c70b2)
- The ordering was causing a reduction in traffic to LibraryExplorer, without a corresponding rise in traffic to search inside.
- Carousel looks right in testing: testing.openlibrary.org (after memcache delete: https://testing.openlibrary.org/admin/inspect/memcache?keys=home.homepage.en-&action=delete )
> Fix fulltext card issues + Re-order onboarding cards

- openlibrary/plugins/upstream/addbook.py
- openlibrary/plugins/upstream/spamcheck.py
Closes #6363
Spam checks for adding new books and editing works and editions are now skipped if the request was submitted by an admin or librarian.
Spam checks for creating new lists and updating patron profiles have not been affected.
New boolean parameter `allow_privileged_edits` has been added to `is_spam()`.  If ever we want to bypass list and profile spam checks, we need only add the parameter to those `is_spam()` calls.
Test BAU functionality:
1. Log in as a non-privileged patron.
2. Attempt to add a book that contains a spam word in it's title.  Expect this to fail.
3. Navigate to a book page and click the edit button. Attempt to add a spam word to any edition field and submit the form.  This should fail.
4. Repeat step three, but add a spam word to a work field instead.  Expect …
> Override spam checks when adding or editing books
