scripts/deployment/deploy.sh

Closes issues discovered on https://github.com/internetarchive/openlibrary/releases/tag/deploy-2021-02-04

Updates to deploy.sh

---

openlibrary/catalog/importer/db_read.py

Related #2852 
Refactor db_read.py to replace urlopen with requests.   
```python
from openlibrary.catalog.importer.db_read import *
read_from_url(api_get()+'/works/OL86707W')
```
```json
{'description': "Stellaluna is a baby bat, but she lives in a bird's nest with a bird family. How did she get there? Will she ever find her bat family? --back cover", 'links': [{'url': 'https://en.wikipedia.org/wiki/Stellaluna', 'title': 'Stellaluna - Wikipedia', 'type': {'key': '/type/link'}}, {'title': 'Stellaluna - Storyline Online', 'url': 'https://www.storylineonline.net/books/stellaluna/', 'type': {'key': '/type/link'}}, {'url': 'https://www.rom.on.ca/en/rom-at-home/rom-storytime/stellaluna-by-janell-cannon', 'title': 'ROM Storytime: “Stellaluna” by Janell Cannon | Royal Ontario ...', 'type': …
```

Refactor db_read.py to replace urlopen with requests.

---

static/css/base/common.less

Fix list-item markers outside content body

---

openlibrary/core/helpers.py

Closes #4586
Reverts internetarchive/openlibrary#4557

Revert "Fix Nothing is not JSON serializable"

---

openlibrary/templates/account/borrow.html
openlibrary/templates/admin/loans_table.html
openlibrary/templates/admin/people/view.html
openlibrary/templates/admin/waitinglists.html
openlibrary/templates/borrow_admin.html
package-lock.json
static/css/components/borrowTable.less
static/css/legacy-borrowTable-adminUser.less
static/css/page-plain.less

Closes #
There are two file that have id at two places so for fixing that i conveerted all the places of borrowtable id into class
@jamesachamp @jdlrobson

BorrowTable id converted to class

---

static/css/components/dropper.less
static/css/components/work.less
static/css/legacy-datatables.less

Related to #4522 (**Closes**)
https://wave.webaim.org/report#/https://openlibrary.org/works/OL66347W/The_Crucible
Fixes Work line contrast issue.
Fixes Want to Read Contrast issue.
Fixes Search Contrast issue.
Also, fixes Want to Read me Border
New:
Old:

Fix Book Page Color Contrast

---

.gitmodules

- i.e. Fix HTTP_LANG cookie not being read
- Also no longer ignore vendor/infogami mods
Closes #
@cclauss @0dysseas

Update infogami to master

---

openlibrary/tests/core/test_fulltext.py

Jenkins is failing Python 2 tests.
@dherbst

from mock import Mock, patch for Python 2 and 3

---

openlibrary/components/LibraryExplorer.vue
openlibrary/components/LibraryExplorer/components/LibraryToolbar.vue
openlibrary/components/LibraryExplorer/configs.js
openlibrary/plugins/worksearch/languages.py
package-lock.json
package.json

Closes #
Want to add this, but couldn't find an elegant way to do it, so debug=true only for now.

[library-exporer] Option to select language + styling tweaks

---

requirements_common.txt

* Security updates
* https://pillow.readthedocs.io/en/stable/releasenotes/8.1.0.html
* https://github.com/yaml/pyyaml/blob/master/CHANGES
* UI peformance improvements using Django async plus Use full git sha as release name
* https://github.com/getsentry/sentry-python/blob/master/CHANGELOG.md
Closes #

requirements_common.txt: Upgrade Pillow, PyYAML, and sentry-sdk

---

.github/workflows/javascript_tests.yml

https://github.com/actions/setup-node/releases

GitHub Actions upgrade setup-node

---

openlibrary/components/LibraryExplorer.vue
openlibrary/components/LibraryExplorer/components/BookCover3D.vue
openlibrary/components/LibraryExplorer/components/BookRoom.vue
openlibrary/components/LibraryExplorer/components/BooksCarousel.vue
openlibrary/components/LibraryExplorer/components/Bookshelf.vue
openlibrary/components/LibraryExplorer/components/LibraryToolbar.vue
openlibrary/components/LibraryExplorer/components/OLCarousel.vue
openlibrary/components/LibraryExplorer/components/Shelf.vue
openlibrary/components/LibraryExplorer/components/icons/SortIcon.vue
openlibrary/components/LibraryExplorer/configs.js
openlibrary/components/LibraryExplorer/lcc.json
openlibrary/plugins/worksearch/languages.py
package-lock.json
package.json

- Based of #4081 and #4608 and #4609. This likely the diff you seek: https://github.com/internetarchive/openlibrary/pull/4610/files/6055423897f8e2d01042eb0d748737857c430a04..13fbcfeeddcf22b39abf7d4a96d5f050fb564a6f
https://user-images.githubusercontent.com/6251786/107995139-1f974f00-6fac-11eb-8481-43b14b3385b5.mp4
https://user-images.githubusercontent.com/6251786/107995473-713fd980-6fac-11eb-9e1d-ceeb8889a187.mp4

[library-explorer] Make toolbar more like tabs

---

openlibrary/solr/update_work.py
openlibrary/tests/solr/test_update_work.py

Closes #
@mekarpeles @kylewill

Fix cover_i not being set when an edition has a valid cover id

---

openlibrary/i18n/fr/messages.po

Linked to PR #4620
Correction of the french translation.
@cdrini

Correct french translation

---

openlibrary/plugins/openlibrary/js/index.js
openlibrary/templates/lib/nav_head.html

Follow up to fd5dbb02937
Fixes: #4686
Closes #

Only one menu should be open at a time

---

openlibrary/templates/lists/preview.html
openlibrary/templates/type/list/embed.html
static/css/components/header-bar.less

Small pre-deploy tweaks to some things that were merged recently.

Small fixes: Nav menu cursor: pointer + Don't show "0 editions" for lists

---

openlibrary/coverstore/code.py

Closes #4672
Changes IA endpoint in `zipview_url` to an updated endpoint that is CORS enabled.  Removed functions used to find the image's server, which was needed to construct the old endpoint.
The proposed change (`%(protocol)s://archive.org/download/%(item)s/%(item)s.zip/%(filename)s`) did not work for API calls that specified a size.  Replacing the second `item` with `zipfile` remedies this.
Attempt to make a valid covers API call using an ISBN.  You should be redirected to a valid archive.org/download URL, and redirected again to the actual image.
**Note:** If testing locally, [is_cover_in_cluster()](https://github.com/internetarchive/openlibrary/blob/fd5dbb02937f7db80a1f90ef898c2f7edc35c83a/openlibrary/coverstore/code.py#L319-#L326) will always return False if the …

Update zipview_url with new endpoint

---

openlibrary/plugins/worksearch/code.py

Subtask of #2852
* `isort --profile black` to order the imports
* Replace `urlopen()` with `requests.get()`
@dherbst

worksearch code.py: Replace urlopen with requests.get

---

docker/README.md

Small fixes to docker instructions

---

openlibrary/macros/DonateModal.html
openlibrary/macros/SearchResultsWork.html
openlibrary/templates/type/edition/view.html

Closes #4638 
Fixes image accessibility issue in book page
@bpmcneilly

Fixes accessibility issue in book page

---

openlibrary/macros/SearchResultsWork.html

Closes #4636 
Fixes image accessibility issue in search results page 
@bpmcneilly

Fixes accessibility issue in search results page 

---

openlibrary/i18n/ja/messages.po

This provides an initial i18n for japanese
@cdrini

adding language support for japanese i18n

---

openlibrary/plugins/importapi/code.py

Closes #4810
Not tested. The full flow here is kind of difficult to test. But PyCharm highlighted this and said it should "bytes expects bytes argument!", so trusting PyCharm knows what it's talking about.
@mekarpeles @cclauss

Fix [bytes].startswith expects bytes argument!

---

requirements_test.txt

https://flake8.pycqa.org/en/latest/release-notes/3.9.0.html
Closes #

requirements_test.txt: flake8==3.9.0

---

openlibrary/templates/account/borrow.html
openlibrary/templates/account/email/forgot-ia.html
openlibrary/templates/account/import.html
openlibrary/templates/account/password/forgot.html
openlibrary/templates/authors/index.html
openlibrary/templates/lib/nav_head.html
openlibrary/templates/lib/not_logged.html

Contribution to #791.
Improve i18n support on several templates
@cdrini

Improve i18n support on templates

---

openlibrary/macros/daisy.html

Closes #4807
Fixes the Image Path of Daisy lock
@mekarpeles

Fixing daisy lock icon

---

openlibrary/templates/type/list/view.html

Closes #4634 
Added Alt Attr to the Books cover present in List Page
@bpmcneilly

Fix Individual List Page Images Accessibility

---

docker-compose.production.yml

Remove ol code volume mounts from prod docker-compose

---

openlibrary/core/lending.py

Let's avoid merging code with failing tests.
Closes #

openlibrary/core/lending.py: Fix indentation error

---

openlibrary/catalog/add_book/tests/test_add_book.py
openlibrary/catalog/utils/__init__.py

Related to #4616
This pull request is a subset of 4616 which only makes the changes 2, 3, and 6 as recommended at https://github.com/internetarchive/openlibrary/pull/4616#pullrequestreview-605923373
Once these changes have been reviewed and landed, 4616 can be rebased to simplify its next review.

Add Unicode tests and remove unused catalog.utils.strip_accents()

---

openlibrary/templates/type/list/view.html
static/css/base/headings.less
static/css/components/mybooks-list.less

Closes #4783 
Added subtitle to items(books) present in lists
@BrittanyBunk @jdlrobson

Add book subtitle to lists

---

openlibrary/plugins/upstream/utils.py

Use requests in openlibrary/plugins/upstream/utils.py

---

scripts/deployment/deploy.sh

No longer needed since we removed volume mounts
Closes #
@cclauss

Remove makei18n from deploy.sh

---

openlibrary/components/LibraryExplorer/components/FlatBookCover.vue

Closes #4938 
Added alt attr
@bpmcneilly

Fix Library Explorer Image Accessibility

---

.github/dependabot.yml

Add @dhruvmanila to dependabot.yml Python

---

openlibrary/solr/update_work.py
openlibrary/tests/solr/test_update_work.py

This is the most logged error from solr updater. I deleted some of the clearly nonsense ones, but some of them are valid works, so just added a simple checks to reduce the noise in the logs.
Extracted from #4337 
- Unit tests should be enough.

Make solrupdater handle works without titles

---

openlibrary/solr/update_work.py
requirements.txt
scripts/solr_builder/Dockerfile.olpython
scripts/solr_builder/Jenkinsfile
scripts/solr_builder/README.md
scripts/solr_builder/docker-compose.yml
scripts/solr_builder/setup.py
scripts/solr_builder/solr_builder/fn_to_cli.py
scripts/solr_builder/solr_builder/index_subjects.py
setup.py

Work towards: #3317 . Extracted from #4337 .
Feature: Replace the solr-backup shim with a proper solrbuilder subjects indexer!
Note: This only works with solr 8, but won't cause solr3 to error if disabled.

solrbuilder subjects indexer

---

openlibrary/templates/lib/nav_foot.html

Add lang attr as per slack discussion
@bpmcneilly

Add lang attribute to the language menu

---

openlibrary/templates/covers/add.html

hotfix, unbreaks `covers/add-covers` template
quote escaping
http://staging.openlibrary.org:1337/books/OL32229144M/The_Plays_of_William_Shakespeare/add-cover?debug=true

fixes quoting, unbreaks add covers

---

openlibrary/templates/account/import.html
static/css/page-user.less

Closes #4971 
Fix unresponsive import and export options
https://user-images.githubusercontent.com/64412143/113483390-d13d0180-94c0-11eb-80ef-e0e88ff7be1f.mp4
@jdlrobson

Fix unresponsive import and export options

---

scripts/deployment/deploy.sh

- Replace rsyncs with git pull ; too many rsync issues :/
- Some reordering
@mekarpeles  @cclauss

Small fixes to deploy script

---

docker-compose.production.yml
docker-compose.yml
scripts/new-solr-updater.py
scripts/solr_builder/solr_builder/fn_to_cli.py

Continuation of #5056 ; the last test there revealed some errors.

Fixup to solr-updater

---

scripts/deployment/are_servers_in_sync.sh
scripts/deployment/deploy.sh

Small tweaks to deploy scripts as a result of olbase changes, or for better readability. Discovered during today's deploy.

Small tweaks to deploy scripts

---

openlibrary/i18n/es/messages.po

Expanded Spanish translation of the website with new strings, improve some existing translations and corrected a couple of typos.

Expanded Spanish translation of the website

---

openlibrary/solr/update_work.py
openlibrary/tests/solr/test_update_work.py

Closes #4323
Didn't manually test here; relying on the tests.

Fix 092 DDC shelf pollution

---

openlibrary/macros/databarHistory.html
openlibrary/macros/databarView.html
static/css/components/edit-toolbar--tablet.less

Fix Tab order of Edit Toolbar

---

setup.py

Refactor. Dependencies are no longer managed from this file
@dhruvmanila @cclauss

Remove dependencies from setup.py

---

openlibrary/plugins/openlibrary/js/edit.js
openlibrary/plugins/openlibrary/js/index.js
openlibrary/templates/books/author-autocomplete.html
static/css/page-user.less

Move autocomplete part of inline js for `openlibrary/templates/books/author-autocomplete.html` #4474
refactor
Nothing interesting in this PR.
Following the standards set for previous tickets in epic.
* Got to a [book edit page](https://openlibrary.org/books/OL7455361M/Biological_Science/edit) and try adding/removing authors 
https://user-images.githubusercontent.com/921217/118733787-adb3e900-b7d8-11eb-9873-ce111a60f205.mp4
@jdlrobson

move inline js for author autocomplete

---

.github/dependabot.yml

jquery is updated to 3.x.x
No issue
fix
@brad2014

Remove ignored packages in dependabot

---

static/css/components/chart.less
static/css/components/footer.less
static/css/components/header-bar.less
static/css/components/list-entry.less
static/css/components/work.less
static/css/layout/v2.less
static/css/legacy.less

Closes #4269
refactor max-width of containers
jamesachamp said to test change on small and large screen and it looks good for me. Tested on 16:9 ratio and 5:4.
Included screenshots of original on screen and change.
Can see changes from homepage
@jamesachamp

changed max-width of containers from max 960px to 1200px

---

openlibrary/templates/lib/nav_foot.html
openlibrary/templates/lib/nav_head.html

No related issue. 
This PR adds a link to the Collections page to the header and footer of the site, following instructions from @cdrini on Slack.

Add collections link to site nav

---

openlibrary/plugins/openlibrary/js/patron-metadata/index.js
static/css/components/metadata-form.less

applying @bpmcneilly fixes in #4887

---

tests/test_docker_compose.py

This causes warnings in our logs for some reason.
@dhruvmanila  @cclauss

Use yaml.safe_load instead of yaml.load in tests

---

static/css/page-book.less

Imported `components/buttonBtn.less`

---

openlibrary/solr/update_work.py
openlibrary/tests/solr/test_update_work.py
openlibrary/utils/ddc.py
openlibrary/utils/lcc.py
openlibrary/utils/tests/test_ddc.py
openlibrary/utils/tests/test_lcc.py

Closes #5267 ; Closes #4322 . Note a full reindex will be needed to fix pre-existing works, of course. A number of small fixes/improvements were made, so go by commit by commit to see them all.
- Trusting the extensive unit tests here.

Fixes/cleanups to ddc/lcc utils

---

openlibrary/plugins/upstream/account.py

hotfix
Handles error created when SOLR data is not present on Work object as expected.
Load http://testing.openlibrary.org/people/seabelis/books/already-read.json?limit=100&debug=true
Applying the fix should correct the error.

Bug fix for Reading Log JSON interface

---

openlibrary/templates/covers/add.html

Removed unnecessary styles in the word "Or" of the pop-up window to add a new cover image.
@mekarpeles

Removed unnecessary styles.

---

openlibrary/i18n/es/messages.po
openlibrary/i18n/messages.pot

Updated messages.pot file to include [this change](https://github.com/internetarchive/openlibrary/pull/5272/files).
The Spanish translation has also been updated to reflect this change. I have taken the opportunity to correct some typos and poor translations.

Updated Spanish translation and messages.pot file

---

openlibrary/templates/lib/nav_head.html

Related to #5287 
Removed Collections option from more menu
@jdlrobson

Remove 'Collections' option from More menu

---

openlibrary/api.py

See: https://docs.python.org/3/library/configparser.html
refactor
Is it compatable with six's ConfigParser?
Try to read a ol.ini
@dhruvmanila

Move to python3 ConfigParser in api.py

---

scripts/solr_builder/solr_builder/solr_builder.py

fix
Compatable with six's version?
Read a config file
@cdrini, @cclauss

Move configparser to python3 in solr_builder

---

openlibrary/macros/LoanStatus.html
openlibrary/macros/databarWork.html
openlibrary/templates/type/edition/view.html

Trying to demystify the editions template and how we're getting the Edition's availability so it's documented.
@jamesachamp please update my docs so they also seem useful and make sense to you

annotating editions html template

---

docker/Dockerfile.olbase

adding bwb import pipeline dependencies

---

openlibrary/i18n/README.md

add video to i18n docs

---

openlibrary/i18n/hr/messages.po

Update Croatian translation

---

openlibrary/templates/type/author/view.html
static/css/page-user.less

Reverts internetarchive/openlibrary#5269 in order to correct issue #5366

Revert "Hoist image on authors page above the editions list on mobile view"

---

openlibrary/plugins/openlibrary/js/index.js
package-lock.json
package.json
static/css/components/header-bar.less

Add \<details\> polyfill for (only) IE11
Closes #
- Confirmed new chunk created
- Confirmed not loaded on FF
- Confirmed loaded + works on IE11
|----|----|
| ![image](https://user-images.githubusercontent.com/6251786/123872197-c13b8f00-d902-11eb-8686-32c9f2c24b92.png) | ![ie11 header](https://user-images.githubusercontent.com/6251786/123873309-4d01eb00-d904-11eb-9fb9-46526e3d00c1.gif) |
@jdlrobson @Yashs911

Fix header menus stuck open on IE11

---

openlibrary/plugins/openlibrary/code.py
openlibrary/plugins/upstream/utils.py

rm hash include to upstream; should be in code.py

---

openlibrary/macros/QueryCarousel.html

Was raising an error on the template
Closes #

refactor key defaults to use == not is

---

package.json

fix
run tests
@cdrini @Yashs911

Update webpack to (fix)? tests

---

openlibrary/templates/account/books.html

Updates header copy for "My Books" page notes and observations views.
_Notes view header_
_Observations view header_
@mekarpeles

Update copy for "My Books" notes and observations pages

---

openlibrary/templates/account/books.html

Fixes error in book notes list view copy.

Fix "My Books" notes view grammatical error

---

Makefile

Remove lessc ie8 option

---

static/css/components/header-bar.less

Fix tap-highlight-color

---

docker-compose.production.yml
scripts/solr_builder/README.md

In prep for #5493 , update some of the docs related to that flow + fix some broken settings!
- Nothing tested on this yet :/ Will test during #5493 and update things accordingly.

Fix/update some docs/configs for solr8

---

static/css/components/home.less

fixes initial loading flash

---

openlibrary/plugins/openlibrary/js/automatic.js
openlibrary/templates/site/body.html
static/css/components/flash-messages.less

Closes #5103 
Add a new class and position it accordingly.
https://user-images.githubusercontent.com/64412143/116820240-90084200-ab91-11eb-9850-fb75fb22e998.mp4
@seabelis

Fix flash message causes content shift

---

scripts/solr_builder/README.md

Update solr builder deploy docs

---

openlibrary/macros/LoanStatus.html

Fix author/search pages erroring

---

openlibrary/core/observations.py

Removes duplicate value "biography" from schema type "type"
@mekarpeles

Remove duplicate value from schema

---

openlibrary/core/models.py
openlibrary/plugins/upstream/models.py
openlibrary/plugins/worksearch/code.py
openlibrary/plugins/worksearch/subjects.py
openlibrary/utils/solr.py

Refactor. Small fixes to improve solr perf and reduce redundant requests. Reduces the number of solr requests made on a work/book page by a factor of at least 4!

Refactor: Misc Solr perf improvements

---

openlibrary/templates/observations/review_component.html
static/css/components/observationStats.less

Implement review notes for #5552.
1. `em`'s changed to pixels.
2. Log in link left aligned and `<hr>` removed.
3. Review categories appear on new lines.
4. Category respondent counts use lighter font-weight.
5. Parenthesis surrounding category respondent counts inserted via CSS.
6. Pill font size decreased.
7. New span wraps each set of category and values.
@cdrini 
@mekarpeles

Implement review notes for review component redesign

---

openlibrary/templates/observations/review_component.html
static/css/components/observationStats.less

Closes #5561 
http://testing.openlibrary.org:1337/books/OL27900720M/Ender's_Game#reader-observations
@jimchamp

adds feedback link

---

openlibrary/core/observations.py
openlibrary/templates/admin/index.html
openlibrary/views/loanstats.py

Feature: adds /stats for community review tags
http://testing.openlibrary.org:1337/stats?debug=true
@jimchamp

adds review /stats

---

openlibrary/templates/covers/add.html

I was adding many author images and this was a minor niggle, every time I overwrote it with an https:// source. Only a minor thing

update image prompt to https://

---

bundlesize.config.json

Bundlesize bump

---

openlibrary/templates/books/add.html

Added license info at bottom of form to improve the user experience as per mentioned in the issue #5585 
Closes #5585

added license info at bottom of form

---

openlibrary/core/lending.py
openlibrary/macros/SearchResultsWork.html
openlibrary/plugins/openlibrary/js/availability.js
openlibrary/plugins/upstream/account.py
openlibrary/templates/account/books.html

readinglog: use add_availability extend w/ openlibrary_work

---

openlibrary/i18n/README.md

Closes #5633
Updates our internationalization README.
Some of our `i18n-messages` scripts have changed recently. Examples featuring these scripts have been updated.
Information about the new validation scripts also provided.

Update i18n README

---

openlibrary/core/lending.py

We have millions of these in Sentry! It's firing in a perfectly un-exceptional situation -- when we're trying to create a subject-based ia query, and the work has no subjects. Or ditto for authors. That's not error-worthy.

Fix Sentry "compose ia url" error noise

---

scripts/partner_batch_imports.py
scripts/tests/test_partner_batch_imports.py

- run by olsystem cron
- processes a batch of csv book records
- marshals them to open library json records
- adds them to the ImportBot import_item batch queue
- ImportBot routinely polls db and imports queue records
Closes #5130

Adds hands-free partner import runner 

---

openlibrary/components/AuthorIdentifiers.vue

feature
Done from the UI side
Try inputing identifiers with whitespaces
@seabelis,@cdrini

Trim whitespace from identifiers in UI

---

.github/workflows/deploy_storybook.yml
package-lock.json
package.json

Closes #5643
Creates a GitHub action that builds and deploys our stories to a `storybook` branch.  This action is triggered whenever a PR containing changes in the `/stories` directory is merged into `master`.
We will have to create a repository secret in order for this to work properly.  This will remain a draft PR until the secret is created and our GitHub page is set up.
This uses [Storybook Deployer](https://github.com/storybookjs/storybook-deployer#readme) to simplify writing the build files to a different branch.
@cdrini 
@jdlrobson

Add Storybook publishing GitHub workflow

---

scripts/manage-imports.py

more readable code
refactor
@mekarpeles

Use list destructuring in add_items

---

docker-compose.override.yml
docker/ol-db-init.sh

feature
A new enviroment variable is needed ,because of the new image
Tested edits on works,editions,lists,reading logs (add and remove)
Tested author merges
Tested login as admin/librarian

Update to Postgres 13

---

openlibrary/templates/site/alert.html
static/css/components/buttonGhost.less
static/css/components/header.less
static/css/components/iaBar--desktop.less
static/css/components/iaBar--tablet.less
static/css/components/iaBar.less

This makes the donate button padding proportional - generally more aesthetically pleasing.
#5641 fixed the issue of the text not being aligned but made the donate button shape a bit too wide.
Before:
After:
This PR restores the donate button to nice proportions. Also code cleanup.
While I was in here I took the chance to cleanup the code a bit.
Changes:
* I removed the increased padding for the logo when on a tablet screen. In my opinion, the padding didn't make it look any better and was not symmetrical on both sides. Additionally, the padding was the sole reason for both the `.less` files that were deleted in this PR.
* I removed the `iaBarLogo` and `iaBarMessage` classes. Without the padding above the only purpose they served was to help with alignment. However, `a:last-child { …

improve donate button padding

---

scripts/flake8-diff.sh

added formating error created by black in flake8

---

openlibrary/tests/accounts/test_models.py
openlibrary/tests/catalog/test_get_ia.py
openlibrary/tests/catalog/test_utils.py
openlibrary/tests/core/conftest.py
openlibrary/tests/core/test_cache.py
openlibrary/tests/core/test_connections.py
openlibrary/tests/core/test_fulltext.py
openlibrary/tests/core/test_helpers.py
openlibrary/tests/core/test_i18n.py
openlibrary/tests/core/test_ia.py
openlibrary/tests/core/test_init.py
openlibrary/tests/core/test_lending.py
openlibrary/tests/core/test_lists_engine.py
openlibrary/tests/core/test_lists_model.py
openlibrary/tests/core/test_models.py
openlibrary/tests/core/test_observations.py
openlibrary/tests/core/test_olmarkdown.py
openlibrary/tests/core/test_processors.py
openlibrary/tests/core/test_processors_invalidation.py
openlibrary/tests/core/test_sponsors.py
openlibrary/tests/core/test_vendors.py
openlibrary/tests/core/test_waitinglist.py
openlibrary/tests/solr/test_data_provider.py
openlibrary/tests/solr/test_types_generator.py
openlibrary/tests/solr/test_update_work.py

Progress toward #4776 using pyupgrade + black
Related to #5839
fix 
Haven't tested locally (dev env broke)
Test the changed files :)
@dhruvmanila

pyupgrade + black on `/tests`

---

scripts/copydocs.py
scripts/generate-api-docs.py
scripts/ipstats.py
scripts/jsondump.py
scripts/lc_marc_update.py
scripts/manage-imports.py
scripts/migrate_db.py
scripts/new-solr-updater.py
scripts/oclc_to_marc.py
scripts/partner_batch_imports.py
scripts/pull-templates.py
scripts/sitemaps/sitemap.py
scripts/solr_builder/solr_builder/fn_to_cli.py
scripts/solr_builder/solr_builder/solr_builder.py
scripts/sponsor_update_prices.py
scripts/store_counts.py
scripts/update-loans.py
scripts/view_marc.py

Progress towards #5836 , #4776 
refactor
@cclauss , @cdrini

pyupgrade + black on `/scripts`

---

conf/openlibrary.yml
conf/solr/conf/managed-schema
docker-compose.production.yml
docker-compose.yml
openlibrary/components/LibraryExplorer/utils/lcc.js
openlibrary/solr/data_provider.py
openlibrary/solr/solr_types.py
openlibrary/solr/update_work.py
openlibrary/tests/solr/test_types_generator.py
openlibrary/utils/lcc.py
openlibrary/utils/tests/test_lcc.py
scripts/new-solr-updater.py
scripts/solr_builder/Dockerfile.olpython
scripts/solr_builder/Jenkinsfile
scripts/solr_builder/docker-compose.yml

Work towards #5502 .
- Fix some LCC parsing bugs
- Fix solrbuilder not cythonizing correctly
- Update Solr for 8.8 to 8.10
- Small Jenkinsfile cleanup
- Ran solrbuilder to completion, with an acceptable number of errors!

Misc solrbuilder fixes + Update solr to 8.10

---

openlibrary/i18n/de/messages.po
openlibrary/i18n/messages.pot
openlibrary/templates/merge/authors.html
openlibrary/templates/recentchanges/merge-authors/comment.html

- updated messages.pot
- updated messages.po for DE and added translations
- changed some occources of term master to primary
Some German translations could be not ideal and I couldnt figure out inclusive scentences in every translation but I'm happe to fix it later. Please let me know if your find some non ideal translations.
Makes PR [#5902](https://github.com/internetarchive/openlibrary/pull/5902) obsolete.

Update German translations

---

docker/README.md

Build times are staggeringly fast.  https://docs.docker.com/desktop/mac/release-notes/
Closes #

Docker Desktop for Mac >= 4.3.0 is Apple M1 native

---

openlibrary/plugins/worksearch/code.py

Closes #5784 . Fix.
Compare https://openlibrary.org/search?q=Jon+kabat*&mode=everything vs https://testing.openlibrary.org/search?q=Jon+kabat*&mode=everything

Fix asterisks no longer working in author search

---

CONTRIBUTING.md

Closes None
It fixes one small typo

fix one minor typo

---

openlibrary/accounts/model.py
requirements.txt

No dependabot PR so...
Closes None
fix
Dependabot did skip this dep
@cclauss

Update internetarchive to 2.2.0

---

openlibrary/macros/BookPreview.html

Fix embeded previews; /stream -> /embed

Fixes previews, switch to /embed

---

.gitignore

Make `git diff` cleaner/easier to use :)
@cclauss

Ignore eg .venv dirs generated by eg VS Code

---

.github/workflows/deploy_storybook.yml

Closes #
This allows us to deploy Storybook with the press of a button.

Deploy Storybook manually

---

scripts/import_standard_ebooks.py

Closes #5994
Adds full-size cover image URL to Standard Ebooks import items.
Also, does not write last updated date to file on dry-run.

Add cover URL to Standard Ebooks import job

---

requirements.txt

Closes #5965
New version (2.2.0) of IA tool causes many errors in Open Library.  Root issue will be solved in version 2.3.0.  In the meantime, let's use 2.1.0.

Downgrade IA tool

---

openlibrary/core/sponsorships.py

Closes #6072
tested on ol-dev1.us.archive.org:1337/admin/sponsorship

closes #6072 admin sponsorship dash

---

package.json

Configure global JS threshold

---

openlibrary/plugins/upstream/account.py

Closes #
hotfix
Increases the cookie expiry time to 1 year
Check the cookie Expires/Max-Age value in Developer Tools.
@mekarpeles

Increase cookie session expiry time

---

.gitpod.yml
static/css/components/form.olform.less

Closes #6011
hotfix
Original implementation selected the incorrect input type (email) instead of text for email address and screen name fields on the signup page.
Navigate to /account/create

Fix sign up page email and screen name input size

---

openlibrary/templates/recentchanges/merge-authors/view.html

Closes #5506 
fix
Check the recent authors merge history page for a author that was deleted
Not sure how to create the required screenshots

Add None check for recent merged authors

---

openlibrary/core/lists/model.py
openlibrary/plugins/openlibrary/lists.py
openlibrary/plugins/worksearch/code.py

Closes #6130 #6149
This supplants @b2pacific #6149 -- his changes remain intact here.

B2pacific 6130/fix/list carousel

---

openlibrary/plugins/openlibrary/js/page-barcodescanner/LazyBookCard.js

Fix cover icons broken in barcodescanner (http -> https)

---

openlibrary/book_providers.py

Fix availability explicitly set to None for some reason

---

scripts/partner_batch_imports.py

This function expects another argument! See also https://github.com/internetarchive/olsystem/pull/149

Fix wrong argv in partner_batch_imports.py

---

scripts/partner_batch_imports.py

repairing partner imports

---

openlibrary/i18n/zh/messages.po

initial i18n for Chinese, work in progress

Adding language support for Chinese i18n

---

docker-compose.production.yml

Not tested this specifically, but have confirmed it has internet access

solr_restarter now does have internet access!

---

openlibrary/templates/lib/nav_head.html

Adds Trending to Browse Nav menu

---

Makefile

Add zh to Makefile validation list

---

openlibrary/core/lending.py

Closes a request by @ximm to annotate Archive.org ES advancedsearch queries with headers

adding headers for IA ES

---

.github/workflows/codegen_api_docs.yml
.github/workflows/deploy_storybook.yml
.github/workflows/javascript_tests.yml
.github/workflows/pre-commit.yml
.github/workflows/python_tests.yml

Closes #
https://github.com/actions/setup-node/releases
https://github.com/actions/setup-python/releases

Update GitHub Actions

---

scripts/make-integration-branch.sh

integration branch script now supports PR nums

---

openlibrary/templates/type/edition/view.html

rm dupe work first published year, title, subtitle

---

openlibrary/templates/type/edition/view.html

Fixes case logic for get sorted editions

hotfix for editions table get_sorted_editions

---

openlibrary/solr/data_provider.py
openlibrary/solr/update_work.py
openlibrary/tests/solr/test_data_provider.py
openlibrary/tests/solr/test_update_work.py
requirements_test.txt
scripts/new-solr-updater.py
scripts/solr_builder/solr_builder/solr_builder.py

Refactor for #6068, switches solr reindexing to use IA ES + md instead of db

switching db to es for solr reindex

---

docker-compose.production.yml

Addendum to #6181 
Not testing

solr-updater no longer needs IA db access!

---

scripts/oldump.py

We do not want to pollute stdout.
Closes #

Write dump message to sys.stderr

---

renovate.json

Note this is apparently experimental
See https://docs.renovatebot.com/modules/manager/git-submodules/

Auto-update submodules via renovate bot

---

scripts/oldump.sh

Updates oldump process to skip already done work/steps if the work is done in the same month
@cclauss

fix oldumps dates

---

requirements_test.txt

Upgrade some key testing requirements.
* https://docs.pytest.org/en/stable/changelog.html
* https://github.com/pinterest/pymemcache/blob/master/ChangeLog.rst

Upgrade pytest==7.1.0 and pymemcache==3.5.1

---

openlibrary/data/dump.py

refactor
bsddb is not used anymore, even python3 removed it
@cdrini

OL dumps cleanup

---

openlibrary/i18n/cs/messages.po
openlibrary/i18n/pl/messages.po
openlibrary/templates/account/verify/activated.html

Fixes sentry issues:
- https://sentry.ux.archive.org/organizations/ia-ux/issues/1525
- https://sentry.ux.archive.org/organizations/ia-ux/issues/165
- https://sentry.ux.archive.org/organizations/ia-ux/issues/171
- The messages.* changes are pretty simple; not testing thoroughly
- https://testing.openlibrary.org/subjects/horror?lang=pl doesn't error
- The activate.html change, searched codebase string and they all are like this:
@jimchamp

Fix Sentry i18n errors

---

openlibrary/tests/data/test_dump.py

These tests test for ascii characters ,not unicode(no clue what char to test there for good coverage)..
Run the tests, they pass
@cdrini

Add tests to pgdecode

---

openlibrary/solr/update_work.py
openlibrary/tests/solr/test_update_work.py

refactor
tests should pass
SolrProcessor  should return the same results
@cdrini

Refactor add_ebook_info to get_ebook_info

---

openlibrary/plugins/upstream/utils.py

Addendum to #6413 . Noticing a new sentry error: https://sentry.archive.org/organizations/ia-ux/issues/40934/?project=7&query=is%3Aunresolved . Can't reproduce it myself though

Fix lang can sometimes be falsey

---

.gitpod.yml

Hello 👋 
Closes https://github.com/gitpod-io/gitpod/issues/9311

Fix gitpod not starting due to permission issues

---

openlibrary/core/bookshelves.py

- Testing works: https://testing.openlibrary.org/stats/readinglog

Fix /stats/readinglog erroring

---

openlibrary/i18n/cs/messages.po
openlibrary/i18n/test_po_files.py

Enable po file tests for Croatian, Czech

---

openlibrary/i18n/__init__.py
scripts/i18n-messages

Status command that shows how close to complete each language is, and gives a summary of any warnings/errors.
- Also added some colors to the validate command.
Run `docker-compose run --rm home scripts/i18n-messages status`
@jimchamp

Add "status" command to i18n-messages

---

openlibrary/plugins/worksearch/code.py

get_solr_next is loading the conf/openlibrary.yml file semi randomly -_-

Hotfix prod loading wrong config file

---

openlibrary/core/lending.py

Closes #6449
- https://testing.openlibrary.org/works/OL20465177W/Diary_of_a_Wimpy_Kid Doesn't error (compare to prod). Not it _does_ say "Special access" when it shouldn't though, but better than the error I guess?
@mekarpeles

Add default for groundtruth error

---

.github/workflows/codegen_api_docs.yml
.github/workflows/deploy_storybook.yml
.github/workflows/javascript_tests.yml
.github/workflows/python_tests.yml

* https://github.com/actions/cache/releases
* https://github.com/actions/checkout/releases
* https://github.com/actions/setup-python/releases

Upgrade GitHub Actions

---

openlibrary/core/lending.py

exempt OL from ES rate limits

---

openlibrary/plugins/openlibrary/api.py

Closes #6333
See #2342
A second attempt at #6333 which got in a bad git state.

api.py: vendors.search_amazon() is a stub function AGAIN

---

renovate.json

Fix. See https://github.com/internetarchive/bookreader/pull/1030
@cclauss

Fix GHA handling in renovate.json

---

Readme_chinese.md

Closes #6432 
Providing a Chinese translation of Readme.md
N/A
N/A
N/A
@mekarpeles

Chinese translation of Readme.md

---

openlibrary/plugins/worksearch/code.py
openlibrary/plugins/worksearch/tests/test_worksearch.py

Closes #6465 . Refactor. Makes it easier to add editions, which will be a dynamic document. Loads more can be cleaned up here :/ But I think this is ok for now.
- The `get_doc` function is only used in the search results UI ; confirm it looks the same between staging and testing
- Confirm .json results are working

Replace XML solr requests with json solr request

---

openlibrary/admin/stats.py

avoid ol stats race conditions on document rev

---

bundlesize.config.json
openlibrary/catalog/add_book/__init__.py
openlibrary/catalog/add_book/tests/test_add_book.py
openlibrary/components/LibraryExplorer/components/LibraryToolbar.vue
openlibrary/components/LibraryExplorer/configs.js
openlibrary/macros/SearchResultsWork.html
openlibrary/plugins/ol_infobase.py
openlibrary/plugins/openlibrary/js/autocomplete.js
openlibrary/plugins/upstream/addbook.py
openlibrary/plugins/upstream/tests/test_utils.py
openlibrary/plugins/upstream/utils.py
openlibrary/plugins/worksearch/code.py
openlibrary/plugins/worksearch/languages.py
openlibrary/solr/update_work.py
openlibrary/templates/books/edit/edition.html
openlibrary/templates/books/edition-sort.html
openlibrary/templates/type/edition/view.html
openlibrary/templates/type/language/repr.html
openlibrary/templates/type/work/editions.html

Closes #6246 
- Also DRY'd up a few util functions
Add `?lang=fr` and see everything change!
@tfmorris @bicolino34 @dcapillae

i18n language names wherever they appear

---

openlibrary/plugins/openlibrary/js/SearchBar.js
static/css/components/header-bar.less

Add subtitles in autocomplete search results

---

scripts/partner_batch_imports.py

fix partner imports quality check + error handling

---

openlibrary/i18n/uk/messages.po

Ukrainian translation

---

Readme.md

Readme.md: Fix swapped Python and JS badges

---

openlibrary/plugins/upstream/spamcheck.py

Add Python type hints to spamcheck.py

---

openlibrary/core/models.py

Small refactor while working around this space
Checked through grep/vs code that none of the deleted methods were used anywhere.

Remove some unused model methods

---

openlibrary/macros/LoanStatus.html

fixes bulk availability open check

---

openlibrary/templates/home/index.html

Ooops error in my solr query here.
testing.openlibrary.org homepage no longer errors

Fix classics carousel erroring

---

openlibrary/plugins/worksearch/code.py

Closes https://github.com/internetarchive/openlibrary/pull/6466#discussion_r886149529
Add a few type hints to one function and then [solve for None](https://github.com/internetarchive/openlibrary/pull/6578#issuecomment-1137181218).

Type hints for worksearch

---

openlibrary/core/bookshelves.py

Add Python type hints to openlibrary/core/bookshelves.py

---

openlibrary/templates/languages/language_list.html

Adds Ukrainian to our language menus.  Reorders languages by ISO code.
@bicolino34

Add Ukrainian to language menus

---

openlibrary/core/models.py
openlibrary/core/ratings.py

Type hints for openlibrary/core/ratings.py

---

Readme.md

I discovered a few minor mistakes in the readme that I wanted to fix.
Line 30
```
-  to get your familiar with 
+  to get you familiar with 
```
I also added full stops to the end of a few sentences in the lines
- 30
- 40
- 54
- 72
- 80
- 82 (here, I find a colon more fitting)
- 91
Proper punctuation and most English teachers would be satisfied.

Fixed a few minor punctuation mistakes

---

openlibrary/plugins/openlibrary/processors.py
openlibrary/plugins/upstream/account.py

auth support for google sign-in

---

scripts/Readme.txt
scripts/affiliate-server
scripts/coverstore-server
scripts/i18n-messages
scripts/infobase-server
scripts/ipstats.py
scripts/manage-imports.py
scripts/openlibrary-server
scripts/pull-templates.py
scripts/solr_updater.py
scripts/store_counts.py
scripts/sync
scripts/upstream-adapter

Document the use of 'import _init_path' to set PYTHONPATH

---

openlibrary/core/edits.py
openlibrary/core/schema.sql
openlibrary/plugins/upstream/code.py
openlibrary/plugins/upstream/edits.py
openlibrary/templates/merge/works.html
openlibrary/templates/merge_queue.html
openlibrary/templates/pendingchanges.html

This is the core-work for the Library merge queue which is already being used in the https://github.com/internetarchive/openlibrary/tree/librarian-queue-integration branch. We want to merge this first to make it easier to review the integration branch.

Librarian queue

---

bundlesize.config.json
openlibrary/components/MergeUI.vue
openlibrary/components/MergeUI/utils.js
openlibrary/core/edits.py
openlibrary/plugins/openlibrary/js/Toast.js
openlibrary/plugins/openlibrary/js/ile/index.js
openlibrary/plugins/openlibrary/js/ile/utils/SelectionManager/SelectionManager.js
openlibrary/plugins/openlibrary/js/index.js
openlibrary/plugins/openlibrary/js/merge-request-table/index.js
openlibrary/plugins/upstream/code.py
openlibrary/plugins/upstream/edits.py
openlibrary/plugins/upstream/utils.py
openlibrary/templates/merge/works.html
openlibrary/templates/merge_queue.html
openlibrary/templates/merge_queue/comment.html
openlibrary/templates/merge_queue/merge_queue.html
openlibrary/templates/site/body.html
package.json
static/css/components/merge-request-table.less
static/css/components/toast.less
static/css/components/work.less
static/css/page-user.less

Closes #4071
Closes #6715
This PR adds librarian merge queue functionality, namely:
1. Allows members of `librarian` and `admin` usergroups to submit a work merge request from a search result page.
2. Allows members of `librarian-work-merge` usergroup to update merge requests (MR) from the merge UI.
Members of group 2 (above) will be referred to as "Super Librarians" in this PR; members of group 1, "librarians".
This PR can be considered complete when the following tasks have been finished:
We enforce a unique URL when creating a new merge request.  If the URL in the new request is already present in the database, we do not create a new row.  This should be fine for merge requests, but we will want to loosen this requirement for flagged records (if/when we include them in the queue).

Librarian Merge Request Table

---

.pre-commit-config.yaml
openlibrary/book_providers.py
openlibrary/i18n/__init__.py
openlibrary/plugins/books/dynlinks.py
openlibrary/plugins/upstream/account.py
openlibrary/plugins/upstream/spamcheck.py
openlibrary/plugins/upstream/utils.py
openlibrary/plugins/worksearch/code.py
openlibrary/solr/data_provider.py
openlibrary/solr/update_work.py
openlibrary/utils/__init__.py
openlibrary/utils/ddc.py
openlibrary/utils/lcc.py
openlibrary/utils/solr.py
scripts/solr_builder/solr_builder/solr_builder.py
scripts/solr_updater.py

https://github.com/asottile/pyupgrade/pulls?q=is%3Apr
Commits:
1. `pre-commit autoupdate`
2. (Done by pre-commit.ci) Updates 15 files to reflect https://peps.python.org/pep-0585/#implementation

pre-commit autoupdate: pyupgrade v2.34.0 -> v2.37.0

---

openlibrary/tests/core/test_db.py
openlibrary/tests/core/test_models.py
openlibrary/tests/core/test_sponsors.py
openlibrary/tests/data/test_dump.py
pyproject.toml

Subtask of #4776
Remove four `openlibrary/tests` files from the `black --force-exclude` list in `pyproject.toml`.

black openlibrary/tests

---

pyproject.toml
scripts/manage-imports.py

Modernize scripts/manage-imports.py

---

openlibrary/plugins/upstream/account.py
openlibrary/utils/dateutil.py

Blocked by #6734 -- Rebase this PR after 6734 lands.
Related to #6621 and #6645 which use the same `csv_string()` functions.
Optimize `generate_list_overview()` by joining yielded csv strings without building large lists in memory which can make this process unwieldy for users with large reading lists.
```
Elapsed time (user.get_lists()):         0.016138959 seconds
Elapsed time (generate_list_overview()): 0.002482458 seconds
Elapsed time (user.get_lists()):         0.035167666 seconds
Elapsed time (generate_list_overview()): 0.002955250 seconds
Elapsed time (user.get_lists()):         0.022057500 seconds
Elapsed time (generate_list_overview()): 0.001791541 seconds
```

Optimize generate_list_overview()

---

openlibrary/templates/lib/header_dropdown.html
openlibrary/templates/lib/nav_head.html

Closes #6492 
We should probably also do #6437 
on http://ol-dev1.us.archive.org:1337/

add track analytics

---

openlibrary/plugins/admin/code.py
pyproject.toml

Makes #6667 easier to review.
Closes #

psf/black: openlibrary/plugins/admin/code.py

---

pyproject.toml
scripts/coverstore-server
scripts/i18n-messages
scripts/import_standard_ebooks.py
scripts/infobase-server
scripts/openlibrary-server
scripts/solr_builder/solr_builder/fn_to_cli.py
scripts/tests/test_copydocs.py

Canonical formatting will make future diffs easier to read thus making pull requests easier to review.
[Commits:](https://github.com/internetarchive/openlibrary/pull/6747/commits)
1. Remove several `black --force-exclude` lines from `pyproject.toml`.
2. (Done by pre-commit.ci) Use black to format the corresponding files.
Leave `/scripts/sync` for a separate pull request after this has landed.

psf/black: /scripts

---

openlibrary/core/models.py
openlibrary/plugins/admin/code.py

Closes #6511 
Run with:
```
import web; import infogami; from openlibrary.config import load_config; load_config('/olsystem/etc/openlibrary.yml');infogami._setup();from infogami import config;from openlibrary.core.models import Work
Work.resolve_redirects_bulk(batch_size=1000, max_limit=10000, test=True)
```

resolve redirects bulk

---

openlibrary/plugins/openlibrary/api.py
openlibrary/plugins/upstream/covers.py
openlibrary/plugins/upstream/models.py
openlibrary/plugins/upstream/mybooks.py
openlibrary/plugins/worksearch/code.py
pyproject.toml
scripts/sync

More black to fix the broken build

---

openlibrary/core/db.py
openlibrary/core/lists/model.py
openlibrary/core/observations.py
openlibrary/coverstore/code.py
openlibrary/views/loanstats.py
pyproject.toml

One of the last remaining tasks of #4776

psf/black: All files in the repo

---

Makefile
conf/solr/conf/managed-schema
docker-compose.override.yml
openlibrary/solr/solr_types.py
openlibrary/solr/update_edition.py
openlibrary/solr/update_work.py
openlibrary/utils/lcc.py
scripts/solr_builder/Jenkinsfile

Work towards #6377  #5827
This PR adds support for indexing editions into solr work records as nested documents. It does _not_ change what queries are performed, so search results will remain the same.
- **DO NOT SQUASH THIS PR, PLEASE.** Sorry it was too annoying to embed the pre-commit stuff in the history :/
- There are a few small unrelated tweaks in here
- Note that because fully testing this code requires a ~2day full reindex, excluding any big bugs, any code review feedback will be implemented in a future PR.
- We've tested this new reindex of solr with the exception of a one line change I made while reviewing the code: https://github.com/internetarchive/openlibrary/pull/6119/files#diff-a5e3871068e5a3f784466986b37e18f5641f577dd1c3a1188084fa2fba4ef9b9R711
- We saw no performance …

Editions in Solr -- Indexing Piece

---

openlibrary/macros/SearchNavigation.html
openlibrary/templates/authors/index.html
openlibrary/templates/search/authors.html

Resolves issues related to #6688

fixing search nav queries

---

openlibrary/templates/merge_queue/merge_queue.html

Closes #6781
Add a second pager above the merge request table.

Added a second pager

---

openlibrary/templates/lib/header_dropdown.html
openlibrary/templates/lib/nav_head.html
static/css/components/header-bar--desktop.less
static/css/components/header-bar--tablet.less
static/css/components/header-bar.less
static/css/components/page-banner.less

- Replaces account dropdown with hamburger on desktop
- Moves "More" menu to hamburger, replaces with "My Books"
- Refactor nav logic to allow singletons (non-dropdown menus; e.g. "My Books")
- Updates styles for mask-menu and app-drawer on desktop
- Makes tablet and mobile more consistent
- Fixed icon sizes and hamburger drop-downs for different media viewports
On http://ol-dev1.us.archive.org:1337
**Mobile**
**Desktop**

re-architect main nav

---

openlibrary/utils/__init__.py

Add a few doctests to utils.py

Add some more tests

---

openlibrary/templates/trending.html
openlibrary/views/loanstats.py

Closes #6809
Allows pagination of first 10 pages of results through UI

adds pager to bottom of trending pages

---

docker-compose.production.yml
scripts/affiliate-server

Closes #6680 by relying more on openlibrary.core.import
Add an Amazon import batch to the Affiliate Service.

Import Affiliate Data

---

openlibrary/i18n/pt/messages.po

Inclusion of Portuguese in the template list

Inclusion of Portuguese in the template list

---

docker-compose.production.yml

production now uses solr-next code

---

scripts/oldump.sh

Fixes oldump cleanup step

---

docker/Dockerfile.olbase

Reverts internetarchive/openlibrary#6837

Revert "docker/Dockerfile.olbase: Upgrade npm as we do with pip"

---

openlibrary/i18n/messages.pot

Closes #6844 
Regenrating the pot file for missing i18n text
@cdrini

Regenrating the pot file for missing i18n text

---

package.json
tests/unit/js/styleMock.js

refactor
See: [Jest Docs](https://jestjs.io/docs/webpack#handling-static-assets)
Run the js tests , verify that they output the same results
@cdrini

Simpify jest config + style mock

---

openlibrary/i18n/hr/messages.po

- updated Croatian tranlsation with current .pot file
- removed orphaned/old strings

Update Croatian tranlsation

---

openlibrary/i18n/pt/messages.po

Fixes 2 typos in the new PT translation. I'm new to contributing to repos and don't know how to create a new branch for merging here, so forgive me if something was done wrong and I'm not supposed to pull request into the master branch (though it should be fine for a minimal change like this).
Typo can be found on the login screen ("Arquiivo" should be "arquivo").

typo fixes

---

docker-compose.production.yml
openlibrary/plugins/worksearch/code.py
openlibrary/plugins/worksearch/tests/test_worksearch.py
openlibrary/solr/update_work.py

Work towards #5827 . Closes #889
On testing.openlibrary.org, but **uncheck** the "solr editions".

Make solr next default now deployed

---

static/css/components/merge-request-table.less

Closes #6833 
Adding visual selected to #mrid123 on the merges page
@jimchamp

Added dark grey colour to the target row

---

openlibrary/accounts/model.py
openlibrary/templates/account/create.html
openlibrary/templates/account/ia_thirdparty_logins.html
openlibrary/templates/login.html
static/css/base/helpers-misc.less
static/css/page-user.less

Add Google Signin button to login page

---

Makefile

This will make subjects searchable from the local/dev environments.
@mheiman

Make reindex-solr make command also index subjects

---

openlibrary/templates/work_search.html

Closes #6875 
When there are no results
When there are results 
@cdrini

Suggest users to add books if there are no results in search

---

.pre-commit-config.yaml
pyproject.toml
setup.cfg

The Python community is migrating away from `setup.cfg` towards [`pyproject.toml`](https://peps.python.org/pep-0621/) so let's be part of that trend.

Move mypy config into pyproject.toml

---

static/css/base/helpers-misc.less

Errorring fields should not disappear

---

openlibrary/plugins/books/readlinks.py

We were noticing a lot of single requests to solr of the sort `q=key:/works/OL123W`. These are more performant when done with the solr `/get` endpoint, so switch to that! Also DRY up some code, and only make when request.
- https://testing.openlibrary.org/api/volumes/brief/isbn/9781627240987.json?debug=true is the same as https://openlibrary.org/api/volumes/brief/isbn/9781627240987.json?debug=true
- https://testing.openlibrary.org/api/volumes/brief/json/isbn:9781627240987
@mekarpeles

Make readlinks API use solr /get

---

package-lock.json

fixing package-lock w/ 8.15 for deploy

---

.pre-commit-config.yaml

Add [`validate-pyproject`](https://github.com/abravalheri/validate-pyproject#readme) to our pre-commit to ensure that our configuration is using proper TOML syntax.

pre-commit: Validate pyproject.toml

---

openlibrary/tests/core/test_db.py

Implements review notes given in #6834, [here](https://github.com/internetarchive/openlibrary/pull/6834#discussion_r938581568).

Fix assert statements in DB unit tests

---

openlibrary/plugins/openlibrary/js/autocomplete.js

Closes #6975 . Hotfix
The regex we were using before was too fancy for safari; it cause a SyntaxError of the entire script!
@mheiman @jimchamp

Rewrite regex that breaks safari

---

openlibrary/templates/search/authors.html
openlibrary/templates/search/lists.html

Closes #6728
Changes the format of the search button on "Search Lists" tab.
Search- > Lists Tab
to

Lists searchbttn

---

openlibrary/core/bookshelves.py

Closes #6978
Fixed at
https://testing.openlibrary.org/trending/daily?page=2&debug=true

fix trending pagination, coerce str to int

---

openlibrary/templates/search/authors.html
openlibrary/templates/work_search.html

Closes #6728 
This unifies the search headers.
Search > Books tab
to

Work search header

---

openlibrary/plugins/openlibrary/js/page-barcodescanner/index.js
openlibrary/templates/barcodescanner.html
openlibrary/templates/covers/add.html
openlibrary/templates/covers/manage.html
openlibrary/templates/covers/saved.html
openlibrary/templates/site/body.html
openlibrary/templates/site/footer.html
openlibrary/templates/type/list/embed.html
package-lock.json
package.json
static/css/page-barcodescanner.less
static/css/page-form.less

Feature. Adds support for a `returnTo` parameter, which causes barcode scanner to go to the provided URL when the first isbn scans
Closes #4708 
- Also did some refactoring
- Also added throttling to the isbn detection to avoid incorrect noise
- Fixed bug where video stream wouldn't work on Android + Edge (and likely other devices)
@judec @mekarpeles

Make barcodescanner embeddable

---

openlibrary/core/schema.sql

closes #7016 add indices to multi-pkey db schema

---

openlibrary/core/models.py
scripts/update_stale_work_references.py

Closes #6752 
Run using:
```
docker exec -it -uopenlibrary openlibrary_cron-jobs_1 PYTHONPATH=. python ./scripts/update_stale_work_references.py /olsystem/etc/openlibrary.yml
```
The following change will also be made to `/olsystem/etc/cron.d/openlibrary.ol_home0`: 
```
0 23 * * * su openlibrary -c "/openlibrary/scripts/update_stale_work_references.py /olsystem/etc/openlibrary.yml" > /proc/1/fd/1 2>/proc/1/fd/2
```
See PR: https://github.com/internetarchive/olsystem/pull/161

adding bulk redirect fix script

---

.pre-commit-config.yaml

https://mypy-lang.blogspot.com
@scottbarnes Your review, please.

pre-commit autoupdate: mypy v0.971 -> v0.981

---

openlibrary/macros/LoanStatus.html

For now, remove donate logic from LoanStatus (Do We Want It)

---

scripts/deployment/are_servers_in_sync.sh

fixing servers_in_sync checks

---

docker-compose.override.yml
docker-compose.production.yml
docker-compose.yml
openlibrary/solr/update_work.py
scripts/solr_builder/solr_builder/index_subjects.py
scripts/solr_builder/solr_builder/solr_builder.py
scripts/solr_updater.py

Addendum to #7037 . These options were disabled in #7037 , and are no longer needed.
Locally, edits do appear in solr!

Delete no longer used solr-updater hard commit code

---

docker-compose.production.yml
scripts/affiliate-server

fixes db_parameters to affiliate-server imports

---

renovate.json

This dependency is only used in testing, so can be auto-merged when updated by renovatebot.

Add pytest-asyncio to autoupdate

---

openlibrary/core/fulltext.py
openlibrary/plugins/inside/code.py

This should have a perf improvement and reduce strain on IA.

Don't fetch search inside facets since we don't use them

---

openlibrary/plugins/worksearch/languages.py

Also a perf improvement! Don't want a facet that large!
- This regressed now that editions are in search, and also have language fields.

Fix language counts should only count works

---

openlibrary/plugins/importapi/code.py

There are numerous errors on the endpoint `/api/import` so improve the error logging to facilitate finding the root cause.

Improve error reporting on the endpoint /api/import

---

scripts/solr_restarter/index.js

It made things worse! I manually reverted but forgot to commit.

Revert "Make solr restarter wait longer before restarting solr"

---

static/css/components/buttonLink.less

Extract a piece from #6948
Looks the same: https://testing.openlibrary.org/books/OL24756879M/Opera_omnia
@mheiman

Make edit button style more reusable

---

openlibrary/core/lending.py
openlibrary/plugins/openlibrary/home.py

Avoid archive.org ES call since not needed here.

Switch /random to use solr

---

docker-compose.production.yml

Auto restart memcached on covers

---

openlibrary/plugins/upstream/borrow.py

Fix Sentry error https://sentry.archive.org/organizations/ia-ux/issues/42/?project=7&query=is%3Aunresolved+location&statsPeriod=14d

Handle invalid ia id to /borrow/ia/*

---

scripts/affiliate-server

tmp stop unsubstantive amz imports

---

pyproject.toml

psf/black: Drop Python 3.9 and add Python 3.11

---

.pre-commit-config.yaml

Related to #7177
Upgrades other packages without upgrading mypy which continues to suffer from the problem explained in #7177

pre-commit autoupdate on 2022_11_29

---

scripts/partner_batch_imports.py

This "author" was associated with not real (and inappropriate) books.
@seabelis

Block a fake book author from imports

---

openlibrary/coverstore/README.md

Add Cover service README

---

.flake8
openlibrary/core/helpers.py
openlibrary/plugins/openlibrary/lists.py
openlibrary/plugins/openlibrary/tests/test_home.py
openlibrary/plugins/upstream/addbook.py
openlibrary/plugins/upstream/jsdef.py
openlibrary/plugins/upstream/models.py
scripts/openlibrary-server
scripts/store_counts.py

Fix flake8 error F811 -- https://flake8.pycqa.org/en/latest/user/error-codes.html

flake8: Fix redefinition of unused variables

---

openlibrary/templates/work_search.html

Re-order facets

---

openlibrary/templates/type/language/view.html

Closes #
- eg https://testing.openlibrary.org/languages/fre

Make language pages link to readable books

---

CONTRIBUTING.md

Improves documentation for new contributors
Deprecates the Orientation Manual. https://docs.google.com/document/d/1fkTDqYFx2asuMWwSIDQRHJlnu-AGWpMrDDd9o5z8Cik/edit#heading=h.68h91rfx9ti3

outline / toc for contributors

---

openlibrary/templates/account/mybooks.html

Differentiate My Books sidebar links and chip links for more accurate analytics

---

openlibrary/i18n/messages.pot
openlibrary/templates/trending.html

Closes #7373 
Please check my changes and take a look at my comments.

Croatian i18n template trending.html

---

requirements_test.txt
scripts/affiliate_server.py
scripts/tests/test_affiliate_server.py

Closes #7245 which is required for #7184
Closes #7318

Re-enable affiliate-server amz imports with tests

---

openlibrary/plugins/openlibrary/js/check-ins/index.js

hide banner when goal set

---

openlibrary/core/bookshelves.py
openlibrary/plugins/openlibrary/api.py
openlibrary/templates/home/index.html
openlibrary/views/loanstats.py

better trending APIs + homepage

---

openlibrary/plugins/openlibrary/opds.py

opds: pages = book.pagination or book.number_of_pages

---

openlibrary/coverstore/code.py

fixes cover resp when no img found

---

scripts/affiliate_server.py

adding docs to affiliate_server

---

openlibrary/i18n/fr/messages.po

This PR translates the FullText  Search Box from English to French.
**These are the only changes I made:**
```
#: home/welcome.html:68
-#, fuzzy
msgid "Try Fulltext Search"
-msgstr "Recherche en plein texte"
+msgstr "Essayez la recherche en plein texte"
#: home/welcome.html:69
msgid "Find matching results within the text of millions of books"
-msgstr ""
+msgstr "Trouvez des résultats correspondants dans le texte de millions de livres"
```
Any other changes are unrelated to this PR and from running the update/validate commands.

Full-text search translation

---

openlibrary/catalog/merge/merge.py
openlibrary/catalog/merge/merge_marc.py
openlibrary/catalog/merge/names.py
openlibrary/plugins/admin/code.py
openlibrary/plugins/books/code.py
openlibrary/plugins/openlibrary/api.py
openlibrary/plugins/openlibrary/filters.py
openlibrary/plugins/openlibrary/processors.py
openlibrary/plugins/upstream/utils.py
openlibrary/plugins/worksearch/schemes/works.py
scripts/oldump.py
scripts/solr_updater.py

* https://beta.ruff.rs/docs/rules/#flake8-simplify-sim
* https://pypi.org/project/flake8-simplify

ruff fixes: Code simplifications from flake8-simplify

---

openlibrary/plugins/openlibrary/js/page-barcodescanner/LazyBookCard.js
openlibrary/plugins/openlibrary/js/page-barcodescanner/OCRScanner.js
openlibrary/plugins/openlibrary/js/page-barcodescanner/index.js
openlibrary/templates/barcodescanner.html
package-lock.json
package.json
static/css/page-barcodescanner.less

Feature. Adds experimental option to scan an ISBN using OCR.
Would like to merge this before any UX/etc improvements to unblock work on other barcodescanner features (eg #7535)
- Works somrwhat slowly on chrome.
- UX isn't great
https://testing.openlibrary.org/barcodescanner?ol_base=https://openlibrary.org
@joannajjliu

Add OCR to barcode scanner

---

openlibrary/core/bookshelves.py

Fix sql interpolation

---

openlibrary/templates/lib/nav_head.html

Closes #7598 
Added "Book Talks" to browse menu
@mekarpeles created issue

Add book talks to browse menu

---

docker-compose.production.yml

web_haproxy should not be exposed publicly

---

openlibrary/macros/ListCarousel.html

Closes #5857 
Add a new sort parameter to ListCarousel and forward it to QueryCarousel

Support sorting for list carousels

---

openlibrary/plugins/worksearch/schemes/works.py
openlibrary/solr/update_work.py

Work towards #6895 . These can be committed now the new solr is on prod.

Commit solr next changes

---

.github/workflows/ruff.yml

Provide our contributors immediate feedback on [Python linting](https://beta.ruff.rs) errors in their pull requests with helpful GitHub Annotations that describe the problem and its location.
This Action uses minimal steps to run in under 10 seconds to provide our contributors with rapid yet intuitive feedback.
Yes.  ;-)

Add a GitHub Action for Ruff

---

.gitattributes

Closes #
fixes https://github.com/internetarchive/openlibrary/pull/7652#discussion_r1136619977

designate MARC as a binary format

---

openlibrary/plugins/openlibrary/code.py
openlibrary/plugins/openlibrary/js/carousels_partials.js
openlibrary/plugins/openlibrary/js/lists/ListService.js
openlibrary/plugins/openlibrary/js/lists/index.js
openlibrary/plugins/openlibrary/lists.py

Addresses # https://github.com/internetarchive/openlibrary/issues/7447
fix
I noticed some other `*/partials*` requests but it didn't look like they were returning `json` responses. Happy to add those in if I am incorrect.
Clicked around locally, ran `make test`  to make sure things worked correctly.

Call json endpoint for partials

---

.gitattributes

Closes #
Builds on #7662, removes visual studio boilerplate unrelated to this project.

rm visual studio boilerplate unrelated to this project

---

static/css/base/helpers-common.less
static/css/components/cbox.less
static/css/components/manage-covers.less
static/css/page-form.less

Closes #7428 
This PR fixes the cursor inconsistencies pointed out in https://www.loom.com/share/d7936ac8557140c08e62949e2e35835f
@ma8642 opened this issue
@mekarpeles lead

Fix cursor inconsistencies on book about page

---

.github/workflows/javascript_tests.yml
package-lock.json
package.json

Cuts off ~15s from js CI.
Cuts off ~20s from local linting.

Run more JS github actions in parallel

---

.pre-commit-config.yaml
openlibrary/catalog/merge/tests/test_merge.py
openlibrary/coverstore/code.py
openlibrary/plugins/upstream/borrow.py
openlibrary/plugins/upstream/forms.py
openlibrary/plugins/worksearch/code.py
openlibrary/utils/tests/test_ddc.py
pyproject.toml
requirements_test.txt

Closes #
Establish upper [pylint limits](https://beta.ruff.rs/docs/settings/#max-args) on:
```
[tool.ruff.pylint]
max-args = 15
max-branches = 42
max-returns = 14
max-statements = 106
```
These plus [McCabe](https://beta.ruff.rs/docs/settings/#mccabe) helps us to limit code complexity.

Ruff: Add pylint max-args, branches, returns, and statements

---

openlibrary/templates/type/author/view.html

Closes #7643 
Remove duplicate lists showing after adding an author to a list
@bicolino34 created issue
@jimchamp lead

Remove duplicate lists showing after adding an author to a list

---

openlibrary/templates/account/privacy.html
static/css/components/form.olform.less

Improve privacy settings page i18n/a11y

---

openlibrary/core/vendors.py

Closes #7822 . 
Very heavy handed approach ; also disabled prices and stuff. But this stops the bleeding so we're not creating swathes of duplicate books

Fix duplicate import (heavy handed)

---

openlibrary/core/loanstats.py
openlibrary/solr/process_stats.py

Related to #4426 . These were never being called, so removing these has no impact on anything.

Remove unused process_stats options/methods

---

openlibrary/plugins/openlibrary/js/compact-title/index.js
openlibrary/plugins/openlibrary/js/edition-nav-bar/EditionNavBar.js
openlibrary/plugins/openlibrary/js/edition-nav-bar/index.js
openlibrary/plugins/openlibrary/js/index.js
static/css/components/nav-bar.less

Recent changes on the `book-page-integration` branch have broken nav item selection for Safari.  The root cause is a new `Element.checkVisibilty()` check before initializing the navbar.  This function is not yet available in Safari.
The `checkVisibility()` call was removed in this PR.   This was used to selectively hydrate the navbar that was visible on-screen, an approach which broke the navbar when the browser window was resized.
Additionally, other small issues were addressed:
1. Extra padding has been added to the mobile navigation arrow.
2. Fixed bug where incorrect nav item is selected when nav item is clicked when compact title is off-screen (First click bug).
First click bug appears to be due to the way the navbar is repositioned when the compact title scrolls into view.  After …

Fix selected nav item in Safari

---

package.json

Add missing Jest dependency

---

openlibrary/plugins/openlibrary/js/compact-title/index.js
static/css/components/nav-bar.less
static/css/components/read-panel.less
static/css/components/readerStats.less
static/css/components/work.less

code review feedback for book page

---

openlibrary/catalog/add_book/tests/test_add_book.py

Partially closes #7884
Feature
This brings test coverage for `openlibrary/catalog/add_book/__init__.load()` up to 100%, not that code coverage tells the entire story obviously.
I know the associated issue (#7884) specifically says to add a lot of tests, but I am hoping because much of this function is conditional logic and small bits of code that test a value and then set other values, that perhaps no more tests are needed (he wrote optimistically).
Run `coverage.py` and verify the code coverage.
@cclauss

Add tests for untested parts of add_book/__init__.load()

---

openlibrary/plugins/worksearch/schemes/works.py

Fix duplicate key in set ruff error

---

openlibrary/plugins/upstream/utils.py
openlibrary/templates/site/alert.html

Fix bug in get_donation_include + cleanup

---

Makefile

Add Italian to validated languages

---

openlibrary/i18n/de/messages.po

Fix German translation issue

---

openlibrary/plugins/books/tests/test_readlinks.py

Closes #
Test cases in test_readlinks.py
Following the same steps in README about Running Tests.
```
cd docker/
docker compose exec web make test
```

Test Cases to get_item_method in Class ReadProcessor of readlinks plugin

---

openlibrary/admin/numbers.py
openlibrary/catalog/add_book/__init__.py
openlibrary/core/lending.py
openlibrary/plugins/openlibrary/home.py
openlibrary/plugins/openlibrary/lists.py
openlibrary/plugins/upstream/code.py
openlibrary/plugins/upstream/models.py
openlibrary/plugins/upstream/utils.py
openlibrary/plugins/worksearch/languages.py
openlibrary/plugins/worksearch/publishers.py
openlibrary/solr/update_work.py

Remove unused Python standard library imports which will likely not have side effects.

Remove unused Python standard library imports

---

openlibrary/plugins/upstream/utils.py

Related #8028 
Add type-hints for legibility.
These changes don't modify any fundamental logic of the code.
Developers

Type hints for openlibrary/plugins/upstream/utils.py

---

openlibrary/plugins/upstream/utils.py

Reverts internetarchive/openlibrary#7998. This introduces some breaking changes and needs more work.

Revert "Type hints for openlibrary/plugins/upstream/utils.py"

---

openlibrary/macros/databarWork.html
openlibrary/templates/covers/book_cover.html

Perf. Address pagespseedinsights perf issue
Opportunity no longer appears on pagespeedinsights, and LCP has gone down!

Preload main book cover

---

openlibrary/plugins/openlibrary/lists.py

Closes https://sentry.archive.org/organizations/ia-ux/issues/45957 55k events
Similar Sentry events NOT fixed by these changes
* https://sentry.archive.org/organizations/ia-ux/issues/360351 1 event
* https://sentry.archive.org/organizations/ia-ux/issues/50689 ~1 event~ 297 events

If there is no user then get_user_lists() should return an empty list

---

openlibrary/accounts/model.py
openlibrary/catalog/marc/marc_base.py
openlibrary/catalog/marc/marc_binary.py
openlibrary/catalog/marc/parse.py
openlibrary/catalog/merge/merge_marc.py
openlibrary/catalog/merge/names.py
openlibrary/core/processors/readableurls.py
openlibrary/coverstore/code.py
openlibrary/plugins/importapi/import_opds.py
openlibrary/plugins/importapi/import_rdf.py
openlibrary/plugins/ol_infobase.py
openlibrary/plugins/openlibrary/connection.py
openlibrary/plugins/openlibrary/home.py
openlibrary/plugins/upstream/account.py
openlibrary/plugins/upstream/addbook.py
openlibrary/plugins/upstream/borrow.py
openlibrary/plugins/upstream/models.py
openlibrary/records/functions.py
openlibrary/solr/data_provider.py
openlibrary/utils/ddc.py
pyproject.toml
scripts/affiliate_server.py

https://beta.ruff.rs/docs
% `ruff rule SIM102`
Derived from the **flake8-simplify** linter.
Autofix is sometimes available.
Message formats:
* Use a single `if` statement instead of nested `if` statements

Simplify Python code with ruff rule SIM102

---

bundlesize.config.json

Bump bundlesize.config.json

---

openlibrary/core/observations.py
openlibrary/plugins/importapi/import_rdf.py
openlibrary/plugins/openlibrary/code.py
scripts/copydocs.py

List comprehensions are approximately __10% faster__ than for loops so let's use them where we can.
* https://beta.ruff.rs/docs/rules/manual-list-comprehension

Use a list comprehension to create a transformed list

---

static/openapi.json

Adds tags for better sorting.
Next step would be to improve the apis themselves based on current docs and testing
Feel free to edit this PR directly as needed to merge
@cclauss

add tags to swagger

---

openlibrary/templates/account/privacy.html

i18n changes + privacy copy for sfw

update privacy page copy + i18n

---

openlibrary/catalog/add_book/__init__.py
pyproject.toml

Closes #7884 
Refactor
This should change no functionality. Instead it breaks out the existing functionality from `load()` into separate functions, most of which now have their own unit tests.
I renamed `w` and `e` to `work` and `edition` in a separate commit to try to make it easier to verify that the changes are mostly due to extracting logic into separate functions.
This is tested by verifying no functionality has changed. Because of #7894 `load()` had full test coverage, and those tests continue to pass, though obviously that is no guarantee.
@cclauss

Break out some add_book load() functionality into individual functions

---

openlibrary/core/helpers.py
openlibrary/core/imports.py
openlibrary/plugins/admin/code.py
openlibrary/templates/admin/imports.html
scripts/dev-instance/dev_db.pg_dump

Improve #7577 /imports dashboard + speed + make public

public /imports & speedup

---

openlibrary/conftest.py
openlibrary/core/bookshelves.py
openlibrary/core/models.py
openlibrary/core/observations.py
openlibrary/i18n/validators.py
openlibrary/plugins/importapi/code.py
openlibrary/plugins/openlibrary/borrow_home.py
openlibrary/plugins/openlibrary/code.py
openlibrary/plugins/upstream/code.py
openlibrary/plugins/worksearch/code.py
pyproject.toml
scripts/copydocs.py
scripts/delete_import_items.py
scripts/import_pressbooks.py
scripts/import_standard_ebooks.py
scripts/manage-imports.py
scripts/oldump.py
scripts/partner_batch_imports.py
scripts/promise_batch_imports.py
scripts/pull-templates.py
scripts/solr_updater.py
scripts/store_counts.py
scripts/tests/test_solr_updater.py
scripts/update_stale_work_references.py

[`ruff rule RUF010`](https://beta.ruff.rs/docs/rules/explicit-f-string-type-conversion/#explicit-f-string-type-conversion-ruf010) - explicit-f-string-type-conversion
[`ruff rule RUF013`](https://beta.ruff.rs/docs/rules/implicit-optional/#implicit-optional-ruf013) - implicit-optional
[`ruff rule RUF015`](https://beta.ruff.rs/docs/rules/unnecessary-iterable-allocation-for-first-element/#unnecessary-iterable-allocation-for-first-element-ruf015) - unnecessary-iterable-allocation-for-first-element

Fix ruff rules RUF010,RUF013,RUF015

---

openlibrary/solr/update_edition.py
scripts/solr_dump_xisbn.py

Closes #7545 . Closes #7657
LCCN was not included inside the solr edition, so this will require a full reindex.
isbn, lccn ran successfully on ol-solr1.
@hornc

Commits xisbn script + makes it support lccn (requires full reindex)

---

pyproject.toml

fix
The ruff docs recommend [extend-exclude](https://beta.ruff.rs/docs/settings/#extend-exclude) instead of [exclude](https://beta.ruff.rs/docs/settings/#exclude)
Ensure that all source files are checked by ruff still
@cclauss

Extend the exclude list of ruff

---

compose.production.yaml
conf/infobase.yml

`ol-web1` and `ol-web2` do not have `/1` volumes like many of our other hosts do.  Currently, we are trying to write end-user errors to `/1/var/lib/openlibrary` and `/1/var/log/openlibrary` which is failing.
See: https://sentry.archive.org/organizations/ia-ux/issues/324142
`os.mkdirs("/1/var/log/openlibrary/infobase-errors/2023-05-18")` raises `PermissionError: Permission denied: '/1'`
`ol-web1` and `ol-web2` do not have `/1/` volumes.
---
Also, see internetarchive/olsystem#184
The infobase logs are filling up the `/1` volume on the host `ol-home` so this change will write those logs into the `/var` directory.  This change means that this log data will be relatively short-lived because `/1` is a large external disk while `/var` is inside the Docker container so the log data will be lost …

Make web nodes and home0 infobase logs ephemeral

---

openlibrary/plugins/worksearch/autocomplete.py
openlibrary/plugins/worksearch/tests/test_autocomplete.py

Closes #8135 
Try the autocomplete on the list edit page. Searching for works should consistently and speedily bring up works.

Simplify works autocomplete search query for perf

---

.gitpod.yml

Use "docker compose" instead of "docker-compose" in gitpod

---

openlibrary/i18n/tr/messages.po

This PR provides an initial i18n for Turkish. 
Later on, once the whole translation is complete, we can update the [UI](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/languages/language_list.html) in a different PR.

Setup Turkish messages.po file

---

openlibrary/core/models.py
openlibrary/plugins/upstream/addtag.py
openlibrary/plugins/upstream/code.py
openlibrary/plugins/upstream/models.py
openlibrary/plugins/worksearch/subjects.py
openlibrary/templates/subjects.html
openlibrary/templates/tag/add.html
openlibrary/templates/type/tag/edit.html
openlibrary/templates/type/tag/view.html
static/css/components/page-heading-search-box.less

unable to amend @mekarpeles 's PR directly as it the branch exists of the main openlibrary repo. will use this branch and PR into Mek's branch instead

Tag Edit/Create UI

---

.github/workflows/ruff.yml
.pre-commit-config.yaml
openlibrary/solr/data_provider.py

https://github.com/astral-sh/ruff/releases

Upgrade to ruff v0.0.286

---

openlibrary/i18n/de/messages.po

Add missing and fix German translations.

---

openlibrary/plugins/upstream/models.py

fix typo in upstream/models.py

---

bundlesize.config.json

Closes #8283
To be honest, not really sure why we have this bundlesize thing but the tests will pass again.
@mekarpeles

fix js tests by updating bundlesize.config.json

---

openlibrary/plugins/openlibrary/pages/config_edition.page

relates to #7826 
The edit will probably need to be made to the live site manually though, I'm not sure this config is deployed manually.
Closes #

Update Harvard id permalink

---

package-lock.json

Fix package-lock outdated

---

docker/README.md

Closes #8316
Update our docs to avoid one more issue for people who build images.
Maybe these docs should be turned into a script people can run too.
I've added filtering so it's pretty safe
Run commands on your own machine
@cclauss

improve docker documentation

---

openlibrary/catalog/add_book/__init__.py
openlibrary/components/LibraryExplorer/components/Shelf.vue
openlibrary/core/admin.py
openlibrary/core/lending.py
openlibrary/core/models.py
openlibrary/plugins/openlibrary/dev_instance.py
openlibrary/plugins/upstream/code.py
openlibrary/solr/update_work.py
openlibrary/utils/solr.py
scripts/solr_builder/README.md

Closes #8359
[Fix] This PR fixes typos found by codespell.
@RayBB

Fix typos found by codespell

---

static/manifest.json

missing comma in manifest.json

---

static/manifest.json

Sorry, this one is my fault. Fixing a mistake I introduced in PR #8348.

Fix wrong URL in PWA manifest

---

static/manifest.json

add description + fix pwa manifest formatting

---

.github/workflows/codegen_api_docs.yml
.github/workflows/cron_watcher.yml
.github/workflows/deploy_storybook.yml
.github/workflows/javascript_tests.yml
.github/workflows/python_tests.yml
.github/workflows/ruff.yml

Small PR to update the used GH Action `checkout` to latest version 4.

update checkout actions to version 4

---

openlibrary/i18n/README.md

Moves https://github.com/internetarchive/openlibrary/wiki/i18n-Pages in to official i18n guide

update i18n docs, merge in wiki page

---

openlibrary/templates/admin/imports.html

Update /imports page so admin menu is admin-only

---

openlibrary/templates/merge/authors.html

Closes #8391
feature
Attempt to merge authors, with at least one id

add id links to author merge UI

---

openlibrary/plugins/openlibrary/pages/config_edition.page

Closes #8294 
Fixes the broken Identifier path of Al Kindi, as suggested.
@cdrini

Fixed-Al-Kindi-Identifier-broken

---

openlibrary/macros/TableOfContents.html

Add analytics to table of contents click

---

scripts/pr_slack_digest.py

Before: ![image](https://github.com/internetarchive/openlibrary/assets/6251786/6d102a9b-97fa-4e5d-b4ca-2d9bbb7289ca)
After:

Small style tweaks to slack digest

---

openlibrary/templates/lib/edit_head.html

Closes #8383
Removes inline js from edit_head.html.
@RayBB

Remove inline js from edit_head.html

---

openlibrary/plugins/README.md

Added README for plugins/

---

openlibrary/i18n/zh/messages.po

This PR updates zh translations by fixing some typos and adding space between Chinese and English.

Update zh translations

---

openlibrary/templates/books/edit/edition.html

Closes #8500 
feature, change order of edition id dropdown
Also contains minor fix to move an HTML comment out of a python for loop, as it was getting repeated after every item in the dropdown list.

feat(edit) promote edition id partners

---

static/css/components/buttonGeneric.less

prevent text wrapping on btns

---

openlibrary/book_providers.py
openlibrary/core/models.py

Use only one IA metadata cache

---

openlibrary/plugins/openlibrary/status.py
openlibrary/templates/status.html

Closes #
- ✅ Works with no/empty dev merged
- ✅ Works with full dev merged

updates /status for dev to include staged PRs

---

openlibrary/templates/type/author/view.html

Closes #8518 
feature
Visit an author with a wikidata ID, see the new link created belowe the wikidata link.

feat(author-ids) auto generate inventair links

---

.github/ISSUE_TEMPLATE/design_proposal.md

adds theme design to Design Proposal template

---

CONTRIBUTING.md

updating good first issues url

---

openlibrary/core/imports.py

Closes https://github.com/internetarchive/openlibrary/pull/8516#issuecomment-1854725871

Add trailing space to DB query

---

openlibrary/plugins/upstream/mybooks.py
openlibrary/templates/account.html

fixes mybooks sidebar on account settings

---

scripts/dev-instance/create-dev-db-pgdump.sh

Update commands for `pg_dump` generation

---

conf/solr/conf/managed-schema.xml
conf/solr/conf/wordtypes.txt

Closes #7555 
Closes #7568
Fix the issue with regarding to special character in solr search. 
I'm new to this repo and I'm working together with @karlitto01 in hope to contribute to the repo and learn in the process.
The original issue was due to the `wordDelimiterGraph` filter discarding special characters. As specified in its documentation at [here](https://solr.apache.org/guide/solr/latest/indexing-guide/filters.html#word-delimiter-graph-filter), non-alphanumeric characters are usually discarded.
The fix is to use filter.types to specify how to handle each special character. Currently, it is added to the word delimiter graph filter of `text_en_splitting` (the field type that titles is using), and uses the newly created file "wordtypes.txt". 
Currently, only two special characters: "©" …

Allow special character to be handled in title search

---

scripts/providers/isbndb.py

Feature.
Currently batch imports for ISBNdb have a hard coded import status of `staged`. This PR allows one to specify the `status` at import time using the `--import-status IMPORT_STATUS_HERE` syntax. By default the status will remain `staged`.
For example, to import with a `status` of `pending` in the local development environment, execute:
```
docker compose exec -e PYTHONPATH="." web python ./scripts/providers/isbndb.py config/openlibrary.yml batches_path --import-status pending
```
This just adds an (optional) switch that can be specified at run time via the command line and passes it through. By default the old behavior is preserved.
After importing four items, two with no `status` specified, and two with `--import-status pending`, one should see, for example:
```
openlibrary=# …
```

Make isbndb.py take an optional 'status' argument

---

compose.production.yaml
docker/Dockerfile.olbase
docker/covers_nginx.conf
docker/ol-nginx-start.sh
docker/public_nginx.conf
docker/web_nginx.conf

Closes #6951 and uses https://github.com/internetarchive/olsystem/pull/196

switches from provider certs to letsencrypt

---

openlibrary/i18n/id/messages.a
openlibrary/i18n/id/messages.po

feature: Added Indonesian transalation
I commented out strings that haven't been translated yet. Will continue to add more transalations
@cdrini

Added Indonesian translation

---

openlibrary/plugins/upstream/account.py

https://graphite.us.archive.org/render?target=integral(hitcount(stats.ol.account.xauth.login,%221d%22))&tz=UTC&width=800
@bfalling

collect anonymized login stats per day

---

openlibrary/plugins/upstream/mybooks.py

Want to read and currently reading were 🔁 Swapped!

Fix my books breadcrumb/headers mismatch

---

openlibrary/i18n/messages.pot

Closes #8813.
Fix. Bulk update of the `messages.pot` file so it is up to date with the current version of the site.
Ended up being amazingly straightforward, just running `./scripts/i18n-messages extract`.
1. Navigate to the `messages.pot` file
2. Search for a message that has recently been added to the website (i.e. "Uploading...")
@cdrini

Generate new .pot file for translations.

---

openlibrary/i18n/sc/messages.po

Feature: it adds a Sardinian translation  (name of the language in Sardinian: "Sardu", ISO 639-1 code: "sc")

Adding Sardinian strings

---

openlibrary/components/MergeUI/EditionSnippet.vue

Add number of pages to MergeUI

---

openlibrary/i18n/sc/messages.po

Fixed some typos and other stuff after running each string through a spell-checker and using https://testing.openlibrary.org/ to check the context.

Fixed some Sardinian typos and other stuff

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Addendum to #8894 to remove the duplicate "Problem" keyword, + remove the "related issues" section to keep this simple. We can add it to the maintainer's section if we want it somewhere. Was there a specific problem you were trying to solve with this @mekarpeles ? I would rather keep this form simple.

Update bug_report.yaml to remove duplicate heading + simplify

---

openlibrary/core/vendors.py

To be queried using the bookworm / affiliate server
Closes #

add lexile lookup to vendors

---

static/css/components/mybooks-menu.less

Fix CSS lint error: added parenthesis

---

openlibrary/plugins/openlibrary/js/edit.js
openlibrary/templates/books/edit/web.html
static/css/components/form.olform.less
static/css/legacy.less

Closes #8826.
Feature. Implements URL validation on the Work Details page.
What was initially just supposed to be adding some HTML type attributes to inputs ended up being far more complicated than expected: it turned out that the only element definitely in need of a new type was the URL input on the Work Details page, but switching to `type="url"` removed a lot of the styling and activated a jQuery plugin called `validate` we couldn't remove which generated an error message span that further disrupted the styling and spacing (and still didn't prevent a bad URL entry).
The solution was in three parts:
1. Add `type="url"` to the input in the HTML
2. Write and call a new validation function in the JavaScript to prevent bad URL submission
3. Clean up and adjust the CSS to keep styling …

Update HTML & JS validation for work details page

---

openlibrary/plugins/worksearch/schemes/works.py

Per drini's request, before the next big solr re-index https://github.com/internetarchive/openlibrary/issues/8234

add open syllabus project fields to solr

---

openlibrary/catalog/add_book/match_names.py

add typehints to match_names.py

---

docker/web_nginx.conf

See also https://github.com/internetarchive/olsystem/pull/204

Remove no longer used google verification pattern

---

openlibrary/plugins/openlibrary/processors.py

Fix typo in docstring

---

openlibrary/i18n/pt/messages.po

It is just a fix of portuguese translate mistakes. I hope that someone will continue this later and check all the other sentences. At least, I did my best to check almost all the file.

Fix several translate mistakes in portuguese

---

openlibrary/i18n/README.md

Update redirection link
Closes #9083
Fixes readme

Update i18n README.md

---

compose.production.yaml
scripts/deployment/are_servers_in_sync.sh
scripts/deployment/deploy.sh
scripts/deployment/pre_deploy.sh
scripts/setup_olserver.sh

Closes #9001
- See also https://github.com/internetarchive/olsystem/pull/206
- Also made some tweaks/adjuestments to the provisioning script based on issues I hit

Add new ol-web0 web head

---

openlibrary/utils/solr.py

Closes #8852
Reading logs no longer error: https://testing.openlibrary.org/people/mheiman9541/books/already-read.json
We need to make this API paginated ; it's fetching all of them!
@mheiman @benbdeitch

Switch Solr get_many calls to use POST

---

openlibrary/plugins/openlibrary/js/readmore.js

This wasn't being debounced correctly! Thanks for reporting, @mc2 !
@mc2

Fix typo in readmore.js

---

openlibrary/templates/site/head.html

Used while validating performance issues to try to reduce bingbot's crawl speed. The dashboard is generally useful though so worth keeping.

Add verification code for Bing webmaster tools

---

scripts/solr_dump_xisbn.py

Update solr_dump_xisbn docs

---

scripts/gh_scripts/issue_comment_bot.py

update slack recent comments bot to add tracking labels

---

openlibrary/templates/account/import.html

add star ratings period

---

openlibrary/plugins/openlibrary/js/realtime_account_validation.js

Closes #9189. 
Refactor. Part of larger registration form update project #2055.
Very straightforward! Simply created two helper functions to handle the repeated `jQuery` logic for rendering and clearing errors. Also bundled in a quick fix of an existing error in the validation `if` clause which was preventing existing error rendering logic from happening.
I ended up opting to pass in both `inputId` and `errorDiv` as parameters even though the latter is currently just "Message" tacked onto the former, so as to make the function more readable and ensure that any changes to error div IDs wouldn't require a rewrite of the function itself.
**Note:** Kept password validation as is to pass JS tests and avoid overlap with #9165.
1. Log out (if logged in)
2. Hit "sign up" on the homepage or go to …

Fix real-time email/username validation + DRY `jQuery` error rendering for registration form

---

openlibrary/i18n/messages.pot

Updates master version of `messages.pot` to prevent conflicts and unnecessary updates in incoming commits.
@cdrini

Hotfix: Generate updated master `messages.pot` template

---

openlibrary/plugins/upstream/addbook.py
pyproject.toml
scripts/cron_watcher.py

enable ruff rule ambiguous-unicode-character-docstring (RUF002)

---

openlibrary/macros/TableOfContents.html

Instead of legacy /stream links
Closes #

Change TOC links to use /details archive.org links

---

openlibrary/i18n/messages.pot
openlibrary/templates/account/readinglog_stats.html
openlibrary/templates/books/check.html
openlibrary/templates/books/daisy.html
openlibrary/templates/books/edit/about.html

Fix some small i18n errors

---

openlibrary/core/lending.py

Closes #9118
Add typehints to the function to reflect what it actually returns.
Update the logic as mentioned [here](https://github.com/internetarchive/openlibrary/issues/9118#issuecomment-2069496193).
I'm not sure how to test this. But I expect that this is addressing an edge case that isn't too common.
@mekarpeles

improved is_loaned_out logic

---

docker/ol-importbot-start.sh

fix importbot pythonpath #9277

---

openlibrary/templates/about/team.json

Addresses team page portion of #9226

updating team fellows for 2024

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

Closes #9269.
Feature. Adds instructions re: basic git pull/push operations to the issue template -- should help contributors avoid merge conflicts/bizarre issues/confusion as a result of out-of-date branches.
- I left out the "suggested branch name" section that was originally suggested for now, to avoid giving submitters more to do, and to make the new section as simple and legible as possible -- but happy to add it back in if people have been having issues with badly-named branches!
- Added `--ff-only` to the `pull` instructions (thanks @tfmorris!) in the Git Cheat Sheet
- I couldn't immediately find a way to make a non-editable section of the template (and as we discussed, there are some cases where the instructions wouldn't be necessary), so I left it editable but with a note re: …

Add `git` instructions to bug report and feature issue forms

---

openlibrary/templates/type/author/view.html

Follow up to https://github.com/internetarchive/openlibrary/issues/9266#issuecomment-2113237602
Closes #9087 again

refactor one final is_librarian

---

openlibrary/plugins/openlibrary/js/realtime_account_validation.js

Closes #9264.
Feature. Prevents registration form submission if any inputs are invalid -- covers taken username/screenname errors which would otherwise pass HTML checks and allow submission.
Adds an extra validity check (determining that no form inputs are invalid) before allowing form submission. This means that inputs that are invalid because they failed backend IA/OL availability checks, but passed `HTML` formatting tests, will still be caught and prevent form submission.
This strategy has the added advantage of ensuring any future `JavaScript`-based checks (i.e. if we move the email spamcheck into `realtime_account_validation.js`) will automatically prevent form submission, as long as they assign the input an `invalid` class.
As noted in the issue, this won't display helpful new error …

Add registration submission prevention for backend checks

---

scripts/obfi.sh
scripts/obfi/hide.py
scripts/obfi/mktable.py
scripts/obfi/reveal.py
scripts/obfi/shownames.py

Closes #9055
Feature.
This will need to be integrated into our existing documentation if this works.
@cdrini

Add internal spam fighting scripts

---

scripts/gh_scripts/weekly_status_report.mjs

Closes #9401
Closes #9402
Fixes incorrect `mrkdwn` syntax for italicized text.
Excludes leads from the "Assigned PRs" section if they currently have no pull requests assigned to them.

Improvements to weekly project management digest

---

openlibrary/book_providers.py
openlibrary/i18n/messages.pot
openlibrary/plugins/worksearch/code.py
openlibrary/plugins/worksearch/schemes/works.py
openlibrary/plugins/worksearch/tests/test_worksearch.py
openlibrary/templates/book_providers/cita_press_download_options.html
openlibrary/templates/book_providers/cita_press_read_button.html

Work towards #8462 
@mekarpeles @scottbarnes

Add Cita Press trusted book provider

---

openlibrary/plugins/upstream/data.py

Add covers metadata dump shortcut link

---

scripts/gh_scripts/issue_comment_bot.py

Fixes bug that was introduced in #9339.
The daily new comment Slack digest is not being published [in 2 weeks](https://github.com/internetarchive/openlibrary/actions/workflows/new_comment_digest.yml) due to the Slack channel being accessed incorrectly (wrong variable name).
Manually trigger the workflow once this is merged into the main branch.

Use correct variable for Slack channel

---

openlibrary/plugins/openlibrary/code.py
openlibrary/templates/site/banner.html

Addresses https://github.com/internetarchive/openlibrary/pull/9432/files#r1641272516

fix dismissible banners

---

scripts/gh_scripts/weekly_status_report.mjs

Use correct URL for untriaged issues

---

openlibrary/plugins/openlibrary/pages/languages.page

source:
https://www.loc.gov/marc/languages/language_appendix.pdf
Relates to internetarchive/openlibrary-librarians#80 and a number of other language related comments and issues that are still open.
Relates to internetarchive/openlibrary#8127 , especially the list 1–4
@cdrini , commiting this might not be sufficient to update the code pages , e.g. https://openlibrary.org/languages/him 
Do you have a process to update these pages automatically?
@tfmorris 
@cdrini

Language code updates

---

openlibrary/i18n/messages.pot
openlibrary/templates/history/comment.html
openlibrary/templates/history/sources.html
openlibrary/templates/type/edition/view.html

List source_records

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

add newlines, fix issue templates: contributor instructions

---

openlibrary/plugins/openlibrary/js/realtime_account_validation.js

Closes #9465. 
Fix. Prevents duplicate registration form submission by removing one of the two calls to `grecaptcha`.
Our registration form was accidentally using both the [button method](https://developers.google.com/recaptcha/docs/invisible#auto_render) and the [programmatic method](https://developers.google.com/recaptcha/docs/invisible#programmatic_execute) to execute the `grecaptcha`, each of which in turn ran a few validation checks (including HTML validation) then submitted the form.
So the solution was simply removing the programmatic method (a click handler in `realtime_account_validation.js`)!
1. Go to `/account/create`
2. Try to make a new account using a fresh email and correctly formatted inputs
3. The form should submit and display a success message
**Bonus test to confirm …

Remove on-click firing of grecaptcha

---

scripts/partner_batch_imports.py
scripts/tests/test_partner_batch_imports.py

Addendum to #9456 . I noticed as I was making the changes that we were dropping a lot of useful data/identifiers, so decided to add them in.
Updated unit tests.
@mekarpeles

Use ISSN, DOI, and dewey decimal from partner batch import

---

openlibrary/templates/about/team.json

updating team page json

---

.github/workflows/cron_watcher.yml

Makes following updates to the `cron_watcher` workflow:
- Slack messages are published to `#team-abc-plus`
- Fixed message formatting

Update `cron_watcher` Slack channel and message

---

scripts/oldump.sh

Closes #9521
closing `fi` to fix data dump script

fix #9521 data dumps script regression

---

openlibrary/plugins/README.md

Fix typo in `/openlibrary/plugins` README

---

.github/ISSUE_TEMPLATE/post_mortem.md

Update post mortem template

---

openlibrary/plugins/openlibrary/js/dropper/Dropper.js

Fix type typo

---

openlibrary/book_providers.py
openlibrary/i18n/messages.pot
openlibrary/templates/book_providers/ia_download_options.html

Closes #9554
Related: #6585 
Fix LCP PDF. This has changes broken out from #6585.
@cdrini

Add LCP download links for IA

---

openlibrary/plugins/openlibrary/js/covers.js
openlibrary/templates/authors/infobox.html
openlibrary/templates/covers/change.html
openlibrary/templates/type/author/view.html

Closes #9473 
changed id based rendering to class based rendering in the covers.

changed covers to use class instead of id

---

openlibrary/plugins/openlibrary/js/dropper/Dropper.js

Edited `Dropper.js` comment for clarity.

Fix grammar in docstring

---

openlibrary/coverstore/coverlib.py
requirements.txt

Closes #
Update Pillow to 10.4.0.
Tested with cover uploads and lists.

Fix: Update Pillow to 10.4.0

---

scripts/oldump.sh

Noticed the new dump generated without the underscore! Which is a typo.

Fix cover metadata dump filename typo

---

openlibrary/components/BulkSearch/components/BulkSearchControls.vue

Closes #9713
This PR adjust the behavior of the feature when in the process of extracting books from provided text, or when matching titles and authors to works in the Solr database. Specifically, it disables the relevant button and changes its text to 'Loading', until the relevant function returns a result. 
To test: 
You'll need an OpenAI API key in order to test the "Extract Books" button, as the loading time is otherwise nonexistent. For match books, however, simply use one of the samples, select the appropriate extraction algorithm, hit extract, and then hit match. 
@cdrini

Added loading indicator to BulkSearch buttons.

---

requirements.txt

Closes #
Updates Pydantic to 2.4.0.
Tested with
- Tested with importing via `/api/import`, with both valid and invalid imports. Results were the same for the imports tested.

Fix: update Pydantic to 2.4.0

---

openlibrary/i18n/sc/messages.po

Only three strings are missing, because it's difficult to translate them without context.
1 - "This updates  and  fields of /, /works, /books and /authors records in the database." - What is "and" supposed to mean here? Is it a boolean logical operator? Also I've left things like "/works" in English in other strings, I hope it's the correct choice.
2 - "Print Slips"
3 - "Dry Run"
Closes #

Update Sardinian translation

---

openlibrary/macros/FulltextSearchSuggestion.html
openlibrary/macros/FulltextSuggestionSnippet.html

Amends + closes #9734 
Takes out unused variable and makes html fix. 
@mekarpeles

Amendments to #9734

---

openlibrary/i18n/messages.pot
openlibrary/plugins/openlibrary/pages/languages.page
openlibrary/plugins/openlibrary/types/language.type
openlibrary/plugins/upstream/utils.py
openlibrary/templates/type/language/view.html

This is an attempt to sort out various language code issues
* Closes #863 
* Closes #864
* Closes #6062 
and possibly other duplicate reports
It builds on #9365  , and feeds into the required work of updating this data to production in #9447
Also will enable:
* #9504
*
**Before:**
**After:** After editing `/languages/far` to add `"deprecated": true` (and clearing browser cache for http://localhost:8080/languages/_autocomplete?q=Faroe&limit=6)
http://localhost:8080/languages/far

Language code deprecations and alternatives: fixes duplicate languages in dropdowns

---

openlibrary/plugins/openlibrary/config/author/identifiers.yml
openlibrary/plugins/openlibrary/config/edition/identifiers.yml

Closes https://github.com/internetarchive/openlibrary/issues/7323
feature
Adds support for the National Library Service of Italy’s identifiers to both authors and editions.
Data values were strongly inspired by these Wikidata properties:
- Author: https://www.wikidata.org/wiki/Property:P396
- Edition: https://www.wikidata.org/wiki/Property:P5485
Work identifiers are [not yet available in code](https://github.com/internetarchive/openlibrary/pull/9798), so someone would need to edit [`/config/work.yml`](https://openlibrary.org/config/work.yml) manually and add something like
```yaml
-   label: SBN/ICCU (National Library Service of Italy)
name: opac_sbn
notes: format is /^\D{2}[A-Z0-3][E0-2]\d{6}$/
url: https://opac.sbn.it/opera/@@@
website: https://opac.sbn.it/
```
for support of their Work …

Add SBN(/ICCU) identifiers for authors+editions

---

openlibrary/i18n/messages.pot
openlibrary/templates/check_ins/check_in_prompt.html
static/css/components/check-in.less
static/css/components/read-panel.less
static/css/components/searchResultItemCta.less

closes #9825 
From:
To:
Checkin prompt:
Last read date:
Author page:
Search: 
Reading log:

fix checkin msg size

---

openlibrary/plugins/openlibrary/pages/languages.page

relates to #9447 , but going the other way; updating the committed data with values from the production config.

minor language updates from current production values

---

openlibrary/i18n/messages.pot
openlibrary/plugins/openlibrary/code.py
openlibrary/templates/batch_import.html

Closes #9487
Adds a text box on `/import/batch/new` for optional batch import via copy/paste, instead of a file attachment.
1. Visit http://localhost:8080/import/batch/new
2. Copy/paste JSON into the text box and import.
3. See that the records are there, e.g.
```
-[ RECORD 1 ]----------------------------
id          | 7
batch_id    | 6
added_time  | 2024-09-10 04:01:56.742681
import_time | 
status      | pending
error       | 
ia_id       | open_textbook_library:1581
data        | {"authors": [{"name": "Tiffany Jackman"}], "description": "Healthcare, a field dedicated to the well-being of individuals and communities, operates within an intricate web of legal principles. Understanding these laws is not simply a professional necessity for doctors, nurses, administrators, and researchers; …
```

Feature: Add a text area for raw JSON copy/paste on /import/batch/new

---

.gitpod.yml
compose.yaml

Tweak gitpod coverstore env file to support older docker versions

---

openlibrary/templates/site/head.html

This was updated on the IA side, and we can avoid a redirect by hitting the direct name.

Update archive preconnect to new name, athena

---

openlibrary/core/models.py

Closes #
Corrects misleading docstring.

Update Tag docstring

---

conf/openlibrary.yml
openlibrary/core/fulltext.py
openlibrary/core/lending.py
openlibrary/core/sponsorships.py
openlibrary/plugins/openlibrary/code.py
openlibrary/plugins/openlibrary/home.py
openlibrary/plugins/upstream/utils.py
openlibrary/solr/data_provider.py
openlibrary/templates/home/index.html

Added new config `offline_mode`, which, when true, mocks calls to Internet Archive. Additionally, the homepage stats component will not render while in offline mode, as these stats are being fetched from IA.
These changes speed up and remove errors from the following pages:
- The homepage
- Search pages
- Book pages
- My Books pages

Minimal changes for an offline mode

---

openlibrary/core/lending.py

unbreak OL when IA lending is WAF'd

---

compose.production.yaml

To enable git pulls from within firewall
Closes #

volume mount prod web

---

openlibrary/templates/about/team.json

Updates json for team page re: #9352

adding super librarians and 2024 fellows

---

openlibrary/accounts/model.py
openlibrary/i18n/messages.pot
openlibrary/plugins/upstream/account.py
openlibrary/templates/account/create.html

Add banner noting registration is temporarily offline.

Add banner to registration page

---

.github/workflows/olbase.yaml

Add docker olbase GHA flow

---

openlibrary/catalog/add_book/__init__.py
openlibrary/templates/site/alert.html

Avoiding more failing network requests and the like.
@mekarpeles

Apply patch deployed temp fixes

---

openlibrary/code.py
openlibrary/core/models.py
openlibrary/core/waitinglist.py
openlibrary/i18n/__init__.py
openlibrary/i18n/validators.py
openlibrary/records/__init__.py
scripts/tests/test_affiliate_server.py

Part of #9181
These are all the unused imports that aren't std or web/infogami/openlibrary
We may want to review these closely and see if any should be removed.

2. mark unusual unused imports as noqa

---

compose.production.yaml
compose.yaml

Remove prod volume mount; no longer needed

---

openlibrary/core/lending.py
openlibrary/plugins/upstream/borrow.py

Remove old, no longer used br params/cookies

Remove no longer used br params/cookies

---

openlibrary/plugins/upstream/data.py

This is a workaround until it's fixed upstream at IA
Closes #

Fix data dump endpoints erroring due to WAF

---

openlibrary/accounts/model.py
openlibrary/i18n/messages.pot
openlibrary/plugins/upstream/account.py
openlibrary/templates/account/create.html

Closes #9987
Re-enables new account creation via Open Library.
Have confirmed that a new account can be created via OL and verified.  Calls to login and create account can be long, and sometimes time out.  Verification link failed the first time it was used, but worked on the second try.  In short, things work but the experience not be the best.

Enable registration

---

openlibrary/catalog/add_book/__init__.py

Closes #10038
Partially reverts #9979.

Re-enable sync button

---

openlibrary/plugins/upstream/mybooks.py

Fix My Books erroring when IA-only book borrowed

---

openlibrary/core/waitinglist.py
openlibrary/i18n/__init__.py
openlibrary/i18n/validators.py
scripts/tests/test_affiliate_server.py

Part of #9181 
Addressed all the feedback in https://github.com/internetarchive/openlibrary/pull/9996

remove unused imports feedback

---

openlibrary/plugins/upstream/utils.py
openlibrary/templates/site/alert.html
openlibrary/templates/site/donate.html
openlibrary/templates/site/donation_banner.html

Re-enable donations banner

---

openlibrary/templates/authors/infobox.html

Followup to https://github.com/internetarchive/openlibrary/pull/9991#discussion_r1854401774

add tracking to wikidata infobox social links

---

static/css/legacy.less

Closes #10070
#10056 inspired me to check for unused CSS in this file.
I found quite a few that don't appear to be used anywhere at all.
Please take a quick double check before merging.
Because our linter doesn't like there being multiple #contentbody I had to merge them.

remove unused css

---

openlibrary/i18n/sc/messages.po

Updated Sardinian translation. The only missing string is "Dry run", could I have some context about it, please?

Updated Sardinian translation

---

openlibrary/i18n/as/messages.po

Limited to 5 translations for now as an initial i18n for Assamese.
This provides an i18n for Assamese
@mekarpeles could you review? Apologies I am unsure of other stakeholders...

Create messages.po for Assamese i18n

---

openlibrary/i18n/messages.pot
openlibrary/templates/diff.html

Closes #7509
Follows the style of the diff button on the author merge page here.
https://openlibrary.org/recentchanges/2021/08/31/merge-authors/84543795
But don't feel strongly about the style.
Merge two works then view the diff of an edition of the work like this:
http://localhost:8080/books/OL669819M/Creepy_Classics_II?_compare=Compare&b=2&a=1&m=diff
@seabelis

add diff history links

---

pyproject.toml

Closes #10074
Noticed the python version for ruff was out of sync with what we use.
Figured I'd update it.
As far as I know this has no risks.

update ruff python version

---

openlibrary/i18n/cs/messages.po

Fixed some grammar, added  some  translations

---

openlibrary/core/processors/invalidation.py
openlibrary/coverstore/db.py
openlibrary/data/db.py
openlibrary/plugins/admin/code.py
openlibrary/plugins/ol_infobase.py
openlibrary/plugins/openlibrary/api.py
openlibrary/plugins/openlibrary/lists.py
openlibrary/plugins/upstream/addbook.py
openlibrary/plugins/upstream/models.py
openlibrary/plugins/upstream/mybooks.py
openlibrary/plugins/upstream/spamcheck.py
openlibrary/plugins/upstream/utils.py
openlibrary/utils/dateutil.py
openlibrary/utils/isbn.py

Needed for #10187
This is a fully automated fix based on
https://docs.astral.sh/ruff/rules/parenthesize-chained-operators/
Personally, I also think this is a nice improvement to readability :)

fix ruff chained operators RUF021

---

openlibrary/core/cache.py
openlibrary/core/formats.py
openlibrary/coverstore/coverlib.py
openlibrary/coverstore/oldb.py
openlibrary/plugins/worksearch/subjects.py
openlibrary/utils/schema.py

In preparation for #10187
A more recent version of ruff started sorting the imports in __all__ so this is making that change for us.

sort the imports from __all__

---

scripts/deployment/deploy.sh
scripts/deployment/restart_servers.sh

Make deploy.sh ready for business! 
Follow the deployment instructions; they should now work!

Various fixes to deploy scripts

---

openlibrary/i18n/messages.pot
openlibrary/templates/observations/review_component.html

Closes #10197
Fix: Removes redundant "Feedback" button from the review component UI.
- Removed the "Feedback" button from `review_component.html`.
- The button was no longer functional and caused unnecessary clutter in the UI.
1. Navigate to any book details page.
2. Go to the "Overview" tab.
3. Verify that the "Feedback" button no longer appears in the UI.
@RayBB

Fixed#10197: Removed redundant 'Feedback' button

---

openlibrary/i18n/messages.pot
openlibrary/templates/lib/nav_foot.html

Closes #10200
Change **report a problem** footer link to **contact us**
Go to the footer part of any page eg(https://openlibrary.org/)
Before:
After:

Changed Report a problem to contact us

---

docker/web_nginx.conf

simple fix to add nginx domain verification for bluesky

add bluesky did to nginx

---

openlibrary/core/vendors.py
openlibrary/tests/core/test_vendors.py

Closes #9885 
Separates author from translator in imported data
Updated tests to match these changes.Tests included in test_vendors.py
@scottbarnes

Distinguish author versus translator

---

static/css/components/nav-bar.less

#10064 
Fixes the arrow alignment issue
1)Go to any book page (eg. https://openlibrary.org/works/OL69166W/Italian_journeys)
2)Resize the screen and see the arrow alignment issue
**Before:**
**After:**
@cdrini

Fix arrow alignment in edition omnibar

---

scripts/dev-instance/load-patron-data.sh
scripts/dev-instance/patron_data.sql

Closes #10153 
Feature
Populates data for reviews, reading logs, and a list for the default OpenLibrary dev user via shell script.
The shell script includes a step to restart the memcached docker container to ensure that the list created though ```patron_data.sql``` DML commands is visible on the My Books page.
DML commands to create a list includes additional INSERT INTO commands to prevent errors for pages that reference the list's revision history.
1. Run ```docker compose up -d```
2. Ensure that the psql database is in an unmodified state (i.e. does not have a pre-existing list as OL1L, reviews, or want to read/already read/currently reading for specific works or editions). This typically means that the My Books page has nothing in the sidebar's Reading Log, My Reviews, and My Lists. …

Create review, reading log, and list DML and shell script

---

.github/workflows/olbase.yaml

Revert https://github.com/internetarchive/openlibrary/pull/10289 . The issue on docker hub appeared to be a problem on their end which has been resolved, so this can be brought back.

Bring back test branch docker hub builds

---

openlibrary/i18n/messages.pot
openlibrary/templates/type/author/view.html

Part of https://github.com/internetarchive/openlibrary/issues/10331
Just removing a feature we no longer need.

remove outdated author wikipedia logic

---

docker/README.md

improved docker documentation

---

docker/README.md

Fix spelling error in README

---

docker/README.md

fix anchor links, add gitpod docs

---

CONTRIBUTING.md
Readme.md

Closes #9318 
Opening on behalf of @jimchamp

Remove `quickstart` references

---

openlibrary/core/wikidata.py

Addresses #10444
Updates the Wikidata API URL to the latest version.

Update Wikidata URL

---

.github/workflows/docs_gh_pages.yml

Closes #
With this we should be able to deploy the vitepress docs.
To test with Drini tomorrow
Mostly from: https://vitepress.dev/guide/deploy#github-pages
Demo: https://github.com/RayBB/ol-docs-deploy-testing
Next steps to do after this is working:
- Look at the docs dump

deploy vitepress docs

---

openlibrary/core/lending.py
openlibrary/tests/core/test_lending.py

Add user agent to availability requests

---

scripts/deployment/deploy.sh

Closes #10493
Exits from deployment script early whenever any critical `cron` job is found to be running.  Critical job check can be bypassed if `KILL_CRON` environment variable is a non-empty string.

Stop deployment script when critical jobs are running

---

scripts/deployment/deploy.sh

Addendum to #10514
Running it worked as expected.

Fix bug with check crons in deploy.sh

---

openlibrary/core/lists/model.py
openlibrary/coverstore/code.py
openlibrary/plugins/upstream/models.py

Fix sentry error: https://sentry.archive.org/organizations/ia-ux/issues/44440/?environment=production&project=7&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=15
Also fix some type issues:
- Handle list missing name
- Fix `Image.LANCZOS` non-existant; should be `Image.Resampling.LANCZOS`
- Various type annotations added to models
https://testing.openlibrary.org/people/DP106/lists/OL194484L/Ancient_History/preview.png

Fix lists preview erroring subjects

---

openlibrary/core/cache.py

Small refactor removing some old code here.
Homepage loads with caching on testing

Add some types + rm py2 code in cache.py

---

static/robots.txt

add publishers to disallow for sitemaps

---

openlibrary/i18n/ro/messages.po

Add missing strings to the romanian translation.
Closes #
Nothing.
The testing was done locally.
The UI was not modified.

More completions to the romanian translation

---

docker/README.md

update docker architecture build instructions

---

openlibrary/core/ia.py

move exempt_collection to separate importable var

---

scripts/deployment/restart_servers.sh

Remove build flag from server restart script

---

scripts/deployment/deploy.sh

fix deploy cron check

---

scripts/monitoring/requirements.txt

Addendum to #10522 
Needs to be installed for root as well
Tested by updating the requirements.txt on prod and rebuilding. Fixed it up!

Add APScheduler to monitoring requirements

---

Readme_es.md

Closes # 10545
Create Readme_es.md
@mekarpeles

Readme_es.md double checked

---

Readme.md

Adds a Spanish translation (README_es.md) for the Open Library project.
- Translated the main README.md file into Spanish.
- Added a reference link to README_es.md in the original README.md.
- Verified that README_es.md maintains proper Markdown formatting.
- Ensured links and headers are intact.
- No breaking changes; this is a documentation improvement.

Added Spanish translation for README.md

---

scripts/monitoring/monitor.py
scripts/monitoring/utils.sh

Add the old top IP monitoring to the new monitoring service.

Add top ip monitoring

---

Readme_vn.md

Description:
This PR introduces a Vietnamese translation of the OpenLibrary's README file to enhance accessibility and inclusivity for contributors from Vietnam.
Key Highlights:
- Added a new file Readme_vn.md in the project root directory.
Purpose: The addition of this README aims to:
- Promote OpenLibrary's mission to Vietnamese audience and support a growing number of Vietnamese developers.
Testing:
No code changes were made, so functionality remains unaffected. A proofread of the README ensures language accuracy and clarity.
Attribution Disclaimer: 
By proposing this pull request, I affirm to have made a best-effort and exercised my discretion to make sure relevant sections of this code which substantially leverage code suggestions, code generation, or code snippets from sources (e.g. …

Add a Vietnamese readme

---

openlibrary/macros/BookByline.html

Fix book byline including spaces around commas

---

openlibrary/i18n/messages.pot
openlibrary/plugins/openlibrary/lists.py
openlibrary/templates/type/list/edit.html

Switch from admin-only based on discussion in community call.

Make creating/editing global lists public

---

openlibrary/macros/StarRatingsByline.html
openlibrary/macros/StarRatingsStats.html

Fix #10511 schema.org ratings microdata add ratingCount

---

bundlesize.config.json

Bump bundlesizes

---

openlibrary/plugins/openlibrary/api.py

author api endpoint 404 returns json

---

openlibrary/plugins/openlibrary/js/index.js

Does the following:
- Adds a chunk name to our team page JS
- Removes redundant logic

`index.js` update

---

scripts/deployment/deploy.sh

Closes #10603 -- we're happy with the flow now that github releases generate notes and our flow links to latest release

rm unused deploy slack method

---

openlibrary/plugins/openlibrary/config/author/identifiers.yml

Eg https://www.patreon.com/robertjsawyer to https://openlibrary.org/authors/OL23251A/Robert_J._Sawyer

Add patreon author identifier

---

openlibrary/plugins/openlibrary/code.py

Closes #10708
Feature: this requires a logged in account to create a batch import.
Try visiting `/import/batch/new` both while logged in and while not logged in. It should only display the page if logged in.
@cdrini

Feature: require logged in account to create batch import

---

scripts/update_stale_ocaid_references.py

Closes #8343 @mekarpeles doesn't intend to set this up as a cron for now, too brittle, but it seems sufficient to manually run every few months and easy enough to cronify
This was was last run through 2025-04-21 (any maybe should be run again ~Oct)
Also, we need @ximm to help us add `dark` scope to the s3 keys mentioned (as we were using a different s3 set as a work-around to run this script)

Updating stale ocaid script

---

docker/web_nginx.conf

block certain requests for no referer

---

openlibrary/templates/type/work/editions_datatable.html

Add `rel="noreferrer"` to book page "add book" link

---

openlibrary/book_providers.py
openlibrary/catalog/add_book/__init__.py
scripts/providers/import_wikisource.py

Work towards #9671 .
Small tweaks and fixes to the way the import works. Also in line with how we handle Gutenberg and Standard Ebooks, avoid saving some metadata that applies only to the origin source edition.
@pidgezero-one

Small fixes to wikisource import

---

scripts/deployment/patchdeploy.sh

Closes #10775
Reviewed already by @mekarpeles and @cdrini

Followup on patch deploy script #10775

---

docker/nginx.conf
docker/web_nginx.conf

update rate limits for api

---

openlibrary/plugins/upstream/merge_authors.py

Addresses #10887 
Removes code that writes `merge-authors-debug` type records to the `store` and `store_index` tables.

Remove code that stores author merge debug data in DB

---

scripts/obfi.sh

Add experimental obfi_range command

---

openlibrary/plugins/worksearch/code.py
openlibrary/plugins/worksearch/schemes/__init__.py
openlibrary/plugins/worksearch/schemes/authors.py
openlibrary/plugins/worksearch/schemes/editions.py
openlibrary/plugins/worksearch/schemes/lists.py
openlibrary/plugins/worksearch/schemes/subjects.py
openlibrary/plugins/worksearch/schemes/works.py

Followup to https://github.com/internetarchive/openlibrary/pull/10283#issuecomment-2940908216
This is using immutable types which guards us against unexpected runtime bugs and gives us nice static checks.

fix RUF012 for schemes

---

Readme_vn.md

About:
This PR fixes some minor punctuation error, clarifies some term and updates the documentation `Readme_vn.md` based on the newest `Readme.md`  file. The changes are made to ensure that the instruction are easier to follow and more approachable for future Vietnamese contributors.
1. Open `Readme_vn.md` in preview mode on GitHub.
2. Open `Readme.md` in preview mode on GitHub.
3. Check for any differences in meaning between two documentation as well as verify that the links are working properly and leading to the same website after the edit process.
4. Confirm there are no syntax related problems afterward. 
N/A — This is a markdown file update only.
@internetarchive/openlibrary-maintainers

Further improve fluency, punctuation and clarity of the Readme_vn.md

---

.gitignore
scripts/build_pwa.sh
twa-manifest.json

Closes #10475 and makes builds reproducible with `./scripts/build_pwa.sh`

adding twa-manifest.json to repo + scripts/build_pwa.sh

---

openlibrary/plugins/openlibrary/pd.py

Alphabetically sorts the PDA list that was fetched from IA.  This list is appended to the default PDA drop-down options.

Sort print disability qualifying authority options alphabetically

---

openlibrary/accounts/model.py
openlibrary/core/ia.py
openlibrary/core/lending.py
openlibrary/plugins/importapi/code.py
openlibrary/plugins/openlibrary/code.py
openlibrary/plugins/openlibrary/connection.py
openlibrary/plugins/recaptcha/recaptcha.py
openlibrary/plugins/upstream/account.py
openlibrary/plugins/upstream/borrow.py
openlibrary/plugins/upstream/models.py
openlibrary/plugins/upstream/utils.py

Closes #
This was a semi-automated change by ruff to start removing some unused variables.

remove unused variables in exceptions

---

docker/README.md

As you can see here https://github.com/internetarchive/openlibrary/issues/10276 architecture specific issues are resolved.
So lets remove this extra cruft from the docs about it not working well.

remove mention of architecture specific issues from docker docs

---

docker/web_nginx.conf

Effectively closes #10917 and #10903 by scoping the /edit fix and also only applying to logged out traffic

apply noref nginx rules only if logged out

---

scripts/deployment/deploy.sh

fixes deploy script

---

openlibrary/templates/account/email/forgot-ia.html
openlibrary/templates/account/password/forgot.html
openlibrary/templates/login.html

Fix IA forgot password link

---

openlibrary/plugins/openlibrary/js/ile/utils/SelectionManager/SelectionManager.js

add work title to ile selection tool

---

scripts/deployment/deploy.sh

Applies co-pilot review notes from #11060
Updates `deploy.sh`, replacing tab characters with spaces and removing an `echo` statement that was used for debugging.

Apply Copilot review notes to `deploy.sh`

---

openlibrary/plugins/openlibrary/js/SearchBar.js
static/css/components/header-bar.less

Closes #11018
| ------- | ------ |
| <img width="479" height="550" alt="image" src="https://github.com/user-attachments/assets/7ebaf241-b955-44fa-b299-4dfd7bde8fbc" /> | <img width="482" height="605" alt="image" src="https://github.com/user-attachments/assets/44abd416-5dff-4802-bbcf-93fab8f16166" /> |
| <img width="485" height="362" alt="image" src="https://github.com/user-attachments/assets/794cce8d-caa6-4f88-8402-4788dc389ef0" /> | <img width="496" height="369" alt="image" src="https://github.com/user-attachments/assets/9fe9a5a2-0997-441d-9c07-a3b1c0535150" /> |
Note there's still something off with the search ranking... see https://github.com/internetarchive/openlibrary/issues/10969 . But this should help non-English users find the book they want.

Make autocomplete edition-aware

---

openlibrary/plugins/worksearch/code.py

Closes #10964
Note this will add a DB request to author pages/trending pages/list pages to intersect the solr results with the db. Will monitor performance of these pages, but I reckon it should not be significant since our search pages also do this. Long term we should be able to remove this as part of #10470 .
Read button appears on https://testing.openlibrary.org/authors/OL8527300A/Brad_Frost

Fix author pages not showing Read button for direct book provider

---

openlibrary/core/ia.py
openlibrary/core/lending.py

- **add typehints to ia model**
- **add more ia types**
- **add more ia types 2**
- **add more ia types 3**
- **add some types to lending.py**
- **add some types to lending.py 2**
- **add some types to lending.py 3**
- **add some types to lending.py 4**
Closes #

add typehints to ia and lending

---

openlibrary/plugins/openlibrary/config/edition/identifiers.yml

Fix OverDrive identifier URL

---

openlibrary/accounts/model.py
openlibrary/core/waitinglist.py
openlibrary/core/wikidata.py
openlibrary/core/yearly_reading_goals.py
pyproject.toml

- **disallow untyped definitions in wikidata**
- **add typehints to yearly reading goals**
- **add types to waitinglist.py**
Closes #

add typehints to wikidata, reading goals, and waitinglist

---

openlibrary/core/models.py
openlibrary/plugins/worksearch/subjects.py
openlibrary/templates/publishers/view.html
openlibrary/templates/subjects.html

Closes #11123
- ✅ https://testing.openlibrary.org/subjects/person:ned_wilcox no longer errors.
- ✅ Normal subjects still work
- ✅ Publisher pages work

Fix people/place/time subject pages erroring

---

compose.production.yaml
openlibrary/macros/RawQueryCarousel.html
openlibrary/plugins/openlibrary/partials.py
openlibrary/plugins/worksearch/code.py
openlibrary/plugins/worksearch/schemes/works.py
scripts/deployment/deploy.sh
scripts/monitoring/haproxy_monitor.py
scripts/monitoring/monitor.py
scripts/monitoring/solr_logs_monitor.py
scripts/monitoring/tests/test_solr_logs_monitor.py
scripts/monitoring/tests/test_utils_sh.py
scripts/monitoring/utils.sh
scripts/obfi.sh

Closes #10290 
Closes #10239 
1. Adds a graph to monitor specifically the homepage appearing with no books (work towards #11145)
When this is 0, it means the homepage is empty.
3. Adds a monitor that watches over the solr logs and tracks various things like run time
- Note: there are some cases where the query is so long that it gets truncated! These are currently skipped over
4. Adds a `query_label` option to a few spots we make solr queries that we can use to monitor certain types of queries
- Note we likely want maybe another option, client to monitor eg internal queries vs public API queries
- Haven't tested; this must be patch deployed to the web nodes in order to see if the labels are applied correctly
5. Add ol-solr0/ol-solr1 to our deploy flow. This lets these monitoring changes …

Improve solr + nginx performance monitoring

---

scripts/deployment/deploy.sh

fix tag_release

---

static/css/components/language.less

Remove border from dropdown menu in language.less

---

openlibrary/i18n/es/messages.po

Update Spanish translations

---

openlibrary/core/formats.py
openlibrary/core/lending.py
openlibrary/core/models.py
openlibrary/core/observations.py
openlibrary/plugins/upstream/account.py
openlibrary/plugins/worksearch/subjects.py
openlibrary/solr/updater/list.py
openlibrary/utils/schema.py

- **use SubjectType typehint literals**
- **typehint literals as needed**
- **observations type literal**
- **add literal to schema.py**
Follow up to https://github.com/internetarchive/openlibrary/pull/11003#issuecomment-3098468324
Adds some type literals.

add typehint literals where possible

---

openlibrary/components/IdentifiersInput.vue

Addresses https://github.com/internetarchive/openlibrary/issues/854#issuecomment-3228680082
Fix IA identifier permissions on book page. Removing was correctly blocked, adding had a bug, so removed/disabled it in the dropper.
Tested on testing.openlibrary.org with a non-admin account, and confirmed worked correctly.

Fix ia identifier editing

---

openlibrary/schemata/author.schema.json
openlibrary/schemata/edition.schema.json
openlibrary/schemata/import.schema.json
openlibrary/schemata/shared_definitions.json
openlibrary/schemata/work.schema.json

Addresses #11225
Add schemata files from olclient

Add schemata files from olclient

---

openlibrary/core/vendors.py

Helps fix #11280 so we can re-instate `/isbn`

Add timeout parameter to API request function

---

openlibrary/plugins/openlibrary/config/edition/identifiers.yml

Removing unsupported identifier from the configuration.
Reverts adding an unsupported identifier, as per discussion w/ @seabelis

Removing unsupported identifier

---

openlibrary/components/MergeUI/utils.js

Closes #11194
I'm not sure how to test this since we don't have 429s on local but I think it should be pretty safe.

retry mergeUI POST request
