internetarchive/openlibrary

openlibrary/conftest.py, openlibrary/solr/update_work.py, openlibrary/tests/core/test_cache.py, openlibrary/tests/core/test_init.py, openlibrary/tests/solr/test_update_work.py, openlibrary/utils/retry.py, openlibrary/utils/tests/test_retry.py
Closes #6400 . Adds retry logic to `solr_update` to fix issues had during the catch-up phase of full solr reindex.
=> Improve solr_update POST error handling

docker/ol-nginx-start.sh
The logrotate file has to be owned by root for some inexplicable reason. Fixes covers0 running out of storage on /1/
I ran the steps manually on the nginx container; after the chown, `logrotate --verbose -f /etc/logrotate.d/nginx` finally worked. It's still being weird, and storing all the logs in access.log (which are since Dec 2021) into `access.log-20220410.gz` but whatever; at least they're gzipping.
Haven't tested the full flow here of running it when the image is constructed, but I imagine it should work ok?
=> Hotfix nginx logrotate not working

openlibrary/config.py, openlibrary/plugins/worksearch/code.py, openlibrary/plugins/worksearch/tests/test_worksearch.py, openlibrary/solr/update_work.py, openlibrary/tests/core/test_fulltext.py, openlibrary/tests/solr/test_update_work.py
Closes #6422 . Closes #2355 (after a full reindex). Closes #6256 . 
Observable changes right now:
- `subtitle:` field in search queries will now search all edition subtitles
- `work_subtitle:` field in search queries will search only the work subtitle
Observable changes after full reindex:
- `title` field will search across all edition titles and subtitles
- `work_title:` field will search only work title
- I was debating whether keeping subtitles out of `alternative_title` might be best to avoid noise in search results... We could potentially make title map to something like `alternative_title:$q^10 OR alternative_subtitle:$q`... I think we'll just have to compare results after the next reindex to see if they're better.
- I was also concerned with duplicating the subtitle data in …
=> Make `title` include all edition titles/subtitle so we can use it as default title search

openlibrary/plugins/worksearch/code.py, openlibrary/plugins/worksearch/tests/test_worksearch.py, openlibrary/tests/core/test_fulltext.py
update_work.load_config always load conf/openlibrary.yml -_- Completely borking testing.openlibrary.org and staging.openlibrary.org
Closes #
=> Do not call load_config before setup()

openlibrary/macros/EditionNavBar.html, openlibrary/templates/type/edition/view.html
=> Added 'Related Books' to Book Page Nav Menu #6436

static/css/components/work.less
Closes #6431 
- Fixes Book Page navigation bar overflow on mobile
N/A
1. `docker-compose exec web make css js` 
2. Inspect element 
3. Toggle device toolbar 
4. Scroll down to nav bar 
@jimchamp
=> resolves navbar overflow mobile

openlibrary/plugins/openlibrary/js/edition-nav-bar/index.js
Corrects issue where position-aware navbar is not updating properly when the page is quickly scrolled.
=> Fix incorrect selected element in navbar on fast scroll

openlibrary/plugins/upstream/mybooks.py, openlibrary/templates/account.html, openlibrary/templates/account/books.html, openlibrary/templates/account/sidebar.html
Refactors the sidebar out of the account/books.html template and plugins/mybooks.py so that it can be added/used w/ the /account settings page.
~NB: The old sidebar.html code is remains / is **duplicated** by this PR and needs to be consolidated + cleaned up in account/books.html template~
@jimchamp @cdrini
=> refactors + adds sidebar to account settings

openlibrary/plugins/openlibrary/js/readmore.js, tests/unit/js/readMore.test.js
Closes #6401 
- Fix such that the "read more/less" button does not appear
- Button will also appear/disappear when the screen gets resized
- Resizing based off of code from `SearchBar.js`
- Hardcoded `58` is based off of the height of `.restricted-height` (made a comment in the code itself)
(Locally): [http://localhost:8080/works/OL13101191W/Alice%27s_Adventures_in_Wonderland](http://localhost:8080/works/OL13101191W/Alice%27s_Adventures_in_Wonderland
)
With resizing in action (sorry for low quality):
@jimchamp
=> fix read more link issue

bundlesize.config.json, openlibrary/plugins/openlibrary/js/compact-title/index.js, openlibrary/plugins/openlibrary/js/index.js, openlibrary/templates/site/head.html, openlibrary/templates/type/edition/book_title.html, openlibrary/templates/type/edition/compact_title.html, openlibrary/templates/type/edition/view.html, static/css/components/buttonLink.less, static/css/components/compact-title.less, static/css/components/readerStats.less, static/css/components/work.less
Creates a compact version of the books page title component.  New component includes an edit button and smaller text.  Title text overflow is replaced by an ellipsis.
Compact title component slides in and out of place, dependent on the navbar's position on the Y-axis.  The navbar appears below the compact title.
__This change does not affect mobile views__
This requires JS to determine when to display or hide the compact title component.  This JS is loaded if a navbar is detected on the current page.
Internal CSS has been added for `noscript` patrons to ensure that the navbar is positioned at the top of the page.
CSS variables are used to help with component layout.  The `calc` function was particularly handy for this, and Less surprisingly (to me) did not have an equivalent function.
A …
=> Sticky title to top of books page

.github/workflows/python_tests.yml
- Basically the same as the paths in https://github.com/internetarchive/openlibrary/blob/master/.github/workflows/javascript_tests.yml .
- Note `paths-ignore` will skip the job only if ALL modified paths match the patterns. Even if one path does not, it will run the job.  See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
- Also remove Python version matrix since we'll only be on one python for the foreseeable future.
=> Don't run Python tests when only JS changes

openlibrary/plugins/openlibrary/js/edition-nav-bar/index.js, static/css/components/compact-title.less, static/css/components/work.less, static/css/layout/index.less
Addendum to #6451 . Adds auto scrolling to navbar, and some offset, to make it more clearly scrollable on mobile devices.
- Ignore the faint scrollbar; that's just desktop FF
https://user-images.githubusercontent.com/6251786/164290645-80031393-bd23-46a7-93db-cb5edebf112a.mp4
=> Tweaks to mobile navbar UX

scripts/cron_watcher.py
A script that checks to see that our cron jobs have competed their respective tasks.
Currently it checks to see if the ol-dump and ol-cdumps for the previous month are stored at
*  https://archive.org/details/ol_exports?sort=-publicdate
Long term, the script should cover more cron jobs:
Daily Cron-audit task (Python) sentry (who watches the watchers)
If dump and cdump for last YYYY-MM were not uploaded to archive.org
Or if sitemaps updated for this YYYY-MM were not on transferred to ol-www
Or if  partner dumps for this YYYY-MM were not uploaded to archive.org
Or if there have been no imports in last 48 hours (i.e. 2 days)
Or if DD>17 for YYYY-MM and bwb `batchname` doesn’t exist in import psql table
Then send daily email with failures only or slack failures …
=> Add scripts/cron_watcher.py

tests/unit/js/html-test-data.js, tests/unit/js/readmore.test.js
Closes  #6461 
It achieves further testing on the initClampers function covering most of its lines(except line: 59). Specifically it tests the pull request #6445 which fixes the subject area expanding/collapsing problem when an anchor tag is being clicked. 
It is using jest to perform the mocking and the function ` trigger('click') ` to create a click event.
@cdrini 
@jimchamp
=> Perform further unit testing in the readmore.js file

openlibrary/i18n/de/messages.po, openlibrary/i18n/fr/messages.po, openlibrary/i18n/hr/messages.po, openlibrary/i18n/messages.pot, openlibrary/macros/AuthorList.html, openlibrary/macros/BookByline.html, openlibrary/macros/SearchResultsWork.html, openlibrary/templates/account/loans.html, openlibrary/templates/account/waitlist.html, openlibrary/templates/admin/loans_table.html, openlibrary/templates/books/edit.html, openlibrary/templates/borrow_admin.html, openlibrary/templates/type/edition/view.html
Prep refactor of some code for editions in solr.
- Uses babel to commify lists instead of manual `', '.join` combining. This i18n better
- Delete an old template, but there are load of other places we do this type of thing
- Truncation works the same: https://testing.openlibrary.org/authors/OL60550A/Olaudah_Equiano?q=Prentice+Hall+Literature
- i18n's better: https://testing.openlibrary.org/authors/OL60550A/Olaudah_Equiano?q=Prentice+Hall+Literature&lang=zh
- Edit page now also same: https://testing.openlibrary.org/books/OL32560269M/Prentice_Hall_Literature/edit?lang=zh
- Loans page shows author byline
- Edit pages now also link to authors
=> DRY Book Byline rendering + make it more i18n-able

.eslintrc.json, package-lock.json, package.json, renovate.json
Closes #6336 
Changes `babel-eslint` to `@babel/eslint-parser` because of depreciation 
Since the diff `package-lock.json` cannot be seen, changes came from `npm uninstall babel-eslint` and `npm install @babel/eslint-parser --legacy-peer-deps`. Note that I added `--legacy-peer-deps` because `@babel/eslint-parser` requires all other `@babel` deps to be of version ^7.5, and there are multiple dependencies that do not meet that. (Consequently, updating dependencies could be a separate issue).
Running `npm run lint-fix` should no longer throw any warnings and will display and fix some linting errors in `.vue` files (which could be another pull request).
@cdrini
=> update babel-eslint to @babel/eslint-parser

openlibrary/i18n/README.md
adds documentation to i18n page w/ instructions + script for creating new infogami i18n pages on Open Library
=> add docs for i18n infogami pages

openlibrary/core/db.py, openlibrary/core/observations.py, openlibrary/plugins/upstream/account.py, openlibrary/templates/account/import.html, static/css/page-user.less
Closes #6457
Provides an easy way for patrons to download their book notes, book reviews, star ratings, and lists overview from the account import/export page.  New data is available in CSV format only (maybe it would be nice to export the data as JSON in the future).
Several new buttons have been added to the original UI.  We may want to revisit that page's design in the near future, as the page is more cluttered now.
Added links to Open Library help pages in order to show patrons _what_ they are exporting.  The copy on these pages could probably use a review, as well.
Created new CommonExtras method for getting all data by username.  This method, `select_all_by_username`, was overridden in the Observations class to transform numeric book tag values into words.
@mekarpeles
=> Expand patron exports

requirements_test.txt
=> requirements_test.txt: Upgrade testing dependencies

static/css/components/header-bar.less
Closes #5985
We added come CSS.
@cdrini
=> Fix overlapping of profile icon and hamburger icon in mobile view

openlibrary/templates/books/edit.html
Closes #6471
Adds a hidden submit button prior to the "Delete" submit button.
A form's first submit button is triggered when `enter` is pressed. PR #6273 linked the previously broken top-of-page delete button to the form, making it the form's first submit button.
=> Add hidden submit button

openlibrary/core/vendors.py
Closes #5474 
The /isbn endpoint should retry a few times to see if the __affiliate service__ has the Amazon result in the cache.  If this import is already queued up, the set operation will ensure that it will be ignored automatically.
=> Vendors: Retry getting Amazon data from the affiliate server

scripts/affiliate-server
Related to #5474 
fixes dupes from recache memoize entering queue
=> prevent dupes from affiliate-server queue

webpack.config.js
hotfix
babel-loader now ignores all node_modules not used in the bundling process in webpack
babel-loader readme also  recommends this: https://github.com/babel/babel-loader
Frontend works correctly
@cdrini
=> Exclude node_modules from babel-loader

openlibrary/templates/account/sidebar.html
Adds placeholder list name to account sidebar for any unnamed list.
__Before:__
_This is how untitled lists are displayed in the sidebar in production today._
__After:__
_Sidebar with placeholder list name._
=> Add placeholder list names in sidebar

openlibrary/catalog/marc/parse.py
* Adds `856$y` (Link text) as the preferred link title 
* Adds `856$x` (Nonpublic note) as the last resort fallback if nothing better exists
example DNB import which prompted this:
https://openlibrary.org/books/OL37853872M
It has 3 external links, two of them have `856$x` which were not picked up from the MARC record.
https://openlibrary.org/show-records/marc_dnb_202006/dnb_all_dnbmarc_20200615-4.mrc:10356060428:1529
Reference:
https://www.loc.gov/marc/bibliographic/bd856.html
and guide:
https://www.loc.gov/marc/856guide.html
https://openlibrary.org/books/OL37853872M
Before:
After:
=> Improve external links from MARC imports

openlibrary/plugins/upstream/account.py
Double-quotes were not escaped in the new patron list overview CSV export.  This PR addresses that, and also removes unnecessary log statements.
See also: #6473
1. Find or create a list that contains double-quotes in the description or title (for more confidence, add some commas as well).
2. Export the list overview and open it with your favorite CSV viewer.
3. Ensure that there are exactly six columns per row in the exported data, and that each cell contains reasonable information (only list OLIDs in the `List ID` column, etc).
@mekarpeles
=> Patron export bug fix

openlibrary/templates/type/edition/view.html, static/css/components/work.less
This PR fixes the following issues that were blocking #6506 from being merged into `master`:
1. `compact_title.html` (the "sticky" title and edit button) not being displayed on screen widths that fall between our tablet and desktop headers.
2. Sticky navbar and compact title not spanning the width of the parent container.
3. Line spacing is too low for the mobile title.
__Note:__ Once this PR is approved and merged, the `book-page-integration` branch can be merged into 'master`.
_Before navbar + title width changes_
_After navbar + title width changes_
_Before title line height change_
_After title line height change_
@constantinazouni 
@mekarpeles
=> Small fixes to mobile header PR

bundlesize.config.json, static/css/components/work.less
Closes #6538.
Fix: Increase padding on a book's nav region so it's easier to click on phone/tablets.
Moved padding from .work-menu li to .work-menu li a.
Moved bottom border from .work-menu li.selected and .work-menu li:hover to .work-menu li.selected a and .work-menu li:hover a to match the padding changes.
@cdrini 
@mekarpeles
=> Increase padding on a book's nav region

openlibrary/templates/books/add.html
Closes #6144
Tips from edit.html and edit/edition.html were copied into the label divs.
Navigate to https://openlibrary.org/books/add and check that the tips are updated and required fields are marked.
@seabelis
@brierjon
@mekarpeles
@tuminzee
=> Improve tips on add book

openlibrary/plugins/openlibrary/js/lists/index.js
If a reading log dropper is expanded and any reading log button is pressed, the dropper will collapse.
=> Close dropper on "Want to Read" button click

openlibrary/plugins/openlibrary/js/ile/utils/SelectionManager/SelectionManager.js
Addresses internetarchive/openlibrary#6556
When selecting items for merging, deselecting a selected item would cause the Merge Works button to disappear, even if multiple other items were still selected.
This was a simple logic error. The SelectionManager action was only being calculated on select, not on deselect. I shifted the relevant block of code out of the `if (selected)` clause it was in and everything works correctly.
Select and deselect some items and note that the action button and its corresponding link update appropriately.
@cdrini @mheiman
=> Fixed SelectionManager deselection bug

scripts/deployment/are_servers_in_sync.sh, scripts/deployment/deploy.sh
trivial fixes to unbreak our deploys (since git now requires sudo in the deployment context)
=> fixing deploy git cmds

docker/README.md
Rearranges Docker README such that the "Prerequisites and Troubleshooting" section is displayed first.  Updated README can be seen [here](https://github.com/jimchamp/openlibrary/tree/reorder-docker-readme/docker#welcome-to-the-docker-installation-guide-for-open-library-developers).
=> Update Docker README

static/css/components/modal-links.less, static/css/less/colors.less
Fixes CSS linter errors found on the `social-share-integration` branch.  This should be merged before #6584.
=> Fix linting errors on integration branch

openlibrary/plugins/openlibrary/code.py, openlibrary/templates/type/edition/opds.html
Previously e.g. https://openlibrary.org/books/OL32050722M.opds was rendering as a python `b''` string
Closes #
=> fix opds rendering

openlibrary/macros/Paginate.html, openlibrary/macros/RecentChanges.html, openlibrary/macros/RecentChangesAdmin.html, openlibrary/macros/RecentChangesUsers.html, openlibrary/macros/WorkInfo.html, openlibrary/templates/admin/people/edits.html, openlibrary/templates/history.html, openlibrary/templates/lib/nav_foot.html, openlibrary/templates/notfound.html, openlibrary/templates/recentchanges/render.html, openlibrary/templates/work_search.html
You are allowed to html encode `&` in urls to `&amp;` when writing out the `href`.
- https://testing.openlibrary.org/%22%3E%3Cscript%3Ealert(document.cookie)%3C/script%3E doesn't xss
- pagination works in search
- facets work in search
=> Avoid XSS when writing a hrefs

openlibrary/solr/update_work.py, openlibrary/tests/solr/test_update_work.py
Work towards #6564 and #6379 . Having the ia metadata be implicit was making it difficult to generalize for different trusted book providers (See WIP pr #6559)
- I added a few too many type hints, and it awoke the sleeping mypy :P So last commit is just things to appease mypy
- Trusting unit tests on this one
- Did a reindex of local data, and results were the same
=> Refactor get_ebook_info to explicitly take IA metadata

openlibrary/plugins/upstream/addbook.py, openlibrary/templates/books/edit.html
Closes #
Prevents record deletion on book page "Enter" key press.  This was largely handled by #6472, but not for some iOS devices running Firefox.  Marking this PR as a draft until this is tested on the platforms in question.
If the POST is a delete, the `process_new_fields` method is not called.  This method processes `select-*` inputs found in [addfield.html](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/books/edit/addfield.html).  This inputs are irrelevant for delete requests.
=> Place "Delete" button on book edit page in it's own form

docker/README.md
No issues exists around this issue as far as I can tell, it may relate to the work done in https://github.com/internetarchive/openlibrary/pull/5455 so reasonably it could be added to that PR. 
This is a slight addition to the documentation when downloading and initializing git submodules if they are not setup when first pulled there are some commands which can be ran to help the user install them. 
specifically `git submodule init && git submodule update`
No technical changes, just some documentation updates for getting started. 
Clone the repository using HTTP, run  `git submodule init` and then `git submodule update` from the root of the repository
The following should appear: 
```
Cloning into '/Users/$user/git/external/openlibrary/vendor/infogami'...
Cloning into …
```
=> Add submodule initialization commands to docs

scripts/import_pressbooks.py
- Ran on ol-home0 ; some records failed to import due to no author data, but that's ok
- Here are the records imported: http://openlibrary.org/query.json?type=/type/edition&providers.provider=pressbooks&providers&limit=1000
- as works: https://testing.openlibrary.org/search?q=publisher%3APressbooks&mode=everything
=> Add script for importing pressbooks

openlibrary/plugins/openlibrary/home.py, openlibrary/plugins/openlibrary/tests/test_home.py, openlibrary/templates/home/index.html
Getting complaints about some odd books showing up in here. Let's limit to something else, and monitor the Google Analytics to see if it does better or worse. Limiting to dewey decimal section 800s, books published before 1950, but which were also published sometime in the last 20 years.
@seabelis
=> Make Classics carousel show only classic books

openlibrary/macros/ReadingLogDropper.html, openlibrary/plugins/openlibrary/js/lists/ListService.js, openlibrary/plugins/openlibrary/js/lists/index.js, openlibrary/templates/lists/widget.html
Closes #6374
Closes #6540
Subject page list widgets were broken with PR #6338, which POSTs _all_ list changes in `{key: ${seedKey}}` format.  This works perfectly for every type but subjects, which are expected to be strings.
This PR remedies the issues with seed key formatting, ensures that the patron's user key is always available on pages with list widgets (if the patron is logged in), and corrects a separate bug that prevents newly added list items from being removed when using the `[X]` link in dynamically generated "Already list" list items.
1. Visit any subject page while logged in.
2. Create a new list.
3. Ensure that the subject is in the new list.
4. Refresh the subject page.  Ensure that the list widget is present and functional.
5. Remove the subject by clicking the `[X]` …
=> Show list widget on subject pages

openlibrary/core/models.py, openlibrary/plugins/upstream/spamcheck.py, scripts/dev-instance/create-dev-db-pgdump.sh, scripts/dev-instance/dev_db.pg_dump
Closes #6500
Creates `read-only` usergroup.  Edits by members of this group will fail our spam checks (unless the member is also an admin or librarian).
Before deploying this code to testing or production, `/usergroup/read-only` must be created.  I suspect that all spam checks will fail if this isn't done.  ~Labeling this PR as `Needs: Special Deploy` in order to bring attention to this.~
__Edit:__ `/usergroup/read-only` has been created in production.
These instructions assume that you are testing locally.  We will be adding local user `openlibrary` to the new usergroup.
1. Login as user `admin`. Remove user `openlibrary` from usergroup `admin`.
2. Add `/people/openlibrary` to the `/usergroup/read-only` group.
3. While still logged in as `admin`, navigate to a book page, and make a test …
=> Create usergroup that cannot edit

.github/workflows/cron_watcher.yml
Data dumps happen on the 1st day of the month so check on them on the 2nd day of the month.
Partner dumps happen on the 17th day of the month so check on them on the 18th day of the month.
Always check again two days later in case they needed to be re-run.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
Runs [`scripts/cron_watcher.py`](https://github.com/internetarchive/openlibrary/blob/master/scripts/cron_watcher.py)
=> GitHub Action to verify successful completion of our cron jobs

openlibrary/core/lending.py
Closes #6592
Instead of asking IA for just one random edition, ask for 25 and then use [`random.choice()`](https://docs.python.org/3/library/random.html#functions-for-sequences) to make the final selection.
The problem may be caused by query results being cached so only requesting a single edition is too small a population.
`docker compose up`
In a separate macOS terminal tab:
```bash
for i in {1..5}; do
open http://localhost:8080/random
done
```
Before, repeated editions as described in #6592
After, different editions in each browser tab
=> Fix random_edition only returns two works

openlibrary/solr/update_work.py
Apparently these were being injected into solr even if they weren't on the record itself ! Knock these out.
Trusting unit tests that nothing broke crazily here ; assuming the fields will no longer be there now!
=> Rm auto-inserted solr availability subjects ("Accessible book", "Protected DAISY")

openlibrary/i18n/README.md, openlibrary/plugins/openlibrary/js/ol.js, openlibrary/templates/languages/language_list.html, openlibrary/templates/lib/nav_foot.html, openlibrary/templates/site/alert.html
Closes #
Creates template for language lists that are found in the footer and the language drop-down.  Adds information about updating the new template in the i18n `README`, which can be viewed [here](https://github.com/jimchamp/openlibrary/tree/i18n-onboarding/openlibrary/i18n#updating-ui-to-include-new-language).
This PR __does not__ address the fact that we are rendering two language lists with the same ID on the same page.  JS functionality is added to these lists based on their ID (`#locale-options`).  In the future, `locale-options` should probably be changed to a class, and the JS initialization code should be updated accordingly.
=> Simplify new language onboarding

openlibrary/data/dump.py, scripts/oldump.py, scripts/oldump.sh
Add more debug information to the ol-dump process based on the [lessons learned](https://github.com/internetarchive/openlibrary/issues/5402#issuecomment-1143547473) in the 2022-05-31 dumps.
1. ~yymm=$(date +\%Y-\%m)~ --> `yyyymm=${yyyymmdd:0:7}`  # So we get 2022-05 instead of 2022-06
2. Log using the prefix `2022-06-01 15:25:06 [openlibrary.dump]` in bash and Python to simplify grepping the logs.
* **ol-home0%** `docker logs -f openlibrary_cron-jobs_1 2>&1 | grep openlibrary.dump`
3. More consistently log the arguments being passed.
4. Log whether or not Sentry is properly enabled.
5. Log timing of major processing steps to quickly spot which jobs are not functioning correctly.
=> Add more telemetry to the monthly ol_dump process

static/css/legacy-datatables.less
Closes https://github.com/internetarchive/openlibrary/issues/6535
Fix.
Belatedly, I see the .less file I modified says not to add to it, through perhaps a 'modification' is okay in this instance? With a bit more direction I can try to comply with the admonition in static/css/legacy-datatables.less.
This addresses https://github.com/internetarchive/openlibrary/issues/6535 by changing the CSS such that, on mobile, the search input is left-aligned and appears below the edition count selector. On desktop/laptop/tablet (or anything at or above @width-breakpoint-tablet as specified in the existing file) the search bar is still to the right of the edition count selector.
Verify that the search box is below the edition count selector and left aligned and mobile, and on the same level as the …
=> Fix mobile book page has a horizontal scroll

.pre-commit-config.yaml, pyproject.toml
Minimal configuration to ensure that Black does not convert quotes.
Black does not support reading its configuration from `setup.cfg`.
This file can be deleted when we convert to favoring double quotes.
https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file
Closes #
=> pyproject.toml: Configure Black to skip-string-normalization

.pre-commit-config.yaml, openlibrary/core/observations.py, scripts/sync
Ensure that Python files end with one and only one blank line.
=> pre-commit: Enable end-of-file-fixer for Python files only

openlibrary/accounts/model.py, openlibrary/core/db.py, openlibrary/core/models.py, openlibrary/plugins/admin/code.py, openlibrary/plugins/openlibrary/js/admin.js, openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/upstream/mybooks.py, openlibrary/templates/admin/people/view.html, openlibrary/tests/core/test_db.py
Creates the means for an admin to anonymize a patron's account.  This PR can be moved from draft when the following tasks are complete:
The `/admin/people/view.html` template was producing invalid HTML.  The initial commit of this PR solely addresses those issues.
__Important Note:__ If the anonymization process throws an error before it completes we can re-run, but some operations may not be possible during the re-run.  This may result in some lingering records.
_New button in `/admin/people`._
_Flash message that is displayed on success_
@mekarpeles
=> Anonymize patron data

openlibrary/plugins/importapi/code.py
001 fields don't have subfields, just txt content. This fixes a bug where the wrong part of the return value was being tested for `str`.
Fixes this error on importing a partner MARC record with an `001$` barcode id (like Trent https://openlibrary.org/local_ids/trent )
```
<class 'AttributeError'> at /api/import/ia
'str' object has no attribute 'get_subfield_values'
Python	/openlibrary/openlibrary/plugins/importapi/code.py in get_subfield, line 287
Web	POST https://openlibrary.org/api/import/ia
```
Closes #
=> allow local_ids to be imported from MARC 001

openlibrary/catalog/marc/cmdline.py, openlibrary/catalog/marc/show_records.py, openlibrary/catalog/merge/build_db.py, openlibrary/catalog/merge/merge_bot/bot.py, openlibrary/catalog/merge/merge_bot/merge.py, openlibrary/coverstore/server.py, openlibrary/data/db.py, scripts/affiliate-server, scripts/copydocs.py, scripts/coverstore-server, scripts/cron_watcher.py, scripts/fake_loan_server.py, scripts/i18n-messages, scripts/import_standard_ebooks.py, scripts/infobase-server, scripts/ipstats.py, scripts/mail_bad_author_query.py, scripts/manage-imports.py, scripts/migrate_db.py, scripts/oldump.py, scripts/openlibrary-server, scripts/pull-templates.py, scripts/sitemaps/sitemap.py, scripts/store_counts.py, scripts/sync, scripts/update-loans.py, scripts/upstream-adapter, scripts/view_marc.py
Normalize all Python shebang lines to `#! /usr/bin/env python3` because we had some Python 2.5 cruft lying around and because on my Mac at least there is no `/usr/bin/python` and `/usr/bin/python3` points to the older system Python 3.8:
```
% /usr/bin/python --version
zsh: no such file or directory: /usr/bin/python
% python --version
zsh: command not found: python
% /usr/bin/python3 --version
Python 3.8.9
% python3 --version
Python 3.10.4
```
Finding Python shebangs on macOS: `git grep "\#\!" | grep python`
=> Normalize all Python shebang lines to #!/usr/bin/env python

openlibrary/templates/type/list/view_body.html
This was hitting solr and often timing out, and blocking the whole page for ~10s. Investigate better fix later (in #6637 ).
Needed for #6608 , so there are less timeouts when twitter tries to fetch the data.
Lists are faster and no longer show the metadata section.
=> Disable subjects list metadata for performance

openlibrary/data/dump.py, scripts/oldump.py, scripts/oldump.sh, scripts/sitemaps/sitemap.py
Related to #5402
good riddance :rofl: 
closes #5892
closes #6253 
closes #6358
closes #6643
- Remove the `$TMPDIR/sitemaps` dir as part of `cleanup`
- Unify logging in `scripts/sitemaps/sitemap.py` with the other Open Library data dumps jobs
- Fix the `scripts/oldump.sh`  archive step which was failing because of a syntax issue only using `[]` instead of `[[ ]]`
- Fix the unbalanced quote in `scripts/oldump.sh`
- Enable Sentry in `scripts.oldump.__main__` instead of `openlibrary.data.dump.__main__` because the latter is never called in the dumps process.
For readability in the logs of the OpenLibrary data dump, add commas to large numbers:
```
log(f"read_data_file() processed {i} records in {minutes} minutes.")
log(f"read_data_file() processed {i:,} records in {minutes:,} minutes.") …
```
=> Data Dumps: Fix remaining archival and sitemaps bugs

static/css/components/header-bar.less
Closes #5194
Fix the dropdown menu "more" behind the search bar.
=> Fixing Menu dropdown

openlibrary/book_providers.py, openlibrary/plugins/worksearch/code.py, openlibrary/solr/update_work.py
Closes #6379
- Moved EbookAccess and IALiteMetadata to book_providers
- Had some import nightmares, so had to import book provider kind of funny :/ There's a circular import somewhere I can't find!
=>  Add access solr fields to non-IA book providers 

openlibrary/plugins/upstream/models.py, openlibrary/templates/lib/history.html
Closes #
* Matches order of  [Cite book](https://en.wikipedia.org/wiki/Template:Cite_book) template (completes the move from the original [Citation](https://en.wikipedia.org/wiki/Template:Citation#Citing_books) template)
* Strips whitespace from LCCNs (whitespace breaks the loc link)
* Correctly adds ISSNs, if present
* Correctly adds `first_publish_date` if different from `date`
Before:
After:
=> Update Wikipedia Cite book format

.github/workflows/cron_watcher.yml
Fix https://github.com/internetarchive/openlibrary/actions/workflows/cron_watcher.yml
Were `$SLACK_CHANNEL_ABC_TEAM` and `$SLACK_TOKEN` added to [GitHub Action secrets](https://github.com/internetarchive/openlibrary/settings/secrets/actions) as discussed in #6661 ?  I do not have the rights to do this.
https://docs.github.com/en/actions/security-guides/encrypted-secrets
=> Cron_watcher: Remove an unbalanced paren

openlibrary/plugins/upstream/account.py
Fixes failing mypy test triggered by increased type checking in #6567
=> Mypy: use typing.Callable instead of builtin callable

openlibrary/templates/type/author/edit.html
Closes #5436 
Added an interrogation mark that links to the author identifier FAQ page.
=> Link to author identifier docs from author edit page

docker-compose.yml
Fix #6656
Docker: The "HOSTNAME" variable is not set. Defaulting to a blank string on zsh.
Closes #
=> Fix #6656: Docker: The "HOSTNAME" variable is not set on zsh

openlibrary/macros/LoanStatus.html, static/css/components/buttonCta--js.less, static/css/components/buttonCta.less
Closes #6652 
Colors are now standard, the messaging appears under the btn (on books page) and don't appear on carousels (due to when not `secondary_action`)
NB: The cta-btns are **still** different sizes either because:
* the cta-btn--shell border or because of the cta-btn 
* form for waitling list
=> minimal fix for carousel waitlist btn

static/css/components/header-bar.less
Closes #6705
Fix.
This changes the z-index for the hamburger menu on desktops to 2 so that it's positioned above the 'more' menu.
The break point where this error occurs is right around where the display switches from desktop to mobile, or a display of around 767px/768 in width. At 767px the mobile menu appears and the error does not. At 768 the desktop menu appears and the hamburger menu displays under the 'more' menu, as noted in #6705.
Incorrect behavior:
Correct behavior:
For further reference, mobile menu behavior, which is fine:
And a wider display where the error doesn't occur:
@bicolino34 
Attribution Disclaimer: By proposing this pull request, I affirm to have made a best-effort and exercised my discretion to make sure relevant sections of this code which substantially leverage …
=> Fix Profile hamburger doesn't override "More" navigation button on Desktop

.pre-commit-config.yaml, openlibrary/plugins/upstream/code.py, pyproject.toml
One of the last remains tasks of #4776
Closes #5079
Remove [--diff](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#diffs) option which currently prevents black from re-formatting modified Python files.
I only made changes to `.pre-commit-config.yaml`.  Pre-commit CI automatically made the changes to all other files.
Question: If we are going to modify 40 Python files, given https://github.com/internetarchive/openlibrary/issues/2981#issuecomment-693664342 should we modify even more by:
1. Dropping [`--skip-string-normalization`](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#strings) and allowing black to favor double-quoted strings in Python code. **-- OR --**
2. ~Adding …
=> Remove black option --diff

openlibrary/macros/SearchNavigation.html, openlibrary/templates/search/advancedsearch.html, openlibrary/templates/search/authors.html, openlibrary/templates/search/inside.html, openlibrary/templates/search/lists.html, openlibrary/templates/search/sort_options.html, openlibrary/templates/search/subjects.html, openlibrary/templates/work_search.html, static/css/components/work.less, static/css/legacy.less
This meant to be an absolute minimal PR of adding Book Page style navigation tabs to Search Results
Closes #6542 
* Lists & Subjects are intentionally omitted from this 1st step because their experience doesn't feel ready -- patrons can still get to this in the same way (through the Browse menu and the main search).
* Google analytics has been added to see if anyone clicks "Quotes" (i.e. fulltext search, named according to Goodreads); see:
* `hits` has been moved consistently below the search box (and the green has been removed); still requires some normalization of font-weight
* Author results have been standardized using the Books format and author covers/imgs have been added. Bullet styles and anchor tags have been standardized across Author and Books results.
**Books**
**Authors** …
=> Unified Search Navigation

openlibrary/macros/EditionNavBar.html, openlibrary/templates/type/edition/view.html
Fixes #6647
Closes #6647
feature
1. Go to any work or book page and you'll initially see `0 Reviews` in the nav bar.
2. Scroll down to Community Reviews and add a review
3. Refresh the page and you'll see the review count has updated, and "reviews" has been changed to "review" to be grammatically correct.
=> Show count of Reviews on Books Page nav bar

openlibrary/core/edits.py, openlibrary/plugins/upstream/code.py, openlibrary/plugins/upstream/edits.py, openlibrary/templates/merge_queue/comment.html, openlibrary/templates/merge_queue/merge_queue.html, pyproject.toml
This PR addresses review notes from #6665, and also prevents reviewers from unassigning themselves from closed requests via the UI.
The "Claimed" tab has been removed from the merge request table views.  Requests that are claimed are now displayed in the "Open" table.
`openlibrary/core/edits.py` and `openlibrary/plugins/upstream/edits.py` are no longer exempt from code formatting.  Reviewing this PR commit by commit will likely be helpful.
The ability to filter results by assignee __is not__ included in this PR.
=> Librarian queue follow-up

openlibrary/templates/merge_queue/comment.html, static/css/components/merge-request-table.less
Changes merge request (MR) comment component class names to avoid ruining our history table comments' styling. 
1. Ensure that the MR table looks the same as it did before this change.
2. Go to  your profile page and look at the history table.  All cells should be the same color.
@mekarpeles
=> Change class names in merge request comment templates

openlibrary/core/edits.py, openlibrary/plugins/upstream/edits.py, openlibrary/templates/merge_queue/merge_queue.html
- Removes CLAIMED mode
- Standardizes `mode` selection in UI
- Adds filtering for reviewer / assignee
Shouldn't affect the UI but does allow `reviewer=` to be added to the URL
=> Refactors Librarian Merge Queue

openlibrary/core/bookshelves.py, openlibrary/plugins/upstream/account.py, pyproject.toml
Canonical formatting will make future diffs easier to read thus making pull requests easier to review.
`openlibrary/core/bookshelves.py` will be modified in both #6621
`openlibrary/plugins/upstream/account.py` will be modified in both #6621 and #6653
Closes #
=> psf/black: core/bookshelves and upstream/account

openlibrary/core/vendors.py, pyproject.toml
Manual change: Remove two `black --force_exclude` lines from `pyproject.toml`
* `lending.py` was black formatted in #6726 as discussed at https://github.com/internetarchive/openlibrary/pull/6723#pullrequestreview-1034902145
* `vendors.py` that will be modified in #6684
=> psf/black: openlibrary/core/vendors.py

openlibrary/core/bookshelves.py, openlibrary/plugins/upstream/account.py
Closes #6519 
Blocked by #6734 -- Rebase this PR after 6734 lands.
Related to #6645 and #6653 which also use `csv_string()`.
`Export your Reading Log` with attention to adding more fields and without building large lists in memory which makes this process unwieldy for users with large reading lists.
* Repeatedly get blocks of books and yield one book at a time.  (lower memory footprint)
Current output: [OpenLibrary_ReadingLog(65).csv](https://github.com/internetarchive/openlibrary/files/8844522/OpenLibrary_ReadingLog.65.csv) or see Screenshots below.
What code returns the results for:
* http://localhost:8080/works/OL54120W.json
* http://localhost:8080/books/OL2058361M.json
The `/api/books` endpoint does not return enough information...
* …
=> Enhanced Reading Log Exports

openlibrary/macros/LoanStatus.html
Fixes the size of waitlist CTA buttons in carousels and edition tables.
=> Fix waitlist CTA button styling

.github/workflows/cron_watcher.yml
```
actions/setup-python@v4
Warning: Neither 'python-version' nor 'python-version-file' inputs were supplied.
Warning: The `python-version` input is not set.  The version of Python currently in `PATH` will be used.
```
https://github.com/actions/setup-python/releases
Closes #
=> cron_watcher: actions/setup-python@v4 needs python-version

.github/workflows/remove_labels.yml
Removes the following labels from a PR when new code is pushed:
`On testing.openlibrary.org`
`On ol-mek (http://ol-dev1.us.archive.org:1337)`
`On ol-jchamp`
__Edit:__ It may not make sense to remove `On ol-mek (http://ol-dev1.us.archive.org:1337)` with this workflow. @mekarpeles to confirm.
=> Add workflow that removes "On testing" labels

openlibrary/macros/EditionNavBar.html
Closes #6437
Adds Google Analytics to our book page navbar.
=> Add analytics to book page navbar items

openlibrary/book_providers.py, pyproject.toml
Canonical formatting will make future diffs easier to read thus making pull requests easier to review.
[Commits:](https://github.com/internetarchive/openlibrary/pull/6747/commits)
1. Remove one `black --force-exclude` line from `pyproject.toml`.
2. (Done by pre-commit.ci) Use black to format the corresponding file.
=> psf/black: openlibrary/book_providers.py

openlibrary/macros/databarWork.html, openlibrary/templates/lists/widget.html, openlibrary/templates/subjects.html
Closes #6740
Prevents lists from being displayed twice in `/subjects` pages list widget showcases.  Also, cleans up unused code in the list widget.
__Note:__ Assigned to myself as a reminder to deploy to testing on Monday.
On subjects pages, two sets of list previews are displayed in the list widget: the owner's lists and a showcase of up to three lists that the subject appears in.  Both use different functions to populate the preview elements (this could probably be DRYed).  The function that populates the showcase now accepts a boolean that will exclude the patron's lists from the showcase.
The whole of the final commit cleans up code unrelated to this functionality.  If those changes are undesirable for any reason, we can easily revert it.
1. Navigate to a `/subjects` …
=> Avoid duplicate list widget items in showcase on `/subjects` pages

.github/workflows/codegen_api_docs.yml, .github/workflows/cron_watcher.yml, .github/workflows/deploy_storybook.yml, .github/workflows/javascript_tests.yml, .github/workflows/python_tests.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>
=> chore: Set permissions for GitHub Actions

openlibrary/plugins/openlibrary/js/SearchBar.js, openlibrary/plugins/worksearch/code.py, static/opensearch.xml
Facets aren't returned in the response, and make the requests quite slow!
Facets are extra data added to a solr query including various group counts. E.g. for a solr query `harry potter`, with facets enabled we would get how many of those books are ebooks, how many are in each language, mention a certain author, etc. This is what powers the numbers in the side bar on the search page.
However we've never exposed this data in our `/search.json` response, but we are fetching it! This data is expensive to calculate. In the past, a GET arg was added, `_facet=true/false` that defaulted to `true`. The thinking back then was that facets were fetched by default, and we didn't want to make a breaking change. We didn't realize that the fetched facets were never even included in the response! So we …
=> Don't fetch facets in /search.json requests

conf/openlibrary.yml
Changes usergroup that is permitted to use the author merge tool from `/usergroup/librarians` to `/usergroup/librarian-work-merge`.
=> Change usergroup for author merge tool

openlibrary/plugins/admin/code.py, openlibrary/templates/admin/people/view.html
Closes #6762
See this comment:
https://github.com/internetarchive/openlibrary/issues/6762#issuecomment-1189808416
There were 2 problem:
edits of /type/delete were breaking things
infobase was breaking when save_many request with changeset of 1000 items submitted.
This code ignores /type/delete records and then performs save_many of batches of 100 at a time.
This also fixes a 3rd problem which is, before, we were just fetching 1000 items irrespective of whether the patron had made more than 1000 edits! We basically weren't reverting everything, doh!
on testing.openlibrary.org as admin try blocking / reverting `whpnob2345`?
@seabelis @jimchamp
=> fixing revert + block flow

openlibrary/plugins/openlibrary/js/carousel/Carousel.js, openlibrary/templates/books/custom_carousel.html
Closes #6648
fix
I believe the problem exists:
- On [line 15](https://github.com/internetarchive/openlibrary/pull/6722#discussion_r917009198) (bug: the conditional statement should not be satisfied when `book.get('cover_id')` returns the string value, 'undefined')
- ...which is resulting in another bug on [line 18](https://github.com/internetarchive/openlibrary/blob/71a074f49b64e391ed92022668488a6fdec11d5d/openlibrary/templates/books/custom_carousel.html#L18) in **openlibrary/templates/books/custom_carousel.html** (as we are passing an undefined value into our course_url string - which leads to a "dead" link i.e. no image)
From looking in browser developer console (shown below), it seems [`book.get('cover_id')`](https://github.com/internetarchive/openlibrary/blob/71a074f49b64e391ed92022668 …
=> Trending Carousel missing default bookcovers

conf/openlibrary.yml, openlibrary/plugins/upstream/code.py, openlibrary/templates/merge_queue/merge_queue.html, openlibrary/templates/site/body.html, scripts/dev-instance/dev_db.pg_dump
Closes #6765
Changes super librarian usergroup from `librarian-work-merge` to `super-librarians`.
=> Change name of super librarian usergroup

openlibrary/components/MergeUI.vue, openlibrary/components/MergeUI/utils.js, openlibrary/core/edits.py, openlibrary/plugins/upstream/code.py, openlibrary/plugins/upstream/edits.py
Closes #6746 
Closes #6769 
Prevents merge request creation for super librarians until the merge has completed successfully.  When the merge is successful, a request that creates a "Merged" MR is POSTed.
This PR also restores the useful status message on successful merge.
Text color of red and green merge UI buttons has been changed to white.
The `/works/merge` controller (which displays the merge UI) no longer creates a "Pending" merge request if an `mrid` is not in the query parameters.  In these cases, `mrid` will be undefined in `mergeUI.vue`, and work IDs are POSTed to the MR update controller on merge success.
As a super librarian:
1. Select at least two works on a search results page.
2. Click the "Merge Works..." button in the right side of the blue ILE bar.  A new tab with the …
=> Delay merge request creation for super librarians (and small tweaks)

openlibrary/plugins/openlibrary/js/index.js
Javascript code for our async star ratings, modal icon links, and merge table are being served on every page, not just on pages where the JS is needed.  This code updates the conditionals that guard loading these modules. 
`querySelectorAll` and `getElementsByClassName` return empty arrays if no matching elements are found.  Javascript considers empty arrays to be truthy, but the original code assumes that empty arrays are falsey.
This update corrects things by checking the length of the arrays returned by these methods.
1. Navigate to https://openlibrary.org and open your browser's dev tools.
2. View the JS code that was served.  In FF, this is found in the `debug` tab in Sources -> Main Thread -> static/build
3. Note the presence of `merge-request-table`, `modal-links`, and …
=> Prevent serving unneeded JS on many pages

openlibrary/macros/EditionNavBar.html
This is following up on a previous pull request, where @mekarpeles requested this:
> If there are 0 Reviews, I think me may just want to stick with "Reviews" instead of "0 Reviews".
Just noticed on the live site, the solution I implemented originally doesn't do this.
So have made some changes in this PR.
=> Changing '0 Reviews' to just 'Reviews'

openlibrary/plugins/upstream/edits.py
Closes #6780
To make entries displayed in descending order.
=> Changed order of entries

openlibrary/templates/merge_queue/merge_queue.html
adds unstyled date created to merges table
Closes #6783
=> Adds unstyled date created to merges table

openlibrary/core/edits.py, openlibrary/core/schema.sql, openlibrary/plugins/upstream/edits.py, openlibrary/templates/merge_queue/merge_queue.html
Closes #6788
Adds `title` field to `community_edits_queue` table.  Title is set whenever a merge request is created.
Removes `enrich` function from the controller.  This function's main purpose was to derive a title using the OLIDs saved in an MR's `url`.  Additionally, `enrich` flattened the `comments` object before passing the data to the template.  Because of this, `comments` is now accessed differently in the template (`r['comments']` v. r['comments']['comments'].
__Note:__ If an MR has a `NULL` title, the title will appear as "None" in the UI.
=> Add title to merge request DB table

openlibrary/templates/type/edition/view.html
Book pages contain a schema.org [exampleOfWork](https://schema.org/exampleOfWork) `link` that references an Open Library work key.  On orphaned edition pages, the `href` for this link is an empty string.  This doesn't seem particularly helpful, so let's prevent these `link`s from rendering on orphaned edition pages.
=> Check for key before rendering `link` with work key

openlibrary/templates/type/edition/modal_links.html
Closes #6761
Affects orphaned edition book pages.  Checks for `work` before rendering note and review modals.  Share modal link will be rendered regardless.
Compare the following orphaned edition page in testing and production:
https://openlibrary.org/books/OL12580742M/Florence_Nighingale
https://testing.openlibrary.org/books/OL12580742M/Florence_Nighingale
Note the render error on production.
=> Check for work before rendering modals

static/css/components/search-result-item.less, static/css/legacy.less
Closes #5810
Fix #5810 so that long titles do not spill over outside the results box.
Added min-width: 0 property and overflow: auto to results box.
Visit https://openlibrary.org/search?q=language%3Ajpn&mode=everything&sort=new to see example of works with long titles
Copy some to a local instance with the fix and conduct the same search.
@lephemere
=> Prevent long titles from overflowing results box

openlibrary/templates/type/edition/modal_links.html
Removing debug `div` from modal links template.
=> Remove debugging `div` from modal links template

static/css/components/search-result-item.less
Closes #5810
As requested here: https://github.com/internetarchive/openlibrary/pull/6793, this is a minor change to ensure that only the title scrolls when the title is too long, as opposed to the entire work/blurb / author scrolling.
Visit https://openlibrary.org/search?q=language%3Ajpn&mode=everything&sort=new to see example of works with long titles
Copy some to a local instance with the fix and conduct the same search.
@mekarpeles
=> Changed scrolling of long titles to only scroll title

.github/ISSUE_TEMPLATE/feature_request.md
When a contributor opens a new feature request issue, the "Type: Feature Request" label is not automatically added.  This PR aims to correct that.
__Note:__ This is untested, and I'm not sure how _to_ test it.  If any reviewers know how, please let me know.
=> Add "Type: Feature Request" label to such issues

openlibrary/templates/type/edition/view.html
Prevents admin bar an non-indexed OCAIDs from appearing on book pages for members of the `librarians` usergroup.  These features are now enabled for `super-librarians`.
=> Prevent admin bar from rendering for `librarians`

openlibrary/plugins/upstream/edits.py, openlibrary/templates/merge_queue/merge_queue.html
Closes #6807
- allows flexible sorting with ?order=asc or desc -- piggy backs on #6785 
- adds total counts to Open and Closed
- removes "All"
- fixes bug where page? persists when switching modes -- fixes **half** of #6782 (i.e. mode part, not submitter!)
@jimchamp
=> librarian merge queue fixes

openlibrary/solr/update_work.py
Closes #6835 
This field, `ia_collection` only exists in `solr_next`.
- Patch deployed, previously failing indexes are now working.
=> Fix books with ia ids not indexed in solr

openlibrary/templates/lib/header_dropdown.html
Today, our `data-ol-link-track` value for our main navbar items is nested within two sets of double quotes:
This is causing a `"` character to be prepended to the `MainNav` category and appended to each action in Google Analytics:
This PR removes the extra double quote characters.
Once deployed, navigate to any page and inspect a main nav link.  Ensure that the value of `data-ol-link-track` is surrounded by a single set of quotes.
=> Remove extra double quote from MainNav analytic events

openlibrary/components/AuthorIdentifiers.vue
Closes: #5696
Closes: #6423
Removes all spaces from ISNI numbers before POSTed.  ISNI links do not render properly if there are spaces in the identifier.
This only cleans up ISNI identifiers that are submitted via the author edit page.  ISNI identifiers consumed from other sources (if any) will be persisted as-is.
1. Navigate to an author edit page.
2. Select "ISNI" from the identifiers drop-down, and input an ISNI identifier (with spaces) in the text field.
3. Click the "Set" button, then click the "Save" button at the bottom of the page.
4. Ensure that the ISNI is present in the sidebar, and that the link contains no encoded spaces.
=> Removes all spaces from ISNI numbers

openlibrary/core/booknotes.py, openlibrary/core/ratings.py, openlibrary/templates/admin/index.html, openlibrary/views/loanstats.py
Adds weekly, monthly, and total counts for the following:
- Book notes created
- Unique patrons creating notes
- Star ratings created
- Unique patrons star rating books
Reading log stats entry needs to be cleared once this is deployed. This can be done from the admin "Inspect Memcache" view.  Just paste that following key into the textarea and press the delete button:
`stats.readling_log_summary-`
__Note:__ The trailing `-` symbol is required for key deletion.
=> Add book note and star rating info to `/stats`

pyproject.toml
[`pyproject.toml: [tool.pytest.ini_options] asyncio_mode = strict`](https://github.com/pytest-dev/pytest-asyncio#modes)
Removes pytest warning:
```
=============================== warnings summary ===============================
../../../../../opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pytest_asyncio/plugin.py:191
/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pytest_asyncio/plugin.py:191:
DeprecationWarning: The 'asyncio_mode' default value will change to 'strict' in future,
please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.
config.issue_config_time_warning(LEGACY_MODE, stacklevel=2)
```
Closes #
=> pytest: Set asyncio_mode to strict

docker/Dockerfile.olbase
Olbase always upgrades to the latest version of Python's pip so why not do the same with Node.js' npm?  https://www.npmjs.com/package/npm
Closes #
`docker build --no-cache -t openlibrary/olbase:npm_latest -f docker/Dockerfile.olbase .`
```
npm --version  # --> 8.11.0
npm install --location=global npm@latest
npm --version  # --> 8.16.0
```
=> docker/Dockerfile.olbase: Upgrade npm as we do with pip

openlibrary/coverstore/tests/test_coverstore.py, openlibrary/coverstore/utils.py
Refactoring to use urlsplit() rather than splitquery() and to add type hints.
Closes #6851
Refactor
Ideally nothing has changed in terms of the inputs and outputs.
I added some tests and used the output from the previous implementation to get the test conditions.
@cclauss
=> Fix for #6851: refactor urldecode() from coverstore/utls.py to use urlsplit() and not the depreciated splitquery()

openlibrary/templates/account/books.html, openlibrary/templates/account/sidebar.html
While looking at the "My Books" sidebar template, I noticed that render times were captured for the sidebar but not displayed in the debug message.
This PR adds the sidebar render times to `component_times`
`component_times` are now passed to the sidebar template.
1. Add `?debug=true` to any "My Books" page URL, and load the page.
2. Scroll to the bottom of the page.  Ensure that the sidebar render times are present in the profile component.
=> Add profiling to "My Books" sidebar

openlibrary/templates/account/sidebar.html
Closes #6802
Adds analytics to all "My Books" page sidebar links.
Event Category for all new analytics events is __MyBooksSidebar__
Events actions and their associated links are as follows:
| Action | Sidebar Link |
| --- | --- |
| Profile | "Profile Page" |
| Settings | "Settings & Privacy" |
| Loans | "Loans" |
| LoanHistory | "Loan History" |
| CurrentlyReading | "Currently Reading" |
| WantToRead | "Want to Read" |
| MyNotes | "Already Read" |
| MyReviews | "My Reviews" |
| ReadingStats | "Reading Stats" |
| ImportExport | "Import & Export Options" |
| Sponsorships | "Sponsoring" |
| AllLists | "See all" lists |
| PatronList | All list details |
=> Add analytics to "My Books" sidebar links

openlibrary/accounts/model.py, openlibrary/core/edits.py, openlibrary/plugins/admin/code.py, openlibrary/tests/core/test_db.py
Adds the `community_edits_queue` table entries to the patron anonymization flow.  __Only submitters are anonymized__, not reviewers.
While logged in as an `admin` on your local instance:
1. Ensure that there are entries in the `community_edits_queue` table.  Choose a `submitter` to anonymize from one of the rows.  Note the number of entries that the `submitter` submitted.
2. Navigate to the `/merges` view that contains the `submitter`'s name.
3. Navigate to `/admin/people/${submitter}`. In the admin history table, tick the "Dry Run" checkbox and press the "Anonymize Account" button. Ensure that the updated row count is correct for `community_edits_queue`.
4. Uncheck the "Dry Run" checkbox, if ticked.  Press the "Anonymize Account" button again. Note the new username.
5. Navigate back to …
=> Add merge request submitters to patron anonymization process

bundlesize.config.json, openlibrary/macros/ReadingLogDropper.html, openlibrary/macros/databarWork.html, openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/js/lists/ListService.js, openlibrary/plugins/openlibrary/js/lists/index.js, openlibrary/plugins/openlibrary/lists.py, openlibrary/templates/lists/active_lists.html, openlibrary/templates/lists/dropper_lists.html, openlibrary/templates/lists/list_overview.html, openlibrary/templates/lists/widget.html, static/css/components/listLists.less
Closes #6775
Asynchronously loads reading log dropper lists.
A number of functions have been moved from `lists/widget.html` to `lists.py`, and made `public`.  Similarly, some HTML rendering functions have been moved to dedicated template files.
For now, the list partials endpoint only returns HTML for a single list widget.  The endpoint can be easily modified to return a collection of partials in a single call, but the object returned will be unwieldy while list management is handled by two components (one for adding to a list, and one for removing from a list).
=> Adds async list loading to reading log droppers

openlibrary/core/models.py
Previously, a limit was required when running resolve redirects.
But what we like usually want is to run on a date range, not a number of entries.
This PR reworks the bulk resolve redirects #6752 #6667 #6511 to prepare us for a monthly cron.
=> simpify resolve redirects, don't require max_limit

openlibrary/plugins/upstream/utils.py
[`openlibrary.plugins.upstream.utils.radio_list()`](https://github.com/internetarchive/openlibrary/blob/b897c8c51a79308e38f9825fac82864a5cc7d3ae/openlibrary/plugins/upstream/utils.py#L311) builds a list but returns no value to its caller and [is never called](https://github.com/internetarchive/openlibrary/search?q=radio_list).
Closes #
=> Dead code: openlibrary.plugins.upstream.utils.radio_list()

openlibrary/accounts/model.py, openlibrary/catalog/marc/marc_binary.py, openlibrary/plugins/books/code.py, openlibrary/plugins/importapi/code.py, openlibrary/solr/db_load_authors.py, openlibrary/solr/db_load_works.py
https://pypi.org/project/flake8-simplify
`SIM201 Use 'len(m.groups()) != 2' instead of 'not len(m.groups()) == 2'`
=> Convert not a == b --> a != b

static/css/legacy.less
The results of an author search are visually ragged, because the space allocated for the author image becomes flexible if no image is preset. The effect is unpleasant:
This is a tiny fix — changing the css on the image slot from width to max-width allows results with no image to use the entire space.
The result of the fix:
@mheiman
=> Fix visual alignment of author search results

openlibrary/plugins/openlibrary/code.py, openlibrary/templates/site/body.html, static/css/components/page-banner.less
Works towards #6714
Closes #6716
This PR adds a banner to OpenLibrary.org and encourage folks to take a quick survey.
The code adds a random choice function to our templates so that we can evenly spread out the different survey links to patrons.
=> Adding Main Banner to Mobile Book Page Surveys (Mazes)

openlibrary/core/lending.py, openlibrary/plugins/upstream/borrow.py
https://sentry.archive.org/organizations/ia-ux/issues/46145/?project=7&query=is%3Aunresolved
If s3_loan fails, raise exception, don't account for loan in graphite
=> p0-lending-sentry-error-handling

openlibrary/templates/lists/widget.html
Closes #6884
Checks for `User` before calling `User` class methods.
=> Fetch `User`'s lists only if `User` exists

openlibrary/macros/databarWork.html, openlibrary/templates/books/edition-sort.html
Closes #6830
Fix
I am not sure it is the best approach, but a simple fix for the left-hand menu would be changing
`$:macros.WorldcatLink(isbn=isbn_13, oclc_numbers=oclc_numbers, referer=page.url(relative=False))` to `$:macros.WorldcatLink(isbn=isbn_13 or isbn_10, oclc_numbers=oclc_numbers, referer=page.url(relative=False))`.
If I understand correctly, the WorldCat link in the left-hand menu is rendered by `openlibrary/macros/databarWork.html`, and only displays if `page.get_isbn13()` returns something. This is so in part because of the following, from line 98, `$:macros.WorldcatLink(isbn=isbn_13, oclc_numbers=oclc_numbers, referer=page.url(relative=False))`.
I think `databarWork.html` is using only ISBN 13 because the page presupposes if there is an ISBN 10, then it will be converted to …
=> Fix for 6830. Generate a WorldCat link even if the only ISBN is an invalid ISBN 10

openlibrary/components/MergeUI/utils.js, openlibrary/core/edits.py, openlibrary/core/schema.sql, openlibrary/plugins/openlibrary/js/dialog.js, openlibrary/plugins/openlibrary/js/ile/utils/SelectionManager/SelectionManager.js, openlibrary/plugins/openlibrary/js/merge-request-table/MergeRequestService.js, openlibrary/plugins/openlibrary/js/merge-request-table/index.js, openlibrary/plugins/openlibrary/js/merge.js, openlibrary/plugins/upstream/code.py, openlibrary/plugins/upstream/edits.py, openlibrary/plugins/upstream/merge_authors.py, openlibrary/templates/merge/authors.html, openlibrary/templates/merge_queue/merge_queue.html, openlibrary/templates/type/author/view.html, static/css/components/merge-form.less
Closes #6812
Allows author merge requests to be added to the librarian request queue.  Author merge requests are added similarly to work merge requests: `librarians` can submit a request via an author search results page via the ILE blue bar, and `super-librarians` can accept or decline the request from the author merge UI.  Author merges by `super-librarians` trigger the creation of an approved merge request.
This PR alters the `community_edits_queue` table, adding a new column 'type` which is used to differentiate work and author merge requests.  __Before this is deployed to any environment, the following queries should be executed:__
```
ALTER TABLE community_edits_queue ADD type int;
UPDATE community_edits_queue set type = 1; /* designates all existing requests as work merges */
``` …
=> Author merge requests

openlibrary/utils/lcc.py, openlibrary/utils/processors.py, scripts/copydocs.py, scripts/import_standard_ebooks.py, scripts/ipstats.py
Partially closes #6755 
Refactor to include more type hints.
`fetch()` from `scripts/test_copydocs.py` is a bit of a question mark. There is a comment that explains it, but the code in production requires `src` to be of type `OpenLibrary`, but pytest uses `FakeServer`. I saw `assert` was used in there to deal with specifically with thte issue of the type for `src`, though admittedly this is rather like using `assert` for flow control.
I also struggled a bit with the best way to narrow the type of `cache`, as the function expects it not to be None, but the type is controlled by a parent function.
@cclauss
=> Partial fix for #6755. Create more python type hints: 48-52.

openlibrary/templates/books/edition-sort.html
These images are below the fold, so we don't need them to be fetched as soon as the page is visible.
=> Make edition table covers loading=lazy

.github/workflows/python_tests.yml
This should save on build time
Closes #
@mekarpeles writes: This doesn't remove any packages from being installed in prod or on dev environments, it just changes what libraries are necessary for running our tests in github actions
=> GitHub Actions: lxml only need on dev releases of Python

static/css/components/mybooks-menu.less
Closes #6768 
Fix.
Clearfix was applied to .section-header.section-header-split, and the left padding was reduced by two pixels to accommodate the German translation of "LISTS" and "SEE ALL (x)".
I had a lot of trouble reproducing it, but I was able to do it in Windows 8.1 (64bit) using current versions of Chrome and Edge. 
In more detail:                                                                                          
- I couldn't reproduce in IE 11.0.14 or Firefox 102.0.1 (64-bit)                                                         
- I could reproduce in Chrome 104.0.5112.102 (64-bit) and (unsurprisingly) Edge 104.0.1293.63 (64-bit)                   
- Screen resolution: I tested a number of resolutions from 1024x768 on up, and could only reproduce when the browser wasn't …
=> Fix reading log is rendered incorrectly in Ukranian and German (#6768)

static/css/components/mybooks-menu.less
This is interim fix number 1 for mobile My Books menu (issue #6858), done initially because it took only a few minutes and helped me get familiar with the development environment. 
Made the menu shorter, resizable, and gave it a slightly darker background. 
This is only the quickest interim fix and I will quickly iterate on this version to do away with the confusing menu entirely
Changed css for mybooks-menu on mobile screens to make it resizable, height: 21vh (previously 42) and slightly darker grey background
Go to 'My Books' page, inspect element, and toggle to mobile device in staging and compare to live site to see the changes. Select mybooks-menu and check out its mobile css to see the changes
@mekarpeles @jimchamp @cdrini
=> My Books page interim Mobile Navigation Fixes #6858

static/css/legacy.less
The contrast ratio for the modified text is not upto the mark. Changing the color of the link to darker-grey improved the readability. Check the image -
=> Changing the diff color to darker-grey for better read - Closes #6855

openlibrary/templates/site/body.html
Removes maze banner (feedback period over)
=> rm book page maze banner

openlibrary/data/dump.py, scripts/oldump.sh
In `scripts/oldump.sh` we tend to use the `log` command which writes to `stderr` and the Docker error logs instead of the `echo` command which writes to `stdout`.  This is done to keep `stdout` clear because this script often pipes data from one command to the next.
The change to the `make_index()` function of `openlibrary/data/dump.py` may not be important because I am unable to find anywhere that this function is called but still it is better to fix this logic error.
=> oldump.sh: Use log, not echo

scripts/oldump.py
Sentry requires infobase config to load which invokes logging that is polluting our monthly data dumps during the cdump stage, printing startup messages like the following to stdout (instead of using stderr logging) and thus polluting (i.e. getting added into the output of this script which then goes into) our cdumps
```
2022-08-25 16:10:09 [11337] [infobase.ol] [INFO] logging initialized                                                                                           
2022-08-25 16:10:09 [11337] [openlibrary.olbase] [INFO] setting up infobase events for Open Library
```
Closes #5402 #6319 #6825
=> unbreak data dumps (prevent log pollution)

openlibrary/plugins/upstream/mybooks.py
Closes #6891
This PR adds a missing param named sort_order in mybooks.py which is being passed to reading_log.html.
1. Log in
2. Add a few books to your "Want to read" list
3. Go to "My Reading Log" page from the user menu
4. Click on the filters given to sort the list
Added the screenshots. Active selection turn green as expected
@bicolino34
=> Passing the missing param - sort_order in mybooks

openlibrary/components/MergeUI/MergeRowReferencesField.vue, openlibrary/components/MergeUI/MergeTable.vue
Late changes to the MergeUI updates PR broke handling of orphaned edition records sent to the MergeUI. This fixes that and allows the MergeUI to fix orphans correctly.
This PR does two things: 
- Only requests and displays lists/reading logs/ratings for valid work records, so the merge isn't blocked by missing data errors
- Correctly returns the filtered list of duplicate works from MergeTable.merge so that edition records aren't changed into redirects when the merge is done
Try a merge like this with some works and an edition:
https://testing.openlibrary.org/works/merge?records=OL99529W,OL27145882W,OL38495188M
(That's not a real orphaned edition, but it's a junk record. You can move the edition back to its work (OL28124291W) when you're done if you like.)
@mheiman @cdrini
=> Fix handling for edition records in merge requests

.gitpod.yml
https://gitpod.io/#https://github.com/internetarchive/openlibrary/ always errors :/ Disable the prebuild.
Won't be able to test until merged.
@cclauss @RayBB
=> Disable gitpod master branch prebuilds

.github/workflows/cron_watcher.yml
https://github.com/cclauss/openlibrary/actions
```
Run scripts/cron_watcher.py
files_with_both_prefixes_found = True
```
Slack notification was not sent.
=> cron_watcher: Send Slack message on failure only

openlibrary/core/edits.py, openlibrary/plugins/openlibrary/js/merge-request-table/index.js, openlibrary/templates/merge_queue/merge_queue.html
This PR does the following:
1. Modifies badge count such that only unassigned pending requests are counted.
2. Adds an assignment date to the merge request table.
3. Allows others with merge capabilities to unassign a person from a merge request.
_Unassigning `openlibrary` as User `admin`_
=> Merge request unassignment

openlibrary/core/vendors.py, openlibrary/utils/ddc.py, openlibrary/utils/isbn.py
Partially closes #6755 
Refactor
This batch entered the Solar system and required some use of `is not None` and `isinstance(x, y)` such that output could be changed. I... hope it has not changed.
I can see how reasonable people might disagree about whether or not some of the `:param:` comments add anything. I was trying to imagine myself in the situation of someone unfamiliar with the code base, as I am, and whether the `:param:` comments added something useful beyond the type hints and parameter names. I have no idea how much I can generalize from my own experience, if that’s even the right approach, though.
Some additional things to note:
- in `openlibrary/tests/solr/test_update_work.py`: the use of `Any` in the various functions to make make authors, editions, etc.
- in …
=> Partial fix for #6755. Batch three of type hints from type comments.

openlibrary/plugins/upstream/edits.py
Closes #6927
Entries in the merge request table are now sorted by last updated date, descending.
=> Sort merge requests by last updated

scripts/solr_restarter/index.js
Makes it less noisy, and avoids it restarting too aggressively.
=> Make solr restarter wait longer before restarting solr

scripts/affiliate-server
The current string is not useful for reporting from statsd.
For current statsd names used in the codebase, see: `git grep increment`
Closes #
=> Improve statsd name ol.affiliate.amazon.queue_size

openlibrary/plugins/openlibrary/js/ile/utils/SelectionManager/SelectionManager.js
Enables work selection on author pages using ILE tools.
Reinstates original regex used for assigning the Work selection provider, with one change: matches must occur at the end of the string.  Without this change, the original Work regex would match author search pages (`/search/authors`).
While logged in as either a `librarian` or `super-librarian`, do the following:
1. Go to an author page and ensure that the ILE blue bar appears.
2. Select some works and ensure that the ILE status message references "works," and that the merge button appears.
3. Go to a work search page and ensure that the ILE blue bar appears.
4. Repeat step 2.
5. Go to an author search page and ensure that the ILE blue bar appears.
6. Select some authors and ensure that the ILE status message references "authors," …
=> Enable work selection on author pages

openlibrary/plugins/admin/code.py, openlibrary/plugins/upstream/addbook.py, openlibrary/plugins/upstream/code.py, openlibrary/plugins/upstream/tests/test_addbook.py, openlibrary/templates/books/add.html, openlibrary/templates/books/edit.html, openlibrary/templates/books/edit/edition.html, openlibrary/templates/showmarc.html, openlibrary/templates/viewpage.html
Closes #6940
Restricts a number of features previously available to members of usergroup `librarians` to `super-librarians`.
Once merged, `librarians` will no longer have access to the following:
- Viewing `/admin` pages
- Deleting records via edit form
- Modification of OCAIDS (including deletion)
- Reverting records to a previous version
- The "Next" button on MARC record pages
- Including an Internet Archive ID when adding a book
- Moving editions to another work
The following functionality remains unchanged by this PR:
- Recaptcha exemption when adding books
- Access to merge UIs and ILE blue bar
- Bypassing `is_spam()` spam checks
- OCAID and ISBNs rendered in book details page omnibar
=> Restrict some features to lead librarians

openlibrary/macros/DonateModal.html, openlibrary/macros/LoanStatus.html, openlibrary/macros/NotInLibrary.html, openlibrary/macros/databarWork.html
Closes #
Makes the following changes to our donate button logic:
1. Renders a "Not in Library" button if we enter the "Donate" button block of code and find that the book is not eligible.
2. Renders a new, uniquely identified donation modal content element with every "Donate" button, allowing multiple "Donate" buttons per page.
3. Checks if the record is an `Edition` before attempting to render a donate button (edition-level data is required for the donate modal macro)
A count of donate buttons is stored in the web context object.  This count is used to uniquely identify individual "Donate" buttons on a single page.  There is a risk that this approach may not work with asynchronously fetched partials (like carousel items).
`Edition`-level methods `get_isbn10` and `get_isbn13` are required …
=> Donate Button Changes

conf/openlibrary.yml, openlibrary/components/MergeUI.vue, openlibrary/components/MergeUI/MergeTable.vue, openlibrary/components/MergeUI/utils.js, openlibrary/plugins/openlibrary/js/dialog.js, openlibrary/plugins/openlibrary/js/ile/utils/SelectionManager/SelectionManager.js, openlibrary/plugins/openlibrary/js/merge-request-table/MergeRequestService.js, openlibrary/plugins/openlibrary/js/merge.js, openlibrary/plugins/upstream/code.py, openlibrary/plugins/upstream/edits.py, openlibrary/plugins/upstream/merge_authors.py, openlibrary/templates/merge/authors.html, openlibrary/templates/merge/works.html
Closes #6883
Permits members of `/usergroup/librarians` to access author and work merge views.  `librarians` now submit merge requests (MRs) from these UIs, instead of search results pages.
The primary work ID can now be included for work MRs.  If a work merge URL has a `primary` ID, that record will appear first in the list of all records.
The `openlibrary.yml` configuration files must be updated in production, testing, and staging before this is deployed.
=> Open merge UIs to `librarians`

openlibrary/plugins/openlibrary/js/ile/utils/SelectionManager/SelectionManager.less
Closes #6942
Hotfix
The `.app-drawer` is the child element of `#header-bar`, which has a `z-index` of `2`, while the `#ile-toolbar` has a `z-index` of `99999`. This causes the `#ile-toolbar` to obstruct the `.app-drawer`.
- This can be fixed through css by 
- increasing the `z-index` of `#header-bar`
- decreasing the `z-index` of `#ile-toolbar`
- adding a bottom padding to the `.app-drawer`
Increasing the `z-index` of header bar would affect other components, like obstructing the language drop down component. Adding a bottom padding to the app drawer would not look good when there is no ile toolbar.
Hence, I decided to decrease the `z-index` of the ile toolbar.
When logged in as a `librarian`, `super-librarian`, or `admin`:
- Go to a search results page.
- Display the drawer by clicking …
=> fix ile bar obstructing drawer

openlibrary/book_providers.py, openlibrary/macros/SearchResultsWork.html, openlibrary/plugins/upstream/models.py, openlibrary/plugins/upstream/utils.py, openlibrary/plugins/worksearch/code.py, openlibrary/plugins/worksearch/tests/test_worksearch.py, openlibrary/solr/query_utils.py, openlibrary/templates/type/edition/view.html, openlibrary/templates/work_search.html, openlibrary/tests/solr/test_query_utils.py, requirements.txt, static/css/components/search-result-item.less
Most of #6377 . Closes #5991
- **NEW**: Switched to _off_ by default while I work out perf issues. But should be good to merge!
- Updates search results to display a matching edition cover/title/ebook_access as opposed to work's
- No longer performs `has_fulltext` filter after-the-fact; this is all done by solr
- Installs a new library, `luqum` (for lucene query manipulator). We have to do a lot of manipulation to convert a user query to a query that can be run against editions. Doing regex replaces and string manipulation was making this impossible.
- Note we kind of had a home grown "parser" written earlier using some clever regexes, but it wasn't flexible enough to do the sort of manipulations I needed.
- Added a Super librarian/admin-only cookie-backed toggle to switch between new …
=> Editions in Solr -- Search Results UI/API Integration piece

openlibrary/plugins/upstream/addbook.py, openlibrary/plugins/upstream/merge_authors.py, openlibrary/plugins/upstream/models.py, openlibrary/plugins/upstream/utils.py
Partial fix for #6755 
Refactor
Added more type hints from type annotations.
Although there is an `assert` at line 573 in `addbook.py`, this should not change runtime behavior because Mypy doesn't understand that `self.edition` won't be `None` in that branch of code, as if `edition_data` is not `None`, then `self.edition` is not `None`.
@cclauss
=> Partial fix for #6755. Batch four of type hints from type annotations.

.pre-commit-config.yaml
Closes #
`pre-commit autoupdate` --> https://github.com/asottile/pyupgrade/compare/v2.38.0...v2.38.2
=> pre-commit autoupdate: pyupgrade v2.38.2

scripts/partner_batch_imports.py
**SQUASH ME**
I've added a bunch of new words to the block list for automatic imports
Note these will probably catch a few valid books, but there's sooooo many bad imports right now; and we can always manually import something that gets incorrectly excluded
Here are the corresponding searches
- [classics](https://testing.openlibrary.org/search?q=title%3Aclassics+publisher%3A%22independently+published%22&mode=everything&editions=true)
- [summary](https://testing.openlibrary.org/search?q=title%3Asummary+publisher%3A%22independently+published%22&mode=everything&editions=true)
- [calendar](https://testing.openlibrary.org/search?q=title%3Acalendar+publisher%3A%22independently+published%22&mode=everything&editions=true)
- [journal](https://testing.openlibrary.org/search?q=title%3Ajournal+publish …
=> Block more words from auto-imports

openlibrary/templates/merge/authors.html
Today, the author merge UI's submit button reads "Merge Author" regardless of the librarian's permissions.  This PR updates the button's copy to "Request Merge" for members of the `librarians` usergroup.
_New copy for librarians._
=> Use correct call to action for author merge UI button

openlibrary/plugins/admin/code.py
Gives members of the `librarians` usergroup access to Open Library's Solr reindexer.
1. Log in with an account that has `librarians` permissions, but does not have `admin` permissions.
2. Ensure that you can access the `/admin/solr` page.
3. Expect a permission denied error to appear if you navigate to any other `/admin/*` page.
4. Ensure that `admin` accounts can still access the `/admin/solr` page.
5. Expect a permission denied error if an unauthenticated patron accesses `/admin/solr`
=> Grant `/admin/solr` access to `librarians`

openlibrary/plugins/upstream/forms.py
Updates the copy for the username field in our registration form.
__Old Copy__: Choose a screen name
__New Copy__: Choose a screen name. Screen names are public and cannot be changed later.
@seabelis @mekarpeles
=> Update copy for registration form

openlibrary/templates/search/authors.html, openlibrary/templates/search/subjects.html
Closes #6728 
This changes the "Subjects" search button to match the "Books" search buttons
Search > Subjects tab
to
=> Subjects searchbttn

openlibrary/templates/search/authors.html, openlibrary/templates/search/inside.html
Closes #6728 
The "Search Inside" search button now is formatted the same as the "Books" Search button.
Search > Search Inside tab
to
=> Inside searchbttn

bundlesize.config.json, openlibrary/plugins/openlibrary/js/admin.js, openlibrary/plugins/openlibrary/js/index.js, openlibrary/templates/admin/people/view.html
This PR makes two improvements to the `/admin/people/{username}` page:
1. Adds merge requests to the patron anonymization confirm dialog.  This was overlooked when #6834 was created.
2. Adds a confirmation dialog to the "block patron" buttons.
The `initConfimationButtons()` function seems like it could be used on many other pages.  We can further generalize this function by passing the confirmation message as a parameter, and move this function into another, more appropriate, file.
__Warning:__ Testing involves clicking the "block and revert all edits" button.  Recommend testing this on a local instance, or with a test account that has no meaningful edits.
1. While logged in as an `admin`, navigate to a patron's admin page.
2. Click the "Anonymize Account" button.  Confirm that merge …
=> Small `/admin/people` improvements

openlibrary/components/MergeUI.vue, openlibrary/plugins/upstream/merge_authors.py
When `librarians` submit merge requests today, it's somewhat unclear that they have submitted a request.  This PR redirects to the new merge table entry on successful submission.
While logged in as a `librarian` (but not an `admin` nor `super-librarian`):
1. Submit an author merge request.  Ensure that you are redirected to the merge request table.
2. Submit a work merge request.  Ensure that you are redirected to the merge request table.
=> Redirect to merge request table on merge request submission

openlibrary/plugins/openlibrary/js/edit.js, tests/unit/js/editionsEditPage.test.js
Closes #
I thought there was a problem with ISBN hyphenation is some cases, but it was just a problem with me not re-building assets in docker.
By the time I realised, I'd already made these refactoring changes. :)
* Uses checksum validation directly, rather than calculating a check digit and comparing the last digit.
* Uses a trick of converting X -> A and parsing as base-16 to handle X = 10 for ISBN 10
Not sure if the the comments  "Adapted from https://www.oreilly.com/library/view/regular-expressions-cookbook/9781449327453/ch04s13.html" still apply;, the nice map reduce seems to be from @scottbarnes , and I have pretty much changed the rest.
* The tests/unit/js/editionsEditPage.test.js ISBN tests pass or fail based on whether the checkdigit code is correct.
@scottbarnes
=> Refactor ISBN checksum validation

openlibrary/templates/merge_queue/merge_queue.html, static/css/components/merge-request-table.less
Adds ability to filter merge requests that were reviewed by oneself.  This option will only be available to `super-librarians`.
This PR also corrects bug where clicking "Show all requests" does not remove `page` from the URL search params.
=> Filter merge requests by reviewer

openlibrary/templates/account/sidebar.html
Closes #7020 
Remove profile and settings links from My Books nav, because they were redundant
Three lines deleted
go to My Books page and review the top few links of the menu
@mekarpeles
=> removing profile and settings links from My Books nav because they are in the sitewide nav also

openlibrary/templates/lib/header_dropdown.html, openlibrary/templates/lib/nav_head.html
Creates distinction between main navigation links and hamburger links for our Google Analytics.
Main navigation link event name: "MainNav" 
Hamburger link event name: "Hamburger"
Event name is now passed as keyword argument `tracker_prefix` to `header_dropdown.html`.  The tracker property is created and rendered if both `tracker_prefix` and `link.track` exist.
@mekarpeles
=> Create distinction between main nav links and hamburger links for analytics

openlibrary/plugins/openlibrary/js/ile/utils/SelectionManager/SelectionManager.js
Closes #6696
Hotfix
In the click handler that adds the selection fires, it will do nothing if there is a text selection.
When logged in as a `librarian`, `super-librarian`, or `admin`:
- Go to an author's page (e.g. http://localhost:8080/authors/OL18319A/Mark_Twain)
- Try to copy the text (title, author, date) of a book
- Result: Text is selected but the book is not selected (not highlighted in blue)
@seabelis @cdrini
=> fix text selection for selectable items

openlibrary/core/sponsorships.py
**SQUASH ME**
Unclear why, but this IA request is sometimes taking 50s. Elevated to appropriate people on IA side, but on our side we should have a timeout here.
- Added a custom exception log so we can see timeout in sentry separate from other errors.
=> Add timeout to DWWI request to fix sometimes being 50s

conf/solr/conf/solrconfig.xml, docker-compose.override.yml, docker-compose.production.yml, docker-compose.yml
Work towards #7017
- Switch to soft commits instead auto of explicit hard commits
- Commits are what make user edits visible to search
- Soft commits make user edits visible to search but do not persist them to disk. The cost of this, is that they stick around in Solr's updateLog until a hard commit is performed.
- Also soft commits will invalidate active searchers, meaning new searchers need to be warmed
- But hard commits, which persist updates to disk, are slow
- We now auto soft commit every minute, and hard commit every 2 minutes
- Previous we would hard commit by sending explicit commit in solr-updater every minute
- In a future PR, I will remove some of the code around explicit commits sent by solr-updater, if everything looks good
- In a future PR, we should also remove …
=> Improvements to solr performance

scripts/affiliate-server
Related to #4465
Currently, the statsd reporting for the affiliate server reports the queue size of one dump in 20.  This change causes it to report the maximum queue size across the last 20 dumps.  We do not report more often but we report more accurately.
These changes also add a `Clear` API endpoint that will clear `web.amazon_queue` and return the current queue size and maximum queue size before it was cleared.
These changes also include black formatting because the filename `scripts/affiliate-server` does not have a `.py` suffix.
---
Affiliate Service (weekend outage fix) + Check [imports](https://openlibrary.org/admin/imports) succeeding (esp. amazon)
=> Improve statsd reporting for affiliate server

openlibrary/core/vendors.py
When looking at the logs of the affiliate service, we noticed two exceptions being thrown:
% `ol-home0% docker logs -f --tail 10 openlibrary_affiliate-server_1`
```
File "/openlibrary/openlibrary/core/vendors.py", line 220, in serialize
edition_info.publication_date.display_value
AttributeError: 'NoneType' object has no attribute 'display_value'
```
```
[ ... ]
File "/openlibrary/openlibrary/core/vendors.py", line 250, in serialize
and [{'name': contrib.name} for contrib in attribution.contributors],
TypeError: 'NoneType' object is not iterable
```
https://github.com/internetarchive/openlibrary/wiki/Deployment-Guide#recovering-from-restart-loops
`docker exec -it openlibrary_affiliate-server_1 bash`
* `vi …
=> Affiliate service: Fix two issues related to None

openlibrary/plugins/upstream/addbook.py, openlibrary/plugins/upstream/tests/test_addbook.py
Closes #6294
Fix
This fixes the "notfound" error that occurs when adding an existing work, but a new edition, via /books/add.
It also fixes a related `KeyError` that would occur when adding a book via /books/add that exactly matched an existing work and edition.
With respect to the "notfound" error, this happened because `make_work()` in `openlibrary/plugins/upstream/addbook.py` was adding `/works/` to every `doc.key` it processed. `make_work()` is used as a wrapper that processes solr results, all of which already have the "/works/" prefix, so every work was getting a key of `/works//works/OL123W`, as seen in #6294. This PR removes that line, and thereby removes the duplication of the "/works" prefix.
Additionally, this fixes the `KeyError` caused when adding a book via /books/add that …
=> Fix for #6294: add a book error with notfound trying to match existing work

openlibrary/plugins/upstream/code.py
Closes #7039
There may be a better way to do this (calling the API directly and using a specific json decoder for the datetime) which doesn't require us fetching the raw text via the API, loading as json, and then dumping json again (which seems like a wasteful performance hit). I imagine it's being called relatively infrequently and so may be OK.
**Another technical note, we may want to simply REDACT the `ip` (leaving the field) in case anything relies on the key being present**
https://testing.openlibrary.org/authors/OL117575A.json?m=history&debug=true
@tfmorris @cdrini @jimchamp @bfalling
=> scrubs IPs from ?m=history json api

openlibrary/core/bookshelves_events.py, openlibrary/core/schema.sql, openlibrary/plugins/upstream/checkins.py, openlibrary/plugins/upstream/code.py, openlibrary/plugins/upstream/tests/test_checkins.py, openlibrary/templates/check_ins/test_form.html, openlibrary/tests/core/test_db.py, openlibrary/utils/decorators.py
Closes #6662
Adds new DB table for tracking check-in events, and creates the persistence layer for the new table.  Creates two check-in event handlers: one for creating events (`/check-ins/{work_olid}`, and one for updating existing events (`/check-ins/{username}`.  Adds a __temporary__ UI from which to create new check-in events.  New UI is only available to `admin`s.
For convenience, the new UI has inline styling and Javascript.  I figure that is okay, as we will not be surfacing this __temporary__ UI to patrons.  The purpose of the UI is for admins to quickly add new events to their dev instances, and to give an example of how to construct a valid payload client-side.  The test UI can be viewed at `/check-ins/{work_olid}` (work OLID need not be valid).
Any updates to the `data` field …
=> Check-ins backend

openlibrary/templates/diff.html
Closes [Sentry OL-WEB-88](https://sentry.archive.org/organizations/ia-ux/issues/81) which has been happening for 7 months and happened 17k times in the past 30 days and 1.1k times in the past 24 hours.
When `get_version(page.key, page.revision)` returns `None`, properly display the page instead of raising the exception `AttributeError: 'NoneType' object has no attribute 'author'`
=> NoneType object has no attribute author

openlibrary/plugins/openlibrary/js/add_provider.js, openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/upstream/addbook.py, openlibrary/plugins/upstream/models.py, openlibrary/templates/books/add.html, openlibrary/templates/books/edit/edition.html, static/css/components/provider-table.less, static/css/page-user.less
Adds field for a web book URL in the add book form.
Also adds a providers table to edition edit forms. New rows can be added to the table dynamically.
=> Include web book URL in add book form

docker-compose.yml, openlibrary/core/bookshelves.py, openlibrary/core/models.py, openlibrary/core/ratings.py, openlibrary/macros/SearchResultsWork.html, openlibrary/macros/StarRatings.html, openlibrary/plugins/upstream/mybooks.py, openlibrary/plugins/worksearch/code.py, openlibrary/templates/account/books.html, openlibrary/templates/account/reading_log.html, openlibrary/utils/solr.py, tests/test_docker_compose.py
Closes #5080. This may need significantly more work, however.
Feature. Adds basic capacity to filter/search one's reading log.
This draft PR likely needs some work, but before getting the problems, first comes an explanation of how this theoretically works:
- From the [Reading Log](http://localhost:8080/people/openlibrary/books/want-to-read) one can enter a 3+ character search term and search (1) up to 1000 of their logged books to see (2) up to 100 matching results within that 1000.
- Currently, searching is not limited to title or author, but rather the defaults from `do_search`. This would be easy enough to change I think by switching to `run_solr_query` (unless it's possible to specify fields in `do_search`.
- Because I could not figure out a good way to filter the results, there is …
=> Adds ability to search/filter one's reading log

static/css/components/work.less
Closes #6536 
This PR fixes the UI issue that was caused when clicking a subsection on the navbar which jumped down too far.
I added margin to the scrolling on top of the anchor points so that when the page jumps it stops right above the anchor point. The problem was that the jump did not account for the nav bar and title staying at the top of the page while scrolling down.
To test my code, simply apply the changes and run the developer mode. Go to any edition or work page and click on the navbar link. Observe the page after scrolling has stopped.
@mekarpeles
=> Fixed excessive scrolling issue w/ Related Books tab

openlibrary/macros/databarWork.html, openlibrary/templates/type/edition/view.html, static/css/components/read-panel.less
Closes #7009 
Feature: `Display vendor beneath omnibar on mobile book page views`
Tried this method suggested in the issue:
> It's probably best to pass an optional string to the template containing any additional classes that will be needed to display the correct vendor section. You can add the new classes the the ul element in AffiliateLinks.html.
Inside `AffiliateLinks.html`
```html
$def with (page, opts, classes='')
...
<ul class="buy-options-table $_(classes)">
```
Inside `view.html`
```python
$:macros.AffiliateLinks(page, {'isbn': isbn_13, 'asin': asin, 'prices': prices}, 'mobile-vendor')
```
Inside `read-panel.less`
```css
.mobile-vendor {
display: none;
}
...
@media only screen and (max-width: @width-breakpoint-desktop){
.mobile-vendor {
display: inline;
}
.desktop-vendor { …
```
=> Display vendor beneath omnibar on mobile book page views

openlibrary/core/ia.py
This was being called with dontcache=True waaaay too often!
Here's an example load graph from our works pages:
=> Fix cache=True logic for ia.get_metadata

openlibrary/templates/type/list/view_body.html
Closes #6660
This PR achieves a feature where clicking on lists now has pagination at the top and bottom of the lists. 
In the “view_body.html” in templates/type/list, the div with class “mybooks-list” now has a macros pager and an additional div with class “clearfix”. This is done so the presentation of the pagination elements remains consistent at the top and bottom of the lists page.  
To reproduce or verify what this PR fixes, one should create or access a list of over 50 items (so there are enough items to present pagination). After completing the above one should look at the people/username/lists/list_id/list_name page and find that pagination is present on the top and the bottom. 
@seabelis  @cdrini @mekarpeles
=> Solves #6660 whole issue of duplicating pagination for user lists

openlibrary/plugins/importapi/code.py
This is needed for importing `promise` item json because some records have no publisher or author.
=> allow overriding import authors + publishers

scripts/promise_batch_imports.py
Run on ol-home0 cron container as
`su openlibrary -c 'PYTHONPATH="/openlibrary" python3 /openlibrary/scripts/promise_batch_imports.py /olsystem/etc/openlibrary.yml'`
Addresses #7132
The imports can be monitored for their statuses and rolled up / counted using this query on `ol-db1`:
```
openlibrary=# select count(*) from import_item where batch_id in (select id from import_batch where name like 'bwb_daily_pallets_%');
```
Relies on #7131 draft
@judec @brewsterkahle @hornc
=> import promise items batch

openlibrary/templates/books/RelatedWorksCarousel.html
Fix. Performance and unnecessary hits to IA metadata. Closes #7136 .
Removes 10s of archive.org metadata API calls per OL book page load!
- We can delete a good chunk of code after this as well: #7138 . Separating to get this out sooner.
- Books without subjects work
- Books in results are comparable (see screenshots)
The timing improvements on testing are quite promising!
The line ~15:00 is when this PR was deployed to testing.
Results look better or comparable:
=> Switch RelatedWorksCarousel to use solr

conf/openlibrary.yml, openlibrary/plugins/openlibrary/sentry.py, openlibrary/utils/sentry.py
We've been getting more traffic lately, and as a result the system has been struggling. To get more visibility into places we can squeeze out some more performance, let's use sentry's performance tools!
- Some of the routes aren't being picked up correctly, but those can be fixed later. eg: profile pages (/people/Foo) show up as <other>, admin pages are all grouped together.
- Throttled to 20% of traffic on prod, 100% on testing
- TODO in future PR: Add to covers, which is currently experiencing the most strain!
- TODO in future PR: Add to infobase
Try it at https://sentry.archive.org/organizations/ia-ux/performance/?breakdown=none&environment=ol-dev&isDefaultQuery=false&metricSearchSetting=transactionsOnly&project=7&showTransactions=p95&sort=-timestamp&statsPeriod=24h 
The metrics are …
=> Add sentry transactions to OL python

openlibrary/plugins/openlibrary/js/readmore.js
Fixes issue where book page subjects do not expand/collapse in Firefox.
=> Fix subject clampers for Firefox

openlibrary/templates/account/mybooks.html
Closes #7053 First step of My Books page redesign process 
Create a new page at /account/books (technically /people/username/books) with new My Books desktop interface
Carousels are custom_carousels, I was unable to test with books in the loans carousel as yet
go to /account/books at your local instance and click through the carousels to see what it does. if there aren't any books in your testing instance, add some books to reading logs or borrow some books if possible
@mekarpeles @jimchamp @cdrini
=> adding book image carousels for loans and reading logs, title URLs

openlibrary/plugins/upstream/mybooks.py, openlibrary/templates/account/mybooks.html
Closes #7053 
Fixes responsiveness bug with carousel design for My Books page with sidebar
set compact_mode=True for each of the carousels
Try looking at carousels with different numbers of books (1 or 2 books vs 5 vs 10)
@mekarpeles @jimchamp @cdrini
=> setting compact_mode=True in the loans and logs carousels to improve responsiveness

openlibrary/templates/lib/header_dropdown.html, openlibrary/templates/lib/nav_head.html
Closes #7021
Makes the following updates to the hamburger menu:
1. Replace "My Loans", "My Reading Log", "My Lists", and "My Reading Stats" links with single "My Books" link which references the loans page.
2. Split "More" section into "Contribute" and "Resources" section.
Unreferenced `moreProps` have been removed from `nav_head.html`.
@danafein
@mekarpeles
=> Update hamburger menu

openlibrary/plugins/openlibrary/api.py, openlibrary/templates/home/index.html, openlibrary/utils/dateutil.py, openlibrary/views/loanstats.py
Closes #6674
This PR still needs to be updated so the header link goes to some sort of hourly view. Currently `hourly.json` has no UI. 
https://github.com/internetarchive/openlibrary/issues/6674#issuecomment-1160791270
After review, we may just want to use the /now.json endpoint (and not aggregate by time)
=> Change trending to hourly API

openlibrary/macros/HiddenSaveButton.html, openlibrary/macros/databarEdit.html, openlibrary/templates/books/edit.html, openlibrary/templates/type/author/edit.html, static/css/components/edit-toolbar--tablet.less, static/css/components/edit-toolbar.less
Closes #6583
Adds delete button to the top of the author edit page for admins and super-librarians.  Adds hidden "Save" button before the delete button in order to prevent accidental deletions when the enter button is pressed (see: #6472).
_Desktop view_
_Mobile view_
=> Add delete button to author edit page

.pre-commit-config.yaml, pyproject.toml, setup.cfg
`codespell`'s latest [release](https://github.com/codespell-project/codespell/releases) adds support for reading its configuration from `pyproject.toml`.  This pull request drops `setup.cfg` and consolidates our configs for `psf/black, `codespell`, `mypy`, and `pytest` in our `pyproject.toml` file.
`codespell` runs in pre-commit so this is tested on both local commits and on pre-commit.ci
=> Drop setup.cfg in favor of pyproject.toml

openlibrary/core/lending.py
Closes #7065
There are duplicate keys in the definition of a dict.  This PR eliminates the first entries and leaves the second entries in place which is exactly what Python has been doing by default.  The `resource_type` value that is being preserved is passed into this function.  The `resource_id` is being created in this function.
=> Fix openlibrary/core/lending.py: Fix duplicate enties in a dict

.pre-commit-config.yaml, openlibrary/accounts/model.py, openlibrary/api.py, openlibrary/book_providers.py, openlibrary/core/bookshelves.py, openlibrary/core/edits.py, openlibrary/core/lending.py, openlibrary/core/vendors.py, openlibrary/plugins/books/readlinks.py, openlibrary/plugins/upstream/account.py, openlibrary/plugins/upstream/addbook.py, openlibrary/plugins/upstream/edits.py, openlibrary/plugins/upstream/utils.py, openlibrary/plugins/worksearch/code.py, openlibrary/solr/data_provider.py, openlibrary/solr/query_utils.py, openlibrary/solr/update_edition.py, openlibrary/solr/update_work.py, openlibrary/utils/solr.py, scripts/copydocs.py, scripts/ipstats.py, scripts/solr_builder/solr_builder/solr_builder.py, scripts/solr_builder/tests/test_fn_to_cli.py, scripts/solr_updater.py, scripts/tests/test_copydocs.py
Closes #7169 
Mypy 0.990 disallows implicit optional types by default. This PR
changes hints of the form `i: int = None` into `i: int | None = None`.
Although there were 23 files with implicit optional issues, a in 24th, `openlibrary/accounts/model.py`, `mypy` had a problem with `# type: ignore[misc]`, so I changed that to `# type: ignore[misc, assignment]`.
Additionally, I could not commit without `.pre-commit-config.yaml` staged, even though it updated mirrors-mypy to `v0.991`. Please let me know if that is an issue and I'll try to work around that.
@cclauss
=> Make optional type hints explicit, per PEP 484

openlibrary/core/lending.py, openlibrary/plugins/openlibrary/api.py, openlibrary/plugins/openlibrary/home.py, openlibrary/templates/home/custom_ia_carousel.html
Refactor. Delete no longer used methods now that RelatedWorkCarousel uses solr.
- Related carousels still work. We shouldn't be using these anywhere else?
=> Delete old subject carousel code

openlibrary/plugins/openlibrary/code.py
Refactor. We could do this in more places, but these are the most hit endpoints.
- This improves Sentry, since this will no longer show as "failed"
- Also remove some unhelpful try/excepts. We _do_ want it to error if those files are missing for some reason!
- URLs still work:
- https://testing.openlibrary.org/health
See the failure rate plummet!
=> Change simple 200 raise to return

openlibrary/catalog/merge/normalize.py, openlibrary/catalog/utils/__init__.py, openlibrary/core/bookshelves.py, openlibrary/core/cache.py, openlibrary/core/ia.py, openlibrary/core/imports.py, openlibrary/core/lending.py
Partially #6755 
Refactor.
Here's the next batch of type hints from type annotations. I will attempt to preemptively explain my rationale for some of the changes to help shorten the feedback cycle:
- `/core/lending.py`: I didn't update `s3_loan_api()` because the default value doesn't match what's in the comments, and after a few minutes I couldn't find the actual values from Internet Archive.
- `/core/cache.py`: in `class memoize` it wasn't immediately apparent what types `key` could be, though the docstrings mention at least two types are `str` and a `Callable`, as well as the default `None`.
- `catolog/utils/__init__.py`: In `flip_name()` mypy took issue with `m.group(2) + ' ' + m.group(1)` because it is possible there is no match. I added an `isinstance(m, Match)`, but that meant the …
=> Type hints from type annotations, batch 6

openlibrary/core/bookshelves.py, openlibrary/plugins/worksearch/code.py, openlibrary/plugins/worksearch/schemes/__init__.py, openlibrary/plugins/worksearch/schemes/authors.py, openlibrary/plugins/worksearch/schemes/subjects.py, openlibrary/plugins/worksearch/schemes/tests/test_works.py, openlibrary/plugins/worksearch/schemes/works.py, openlibrary/plugins/worksearch/subjects.py, openlibrary/plugins/worksearch/tests/test_worksearch.py, openlibrary/solr/query_utils.py, openlibrary/templates/authors/index.html, openlibrary/templates/search/authors.html, openlibrary/templates/search/subjects.html, openlibrary/templates/work_search.html, openlibrary/utils/__init__.py, openlibrary/utils/tests/test_utils.py
Refactor worksearch code for easier maintenance/DRY-ness.
- Introduces an abstraction `SearchScheme` to handle the different "types" of search (eg author, work, etc). The scheme defines various parameters for what can be faceted, what fields can be fetched/sorted, etc. This lets us use the same core code for all the different search pages. And potentially in the future, this could even let us use the same UI/templates.
- This also makes worksearch/code.py MUCH smaller! :) 
- Allows searching by the field `top_subjects` in authors searches. Eg https://openlibrary.org/search/authors?q=top_subjects%3AHorror
- Fix: trailing dashes in search causing errors
Future TODOs:
- Rename some of the fields in `SearchScheme` ; their purpose has become clearer now than when I started writing it
- Link …
=> Refactor/DRY worksearch/code.py

openlibrary/components/MergeUI/MergeTable.vue
Closes #7120
If a primary record has been selected, the work records are not reordered.  Instead, the chosen primary record is selected as the main record.
=> Prevent reordering of work records in merge UI

openlibrary/macros/databarEdit.html, static/css/components/edit-toolbar--tablet.less, static/css/components/edit-toolbar.less
Closes #7188
Reverts layout changes made in #7157.
Previous layout changes were made in order to align the author page delete button with the "Cancel" link in mobile views. Reverting these changes causes the delete button to appear to the right of the "Edit Author" heading (see screenshot below).  This change will only affect admins who edit in mobile views.
=> Fix edit button layout

openlibrary/plugins/upstream/addbook.py
Closes #7075 
Fix.
Stops `TypeError` `'NoneType'is not iterable` when removing the weight or physical dimensions from an edition and saving, when the edition originally had:
1. a weight but no weight unit, or
2. a physical dimension but no physical dimension unit.
Though the scope of the issue was only weights, the same issue was present with the `physical_dimensions` value and the fix was the same.
If `edition.weight` or `edition.physical_dimensions` was an empty string, e.g. because a librarian had deleted a bad weight value, `trim_doc()` would set the values to `None`, which caused calls to `list(None)` a few lines later in `process_edition()`.
It would have been possible to simply move `edition = trim_doc(edition)` below the `list(edition.get('physical_dimensions', []))` and …
=> Prevent calls to `list(None)` for edition weights and dimensions

openlibrary/templates/check_ins/modal_form.html
If a patron sets the last read page of a book and later views the book's page, a prompt to edit the last read date appears below the reading log dropper.  Pressing the edit button displays a form that should be populated with the last read date, but the logic that sets the selected year is incorrect.  This PR corrects this issue.
_Before: Year is not selected by default.  Pressing the "Submit" button before setting the year would send an invalid date to the server_
_After: Year is correctly pre-populated_
=> Check-ins: Ensure last read year is selected by default in edit form

openlibrary/core/schema.sql, openlibrary/core/yearly_reading_goals.py, openlibrary/tests/core/test_db.py
Adds definition and CRUD functions for a new table that tracks patrons' yearly reading goals.
`yearly_reading_goals` DDL must be executed before this is deployed.
=> Yearly reading goals back-end

openlibrary/plugins/openlibrary/js/lists/index.js
Today, the last read date prompt is displayed whenever a book has been marked "Already Read", regardless of whether a date has been set or not.  This can sometimes cause the date display and the date prompt to appear concurrently:
This PR checks if the date display is visible before displaying the prompt on "Already Read" clicks.
=> Prevent showing date prompt if read date exists

scripts/partner_batch_imports.py, scripts/tests/test_partner_batch_imports.py
Closes #7201
This prevents importing books from partner data where the `publish_date` is for a future year.
This just checks if a book's `publish_date` is for a future year; if it is, it won't import it via `batch_import`.
To satisfy mypy `cast` is used, as I wasn't sure of the data schema. I'd like to address this if I can before merging.
I am testing if `publish_date` is a future year by adding +1 to the current year, and I don't know enough about the publishing industry to know if this is a problem.
For example, if publishers submit data to Open Library partners in the last week of December for books published in January of the coming year, this PR treats that data as bad.
Take a look at the new tests in `scripts/tests/test_partner_batch_imports.py`, make sure they cover the use cases, …
=> Don't import from partner data where publish_date is a future year

openlibrary/catalog/add_book/__init__.py, openlibrary/core/imports.py, scripts/manage-imports.py, scripts/promise_batch_imports.py
Closes #7215 
- Runs 10 workers in parallel
- Fixes bug where `source_record` field would be deemed sufficient to create a "match" on import!
- Corresponding haproxy changes: https://github.com/internetarchive/olsystem/pull/166
- Observe increased throughput in https://openlibrary.org/people/ImportBot
@mekarpeles
=> Parallel process importbot imports to increase throughput + bug fixes

openlibrary/templates/stats/readinglog.html
While prepping for #7218, I noticed that the `stats/readinglog` page was not rendering due to incorrect keys being accessed on the `stats` object.  This PR uses the correct values in the reading log stats template.
This branch has been deployed to testing.  You can test by comparing the following pages:
https://testing.openlibrary.org/stats/readinglog
https://openlibrary.org/stats/readinglog
=> Fix broken `stats/readinglog` page

openlibrary/templates/account/import.html, openlibrary/templates/type/list/exports.html
Adds Google Analytics tracking for the following actions:
- Goodreads imports
- Reading log exports
- Star Rating exports
- Lists summary exports
- Book notes exports
- Review tag exports
- JSON list export
- HTML list export
- BibTex list export
=> Add analytics for patron imports and exports

openlibrary/plugins/worksearch/code.py, openlibrary/plugins/worksearch/schemes/__init__.py, openlibrary/plugins/worksearch/schemes/authors.py, openlibrary/plugins/worksearch/schemes/subjects.py, openlibrary/plugins/worksearch/schemes/works.py, openlibrary/solr/query_utils.py, openlibrary/solr/update_edition.py, openlibrary/solr/update_work.py, openlibrary/tests/solr/test_query_utils.py, openlibrary/tests/solr/test_update_work.py
Makes edition search the default. It can still be disabled via cookies by the librarian/admin toggle.
- Known issues: searching for author. But I figure with the search nav, it's easy enough for people to switch to author search.
=> Fix various editions search bug + make edition search the default

openlibrary/macros/StarRatings.html, openlibrary/macros/StarRatingsStats.html, static/css/components/rating-form.less
… redirect user to rate section and highlights this section.
Closes #7024
Clicking Book Page Star Ratings summary redirect user to rate section and also highlights this section.
In the file "StarRatings.html", div with class="review" now also has an id="starRatingSection".
In the file "StarRatingsStats.html", there is a change that provides clickable link to "rate" section: 
< li onclick="location.href='#starRatingSection';" >
In terms of a design (highlighting), I added detailed comments to the code. (If needed, I can describe changes even more.)
After picking one of the books and clicking on Book Star Rating, you should be redirected to "rate" section, this section should be also highlighted for a moment.
@mekarpeles
=> Clicking Book Page Star Ratings summary goes to ratings section

openlibrary/macros/StarRatings.html, openlibrary/macros/StarRatingsStats.html, static/css/components/rating-form.less, static/css/components/work.less
Adds analytics to the star rating and star rating stats components.  Also, moves `scroll-behavior` rule (added in #7125) to `work.less`.
No distinction is made between star rating clicks on the book page and star rating clicks in search items.
=> Book page star ratings analytics + small refactor

docker/ol-covers-start.sh, openlibrary/coverstore/README.md, openlibrary/coverstore/archive.py, openlibrary/coverstore/code.py
Code fixes for #7197 
See: [README edits](https://github.com/internetarchive/openlibrary/pull/7230/files?short_path=a584955#diff-a5849555f8f6b6f9948f815963e945e4b66981c66eb57a1cf83941c133d5f696)
So far we've successfully archived `covers_0008_00` for all sizes and cleared up ~5GB.
=> Fixing py3 cover archiver + extending cluster allowlist IDs

openlibrary/plugins/openlibrary/js/SearchBar.js, openlibrary/templates/account/reading_log.html, tests/unit/js/SearchBar.test.js
Additionally, when a reading log shelf has < 1 book, link to /search. On mobile, clicking this link will expand and focus the main search bar at the top.
Closes #7143
Fix.
This does four things:
- It hides the reading log search when a shelf has < 1 book;
- It adds a link to /search when the reading log search is hidden;
- On mobile, clicking the link to /search will expand the main search bar at the top and focus it.
- It limits the `q` parameter used by `SearchBar.js` to `/search`; this way we can use `q` both for reading log queries and search bar queries -- and possibly other queries in other places.
Edit: I hasten to add this changes functionality on mobile in one minor way. Previously, the search bar at the top would only expand when one clicked on the magnifying glass; this changes …
=> Don't show the reading log search when a shelf has < 1 books.

openlibrary/templates/lib/header_dropdown.html, openlibrary/templates/lib/nav_head.html
Restores merge request badge count in the hamburger menu.
=> Restore badge count to navigation drawer

openlibrary/coverstore/code.py
Archives covers between 8100000 and 8230000 in archive.org items `covers_0008`, `l_covers_0008`, `m_covers_0008`, and `s_covers_0008` so the tars can be removed off disk. Bumps the coverstore ranges from including part `_10` to `_23`
=> move covers_0008 parts _10 to _23 -> ia

openlibrary/templates/admin/people/view.html
Noticed that the "View profile" links in `/admin/people/{person}` pages do not actually link to the person's page. This PR corrects the issue.
While logged in as an admin:
1. Navigate to a patron's `/admin/people` page.
2. Ensure that the red "View profile" link references the persons public profile page (rather than the current page).
=> Fix "view profile" link on `/admin/people/{person}` page

openlibrary/plugins/worksearch/code.py, openlibrary/plugins/worksearch/schemes/__init__.py, openlibrary/plugins/worksearch/schemes/authors.py, openlibrary/plugins/worksearch/schemes/subjects.py, openlibrary/plugins/worksearch/schemes/works.py
Closes #7270 . Closes #7284
- In incognito, https://testing.openlibrary.org/search?q=slovnyk&has_fulltext=true&mode=ebooks&sort=random shows 6 books. Logged in as admin, it shows 37
@mekarpeles
=> Make has_fulltext user pd-status aware

bundlesize.config.json, openlibrary/plugins/openlibrary/js/add-book.js, openlibrary/plugins/openlibrary/js/edit.js, openlibrary/templates/books/add.html
Closes #4548
Closes #7055 
Adds sanity-checks for the ISBN value in the add books page:
-strips ISBN value of whitespaces and hyphens
-checks ISBN length and ISBN checksum value
Error will be displayed when trying to add a book with an ISBN that is of incorrect length (whitespace and hyphens are *not* included in this character count) or if the ISBN checksum value is incorrect. User will subsequently be given the option to retry and submit the book with an invalid ISBN. Warning messages will reset if user changes the ISBN value or the ISBN field type (ISBN10 or ISBN13).
Try adding a book with an ISBN that either a) isn't 10 or 13 characters, or b) has an invalid checksum value i.e. 0-545-01022-4. Error should appear after clicking 'Add' the first time. Clicking 'Add' again will finish …
=> checking ISBN value when manually adding a new book

openlibrary/plugins/worksearch/code.py
Closes #7268
Author pages now prefer editions in the user's language.
- eg https://testing.openlibrary.org/authors/OL2162284A/Stephen_King?lang=fr
- eg https://testing.openlibrary.org/authors/OL23919A/J._K._Rowling?lang=fr
=> Make author pages used edition-aware data

openlibrary/templates/account/reading_log.html
Closes #7246
In My Reading Log views, the edition ID was being changed to `False` for "Want to Read" and "Currently Reading" shelves.  This PR corrects this issue by removing the bookshelf ID check that occurs when setting the `edition_key` parameter for the reading log droppers.
1. Add a book to your "Already Read" shelf.
2. Navigate to your My Reading Log "Already Read" shelf.  You should see a prompt for a check-in date on the newly added item.
3. Move the book to another shelf, then navigate to that shelf.
4. Move the book back to the "Already Read" shelf.  If the check-in prompt is present, then the `edition_id` is not being deleted.
=> Stop clobbering edition_id when changing shelves

.pre-commit-config.yaml, openlibrary/solr/process_stats.py, openlibrary/solr/update_work.py
pre-commit: Add the [auto-walrus](https://pypi.org/project/auto-walrus) tool which was used to create #7213 
Can these two solr-related files be modified in this way or will Cython object?  See #7213
=> pre-commit: Add auto-walrus to enforce Python assignment expressions

openlibrary/macros/NotesModal.html, openlibrary/templates/account/notes.html, static/css/components/metadata-form.less, static/css/components/notes-view.less
Updates classes of CTA buttons found in book notes components.  The delete buttons are now solid red with white letters, and the save buttons use the blue "shell" styling.  These changes make the notes component buttons consistent with the buttons on the new check-in form.
1. Navigate to a book page, and open the note modal and confirm that the submit button is styled properly.
2. Submit a note for the book. The notes modal should close (this is BAU).
3. Open the notes modal again.  Verify that the delete button is properly styled.
4. Navigate to the "My Notes" section of the My Books page.
5. Verify that the delete and save buttons are properly styled.
_Book page notes modal_
_"My Notes" page notes component_
=> Update book notes UI CTA button styles

openlibrary/core/bookshelves_events.py, openlibrary/plugins/upstream/checkins.py, openlibrary/plugins/upstream/tests/test_checkins.py
Validates POSTed check-in events (specifically the `event_type` property).  Also replaces the `has_key` enum method with a `__contains__` method (as per this [review note](https://github.com/internetarchive/openlibrary/pull/6987/files#r985286665))
Our backend check-in service expects `event_type` to be one of the values in the `BookshelfEvent` enum (1, 2, or 3).  This code checks if the value of `event_type` is included in `BookshelfEvent`.
=> Improve check-in event validation

openlibrary/templates/lists/lists.html
Avoids unexpected change of environment while testing features on testing.openlibrary.org
=> Use relative link to lists help page

openlibrary/macros/FormatExpiry.html, openlibrary/macros/LoanStatus.html, openlibrary/plugins/upstream/account.py, openlibrary/plugins/upstream/mybooks.py, openlibrary/templates/account/books.html, openlibrary/templates/account/loans.html, openlibrary/templates/account/mybooks.html, openlibrary/templates/account/sidebar.html, openlibrary/templates/books/custom_carousel.html, openlibrary/templates/lib/nav_head.html, static/css/base/helpers-common.less, static/css/components/buttonBtn.less, static/css/components/carousel.less
Prototype of #6857
https://testing.openlibrary.org/account/books
1. The My Books nav header + My Books hamburger go to a dedicated My Books page
2. compact_mode now not only fixes width issues in My Books but also takes up far less vertical space
3. I borrowed the chip code from @Jim Champ + community reviews to add My Reading Stats at the top of the design
4. My Books is much faster due to removal of logged_in_user.update_loan_status() call
5. I was able to DRY up the code a ton (other than chip and a bit of lazy less placement) 
6. Added bonus: This new My Books view looks significantly better than our existing views in mobile, so it's a great improvement until mobile designs land!
http://ol-dev1.us.archive.org:1337/people/mekBot/books?debug=true
=> My Books summary desktop redesign

openlibrary/core/yearly_reading_goals.py, openlibrary/plugins/openlibrary/js/check-ins/index.js, openlibrary/plugins/upstream/checkins.py, openlibrary/templates/account/mybooks.html, openlibrary/templates/check_ins/reading_goal_form.html
Closes #7329
Provides patrons with a way to delete their reading goals.  Submitting "0" as a goal update will delete the patron's current reading goal and update the "My Books" view.
Add instructive note to form if reading goal is set.  The note's copy and styling may need adjustment.
Restores client-side validation that was disabled with the `event.preventDefault()` call on form submission.
Chip group containing the "Set reading goal" link is now hidden (rather than removed completely).
Removes progress component on goal deletion.
`mybooks.html` adjusted to make updates to make client-side updates to the view easier.
=> Clearing reading goals

openlibrary/core/bookshelves_events.py, openlibrary/macros/ReadingLogDropper.html, openlibrary/plugins/openlibrary/api.py, openlibrary/plugins/openlibrary/js/lists/index.js, openlibrary/templates/account/reading_log.html
Closes #7333 
Closes #7334
Removes all check-ins for a work whenever the work is removed from all bookshelves.  Prompts patron to confirm that they'd like to proceed with this destructive action.
Prevents work card from being removed from "My Books" reading log views on shelf change.
=> Delete check-ins when book removed from all shelves

openlibrary/core/bookshelves_events.py, openlibrary/macros/ReadingLogDropper.html, openlibrary/plugins/upstream/checkins.py, openlibrary/templates/account/reading_log.html, openlibrary/templates/work_search.html, openlibrary/tests/core/test_db.py
Closes #7330
To avoid issues stemming from our reading log being a work-level feature, check-ins have been changed to be work-level.  When available, edition IDs are persisted with the check-in entry in order to make transitioning to edition-level check-ins easier.
Null edition IDs occur when a patron checks in from a search result item.
`edition_id` is still a required field in the `bookshelves_events` table.  If no edition ID is included with the check-in, `edition_id` is set to `-1`.  `edition_id`s of such entries will need to be updated to some best-fit edition ID once check-ins become edition-level.
`edition_id` is now also updated when a check-in date is updated, with one caveat: a valid `edition_id` will not be updated to `-1`.
=> Work-level check-ins

openlibrary/core/bookshelves_events.py, openlibrary/plugins/upstream/checkins.py
Adds missing `message` keyword when HTTP errors are raised.
Corrects a type hint.
Most importantly, prevents unauthorized users from deleting check-ins.
=> Misc. `checkins.py` fixes

openlibrary/plugins/openlibrary/js/check-ins/index.js, openlibrary/plugins/openlibrary/js/index.js, openlibrary/templates/account/mybooks.html, openlibrary/templates/check_ins/check_in_form.html, openlibrary/templates/check_ins/check_in_prompt.html, static/css/components/check-in.less
Closes #7335
This PR does the following:
1. Allows patron's to submit a check-in with the current year as the date in a single click.
2. Places check-in edit button on the same line as the read date.
3. Updates the year to the patron's local year, if necessary.
This branch is forked from #7343.  This branch will be ready for review once #7343 is merged and this branch is rebased.
=> Update check-in prompt

docker/ol-affiliate-server-start.sh, scripts/affiliate_server.py
Related to #7318 and #7340
The filename of this Python script currently contains a hyphen instead of an underscore and does not end in `.py` so the file is not tested in our pre-commit and cannot be pytested as attempted in #7340.  pre-commit tools like mypy, black, flake8, and auto-walrus make useful changes when the `.py` is added.  This PR also changes the name when the file is run.
`git grep affiliate-server`
=> git mv scripts/affiliate-server scripts/affiliate_server.py

openlibrary/components/AuthorIdentifiers.vue
Closes #7072
fix
Typing a long VIAF (or any other numerical identifier) with more than 16 digits will still switch the type to ISNI as you pass 16 digits, but pasting or editing a longer string of digits won't trigger the bug.
Visit a author edit page.
Pasting or typing the following ISNI codes should be automatically detected:
0000000403855362
000000012146438X
000000012146438x
The following Wikidata ids should be autodetected:
Q42
q42
Q461
The following Amazon IDs (or any string with a Q in the middle followed by digits) should not change the type setting to Wikidata when typed or pasted in:
B000AQ51EY
The following librarything ID (or any other string of characters that is 16 long but isn't entirely digits except for the last one which may optionally be an X) should not change the type …
=> Fix autodetect of identifiers

openlibrary/macros/ReadingLogDropper.html, openlibrary/plugins/openlibrary/js/check-ins/index.js, openlibrary/plugins/upstream/checkins.py, openlibrary/templates/account/mybooks.html, openlibrary/utils/dateutil.py
Removes beta-tester restrictions for check-ins and yearly reading goals.
Prompts patrons to set their 2023 reading goals (as opposed to setting a goal for the current year, 2022).
=> Prep reading goals for release

openlibrary/plugins/openlibrary/js/add-book.js, openlibrary/templates/books/add.html
Localizes recently added ISBN error strings for the "Add Book" page.  Also changes a function's name for clarity.
1. Navigate to the "Add a Book" page.
2. Select "ISBN10" from the ID dropdown.  Input a 9 digit number and press enter.  Confirm that an invalid ISBN10 message appears.
3. Input a 10 digit ISBN with an incorrect checksum, then press enter.  Confirm that an invalid checksum message appears.
4. Select "ISBN13" from the ID dropdown.  Input a 12 digit number and press enter.  Confirm that an invalid ISBN13 message is displayed.
5. Input a 13 digit ISBN with an incorrect checksum, then press enter.  Confirm that an invalid checksum message appears.
@tfmorris
=> Internationalize add book ISBN error messages

openlibrary/templates/diff.html
I discovered this bug in the diff display while working on merge undo.
If two revisions of a work have different `authors` values, but one of the authors redirects to the other, the diff display will say there is no difference:
This fix causes the pre-redirect values to be compared and displayed:
diff.html was calling `get_authors()` on the work object to retrieve the values for comparison, but `get_authors()` resolves redirects before passing the values back. I replaced the call with a direct retrieval of the object values.
Browsing back through the history of the code in question, it's not clear that this case has ever worked correctly.
This problem crops up most when work authors have been reassigned during an author merge. Here's an example:
Look at …
=> Fix for diff.html not correctly handling redirected author data

openlibrary/plugins/worksearch/code.py
[Ply](https://pypi.org/project/ply) is throwing `ParseSyntaxError` when param['q'] one or more space characters.
We do not want to `process_user_query(" ")` so let's instead use `build_q_from_params(param)`.
Closes https://sentry.archive.org/organizations/ia-ux/projects/ol-web/?issuesType=all&project=7&query=ParseSyntaxError
=> Deal with query param['q'] being only whitespace

openlibrary/core/cache.py
Fixes two pytest `DeprecationWarning: getName() is deprecated, get the name attribute instead`
Similar to #5157 a few lines further down in the same file.
Closes #
=> Fix DeprecationWarning: threading.Thread.getName() --> Thread.name

openlibrary/templates/diff.html
Closes #7355
This fixes the problem of the diff display not showing author changes for editions.
Editions store authors differently than works, so the special case in the diff routine for work authors fails when handling an edition. However, the default behavior works just fine for editions, so limiting the special case to works solves the problem.
BEFORE:
AFTER:
@mheiman @tfmorris @cdrini
=> Correctly handle author data in edition diff display

CONTRIBUTING.md
[No Ticket #] Discovered this extremely minor issue while running through the steps in `CONTRIBUTING.md`.
This PR makes the link in the outline of the "Getting Started" Markdown document match the link in the body.
Prior to this fix, the "Quick Tour" text linked to a ~2 hour long video.
N/A
1. Go to the URL specified in the original Markdown link: [https://archive.org/embed/openlibrary-tour-2020](https://archive.org/embed/openlibrary-tour-2020)
2. Verify that it links to an incorrect file ("2021-10-26-OpenLibrary-Community-Celebration")
3. Verify that the updated link matches the URL in the "Quick Tour" section of the body (https://archive.org/embed/openlibrary-tour-2020/openlibrary.ogv)
N/A
Tagging @mekarpeles as the most recent contributor to this file (please let me know if I should …
=> Update Quick Tour video link

openlibrary/plugins/worksearch/code.py, openlibrary/plugins/worksearch/schemes/authors.py
Closes #7371 
Boost phrase matches when performing an author search. E.g. searching for `e h smith` will now show results that match the full phrase `"e h smith"` over those that match `e OR h OR smith` in any order. To make this work, I had to change the default sort order. Previously results were always sorted by `work_count desc`.
Compare: https://testing.openlibrary.org/search/authors?q=h.+a.+j
- correct j k rowling boosted
- correct mark twain at top
Improvements in metrics:
Class | AVERAGE of Prod | AVERAGE of Testing
-- | -- | --
Initials | 25.5 | 5.5
Middle names | 1 | 3
Popular Authors | 1 | 1
Top User Searches | 1 | 1.111111111
Grand Total | 4.5 | 1.857142857
See https://docs.google.com/spreadsheets/d/1BN5I7-OkTPaoTr2Es6jQ4O9ICWFmH0q9CP6kEgolCgg/edit#gid=1127406974
@tfmorris
=> Make author search results sort by relevance

openlibrary/plugins/worksearch/subjects.py, openlibrary/solr/query_utils.py
Closes #7074 
- https://testing.openlibrary.org/publishers/Media_Blasters no longer shows as missing.
- Normal subjects still work https://testing.openlibrary.org/subjects/English_Poetry
@seabelis
=> Fix publishers pages showing no books

openlibrary/catalog/marc/parse.py, openlibrary/catalog/marc/tests/test_data/bin_expect/equalsign_title.mrc
Closes #701
Bugfix for #701 to add the number of work part (245$n) to edition titles. 
- it's trivial
- run MARC unit tests
@hornc @mekarpeles
=> Add number of work part to edition titles. Fixes #701

openlibrary/templates/books/edit/about.html
Closes #7374
Stops the editing interface from doubling quotation marks embedded within subject tags.
The quote doubling function was in place for the previous version of the subject editing code, and was no longer needed, so I removed it.
Create a tag with internal quotes, e.g. Winnie "The" Pooh. Save the change, then edit again. The quotes should remain as originally entered.
=> Removed quote doubling code from subject editing

openlibrary/templates/account/books.html
Checks that `key == 'mybooks'` before rendering yearly reading goals banner on My Books pages.  Failing to do so causes the banner to render on all My Books pages.
Also adds profiling for banner render times.
=> Display reading goal banner only on new My Books page

.github/workflows/python_tests.yml
We are halfway thru the Python 3.12 alpha cycle so let's see if any of the proposed changes break our tests...
* https://peps.python.org/pep-0693/#release-schedule
* https://www.python.org/download/pre-releases
* https://www.python.org/downloads/release/python-3120a4/
Related to internetarchive/infogami#209
Closes #
=> Add Python 3.12-dev to the testing

openlibrary/catalog/marc/parse.py, openlibrary/catalog/marc/tests/test_data/bin_expect/equalsign_title.mrc, openlibrary/catalog/marc/tests/test_data/bin_expect/zweibchersatir01horauoft_meta.mrc, openlibrary/catalog/marc/tests/test_data/xml_expect/zweibchersatir01horauoft_marc.xml, openlibrary/catalog/marc/tests/test_parse.py
Closes #7403
This fixes a few things:
- Missing 008 language fallback should actually work now (it couldn't have before)
- All languages are imported for primary content
- Support is added for multiple languages encoded in a single subfield (an obsolete cataloging practice, but one which is present in the MARC test data)
=> Fix parsing of MARC 041 field. Fixes #7403.

openlibrary/plugins/worksearch/schemes/works.py
This PR makes it so you can sort by key. 
Right now an API call like https://openlibrary.org/search.json?q=craigslist&fields=title,key&sort=old works and sorts by title. After this PR is merged https://openlibrary.org/search.json?q=craigslist&fields=title,key&sort=key will work and will sort by key.
Why do I want this?
I would like to sort by key because I want to be notified when new books are added to OL for a certain query. I want to use [followthatpage.com](http://followthatpage.com/) to check once per week for changes in the json response. If items move around in search (as they do occasionally) then I'll get false positives (as follow that page is just doing  a plaintext diff). But if they're sorted by key then I'll just be notified by a new change.
It's pretty simple, following …
=> [api] add ability to sort search results based on key

openlibrary/i18n/fr/messages.po
**What issue does this PR close?**
There is not any PR associated with this issue.
I have translated the "Trending Books" portion of the French home page. The intention of this translation is to ensure the home page is read more naturally by French speakers.
In addition, upon updating the file, I ran into an issue as it seems another portion of the file had been changed but not updated.
```
openlibrary/i18n/fr/messages.po:5326: 'Voir %(count)s édition'
incompatible format for placeholder 'count': 's' and 'd' are not compatible
Failed custom string format validation
Validation failed...
Please correct the errors before proceeding.
Validation failed.
2 errors found...
```
This was fixed by switching "s" to "d" on the French translated portion. Once updated all tests passed.
**What does this …
=> Bug fix and French language corrections

openlibrary/components/MergeUI/MergeTable.vue
This is a small interaction fix for MergeUI. The code currently checks to see if any works have more than 200 editions and blocks the merge in that case. However, it doesn't check whether the large work is actually selected to be included in the merge, so you can't make your merge go through just by unchecking the offending item.
This PR adds one line of code to check for selected status so that the process behaves as expected.
You don't really want to mess around with big merges to test this, but you can if you want to. I've tested it thoroughly in a local instance.
@cdrini @mheiman
=> Allow work merge if 200+ edition work is present but unselected

openlibrary/catalog/add_book/tests/conftest.py, openlibrary/plugins/importapi/code.py, openlibrary/plugins/importapi/tests/test_code.py, openlibrary/plugins/upstream/tests/test_utils.py, openlibrary/plugins/upstream/utils.py
Improve page count and language detection for IA imports where no MARC record is available.
Closes no PR.
Fix.
Previously, `get_ia_record()` in `openlibrary/plugins/importapi/code.py` wouldn't try to get the page count from IA metadata, nor would it try to get a language from that metadata unless the language was represented as a three character abbreviation.
This PR:
- allows language detection where the IA metadata has, for example `'language': 'English'`;
- gets the page count from the IA record's `imagecount`, which appears to be where the page number comes from on the details page for an IA scanned book.
Try importing an IA record that has metadata where `'language'` is an English-word-representation of a language and where there is an `'imagecount'`, along with no MARC data.
Two …
=> Improve page count and language detection for IA imports

scripts/promise_batch_imports.py
The Promise Item importer was queuing far fewer imports than we need because in some cases the field BookSKUB was an empty string. Every time this happened, the result was that the item we were adding to the batch also had an empty `ia_id` (since BookSKUB is part of the record's primary ID) and therefore it was skipped.
This change ensures that (likely) tens of thousands of records which didn't have a `BookSKUB` value will now receive one by virtue of falling back to `BookSKU` (sans the `B`) and `BookBarcode` values. By `or`-ing them, we have a much higher chance one of them will be there. `BookBarcode` seems to almost always be present but since i'm not positive whether Barcode will always be the SKU, we favor the SKU + SKUB fields first.
This code also adds more flexible processing …
=> ensure books have bwbsku/barcode

openlibrary/plugins/admin/code.py
Closes #7204
Deletes every new record created by a user who's edits are being reverted.  Adds deleted record count to flash message.
=> Delete records created by blocked patron

openlibrary/plugins/upstream/account.py
Closes #7383
Resolves redirects before generating the export file.
=> Resolve redirects before exporting data

openlibrary/plugins/upstream/account.py
Closes #7421
Corrects malformed reading log `.csv` issue by escaping `title` and `authors` fields.  Additionally, escapes subject field strings, eliminating the need to replace commas with semicolons in these fields.
The new `escape_csv_field` could be combined with the `csv_string` function to greatly simplify our existing and future `.csv` row formatters.
Follow replication steps outlined in #7421. Verify that the results are as expected.
Additionally, ensure that there are no unexpected semicolons in the subject fields of the exported records.
=> Fix malformed reading log exports

openlibrary/coverstore/code.py
Closes #7362 
Followup to #7260.
QA required to ensure all files on archive.org before deleting.
Example IDs are those between 8240000 and 8810000.
* ✅ https://covers.openlibrary.org/b/id/8500001-L.jpg -- correctly resolves
* ✅ https://covers.openlibrary.org/b/id/8500001-M.jpg -- correctly resolves
* ✅ https://covers.openlibrary.org/b/id/8500001-S.jpg -- correctly resolves
* ✅  https://covers.openlibrary.org/b/id/8500001.jpg -- does **not** seem to resolve!
**2023-01-29** All resolved -- wrote a script #7472 to audit uploads to ensure all covers parts successfully uploaded!
Deleted `[s,m,l]_covers_0008` up to `80` from disk.
Patch deployed this PR for images up to id `8810000`
**2023-01-28** Not all uploads succeeded to `covers_0008` (full size). Re-uploading now.
Looks like a catalog red …
=> archive another ~570k covers

.gitpod.yml, .pre-commit-config.yaml, scripts/setup_gitpod.sh
Closes #6918
Fixes committing via Gitpod.
Before: `pyenv install`
After:
```
pyenv install 3.11 --skip-existing
pyenv global 3.11
```
We were running the install command without specifying the version. I assume at one point we had a `.python-version` file it was reading but we removed it. Setting this here now is a bit clearer. 
It is a small bit of work to keep this file in sync with pre-commit yaml but simpler than trying to parse it.
I didn't look now, but some months ago when I looked there was no straightforward way to sync a precommit config file and the `.python-version` file without bash scripts editing files. 
If someone knows otherwise please let me know.
This is the recommended way to set a python version in Gitpod https://www.gitpod.io/docs/introduction/languages/python#python- …
=> fix commiting from Gitpod

openlibrary/plugins/upstream/addbook.py, requirements.txt
Closes #
This is taking values from the edition edit web form -- there is no `distributors` value on that form to read this data from.
=> remove non-existent form field 'distributors'

Readme.md
This is just following the docs [here](https://www.gitpod.io/docs/introduction/getting-started#contribute-with-gitpod-badge) to use the new smaller (uniform) button for the readme :)
@cclauss
=> use new smaller gitpod button

openlibrary/macros/AffiliateLinks.html
Matt Hogberg @ BWB reports: 
> While working on a project I noticed links on http://openlibrary.org point to `betterworldbooks.com/-id-{ISBN13}.aspx`. These work but get a 301 redirect over to `https://betterworldbooks.com/product/detail/-9780747582380`. Feel free to change the format to `betterworldbooks.com/product/detail/{ISBN13}` as this will prevent the redirect.
On https://testing.openlibrary.org/works/OL17860744W/A_Court_of_Mist_and_Fury
=> Rework bwb urls to avoid redirects

openlibrary/catalog/add_book/__init__.py
Closes #7493
Imports `publishers`, `publish_date`, and `number_of_pages` fields when a matching edition is found.
=> Add additional importable fields to edition

scripts/affiliate_server.py
Aspires to close #7340, #7184
Once upon a time, Amazon imports from affiliate_server were not working because `db_parameters` was required and this field was in `infogami.yml` which was not available to `affiliate_server.py`. This was recently changed. See: https://github.com/internetarchive/openlibrary/pull/7109/files#diff-939173f100b9faaec94fb740138ad0f6376d79e4317974d4dc28a5b489bab7b8R237
But in doing this, we forgot to update the config load methods to load `infogami.yml` and so the variable was not available. We fix that in this PR.
EDIT 2: Since @jimchamp merged #7495, the catalog should now support the fields we're submitting! 🎉 
EDIT 1: web.ctx.site has been fixed, however, the `pre_check` algorithm now does not seem to be working correctly in that it is allowing entries into the …
=> Fix amz imports + stats

.github/workflows/python_tests.yml
This slows down our pipelines and doesn't provide a ton of value; it's unlikely we'll break compatibility with py 3.12, so don't need this to run for every PR. Also results in more queueing for our workflows.
@cclauss
=> Rm 3.12-dev from testing; it's slow

scripts/get_web_error.py
Closes #
> Sorry. There seems to be a problem with what you were just looking at.
We’ve noted the error 2023-02-02/133571627493 and will look into it as soon as possible. Head for [home](https://openlibrary.org/)?
% `python3 get_web_error.py 2023-02-03/011556535629.html | lynx --stdin`
To see the contents of an Open Library user-reported like `2023-02-03/011556535629.html`:
1. Copy this script into your user directory on any Open Library host.
2. Type the command above substituting in the error code you are looking for.
This script will ssh into `ol-web1` and `ol-web2` and if that file is found in the
`openlibrary_web_1 container`, it will print its contents to stdout.
Type `yes` if ssh prompts you to add the hosts to your known_hosts file.
If lynx is not yet installed, please type `sudo …
=> Add scripts/get_web_error.py to review user-reported errors

.pre-commit-config.yaml, pyproject.toml
Add https://beta.ruff.rs to our pre-commit as a replacement for `black`, `flake8`, `isort`, `pyupgrade`, etc. but written in Rust instead of Python. It can lint the CPython codebase from scratch in 0.29 seconds.
Adopting Ruff should greatly accelerate our pre-commits and our pre-commit.ci jobs. We will run the new and old tools in parallel for a sprint or two to verify the coverage before we completely drop the old tools.
=> pre-commit: Add Python linting tool ruff

openlibrary/plugins/worksearch/code.py, openlibrary/templates/search/authors.html, openlibrary/templates/search/sort_options.html
Closes #7365
Feature/Adds sort options to authors
The issue #7365 said there should be two options but the example said 3. I went with 3 options and it does default to relevance when there are authors. I have also noticed that relevance and work count appears to return identical results.   
I expect this might need a revision as the sort options might need to change :)
Go to author search, search for an author and sort by relevance or work count or random.
@cdrini
=> Add sort options for authors

openlibrary/plugins/openlibrary/pages/config_edition.page
LearnAwesome.org went through a rewrite recently. The URL scheme for identifiers has changed. This change fixes it.
Here's an example URL to a book on LA: https://learnawesome.org/#/item/34d8cd4d8294
Here's the corresponding book in OpenLibrary that has such an identifier present. This PR will fix the link: https://openlibrary.org/works/OL2745855W/Exit_voice_and_loyalty?edition=key%3A/books/OL3319564M
@cdrini had reviewed and merged the initial introduction of these identifiers: https://github.com/internetarchive/openlibrary/issues/3382
=> Updated the URL scheme for LearnAwesome.org

openlibrary/solr/data_provider.py
Closes #7467 . Fix. Remove ES limits since these internally used requests.
- We have access to the service unlimited param because we are in the cluster.
Full reindex now completes correctly.
@ximm
=> Remove solrbuilder ES rate limits

docker/web_nginx.conf
Remove duplicate listens on ports 80 default, 443
Closes #7544
We tested by modifying our local etc/hosts to map www0's ip to `x-openlibrary.org` and `www.x-openlibrary.org`, and confirmed the rewrites happened. (Also updated the server_name on www0's conf to be `x-openlibrary.org` for testing.)
=> Fix nginx restart loop

docker/README.md
Closes no issue.
I have noticed Docker and `git` sometimes cause an obstacle to contributions. To help new volunteers I have tried to clarify some elements where I have personally seen people getting confused, and where information about the same topic is found in different places.
I based the directions on Compose V2 as that is where it appears most first-time Docker users will be shepherded. If this was the correct call, I can update the wiki to be consistent with that by changing references from `docker-compose` to `docker compose`.
As part of this PR, see these two diffs for:
- [Frontend Guide](https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide/_compare/edcda40ce92b0845bcc60a458fb0d3c1b583e41d...b48726b18b008dd8e8c5df63c62eb446cb74c4d8)
- [How we use Git: Cheat …
=> More directions for Docker README; DRY up slightly

openlibrary/core/lists/model.py, openlibrary/core/statsdb.py, openlibrary/plugins/upstream/addbook.py, openlibrary/solr/data_provider.py, openlibrary/solr/update_work.py, pyproject.toml
https://docs.python.org/3/library/logging.html#logging.Logger.warning
> There is an obsolete method `warn()` which is functionally identical to `warning()`. As `warn()` is deprecated, please do not use it - use `warning()` instead.
This PR was created with:
% [`ruff --select=G010 --fix .`](https://beta.ruff.rs/docs/rules/#flake8-logging-format-g)
=> Remove deprecated logging.warn()

openlibrary/tests/core/test_db.py
We only need to import `YearlyReadingGoals` from `yearly_reading_goals.py` for these unit tests, not the entire module.  This PR removes the broader import.
=> Remove redundant import

openlibrary/core/imports.py, openlibrary/tests/core/test_imports.py, scripts/delete_import_items.py, scripts/import-item-cleanup/config.ini
Adds function for deleting entries from the `import_item` table, and script for deleting such entries in bulk.
DB entries that should be deleted will have a `batch_id` > 321, hence the default value in the `delete_items` function.
Script relies on an input file containing the `ia_id`s of entries that should be deleted.  Each line of the tab-separated input file is expected to be in the following format:
`{N number of IA IDs in this line} {edition_key} {IA ID 1} ... {IA ID N}`
Running this with `dry_run=True` will result in each `DELETE` statement being printed out, but with no data actually being deleted.
@mekarpeles
=> Create script for deleting import_item entries

openlibrary/coverstore/archive.py, requirements.txt
Run with
```
from openlibrary.coverstore import archive;archive.audit("0008", (20, 81), sizes=("l", "m", "s", ''))
```
Enables one to check which cover batches have been uploaded to archive.org, for which size.
e.g.
```
>>> from openlibrary.coverstore import archive;archive.audit("0008", (20, 81), sizes=("l", "m", "s", ''))
l: ...............................X...X.........................
ia upload l_covers_0008 l_covers_0008/l_covers_0008_51* l_covers_0008/l_covers_0008_55* --retries 10
m: ....................................XXXXXXXXXXXXXXXXXXXXXXXXX
ia upload m_covers_0008 m_covers_0008/m_covers_0008_56* m_covers_0008/m_covers_0008_57* m_covers_0008/m_covers_0008_58* m_covers_0008/m_covers_0008_59* m_covers_0008/m_covers_0008_60* m_covers_0008/m_covers_0008_61* …
```
=> code to audit cover archive uploads

openlibrary/macros/databarView.html, openlibrary/plugins/upstream/addbook.py, openlibrary/templates/books/edit.html
Closes #4993
Prevents redirect to edition page after editing a work page.
Whenever the edit button for a work page is rendered, the associated edition's edit URL is used in place of the work edit URL.  If the URL is not updated, the edition tab would not be present in the edit view.
This PR passes a `work_key` query parameter whenever the edit URL changes from a work to an edition.  `work_key` is passed to the POST handler by way of the edit form's `action` attribute.  If the `work_key` is passed to the handler, and it starts with `/works/`, patrons are redirected back to the work page.
1. Navigate to an edition page and click the "Edit" button.  When the edit form loads, click the "Save" button without making any edits.  Ensure that you are redirected back to the edition …
=> Redirect correctly on work edit

docker-compose.production.yml
The webserver logs are displaying the container ID instead of the hostname : https://archive.org/download/ia_webserverlogs_20230215/openlibrary/
Not testing; trivial change. I assume just an oversight.
=> Fix covers nginx weblogs having wrong hostname

openlibrary/templates/admin/index.html
These endpoints are now https enabled!
https://graphite.us.archive.org/render/?min=0&template=plain&lineMode=staircase&areaMode=stacked&areaAlpha=0.5&yAxisSide=right&title=openlibrary+++Unique+IPs+per+day+++(uip_openlibrary)&hideLegend=true&target=cactiStyle(alias(summarize(sumSeries(group(stats.uniqueips.openlibrary)),%221day%22),%22openlibrary+++Unique+IPs+per+day+++(uip_openlibrary)%22))&colorList=00ff00&height=200&width=900&from=-60days
=> Update /stats graphs to https

openlibrary/catalog/marc/tests/test_marc.py, tests/integration/__init__.py, tests/integration/test_auth.py, tests/integration/test_loans.py
Closes #
% `ruff --select=PT009 --fix .`
```
Found 49 errors (49 fixed, 0 remaining).
```
Pytest assertion introspection enables it to show the `expected` and `actual` side-by-side when tests fail.
* https://docs.pytest.org/en/7.2.x/how-to/assert.html
* https://docs.pytest.org/en/7.2.x/how-to/assert.html#assert-details
=> Use a regular assert instead of unittest-style

openlibrary/templates/books/edit/edition.html, openlibrary/templates/books/edit/excerpts.html
Closes #5640 
Added documentation regarding what "first sentence" means in edit page. 
@RayBB created issue and lead
@seabelis vetted the copy for the clarification
=> add clarification regarding what first sentence means in edit page

openlibrary/plugins/importapi/code.py
Closes no issue
Fix
Currently it seems possible for promise items to create an edition with `publish_date="????"`. Promise items sometimes have dummy data of `????` filled in for `authors`, `publishers` and `publish_date`.
(I say 'seems' because I had trouble reproducing import of promise items and am basing the continued existence of this issue on reading the code and the best simulation I could do.)
This dummy data is then removed from `authors` and `publishers`, but not `publish_date`.
`map_book_to_olbook()` in [scripts/promise_batch_imports.py](https://github.com/internetarchive/openlibrary/blob/c0de1e96e438e3e7351d43bb4b152c5b8cade67f/scripts/promise_batch_imports.py#L-56-L60), adds dummy data to `authors`, `publishers`, and `publish_date` thus:
```python
'authors': [{"name": …
```
=> Stop promise items from creating editions with publish_date=????

openlibrary/macros/ReadingLogDropper.html, openlibrary/plugins/openlibrary/js/lists/index.js, static/css/components/read-statuses.less
Partially closes #7433
Feature
I goofed this up a bit by creating an implementation prior to any sort of UX decision. Lesson learned on that one. After hemming and hawing I decided to submit this as a possible stopgap. I understand that #7433 involves more.
This adds a 'Remove From Shelf' item to the Reading Log dropper that, when clicks, behaves as if someone clicked the `primaryButton` in the Reading Log dropper to remove an item from the shelf.
- Add an item to one of the `want-to-read`, `already-ready`, `currently-reading` shelves.
- Activate the dropper, select 'Remove From Shelf', and verify the item is removed from the shelf.
- Verify the same behavior while viewing an edition: http://localhost:8080/books/OL20431791M/Flatland_A_Romance_of_Many_Dimensions
- Verify the same behavior …
=> Add 'Remove From Shelf' option to Reading Log dropper

docker/covers_nginx.conf, docker/public_nginx.conf, docker/web_nginx.conf
Have other server names 404
Tested on ol-www0 with etc hosts, and worked
@mekarpeles @cclauss @samuel-archive
=> Configure nginx to only serve OL on correct server_name

openlibrary/plugins/openlibrary/js/lists/index.js, tests/unit/js/html-test-data.js, tests/unit/js/lists.test.js
Closes no issue
Feature
Adds unit tests for syncReadingLogDropdownRemoveWithPrimaryButton. This also helps get the JS unit testing threshold back over 16%. :)
`docker-compose run --rm web npm run test`
@cdrini
=> Add unit tests for syncReadingLogDropdownRemoveWithPrimaryButton

docker/README.md
Feature
I propose adding `--no-cache` to the "Fully Resetting Your Environment" section of the Docker `README.md`. I have had to use `--no-cache` a few times, including a few moments ago, and at the cost of perhaps a few minutes of CPU time, it may help people avoid Docker woes.
Anyway, just a proposal. :)
@cclauss
=> Add --no-cache when fully resetting the development environment

.pre-commit-config.yaml, pyproject.toml
`s == ''` can be simplified to `not s` as an empty string is falsey
* https://github.com/internetarchive/openlibrary/pull/7652#issuecomment-1469339549
% `ruff rule PLC1901`
Derived from the **Pylint** linter.
Message formats:
* `{}` can be simplified to `{}` as an empty string is falsey
=> Python linting: Ignore ruff rule PLC1901

CONTRIBUTING.md, conf/twa/README.md, docker/Dockerfile.oldev, docker/README.md, scripts/solr_restarter/Dockerfile, tests/screenshots/README.md
Closes #7671 
Fix
This disables the automatic NPM audit by adding `--no-audit` to:
- every reference to `npm install`, and
- every reference to `npm i`
```
❯ rg "npm i"
tests/screenshots/README.md
13:$ npm install --no-audit
CONTRIBUTING.md
112:npm install --no-audit
docker/Dockerfile.oldev
16:RUN npm install --no-audit
docker/README.md
158:- **Editing npm packages?** Run `docker compose run --rm home npm install --no-audit` (see [#2032](https://github.com/internetarchive/openlibrary/issues/2032) for why)
178:docker compose run --rm home npm install --no-audit
conf/twa/README.md
19:npm i --no-audit -g @bubblewrap/cli
scripts/solr_restarter/Dockerfile
7:RUN npm install --no-audit -g node-fetch@2
```
- `docker compose build --no-cache` to ensure the build works without relying on cache. …
=> Add --no-audit to npm install

scripts/affiliate_server.py
Closes #7569
Makes this thread automatically restart.
Adds logging which will appear in Sentry with `amazon_lookup()` for error isolation.
Adds stated logging for:
1. How many ISBN-10s are batched for processing
2. How many times does the `amazon_lookup()` thread dies?
* https://github.com/internetarchive/openlibrary/wiki/Deployment-Guide#recovering-from-restart-loops
* https://github.com/internetarchive/openlibrary/wiki/Recipes
* HOSTNAME="$HOSTNAME" docker-compose up -d --no-deps affiliate-server
Terminal 1
```
ssh -A ol-home0
docker ps  # Make sure affiliate_server is running
docker logs --tail 20 --follow openlibrary-affiliate-server-1
```
Terminal 0
```
ssh -A ol-home0
docker ps  # Make sure affiliate_server is running
cd /opt/openlibrary
git branch
git status
docker exec -it …
```
=> Affiliate server: Make amazon lookup thread a daemon

openlibrary/admin/numbers.py, openlibrary/book_providers.py, openlibrary/catalog/marc/fast_parse.py, openlibrary/catalog/marc/parse.py, openlibrary/catalog/marc/tests/test_parse.py, openlibrary/catalog/merge/names.py, openlibrary/core/edits.py, openlibrary/core/imports.py, openlibrary/core/models.py, openlibrary/mocks/mock_infobase.py, openlibrary/plugins/books/readlinks.py, openlibrary/plugins/openlibrary/code.py, openlibrary/plugins/openlibrary/infobase_hook.py, openlibrary/plugins/upstream/account.py, openlibrary/plugins/upstream/borrow.py, openlibrary/plugins/upstream/models.py, openlibrary/plugins/upstream/mybooks.py, openlibrary/plugins/upstream/tests/test_forms.py, openlibrary/solr/find_modified_works.py, openlibrary/solr/solrwriter.py, scripts/import_standard_ebooks.py
Closes #
[`ruff --fix`](https://beta.ruff.rs/docs/rules) enables us to clean up our code.  Not all rules should be fixed up but my sense is that these ones are OK.  I picked some rules that only have less than a handful of instances in our codebase.
ruff --select=B010,B011,C400,C406,C416,D208,D210,D211,PIE802,PIE807,PLR0402,PLR1711,RET501,UP031 --statistics .
```
1	B010   	[*] Do not call `setattr` with a constant attribute value. It is not any safer than normal property access.
1	B011   	[*] Do not `assert False` (`python -O` removes these calls), raise `AssertionError()`
1	C400   	[*] Unnecessary generator (rewrite as a `list` comprehension)
1	C406   	[*] Unnecessary `tuple` literal (rewrite as a `dict` literal)
3	C416   	[*] Unnecessary `list` comprehension (rewrite using `list()`)
2 …
```
=> Some miscellaneous Ruff fixes

static/css/components/illustration.less, static/css/components/work.less
Closes #4924
This PR fixes a z-index issue that occurs on the book detail page and (seems to be) specific to Safari.
This fix sets the `z-index` for the parent, and then sets the child to a negative `z-index` (relative to its parent context). This keeps the cover from jumping above anything while its animation effect is being painted and allows it to still be clickable.
1. To test, please make sure the browser you test in is a narrow enough viewport size to make the "Browse" menu overlap the book image.
2. Navigate to a book detail page.
3. Click the "Browse" menu.
4. With the "Browse" menu still open/expanded, hover your cursor over the book cover image.
5. Interacting via hover with the book cover image should trigger an animation, but the image should stay beneath the menu.
I was able …
=> Fix z-index book cover animation issue in Safari

openlibrary/plugins/openlibrary/js/goodreads_import.js, openlibrary/templates/account/import.html
Closes #7399
- Fix for missing read dates when importing Goodreads data.
- Fix the "Import N Books" title that wasn't updated when (un)checking checkboxes.
- Fix the progress bar not taking into account unchecked books in percent computation.
Nothing.
Open the browser at the `/account/import` page, select your Goodreads export, then click on import.
From there, play with checkboxes to see that the number of books-to-import is updated in real-time.
finally, run the import, and check any read book page to see the check-in date properly set.
The video of the title being updated:
https://user-images.githubusercontent.com/2033598/216003419-0e79b782-144b-4675-901b-956b52b4af99.mp4
The screenshot with calls to update the read date (it includes several books to cover all use case like unchecked …
=> Handle read date in the Goodreads importer

static/css/components/dropper.less
Closes #7005 
Changed the style of the Reading log dropper as requested
@jimchamp Created issue
=> change reading log dropper color

openlibrary/templates/home/welcome.html
Closes #5987 
Fix onboarding carousel inconsistent breakpoint that happens from screensize 1024px-1059px
**Previous**
**Current**
@tuminzee created issue
@jimchamp lead
=> fix onboarding carousel breakpoint

scripts/oldump.sh
Related to:
* #7581
* #7580
While we are trying to debug the issues above, it would be better for us to preserve the sitemaps.  We can manually delete the sitemaps after we have studied them and in any case this script will erase them before generating them.
=> Delete sitemaps before generating them, not after

.pre-commit-config.yaml, openlibrary/catalog/merge/merge.py, openlibrary/catalog/merge/merge_marc.py, openlibrary/core/lists/model.py, openlibrary/core/processors/invalidation.py, openlibrary/plugins/upstream/borrow.py, pyproject.toml, scripts/copydocs.py
Adds [ruff rules SIM](https://beta.ruff.rs/docs/rules/#flake8-simplify-sim) from [flake8-simplify](https://pypi.org/project/flake8_simplify/) to our testing with fixes for six instances:
% `ruff --select=SIM114,SIM116 .`
```
openlibrary/catalog/merge/merge.py:226:18: SIM114 Combine `if` branches using logical `or` operator
openlibrary/catalog/merge/merge_marc.py:302:22: SIM114 Combine `if` branches using logical `or` operator
openlibrary/core/processors/invalidation.py:91:9: SIM114 Combine `if` branches using logical `or` operator
openlibrary/plugins/upstream/borrow.py:586:5: SIM114 Combine `if` branches using logical `or` operator
scripts/copydocs.py:310:9: SIM114 Combine `if` branches using logical `or` operator
openlibrary/core/lists/model.py:382:9: SIM116 Use a dictionary instead of …
```
=> Combine if statements: ruff --select=SIM114,SIM116

scripts/sitemaps/sitemap.py
Related to:
* #7580
* Add logging so we can follow the process and know how many records are processed and retained in our sitemaps.
* Minor optimizations of using Python f-strings for speed.  https://www.scivision.dev/python-f-string-speed
=> sitemaps: Add logging to the generation process

docker-compose.production.yml
Closes #
filename | run on | in Docker container | purpose | last modified
--- | --- | --- | --- | ---
archive-webserver-logs | ol-home0 | covers_nginx | archive-webserver-logs | 2 years
mrtg | | | | 12 years
openlibrary.allnodes | ol-www1, | bare metal | Copy sitemaps | 2 years
openlibrary.ol_home0 | ol-home0 | cron-jobs | Monthly data dumps | 3 months
pg-backups | ol-home | bare metal | Backup postgres | 9 years
=> ol-www: Sitemaps are in /1/var/lib/openlibrary/sitemaps/

openlibrary/utils/__init__.py
Fixes #7070
Running `openlibrary.utils.get_software_version()` was printing the current git SHA to stdout but was not returning it as a str to the caller.  This change adds [`subprocess.run(capture_output=True)`](https://docs.python.org/3/library/subprocess.html#subprocess.run) to successfully capture the git SHA as a str and return it to the caller.
Closes #
=> Fix get_software_version() to properly captue the git SHA

openlibrary/templates/account/books.html, openlibrary/utils/dateutil.py, openlibrary/utils/tests/test_dateutil.py
Closes #7488
Automatically displays yearly reading goal banner on My Books page from 1 Dec to 1 Feb of the following year.
=> Display reading goal banner between Dec and Feb

docker-compose.production.yml, docker/Dockerfile.olbase, docker/ol-nginx-start.sh
Closes #7580
Add a second cron job to the `openlibrary_web_nginx` Docker container which runs on the host `ol-www0`.  This job runs at 8 pm on the first day of every month and pulls the newly created `sitemaps` from the host `ol-home0`.
On `ol-www0`...
rsync --version
docker exec -it openlibrary_web_nginx_1 bash # --> docker container
rsync --version
cd /sitemaps
ls
rm -r previous_sitemaps
rm rsync.log
apt-get update && apt-get install rsync  # https://internetarchive.slack.com/archives/GM13CHXBP/p1681428713708969
vi /olsystem/etc/cron.d/pull-sitemaps-from-ol-home0
> copy the line and modify the new line to start with `X * * * *` where X is an upcoming minute.
CRONTAB_FILES="/etc/cron.d/archive-webserver-logs /etc/cron.d/pull-sitemaps-from-ol-home0"
cat $CRONTAB_FILES | crontab -
crontab …
=> ol-www0: Add cron job pull-sitemaps-from-ol-home0

pyproject.toml
Lint for most [flake8-bugbear](https://pypi.org/project/flake8-bugbear) and [pylint](https://pylint.readthedocs.io) issues
Also, add per-file-ignores to prevent the addition of new bare exceptions to most Python files.
> A bare `except:` clause will catch SystemExit and KeyboardInterrupt exceptions, making it harder to interrupt a program with Control-C, and can disguise other problems.
* https://peps.python.org/pep-0008/#programming-recommendations
* https://pypi.org/project/flake8-blind-except
=> ruff: Add bugbear and prevent future blind exceptions

openlibrary/templates/type/edition/view.html
Closes #7784
Fix Sentry error https://sentry.archive.org/organizations/ia-ux/issues/35685 ; `work.edition_count` is `Nothing` because `work` is a redirect
- Before: Errors https://openlibrary.org/books/OL23244503M/Riding_freedom?v=6
- After: No error! https://testing.openlibrary.org/books/OL23244503M/Riding_freedom?v=6
Now displays an icon and the old work key, but links to the new work key: 
@cclauss
=> Fix work redirects in history causing i18n error

static/css/components/work.less
Closes #7754
Removes smooth scrolling from the site.  This was recently added, and doesn't play well with our navbar scroll handler.
=> Remove smooth scrolling

openlibrary/plugins/openlibrary/js/index.js, openlibrary/templates/account/ia_thirdparty_logins.html, openlibrary/templates/lib/header_dropdown.html, static/css/components/header-bar.less
This reverts commit 753a27b28fecc647d93b7de7a69f674bee53d105.
We've seen a dip in registrations and an increase in errors on infogami. Possibly related to this.
This was deployed on 03/30
Going to patch deploy on prod to see if it reduces the infogami errors.
=> Revert hamburger menu google sign in button

openlibrary/plugins/upstream/covers.py
Closes #7835
Prevents image uploads from patron's in the `read-only` usergroup.
While logged in as a member of the `read-only`usergroup:
1. Navigate to any book page.
2. Open the manage cover modal and submit a URL or image.
3. Ensure that the image isn't uploaded.
_Error message displayed after attempted `read-only` edit._
@seabelis
=> Prevent `read-only` patrons from uploading images

openlibrary/plugins/openlibrary/js/handlers/index.js
Closes #7782
Fixes bug where logged out patron can interact with star rating components.  Root cause of bug is the `event.preventDefault()` call in the `handleRatingSubmission` function, which cancels the redirect to the login page.
The star rating handler redirects to the login page if the request was made by a logged out patron.  This PR modifies the `fetch()` response handler such that redirect responses are honored.
While logged out:
1. Go to a page with a star rating component.
2. Attempt to rate a book.
3. Ensure that your are redirected to the login page.
1. Go to a page with a star rating component.
2. Attempt to rate a book.
3. Refresh the page.
4. Ensure that your rating was persisted.
=> Follow login redirect on logged-out star rating

scripts/promise_batch_imports.py
@judec reported that promise item crons may not be working. Investigation revealed the cron PYTHONPATH was not being set correctly. We add a line that is used by other crons to load the paths correctly.
=> Fix promise item import cron (path)

openlibrary/templates/history/comment.html, openlibrary/templates/history/sources.html
Closes #7755 
The broken import province footer for the promise item has been fixed, now the footer shows only one link ("https://archive.org/details/{import_batch_name}")
Search for specific books imported as promise items via OL number (e.g. OL45991226M).
@jimchamp
=> Only display link to import batch for promise item

openlibrary/templates/type/edition/view.html
Closes #7499
This PR is to update the page title to include the author's name. 
This PR does the following:
- get a list of authors
- if the list is present, append the name of the first author to the page title. Else, append an empty string
- Run `docker-compose up` to load the website on local
- Look up "Upon A Midnight Clear"
- Verify that the page title is {title of the edition/work} by {author}
- I was only able to test this with "work". When i load the website in my local, it only has one book: Upon A Midnight Clear. So I'm unable to test with "edition" or with book that doesn't have any author (if such book existed)
Verified that page title is using the form {title} by {primary author} 
@seabelis @jimchamp @RayBB
=> Add author to page title instead of date (#7499)

openlibrary/core/infobase_schema.sql
Adds DDL statements for Infobase tables and sequences.
This file is not referenced by any of our code.  It has mainly been added to aid us during disaster recovery events.
This SQL (excluding `/* */` style comments) is the result of the `get_schema` function: https://github.com/internetarchive/openlibrary/blob/757ee735d5a95716a8a4c59a354bbe8e9d784e22/openlibrary/core/schema.py#L7
N/A
=> Add `CREATE` statements for Infobase tables, sequences

static/css/components/dropper.less, static/css/less/colors.less
Changes My Books dropper's color to light grey.
_Search result, not on shelf_
_Search result, on shelf_
=> Restyle dropper

openlibrary/plugins/openlibrary/js/lists/index.js, tests/unit/js/lists.test.js
Closes #7855
Fix
This bug was occurring because `syncReadingLogDropdownRemoveWithPrimaryButton()` was unconditionally called by `initDroppers()`, and `syncReadingLogDropdownRemoveWithPrimaryButton()` anticipated that `dropper.querySelector('.readingLog')` would not be null. When it was null, things broke.
This PR:
1. makes `syncReadingLogDropdownRemoveWithPrimaryButton()` exit immediately if `dropper.querySelector('.readingLog')` is null, and
2. stops `syncReadingLogDropdownRemoveWithPrimaryButton()` from being called by `initDroppers()` when the dropper isn't for a reading log.
1. Visit an author profile page, e.g. http://localhost:8080/authors/OL20585A/Edwin_Abbott_Abbott.
2. Add the author to a list
3. Reload the page, as the bug was only present then, as it related to …
=> Don't sync the reading log dropper when .readingLog isn't present

openlibrary/plugins/books/readlinks.py
Closes #
Remove code that will always evaluate the same value regardless of the inputs.
=> ReadProcessor.get_item_status(): Remove unreachable code

scripts/deployment/deploy.sh
Closes: #4806
Closes: internetarchive/olsystem#74
* #4806
Our `openlibrary/olbase` Docker images on `ol-home0` are > 2GB each so let's automate the removal of older `openlibrary/olbase` images before creating a new one.  Avoid deleting any non-`openlibrary/olbase` images.
ol-home0% `docker image ls`
```
REPOSITORY           TAG           IMAGE ID       CREATED         SIZE
openlibrary/olbase   3e9f6f8       a35ff4dd787f   2 weeks ago     2.08GB
openlibrary/olbase   latest        a35ff4dd787f   2 weeks ago     2.08GB
openlibrary/olbase   <none>        fc631b6a6748   2 weeks ago     2.08GB
openlibrary/olbase   solr-next     940e72eb6d45   5 weeks ago     2.03GB
openlibrary/olbase   c69c9f4       85cc7bab78a7   8 weeks ago     2.03GB
<none>               <none>        059e9513dfb1   2 months …
```
=> Prune older Docker images during deployments

openlibrary/macros/FormatExpiry.html, openlibrary/macros/LoanStatus.html, openlibrary/plugins/upstream/borrow.py
=> make expiry relative and fix databar styling

openlibrary/templates/books/edit/edition.html
Closes #7265 
If the edition already has a title don't allow the field to be blanked. Uses HTML5 client side validation, namely the required attribute, to prevent the edition title from being removed entirely but still allows it to be edited.
Uses HTML validation as suggested by Mek on #7265.
- Testing with an edition that has an empty edition title, test that the form can be submitted without setting an edition title.
- Testing with an edition that already has an edition title,  check that the form can still be edited and the form submitted if the edition title unchanged.
- Testing with an edition that already has an edition title, ensure that the edit form cannot be submitted if the edition title has been removed completely.
=> If edition title already exists, make the edition title field required.

.gitpod.yml
Closes #7497
Automatically runs the watch commands when starting in Gitpod.
Feel free to edit this PR as needed before merging 👍 
PS: After this I'll work on #6939 :)
I didn't use concurrently because I didn't see examples of how to do that and I wasn't clear how to do that.
If someone would like to propose a nicer way to do this I'm open to it. But I figured this is a good point to start talking from.
Open this PR in gitpod and try making changes to css/js.
https://user-images.githubusercontent.com/921217/222598532-c8037bb3-6277-48df-9dbc-fc6fcc99c116.mp4
@cdrini
=> run watch commands when starting Gitpod

openlibrary/core/fulltext.py, openlibrary/plugins/openlibrary/home.py
Closes #7713
Previously, `fulltext_search` calls `format_book_data` with an ocaid which is causing `core.ia.metadata` lookups. However, these calls are unnecessary as the availability has already been fetched in bulk from IA using `get_availability_of_ocaids(ocaids)`
Looking through the other calls of `format_book_data`, it seems like `custom_ia_carousel` is indirectly calling `format_book_data` with `core.ia.metadata` lookups even though the availability is already fetched from IA via `lending.get_available`. Removing metadata queries on `custom_ia_carousel` should improve the loading of the home page!
Modified format_book_data so it can take an extra parameter defaulting to True which lets callers override the if statement for whether we fetch collections / ia.get_metadata.
Unable to …
=> remove metadata queries for books that has availability fetched from IA

openlibrary/macros/ReadingLogDropper.html, openlibrary/plugins/openlibrary/js/droppers/index.js, openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/js/lists/index.js, openlibrary/plugins/openlibrary/js/ol.js, openlibrary/templates/lists/dropper_lists.html, tests/unit/js/droppers.test.js, tests/unit/js/html-test-data.js
Closes #6530
Removed redundant `toggleDropper()` function.  This was interfering with other code in `ol.js` that toggled the droppers.  Droppers should now behave as they did before the list widget refactor.
`ol.js` seems to be a catch-all file that contains JS that was previously inlined.  I moved all dropper-related code from `ol.js` to a new `/droppers/index.js` file.
Since the `ol.test.js` only contained a test for the dropper, I have renamed the file `droppers.test.js`.
@DebbieSan 
@mekarpeles
=> Fix reading log dropdown toggling

openlibrary/components/LibraryExplorer/components/LibraryToolbar.vue, openlibrary/plugins/worksearch/schemes/works.py, openlibrary/plugins/worksearch/subjects.py, openlibrary/templates/search/sort_options.html
Adds rating and reading log options to search results pages and library explorer.
Also changes the default subject search order to be reading log count.
The UI on the search page is definitely non ideal and getting long ; longer term we should flatten this and put it in a drop menu of some sort. But don't have the time for that now.
@mekarpeles
=> Add rating, reading log to sort options

.pre-commit-config.yaml, pyproject.toml, requirements_test.txt
[Ruff](https://beta.ruff.rs) helps us to find Python __code complexity__ with five key rules:
* `C901` McCabe code complexity
* `PLR0911` Too many return statements
* `PLR0912` Too many branches
* `PLR0913` Too many arguments to function call
* `PLR0915` Too many statements
This pull request sets up ruff `per-file-ignores` for our three most complex Python functions:
```
"openlibrary/catalog/add_book/__init__.py" = ["C901", "PLR0912", "PLR0915"]
"openlibrary/catalog/marc/get_subjects.py" = ["C901", "PLR0912", "PLR0915"]
"openlibrary/solr/update_work.py" = ["C901", "E722", "PLR0912", "PLR0915"]
```
Doing so allows us to:
1. substantially lower our ruff `max-complexity`, `max-branches`, and `max-statements` thresholds to spot any new attempts to increase code complexity.
2. create new …
=> Use ruff to find Python code complexity

openlibrary/solr/data_provider.py, openlibrary/solr/update_work.py, openlibrary/tests/solr/test_update_work.py, pyproject.toml
Related to #7891 
% `ruff rule ASYNC100`
Derived from the **flake8-async** linter.
Checks that async functions do not contain blocking HTTP calls.
Blocking an async function via a blocking HTTP call will block the entire
event loop, preventing it from executing other tasks while waiting for the
HTTP response, negating the benefits of asynchronous programming.
Instead of making a blocking HTTP call, use an asynchronous HTTP client
library such as `aiohttp` or `httpx`.
```python
async def fetch():
urllib.request.urlopen("https://example.com/foo/bar").read()
```
Use instead:
```python
async def fetch():
async with aiohttp.ClientSession() as session:
async with session.get("https://example.com/foo/bar") as resp:
...
```
=> Async functions should not call blocking HTTP methods

openlibrary/components/MergeUI/MergeRowReferencesField.vue, openlibrary/components/MergeUI/MergeTable.vue, openlibrary/components/MergeUI/utils.js
Addresses #7608
This PR modifies the MergeUI workflow so that network errors when retrieving counts for lists, reading logs, and ratings don't block the entire merge process. Failures instead display a warning symbol to indicate that something has gone wrong, and the Super Librarian can make the decision whether to attempt a reload or continue with the merge.
Failures to load edition data continue to be blocking, as not having this data could create a bad merge.
Rather than throwing a JS alert on network errors, the relevant functions in utils.js now pass back an error value, which is handled by the Vue component.
Setup an arbitrary merge — the more works, the more likely you'll have failures. Unfortunately, the performance issue seems to be happening mostly in production, so this may be …
=> Make MergeUI work reference network errors non-blocking

openlibrary/macros/databarWork.html, openlibrary/templates/type/edition/view.html
Ensures that same WorldCat and affiliate links appear in both mobile and desktop views on the book page.  These links are now rendered in the `edition/view.html` template and passed to `databarWork`, as opposed to being rendered in both templates using potentially different data as inputs.
Before DRYing this code, price info was prepared in both templates using `page`.  The issue was that `edition or work` is passed to `databarWork` as `page`, while the `edition/view.html` `page` could be either and is missing the enrichments that `edition` and `work` undergo before being passed to `databarWork`.
Once this has been deployed to `testing`:
1. Navigate to a book page where the links are inconsistent between mobile and desktop views.
2. Ensure that the same WorldCat and affiliate links are …
=> Use same WorldCat and affiliate links in mobile, desktop

openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/js/lists/ListViewBody.js, openlibrary/templates/lists/lists.html
Closes #2468 (final subtask in this issue)
JS in `openlibrary/plugins/openlibrary/js/lists/ListViewBody.js` has been updated to handle the functionality that was previously inline in `openlibrary/templates/lists/lists.html`, and all inline JS has been removed.
There should be no visible change to the My Lists page after this update. To test that no functionality is broken, please:
* Visit My Lists (`/people/openlibrary/lists`)
* Verify that a "Delete this list" link appears for each list
* Upon clicking "Delete this list":
* Verify that dialog text is unchanged from current prod version
* Verify that "No, cancel" button successfully cancels the action and that "Yes, I'm sure" button successfully deletes the list
* Additionally, it would be good to run through the test cases in my previous …
=> Refactor lists template file to move inline JavaScript

openlibrary/core/fulltext.py, openlibrary/macros/BookPreview.html, openlibrary/macros/LoanStatus.html, openlibrary/macros/SearchResultsWork.html
Contributed towards fixing #7861 
What was happening is plugins/inside/code.py was calling the search/inside.tmpl which called macros/SearchResults which looped over each book/results doc and called macros/SearchResultsWork which was making calls to get_data_provider which was performing an ia.get_metadata lookup.
=> remove ia extra get_metadata calls

openlibrary/plugins/worksearch/schemes/tests/test_works.py, openlibrary/plugins/worksearch/schemes/works.py
Fix. Searches with field `edition_key` weren't working, because `edition_key` shouldn't include the `/books/` prefix, but `key` should.
This now works!
- Before: https://openlibrary.org/search?q=edition_key%3AOL10676534M&mode=everything
- After: https://testing.openlibrary.org/search?q=edition_key%3AOL10676534M&mode=everything
Also added a unit test to prevent regression.
=> Fix edition_key not working in search

static/css/components/read-panel.less
The ".more" class in the "li" tag on the "works" path for each book had a default cursor, which could lead the user to think there were no more links to be seen in that panel. As a result, more people would ignore clicking that button. You can see that button, for example, on the "works page" in the "Check nearby libraries" section for this [Harry Potter](https://openlibrary.org/works/OL82536W/Harry_Potter_and_the_Prisoner_of_Azkaban) book  (Screenshots below).
The "li" tag with ".more" class lacked of ```cursor: pointer;``` property. Some other similar tags in the same view, with similar styling, have the said property.
Tests were run to verify everything worked after changing the .less file as said in the guide with:
```sh
docker-compose exec web make test
```
Since it was just a css …
=> Fix cursor styling for better ux in nearby libraries pannel

pyproject.toml
Fixes `openlibrary/plugins/worksearch/schemes/works.py:254:9: PLR0915 Too many statements (71 > 70)`
% `ruff rule PLR0915`
Derived from the **Pylint** linter.
Checks for functions or methods with too many statements.
By default, this rule allows up to 50 statements, as configured by the
`pylint.max-statements` option.
Functions or methods with many statements are harder to understand
and maintain.
Instead, consider refactoring the function or method into smaller
functions or methods, or identifying generalizable patterns and
replacing them with generic logic or abstractions.
```python
def is_even(number: int) -> bool:
if number == 0:
return True
elif number == 1:
return False
elif number == 2:
return True
elif number == 3:
return False
elif number == 4:
return True
elif number == 5: …
```
=> pyproject.toml: Increase tool.ruff.pylint.max-statements to 71

openlibrary/core/imports.py, openlibrary/core/lists/model.py, openlibrary/core/processors/invalidation.py, openlibrary/coverstore/utils.py, openlibrary/mocks/mock_memcache.py, openlibrary/plugins/importapi/code.py, openlibrary/plugins/importapi/import_opds.py, openlibrary/plugins/importapi/import_rdf.py, openlibrary/plugins/importapi/metaxml_to_json.py, openlibrary/plugins/worksearch/schemes/works.py, openlibrary/tests/solr/test_update_work.py, pyproject.toml
% `ruff rule SIM105`
Derived from the **flake8-simplify** linter.
Autofix is sometimes available.
Message formats:
* Use `contextlib.suppress({exception})` instead of `try`-`except`-`pass`
---
% `ruff rule SIM300`
Derived from the **flake8-simplify** linter.
Autofix is sometimes available.
Message formats:
* Yoda conditions are discouraged, use `{suggestion}` instead
* Yoda conditions are discouraged
=> Simplify Python code with ruff rules SIM105 and SIM300

static/css/less/colors.less, static/css/less/z-index.less
Removes color and z-index Less variables that are no longer referenced in the codebase.
=> Remove unreferenced `less` variables

openlibrary/data/dump.py
Closes https://sentry.archive.org/organizations/ia-ux/issues/45005
The call to https://docs.python.org/3/library/logging.html#logging.Logger.error is halting the dump process as can be seen in the Sentry event above.  This PR converts to `log()` which will log the desired information but not halt the processing.
=> Use log() instead of logging.Logger().error() in dump.py

openlibrary/plugins/upstream/account.py
Fixes a case where for login json endpoint `ol_account` was being fetched using an empty email as opposed to the email matched by the `audit`.
=> Fix login json SFW

openlibrary/plugins/upstream/models.py
A fix for https://sentry.archive.org/organizations/ia-ux/issues/356335 which has happened seven times since [deploy-2023-05-23](https://github.com/internetarchive/openlibrary/releases/tag/deploy-2023-05-23).
Currently, `self.get_users_settings()` is returning `None` in rare instances, and then `None.get()` is raising an `AttributeError`.  This pull request recommends using `(self.get_users_settings() or {})` which will provide a dict in all cases.
`{}.get('safe_mode', "").lower()` will then return an empty str which means if there are no `user_settings` then there is no `safe_mode`.
=> If there are no user_settings then there is no safe_mode

openlibrary/templates/lists/lists.html
Closes #
Previously, `deleteType` was not being set if the patron visiting the `/lists` page was not the page's owner.  Now, `deleteType` will always have an assigned string.
1. Visit your own /lists page.  Does it work as expected?
2. Visit another patron's /lists page.  Does it also work as expected?
=> Fix public lists page error

openlibrary/catalog/add_book/__init__.py
Closes no issue.
Fix
This PR changes the re-import behavior such that the `publishers` field is only updated if the field is currently empty.
Currently an edition's publishers field is appended to, [which can result in duplication](https://openlibrary.org/books/OL46931415M/More_Scary_Stories_to_Tell_in_the_Dark?_compare=Compare&b=5&a=4&m=diff). This PR stops that.
I know there may be other factors at play, but it was a quick change so I figured I'd just submit a PR.
❯ curl -X POST http://localhost:8080/api/import -H "Content-Type: application/json" -H "Cookie: $OL_COOKIE" -d '{
"title": "Les noirs et les rouges",
"source_records": ["ia:lesnoirsetlesrou0000garl"],
"authors": [{"name": "Alberto Garlini"}],
"publishers": ["Gallimard"],
"isbn_13": "9782072702211",
"publish_date": "2001-01"
}' …
=> On re-import, only update 'publishers' if the field is empty

scripts/solr_builder/setup.py
`distutils` was deprecated in Python 3.10 and removed in Python 3.12 by [PEP 632](https://peps.python.org/pep-0632/) “Deprecate distutils module”.
https://docs.python.org/3.12/whatsnew/3.12.html#removed
=> The distutils module is removed in Python v3.12

openlibrary/templates/admin/spamwords.html
Follow-up for #7967
Updates instructions in the admin "Spam Words" page.  New instructions note that the spam words are, in fact, regex patterns.
=> Update instructions in admin "Spam Words" template

openlibrary/core/edits.py, openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/js/merge-request-table/index.js, openlibrary/plugins/upstream/edits.py, openlibrary/templates/merge_queue/merge_queue.html, package.json, static/css/components/merge-request-table.less, static/css/less/colors.less
Partially closes #6816. 
Feature. 
Adds dropdown menus to sort and filter merge queue records, specifically:
"""
Adding sort label / link which swaps the sort order from desc to asc
remember sort across requests / pages
defaults to desc
Merge Queue: Add UI dropdown to filter by submitter
remembers submitter across requests / pages
be able to filter submitters by string
Merge Queue: Add UI dropdown to filter by reviewer
remembers reviewer across requests / pages
be able to filter reviewers by string
"""
per Figma
This addresses #6816 by creating two new fields (a list of submitters and a list of reviewer) that are passed from the model to the controller. Changes to the sorting/filtering of the merge requests are handled by parameters in the GET request. Currently, the query filtering of …
=> adds sort, submitter, reviewer dropdown menus to merge queue

openlibrary/catalog/marc/marc_xml.py
https://sentry.archive.org/organizations/ia-ux/issues/362513 does not deliver clear data about the two asserted values so provide that information to ease debugging.
=> Improve AssertionError in openlibrary/catalog/marc/marc_xml.py

openlibrary/plugins/upstream/merge_authors.py, openlibrary/templates/merge/authors.html, static/css/components/merge-form.less
Closes #7259
Updates the merge author UI to reflect the current merge guidelines: the oldest record is listed first and automatically selected as the default record to be merged into. The author's OL number is displayed above the author name.
On this page: "search/authors?q=key%3A*&mode=everything" select multiple authors to merge. When you click 'Merge', it should list the oldest author as the default to be merged into, which you can verify by the OL number (will be the lowest OL number) that now shows above the author name.
Librarians
=> 7259/fix/update merge author UI

openlibrary/plugins/openlibrary/api.py, pyproject.toml
% `ruff rule B009`
Derived from the **flake8-bugbear** linter.
Autofix is always available.
Message formats:
* Do not call `getattr` with a constant attribute value. It is not any safer than normal property access.
=> ruff rule B009 Do not call  with a constant attribute value

openlibrary/solr/query_utils.py
Closes #7618 
I have expanded the `fully_escaped_query` function to include queries with single quotes.
Please note that this is a temporary fix for now as the luqum parser should be accepting single quote characters in the first place. I will try to make a PR on the https://github.com/jurismarches/luqum repo for this issue. 
This following query should no longer have an error:
https://openlibrary.org/search?q=Cornell+%2777%3A+The+Music%2C+the+Myth+and+the+Magnificence+of+the+Grateful+Dead+Show+at+Barton+Hall&mode=everything
No longer facing `IllegalCharacterError`
@cdrini
=> expand solr query escape flow to include single quotes

openlibrary/solr/data_provider.py
In #7902 , looks like there was one sneaky usage of process_stats left! Replaced the call to an equivalent fn I found in the codebase.
@cclauss
=> Fix deleted process_stats.get_db still in use!

bundlesize.config.json, openlibrary/plugins/openlibrary/js/autocomplete.js, openlibrary/plugins/openlibrary/js/edit.js, openlibrary/plugins/upstream/addbook.py, openlibrary/plugins/worksearch/autocomplete.py, openlibrary/plugins/worksearch/code.py, openlibrary/plugins/worksearch/tests/test_autocomplete.py, openlibrary/templates/books/author-autocomplete.html, openlibrary/templates/books/edit/edition.html, openlibrary/utils/__init__.py, package.json, static/css/components/form.olform.less, static/css/legacy-jquery-ui.less, static/css/page-user.less, tests/unit/js/SearchBar.test.js, tests/unit/js/autocomplete.test.js, tests/unit/js/droppers.test.js, tests/unit/js/editionsEditPage.test.js, tests/unit/js/jquery.repeat.test.js, tests/unit/js/readmore.test.js, tests/unit/js/search.test.js, tests/unit/js/setup.js, tests/unit/js/subjects.test.js
Closes #7805 . Preparation for list edit UI.
- DRY up the autocomplete endpoints
- Make it possible to reorder multinput autocompletes
- Added some python tests for the autocomplete endpoint
- Had to make some updates the way jquery was added into jest. Made it a global inside jest for easier testing. Otherwise testing the jquery-ui, which requires jquery already be at the global, kind of annoying.
- Note reordering does not work on touchscreens
Manually verified:
- autocomplete for authors, works, languages work when editing
- Reordering works for authors, languages
- Reordering covers still works.
=> Autocomplete refactor + add ability to reorder

openlibrary/i18n/it/messages.po
Related to #7986
`(username)` is used earlier on this line and also twice a few lines above.
@ormai Your review, please.
@cdrini Fixes https://sentry.archive.org/organizations/ia-ux/issues/363456
Closes #
=> Fix a variable name in the Italian translation

openlibrary/core/db.py
Added requested features of https://github.com/internetarchive/openlibrary/issues/7769
Hello! My name is Alex and I'm a student at the University of Michigan. For my final project for EECS 481 (Software engineering) I've been asked to make a contribution to an open source project hosted on github. Part of this assignment is to make a push request, so I've done so. Thanks!
Closes # https://github.com/internetarchive/openlibrary/issues/7769
Fixes warnings explaining that the default SQLite3 adapters for pythons's datetime module have depreciated as of Python 3.12 (first shown here: https://github.com/internetarchive/openlibrary/issues/7322#issuecomment-1380127796). This warning occurred when running unit tests on certain functions updating datetimes in the database. 
Adapted from: …
=> Added custom SQLite3 datetime converter

openlibrary/i18n/it/messages.po
I found a minor error in the Italian translation.
Since _read_ is both present and past tense there is ambiguity without the contest.
=> Fix translation error

openlibrary/templates/search/sort_options.html, openlibrary/templates/type/list/view_body.html
Closes #7809
Makes lists ordered by default, with an option to sort by last modified (which was the previous default, and still potentially useful for librarians who sometimes use these as "watchlists").
Manually confirmed on testing. The sort bar appears and lets you change the order.
=> Make lists ordered by default

openlibrary/macros/SearchResultsWork.html, openlibrary/templates/type/author/view.html
Closes # #7525
Feature - The work title of a book now shows on both the search results page and author page.
Search for a book/author, then visit their author page. The search results and their individual page will display the work title in each book. 
@bicolino34 @cdrini
=> work title now displays on author page

openlibrary/api.py, openlibrary/plugins/upstream/utils.py, pyproject.toml, requirements_test.txt, scripts/copydocs.py
Closes #
Add new Python linting rules from https://beta.ruff.rs/docs/rules/
```
"PERF",    # Perflint
"SLOT",    # flake8-slots
```
The `SLOT` fixes should save memory while increasing performance...
> The space saved over using [__dict__](https://docs.python.org/3/library/stdtypes.html#object.__dict__) can be significant. Attribute lookup speed can be significantly improved as well.
> -- https://docs.python.org/3/reference/datamodel.html#slots
```
openlibrary/api.py:284:7: SLOT000 Subclasses of `str` should define `__slots__`
openlibrary/api.py:289:7: SLOT000 Subclasses of `str` should define `__slots__`
openlibrary/plugins/upstream/utils.py:836:7: SLOT000 Subclasses of `str` should define `__slots__`
scripts/copydocs.py:135:7: SLOT002 Subclasses of `collections.namedtuple()` should …
```
=> pyproject.toml: Add newer ruff rules

docker/nginx.conf
Closes #8007 
Put this change on prod, and now the networks panel shows a reduced transferred size!
(Before transferred == size)
=> Also gzip javascript files

openlibrary/tests/core/test_unmarshal.py
Closes # ----
feature - tests for unmarshal method
Tests for the unmarshal method
run the tests of the project in the folder `docker`, run `docker compose exec web make test`
=> making tests for unmarshal method

.github/workflows/javascript_tests.yml, .github/workflows/python_tests.yml, openlibrary/tests/accounts/test_models.py, requirements_test.txt
Fixes #8023
test: method get from the class OpenLibraryAccount 
Testing
Run Automatizated Test, this test is for accounts/model.py
This PR covers the method get from the class OpenLibraryAccount test that is present on the accounts/model.py file, it simulates the web case when the backend is trying to return a OpenLibraryAccount object by searching it from username, email, link or key. The test is covering 100% of the method.
=> test: add OpenLibraryAccount test

openlibrary/plugins/importapi/tests/test_code.py, openlibrary/plugins/importapi/tests/test_code_ils.py, openlibrary/plugins/openlibrary/tests/test_home.py, openlibrary/plugins/openlibrary/tests/test_listapi.py, openlibrary/plugins/openlibrary/tests/test_ratingsapi.py, openlibrary/plugins/upstream/tests/test_borrow.py, openlibrary/plugins/upstream/tests/test_utils.py, scripts/tests/test_solr_updater.py
Use [`ruff rule F401`](https://beta.ruff.rs/docs/rules/#pyflakes-f) to find unnecessary imports in test files.  If the tests continue to pass then the imports are indeed unnecessary.  This process makes it clear that `add_languages` is an import that has useful side effects.
Should `openlibrary/plugins/upstream/tests/test_borrow.py` just be deleted?
=> Remove unnecessary imports from tests

openlibrary/catalog/marc/tests/test_marc.py
Migrate from class-based tests to function-based tests.
> ~# TODO: refactor to not use unittest~
Before and after: `5 passed, 1 warning in 0.11s`
* `docker compose run --rm home pytest openlibrary/catalog/marc/tests/test_marc.py`
=> Refactor test_marc.py to not use unittest.TestCase

openlibrary/data/dump.py
Closes #2609 creates a new dump file for lists.
I'm thinking it makes more sense to leave the user name in the key ; usernames and lists are both public after all? I think this will make things easier down the road as well, since solr will have to know how to link to these things.
Running `docker compose exec web scripts/oldump.sh $(date +%Y-%m-%d)` locally successfully generates a lists dump file.
@mekarpeles
=> Create lists dump file

openlibrary/core/models.py, openlibrary/plugins/openlibrary/code.py
Allows super-librarians to edit `yaml` files.
=> Allow super-librarians to edit type yamls

openlibrary/core/admin.py
Closes #7936
As discussed at https://github.com/internetarchive/openlibrary/issues/7936#issuecomment-1602849387 switching from graphite `hitcount` to `summerize` makes the graph match with 
https://graphite.us.archive.org/render/?min=0&template=plain&lineMode=staircase&areaMode=stacked&areaAlpha=0.5&yAxisSide=right&title=openlibrary+++Unique+IPs+per+day+++(uip_openlibrary)&hideLegend=true&target=cactiStyle(alias(summarize(sumSeries(group(stats.uniqueips.openlibrary)),%221day%22),%22openlibrary+++Unique+IPs+per+day+++(uip_openlibrary)%22))&colorList=00ff00&height=200&width=900&from=-28days
=> Correct unique visitor counts - Use graphite summerize, not hitcount

openlibrary/plugins/openlibrary/home.py
Invalidates cache entry for homepage if homepage fails to render.
=> Bust cache if homepage fails to render

.pre-commit-config.yaml, pyproject.toml, requirements_test.txt
[ruff v0.0.276](https://github.com/astral-sh/ruff/releases) adds:
* `PERF401` Use a list comprehension to create a transformed list
* `PERF402` Use `list` or `list.copy` to create a copy of a list
Let's temporarily disable these rules until we can provide proper fixes.
% `ruff .`
```
openlibrary/catalog/add_book/__init__.py:329:13: PERF401 Use a list comprehension to create a transformed list
openlibrary/catalog/marc/marc_base.py:46:17: PERF401 Use a list comprehension to create a transformed list
openlibrary/catalog/marc/parse.py:125:13: PERF401 Use a list comprehension to create a transformed list
openlibrary/catalog/marc/parse.py:486:21: PERF401 Use a list comprehension to create a transformed list
openlibrary/catalog/marc/parse.py:499:13: PERF401 Use a list comprehension to create a …
```
=> Disable new ruff rule PERF401

openlibrary/catalog/marc/parse.py, openlibrary/core/cache.py, openlibrary/plugins/upstream/account.py, openlibrary/plugins/worksearch/schemes/__init__.py, openlibrary/plugins/worksearch/schemes/authors.py, openlibrary/plugins/worksearch/schemes/subjects.py, openlibrary/plugins/worksearch/schemes/works.py, openlibrary/solr/query_utils.py, pyproject.toml
% `ruff --select=UP035 .`
```
openlibrary/catalog/marc/parse.py:2:1: UP035 [*] Import from `collections.abc` instead: `Callable`
openlibrary/core/cache.py:8:1: UP035 [*] Import from `collections.abc` instead: `Callable`
openlibrary/plugins/upstream/account.py:5:1: UP035 [*] Import from `collections.abc` instead: `Callable`
openlibrary/plugins/worksearch/schemes/__init__.py:2:1: UP035 [*] Import from `collections.abc` instead: `Callable`
openlibrary/plugins/worksearch/schemes/authors.py:3:1: UP035 [*] Import from `collections.abc` instead: `Callable`
openlibrary/plugins/worksearch/schemes/subjects.py:3:1: UP035 [*] Import from `collections.abc` instead: `Callable`
openlibrary/plugins/worksearch/schemes/works.py:5:1: UP035 [*] Import from `collections.abc` instead: `Callable` …
```
=> ruff rule UP035: Import from `collections.abc` instead: `Callable`

openlibrary/plugins/upstream/utils.py
Related: #8028 
Fix for a pair of errors introduced in #7998 that caused a template error when processing a work.
The two errors I introduced came about because of reliance on `if TYPE_CHECKING: ...` to get around circular imports errors. However, two of the items so imported were actually called, rather than merely being used for type checking. This PR fixes that.
I reverted #7998 rather than create a new PR to fix the two import errors because I couldn't decide on a good way to handle typing `process_version`, where one of the errors was introduced.
I opted here to use composition with `Protocol`, such that `process_version` will type check with model that satisfies the following interface:
```python
class HasGetKeyRevision(Protocol):
key: str
revision: int
def get(self, item) -> Any: …
```
=> Add type hints to upstream/utils.py

openlibrary/macros/ReadMore.html
Closes #7858 
Adds tab navigation to "Read more" and "Read less" elements on book overview page to improve a11y. 
Added `tabindex="0"` to Read more & Read less a tags within the ReadMore.html macro
1. Navigate to any book's overview page where summary is sufficiently long enough to show "Read more" element. 
2. Starting from the top of the page keep hitting tab until the "Read more" elements is selected.
3. Click "Read more" to display "Read less" element and repeat step 2.
@jimchamp
=> Add "Read more" and "Read less" elements to tab navigation

.gitpod.yml
Sometimes the repo will be at /workspace/openlibrary-1
@RayBB
=> Handle gitpod dynamic repo root

openlibrary/solr/update_work.py, pyproject.toml, requirements.txt, scripts/solr_builder/solr_builder/solr_builder.py, scripts/solr_updater.py
Closes #7891
Adds dependency https://pypi.org/project/aiofiles to enable async file IO to avoid blocking operations in our async functions.
% `ruff rule ASYNC101`
Derived from the **flake8-async** linter.
Checks that async functions do not contain calls to `open`, `time.sleep`,
or `subprocess` methods.
Blocking an async function via a blocking call will block the entire
event loop, preventing it from executing other tasks while waiting for the
call to complete, negating the benefits of asynchronous programming.
Instead of making a blocking call, use an equivalent asynchronous library
or function.
```python
async def foo():
time.sleep(1000)
```
Use instead:
```python
async def foo():
await asyncio.sleep(1000)
```
=> Python async functions should not call the sync function open()

openlibrary/plugins/upstream/models.py
Hyphenates the record's ISBN when generating a Wikipedia citation.
Adds a `get_isbnmask()` method to the model to return one masked (if possible) ISBN.
```
{{cite book|author=Lawrence Lessig |date=2008 |title=Remix |url=https://archive.org/details/remixmakingartco01lessrich |publication-place=London |publisher=Bloomsbury Academic |isbn=978-1-4081-1347-9 |oclc=263296519 |ol=24218235M}}
```
=> Hyphenate ISBNs in Wikipedia cite book templates

.pre-commit-config.yaml, .stylelintrc.json, package-lock.json, package.json, renovate.json, static/css/components/carousel.less, static/css/components/header-bar.less
`stylelint` 14 has a number of breaking changes, including the fact it no longer lints non-css by default. This PR relies on Node's `postcss-less` being installed.
Additionally, `stylelint-declaration-strict-value` requires implementing each fix on one's own, so this PR merely disables autofix.
There may not be a way to exactly map our old `stylelintrc.json` the format that `stylelint-declaration-strict-value` expects. This file should be reviewed.
Finally, `stylelint` 15 deprecated a number of rules we use, though they remain functional until the next major version.
See:
- https://stylelint.io/migration-guide/to-14/
- https://stylelint.io/migration-guide/to-15/
- https://github.com/AndyOGo/stylelint-declaration-strict-value#autofix-support
@cclauss
=> Preliminary changes for stylelint updates

openlibrary/core/db.py, openlibrary/plugins/upstream/account.py, openlibrary/plugins/upstream/tests/test_utils.py, pyproject.toml
% `ruff rule ISC001`
https://beta.ruff.rs/docs/rules/single-line-implicit-string-concatenation
=> Fix implicitly concatenated string literals on one line

.pre-commit-config.yaml, openlibrary/plugins/admin/services.py, openlibrary/plugins/upstream/borrow.py, scripts/sponsor_update_prices.py
[ruff v0.0.278](https://github.com/astral-sh/ruff/releases/tag/v0.0.278) adds ruff rule UP032.
```
openlibrary/plugins/admin/services.py:57:16: UP032 [*] Use f-string instead of `format` call
openlibrary/plugins/upstream/borrow.py:149:28: UP032 [*] Use f-string instead of `format` call
scripts/sponsor_update_prices.py:50:21: UP032 [*] Use f-string instead of `format` call
```
https://beta.ruff.rs/docs/rules/f-string/#f-string-up032
=> More Python f-strings

openlibrary/plugins/upstream/models.py
Closes #7943
Fix
- Patron edits an edition via `/books/OL123M/book_title/edit`
- Patron enters invalid LCCN.
- Page chokes on reload.
- Saving on this page goes through `SaveBookHelper` in `openlibrary/plugins/upstream/addbook.py`.
- This calls `self.edition.set_identifiers(identifiers)`, and an LCCN is one of the identifiers.
- `set_identifiers` is defined in the `Edition` model in `openlibrary/plugins/upstream/models.py`, and it calls `normalize_lccn` on the identifier when setting the object's LCCN.
- `normalize_lccn()` returns `None` for an invalid LCCN, and that's what leads to `null` in the template view.
- Because this all happens on the backend, the patron (1) has no idea their LCCN is invalid, and (2) no way to fix things once they've submitted the bad LLCN, unless they can use …
=> Don't set edition LCCNs to None

openlibrary/catalog/add_book/__init__.py, openlibrary/catalog/add_book/tests/test_add_book.py
Fix for `rec`s with `None` as the `authors` value.
`add_db_name` tries to iterate over `rec['authors']`, but sometimes `authors` has a value of `None`, as opposed to an iterable. This handles those cases.
See added tests in `pytest`, or just add a malformed `rec` such that `rec = {'authors': None}`.
@cclauss
=> make add_db_name handle an authors value of None

openlibrary/plugins/worksearch/autocomplete.py, openlibrary/templates/covers/manage.html, static/css/legacy-jquery-ui.less
Closes #8094  .
- Autocomplete now *boosts* results which have an exact match. They will now almost always show up-top.
- Fix work author autocompletes showing scrollbar if too many values.
- Fix subjects/top work missing from autocomplete
=> Fix recent autocomplete bugs

.github/workflows/ruff.yml
This was causing random failures in other PRs
=> Keep ruff at same version in gh action as repo

openlibrary/templates/lib/header_dropdown.html
Closes #8109
The badge which represents the count is originally a div tag and has been known to have invalid HTML issues as reported in #8109. I have replaced the div tag with span tag and there was no change in design when I ran it. Please review. 
Inspect the badge with your browser's dev tools. Now, the count is wrapped in span tag.
The "5" count is just a dummy count, used for testing.
=> bug: replaced div tag in header_dropdown.html with span

openlibrary/templates/site/head.html
Removes `meta` tag used for Alexa tracking.  The Alexa page ranking service is defunct.
=> Remove meta tag for Alexa

openlibrary/plugins/openlibrary/api.py
Closes #5949 
If 'bulk=True' is in the URL, every edition of the selected work will be deleted. The original functionality of returning an error remains for works with over 1000 editions if 'bulk=True' is not in the URL.
Currently there is no UI attached to this functionality. Testing can be done through running the following JavaScript in the browser:
```js
await fetch('https://openlibrary.org/works/OL24314717W/College_Ruled_Line_Paper/delete.json', {method: 'POST'})
```
=> Add capability to delete a work with over 1000 editions

openlibrary/templates/type/list/view_body.html
Currently it can appear at the top, above the description, which can be far away from the books it'll be sorting if the list description is long!
EG random list with description: https://testing.openlibrary.org/people/pierre_bachelot/lists/OL211236L/MUST_READ
=> Move list sort options to be under the description

.github/workflows/python_tests.yml, .github/workflows/ruff.yml, .pre-commit-config.yaml, openlibrary/catalog/add_book/__init__.py, openlibrary/catalog/marc/marc_xml.py, openlibrary/catalog/marc/parse.py, openlibrary/catalog/marc/tests/test_marc_binary.py, openlibrary/catalog/merge/names.py, openlibrary/catalog/utils/__init__.py, openlibrary/plugins/books/readlinks.py, openlibrary/plugins/upstream/addbook.py, openlibrary/records/driver.py, openlibrary/solr/update_work.py, openlibrary/tests/core/test_db.py, openlibrary/utils/bulkimport.py, requirements_test.txt, scripts/copydocs.py, scripts/solr_builder/solr_builder/solr_builder.py
Fixes #8125
Fixes #8129
% `ruff --statistics .`
```
8	RUF015 	[*] Prefer `next(...)` over single element slice
5	PLR1714	[ ] Consider merging multiple comparisons: `f.tag not in (data_tag, control_tag)`. Use a `set` if the elements are hashable.
4	PERF102	[*] When using only the keys of a dict use the `keys()` method
4	UP032  	[*] Use f-string instead of `format` call
2	UP037  	[*] Remove quotes from type annotation
1	SIM102 	[*] Use a single `if` statement instead of nested `if` statements
```
% `ruff --fix .`
```
openlibrary/catalog/marc/marc_xml.py:84:16: PLR1714 Consider merging multiple comparisons: `f.tag not in (data_tag, control_tag)`. Use a `set` if the elements are hashable.
openlibrary/catalog/merge/names.py:227:8: PLR1714 Consider merging multiple comparisons: `len_amazon not …
```
=> Upgrade to ruff v0.0.280

bundlesize.config.json, openlibrary/macros/databarView.html, openlibrary/plugins/openlibrary/js/autocomplete.js, openlibrary/plugins/openlibrary/js/edit.js, openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/js/jsdef.js, openlibrary/plugins/openlibrary/js/lazy-thing-preview.js, openlibrary/plugins/openlibrary/lists.py, openlibrary/plugins/upstream/code.py, openlibrary/plugins/upstream/utils.py, openlibrary/templates/books/author-autocomplete.html, openlibrary/templates/books/edit/edition.html, openlibrary/templates/jsdef/LazyAuthorPreview.html, openlibrary/templates/jsdef/LazyWorkPreview.html, openlibrary/templates/type/list/edit.html, openlibrary/templates/type/list/view_body.html, openlibrary/utils/__init__.py, static/css/components/form.olform.less, static/css/components/jquery.autocomplete.less, static/css/legacy-jquery-ui.less, static/css/page-list-edit.less
Closes #7808
- The "edit" button on your lists now lets you re-order or add works to the list
- New API: `/people/{USERNAME}/lists/add` endpoint let's you create a new list under your namespace
- e.g. (change the username to avoid permission issues)  https://testing.openlibrary.org/people/ScarTissue/lists/add?seeds=OL23553W
- You can only add works to a list from the edit page ; authors/etc display correctly (ish) , but can't be added from here
- Note admins can create lists under other users
- Future work:
- List edit page should support more than 100 book previews
- List edit page should show preview cards for redirects
- Go to one of your lists and try to edit it!
- NOTE: Because testing.openlibrary.org cache issues, you might not see your edits reflected immediately.
=> Ability to edit list item order + New lists/add UI-API

openlibrary/plugins/openlibrary/js/autocomplete.js, openlibrary/plugins/openlibrary/js/covers.js, package-lock.json, package.json, static/css/page-list-edit.less
Closes #905
~Blocked waiting on #8113~
- Also reduced the size of the reorder hit region for lists to make accidentally reordering less likely.
1. Try dragging around the covers here, or dragging them to the trash region: https://testing.openlibrary.org/works/OL257943W/A_Game_of_Thrones/manage-covers
=> Make reordering covers/authors/etc work on touch screens

openlibrary/catalog/add_book/__init__.py
Refactor.
Though this should be perhaps two PRs, with respect to `add_book.load()`, one commit fixes the type hints used for imports, as it was importing from `core.models` rather than `upstream.models`, as it should have been, and the other commit changes the `w` and `e` variables to `work` and `edition` respectively.
I know it has been that way for a long time, but as @cclauss has pointed out, it's idiomatic to use `e` for errors in Python. But then if changing `e` to `edition`, it looks a bit odd to have `w` instead of `work.
If only one of these commits looks mergeable, let me know and I can break it out separately.
This should have no functional changes. The import change only affects type hinting, and the variable rename was done using an IDE.
@cdrini 
@cclauss 
@hornc
=> Fix type hints and rename w and e to work and edition within load()

openlibrary/plugins/worksearch/languages.py
Closes #8133
Adds support for a 'limit' URL parameter to the existing /languages.json API call rather than being locked to 15 results only. Ex: /languages.json?limit=1000
Limit defaults to 15 in order to remain similar to the original behavior. Default is used if there is no limit provided or if an invalid limit is provided.
After pulling updated code and populating solr with some language data; navigate to localhost:8080/languages.json?limit=100 and verify that more than 15 results are returned.
@tfmorris @cdrini
=> Add 'limit' URL parameter to /languages.json API call

openlibrary/catalog/add_book/__init__.py, openlibrary/catalog/add_book/tests/test_add_book.py, openlibrary/catalog/utils/__init__.py, openlibrary/plugins/importapi/code.py, openlibrary/tests/catalog/test_utils.py
There's no issue associated with this, but it addresses some of the issues @seabelis raised in #open-librarians-g.
UNLESS the item is a promise item, for imports that go through load(), this PR:
- Stop imports prior to ~~1500 CE~~ 1400 CE from Amazon and BWB;
- Stop imports of AMZ/BWB source_records if the record has no ISBN.
- Stop import of books published in future years; and
- Stop imports of Independently Published books.
If an import is a promise item, based on the source record, these validations are *not* applied.
Additionally, these validations do *not* apply to books added via `/books/add`.
Feature.
The `load()` validation has been largely consolidated in its own function, `validate_record()`, in part because they're related, in part because `load()` has quite a lot going on …
=> load(): validate publish_date, no independent publishers, no amz/bwb without ISBN

openlibrary/templates/account/import.html
Closes #7924
Fixes error redirect on Goodreads book import when no file selected
Required attribute added to file input prevents bad submission from happening
Attempt import with no file selected
@jimchamp
=> Add required attribute to file input for Goodreads import

openlibrary/olbase/tests/test_events.py, openlibrary/plugins/openlibrary/tests/test_stats.py, openlibrary/tests/core/test_i18n.py, pyproject.toml
Ruff calls rule **B015** a `useless comparison` but I call it "Do not forget to `assert` in pytests."
Enable these tests have been passing but two of them actually fail when an `assert` is added.  Let's enable this rule.
% `ruff rule B015`
Derived from the **flake8-bugbear** linter.
Checks for useless comparisons.
Useless comparisons have no effect on the program, and are often included
by mistake. If the comparison is intended to enforce an invariant, prepend
the comparison with an `assert`. Otherwise, remove it entirely.
```python
foo == bar
```
Use instead:
```python
assert foo == bar, "`foo` and `bar` should be equal."
```
- [Python documentation: `assert` statement](https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement)
=> Ruff rule B015: Do not forget to assert in pytests

openlibrary/catalog/add_book/__init__.py, openlibrary/catalog/add_book/tests/test_add_book.py
Partially closes #7521
Fix.
This will add a description to a work or edition if:
- there is a description in the incoming record ("`rec`"); and
- there is no `description` field in the respective work or edition.
Currently, on re-import, if a work is missing a description and edition has a description, the description will be copied from the edition to the work.
However, if the incoming record ("`rec`") has a description and the edition does not, that data is ignored and not set on either the work or edition. This PR will addresses that by setting a description if the criteria above are met.
Would it make more sense to limit this change to apply _only_ when the incoming record has a MARC record?
Take a work or edition without a description, and re-import it from a record that has a …
=> Add description to works and editions on reimport if absent

openlibrary/catalog/add_book/tests/test_add_book.py
This merely fixes lingering references to old function names in the docstrings of a test.
In #7940 the 'match' functions that look for matching editions were renamed for clarity. `find_match()` became an 'umbrella' function that called three matching functions. With old and new names, they are:
- `early_exit()` -> `find_quick_match()`
- `find_exact_match()` -> `find_exact_match()` (no change)
- `find_match()` -> `find_enriched_match()`
@cdrini
=> Fix outdated references to early_exit() and find_match()

openlibrary/coverstore/code.py, openlibrary/olbase/events.py, openlibrary/plugins/openlibrary/lists.py, openlibrary/templates/lists/home.html, openlibrary/templates/lists/list_overview.html, openlibrary/templates/lists/preview.html, openlibrary/templates/lists/widget.html, openlibrary/templates/type/list/edit.html, openlibrary/templates/type/list/embed.html, openlibrary/templates/type/list/view_body.html
Closes #7810
Feature. Makes it possible to create lists on the global namespace. No real links in the UI yet, but this will be used to support series. 
- `/lists/add` is how you can create a new global list.
- All list APIs that work on `/people/USER/lists/OL123L` now also work on `/lists/OL123L`
Use the little UI to try to extract a series from open library edition data! https://codepen.io/cdrini/full/xxQNbgZ
=> Allow lists at global level (eg /lists/OL123L)

static/css/components/mybooks-details.less, static/css/components/mybooks-menu.less
Closes #8156 
Borders on tops of the showcase section headers in My Books mobile instead of bottoms, clarifies delineation between book showcase sections. Also adds border to bottom of each menu section for self-contained look
Just some small CSS changes (border-bottom now border-top, adding bottom borders to sidebar-section class on My Books Mobile, changing padding to margin so borders are in right place)
View My Books mobile with books added to some reading logs
@cdrini @mekarpeles @jimchamp
=> border fixes for my books mobile showcase section divisions

.github/workflows/ruff.yml, requirements_test.txt
Aligns with `.pre-commit-config.yaml` which contains:
```yaml
- repo: https://github.com/astral-sh/ruff-pre-commit
rev: v0.0.285
hooks:
- id: ruff
```
=> ruff v0.0.285

openlibrary/utils/__init__.py
https://github.com/internetarchive/openlibrary/pull/8187#pullrequestreview-1587935577 If `git rev-parse --short HEAD --` fails then return "unknown" as the version number.
Closes #8211
@badlektor
=> git rev-parse --short HEAD

openlibrary/plugins/upstream/addbook.py, openlibrary/templates/books/add.html, openlibrary/templates/books/author-autocomplete.html
Closes #8161
Fixes the add book page by rendering all authors when creating a new edition for a work with more than one author.
Only the first author was passed to [templates/books/add.html](https://github.com/internetarchive/openlibrary/blob/6f755aee7115c668ae3ce078a4209ecd7a400cb5/openlibrary/templates/books/add.html#L39) from [upstream/addbook.py](https://github.com/internetarchive/openlibrary/blob/6f755aee7115c668ae3ce078a4209ecd7a400cb5/openlibrary/plugins/upstream/addbook.py#L201). Updated addbook.py to pull all authors and pass them instead since [templates/books/author-autocomplete.py](https://github.com/internetarchive/openlibrary/blob/6f755aee7115c668ae3ce078a4209ecd7a400cb5/openlibrary/templates/books/author-autocomplete.html#L28) was already attempting to render a list of …
=> Fix list of authors rendering only first author when creating a new edition

scripts/dev-instance/dev_db.pg_dump
Supplement #7928 
Recreates our development `pg_dump` file after adding the Tag-related tables and new Infogami type.  These additional tables and entries are required in order for Tags to be created and viewed in local environments.
New `pg_dump` file was created by executing the following commands:
```
docker compose exec -uroot web bash
./scripts/dev-instance/create-dev-db-pgdump.sh > scripts/dev-instance/dev_db.pg_dump 
```
DB container was removed completely before adding the new tables, creating the Tag Infogami type, and generating the updated dump.
DDL for the new tables, sequences, and indices was copied from [this commit](https://github.com/internetarchive/openlibrary/commit/a31e3c1a7d61eb720b0e483100f977a9026afa2c#diff-23da12f4c2d12d8edbff5eb7dc5537e161f3729ff0f33c7ae88ffa465448 …
=> Add Tag tables and metadata to development `pg_dump` file

openlibrary/accounts/model.py
Closes #8179
In ~2016 or 2017 when we switched from Open Library authentication to archive.org auth via the xauthn bridge, we somehow dropped a codepath which set/updated the `last_login` value on the patron's Open Library account. This adds back a `last_login` set in the `audit` authentication path.
Minimal test:
```
import web
import infogami
from openlibrary.config import load_config
load_config('/olsystem/etc/openlibrary.yml')
infogami._setup()
from infogami import config;
a = OpenLibraryAccount.get(email='michael.karpeles@gmail.com')
a['last_login'] = '2023-08-17T08:22:28.788221'  # for example
a._save()
```
@jimchamp
=> set last_login on login

.github/workflows/python_tests.yml, pyproject.toml
Ensure GitHub Actions are testing on the same version of Python as production.
* https://github.com/actions/setup-python/releases/tag/v4.7.0
```yaml
- uses: actions/setup-python@v4
with:
python-version-file: pyproject.toml
```
Arrgghh...
```
Run actions/setup-python@v4
with:
python-version-file: pyproject.toml
check-latest: false
token: ***
update-environment: true
allow-prereleases: false
Extracted ~=3.11.1 from pyproject.toml
Installed versions
Successfully set up CPython (3.11.4)
```
@dariocurr I would like to leverage actions/setup-python#669 to set `project.requires-python` in `pyproject.toml` to exactly match `3.11.1` so that our GitHub Actions are testing on the same version of Python as [production](https://github.com/internetarchive/openlibrary/blob/master/docker/Dockerfile.olbase …
=> pyproject.toml: project.requires-python = ">=3.11.1,<3.11.2"

openlibrary/templates/admin/spamwords.html
Updates copy on spam words page to provide guidance for adding a domain to the spam words list.
=> Update instructions on spam words page

openlibrary/plugins/openlibrary/js/utils.js
The JS `cond` function is only called in the books/edit/excerpts.html template.
=> Update `cond` comment

static/manifest.json
Closes #8197
This will make it so if someone highlights text on their phone and hit's share they have the option to share it to OL (if they have the PWA installed).
Just following the guide here: https://developer.chrome.com/en/articles/web-share-target/
`"text": "q"` is so that the text shared has a `q` query param which is what our search page uses.
This doesn't work if you "Install" the PWA from FF or Safari but you can happily share from them if you use install the pas via other browsers.
https://developer.mozilla.org/en-US/docs/Web/Manifest/share_target#browser_compatibility
PWAs need to be installed on https so can we please put this on the OL test env?
However, I created my own PWA to play around with the APIs so I'm confident this will work.
<details>
<summary>Video of it working …
=> add share_target for progressive web app

openlibrary/catalog/add_book/__init__.py, openlibrary/catalog/add_book/load_book.py, openlibrary/catalog/add_book/tests/test_add_book.py, openlibrary/catalog/add_book/tests/test_load_book.py, openlibrary/plugins/importapi/code.py, openlibrary/plugins/upstream/utils.py
Closes #7521 
Feature
If successful, this PR will overwrite v1 promise items with MARC data. After #7490 became a mess, I am trying to more targeted approach to get a PR through to address #7521.
This is a work in progress.
=> add_book.load(): add function to overwrite v1 promise items with MARC data

openlibrary/coverstore/README.md, openlibrary/coverstore/archive.py, openlibrary/coverstore/code.py, openlibrary/coverstore/schema.sql, openlibrary/coverstore/tests/test_archive.py
Archival utility to fetch covers in batches
Closes #7257 
- adds basic tests
- adds CoverDB handler to fetch and check batches
- adds ZipManager in addition to TarManager
- extends and simplifies archive() to use ZipManager and CoverDB
- DRYs get_filepath and get_filename logic for computing zip file names / locations
- updates README with info on historical imports
- updates schema.sql
- updates code.py to support zips in covers_0008
- adds hook for checking pending zips
- migrates from tar to zip
- moves deletion functionality from archive() to finalize()
- updates code.py so anything uploaded > cover.id 8M redirects to archive.org
On `ol-covers0`, `docker exec -it  openlibrary-covers-1 bash` run the magic incantation to get set up
```python
from openlibrary.coverstore import config …
```
=> Replace covers TarManager with new ZipManager

openlibrary/templates/account/create.html, openlibrary/templates/lib/header_dropdown.html, openlibrary/templates/lib/nav_head.html, openlibrary/templates/login.html, package-lock.json
Closes #8219
Fixes logout not working for these pages:
-     https://openlibrary.org/account/create
-     https://openlibrary.org/account/login
=> Fix broken logout link in create.html and login.html

scripts/dev-instance/dev_db.pg_dump
In support of #8202
Adds Storygraph, Youtube, and Amazon author identifier configurations to the `pg_dump` file which is used to initially populate DBs in developer environments.
**Edit:** Additionally, adds a Wikidata identifier to Mark Twain's author record.
Steps taken when making this update:
1. Remove local DB container by running `docker container rm openlibrary-db-1`
2. Populate DB with initial load by bringing the application back up: `docker compose up`
3. Verify that DB has been recreated by visually inspecting the results of `select * from thing order by id desc limit 10`
4. Update the author configuration via http://localhost:8080/config/author.yml?m=edit
5. Confirm that new entries are present in the "Identifiers" dropdown (found on author edit pages)
6. Add Wikidata ID to …
=> Add author configs to `pg_dump` file

openlibrary/macros/SearchResultsWork.html, openlibrary/plugins/worksearch/code.py, openlibrary/templates/work_search.html, static/css/components/search-result-item.less
Closes #7850, cleans up git history
From #7850:
Follow-Up to PR #7775 and Issue #7416 (part 2) to blur covers containing nsfw content.
This PR implements the blurring functionality of the opt-in safe-mode feature. Books tagged as nsfw/containing inappropriate content via a `content_warnings:*` subject will have their covers blurred if the user has enabled Safe Mode in 'Manage Privacy and Content Moderation Settings' on the Settings page. 
When Safe Mode is enabled, an `sfw` cookie is set to 'yes' and a list of subjects is retrieved  when a search is entered. If a `content_warnings:*` subject is present for that book, a blurred book cover appears else the original book cover is displayed. This also works for the small book previews as shown in the screenshots. 
1. Go to …
=> Ossd s23 7416/feature/safe mode

openlibrary/components/AuthorIdentifiers.vue
Closes #8202
Autodects ASIN, Youtube and storygraph identifiers on the Author edit page.
Pasting in (or typing) one of the above ids should automatically set the dropdown to the appropriate id type. Wikidata and ISNI types should continue to be detected.
One note for testing, if the contents doesn't change, the code isn't triggered, so if you paste in a storygraph id, manually change the type of id in the selector to something else, then paste in the exact same storygraph id then it'll not do anything. Not an issue for real users but something that testers might do and wonder if it is a bug.
=> autodetect author ASIN, Youtube, storygraph ids

openlibrary/templates/merge_queue/merge_queue.html, static/css/components/merge-request-table.less, static/css/less/colors.less
Closes #
Adds new color for merge requests that have been merged.
=> Merge request table : Add new status dot color for merged requests

openlibrary/plugins/openlibrary/js/add-book.js, openlibrary/plugins/openlibrary/js/edit.js, openlibrary/plugins/openlibrary/js/idValidation.js, openlibrary/templates/books/add.html, openlibrary/templates/books/edit/edition.html, tests/unit/js/editionsEditPage.test.js, tests/unit/js/html-test-data.js, tests/unit/js/idValidation.test.js
Closes #8092
Adds front-end validation and normalization for Library of Congress Control Number (LCCN) ID types within edit edition and add book forms. Previously the invalid LCCNs were silently dropped after submission. This feature normalizes the IDs on add and validates correct format according to the guidelines found [here](https://www.loc.gov/marc/lccn-namespace.html), [here](https://www.loc.gov/marc/lccn_structure.html), and [here](https://www.oclc.org/bibformats/en/0xx/010.html) as well as the existing python LCCN validation in [lccn.py.](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/utils/lccn.py) New error messages have also been added to notify the user that an incorrectly formatted LCCN has been entered.
Validation has been added in the JavaScript that …
=> Add Library of Congress Control Number format validation

openlibrary/core/edits.py, openlibrary/plugins/upstream/edits.py, openlibrary/templates/merge_queue/merge_queue.html
Closes #8195
Adds "Status" filter to merge request table when selected mode is not "open".  This filter allows librarians to filter closed requests that have been "Merged" or "Declined"
Ensure that the new filter is not rendered when `mode` is `open`.
Ensure that the new filter is present when perusing "Closed" requests.
Ensure that the filter works properly.
=> Add "Status" filter to merge request table

openlibrary/plugins/openlibrary/js/index.js
Noticed that we were always importing the dismissible banner `js` code, as empty arrays (or, in this case, array-like objects) are truthy.  This PR corrects the issue.
@mekarpeles
=> Fix banner import bug

openlibrary/plugins/worksearch/code.py, openlibrary/plugins/worksearch/schemes/editions.py, openlibrary/plugins/worksearch/schemes/works.py, openlibrary/templates/work_search.html, pyproject.toml
Feature to help with #8170 
Adds a new parameter, `editions.sort` to sort the editions displayed for each work (hence helping boost a specific edition)
- Also add new (API only) sort option: `ebook_access` to sort by most available.
Examples:
- Newest editions of English horror books: https://testing.openlibrary.org/search?q=subject_key%3Afiction_horror+language%3Aeng+-publisher%3A%22Independently+published%22&mode=everything&editions.sort=new
=> Add option to sort editions in search

openlibrary/macros/LoanStatus.html, openlibrary/macros/ReturnForm.html, openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/js/return-form/index.js
In support of #4474
Moves inline `js` for our book return forms.  This javascript is responsible for displaying the confirmation dialog that is displayed whenever a book is returned.
I tested this by checking out multiple books, navigating to the loans page, and clicking each of the return book buttons.  Afterwards, I refreshed the page to verify that the books were all returned.
=> Remove inline JS for return forms

docker/Dockerfile.olbase, scripts/install_nodejs.sh
Closes #8255 
Needed as the old install method is deprecated.
This PR just follows the exact method they recommend for installing.
Works pretty seamlessly on my machine and gitpod.
@cclauss 
Also @cdrini you might like this making the build/deploy process go about 60 seconds faster :)
=> update node install method

docker/Dockerfile.olbase, scripts/install_openresty.sh
Closes #6316
I want to be able to build on my m1 mac and this fix enables that.
Solution based on discussion in the issue above.
`TARGETARCH` wasn't working so I went with `uname -m` which seems to be a common solution.
It works on my m1 mac. I also tested it on gitpod and had no problems.
But ultimately openresty isn't used for dev so someone will need to check it on testing to be sure.
Run `docker build -t openlibrary/olbase:my-test-label -f docker/Dockerfile.olbase .`
@cdrini @cclauss
=> add ARM64/M1 support for building olbase image

tests/unit/js/realtime_account_validation.test.js
DRYs recently added realtime account validation unit tests by adding a nested `beforeEach` call.  Renamed some variables.
@vnsrz
=> DRY account validation unit tests

openlibrary/plugins/openlibrary/js/edit.js, openlibrary/plugins/openlibrary/js/idValidation.js, openlibrary/plugins/upstream/models.py, openlibrary/templates/books/edit/edition.html, tests/unit/js/html-test-data.js
Closes #8281 
Implements the new de-dupe function for the edit edition page that accepts any identifier type.
- Add a valid identifier of any type
- Attempt to add the same identifier for each type
- Duplicate identifiers will be rejected with an informative error message
- Duplicate identifier values of different Id types will be able to be added
- Eg. 1234567890 for ISBN 10 and 1234567890 for LCCN is allowed
LCCN
ISBN 10
@scottbarnes
=> Add generalized de-dupe for ISBN and LCCN for edit edition form

openlibrary/coverstore/archive.py
This allows us to run archival (starting at whatever the current/next record is) to any desired end_id, which allows us to process more records at a time. This is different than `limit` which has no way to guarantee our ending point is the logical end of a batch, (e.g. a number like 8,110,000)
=> ability to specify end_id for archival run

openlibrary/components/MergeUI.vue
this.isSuperLibrarian() -> this.isSuperLibrarian
Just like we use in the rest of the file.
Was found as an issue via the updated linter #8312
https://eslint.vuejs.org/rules/no-use-computed-property-like-method.html
Not sure if it was actually causing a bug. But I figured we should pull it into a separate PR to avoid extra discussion there.
@jimchamp can you please check this one? (Since this was your code in #6920)
=> use prop in correct way for mergeUI

openlibrary/templates/account/books.html
Closes #8304
Add an 'Imports and Exports' option to the MyBooks navigation dropper. Previously the dropper had no option for the imports/exports page and the dropper showed an empty value.
Login and navigate to to MyBooks page. Verify that the 'Imports and Exports' value is displayed in the navigation dropper when on the imports/exports page and verify that selecting 'Imports and Exports' send the user to the proper page (account/import).
@jimchamp
=> Add Imports and Exports option to MyBooks page dropper

openlibrary/plugins/openlibrary/js/goodreads_import.js
Closes #8158 
Fixes the bug wherein an unchecked or custom shelved book causes the entire import to fail
Replaced  'return false' in the unchecked or custom shelf condition with a 'return'. This statement was causing the code to break out of the loop entirely when the condition was encountered
1. Go to ... import options.
2.  Do ... try to import Goodreads data containing a custom exclusive shelf, or an unchecked book
The bug should be fixed, and the import completes with error messages
@jimchamp
=> Fix goodreads custom shelf bug

openlibrary/plugins/importapi/code.py
Related: #8290 #8289 
Fix
Currently `ia_import()` in the import API does not use Open Library edition IDs from Internet Archive metadata because it is using the wrong field -- `metadata['openlibrary']` instead of `metadata[openlibrary_edition]`.
This PR fixes that, and ensures we won't make a new edition when trying to import an IA record. Additionally, it avoids at least two further database calls that would have been made in an attempt to find a match.
Try to import an IA record and see that 'step 2' now works as intended and gets the existing Open Library edition ID from the Internet Archive metadata, rather than relying on finding a match by searching the Open Library database.
```
❯ http POST http://localhost:8080/api/import/ia identifier==007exoticlocatio0000arno Cookie:$OL_COOKIE …
```
=> import api: use edition ID from IA metadata if it exists

openlibrary/plugins/openlibrary/js/covers.js, openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/js/utils.js
The `closePopup()` JS function is used to close Colorbox modals.  Since there are no references to `closePopup` in our templates, it seems appropriate to remove this function from the global `window` object.
=> Remove `closePopup()` function from global `window` object

openlibrary/plugins/worksearch/autocomplete.py
Closes #8344
Restores the sorting by work count that existing in the subjects and authors autocomplete before the autocomplete refactoring.
This fix adds an optional sort attribute to the autocomplete base class, and populates that with a work_count sort for the subject and author subclasses.
On a work editing page, type author and subject names in the appropriate fields and observe that the choices are ordered by work count, descending. Other autocompletes (languages and works) should be unaffected.
@mheiman, @cdrini, @seabelis
=> Restore work_count sort to subjects and authors

scripts/deployment/are_servers_in_sync.sh
Part of #8361
Tested on ol-home0
=> Make are_servers_in_sync output emptyline if no olbase

openlibrary/plugins/upstream/addbook.py, openlibrary/templates/type/author/edit.html
Closes #8183 
Alternate names are separated by newlines instead of semicolons for easier editing.
Go to the author edit page, add and remove values separated by newlines and save to verify results.
@cdrini
=> Switch alternate names editor delimiter to newline instead of semicolon

openlibrary/macros/ListCarousel.html, openlibrary/macros/QueryCarousel.html, openlibrary/templates/books/custom_carousel.html, static/css/components/carousel.less
Closes #7778 (or at least provides an alternative way for librarians to achieve their goals)
feature: add grid_mode=True to the Carousel macros to get a grid view instead.
1. this basically ignores the load_more code path. So you need to load your full grid in one go.
2. I've not tested in IE11, but it should be relatively simple to tweak the grid stuff to work if there's issues. Might just need `display: -ms-grid;` but not sure if prefixing is already automated in webpack.
Find/create a page with a Carousel macro and add `grid_mode=True` e.g.
```
{{ListCarousel("/people/openlibrary/lists/OL1L", limit=20, has_fulltext_only=False, url='https://openlibrary.org/people/openlibrary/lists/OL1L', grid_mode=True)}}
```
@cdrini, @digitals82
=> add a grid mode to the carousel macro

openlibrary/macros/TypeChanger.html, openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/js/type_changer.js, static/css/page-edit.less
Contributes to #4474 
I was investigating moving the JS to be inline but couldn't figure out how the functionality works.
Turns out it didn't work at all. Perhaps because the code is [12 years old](https://github.com/internetarchive/openlibrary/blame/35d6b72c7851f260d673fbcd9ce3f95b0e9c3169/openlibrary/macros/TypeChanger.html#L21) and not used too frequently.
This PR makes the code actually work and moves it away from being inline js.
thinginput comes from [here](https://github.com/infogami/infogami/blob/3e9357c0184cd51921e198762c9f7d03b4589cf1/infogami/utils/view.py#L185-L195). It doesn't seem to pass the "onclick" field currently, hence the code wasn't working.
See video
https://github.com/internetarchive/openlibrary/assets/921217/b2c2d172-7faf-444e-852c-9867bf6169a9
@jimchamp are you …
=> fix TypeChanger bug

openlibrary/catalog/add_book/__init__.py, openlibrary/catalog/add_book/tests/test_add_book.py
Closes #8351
The PR makes a statement that no created record from any source should have a future date.
Most records with future dates will fail to import because of the validation step. Records from sources that are exempt from validation, like bwb promise items, will have certain fields checked/pruned during the normalize stage. 
All API imports (I'm not sure about /addbook though, which does have front-end validation) seemingly go through https://github.com/internetarchive/openlibrary/pull/8367/files#diff-2f9a6b1879442fc58af3064df91b70cd3138d6da15003d0d3127ecf05098386cL975-R997. Everything goes through `validate` _unless_ (currently) it's a promise item, in which case `validate` is skipped. Everything should go through `normalize` after, including promise items.
* This shouldn't be a …
=> Fix promise future dates

static/css/components/generic-dropper.less, static/css/components/mybooks-dropper.less
It has been bothering me for a while that the want to read button looks funny in the corners of the button.
It looks like this:
After my PR it looks like this:
PS: I set the width of the dropdown button to match the width of the listen button. But I'm not attached to that change.
<details>
<summary>screenshot of listen button.</summary>
</details>
Had to move the border radius code one level down to be able to hide overflow.
Did a few more small css cleanups while I was in there.
I explain more in the demo video below.
To see this change locally on search results you might need to enable `my_books_dropper` in `openlibrary.yml`
Demo and code walkthrough: https://www.loom.com/share/b571d2aefbf4443890f9a9a345f14646
Related to #8181 so I'll tag @jimchamp
=> fix mybooks-dropper overflow

conf/openlibrary.yml
This enables the My Books Droppers by default in local dev environments.
=> Enable My Books Droppers for devs

openlibrary/plugins/openlibrary/lists.py
Noticed we weren't setting the content-type for the seeds api in lists.
Relevant urls
http://localhost:8080/people/openlibrary/lists/OL1L.json - currently sets correct content-type
http://localhost:8080/people/openlibrary/lists/OL1L/seeds.json - doesn't currently set correct content type
Prod urls:
https://openlibrary.org/people/raybb/lists/OL235745L.json - sets content type
https://openlibrary.org/people/raybb/lists/OL235745L/seeds.json - doesn't
This PR fixes that.
See lomo
https://www.loom.com/share/a02c06360ce5422595daf078e5c1f99f
@cclauss maybe since you're more on the backend side.
=> set content type for list seeds json api

openlibrary/components/MergeUI.vue
When trying to build vue in development mode it was failing with an error (see below).
Turns out we had an unclosed div that the IDE was complaining about too.
The production mode was swallowing the error and browsers were probably making a lucky guess of where to end the div. 
Contributes to #7547 
Error I was getting
```
npx vue-cli-service build --no-clean --watch --mode development --dest static/build/components/prod
uction --target wc --name ol-MergeUI openlibrary/components/MergeUI.vue
⠋  Building for development as web component...
ERROR  Failed to compile with 1 error                                                                                          9:32:00 AM
error  in ./openlibrary/components/MergeUI.vue?vue&type=template&id=468bf6df&shadow
Module Error (from …
```
=> fix unclosed div in MergeUI

openlibrary/plugins/openlibrary/js/initTaggingSearchBar.js
Closes #8417
Ensures that the `workCountDiv`'s innerText is being set when a subject has more than 1,000 works.
Try adding a common subject to some works on testing.openlibrary.org
=> Fix bulk tagging count update bug

openlibrary/plugins/upstream/addbook.py
Closes #8422 
Prefills author name on add book page when adding a new work from the author page.
Go to an author's page. Select 'Add another?'. Verify that the author's name is already included in the author field for the new work. 
@mheiman @lephemere
=> Fix author not pre-filling on new work

docker/Dockerfile.oldev
Closes #8002
Fix
This adds a few packages globally to the local Docker development environment.
Obviously doubling packages is potentially pointless duplication, though it draws from the same source in `requirements.txt` and installs as few packages as possible.
This increases the size of `site-packages` on the development containers from 13 megabytes to 55 megabytes:
```
❯ docker compose run --rm -uroot home du -ch /usr/local/lib/python3.11/site-packages
...
55M total
```
Thoughts?
Before:
```
❯ docker compose run --rm -uroot home pip list                                                                                                                                                                                                                                              
WARN[0000] The …
```
=> i18n: install web.py and Babel globally

compose.production.yaml, scripts/pr_slack_digest.py
One of the pieces of feedback we went through was the staff PRs tend to often get stuck for long periods of time. To attempt to rectify this let's try a daily digest of staff PRs!
Note although all PRs would in theory be useful, there are just too many for a daily digest to help there.
- Corresponding olsystem changes: https://github.com/internetarchive/olsystem/pull/190
I've tested the script but not the cron-linking
=> Add daily PR slack digest for staff PRs

openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/upstream/mybooks.py, openlibrary/templates/account/readinglog_stats.html
Closes #8382 
Removes the inline JS from readinglog-stats.html. 
Passes data through data-config in html instead.
Go to reading log, verify that log stats display correctly.
@RayBB
=> Remove inline JS from readinglog_stats.html

openlibrary/catalog/get_ia.py, openlibrary/plugins/importapi/code.py, openlibrary/tests/catalog/test_get_ia.py
Fix.
Currently `ia_import()` will twice query the (memcached) Internet Archive API during the process for importing from an Internet Archive ID.
This PR passes the already-fetched `metadata` to the function that calls the metadata API again (`get_marc_record_from_ia()`), thereby avoiding the second call to the (memcached) API.
First, in "case 1", the metadata is gathered:
```
metadata = ia.get_metadata(identifier)
```
Once #8331 is merged, this will be the final query to the the IA metadata API, _if_ that IA record has data in the `openlibrary_edition` field. ("Case 2".)
However, if the IA record does not have data in `openlibrary_edition`, then there is a query for MARC data from the IA item, which calls `get_marc_record_from_ia()`, which again calls the metadata API:
```
metadata = …
```
=> get_marc_record_from_ia: use existing metadata if present

static/css/components/buttonCta.less
Closes #8376
Changed `white-space` to normal, but we could omit the attribute all together. `text-align` centered was just because everything else in that container is centered but I'm not hip to the design principles. 
I've been unable to replicate a waiting list in my local environment. I know borrowing is not possible in the local environment but not sure if I'm missing any contributor docs to mock the waiting list info or force it in the local db. It's a fairly small change so I checked against the prod site for now
This is on the live prod site, using Firefox developer tools to toggle / change `waitinglist-message`.
Before:
After:
@jimchamp
=> Change white-space to normal and text align center

bundlesize.config.json, openlibrary/macros/ReadMore.html, openlibrary/macros/TableOfContents.html, openlibrary/plugins/openlibrary/js/edition-nav-bar/EditionNavBar.js, openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/js/readmore.js, openlibrary/templates/site/head.html, openlibrary/templates/type/edition/view.html, static/css/base/helpers-common.less, static/css/components/header.less, static/css/components/read-more.less, static/css/components/toc.less, static/css/components/work.less, static/css/legacy.less, static/css/page-book.less, tests/unit/js/readmore.test.js
Closes #6171 
Feature. Redesign table of contents to be easier to read and better match our design aesthetic.
- refactor read-more component to support customizeable height
- read-more component now animates
- read-more component not doesn't cause as big a page-shift since it begins with the content collapsed
- ✅ Books with TOC:
- https://testing.openlibrary.org/books/OL7596598M/Digital_Photography
- https://testing.openlibrary.org/books/OL27371038M
- https://testing.openlibrary.org/books/OL26234146M
- ✅ Books without TOC: 
- https://testing.openlibrary.org/works/OL25312237W/Control_Your_Mind_and_Master_Your_Feelings
| ------- | ------- |
| ![image](https://github.com/internetarchive/openlibrary/assets/6251786/e1f8c427-ecb6-45c7-b0b4-7270543ed33b) | …
=> Redesign TOC on books page

openlibrary/plugins/upstream/addbook.py
fixes #7845, and adds case insensitive comparison
Closes #7845
feature to remove duplicate alternative names on save, maintaining sort order. Compares case insensitively, so the first appearing case-variant will win.
Possibly this change will be obsoluted by work on #8341
Find an author with duplicate alternate names, on save check that duplicates have been removed and that otherwise the list of alternate names is intact and in order.
=> remove duplicate author alternate names on save

static/css/components/editions.less, static/css/components/work-title-and-author.less, static/css/components/work.less
Closes #8323
Adds word break in two places, work and edition title (and same again in mobile view)when a word in the title exceeds the space available.
=> fix #8323 title work break

openlibrary/plugins/openlibrary/lists.py, openlibrary/plugins/openlibrary/tests/test_lists.py, openlibrary/plugins/upstream/code.py, openlibrary/plugins/upstream/utils.py, openlibrary/templates/type/list/edit.html
Closes #8245 . Closes #8246 .
Fix. Saving from the /lists/add endpoint was erroring when used with url parameters to pre-populate the form. This was because these url parameters would be forwarded along with the POST request when the form was submitted (since the `action` was unset on the form). The endpoint now checks the request body independently/separately (by default, `web.input()` combines data from both).
Fix. Global lists (eg `/lists/OL1L`) were erroring when edited due to the `?m=edit` → `/edit` rewrite rule not triggering, causing the endpoint to be handled by infogami instead of our custom code. Fixed the rewrite rule.
Fix. The `/edit` rewrite rule was erroring for users when a list had unicode characters in its url (see this [users unfortunate list …
=> Fix 500 when saving /lists/add with URL parameters + fix global lists editing

openlibrary/plugins/openlibrary/pages/config_edition.page
Closes #7824
Fix: fixes the url for the boston public library
@cdrini
=> Fixed boston public library url in config_edition.page

openlibrary/templates/site/body.html
I could have sworn I saw an issue for this, but now I can't find it anywhere.
The ILE blue bar appears on popups like the cover manager, when it should only show up on full pages. This PR adds a check to make sure this happens correctly.
Add some items to the blue bar, then (in the same tab) open the Manage Covers popup. Blue bar should not appear.
Before: 
After:
@mheiman @cdrini @seabelis
=> Hide ILE on pop-ups

static/.well-known/assetlinks.json
Thanks to @Yashs911 suggestion, this should fix the address bar in the TWA! ~Unable to test unfortunately.~
Note I included both certs, the old and the new one, since that's what the App signing page recommended. I reckon it's to support older versions of the app.
Patch deployed this, and no more bar!!
@Yashs911 @RayBB
=> Fix address bar appearing in TWA

openlibrary/catalog/get_ia.py
Hotfix. Breaking the pre-commit CI. There's an underlying issue of why that's the only one breaking suggesting inconsistent version, but let's see if this'll fix it.
=> Fix mypy error

openlibrary/core/lending.py, openlibrary/plugins/upstream/borrow.py
Closes #8372. Loosely related to #3429, we think we're seeing an uptick of lending error exception cases perhaps related to system limit. We want to add more specific reporting (e.g. response `429` instead of generic `400` or `401`) so we know internally where these error cases are coming from and how to deal with them gracefully for patrons. 
EDIT: I think we may have converged on `409` HTTP Response: **Conflict** or `429`.
This PR likely depends on changes being made internally within petabox, perhaps near:
https://git.archive.org/ia/petabox/-/blob/master/www/common/Lending.inc#L111-114
Which also pertains to https://git.archive.org/ia/petabox/-/blob/master/www/common/Lending/BookLoanService.inc#L525-534 and https://git.archive.org/ia/petabox/-/blob/master/www/common/Lending/BookLoanServ …
=> Improve lending error handling

openlibrary/plugins/openlibrary/js/add-book.js
Closes #8424
When adding a new book, it would be great if the ID type be automatically selected when entering the ID.
@scottbarnes
=> feat(add-book-detect): add Auto-detect entered edition ID type #8424

openlibrary/plugins/openlibrary/js/ile/utils/SelectionManager/SelectionManager.js
Closes #8481
Addresses the issue where dragging content other than ILE selectable elements would trigger ILE drop target behavior.
Any content can still be dragged, but now only ILE elements will trigger ILE behaviors.
While I was testing, I also noticed that the drag target highlighting wasn't deactivating after the drag was complete, so I fixed that as well.
The challenge here is that the dragover event doesn't have any visibility into the elements being dragged; all it can see is the data payload attached to the dataTransfer object during the dragstart event.  One solution would be to unserialize that data during dragover and examine it to see if it contains the kind of data we want. However, dragover is fired every time the mouse moves with a dragged item, so that's a potential …
=> Restrict ILE dragging to ile-selectable items

openlibrary/templates/account/books.html
Makes the Yearly Reading Goals banner dismissible.
=> Use dismissible banner for yearly reading goals

openlibrary/macros/databarWork.html, openlibrary/templates/type/edition/view.html
Closes #8493
The `render_component` function, when called for the first time, appends a `script` element which pulls in Vue.  It also renders a `script` element for the specific component the first time that component is rendered on a page.
The first time that `render_component` is called on the book page is in the `edition/modal_links` template.  Prior to these code changes, the rendered modal links were stored in a variable which was rendered twice in `databarWork.html`, resulting in duplicate `script` tags.
Since rendering the `edition/modal_links` template takes very little time, `render_template` is now called both times the modal links are rendered.
=> Avoid rendering duplicate Vue-related script elements on book pages

conf/openlibrary.yml, openlibrary/plugins/openlibrary/js/realtime_account_validation.js, openlibrary/plugins/upstream/account.py, openlibrary/templates/account/create.html
Closes #7674
Replaces our image-based reCAPTCHA with an invisible reCAPTCHA.  ~Not yet tested.~  
**Edit:** I was able to create an account on `testing`.
=> Add support for invisible reCAPTCHAs

openlibrary/plugins/openlibrary/js/check-ins/index.js
Closes #8521 
This PR aims to add zero padding to last read date for a book in client-side code.
1. Mark a book as "Already Read". A prompt for a read date will appear below the dropper. Click the "Other" option to manually enter a date.
2. Set a read date of 1 January 2023, and submit the form.
3. You'll see that the day and month will be zero padded wherever expected.
https://github.com/internetarchive/openlibrary/assets/116485536/59d4d52c-e302-453c-a88e-7e9e87102c6f
@jimchamp
=> Add zero padding to last read date in client-side code

openlibrary/templates/search/sort_options.html
Adds an alphabetic search to any search other than author and list searches.
Note: Sorts on work title, which may not reflect the edition title shown to the user.
Work towards #2796 
feature
Sorts on work title, which isn't shown to the ordinary user and may vary from what is shown e.g. searching for a title in a specific language will display that edition, but the work may be titled, and therefore sorted, in a different language.
The sort code has references to ga_key, which don't seem to be used in the code, so I just used "Alphabetical". I'm assuming this is something tracked by Google Analytics?
The author page book list and Book search results should now show an "Alphabetical" option.
@RayBB
=> Add librarian-only sort option for work title

openlibrary/plugins/openlibrary/js/ile/BulkTagger.js
Modifies bulk tag submission handler to prevent clearing selected works on successful submission.  @mheiman mentions that this is likely the preferred experience, [here](https://github.com/internetarchive/openlibrary/issues/8530#issuecomment-1815282306).
While logged in with an account that can bulk tag works:
1. Go to a search page.
2. Select two or more items.
3. Using the bulk tagger, add at least one subject to the selected works.
4. Ensure that the selected works are still selected on success response.
=> Retain selections on bulk subject submission

openlibrary/plugins/openlibrary/js/ile/BulkTagger.js, static/css/components/tagging-menu.less
Improves contrast of the subject type pills, found in the "Create new subject" section of the bulk tagger.
Before:
After:
@mheiman
=> Improve contrast of subject pills in bulk tagger

openlibrary/plugins/admin/code.py, openlibrary/templates/admin/people/index.html
Closes #8151
Adds second account look-up option to `/admin/people` page.  New option allows one to look up accounts by IA identifier.
_New input with error message.  Successful account look-ups redirect to the admin account page._
@seabelis
=> Add account look-up by IA ID

openlibrary/plugins/openlibrary/js/my-books/MyBooksDropper/ReadingLists.js, openlibrary/templates/lists/dropper_lists.html, static/css/components/mybooks-dropper.less
Adds some visual feedback whenever an item is added to or removed from a list via the My Books Dropper.
If the server responds with a `4XX` or `5XX` status when updating a list, a toast message is displayed and the list item's initial state (checked or unchecked) is restored.
_Loading indicator beside a list named "137"_
@mekarpeles
=> Add visual feedback when updating list via My Books Droppers

docker/README.md
This adds a hotlink to the Debugging page in the documentation.
Closes  #8512
This adds a hotlink and a section on how to run the debugger and profile the docker container, which is very useful information.
=> Add link for Debugging in Docker Installation Guide

openlibrary/plugins/openlibrary/js/ile/utils/SelectionManager/SelectionManager.js
Closes #8212
This PR implements support for using shift+click to select/deselect ranges of items in the ILE.
There are different models for how shift+click selection works in interfaces, particularly with regard to how intermediate toggled items are handled; e.g. If a list is unselected except for item 3, and you click on 1 to select it and then shift+click on 5 to extend the selection, does 3 switch states or remain selected? I judged that the most common use case would be selecting or deselecting all the items in a range, and implemented accordingly.
The shift+click function requires two clicks, one to establish the starting point and the action (select/deselect) and one (with the shift key) to indicate the end of the range. Ranges may be selected in either direction. If the shifted …
=> Add shift+click selection support

openlibrary/macros/Pager.html
Closes #8420 
Adds a shortcut to the last page of an author's works on the author page.
On an author record that has more than 10 pages of works, verify that the last page number is shown separated by an ellipsis.
Additionally, verify that the ellipsis is not present when the last page would normally be shown.
The last page being shown as an option at the beginning of the works.
(For testing, the number of works per page was set to 10 instead of 20)
When towards the back pages, the shortcut is not displayed.
@cdrini
=> Add last page shortcut to Author works list

conf/solr/conf/managed-schema.xml, openlibrary/plugins/worksearch/schemes/works.py, openlibrary/solr/solr_types.py, openlibrary/solr/update_edition.py, openlibrary/solr/update_work.py
In order to support our implementation of web books, we wanted to add an ability to search by `format` . This adds that ability.
You'll have to reset your local solr:
```sh
docker compose down
docker volume rm openlibrary_solr-data openlibrary_solr-updater-data
docker compose up -d
docker compose exec web bash -c 'PYTHONPATH=. ./scripts/copydocs.py /books/OL40066166M'
```
- ✅ Searching for `format: web book` or `format:audio` or `format:ebook` works
- ✅ Selects editions of said format
- ✅ Appears correctly in search.json endpoint
To deploy: Copy the manage-schema into the running solr docker container _before_ deploying
=> Add format field to solr works/editions

openlibrary/templates/my_books/dropper.html, openlibrary/templates/type/list/view_body.html
Closes #8206 
Adds the Want to Read dropper to book options within lists.
1. Go to a list with books added.
2. The Want to Read dropper should display underneath the existing Read/Listen button.
3. Selecting the dropper when logged out should redirect the user to the login page.
4. Selecting options from the dropper while logged in should update the user's reading log as expected.
While logged out:
@jimchamp
=> Add Want to Read dropper to lists

openlibrary/templates/lib/nav_foot.html
Closes #8552
Add Release Notes link to footer navigation, under help center
Navigation links to : https://github.com/internetarchive/openlibrary/releases
@scottbarnes
=> Release Notes navigation to Help Center footer

openlibrary/plugins/books/dynlinks.py
This merely fixes a typo in `trim()`'s docstring in `openlibrary/plugins/books/dynlinks.py`.
=> Fix typo in trim() docstring

openlibrary/plugins/openlibrary/lists.py, openlibrary/plugins/openlibrary/tests/test_lists.py
To support Scott Hewitt's work, and to make consistent with our other APIs, `POST /lists/add` now supports a JSON body containing the list document. Previously it only supported URL parameters.
Tests added.
✅ You can test locally on the local host instance by running this in your browser console while logged in and on `localhost:8080`
```js
await fetch('/lists/add', {
method: 'POST',
headers: {
'Content-Type': "application/json",
},
body: JSON.stringify({
name: 'foo data',
description: 'bar',
seeds: [{'key': '/books/OL1M'}, {'key': '/books/OL2M'}],
}),
}).then(r => r.json())
```
Should create the list!
✅ You can also create one using url parameters, like before:
```js
await fetch('/lists/add?name=hello&seeds=OL2M,OL3M', {
method: 'POST',
headers: {
'Content-Type': "application/json",
}, …
```
=> Make /lists/add support POST with json body

openlibrary/core/lists/model.py, openlibrary/core/models.py, openlibrary/plugins/openlibrary/code.py, openlibrary/plugins/openlibrary/lists.py, openlibrary/plugins/upstream/models.py, openlibrary/plugins/upstream/tests/test_models.py, openlibrary/plugins/upstream/utils.py, openlibrary/tests/core/lists/test_model.py, openlibrary/tests/core/test_models.py
`ListMixin` is one of the pieces that makes the list code really annoying to work with. Dissolve that class and have just a single `List` class. This also makes a lot of the types now make sense / possible to add!
- Centralize all the list models into a single file. This clears up a circular dependency -- which is a good sign :P
- ✅ Lists display
- ✅ Can edit lists
- ✅ Can add to list from search page
- ✅ List history displays nice history messages
=> Refactor: Dissolve ListMixin

openlibrary/plugins/upstream/covers.py, requirements.txt
Closes #8147
~~NOTE: This is blocked pending an update to `web.py`. We have a few proposed solutions for that. Here's one: webpy/webpy#773.~~
Fix.
This changes `covers.py` to reflect the changed field names brought on by `web.py`'s switch to [`multipart`](https://github.com/defnull/multipart/).
This will affect every request made on the website + cover uploads. We'll want to monitor after deploying (and also try on staging)
Some field names changed, as the diff will show.
Additionally, the `web.py` version in `requirements.txt` has been pinned to the commit with the `cgi.FieldStorage` change: https://github.com/webpy/webpy/commit/ed3e92cceb6ed870b224107ea653f48fa7fc2d0a.
- Add a cover;
- Delete a cover; and
- Generally use the site every page load goes through the changes to `web.py`, and …
=> Make covers.py compatible with web.py cgi.FieldStorage removal

openlibrary/core/bookshelves.py
Fixes yearly already-read reading log by showing books with checkins that have since been moved to other shelves, e.g. a book that was marked as read but then moved to e.g. "Already Read" or "Currently Reading"
=> Relax yearly already-read page query

openlibrary/templates/search/sort_options.html
=> Make sort_option anchors nofollow to prevent crawling

openlibrary/templates/covers/add.html, static/css/components/cbox.less
Closes #4306
Fixes display issue on "Add Cover Image" Popup 
- Modifies LESS template for form styles and inline style declaration in the add a cover template
- Rebuild static assets and see correct alignment on "add cover"
Before:
After:
@scottbarnes
=> Fix "Add Cover Image" Form Display

openlibrary/templates/account/create.html, openlibrary/templates/books/add.html, openlibrary/templates/books/edit.html, openlibrary/templates/recaptcha.html, openlibrary/templates/site/footer.html, openlibrary/templates/support.html, openlibrary/templates/tag/add.html
- Previously we were loading the recaptcha JS from google on every /books page and every edit page. We only need it for logged out users, and not at all on the books page, so load it then.
- Also DRY up recaptcha rendering
- ✅ Invisible recaptcha appears on registration form
@jimchamp
=> Only load recaptcha JS when needed + DRY recaptcha code

openlibrary/core/imports.py, scripts/promise_batch_imports.py
In support of #7658 
Identifies JIT import candidates during the promise item import process.  Updates the `status` of all matching import items to `pending`.
Keeping this as a draft until it is properly tested.
=> Trigger JIT imports during promise item import flow

openlibrary/core/schema.sql, scripts/dev-instance/dev_db.pg_dump
Removes unused `bookshelves_votes` table.
PG dump file was generated after dropping the `bookshelves_votes` table from a newly created Open Library instance.
Commands used:
```
docker compose exec -uroot db bash
./openlibrary/scripts/dev-instance/create-dev-db-pgdump.sh > /openlibrary/scripts/dev-instance/dev_db.pg_dump
```
@mekarpeles
=> Remove `bookshelves_votes` table from `schema.sql` and pg dumps

openlibrary/plugins/worksearch/schemes/works.py
Improve search rankings by boosting results that have high reading log counts or have exact phrase matches to the user's query.
Has been up on testing.openlibrary.org over a week. Improvements to almost all our search metrics!
Percent high ranking (position <= 3)
The only case I noticed some worsening is when searching for generic more subject-like terms such as "science textbook". For these searches, books like "Frankenstein" will pop to the surface because their popularity causes them to jump too high in the rankings. These searches are not measured by the spreadsheet.
=> Boost search via reading log, phrase boosting

openlibrary/plugins/openlibrary/lists.py, openlibrary/templates/account/sidebar.html, openlibrary/templates/account/view.html, openlibrary/templates/books/breadcrumb_select.html, static/css/components/mybooks-details.less, static/css/components/mybooks.less
- fixes Loan History class so it's not individually underlined
- adds username (links to profile) on my books page before nav dropper
- removed duplicated `notes` from nav dropper
Resolves outstanding issues from #8597
Make it clear what page you're on
EDIT: Mobile
Remove duplicate notes
No underlined link (Loan History took visual precedence over My Loans and the Section was empty for non-owners)
Before:
After:
After (when not owner, hide initial section):
=> My Books visual fixes

openlibrary/plugins/upstream/edits.py, openlibrary/templates/merge_request_table/merge_request_table.html, openlibrary/templates/merge_request_table/table_row.html
Closes #
a.) Removes top of page pagination.
b.) Removes the "Show requests that I've reviewed" and "Show my requests" at the top of the page.
c.) Makes the make the MR title a link to preview the merge without assigning.
Changes in merge_request_table.html only
Mostly visual. Will update next section with images.
Will update
@mekarpeles @jimchamp
=> Merge Queue tweaks

openlibrary/solr/updater/edition.py, openlibrary/solr/updater/work.py, openlibrary/tests/solr/updater/test_edition.py, openlibrary/tests/solr/updater/test_work.py
Hotfix.
- [Fix presence of contributor causing index error](https://github.com/internetarchive/openlibrary/pull/8631/commits/ab9d65459de7ff888bc23713f1f0b9c813826fd9)
- I checked the previous version and it was never using `contributor`! So just disabled it for now and switched it back to what it was doing before
- [Fix EditionSolrUpdate wrongly queueing old orphans](https://github.com/internetarchive/openlibrary/pull/8631/commits/6ccb2645f9a3c653e2a513e6a044a7b4399b18a6)
- Typo on my end was causing it to create a fake work for every edition!
Added unit tests to prevent regression.
=> Hotfix some bug in solr updater refactor

package.json
Changes `repository` in `package.json` to conform with the shortcut syntax found [here](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository).
This was done to address these types of deprecation warnings, which are seen while building assets:
```
(node:5804) [DEP0170] DeprecationWarning: The URL github:internetarchive:openlibrary is invalid. Future versions of Node.js will throw an error.
```
Here's a [link to the deprecation](https://nodejs.org/api/deprecations.html#dep0170-invalid-port-when-using-urlparse).
=> Address deprecation warnings during build

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/post_mortem.md, .github/ISSUE_TEMPLATE/question_template.md
Adds cautionary message to our GitHub issue templates.  People are urged to remove or redact any sensitive information before submitting a new issue.
Message was not added to the new design proposal template.
=> Add cautionary message to our Github issue templates

openlibrary/templates/books/edit/edition.html
Closes #8174 
Hi, I'm a new contributor, I'm working with @karlitto01 to try to learn more about the codebase and find ways to contribute to OpenLibrary :)
In the issue above, the language an edition was originally translated from did not appear in the localized language on the edition edit page, this is a small fix for that issue.
I simply wrapped the initial value of the the language field in a '$_()' call. I believe this should correctly translate the text to the localized version.
Steps I took to test this:
- Setup dev environment
- Built the translation files
- Imported the work mentioned in the issue above (OL16656007W) to the dev environment.
- On the site, changed the language to Deutsch (but could use French like in the original issue)
- Going to the French edition of that work, …
=> Fixes translated languages not being localized on edition edit page

static/css/components/cbox.less, static/css/components/form.olform.less, static/css/components/metadata-form.less, static/css/page-edit.less, static/css/page-list-edit.less
Closes #5210 
UI fix
This change adds a ```resize``` field to ```textarea``` elements in the css to restrict the textarea from expanding beyond the page/container borders. For forms that can expand downwards, the value is ```vertical``` and for fixed size containers, the value is ```none```.
Go to any page with a ```textarea``` element (eg. edit book) and try to resize it; it should only resize vertically for forms that can expand downwards, or not at all for containers that are a fixed size.
Pages tested:
- books/edit/edition.html
- books/edit/about.html
- type/author/edit.html
- type/list/edit.html
- type/user/edit.html
- macros/NotesModal.html
Not yet tested:
- sectionopenlibrary\templates\admin\case.html
- openlibrary\templates\books\edit\addfield.html
- …
=> Limit textarea resize within page/container border

openlibrary/templates/lists/home.html, openlibrary/templates/search/inside.html, openlibrary/templates/search/lists.html, static/css/legacy.less, tests/integration/test_search.py
#8595 
1. deleted ```.searchInsideForm``` class from ```static/css/legacy.less``` as using ```.olform``` class can will maintain consistency and will allow us to remove code.
2. updated ```openlibrary/templates/lists/home.html``` , ```openlibrary/templates/search/inside.html ``` , ```openlibrary/templates/search/lists.html files``` . Changing ```.searchInsideForm``` class to ```.olform``` class which solves the issue and maintenaces consistency.
4. updated the references of ```.searchInsideForm``` to ``` .olform``` in ```tests/integration/test_search.py``` file.
=> Fixed inconsistent margin gap between search box and search button #8595

openlibrary/plugins/openlibrary/bulk_tag.py
Follow-up for: #8575 
Increments three new statsd counters whenever a bulk tagging operation occurs.
| Counter Name | Tracks |
|---|---|
| `ol.tags.bulk_update` |  Number of `POST` requests to the bulk tagging handler |
| `ol.tags.bulk_update.add` | Total tags added, per work |
| `ol.tags.bulk_update.remove` | Total tags removed, per work |
=> Gather stats on bulk tagging operations

openlibrary/macros/CheckOptions.html, openlibrary/macros/LoanStatus.html, openlibrary/macros/NotInLibrary.html, openlibrary/templates/books/edition-sort.html, static/css/components/buttonCta.less
Closes #8492 but does so by not rendering the link as clickable, rather than by triggering a pop-up.
This pull request is a partial hotfix for the the listed issue by creating an alternate class version of the 'Not in Library' button that does not allow the page to be reloaded when clicked. This Pull Request, however, was only able to fix it partially. I was only able to get the button to show a 'non hyperlink' version on the left screen but not in the table. Need to improve this PR further and get some help for that before then.
This uses the 'secondary_action' check in order to verify whether the link should be rendered. It makes the assumption that if 'secondary_action' is enabled, we do not have to render the link.
```
$# We assume that we are on the Book Page if secondary_action is …
```
=> Add non-link version of 'Not in Library' Button

static/css/base/helpers-misc.less
… related buttons
Closes #8567 
added #8567 cursor type to cursor: pointer to login sign up and other related buttons
a hand tool (pointer) will be seen whenever we hover over login, signup and other related buttons.
Hover over Login and signup buttons
@jimchamp @mekarpeles @cdrini
=> Add `cursor: pointer` non-standard buttons

openlibrary/plugins/openlibrary/lists.py, openlibrary/plugins/upstream/mybooks.py
Closes #8665
Breadcrumb selector now shows the fallback English text if no translations are available for the titles of the reading log and list overview pages.
`breadcrumb_title` was not being set [here](https://github.com/internetarchive/openlibrary/blob/5c72f357664f04faafa0b0c3f4d7d6de099fd164/openlibrary/templates/books/breadcrumb_select.html#L41-L46), due to the `selected` string not matching any of the `options` that include a count.  `selected` is the `header_title` that is passed to `MyBooksTemplate.render`.  Modifying the `header_title`s to include the counts corrected this issue.
Repeat the repro steps found in #8665
=> Change header titles for lists, shelves

openlibrary/catalog/add_book/__init__.py, openlibrary/catalog/add_book/tests/test_add_book.py, openlibrary/plugins/upstream/addbook.py
Closes #8661. 
This PR de-duplicates, using `casefold()`, the `subjects` field on `Work` items, and field values of list items that are added to `Edition` items on re-import via `load()`.
This does not affect edits made via the UI as they go through `DocSaveHelper()` and `process_work()` from `openlibrary/plugins/upstream/addbook.py`, which de-duplicates via a slightly differest strategy. Rather than merging two lists (existing subjects on a matched item, and new ones from an import item), it takes form data with every subject as a CSV and dedupes that string.
Though I had hoped to unify the de-duping logic, I think that is beyond the scope of this particular issue.
I added a slight bit of logic to the fields that looked as if they might possibly result in duplicates because of a lack of …
=> Fix: deduplicate subjects on works and list items on editions

openlibrary/plugins/openlibrary/js/bulk-tagger/BulkTagger.js
issue-:#8651
Closes #8651 
Fix:  Disable 'Submit" button after submission with a loading spinner .
// Adds state
this.isSubmitting = true;
// Disable button
this.submitButton.disabled = true;
// Show loading spinner
this.submitButton.textContent = "Submitting...";
A loading spinner can be seen after submission is made
=> Disable bulk tagger's "Submit" button after submission is made

openlibrary/plugins/upstream/mybooks.py, openlibrary/templates/account/readinglog_stats.html
Closes #8585 . Adds subtitles along with titles of books in stats
added subtitle attribute to work_json in mybooks.py and printed it in readinglog_stats.html
Step 1 : Add a book that has subtitle to Already read
Step 2 : Go to mybook section and click on the My Reading Stats and click on any bar
=> Adds work subtitles to reading stats

openlibrary/plugins/worksearch/code.py, openlibrary/plugins/worksearch/schemes/works.py, openlibrary/templates/work_search.html
Closes #7277  . Fix. Searching for fields which have no edition equivalent (eg `subject:horror`) now will still show works in the user's language.
- Also refactor work_search.html to read a `SearchResponse` object, and _not_ make the solr request from the template!
- Facets/sort/pagination still work in search
Subjects:
Key:
Authors:
=> Make search results use userlang even if no ed query

openlibrary/accounts/model.py, openlibrary/core/helpers.py, openlibrary/core/lists/model.py, openlibrary/core/models.py, openlibrary/plugins/openlibrary/lists.py, openlibrary/plugins/openlibrary/tests/test_lists.py, openlibrary/plugins/upstream/models.py, openlibrary/plugins/worksearch/subjects.py, openlibrary/solr/data_provider.py, openlibrary/solr/update.py, openlibrary/solr/updater/list.py, scripts/solr_builder/Jenkinsfile, scripts/solr_builder/index-type.sh, scripts/solr_builder/solr_builder/solr_builder.py
Closes #7815. Feature. Stores lists in solr. Includes both global lists (series) and user lists. This will eventually be used to replace the current lists search implementation which uses postgres.
~Depends on #8618~
Stores the names and a number of the aggregated book subjects.
Also some small refactors, including more list types.
Did a full reindex, and they all correctly appear in solr search results.
=> Lists in Solr

openlibrary/macros/CheckOptions.html, openlibrary/macros/LoanStatus.html, openlibrary/macros/NotInLibrary.html, static/css/components/buttonCta.less
Addendum to #8524 . We had a miscommunication internally about what we wanted the design to look like!
This basically has the exact same click behaviour as the previous PR (which we discussed during calls w @mekarpeles and @scottbarnes ), but no longer has the blue "check options" button.
Try it here: https://testing.openlibrary.org/search?q=Teachers%2C+preachers%2C+non-believers&mode=everything
@mekarpeles @scottbarnes
=> Revert blue "Check Options" but keep click behaviour

openlibrary/plugins/upstream/addbook.py, openlibrary/templates/books/add.html
Closes #8598 
updated `book_title` as the new `name` 
Added `book_title=""` as object to post handler and set the value of `i.title` to `i.book_title`
=> Re-enabled autofill on add new book form

openlibrary/templates/account/reading_log.html
Fixes bug which causes reading log pages greater than `1` to fail to render. Root cause of the issue was that `current_page` was passed to the `Pager` macro as a string.  Casting `current_page` to an integer in the `Pager` macro call squashes this bug.
Navigate to the second page of any public reading log.
@mekarpeles @onnotasler
=> Fix broken reading log pages

openlibrary/templates/trending.html
Added nav-bar class just like in the searching page to make the menu appear exactly as the searching page.Fixes #8702
Closes #8702 
Changes styles of tabs on the trending page to appear same as same as the search page. 
nav-bar class is used just like in the searching page.
Visit http://localhost:8080/trending/now on local deployment to see the changes and test them out.
Before:
After:
@cdrini
=> Made styles of tabs on trending page same as search page.

openlibrary/core/lists/model.py, openlibrary/macros/SearchResultsWork.html, openlibrary/plugins/openlibrary/lists.py, openlibrary/plugins/upstream/utils.py, openlibrary/plugins/worksearch/code.py, openlibrary/solr/updater/list.py, openlibrary/templates/lists/feed_updates.html, openlibrary/templates/type/list/edit.html, openlibrary/templates/type/list/view_body.html, openlibrary/tests/core/test_lists_model.py, static/css/components/search-result-item.less
~Depends on #8627 .~
Closes #6160
Closes #7812
Feature. Adds the ability to add markdown notes to list seeds.
- Introduces a BREAKING CHANGE to our schema for lists. Previously, list seeds could be only two types: a `ThingReferenceDict` (eg `{ key: "/books/OL1M" }`), or a `SeedSubjectString` (eg `"subject:sci_fi"`). We now have a new option, an `AnnotatedSeedDict` which is eg `{ thing: { key: "/books/OL1M" }, notes: 'My notes!' }`.
- The changes have been carefully designed to support the old formats as well, so adding notes to a list seed will not cause every seed on the list to be modified. This will allow history to be reasonable and avoid confusing unintentional edits.
- ✅ adding edition to list
- ✅ adding work to list
- ✅ adding author to list
- ✅ removing edition from list
- ✅ …
=> Add ability to add notes to list seeds

openlibrary/plugins/openlibrary/js/check-ins/index.js, openlibrary/plugins/upstream/checkins.py
Closes #7447
Changes YRG partials endpoint to use JSON encoding.
This endpoint is called whenever a patron sets a yearly reading goal from their `/account/books` page.
=> Use JSON endpoint for reading goal partials

openlibrary/plugins/openlibrary/js/add-book.js, openlibrary/templates/books/add.html
Closes #8475 
LibriVox and Project Gutenberg can now be selected as identifiers when adding a new work.
Added a default empty check for all identifiers on the page that don't have specific validation.
1. Go to /books/add
2. Attempt to select LibriVox or Project Gutenberg as the book's identifiers
3. Ensure that an empty value will not be accepted
4. Once submitted, ensure that the identifier is populated on the edition edit screen with the proper value
New identifiers on add book page
Empty value error message
=> Add LibriVox and Project Gutenberg identifiers to add book page

openlibrary/templates/search/sort_options.html
Closes #8723
Fixed Changing sort order of works on author page should reset page to 1
by modifying ```openlibrary/templates/search/sort_options.html```
by setting ```page=None``` wherever it calls ```changequery```.
Page no - 2
After sorting page no reset to page 1
=> Fixed Changing sort order of works on author page should reset page to 1

scripts/promise_batch_imports.py
Shouldn't be so much of an issue now, but some old records came in lowercased. Protect against it ever happening again.
Closes #
@mekarpeles
=> Ensure bwbsku local_id is uppercased.

.github/workflows/javascript_tests.yml
Updating the Node version in the cache `key` string to `20`, which is the version of Node that is used by this workflow.
=> Update Node version in `key`

openlibrary/core/lending.py
In response to (internal) Bulk Availability API PR https://git.archive.org/ia/petabox/-/merge_requests/3516/diffs
This PR decorates our calls to the Bulk Availability API (petabox) to include headers with s3 authorization, scope, application, and client_ip to help enforce security/permissions and rate limiting. 
The `scope` field may need to be changed? I'm not sure what values are acceptable.
This PR can be deployed to testing when there's a petabox PR to test against
@ximm @cdrini
=> Add client_id, s3, scope to bulk availability API

conf/solr/conf/managed-schema.xml
Closes #8722 
Title sorting now ignores diacriticals.
This solution replaces the lowercase filter on the text_title_sort SOLR type with the icuFolding filter, which not only lowercases, but also removes diacritical marks from the search tokens according to Unicode standards.
A SOLR reindex will be required for this change to take effect.
The test case in the issue, https://openlibrary.org/authors/OL291650A/Max_Ernst?q=&sort=title should now colllate Dechets and Déchets together.
I add some works in my development instance to test this behavior.
Before this change, the "With Mark Twain" work sorted between "Wit" and "Wít".
@mheiman @tfmorris @cdrini
=> Make title sorting ignore diacriticals

openlibrary/macros/ShareModal.html
Previously share modals had the wrong url; eg
```html
<iframe frameborder="0" width="165" height="400" src="/works/OL82563W/Harry_Potter_and_the_Philosopher&#39;s_Stone/-/widget"></iframe>
```
1. Should have `openlibrary.org`, of course since this will be pasted in other people's sites
2. Should not have both the page slug _and_ the `/-/` placeholder
Tested it creates the right url on testing.
```html
<iframe frameborder="0" width="165" height="400" src="//testing.openlibrary.org/works/OL459469W/Madlenka/widget"></iframe>
```
=> Fix share modal iframe url

openlibrary/i18n/pt/messages.po
Closes #8743
Fix. Switches out 3 Portuguese phrases for more idiomatic versions.
Very straightforward. All changes made in the [translation file](https://github.com/internetarchive/openlibrary/blob/136fc1ff4c86bbb3f81aee49224aa44c01297950/openlibrary/i18n/pt/messages.po). Note: Switched second word of both longer phrases ("ajuda", "desenvolvedor") to lowercase for consistency, but can switch both to uppercase if preferred. 
@cdrini
=> Update Portuguese translation for 3 phrases.

conf/coverstore.yml, openlibrary/coverstore/code.py, openlibrary/plugins/openlibrary/sentry.py, openlibrary/utils/sentry.py
Closes #8699 . Feature. Let us monitor covers.openlibrary.org performance via sentry.
- Note I couldn't get it to do the path regex, so it just displays the class name. That's sufficient.
- Corresponding olsystem change: https://github.com/internetarchive/olsystem/pull/199
- Tested by enabling locally into our sentry, and it worked.
- Patch deployed it to ol-covers and ol-web, and both worked!
- See covers in sentry here: https://sentry.archive.org/organizations/ia-ux/performance/?project=10
=> Add sentry transactions to covers server

openlibrary/plugins/openlibrary/js/covers.js, openlibrary/templates/covers/add.html, static/css/components/cbox.less
Closes #8755 
Refactor. Removes unnecessary/outdated js by handling URL validation with the "url" HTML attribute.
Very straightforward! Just a quick switch-out in the `add.html` file and removal of unnecessary url validation js from the `covers.js` file.
**One quick note:** This issue originally arose because I noticed that the `val` function was causing a type error (by trying to run `.trim()` on an empty string), which isn't directly fixed by this adjustment. Happy to add a quick fix for that -- confirming that `$(#selector).val()` is not an empty string before running `.trim()` on it -- to this PR or a separate one, but the fix may not be necessary.
1. Go to a book page (while logged in)
2. Select `Add a Cover`
3. Try typing an invalid URL and hitting `Submit`
@cdrini
=> Replace cover URL validation with HTML attributes

openlibrary/plugins/openlibrary/js/covers.js, openlibrary/templates/covers/add.html
Closes #8749 
Feature. Adds a js function to disable `Submit` button and replace text with `Uploading...` when form is submitted.
The `addLoadingStyling` function is currently defined locally within the on submit function for `#addcover-form`. Could be moved into the `initCoversAddManage` function or elsewhere in the case of re-use (i.e. for the `Save` button in the manage cover window).
Another note: there is no function to clear the styling because the template is re-rendered when the function returns; if re-used elsewhere, a simple cleanup function may be necessary.
With @cdrini's help, I settled on the `data-loading-text` attribute to store the "Uploading..." message for translation purposes. Any other implementation of the function would require the same attribute in the …
=> Disable cover upload `submit` button while uploading

openlibrary/plugins/worksearch/code.py
Work search template expects a SearchResponse object, but None was being sent if the request did not have any params. Updated request to always send a SearchResponse object.
Also, removed an unused import.
Closes #8730 
Fix the broken rendering issues on the '/search' page when there are no query params.
There was existing logic to prevent the solr search query from being executed if the param dict was empty. I am assuming this was done to prevent a db hit. Executing the search query with the empty param was a solution that I tested and worked but I decided to send back an empty SearchResponse.
These are the steps I took to test.
1. Visit the `/search` page. Search form should be rendered.
2. Go to `/advancedsearch` and submit and empty search. This will redirect to `/search` and the …
=> Fix broken template rendering on /search requests

.github/workflows/auto_unassigner.yml, .github/workflows/javascript_tests.yml, .github/workflows/python_tests.yml
We are seeing deprecation warnings on workflows that use version 3 of the `setup-node` and `cache` actions.  Upgrading this now in order to avoid our workflows completely failing in the Spring.
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> update `setup-node` and `cache` actions to v4

openlibrary/plugins/upstream/mybooks.py
Closes #8771
Going to page 2 of notes breaks because the page is a string instead of an int so added one line to convert string to int.
Go to link:http://localhost:8080/people/openlibrary/books/notes?page=2&debug=true and check if we get type error.
Before changes:
After changes:
@mekarpeles
=> Fixed My Notes

scripts/gh_scripts/issue_comment_bot.py
Ensures that the new comment digest is always published to Slack, even if no new comments were found.  If we publish the digest daily, we'll know that something has gone wrong with the workflow if the digest is ever not published.
=> Always publish new comment digest

.github/workflows/new_comment_digest.yml, scripts/gh_scripts/issue_comment_bot.py
Adds authorization token to GitHub request headers, iff a token is found in the environment.  Also adds API version and Accept headers.
Without authentication, we can only make 60 calls to GitHub's REST API per hour, which sometimes isn't enough to successfully run the new comment digest script.  This script can still be executed without an auth token.
=> Add support for authenticated requests to the comment digest script

openlibrary/core/cache.py, openlibrary/core/lending.py, openlibrary/plugins/admin/code.py, openlibrary/plugins/openlibrary/api.py, openlibrary/plugins/openlibrary/code.py, openlibrary/plugins/upstream/models.py, openlibrary/tests/core/test_lending.py
We're having some performance issues associated with high traffic to the availability endpoint. Add caching to our /service/availability calls to avoid causing too much traffic.
- DRY methods that call get_availability
- Add more types to availability data structures
- Add support for memcache's get/set_multi
- Decrease get_availability timeout to 10s instead of 30s
- Loading a search result page twice results in no new call to availability endpoint
- Loading /widget endpoint works
=> Add per-key caching to get_availability

compose.production.yaml
Closes #8710
Causing expansion in CRONTAB_FILES to fail; it included the quote in the file path!
@mekarpeles
=> Fix environment variables in compose file must not have quotes

compose.production.yaml, docker/ol-nginx-start.sh
Adds www.openlibrary.org to letsencrypt initialization for www0 nginx
Closes #
=> adds www.openlibrary.org domain to cerbot

openlibrary/components/MergeUI.vue
Closes #8655
The MergeUI action button would confusingly change back to "Merge" from "Saving..." or "Done" in the midst of a merge. This PR fixes that behavior.
The MergeUI interface is designed to change the action button to "Merge" (or "Request Merge") button as soon as enough data has loaded for the merge to complete successfully. This means that when the server is slow, the Merge button will be available before covers, list counts, reading log counts, etc. have loaded. That's the expected behavior.
A previous PR had added a watch function that set the button to "Merge" whenever the internal merge() function returned changed data. The merge() function returns values as soon as a merge is possible, but the returned values change as additional data comes in, so if the user pressed the …
=> Fix action button label changing behavior in MergeUI

scripts/promise_batch_imports.py
Fix. `ProductJSON` missing was causing the process to error.
- Also handle some `'null'` strings I noticed in the data.
With the `--dry-run` parameter from #8793 , it no longer errors on rows where `ProductJSON` is not defined.
@hornc
=> Handle ProductJSON being undefined for some records

openlibrary/templates/covers/add.html
Closes #8762.
Feature/refactor. Uses HTML `accept` attribute to specify acceptable cover image file types (jpg/png/gif) so that no other file types can be submitted.
Super simple! Ended up just adding the single attribute to the HTML in `covers/add.html`.
1. Go to a book page, select "Add Cover" or "Manage Covers"
2. Try to upload an incorrect file type (like a PDF) -- the file should be greyed out and not selectable.
@cdrini
=> Limit cover image file type.

openlibrary/templates/books/mybooks_breadcrumb_select.html
Closes #8800 
Removes extra notes option on the drop down menu on My Books page.
See issue #8800 for before image.
After fixing the duplication:
Testing the link:
@RayBB @scottbarnes
=>  remove second notes option

openlibrary/templates/search/authors.html, openlibrary/templates/search/subjects.html
Closes #8803
Fixed Unable to render this page Error when empty spaces passed to search/authors and search/subjects.
It is a simple fix by passing the default argument ```q=''``` to``` get_results``` function in ```search/authors.html``` and ```search/subjects.html```.
=> Fixed Unable to render this page Error when empty spaces passed to search/authors and search/subjects 

openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/js/password-toggle.js, openlibrary/plugins/upstream/forms.py, openlibrary/templates/account/create.html, static/css/components/form.olform.less
Closes #7645
An button to show and hide password
Changes in html and a python file. Also used fontawesome eye icon
docker compose up , then  redirect to sign in page.
Before
After
@beccat123
=> Moving to single password field for registration

openlibrary/core/models.py, openlibrary/core/vendors.py, openlibrary/plugins/books/code.py, openlibrary/plugins/books/dynlinks.py, openlibrary/plugins/openlibrary/code.py, openlibrary/plugins/upstream/borrow.py, openlibrary/tests/core/test_vendors.py, scripts/affiliate_server.py
Closes #8541 
Fix.
This PR reenables AMZ imports from `/isbn`.
With this PR, the logic upon visiting `/isbn/[some isbn]` is:
- (existing functionality) attempt to fetch the book from the OL database;
- (existing functionality) attempt to fetch the book from the `import_item` table (likely ISBNdb);
- (new) attempt to fetch the metadata from the Amazon Products API, clean that metadata for import, add the record as a `staged` import in the `import_item` table, and then immediately import it `load()`, by way of `ImportItem.import_first_staged()`.
This leverages the change in bec372cfdddefdef8b19c1304a5c051f399c05e5 (hopefully) prevent the race condition that seemed to cause multiple Amazon imports in #6405.
I also want to draw attention to the fact this does _not_ add the proposed `GET` …
=> Re-enable Amazon imports from /isbn

openlibrary/core/lending.py, openlibrary/macros/IABook.html, openlibrary/macros/Pager_loanhistory.html, openlibrary/plugins/upstream/account.py, openlibrary/plugins/upstream/mybooks.py, openlibrary/templates/account/loan_history.html, openlibrary/templates/account/mybooks.html, openlibrary/templates/account/sidebar.html, openlibrary/templates/books/mybooks_breadcrumb_select.html, static/css/components/mybooks-list.less
Closes #7311
Feature: This is a draft PR to create a borrow history page on openlibrary.org instead of being redirected to the internetarchive.org currently.
=> 7311/feature/loan history code for rendering loan_history page

openlibrary/macros/FulltextResults.html
Closes #8650
Added 'Want to Read' Dropper to the Search Inside page.
Added 'Want to Read' Dropper to the Search Inside page by importing and adding the dropper component to the calling of the searchResultsWork macro in ```openlibrary/macros/FulltextResults.html``` file.
=> Added 'Want to Read' Dropper to the Search Inside page #8650

openlibrary/plugins/openlibrary/js/ile/index.js, openlibrary/plugins/openlibrary/js/ile/utils/SelectionManager/SelectionManager.less
I think it would be better to stick with just sliding up the selection above the ILE blue bar on clicking  "```N``` works selected". It would allow the selected works to appear above the blue bar upon click and immediate visibility of the selected works. This implementation would not mess with the drag and drop functionality as mentioned here [https://github.com/internetarchive/openlibrary/issues/8659#issuecomment-1876019782](https://github.com/internetarchive/openlibrary/issues/8659#issuecomment-1876019782) by @cdrini.
Other than that we can also choose to go with an implementation of a drawer or a menu like bulktagger but I am not sure if that won't interfere with the drag and drop functionality. If @cdrini or someone can verify the working of ```setDragImage``` API in a drawer or menu, …
=> ILE: Increasing the visibility of selected works

static/css/components/carousel.less, static/css/components/mybooks-menu.less
Closes #8672 
Fixes the carousel overflow in the my account page
Fixed it by dynamically adjusting how the margin on the right behaves.
=> Fixed the Reading log carousels overflow on tablets #8672

openlibrary/plugins/upstream/mybooks.py
Closes #8771
Fix
This employs the same strategy as #8772, but adds an `int()` conversion to a line that was missed.
Look at, for example, page 2 of notes, assuming 26+ notes: http://localhost:8080/people/openlibrary/books/notes?page=2.
@mekarpeles
=> Fix: add missing `int` conversion to notes page

openlibrary/core/observations.py
Removes unused `accounts` import statement from `observations.py`.
=> Remove unused import from `observations.py`

openlibrary/plugins/openlibrary/js/edit.js, openlibrary/plugins/openlibrary/js/jquery.repeat.js, openlibrary/templates/books/edit/excerpts.html, openlibrary/templates/books/edit/web.html
Closes #8423 
Fix. Makes the inputs for adding contributors, classifications, identifiers, excerpts and links (on the `Edit` page and the `Work Details` page) only clear once the input is accepted -- to make it easier for users to fix typos/etc. if rejected instead of having to re-type their entry.
This ended up being a little more involved than expected. Since the values were automatically clearing (to be saved separately in a `data` variable) before the error checks ran, I initially implemented a workaround solution that used the `data` values to manually re-set the input fields to their lost values after the error checks.
After this, I discovered that the root of the problem was actually in the `jquery.repeat.js` file, where all text inputs were being cleared as a side effect of …
=> Show error messages without clearing inputs in edition edit page

requirements.txt, scripts/promise_batch_imports.py
Refactor. Spent a decent chunk of time trying to trace through how the dates were used in this file. Refactored them to be less flexible and more explicit. It now avoids kwargs, and only supports input like `2024-01-01:2024-01-10` or `2023-01-01` or `2023-01-01:*`.
olsystem side: https://github.com/internetarchive/olsystem/pull/201
- `--help` works
- `--dry-run` works and outputs all modified records.
@hornc
=> Refactor promise_batch_imports args + add --dry-run option

openlibrary/i18n/pl/messages.po
Closes #8836 
Fix. Quick update to fix a spelling error in the Polish word for "published." Also confirmed that all the variations on the word I could find in `messages.po` did include the missing "w."
Switch site language to Polish and navigate to an edition page. The text should now read "opublikowane" instead of "opublikoane."
=> Fix Polish spelling error in two places.

openlibrary/templates/type/author/view.html, openlibrary/templates/type/list/view_body.html
The My Books dropper feature flag is being removed from the config, so we shouldn't use the flag to decide whether or not to use the refactored droppers.  The notion of a "My Books" feature flag was removed by #8539.
> [!WARNING]
> Merge the [config changes olsystem #195](https://github.com/internetarchive/olsystem/pull/195) before merging these changes.
=> Always use "My Books" droppers

openlibrary/plugins/openlibrary/support.py
Closes #8833 . Hotifx. `get_memcache` was changed to return a wrapper memcache object which has various helper utils. Unfortunately the `set` method has a different parameter called `expires` instead of the `time` parameter.
=> Fix rename of method parameter causing contact form error

openlibrary/macros/databarHistory.html, openlibrary/macros/databarTemplate.html, openlibrary/macros/databarView.html, openlibrary/macros/databarWork.html, openlibrary/templates/subjects.html, openlibrary/templates/type/edition/compact_title.html
These pages should not be crawled by search engines. ~4.3k appear in the "Soft 404" error section of Google Search Console.
https://search.google.com/u/1/search-console/index/drilldown?resource_id=sc-domain%3Aarchive.org&item_key=CAMYDiAC
Should have no effect on behaviour
=> Edit button should be rel=nofollow

openlibrary/plugins/openlibrary/js/bulk-tagger/BulkTagger.js, openlibrary/plugins/openlibrary/js/bulk-tagger/BulkTagger/MenuOption.js, static/css/components/tagging-menu.less
Closes #8658 
This PR addresses the issue outlined in #8658 by enhancing the Bulk Tagger tool to provide visual indications of subjects staged for addition or removal. The proposed solution adds highlighting to the corresponding menu options when a subject is staged.
The PR integrates the highlighting logic to the staged changes for addition or removal. The highlighting classes are applied based on the updated menu option state. I still have some queries regarding the staged changes as mentioned [**here**](https://github.com/internetarchive/openlibrary/issues/8658#issuecomment-1872234457)
1. Open Manage Subjects Menu
2. Add / Remove subject to view highlighted staged changes
Before Staging changes
After Staging changes
@jimchamp
=> Added: Highlighted staged changes in BulkTagger

openlibrary/plugins/openlibrary/js/bulk-tagger/BulkTagger.js, openlibrary/plugins/openlibrary/js/bulk-tagger/index.js
Closes #8652 
Moved the "Create subject" affordance to the bottom of the scroll container for better visibility and prevention of duplicate subjects.
- Moved the "Create subject" affordance to the bottom of the scroll container.
- The functionality of updating and displaying the affordance remains unchanged and doesn't get affected from the following changes in this PR.
- Ensured that the visibility rules remain unchanged: the affordance is hidden when the subject search input is empty.
- Search for a subject in bulk tagger component of ILE
- The behavior of displaying create new subject affordance has been updated as per requested whilst ensuring the visibility rules
https://github.com/internetarchive/openlibrary/assets/85943021/ffbed116-7583-4e26-b4fa-2c4b4722cd38
@jimchamp
=> Bulk Tagger: Move "Create subject" affordance to bottom of menu options scroll container

openlibrary/templates/books/edit/edition.html
Closes #2242 
Make the Metric System as Default for Physical Values of the Book while editing. Most comments in the issue favored the metric system so went with the metric.
Not that much technical, just changed the default to `centimeters` from `inches` and to `kilos` from `grams`.
`docker-compose exec web make test` returned no errors.
@seabelis @cdrini
=> Make Metric System as Default for Physical Values of the Book.

openlibrary/core/models.py, scripts/update_stale_work_references.py
Modified the resolve redirects query from doing batches across all time, to a query-per-day.
Modifying the grace period allows the developer to specify a start offset.
Closes #8778 and follows up on #6511 
This has been run on the last 2 years of redirects on ol-dev1 with e.g.:
```bash
PYTHONPATH=. python scripts/update_stale_work_references.py /olsystem/etc/openlibrary.yml --days=365 --skip=7
```
@mheiman @cdrini
=> improve bulk resolve redirects performance

openlibrary/templates/type/edition/view.html
For some reason `edition.to_isbn10()` and `edition.to_isbn13` seem to be returning the good for nothing `<Nothing>` type in `view.html`.
This commit opts for `None` over other falsy values when setting `isbn_10` and `isbn_13`.
Fix
Try to load a work or edition:
* http://localhost:8080/books/OL20431791M
* https://staging.openlibrary.org/works/OL118388W/Flatland?edition=key%3A/books/OL37044775M.
=> Fix: stop isbns from being `<Nothing>` in `view.html`
