internetarchive/openlibrary

openlibrary/templates/type/author/edit.html, openlibrary/templates/type/author/view.html
… removed as Author.website is now deprecated and will be replaced with the links tab. Fix will remove Author.website UI elements during editing and viewing windows as they are no longer needed
Addresses #8293 
fix
Author.website property has UI elements being built within author/edit.html and author/view.html, these references have been removed so that Author.website elements are no longer built.
View author previously containing a website link on their author page, website link should no longer be visible and when editing author, there should no longer be a website identifier.
@hornc  @jimchamp
=> Removed Author.website UI elements from Author.edit/view templates

openlibrary/templates/lib/header_dropdown.html
Closes #8708.
Feature. Uses an HTML `title` attribute to show the user's username and joined date when they hover over the account icon.
Very simple! Used `ctx.user` to get the relevant data, and replicated the joined date syntax from the `view.html` page. There are definitely fancier ways of making the tooltip that would look more stylish, but for the purpose of simplicity and responsiveness -- and avoiding any awkward tooltip hanging around once the on-click menu is opened -- I figured the `title` attribute would be the best way to go.
Hover over the account icon from any page. After a second or so, a tooltip should appear with the accurate username and user created date.
@mekarpeles @Abhishektharu
=> Add user info tooltip to account icon

.github/workflows/codegen_api_docs.yml, .pre-commit-config.yaml, docker/Dockerfile.olbase, pyproject.toml, requirements.txt, scripts/oldump.py, scripts/setup_gitpod.sh
Update the Docker containers to Debian Bookworm and Python 3.12.
This update is tied to a specific `webpy` commit because although the commit has been merged to master, there is not yet a release. Hence using the git hash in `requirements.txt`.
Because of the webpy changes, the major Python version changes, and changes to the underlying Debian distribution, it would be good to test out as many tasks as possible.
@cdrini
=> Update containers to Python 3.12.2 + Bookworm

openlibrary/plugins/upstream/mybooks.py
Closes #7526
Closes #7572
These now match:
=> Fixed #7526, sort my books by most recent (desc)

static/css/components/cbox.less
Closes #8868 
This PR aims to add the drop shadow to the covers modal
I just copied the previously applied css on the covers here
https://github.com/internetarchive/openlibrary/blob/21b78ad55cbb89a8260d1d4ebe0b1c5daac1c0e8/static/css/components/illustration.less#L14-L15
- Click on any book cover
- Notice the box shadow
Before
After
@RayBB
=> Added: Drop shadow to cover modal

compose.production.yaml, openlibrary/core/ia.py, scripts/manage-imports.py
Refactor. Switches to the archive.org search endpoint for better dev ex and simplicity.
- olsystem side: https://github.com/internetarchive/olsystem/pull/202
- The original code is a bit confusing and littered with variables that do something else than what they say, or which aren't really used. The new code does what the old code did, even if the names now seem like they do something else (eg `since_date` is now just `day`, because the old code wasn't _Actually_ finding all items since that date, it was just finding items from that specific day! See the + 1 day interval chunk).
- I tested the query on past days, and it was usually spot on the exact same results as the previous db query, or more results were returned through the advanced search call. But these would be filtered out …
=> Refactor manage-imports to use advancedsearch endpoint

openlibrary/i18n/sc/messages.po
Fix: I updated the strings from the latest messages.pot file.
After I used the new translation for a bit to test it (on the main website, unfortunately I can't seem to be able to create a docker copy on my machine, I will try again later) I realized that there were some strings missing in the file I translated that were available in other languages. That was probably caused by the fact that I had downloaded the messages.pot file quite some time ago, so I did it again and added all the missing ones (and changed some some already translated ones as well). I hope it works fine.
=> Update Sardinian strings from latest messages.pot

openlibrary/core/lists/model.py
Closes #8882 
Fix.
Thanks to @cdrini for very quickly figuring out the problem.
When there is a cache miss with a list containing a redirect, `Seed.from_db()` is called with a `client.Thing` type, but the logic didn't handle this.
Create a list with a redirected item on it (e.g. by adding an item to the list and merging). Note: you cannot have the non-redirected version of the item on the same list or the error won't occur.
Try viewing the profile page of the account with the relevant list before and after applying the PR.
Before:
After:
@RayBB 
@cdrini
=> Fix: `Seed.from_db()` now handles `client.Thing` types

static/css/layout/index.less
Closes #8839 
Fixed Links and code section overflow in API Documentation pages.
Added ```word-wrap: break-word```  property to ```div#contentBody``` to solve the issue.
@jimchamp
=> Fixed Links and code section overflow in API Documentation pages

static/css/components/tagging-menu.less
This css was leaking and applying to the entire site. We don't want thin scrollbars everywhere.
- Also fix thin scrollbar only work on Chrome.
- Also fix thin scrollbar in tagging menu appearing when unnecessary.
Before:
(note thin scrollbars in body, sidebar)
After:
(normal sized scrollbars)
=> Fix thin scrollbar being applied to entire site

openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/js/covers.js, openlibrary/plugins/openlibrary/js/edit.js, openlibrary/templates/books/edit/excerpts.html, openlibrary/templates/books/edit/web.html, openlibrary/templates/covers/add.html
Closes #8848.
Fix. Makes string translation possible by internationalizing and moving text from JavaScript to HTML.
Very simple and easy to replicate in similar PR's! Of the various `data-i18n` examples in the codebase, the one I liked most and went with involves just:
1. Adding i18n strings to the top of the HTML file, i.e.:
```
$ i18n_strings = {
$ "empty_excerpt": _("Please provide an excerpt."),
$ "over_wordcount": _("That excerpt is too long.")
$ } 
```
2. Adding the strings as an attribute to the div where the text will be displayed: `data-i18n="$json_encode(i18n_strings)"`
3. In the JavaScript, replacing the plain string with a call to the `data-i18n` attribute:
```
const i18nStrings = JSON.parse(document.querySelector('#excerpts-errors').dataset.i18n);
if (!data.excerpt) {
return …
```
=> Move untranslated strings into `data-i18n` attributes

openlibrary/templates/books/edit/edition.html
Closes #8825 
feature of having **markdown controls on edition description** field on edit
markdown class has been added to the textarea input of **edition description**, it enables JS to show controls above the input **edition description**
click on edit button of a book to reproduce, you can directly visit [Book URL](http://localhost:8080/books/OL7361700M/Three_Cups_of_Tea/edit?work_key=/works/OL5702375W) directly to open a book in edit mode.
@bitnapper
=> Added markdown control buttons to edition description

openlibrary/plugins/openlibrary/support.py, openlibrary/templates/support.html
Closes #8890
Replaces "Topic" drop-down with a "Subject" input on our `/contact` page.
Subject lines for support emails will read:
`Support case *{subject}*`
... where `subject` is the given subject string, truncated to 60 characters, or `[no subject]` if the field was left blank by the submitter.
The following cases have been tested:
1. Sending a support email with no subject
2. Sending a support email with a subject shorter than 60 characters
3. Sending an email with a subject longer than 60 characters
=> Add free-form subject field to contact form

openlibrary/plugins/admin/code.py
Closes #8473
Wraps `create_ol_subjects_for_ocaid` call in a `try/except` block.  If any edition is not added to the staff picks, an error message for that edition will be included in the handler's `json` response.
=> Handle "Add to staff picks" errors

openlibrary/templates/viewpage.html
Revert button styling on Edition pages shows link which should be hidden
Closes https://github.com/internetarchive/openlibrary/issues/2282
Fix
Is a quick fix to the duplicate revert buttons bug where there was two revert buttons instead of one.
1. docker compose up
2. http://localhost:8080/
3. Go find a book
4. Make Edit on book
5. Click History
6. Click previous version
7. Look at side to see revert button
@jdlrobson
=> Removed duplicate revert button

scripts/affiliate_server.py, scripts/tests/test_affiliate_server.py
When checking `/status` on the affiliate-server, *if* there is an item in the queue, rather than display the count, the server would respond with a rather verbose error because to display items in the queue, they must be first serialized via `json.dumps`, but prior to this commit, the `PrioritizedISBN` class could not be serialized, and the queue contains only `PrioritizedISBN` items.
For reference, here is what would happen:
```
172.28.0.1:59064 - - [15/Mar/2024 22:20:29] "HTTP/1.1 GET /status" - 500 Internal Server Error
File "/home/openlibrary/.local/lib/python3.12/site-packages/web/application.py", line 276, in process
return self.handle()
^^^^^^^^^^^^^
File "/home/openlibrary/.local/lib/python3.12/site-packages/web/application.py", line 267, in …
```
=> Fix: add `.to_dict()` method to `PrioritizedISBN` for serialization

conf/openlibrary.yml, openlibrary/plugins/openlibrary/api.py, openlibrary/plugins/upstream/account.py
Closes #8814 
This PR addresses the issue where the Yearly Reading Goal banner reappears upon each login. The solution involves persisting the banner preference on the User, preventing the banner from displaying every time a user logs in.
- Dismiss the "Your Reading Goal" banner 
- You can monitor browser storage for the respective cookie starting with "yrg" stored locally
- Remove the cookies or open another browser
- Log in and check the "yrg" cookies being stored as per the user preference leading to no display of the YRG banner
@jimchamp
=> Persist Yearly Reading Goals banner preferences

.github/pull_request_template.md
I think this improves the PR template just a bit for new contributors.
Posted about this in slack [here](https://internetarchive.slack.com/archives/C0ETZV72L/p1710932131829919).
=> Update pull_request_template.md to mention tagging lead

stories/README.md
Fixes the link to storybook, before it lead to a 404 page
=> fix storybook link

.gitpod.yml
A small improvement by adding names to ports for gitpod users :)
Docs: https://www.gitpod.io/docs/configure/workspaces/ports#specify-port-names--descriptions
<details>
<summary>Before</summary>
</details> 
<details>
<summary>After</summary>
</details>
=> add gitpod port names

static/css/components/header-bar.less
Closes #8943 
This PR makes the sidebar cover the entire height instead of leaving top and bottom space. It also removes the linear gradient of the bg mask and bring a solid black translucent mask covering the entire screen uniformly 
- Switch to small screen display and click the hamburger icon
@RayBB
=> Update: Sidebar height and top margin and remove bg mask gradient

openlibrary/templates/type/edition/view.html
Closes #8983
Checks for a work key before rendering the work list showcase on book pages.
On orphaned edition book pages, an `IndexError` was being thrown by the `get_seed_info` call in `lists/widget.html`, [here](https://github.com/internetarchive/openlibrary/blob/7755d8cc3a392740cca35e8539eccc23749270fc/openlibrary/templates/lists/widget.html#L16).  In these cases, a dummy `Work` object, which has an empty string as its `key`, is passed to `get_seed_info`, which requires a `Thing` with a non-empty string to function correctly.
Since the dummy `work` object is truthy, we also have to check for a `work.key` before rendering the work list showcase.
1. Visit an orphaned edition's book page.  Ensure that there are no error messages rendered on the page ("Lists" section and flash message).
2. …
=> Check for work key before rendering list showcase

openlibrary/plugins/worksearch/schemes/__init__.py
Closes #8965 .
- Viewing https://testing.openlibrary.org/search?q=subject%3A("Reading+Level-Grade+11"+OR+"Reading+Level-Grade+12")+first_publish_year%3A[2000+TO+*]&sort=random.hourly returns the same results when refreshed or until the hour changes
- https://testing.openlibrary.org/search?q=subject%3A(%22Reading+Level-Grade+11%22+OR+%22Reading+Level-Grade+12%22)+first_publish_year%3A[2000+TO+*]&sort=random.hourly_1 has the same behaviour, but displays a different random than the above.
Note: Solr has a caveat that the order might change more frequently if the documents are edited.
@RayBB
=> Add ability to sort by different seeds of hourly/daily randoms

docker/Dockerfile.oldev
Fix. Fixes bug that was preventing successful runs of the `i18n` script to `extract` messages in Docker by ensuring Docker installs the `git`-installed version of `web.py` if that is what is in `requirements.txt`.
Currently Docker runs of the script are causing `TokenError`s as a result of a mismatch between Python 3.12 and the `web.py` version, which was solved in a recent `web.py` git commit, but not in the latest release.
1. Start a Docker container
2. Run the following command: `docker compose run --rm -uroot home ./scripts/i18n-messages extract`
A new `messages.pot` file should be generated!
@cdrini
=> Allow Docker to install `web.py` from git rather than latest release

static/robots.txt
Closes #8959 
I'm seeing these a lot in the nginx logs lately, and they waste our crawl budget (~24%!) as well as cause unnecessary traffic to the site. So let's block 'em!
=> Block .rdf from Googlebot crawling in robots.txt

openlibrary/plugins/openlibrary/js/carousel/Carousel.js
Closes #8906
Restores "next" and "previous" page buttons to the work `add-cover` carousel.
An input with name `carousel-i18n-strings` does not exist on the work's add-cover page.  This caused an error during instantiation when i18n strings were parsed, preventing the `Carousel` from being created.
Now, we check for the `carousel-i18n-strings` input before attempting to parse its value.
@seabelis
=> Fix work's `add-cover` carousel

openlibrary/utils/dateutil.py
=> add typehints to dateutil.py

.gitpod.yml
Noticed these prebuild settings are deprecated. Prebuilds must be manually turned on [here](https://gitpod.io/repositories/b5c70fe2-e964-42ca-9992-4789b4134624) by someone with webhook permissions. As such, we don't need this part of the config file anymore.
Changed in Oct 2023: https://www.gitpod.io/changelog/simplified-prebuilds-defaults
I suppose you could open this PR in GitPod but really no testing needed.
=> remove old gitpod prebuild config

openlibrary/components/MergeUI/EditionSnippet.vue
A very tiny improvement to the MergeUI so the images don't have a white space under them.
| Before                                      | After                                      |
|---------------------------------------------|--------------------------------------------|
| ![image](https://github.com/internetarchive/openlibrary/assets/921217/29452704-ed1d-4dab-b42b-fe90666a3804) | ![image](https://github.com/internetarchive/openlibrary/assets/921217/07d30eb9-e51c-405d-9d69-6413d24d23ed) |
=> improve image height for mergeUI

openlibrary/i18n/it/messages.po
Closes #
This is causing a `KeyError` on Italian `/account/create` pages (example Sentry event [here](https://sentry.archive.org/organizations/ia-ux/issues/363272/?query=is%3Aunresolved&referrer=issue-stream)).
=> Fix incorrect `msgstr`

docker/README.md
Recently a few people have experienced an error similar to:
```
/openlibrary/openlibrary/templates/home/index.html: error in processing
template: ConnectionError: HTTPConnectionPool(host='solr', port=8983):
Max retries exceeded with url: /solr/openlibrary/select (Caused by
NameResolutionError("<urllib3.connection.HTTPConnection object at
0x77a95c4e7f90>: Failed to resolve 'solr' ([Errno -2] Name or service
not known)")) (falling back to default template)
```
This commit details one way to address this, as well as providing some context.
@RayBB 
@benbdeitch
=> Documentation: add docker troubleshooting when unable to connect to solr

openlibrary/templates/books/edit.html
Follow up to @jimchamp comment here https://github.com/internetarchive/openlibrary/pull/8946#pullrequestreview-1974487251
I'm still investigating making the edit button on the works/editions page direct to the correct place but that'll be a separate pr 👍
=> make edit button return to correct place

openlibrary/plugins/upstream/mybooks.py
Closes #8917
Avoids error that occurs when a private reading log page is visited.
Also, sets default fall-back value of `MyBooksTemplate.counts` to an empty `dict`.  This doesn't fix anything, but should give developers an indication, with a cursory glance, that this property is meant to be a `dict`.
Today, whenever a private reading log page is visited, the default `mb.counts` value is an empty list.  The reading log view handler attempts to set the values of `KEYS_TITLES` by accessing `mb.counts` with a key, which causes an error when `mb.counts` is a list.  The PR sets `KEYS_VALUES` inside of the conditional that checks if the page is viewable, avoiding the error altogether.
1. Open a private browser window, and navigate to a private reading log page.  Ensure that you are redirected to …
=> Fix private reading log errors

openlibrary/plugins/openlibrary/js/ia_thirdparty_logins.js, openlibrary/plugins/upstream/account.py
Closes #9019
Shows error message on Google sign-in failures.
If the response from the `/account/login.json` call is ok, we immediately redirect to the patron's account page (this is BAU).  Otherwise, we display the localized error message in a newly created `.note` `div`.
The `account/login.json` handler has been updated to return a JSON string containing the error short code and the localized error message when a `BadRequest` is raised.  Previously, only the error short code was returned in these cases (it wasn't even JSON encoded...).
Recommend testing this before #8980 is deployed and tested.
1. Delete an existing IA account that was created using Google sign-in.
2. Re-create the IA account using the same Google account.
3. Attempt to log into OL using Google sign-in.  If you see an …
=> Show error message on Google sign-in failure

openlibrary/accounts/model.py
Closes #8696
Re-establishes linkage between existing Open Library account and an IA account that has been deleted but later recreated using the same email address.
Publishes an "IA <-> OL itemname mismatch" event to sentry, which includes the old and new `itemname`s in the "Additional Details" section (as `ol_itemname` and `ia_itemname`, respectively).
`logger.error` calls automatically publish events to Sentry (details [here](https://docs.sentry.io/platforms/python/integrations/logging/#verify)).  Such event, however, do not contain the entire stacktrace.  Additional data that is included in the `extra` dict will appear in the event's "Additional Data" section.
> [!important]
> I've only included the old and new `itemname` in these Sentry events.  Will this be enough to determine if …
=> Link new IA accounts to existing, previously linked OL account

openlibrary/templates/type/user/view.html
Closes #8905
When viewing a profile page, the history table will now only be rendered page owners and members of any of the following usergroups:
`admin`
`librarians`
`super-librarians`
While logged out:
1. Visit as many profile pages as you like, ensuring that there is no history table at the bottom of the page.
While logged in with a non-admin account:
1. Visit your account's profile page.  Ensure that the history table **is** rendered.
2. Visit any number of other profile pages.  Ensure that the history table **is not** rendered.
While logged in with an admin or librarian account:
1. Visit your account's profile page.  Ensure that the history table **is** rendered.
2. Visit any number of other profile pages.  Ensure that the history table **is** rendered.
_Desktop view when history …
=> Show profile page history table conditionally

openlibrary/plugins/openlibrary/code.py, openlibrary/plugins/openlibrary/processors.py
Closes #8893
Prevents unauthorized access to patrons' preferences.  Instead, patrons will be able to access their own preferences, while admins can access all patrons' preferences.
These changes include access to `json` and `yml` encodings of patron preferences, not just the preference pages.
A new processor was created to aid with authorization.  The `PreferenceProcessor`, when handling a request for patron preferences, gets a reference to the authenticated `User`.  If the request was unauthenticated, a `401` error is raised.  Then, the processor checks if the `User` is the owner of the requested preferences, or is an admin.  If neither are true, a `403` error is raised.
If all checks pass, or the request is not for preferences, the processor handles the request as per usual.
At a …
=> Preference authorization processor

openlibrary/catalog/add_book/__init__.py, openlibrary/catalog/add_book/tests/test_add_book.py
Closes #8969
Certain import sources, such as Amazon and BWB, have `publish_date` values that are known to be suspect, such as `1900` or `January 1, 1900`.
This commit removes the `publish_date` value from those import records prior to import.
Specifically, the `publish_date` value is removed in the following situations:
1. The import record has a `source_record` value starting with `amazon`, `bwb`, or `promise`; and
2. the `publish_date` is either `1900` or `January 1, 1900`.
I want to verify the above above conditions for removal are correct.
See the unit tests.
@mekarpeles 
@judec 
@hornc
=> Feature: remove suspect `publish_date` values from AMZ/BWB

openlibrary/i18n/es/messages.po
Spanish translation updated according to the latest changes in English.
The translated text inside the button exceeds the limits of the button. I have adapted Spanish translation: instead of the literal translation "Leyendo actualmente" (Currently Reading), I have translated it as "Leyendo" (Reading), using the same solution that was given for similar conflicts with the length of the text inside the button (see #5754).
=> Update Spanish translation

openlibrary/templates/lib/nav_head.html
Ever notice how every time you go to a page on OL the search bar selector flickers a bit?
<details>
<summary>Current issue</summary>
</details> 
Well this will fix it. At least for all the users that keep it set to the default of All.
<details>
<summary>After this PR</summary>
</details>
=> set All as default for search bar

openlibrary/macros/databarHistory.html, openlibrary/macros/databarTemplate.html, openlibrary/macros/databarView.html, openlibrary/templates/admin/profile.html, openlibrary/templates/type/edition/compact_title.html
Closes #9012
Modifies the Alt text for the History button from Template to Page.
@RayBB
=> Modified alt text from Template to Page

static/openapi.json
Closes #8474
Add warning about OpenAPI definitions that swagger only includes subset of api and people should view developer's docs for the full set.
Adds more to open library swagger docs page adding disclaimer that it is not all of the docs.
1.  docker compose up
2. http://localhost:8080/
3. Go to add swagger/docs#/ to url or http://localhost:8080/swagger/docs#/
4. View changed swagger docs page
Before
After
@RayBB
=> Added warning about OpenAPI definitions

openlibrary/macros/databarEdit.html
We don't use capital E anyone else really. Looked out of place here.
=> fix unneeded capitalization

openlibrary/templates/type/author/view.html
Closes #
Naive solution for these Sentry [events](https://sentry.archive.org/organizations/ia-ux/issues/469294/events/c61d5ccdbd4044f3ba471874a36da3f1/events/?project=7&referrer=events-table%2F%3Fenvironment%3Dproduction&statsPeriod=14d).
`books.num_found` can sometimes be `None`.  This change creates a new `num_found` variable that hold the immutable `books.num_found` value, or 0 if none exists.
This [page](https://openlibrary.org/authors/OL120205A/Marcel_Proust?has_fulltext=true&q=1%C0%A7%C0%A2%252527%252522%5C%27%5C%22&debug=true) fails to load in production, but works in testing with this branch deployed.
=> Set default author book count to zero

docker/ol-solr-updater-start.sh
Closes #8851 
Keeps the code aligned with the Jenkinsfile.
Also it seems a little faster?
Start OL. You can follow the steps here if you really wanna see the OSP items there.
https://github.com/internetarchive/openlibrary/pull/8395
@cdrini
=> Refactor ol-solr-updater-start.sh to use wget --no-clobber

openlibrary/templates/history/sources.html
Partially closes #8589.
Include `osp:` as a source record and point to ISBNdb, as it is the source of data for OSP-sourced imports.
Pursuant to #8589 we want to import ISBNdb records, based on ISBNs from OSP that are not already in Open Library. We also want to track these records, so we settled on including `osp:<isbn_13>` in the `source_records` field. But if it's in the source records field, we should handle it 'properly' as a source record so it doesn't falsely display as a MARC record instead.
Note, `osp:` will currently only show in an import record if (1) we 'fix' the import sources history so it doesn't always display the last source record, or (2) `osp:` isn't the last source record.
Currently OSP records have been imported with the `idb:` source record as last, so it displays. …
=> Feature: add osp as import source

Readme.md, Readme_chinese.md
Closes #8985 
* Remove unneeded cd
* Use `run --rm` so it can be executed as a standalone command and to match the testing wiki commands
* Replace `pytest` with `docker` as `make test` also involves javascript tests
Closes #
@scottbarnes
=> Update testing command in the readmes 

openlibrary/core/models.py
Closes #
Removes unused and obsolete method for determining if a patron has access to librarian tools.
> [!NOTE]
> After deployment, this [usergroup](https://openlibrary.org/usergroup/librarian-tools) can be removed.
=> Remove unused `User` method

openlibrary/core/bookshelves.py, openlibrary/plugins/upstream/mybooks.py
Closes #8852 . The readinglog APIs were fetching with a default of 5000. That's too much for a default, so reduce that to 100. Also add a total `numFound` field to the response to make pagination easier.
Note this is a BREAKING CHANGE to a public API, but I think it's required for healthy site/solr performance. Also because of the bug in #8852 , it would error if you tried to get a lot of books in one go anyways.
- Reading log loads only 100 items: https://testing.openlibrary.org/people/mheiman9541/books/already-read.json
- Pagination works https://testing.openlibrary.org/people/mheiman9541/books/already-read.json?page=5
@mheiman
=> Reduce default limit of readinglog API to 100

openlibrary/plugins/upstream/account.py
Closes #9068 
Follow-up to #8980
Removes unused `LOGIN_ERRORS` entries.  The last reference to `wrong_ia_account` was removed in #8980.  While removing this, I found that `ia_login_only` is also not referenced in the codebase, so it has also been removed.
=> Remove unused login errors

openlibrary/plugins/openlibrary/code.py
Closes #8964
This PR aims to extract valid isbns from the ```/isbn/{isbn}``` path to avoid unnecessary manual stripping of unwanted characters in {isbn}
- log the isbn in the isbn_lookup's GET method and notice the stripping of unwanted characters of from the isbn
- go to http://localhost:8080/isbn/_9781554042951_
@RayBB @scottbarnes
=> Updated regex 'path' of isbn and added canonical to have correct isbn

openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/js/waitlist.js, openlibrary/templates/account/loans.html
Closes #8378
I don't know locate a book that is waitlistable to test better. However, I have a book on my waitlist from long ago. The testing plan is:
1. Demonstrate the functionality of the "Leave Waitlist" button on the Open Library testing platform, accessible at https://testing.openlibrary.org/account/loans.
1. Deploy a version of the application to the testing environment that temporarily removes this functionality. This step is crucial for observing the impact of the removal on the user experience.
1. Deploy a refactored version of the application to the testing environment. This deployment aims to reintroduce the "Leave Waitlist" functionality, ensuring that it operates as expected and maintains consistency with the previous version.
This plan will be shown via the screen recording …
=> remove inlinejs for waitlist

conf/openlibrary.yml, openlibrary/plugins/upstream/code.py
I was poking around looking at https://github.com/internetarchive/openlibrary/issues/2340 and found this code for getting the jquery urls. I'm pretty sure this is long dead. I couldn't find a single reference to any of these variables or urls and I doubt if we've loaded from a CDN for a long time.
=> remove setup_jquery_urls

openlibrary/i18n/__init__.py, openlibrary/i18n/messages.pot, openlibrary/plugins/upstream/account.py
Closes #8967
@RBrar66 and I worked on this fix together, he was struggling w/ build set up. we go to the same school.
should fix the described issue with non-localized error messages, following the example of @rebecca-shoptaw 
we thought that simply changing the formatting of the strings would be enough, but ran into this error:
we were able to pass test cases by adding an empty fallback value `load_translations(getattr(web.ctx, 'lang', ''))`
please let me know if this is the correct approach, or why we would be getting this error when attempting to format the strings in the `LOGIN_ERRORS` dictionary.
in addition, the strings in the dictionary auto-formatted on commit - I am assuming this is how they are supposed to be according to the style guide but I thought it was more readable being …
=> internationalized login errors

openlibrary/templates/work_search.html
Closes #9054
Feature
Added another check for librarians when displaying the edition search checkbox
Logged in as AccountBot and searching something, the "solr edition" checkbox should not be visible. After adding AccountBot as a librarian, the checkbox should be visible.
Before Adding AccountBot as librarian:
After Adding AccountBot as librarian:
@RayBB 
@seabelis
=> allows librarians to view edition search

openlibrary/plugins/upstream/account.py
Closes #7985. 
Feature. Adds "Title" and "Author(s)" fields to star rating CSV.
**Note**: Switched to a draft while I fix a quick circular import issue. 
Reused logic from `generate_reading_log`, extracting two helper functions -- `escape_csv_field` and `get_work_from_id` -- to use in both places.
1. Log in (if not logged in)
2. Give at least one book a star rating
3. Go to `/account/import`
4. Download star ratings in CSV format; the file should include work title and author info
@jimchamp
=> Add title and author to star ratings CSV exports

openlibrary/plugins/openlibrary/js/ia_thirdparty_logins.js
Closes #9108
Sets the default redirect value for Google sign-in to `/account/books`, the "My Books" page.
This conforms with our default redirect value for email and password authentication, set here:
https://github.com/internetarchive/openlibrary/blob/2ca79bd87b458c40f6ceb6746063aab45bf900e8/openlibrary/plugins/upstream/account.py#L455-L456
1. Visit the log in page, and sign-in using your Google account.
2. Ensure that you're redirected to the "My Books" page.
=> Go to "My Books" page on Google sign-in

openlibrary/templates/history/comment.html, openlibrary/templates/history/sources.html
Partially closes #8623.
Pursuant to #8623, we will be importing some items with metadata based on OpenAlex's dataset, so this commit adds an OpenAlex data source.
Look at an item imported with a `source_records` value including, e.g., `openalex:W12345689`. Clicking on the link in "Imported from OpenAlex" line should take you to the OpenAlex page for that identifier.
Before this PR:
After this PR:
=> Feature: add OpenAlex as a source record

scripts/gh_scripts/issue_comment_bot.py
Closes #9113
Our recent changes to the `issue_comment_bot` script are [breaking](https://github.com/internetarchive/openlibrary/actions/runs/8750728637/job/24014837209), as the results of `filter_issues` do not have the issue number.  This PR adds the issue number to the results.
`filter_issues` is a poor name for the function, as it returns a list of newly created objects containing only the data that is needed for the Slack comment, not the whole `issue` object itself.  Is there a better name for `filter_issues`?
=> Add issue number to `filter_issues` results

compose.infogami-local.yaml, compose.override.yaml, compose.production.yaml, compose.staging.yaml, compose.yaml
Closes #9092
Fix
Removed "VERSION" tags from docker compose files
@RayBB
=> Remove version tags

openlibrary/plugins/openlibrary/js/autocomplete.js, openlibrary/plugins/worksearch/autocomplete.py
Closes #9111
Removes `timestamp` because it is not used and would mess up caching.
Compare the speed of language on prod and testing for a work like 
- https://testing.openlibrary.org/books/OL24938286M/Pacific_Vortex!/edit
As far as I can tell, it is drastically faster.
=> improve language autocomplete speed

openlibrary/catalog/add_book/__init__.py
Closes #9137.
Addes `1900-01-01` to the list of dates that will be cleared for AMZ/BWB imports because this seems to be a date added when the true `publish_date` is unknown.
Other checked dates not included because they didn't seem to be a problem:
- https://openlibrary.org/query.json?type=/type/edition&publish_date~=1-1-1900 (none)
- https://openlibrary.org/query.json?type=/type/edition&publish_date~=01-01-1900 (none)
- https://openlibrary.org/query.json?type=/type/edition&publish_date~=01/01/1900 (none)
- https://openlibrary.org/query.json?type=/type/edition&publish_date~=1/1/1900 (one entry)
- https://openlibrary.org/query.json?type=/type/edition&publish_date~=1900-1-1 (none)
Import something with a `publish_date` of `1900-01-01` and that `publish_date` should be removed. I didn't …
=> Fix: add 1900-01-01 to AMZ/BWB suspect publish_date list

.github/workflows/new_comment_digest.yml
Closes #9113
I noticed that the `Needs: Response` label wasn't being added to issues with new comments.  Turns out that we were missing the correct permissions for adding labels.
See documentation for the [add label endpoint](https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#add-labels-to-an-issue) for more details.
=> Add permissions for labeling issues

.github/workflows/new_comment_digest.yml, scripts/gh_scripts/issue_comment_bot.py
Closes #9143
Adds `--verbose` and `--no-labels` flags, and makes the Slack token and channel optional arguments. Digest will only be published to Slack of both the token and the channel are present when the script is called.  Our `new_comment_digest` action has been updated to accommodate these changes.
If the `--no-labels` flag is included, https://github.com/internetarchive/openlibrary/labels/Needs%3A%20Response labels are not added to the issues.
Detailed information about each identified issue is printed to `stdout` whenever the `--verbose` flag is included.
=> Allow `issue_comment_bot.py` to run without updating issues or publishing Slack digest

requirements.txt
Closes: #9145
Fixes a high severity bug that didn't apply to our current setup, but had the potential be quite severe. This update may also increase performance.
Release notes:
https://docs.gunicorn.org/en/stable/news.html#id1
@cdrini
=> Update `gunicorn` to 22.0.0

openlibrary/catalog/add_book/__init__.py, openlibrary/catalog/utils/__init__.py, openlibrary/core/models.py, openlibrary/core/vendors.py, openlibrary/plugins/books/dynlinks.py, openlibrary/plugins/importapi/code.py, openlibrary/plugins/openlibrary/code.py, openlibrary/tests/catalog/test_utils.py, openlibrary/tests/core/test_models.py, openlibrary/utils/isbn.py, openlibrary/utils/tests/test_isbn.py, scripts/affiliate_server.py, scripts/manage-imports.py, scripts/promise_batch_imports.py, scripts/tests/test_affiliate_server.py
Closes #9030.
Note for the reviewer. The commits should be meaningful such that stepping through them and reading the commit messages may be the easiest way to review this. Maybe.
One question: when do we want to look to `staged` BookWorm/Amazon data to supplement empty fields? In the current state of this PR it's doing that if an incoming `rec` (i.e. a record to be imported) has a `B*` ASIN in either `source_records`, which it gets if imported via `/isbn`, or if it has an ASIN in the `amazon` key of an `identifier` (such as in the case of a BWB promise item) *and* there's a `staged` item with a matching ASIN.
If this is too broad, one way to restrict it could be attempt supplement only if an ISBN is absent. Currently the attempt to supplement happens if there's a `B*` ASIN in …
=> Augment non-ISBN ASIN BWB records with BookWorm data

openlibrary/plugins/openlibrary/js/validate.js
Closes #9136 
Fixes a bug where users were able to add books without titles by putting only whitespace characters into the required title field.
Adds a regex check in `plugins/openlibrary/js/validate.js` to the `title` class used by `templates/books/add.html` that ensures the title input contains at least one non-whitespace character.
1. Go to the 'Add Book' page
2. Attempt to add a book with a title containing only whitespace characters (i.e. matches `/\s+/`)
3. Observe that the action is not successful and the title input box is red
@cdrini
=> Add whitespace validation for book titles

openlibrary/templates/type/edition/view.html, static/css/base/headings.less, static/css/components/carousel.less, static/css/components/edit-toolbar.less, static/css/components/editions.less, static/css/components/link-box.less, static/css/components/readerStats.less, static/css/components/work-title-and-author.less, static/css/components/work.less, static/css/less/font-families.less
Work towards #8692.
A uniform font size for the Open Library application.
Initially, we are updating a portion of the app, the works page. 
| -- | -- |
| ![Screenshot 2024-03-22 at 12-43-18 The Memoirs of Sherlock Holmes by Arthur Conan Doyle Open Library](https://github.com/internetarchive/openlibrary/assets/6251786/4bea5a6d-6642-417f-be5b-8af5c892d073) | ![Screenshot 2024-03-22 at 12-43-31 The Memoirs of Sherlock Holmes by Arthur Conan Doyle Open Library](https://github.com/internetarchive/openlibrary/assets/6251786/b7ea665c-bfc8-4310-ace1-797d26ff9782) |
crossed out in read are the updated classes using our new font size variables instead of static numbers
=> Standardize font sizes on works page

openlibrary/plugins/openlibrary/api.py
Closes #9152
Related to this Sentry [issue](https://sentry.archive.org/organizations/ia-ux/issues/274622/?query=is%3Aunresolved&referrer=issue-stream).
Immediately redirects to login page when an unauthenticated request to the notes update handler is made.
=> Redirect immediately on unauthenticated note update request

openlibrary/templates/publishers/view.html, openlibrary/templates/subjects.html, openlibrary/templates/type/author/view.html, static/css/components/link-box.less, static/css/components/work.less, static/css/layout/v2.less
Addendum to #8931 . A few of the classes sizes were being used on other pages, causing them to appear odd. Also the TOC was accidentally might smaller. Mostly removed CSS which no longer made sense, and DRY'd the way the link-boxes were rendered (although this could be DRY'd quite a bit more).
The `link-box` is the css component name we give to the e.g. "SUBJECTS: Horror, Fantasy, ..." block. It appears on author pages, book pages, and on subjects/publisher pages.
TOC before/after:
link-box before/after
=> Fix links on subjects page font size too large, TOC too small

scripts/dev-instance/dev_db.pg_dump
In support of #8607
Adds the `follows` table and related indices to local dev environments.
Commands used to generate dump:
```
docker compose exec -uroot db bash
./openlibrary/scripts/dev-instance/create-dev-db-pgdump.sh > /openlibrary/scripts/dev-instance/dev_db.pg_dump
```
=> Add `follows` table to local dev environment

openlibrary/core/bookshelves.py, openlibrary/core/follows.py, openlibrary/core/models.py, openlibrary/core/schema.sql, openlibrary/macros/Follow.html, openlibrary/macros/SearchResultsWork.html, openlibrary/plugins/openlibrary/api.py, openlibrary/plugins/upstream/account.py, openlibrary/plugins/upstream/mybooks.py, openlibrary/templates/account/follows.html, openlibrary/templates/account/privacy.html, openlibrary/templates/account/reading_log.html, openlibrary/templates/account/sidebar.html, openlibrary/templates/account/view.html, openlibrary/templates/books/mybooks_breadcrumb_select.html, static/css/components/mybooks-details.less, static/css/components/mybooks.less, static/css/legacy.less
* Followup to #8597, closes #1966 (previous PR) and implements #739
closes #739
- database schema for follows
- adds core model for follows
- elementary mybooks /feed of followers
- ability to follow/unfollow
- json API to fetch patron's follows
**My Feed** (private)
**My Followers** (public)
**Following** (public)
**Schema already on production db**
- There are still valuable pieces from #1966 which we should consider implementing, like the [people I'm following page](https://github.com/internetarchive/openlibrary/pull/1966/files#diff-640b35cc042bf968b008b029cc8c77593cb5b668d22fa787cef684d31b4937f9) even if this is private
using with the following code:
```
+++ b/openlibrary/templates/type/edition/view.html
@@ -338,6 +338,13 @@ $ worldcat_links = macros.WorldcatLink(isbn=isbn_13 or …
```
=> Adds follow (pubsub) feature

conf/solr/haproxy.cfg
It's an alias for `option httpclose`, which we specify a few lines up.
See https://cbonte.github.io/haproxy-dconv/1.9/configuration.html#4.2-option%20forceclose
Patch deployed to fix haproxy not starting up due to the now invalid option.
=> Fix: option forceclose removed in latest haproxy

Readme.md
Trivial change to README to add contributors tag; no issue created as this is a minor enhancement/convenience to offer validation that our community is active :) 
You can see it working here:
https://github.com/internetarchive/openlibrary/blob/2c96889241b55967db8f0a1078fe80db2bf8f6e1/Readme.md
=> add contributors tag to README

openlibrary/templates/account/reading_log.html, openlibrary/templates/lists/list_overview.html
Addendum to:
- #9025 - Displaying "from You" for all lists, not just own
- #8607 - This PR uses the readinglog_item strings in the URL, so will need those to be not internationalized: https://github.com/internetarchive/openlibrary/blob/d6dcacce55185a851c446173fb16bd9aee702dc3/openlibrary/macros/SearchResultsWork.html#L50
=> Fix some i18n-related bugs

openlibrary/plugins/openlibrary/code.py, openlibrary/templates/search/sort_options.html
Closes #9186
Only shows the "Shuffle" sort option for non-bot user agents.
=> Update bot useragents + hide shuffle link for bots

.pre-commit-config.yaml, openlibrary/i18n/__init__.py, openlibrary/i18n/messages.pot, openlibrary/macros/ManageWaitlistButton.html, scripts/i18n-messages
Closes #8818.
Feature. Automates generation of new `messages.pot` file for translation whenever Python or HTML files that affect `i18n` strings are changed.
The implementation is in two parts and mainly confined to two files:
1. `pre-commit-config.yaml` -- Added a new `pre-commit` local hook that runs the `./scripts/i18n-messages extract` script to generate a new `messages.pot` file and is activated by changes to Python or HTML files.
**Note:** This hook has a few dependencies will need to be updated to match the current version when we update `Babel`, `multipart`, and/or `web.py`.
2. `__init__.py` in `openlibrary/i18n` -- Wrote new logic into the message extraction function, using a straightforward `symmetric_difference` compare between the old and new `i18n` messages to make sure that …
=> Add messages.pot update script to pre-commit.

static/offline.html, static/status-500.html
Closes #9097
fixed a syntax bug 
removing the $(" ") and $(' ') from the necessary lines (the page is static HTML, and does not have access to the Python gettext function that the $_(" ") is supposed to call, so there is no need to use the syntax)
1.Go to any page on the Open Library site 
2.Turn off your wifi
@rebecca-shoptaw
=> Fixed i18n syntax errors by removing \$_("") in 2 files

openlibrary/i18n/__init__.py
Closes #9208.
Fix. Prevents unnecessary merge conflicts in auto-updated `messages.pot` file by setting `POT-Creation-Date` to a fixed date. 
The date and timezone was selected to exactly match the creation date we have currently, so no date-based merge conflicts should occur, including with this PR.
1. Locally, with `pre-commit` installed, make a temporary change to the site text (i.e. adding or removing a word) and do a test commit
2. The `generate POT` method will auto-generate a new `messages.pot` file
3. Look at the `messages.pot` file diff and confirm that the only change in it is the text change (i.e. the creation date field remains the same)
@cdrini
=> Add fixed creation date to POT file

openlibrary/core/models.py, openlibrary/core/schema.sql, openlibrary/core/wikidata.py, openlibrary/i18n/messages.pot, openlibrary/plugins/wikidata/__init__.py, openlibrary/templates/authors/infobox.html, openlibrary/templates/type/author/edit.html, openlibrary/templates/type/author/view.html, openlibrary/tests/core/test_wikidata.py, static/css/components/author-infobox.less, static/css/page-user.less
[Wikidata Project Google Doc](https://docs.google.com/document/d/1-xAija9Pfhtwc-wCAgERHBx6GvFv40Hb-nfHd9f6SPc/edit)
In short, this PR enables us to start fetching info from wikidata and showing it on the author pages.
- For patrons, we only fetch missing items (and bust cache) when they visit the edit page.
- This has the unfortunate side effect that if they add a wikidata id, it won't be loaded until the next time the edit page is visited. That is okay for this v0 because in v1 we will bulk upload the wikidata and then remove this restriction. We have this restriction now so we don't overload wikidata with requests at go live.
- The date has also moved from under the name to the infobox for patrons.
- For librarians, we fetch missing items on the view/edit pages but only bust_cache on …
=> Wikidata v0 with author description and infobox

.pre-commit-config.yaml, openlibrary/i18n/__init__.py, scripts/i18n-messages
Addendum to #9208.
Fix. Fixes a bug with the timezone rendering of the new static date, and adds a `--skip-untracked-files` option to prevent bugs when running the `extract` script in Docker.
Simple! Involved:
a. Switching from `Babel.dates` for timezone to a built-in `datetime` method, which is cleaner anyway
b. Adding a flag for `--skip-untracked-files` that works similarly to the `--verbose` and `--forced` flags and is now called in `pre-commit-config.yaml`
1. Make a new `html` file in `templates` with internationalized text.
2. Do a test commit locally
3. Pre-commit should skip the untracked file when generating the `messages.pot` file
4. Undo the commit, and use the extract script directly in Docker
5. Docker should run the script without errors and include the untracked file
@cdrini
=> Update `messages.pot` creation date timezone and add `--skip-untracked` option

openlibrary/templates/books/edit/edition.html
Closes #9169
Fix client side bug
As was proposed by @RayBB adding html attribute "min" prevents users to go below 0 (including typing)
Same as screenshot
@scottbarnes
=> Fix: Can set the page count for a book negative (fixed)

openlibrary/core/helpers.py
Adds comment to notify developers that functions in `openlibrary.core.helpers` `__all__` are exposed to templates.
> [!IMPORTANT]
> Reviewer to confirm that comment is accurate.
>
> Functions found in `helpers` are exposed to templates [here](https://github.com/internetarchive/openlibrary/blob/4e47fb46e329fd8e55ff3b8b100692d69e9964b8/openlibrary/plugins/upstream/utils.py#L1700-L1702).
>
> `helpers` variable is set [here](https://github.com/internetarchive/openlibrary/blob/4e47fb46e329fd8e55ff3b8b100692d69e9964b8/openlibrary/core/helpers.py#L336-L342), using `__all__`.
=> Add comment to `helpers.py`

.github/labeler.yml, .github/workflows/pr_update_labeler.yml
Closes #9199
Removes any existing https://github.com/internetarchive/openlibrary/labels/Needs%3A%20Submitter%20Input labels from PRs when the pull request's head branch is updated.
The `pull_request_target` event was chosen over `pull_request` event, as the workflow will not run for `pull_request` events if there is a merge conflict (more details [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)).
Our labeler configuration is set to add a https://github.com/internetarchive/openlibrary/labels/Needs%3A%20Submitter%20Input label if the PR includes changes to any file in the project's non-existent `dev/null` directory.  When coupled with a truthy `sync-labels` input, the label is removed every time there is no change to any `dev/null` …
=> Remove `Needs: Submitter Input` label on push

scripts/pr_slack_digest.py
Closes #9088
Updates query to avoid fetching pull requests that have either https://github.com/internetarchive/openlibrary/labels/State%3A%20Blocked or https://github.com/internetarchive/openlibrary/labels/Needs%3A%20Submitter%20Input labels.
Draft PRs are already ignored by this query.
> [!IMPORTANT]
> This script is executed by our `cron` job runner.  Code changes will have to be deployed after merging before we see changes in the staff PR Slack digest. 
I checked the results of the new query in my browser, and compared to the most recent staff PR Slack message:
https://api.github.com/search/issues?q=repo:internetarchive/openlibrary%20%20is:open%20is:pr%20author:cdrini%20author:jimchamp%20author:mekarpeles%20author:scottbarnes%20-is:draft%20-label:%22State:%20Blocked%22%20-label:%22Needs …
=> Filter out PRs having specific labels

.github/workflows/new_pr_labeler.yml, scripts/gh_scripts/new_pr_labeler.mjs
Closes #9200
Automatically labels and assigns newly created PRs, including drafts, via a new GitHub action.
When a new PR is created, the action passes the full repository name (e.g. `internetarchive/openlibrary`), the PR's author, the PR's number, and the PR's body to the `new_pr_labeler.mjs` script, which does the following:
1. Searches the PR body for a `closes #` statement.
2. Fetches the issue referenced by the `closes #` statement.
3. Checks the issue for the first `Priority` and `Lead:` labels.
4. If a level 0, 1, or 2 priority label is found, it is added to the new PR.
5. If a lead label is found, and the lead is not the PR's author, the issue's lead is assigned to the new PR.
This can be tested by merging this branch into a forked Openlibrary repo by:
1. Merging into the fork's …
=> Create action for assigning, labeling new PRs

openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/js/realtime_account_validation.js, openlibrary/templates/account/create.html, tests/unit/js/realtime_account_validation.test.js
Closes #9165
Fix. Addresses console errors re: non-existent `#password2` field, and updates real-time password validation to make the correct checks (determining whether password length is <3 or >20 rather than whether two passwords match).
Also involves re-writing the relevant unit tests.
Fairly simple! 
- Added `i18n`-ized error message to `create.html` to pass to `realtime_account_validation.js`
- Rewrote `validatePasswords` function to check length instead of match
1. Log out (if logged in)
2. Go to the sign up page (/account/create)
3. Enter a password that is < 3 or > 20 characters
4. An error message should appear next to the field (on blur)
5. Enter a password that is the correct length
6. The error message should disappear (on blur)
@jimchamp @cdrini
=> Redo password validation for registration form

openlibrary/components/MergeUI/MergeTable.vue
Closes #9044
Adds text wrap to title in merge tool
Changes the css inside of the mergetable.vue
Adds "
white-space: normal;
word-wrap: break-word;
overflow-wrap: break-word;
"
for text wrap
adds min-width: 500px; for setting new width of title column can be different width current implementation of text wrap works in firefox where text-wrap is not valid
1. docker compose up
Runs view components
2. docker compose run --rm home npm run build-assets
Wait to finish
Adding book
3. docker compose exec -e PYTHONPATH=. web bash -c "./scripts/copydocs.py /works/OL6030812W /works/OL31219436W /works/OL32006641W /works/OL29342271W"
4. Visit http://localhost:8080/works/merge?records=OL6030812W,OL31219436W,OL32006641W,OL29342271W
Before:
https://private-user-images.githubusercontent.com/921217/320514509 …
=> Fixed title wrap merge tool

openlibrary/accounts/model.py, openlibrary/i18n/messages.pot, openlibrary/plugins/upstream/account.py, openlibrary/utils/sentry.py
In support of #8863
1. Update our `Sentry` objects to allow for capturing handled exceptions
2. Creates new `OLAuthenticationError`, which are now thrown on IA account creation failures
3. Publishes `/account/create` `POST` handler to Sentry
1. Deploy this to `testing`
2. Trigger an error during account registration
3. Check Sentry for an `OLAuthenticationError`
=> Instrument registration flow

openlibrary/coverstore/code.py
Prep for project outlined in #9077.
Refactor. A quick but satisfying refactor of the code that determines placement for book covers in the social share image. Done in preparation for a re-use of the code for subject/collection social share images for #9077.
**Note:** I'd be happy to change the `start_width` variable name to something more descriptive/accurate -- `start_point`? `start_x_position`? -- if there's a preferred name for it. 
The implementation used the mathematical patterns derived from the original version of the function to drastically simplify it:
- Because the starting point (width) for the first image in the case of 5 images was 63:
```
if len(image) == 5:
background.paste(image[0], (63, 174 + max_height - image[0].size[1]))
```
And the starting point consistently went up …
=> Refactor social image generation code

openlibrary/templates/type/edition/view.html, static/css/base/dl.less, static/css/components/work.less
Saw some simple opportunities while working on #9175 to DRY up some of the pieces of this section. Namely:
- Make all the heading here the same size
- Make `Published in` appear like `Other Titles`/other metadata instead of own section since it's very short.
- Removed a number of classes that no longer really made sense:
- `edition-header`: was only used here, and made the headings look meaninglessly inconsistent
- `list-header`: The class didn't really make any style changes? And the `clear-both` was no longer needed after I changed this to not `float: left`. Floating was a residue of a former time when these mini table things were in a grid via float.
- `list-header.collapse`: No longer necessary; residue when `.collapse` was used to remove the margins from something. The margins of the …
=> DRY design/code of "Book Details" section

scripts/gh_scripts/new_pr_labeler.mjs
Closes #9248
Uses optional chaining to handle case where `matches` is null.
=> Fix PR assignment workflow

openlibrary/plugins/openlibrary/code.py, openlibrary/plugins/openlibrary/processors.py
Closes #9058
Creates new `CacheablePathsProcessor` that can be used to cache Infogami pages without overriding the default Infogami handler for such pages.
This processor attempts to fetch pages from cache when the following are true:
1. The request is a `GET`
2. The request is not specially encoded data (`json`, `yml`, etc.)
3. The request's path matches one of the patterns in the `paths_and_expiries` dictionary
4. `debug` is not in the request's query string
5. The requested page's mode is `view`
The processor has been set up to cache`/collections` and `/collections/{collection_identifier}` pages.
Cache keys will take the form:
`{web.ctx.path}.{web.ctx.lang}{query_string}`
...where `query_string` is either an empty string or an ordered query string (e.g. `?a=1&b=1&c=1`)
Adding a new …
=> Cache collections with new `CacheablePathsProcessor`

openlibrary/i18n/messages.pot, openlibrary/plugins/upstream/account.py
Closes #7080.
Fix. Adds checks for any existing Internet Archive account with the selected email or username before submission of registration form. This will notify users real time if the username they select is already taken, so that they can choose a new username rather than being auto-assigned one with random digits appended.
Because of the scope of #2055 , I've limited this PR to only adding real-time validation for the fields, not preventing submission with a taken username. This means that if a user elects to ignore the "username taken" error message and submits anyway, the account creation will go through and random digits will be appended to their chosen username.
Submission prevention for this and other failing backend checks (i.e. taken OL email address) will be added as a part …
=> Add pre-registration validation for IA email and username

.github/workflows/new_pr_labeler.yml
Closes #9251
Prevents running the `new_pr_labeler` workflow if the new PR is a draft.
=> Drafts now skipped by PR assignment workflow

openlibrary/templates/type/edition/compact_title.html
This commit address the issue by changing a button class to the requested one
This change affects the appearance of the button border line
Closes #9238
Fix the UX bug
Were changed the button class to meet the requirement style
Same as screenshot
@RayBB
=> Fix: This change was requested in order to standardize Open Library's buttons, #9238

openlibrary/templates/type/about/view.html
Closes #9080
fix
Removing the mailing list heading
Test it before merging because I am getting below error in local dev environment
=> Remove mailing lists heading from about page

openlibrary/i18n/messages.pot, openlibrary/macros/DonateModal.html, openlibrary/templates/lib/not_logged.html
We run `extract/i18n-messages extract` by default now, but we need to get the `master` branch in a state where the command can run cleanly, or the files in this commit will get flagged with any commit that makes an `i18n` change.
This seems to be confusing people.
Edit: I double checked by adding another commit with an `i18n` text change and no accompanying update to `messages.pot` within the PR. on push, `pre-commit` ran, failed because `message.pot` changed by way of the `pre-commit` hook, added the updated `messages.pot` to the PR, ran again, and succeeded. This is evidence, though not entirely conclusive, that it may fix things for, e.g., #9246.
- Get on the current `master` branch.
- Make a change to to some i18n text. E.g.:
```diff
diff --git …
```
=> Fix: update and escape a handful of templates

openlibrary/plugins/admin/code.py, openlibrary/plugins/upstream/merge_authors.py, openlibrary/templates/search/sort_options.html, openlibrary/templates/type/author/view.html, openlibrary/templates/work_search.html
Closes #9087 
Replaces the existing ```is_usergroup_member('/usergroup/librarians')``` with ```is_librarian()```
- Given below are the affected paths, the testing has been done and all seems to work similarly
- /admin/*
- /search/?q=the&mode=everything (any search path /search/*)
- /authors/merge (test url: http://localhost:8080/authors/merge?key=OL21093A&key=OL161167A&key=OL19677A&key=OL24638A&key=OL114411A&key=OL20585A&key=OL50694A&key=OL47908A&key=OL29586A&key=OL2688089A&key=OL29388A)
- /authors/* (http://localhost:8080/authors/OL22098A/Lewis_Carroll)
@RayBB
=> Replace: Cleanup use of is_usergroup_member('/usergroup/librarians')

openlibrary/i18n/messages.pot, openlibrary/templates/lib/message_addbook.html, static/css/components/buttonsAndLinks.less
Closes #9237 
Removed usages of `icon_cancel.png`, since it doesn't exist and it was still referenced in some part of the codebase.
@RayBB
=> Removed deprecated .png file

openlibrary/plugins/openlibrary/js/team.js
Related: #9227
Fix: stops the current year in `team.js` from being hard coded.
Without this change or a similar one, #9227 will have unintended outcomes because the years won't be right.
With #9227, the team page will look like:
@mekarpeles
=> Fix: change `team.js` so the current year is not hard coded

openlibrary/i18n/messages.pot, openlibrary/macros/DonateModal.html
Closes #9297.
Hotfix. Fixes the last two remaining un-closed tags in our `messages.pot` file, both of which are located in `DonateModal.html`.
- Simply changed the placement of the closing quote and parentheses for the relevant strings
- Also searched the `messages.pot` file for various HTML opening tags (`<a`, `<i>`, `<em>`, `<strong>`) and confirmed that, aside from these two, each other opening tag was accompanied by a closing tag
1. Go the Donate Modal section of the `messages.pot` file
2. Confirm all opening tags are now closed
@dcapillae
=> Fix `i18n` syntax in Donate Modal to include closing tags

openlibrary/plugins/upstream/account.py
Closes #9292
Fixes issue where `sentry` is `None` if imported before `setup()` is called (as per [this comment](https://github.com/internetarchive/openlibrary/pull/4055/files#r527004362)).
=> Move `sentry` import to function

openlibrary/templates/about/team.json
Fix. Switched out my personal URL on the team page so it points to the correct site.
Quick adjustment to `team.json`, also added a favorite book url while I was at it.
@cdrini
=> Switch out personal URL for team page

openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/js/utils.js, openlibrary/templates/books/edit/excerpts.html
Closes #9179
Did a fulltext search of the code and these aren't used anywhere I can see but a second check would be good.
Removes one unused piece of code and adds a comment about why we want to keep the rest.
=> Remove unused util `$.fn.focusNextInputField`

openlibrary/coverstore/archive.py
Closes #8278
To be run with:
```
PYTHONPATH=. python /openlibrary/openlibrary/coverstore/archive.py /olsystem/etc/openlibrary.yml /olsystem/etc/coverstore.yml
```
Tested by running the following on `ol-home0`:
```
docker cp openlibrary/coverstore/archive.py openlibrary-cron-jobs-1:/openlibrary/openlibrary/coverstore/archive.py
docker exec -uroot -it openlibrary-cron-jobs-1 bash
su openlibrary -c "PYTHONPATH=. python /openlibrary/openlibrary/coverstore/archive.py /olsystem/etc/openlibrary.yml /olsystem/etc/coverstore.yml"
```
Depends also on https://github.com/internetarchive/olsystem/pull/210, which should be reviewed/merged **after** this PR.
=> Prepares cover archival to be run as cron #8278

openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/js/realtime_account_validation.js, openlibrary/plugins/upstream/forms.py, openlibrary/templates/account/create.html, openlibrary/utils/form.py
Closes #9244.
Feature. Adds HTML attributes to registration form inputs to prevent submission with improperly formatted data.
Implementation involved removing `validate` class to prevent duplicated realtime validation, and adding appropriate attributes to inputs in `forms.py`. Also involved triggering the `HTML` validation manually before the `grecaptcha` process, a strategy that will likely be re-used/expanded for part 2 of [#9205](https://github.com/internetarchive/openlibrary/issues/9205).
1. Log out (if logged in)
2. Hit "Sign Up" or go to `/account/create`
3. Try entering an improperly formatted password, username or email 
4. Ignore the on-screen warning and submit the form
5. Submission should be prevented and you should see an HTML built-in error message pop up next to the first …
=> Add HTML validation to registration form

openlibrary/catalog/add_book/load_book.py, openlibrary/catalog/add_book/tests/test_load_book.py
Matching and stripping honorifics should match `honorific + " "` and not just `honorific`. Thanks @hornc for catching this!
Closes #7349
Closes #9321 
Fixes cases where names beginning with an honorific (e.g. `Dr` and `Drini` would incorrectly match as an honorific).
This matches and removes `honorific + " "`, rather than just `honorific`.
It also incorporates the test from #9321.
See the updated unit test.
@cdrini
@hornc
=> Fix: add spaces when matching author honorifics

openlibrary/plugins/admin/code.py, openlibrary/plugins/upstream/addbook.py, openlibrary/plugins/upstream/addtag.py, openlibrary/plugins/upstream/code.py, openlibrary/plugins/upstream/merge_authors.py, openlibrary/plugins/upstream/tests/test_addbook.py, openlibrary/templates/books/add.html, openlibrary/templates/books/edit.html, openlibrary/templates/books/edit/edition.html, openlibrary/templates/lib/header_dropdown.html, openlibrary/templates/lib/nav_head.html, openlibrary/templates/merge_request_table/merge_request_table.html, openlibrary/templates/showmarc.html, openlibrary/templates/subjects.html, openlibrary/templates/type/author/edit.html, openlibrary/templates/type/edition/view.html, openlibrary/templates/viewpage.html
Closes #9266
Refactors uses of `self.is_usergroup_member('/usergroup/super-librarians')` to `is_super_librarian()`
Simple find and replace (except the definition of course)
@RayBB
=> Refactor checking super librarian status with is_usergroup_member()

openlibrary/templates/site/footer.html
This comment is no longer true. Probably hasn't been for a long time.
We load jquery in all.js and the analytics file doesn't need it.
=> remove outdate jquery comment

openlibrary/templates/search/work_search_facets.html, openlibrary/templates/work_search.html
Supports #7271 
Moves search facets sidebar into its own template.  The new `work_search_facets` template supports asynchronous loading, and will display `Loading...` indicators when `facet_counts` is `None`.
As of now, there is no way to trigger `async_load` mode via the UI.  However, you can make the following change to `work_search.html` to view the loading indicators:
https://github.com/internetarchive/openlibrary/pull/9276/files#r1602125790
_Facet sidebar when `facet_counts` is `None`._
=> Create template for search facets

.github/workflows/weekly_status_report.yml
Closes #9340
Changes scheduled execution of the `weekly_status_report` digest to twice a week, on Mondays and Fridays.
> [!IMPORTANT]
> As of writing, the `weekly_status_report` workflow is disabled.  After merging this, please enable the workflow again.  Instructions for doing so can be found [here](https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow#enabling-a-workflow).
=> Run weekly PM digest on Monday and Friday

.github/workflows/config/new_comment_digest.json, .github/workflows/new_comment_digest.yml, scripts/gh_scripts/README.md, scripts/gh_scripts/issue_comment_bot.py
Closes #9336
Updates script to read a configuration that contains the GitHub username, Slack ID, and lead label text for project leads.  The script will avoid adding the https://github.com/internetarchive/openlibrary/labels/Needs%3A%20Response label to any issue that was last responded to by a lead, if that lead's information is included in the configuration file.
=> Expand `issue_comment_bot` to include more leads

openlibrary/catalog/marc/parse.py
Closes #8140
Updates the MARC import table mappings to correct LOC deprecated 3 character language codes to their current code.
This will ensure records imported from older MARCs have the up-to-date codes in Open Library.
This will not modify language codes on existing records (#8139), it only affects new imports.
@cdrini 
@tfmorris
=> Update MARC importer language mapping table

openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/js/index.js, openlibrary/templates/type/author/edit.html
Closes #9280 
I can fix the indentation in a later commit if needed. For now, just want to show how simple the change is.
Exits work fine. UI looks only slightly different. The page could use some general improvements but that's for another pr ;) 
|--------|-------|
|![image](https://github.com/internetarchive/openlibrary/assets/921217/4943ca2b-e420-4a41-90fd-1b78ed8c4669) |![image](https://github.com/internetarchive/openlibrary/assets/921217/9375774c-399a-40ba-87b6-3b98925f5031) |
=> merge tabs on author edit page

openlibrary/core/follows.py, openlibrary/plugins/upstream/account.py, openlibrary/templates/account/follows.html
Closes #9283 
Adds pagination support to `people/:username/followers` and `people/:username/following`
- I added `results_per_page` as a mandatory variable in the template instead of optional, so that the page size given to the macro will always match the page size used for calculating the offset in the DB query
- An easier way to solve this issue would have just been to pass a slice of `follows` to the template, but I don't think returning the whole DB contents would be solving an issue of performance as well as returning a constant 25 or fewer rows does.
- I added limits and offsets to the methods in core/follows.py, but I made these params optional so as to not break other parts of the code that use `get_following`. I looked in other parts of the codebase to verify that None and 0 are …
=> Add pagination to user following/follower lists

.github/workflows/stale_assignee_digest.yml, scripts/gh_scripts/README.md, scripts/gh_scripts/stale_assignee_digest.mjs, scripts/gh_scripts/weekly_status_report.mjs
Closes #9335
Updates the `stale_assignee_digest` script in the following ways:
1. Adds the https://github.com/internetarchive/openlibrary/labels/Needs%3A%20Review%20Assignee link to any issues that may be stale
2. Removes code that publishes messages to Slack
3. Adds a section for stale issues to our biweekly Slack project management digest
4. Updates stale assignee workflow to run an hour before Monday's Slack digest is published
> [!TIP]
> It may be easier to review the first two commits individually.  The first commit updates some malformed `jsdoc` strings, and the second DRYs the GitHub request headers.  These commits are somewhat unrelated to the task at hand, and may cause confusion when viewed with all other changes.
=> Automatically label assigned issues that may not have had recent progress

openlibrary/plugins/upstream/account.py
Closes #9283 (cont'd)
- Fixes page validation for followers/following pages in the event that the page ID is already an integer and not a string
- Defaults to the last valid page if the provided page is too high
- I extracted page validation into an "unexported" function for cleanliness. It covers the `page` qparam being either an int or a string as well as a fallback to just return 1.
- I noticed I had no checks for invalid pages that are too highly numbered, so I added that as well.
I repeated my tests from https://github.com/internetarchive/openlibrary/pull/9323, but also tried loading the page with invalid high values like 21, 100, etc.
There was no change in the results of my tests from https://github.com/internetarchive/openlibrary/pull/9323.
Here is another screenshot with a page …
=> Fix and improve page number validation for following/followers pages

openlibrary/data/dump.py, openlibrary/plugins/upstream/data.py
Closes #8401 
This is a refactor that allows all dump file types that are NOT   
```
"/type/edition",
"/type/author",
"/type/work",
"/type/redirect",
"/type/list"
```
to be sorted into a `misc` category. This category catches all `/type/page` dump files, in addition to all other types that are not in above list. 
This misc files should help provide a comprehensive inventory of pages in the dump that is used to generate the sitemap. 
I only tested these changes with a subset of full data (commented in line 38 of /scripts/oldump.sh) . 
When line 38 was commented in, I also had to change the `-z` in line 133 of /scripts/oldump.sh to `-n` to avoid an error in /data/dump.py. 
Ran `docker compose run --rm home make test`
@jimchamp @RayBB
=> Added logic for page dump and commented out test line

openlibrary/plugins/upstream/account.py
Closes #9283 (cont'd)
- Fixes max page validation in the case of zero followers/following
- Added max page calculation to _validate_follows_page to contain all of the page validation logic in one place. The output can only be between a minimum page number (1) and ceil(hits / pagesize). Therefore the offset, page - 1, can never be below zero.
- I've added an extra safeguard to floor `offset` to zero as well. This doesn't do much in the context of this PR since the output of the validation function should never go below 1, but it's there in case the validation function ever changes, or anything along those lines. I thought about adding an offset validation check further upstream but ultimately I think it should be the consumer function's job to make sure it's passing correct information to …
=> Fix zero follower page case

openlibrary/templates/recentchanges/render.html
Closes #9197 
The /recentchanges page will no longer display individual user preference changes
In `templates/recentchanges/render.html`, checks that a change's path (specifically `c.get_changes()[0].key`) does not end in `preferences` before rendering the change. This is the best solution I could think of (over e.g. `call_template("path", c)`) due to lack of access to regular expressions in the templating engine. In a previous commit I used `c.comment` which is simpler and somewhat more prone to breaking.
1. By commenting out or switching to another branch, ensure that there is at least one /recentchanges entry recording a user preferences change (comment is `updating user preferences`) in your testing environment. If not, you can switch your safe mode preference to generate one.
2. …
=> Hide user preference changes in /recentchanges

openlibrary/catalog/marc/parse.py
Fixes a typo in the new Tagalog code, relates to #8139 and #8140
Adds a comment to clarify that not all deprecated codes are auto-converted, just the ones which have clear 1-to-1 mappings. 
@tfmorris 
@mekarpeles , you merged the last one of these, after the fact I noticed a typo in one of the codes, This is a fix that should go in quickly, before any imports go through.
=> fix typo on Tagalog, tgi should be tgl

scripts/import_standard_ebooks.py, scripts/tests/test_import_standard_ebooks.py
Closes #9372
Add the access key for the standard ebooks OPDS feed. Corresponding olsystem change: https://github.com/internetarchive/olsystem/pull/211
On ol-home0 (after patch deploying the olsystem change) I ran:
```sh
docker run -it --rm --name standard-ebooks-import -v "/opt/olsystem:/olsystem" openlibrary/olbase:latest bash
curl -L 'https://github.com/internetarchive/openlibrary/pull/9327.diff' | git apply
curl -L 'https://github.com/internetarchive/openlibrary/pull/9386.diff' | git apply
PYTHONPATH=. ./scripts/import_standard_ebooks.py /olsystem/etc/openlibrary.yml --dry-run > tmp.jsonl
```
And the file had 1006 records looking good!
=> Add access key for standard ebooks OPDS feed

scripts/dump-covers-metadata.sql, scripts/oldump.sh
Closes #9157 
This PR adds a script to create a memory dump of ids, widths, and heights from the cover databse, as requested by #9156.  The command to run this SQL file on the local version is listed in the file itself. 
First, upload a few images to coverstore on your localhosted version, then run the script file added by this PR. 
@cdrini
=> Added script for metadata dumping of coverstore id/width/height

openlibrary/plugins/openlibrary/code.py
Closes #9364
Removes `CacheablePathsProcessor` from the application's processor chain.  Collections pages will now be fetched from the DB.
=> Fetch `/collections` pages from DB, not cache

openlibrary/plugins/openlibrary/js/my-books/index.js, openlibrary/templates/type/author/view.html
Closes #9268
Updates the author page active lists showcase to:
1. Load asynchronously
2. Display only the patron's list items
Fixes bug where arrays of seed keys were being added to the `seedKeys` array, which caused keys to be dropped later, when a set is created from this array.
While authenticated:
1. Navigate to an author page
2. Add the author to one of your lists
3. Refresh the page
4. Confirm that loading indicator is present on page load
5. Confirm that the loading indicator is replaced with a list showcase item that represents the list from step 2, above
=> Async load patrons' author list showcases

openlibrary/catalog/add_book/match.py, openlibrary/catalog/add_book/tests/test_match.py
Closes #9387 
Fix.
This PR increases the penalty for a truthy and yet non-matching `publishers` field so that during import editions will not match when they have:
1. matching author;
2. matching title;
3. matching publish_date; and
4. do NOT have a matching truthy publishers field.
Edition matching uses a points system found in
`openlibrary/catalog/add_book/match.py`, and a match is made when the threshold of 875 points is met. This PR increases the penalty for non-matching publishers to stop a match from occurring in the above situation.
The rationale is that multiple editions can be published by different publishers in the same year, and all would have the same title, authors, and publish_date, yet they would be different editions if the truthy `publishers` field did not match.
If the …
=> Imports: increase point penalty for non-matching publishers

openlibrary/i18n/messages.pot, openlibrary/templates/lists/showcase.html, static/css/components/list-showcase.less
Closes #7704 (Addendum)
Finished some of the design details in figma + DRYed up some of the code.
Code:
- Used BEM notation correctly; the code was already structured BEM-like, but was using `-` instead of `__` to denote child relationship
- The HTML had a few unnecessary nesting/divs; dropped those
- I18n all the strings
- Fix some bugs in the code (eg default parameters cannot be lists)
- Used larger covers since they're displayed larger than the -S
- Used less `position: absolute` in the list-card
- Used CSS to truncate title, not manual limiting to 16 characters
UI:
- I removed the gradient at the end ; that's a pretty common UI affordance for scrolling; we should bring back now that scrolling is enabled, but it takes a bit of time since you have to make it appear/disappear as …
=> Fixes to lists-showcase styling/code

openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/js/realtime_account_validation.js, openlibrary/plugins/upstream/account.py, openlibrary/plugins/upstream/forms.py, openlibrary/templates/account/create.html, openlibrary/templates/account/ia_thirdparty_logins.html, static/css/page-signup.less, tests/unit/js/realtime_account_validation.test.js
Closes #9316.
Feature. Implements a full design overhaul for the registration page.
**Requirements:**
**Note:**
- The PR involved modifying the tests in `realtime_account_validation.test.js` as a result of replacing the `invalid` class toggle with a `display:none` vs. `display:block` toggle for the error divs to avoid phantom errors; further improvements to the test can be included in the final refactor, or as part of the PR
- The "Subscriptions" label from the mockup is currently not included to avoid `label` clashes that could interfere with accessibility, could certainly be added once we have a reasonable solution for how to do so
1. Log out (if logged in)
2. Go to `/account/create`
3. The page should look like this v
Registration UI Mobile View" …
=> Implement Figma mockup for registration

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml
The current instructions template for issues can be confusing because instructions to contributors shows up under `### Stakeholders` even if the section is blank. There should be a section specifically for `### Instructions for Contributors` and we may be able to make it a bit more clear / actionable: 
> ### Instructions for Contributors
> - Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to github, because pre-commit bot may add commits to your PRs upstream.
=> update contributor instructions

openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/js/covers.js, openlibrary/templates/covers/add.html, openlibrary/templates/covers/saved.html, static/css/components/cbox.less, static/css/page-form.less
Closes #9333.
Feature. Adds an option to use the book's cover from the Internet Archive site if applicable.
Current progress:
✅ IA cover option is visible for books with an `ocaid` - i.e. `/books/OL24755423M/Odyssey_book_iv`
✅ IA cover option is not visible for books without an `ocaid` - i.e. `/books/OL9737752M/The_Odyssey`
✅ Selecting "Use this Image" successfully uploads the IA cover
✅ Entering a link or image file and selecting "Submit" successfully uploads the user-selected cover, not the IA one
✅ Error checks are modified to run only if the regular "Submit" button is clicked
✅ Button disabling is switched from built-in HTML to manual CSS to prevent IA upload failure
✅ Inline styles should be removed
✅ Hitting the "Enter" key should click the original "Submit" button, not the IA one
✅ …
=> Add Internet Archive cover option

openlibrary/plugins/openlibrary/js/service-worker.js, openlibrary/plugins/upstream/code.py
Before:
The covers should be the grey default book cover, and there should be up/down arrows next to the headers
After:
=> Partially fix static images not working in gitpod

openlibrary/core/bookshelves_events.py, openlibrary/core/yearly_reading_goals.py, openlibrary/i18n/messages.pot, openlibrary/templates/admin/index.html, openlibrary/tests/core/test_db.py, openlibrary/views/loanstats.py
Closes #7352
Added `summary` and `total_yearly_reading_goals` functions to  `yearly_reading_goals.py`. Added unit test for `total_yearly_reading_goals` function. Added Yearly Reading Goals row in `openlibrary/templates/admin/index.html`.
Let me know if there are things we want to change!
There are a few things to note:
1. First, during testing, I found that for some reason the key in the storage object (noted by @scottbarnes in https://github.com/internetarchive/openlibrary/pull/7560#discussion_r1153914826, Scott is also right that the other functions are documented incorrectly - they return Storage objects not ints) in the unit test is different from when the application is run (that is the reason in the HTML file the key is `'count'` while in the unit test it is `'count(*)'`) …
=> added Yearly Reading Goals to /stats page

openlibrary/templates/type/edition/view.html
Mainly fixing some invalid nesting I introduced recently, there are many heading tags within spans which fail validation that might need some careful redesign.
follow up to  #9433
=> tidy some invalid HTML and rendered comments in edition view template

scripts/manage-imports.py
Was noticing high CPU load on our db server, so reduced the multiprocessing of importbot. I tried 6 but it seemed like it had room for more, so leaving it at 8 to see how it does. Either way better than 10!
=> Reduce multiprocessing of importbot

openlibrary/core/models.py, openlibrary/plugins/upstream/mybooks.py, openlibrary/templates/type/user/view.html
Closes #9358
Adds a follow button to a user's patron page.
- The button should only show if you are logged in, not looking at your own page, not already following the user, and the user's reading list is public.
- Moves the `is_subscribed` check business logic from `MyBooksTemplate` to the user level so that it can also be leveraged by the patron page. This seems like an appropriate place for it IMO as the user model also includes other object reference checks like `is_usergroup_member`.
I added a test patron via the provided instructions.
(The rest of my testing steps are outlined in the Screenshots section)
Viewing my own page: no follow button (public or private)
Viewing a public patron while logged in: follow button appears
Click the follow button: it becomes an unfollow button …
=> Add follow button to patron profile pages

scripts/gh_scripts/issue_comment_bot.py
Correctly compares GitHub username to lead label.  Previous code was throwing a `StopIteration` error due to a match never being made in the `next` call.
=> Fix broken Slack digest for new comments

scripts/decode_ip.sh, scripts/obfi/mktable.py
Closes #9478
The `dbm.ndbm` module doesn't flush very often, resulting in sometimes long waits for decoding an IP. These changes flush the database (by closing it and opening it, as there is no flush method) every 10 IPs.
Additionally, it has `tcpdump` listen on port 443, in addition to port 80.
Finally, there is a small fix for a race condition where the script would sometimes try to access the database file before it had been created.
Get an obfuscated IP (e.g. from tailing `/1/var/log/nginx/access.log`, and then, assuming `$SEED_PATH` has been exported, run `sudo -E decode_ip.sh <obfuscated IP here>` on it.
@mekarpeles
=> Fix: `decode_ip.sh` returns more quickly and listens on port 443

openlibrary/catalog/add_book/load_book.py, openlibrary/catalog/add_book/tests/test_load_book.py
Closes #9482
Related #9480
This PR normalizes the language code[s] on import via `load()`.
This just ensures the language code is lower case, even if the incoming `rec` has a language code that is not lower case.
Without the PR, try to import something with an all-caps language code, such as this IA item: [270b51a0-d993-4be6-ae92-d3bb06a68955](https://archive.org/metadata/270b51a0-d993-4be6-ae92-d3bb06a68955/metadata/language)
```
❯ curl -X POST "http://localhost:8080/api/import/ia" \
-b ~/cookies.txt \
-d "identifier=270b51a0-d993-4be6-ae92-d3bb06a68955&require_marc=false"
{"success": false, "error": "invalid language code: 'ENG'"}
```
Try again with the PR:
```
❯ curl -X POST "http://localhost:8080/api/import/ia" \
-b ~/cookies.txt \
-d …
```
=> Feature: normalize language codes on import via `load()`

openlibrary/templates/search/searchbox.html
Closes #9492
This re-enables autocomplete in the searchbox.
@seabelis 
@cdrini
=> Fix: renable autocomplete in searchbox

openlibrary/book_providers.py, openlibrary/macros/BookPreview.html, openlibrary/macros/LoanStatus.html, openlibrary/macros/NotInLibrary.html, openlibrary/macros/QueryCarousel.html, openlibrary/macros/ReadButton.html, openlibrary/plugins/openlibrary/js/carousel/Carousel.js, openlibrary/plugins/openlibrary/js/ol.analytics.js, openlibrary/templates/book_providers/gutenberg_read_button.html, openlibrary/templates/book_providers/librivox_read_button.html, openlibrary/templates/book_providers/openstax_read_button.html, openlibrary/templates/book_providers/standard_ebooks_read_button.html, openlibrary/templates/books/custom_carousel.html, openlibrary/templates/home/categories.html, openlibrary/templates/home/index.html, openlibrary/templates/home/onboarding_card.html, openlibrary/templates/home/welcome.html, openlibrary/templates/publishers/view.html, openlibrary/templates/subjects.html
Closes #7301 . ~Depends on #8782 . Closes #8615 .~
Adds analytics events of the nature:
- `BookCarousel|CTAClick|thrillers`
- `BookCarousel|Next|related-subjects-carousel`
- `Carousel|Next|welcome`
- `Carousel|Next|categories`
- and so on.
- Modifies the way we use `label`, which have in the past set to be the URL, to contain actual data. Not sure if this will have side-effects!
- We will no longer fire a eg `CTAClick|Borrow` event from the cta buttons in a carousel; it will now be eg `BookCarousel|CTAClick|thrillers`. I believe this is more useful than knowing what type of cta button was there.
Open the networks panel, filter by `0.gif` while performing various carousel-y actions on carousel.
- ✅ Confirmed analytics events firing on ✅ cover click, ✅ cta click, ✅ next button click
- ✅ …
=> Add carousel analytics

openlibrary/i18n/messages.pot, openlibrary/macros/DisplayCode.html, openlibrary/macros/Profile.html, openlibrary/templates/admin/index.html, scripts/detect_missing_i18n.py
Sub-task of #9486. 
Fix. Adjusts the `i18n` `WARN` syntax to only flag text wrapped in `$(' ')` or `$(" ")`, the chosen syntax for intentionally untranslated text. This way, we avoid flagging Python insertions wrapped in parentheses, and can remove a number of files from the exclude list.
Also involved adding the `skip_directive` to escape a few last Python lines still accidentally caught by the script.
1. Add a new line of Python into an HTML file wrapping it in the following: `$( )`
2. Run the script with `pre-commit run detect-missing-i18n --all-files`, you should not see a warning appear
3. Change existing `i18n` syntax or add a new line you think shouldn't be translated, using the preferred warning syntax, i.e. `$('https://www.google.com')`
4. Run the script again, the script should …
=> Update `i18n` warn regex and escape relevant files

openlibrary/templates/merge/authors.html
Closes #9429
This PR introduces the display of author descriptions on the merge page. The author descriptions will provide more context about each author during the merge process, improving the usability and user experience and helping librarians disambiguate authors, and avoid accidentally merging authors that shouldn't be merged.
1. **Conditional Display of Author Description**:
- Added logic to conditionally display the author description if it exists. If no description is available, a placeholder message "No description." will be shown.
- Used the `TruncateString` macro to limit the displayed author description to 250 characters for better readability and to ensure a consistent layout.
2. **Updated Template**:
- Modified the HTML template to include the new logic for displaying author …
=> make author merge description visible

.github/workflows/codegen_api_docs.yml, .github/workflows/cron_watcher.yml, .github/workflows/javascript_tests.yml, .github/workflows/new_comment_digest.yml, .github/workflows/python_tests.yml
Closes #9517
Upgrades deprecated `codecov-action` and `setup-python` actions in our workflows.
=> Update deprecated dependencies

openlibrary/templates/merge/authors.html
Closes #9476 
Fixed the issue that extra ' is added to the work URLs when authors are merged..
=> fix merge author url issue

openlibrary/templates/account/reading_log.html
Closes #9547 
This PR achieves a quick fix to return the search bars to users' already-read and currently-reading pages. Somehow, the names of two of the keys used to check rendering  got changed, so the search bar was no longer loading. 
There was very little technical about this issue, it just involved fixing some changes made to a template's variables. 
Go to your already_read or currently_reading pages on your account, and see the search bar. 
@cdrini
=> Fix Search Box Only Visible On Want To Read

openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/js/realtime_account_validation.js, openlibrary/plugins/upstream/account.py, openlibrary/plugins/upstream/forms.py, openlibrary/templates/account/create.html
Closes #9467.
Feature. Improves registration form performance by ensuring lightweight formatting checks (i.e. username field length, email format) all take place on the frontend before the backend query runs.
In `realtime_account_validation.js` a set of formatting checks run first, and if any of them fail the appropriate error is rendered. 
If they all pass, any errors are cleared and the query to the API endpoint in `account.py` runs, to check whether the username/email address is taken. This meant I could remove the error-clearing `else` condition from the `ajax` call, as the errors will be auto-cleared before the call happens. 
It also allowed me to remove the formatting checks from the API endpoint entirely, as they are now duplicated by the js validation -- _but_ duplicative …
=> Move registration formatting checks to frontend

openlibrary/plugins/openlibrary/js/lazy-thing-preview.js
Closes #9535 . Fixes lists with many items timing out when lazy-rendering the book titles/covers.
- A _better_ solution might be make these load when they're rendered; since now we're fetching/rendering all 400 books when the user likely only ever be looking at max 10 at a time, but since this page is only viewable by one when logged in and looking at their own list, this is sufficient for now.
Before: https://openlibrary.org/people/el4ctr0n/lists/OL235242L/Specific_History_Books/edit
After: https://testing.openlibrary.org/people/el4ctr0n/lists/OL235242L/Specific_History_Books/edit
=> Chunk keys in lazy-thing-preview; fix long lists editing

openlibrary/components/AuthorIdentifiers.vue
Storygraph was previously the only known identifier using UUIDs, but BookBrainz and MusicBrainz have recently been added to the known identifiers too, and they both use UUIDs as well.
Closes #9503
fix
This simply removes the matching of UUIDs entirely.
Edit an author, paste in a UUID. Storygraph should _not_ get automatically selected.
(I have not done any actual testing of this myself as I don’t have a working environment running OL.)
@jimchamp
=> fix: Don’t autoselect identifier for UUIDs

Readme.md
Closes: #9091
This PR improves the structure of the README.md file by adding a dedicated "Contributing" section. This section provides a brief introduction to the various ways volunteers can contribute to the Open Library project, making it easier for new contributors to get started and understand how they can help. The changes aim to make the documentation more organized and user-friendly.
1. **Added a "Contributing" Section in README.md**:
- Created a new section titled "Contributing" in the README file.
- Provided a brief introduction to the various ways contributors can participate (e.g., developers, designers, librarians).
- Included links to relevant documents and pages for each type of contributor:
- Developers: Linked to `CONTRIBUTING.md`.
- Librarians: Linked to the [volunteer …
=> Improved Documentation Structure for New_Contributors

openlibrary/book_providers.py, openlibrary/i18n/messages.pot, openlibrary/templates/book_providers/ia_download_options.html
Reverts internetarchive/openlibrary#9555 . This one shouldn't have gone in yet ; it was just saving some code from the web books PR. We should've labelled it as a draft, but also should've tested the feature before merging! Two failures in process there :P Going to revert this one and leave the PR open as a draft.
=> Revert "Add LCP download links for IA"

openlibrary/coverstore/code.py
Work towards #9560 
The backing IA item is struggling with traffic, but will be re-enabled once it is switched from .tar to .zip in the next week or so
Previously erroring covers (eg https://covers.openlibrary.org/b/id/8791306-L.jpg) are no longer erroring and serving the smaller image
@mekarpeles @hbromley
=> Temporarily downscale 8XXXXXX-L.jpg covers

openlibrary/templates/admin/people/index.html, openlibrary/templates/admin/people/view.html, openlibrary/templates/support.html, static/css/components/form.olform.less, static/css/legacy.less
Subtask of #9605.
Feature. Replaces jQuery `validate` required field and email validation with built-in HTML validation to improve performance, JS-disabled functionality, and internationalization.
Quite simple! Just removed the `validate` class (which triggers the plugin), and replaced each `class="required"` with the HTML `required` attribute and each `class="email"` with the HTML `type="email"` attribute.
Also involved some CSS fixes to keep input styling consistent, same fixes should hold for all relevant PRs.
1. Go to one of the relevant forms, i.e. `/contact`
2. Enter a badly formatted email and/or leave a required field blank, hit submit
3. The submission should fail and you should see an HTML-native error message
@cdrini
=> Replace jQuery `validate` in admin and support forms

openlibrary/templates/books/edit/edition.html
Closes #9235
fix
Adds a new page-local variable `is_librarian` which is then checked for in the call that decides whether to add the “-- Move to a new work” option in the Work move dropdown list.
**NOTE:** I have _not_ run tests or manually tested this in a working environment, as I haven’t set one up (yet?), and the `pre-commit` hook failed due to an <q>Error getting the version from source `vcs`</q> which seems unrelated to this PR.
1. Edit an edition with a librarian account which is _neither_ super librarian _nor_ admin.
2. The “-- Move to new work” option should be available.
I didn’t find anywhere where the existing behaviour was tested in automated tests, and thus also haven’t edited or added any such tests.
@seabelis
=> Permit librarians to move editions to a new work

openlibrary/i18n/messages.pot, openlibrary/macros/ManageLoansButtons.html, openlibrary/macros/ManageWaitlistButton.html, openlibrary/macros/databarWork.html, openlibrary/templates/account/readinglog_stats.html, openlibrary/templates/admin/attach_debugger.html, openlibrary/templates/admin/block.html, openlibrary/templates/admin/loans_table.html, openlibrary/templates/admin/people/view.html, openlibrary/templates/admin/sponsorship.html, openlibrary/templates/home/loans.html, openlibrary/templates/jsdef/LazyAuthorPreview.html, openlibrary/templates/jsdef/LazyWorkPreview.html, openlibrary/templates/lists/export_as_html.html, openlibrary/templates/lists/widget.html, openlibrary/templates/publishers/view.html, openlibrary/templates/recentchanges/merge/comment.html, openlibrary/templates/recentchanges/undo/view.html, openlibrary/templates/search/snippets.html, openlibrary/templates/type/author/view.html, openlibrary/templates/work_search.html, scripts/detect_missing_i18n.py
Subtask of #9486.
Fix. This PR adds `i18n` syntax in cases where the text to be translated includes a variable or variables. See the i18n [guide](https://github.com/internetarchive/openlibrary/wiki/Internationalization#html-files) for full syntax info and instructions.
Separated the PR's by `i18n` syntax type for ease of review, this one is scoped to cover all the `i18n` variable syntax.
Also includes removing relevant files from `i18n` exclude list so as to confirm they now pass the `detect-missing-i18n` check.
1. Find a newly `i18n`-ed phrase in one of the files that includes a variable
2. Confirm that the new variable is assigned to the correct variable name, i.e. `View $num_works works` should become `$_('View %(count)d works', count=num_works)`
3. Confirm that the new variable uses …
=> `i18n` syntax additions with variables

openlibrary/i18n/messages.pot, openlibrary/macros/BookPreview.html, openlibrary/macros/LoanStatus.html, static/css/components/read-panel.less
Closes #9606.
Fix. Combines the phrase "Preview Only" in the `i18n` syntax instead of translating each word separately, which was messing with word order in translation.
Very simple! Just moved start/finish of `i18n` syntax and switched to the `$:_(' ')` inner HTML version.
1. Check the `messages.pot` file
2. Confirm that it now includes "Preview Only" as a full phrase (with an HTML `span` element and its corresponding closing tag included)
=> Combine the phrase "Preview Only" for internationalization

openlibrary/catalog/add_book/__init__.py, openlibrary/catalog/add_book/load_book.py, openlibrary/catalog/add_book/tests/test_load_book.py
fixes #9599
Corrects some expected type issues introduced in https://github.com/internetarchive/openlibrary/commit/53d376b148897466bb86d5accb51912bbbe9a8ed
and possibly a pre-existing inefficiency where in some cases existing `Author` objects were sent through the author matching process to find matches... 
Closes #
=> Sort out Author types on import

openlibrary/i18n/messages.pot, openlibrary/templates/covers/manage.html
Closes #9602 
Cancel Button has been removed from the author photos "manage" page.
Visit any author page, click on "Add Author Photos," then navigate to the manage tab and check if the cancel button has been removed from the bottom.
@RayBB
=> Remove broken "Cancel" button on author photos "manage" page

openlibrary/catalog/get_ia.py, openlibrary/catalog/marc/tests/test_get_subjects.py, openlibrary/catalog/marc/tests/test_parse.py, openlibrary/plugins/importapi/code.py, openlibrary/plugins/importapi/metaxml_to_json.py, openlibrary/plugins/upstream/borrow.py, scripts/lc_marc_update.py
This defaults `lxml` to not use external entity expansion (XXE) when parsing XML.
This is identical to #9523, except I can't seem to push to the branch to update the PR so the linting tests pass, so I simply made a new branch + PR.
For more on XXE, see https://codeql.github.com/codeql-query-help/python/py-xxe/
As XXE is not currently used, we might as well disable this.
The place this matters is importing MARC records via the MARC XML method. That is the place to watch for impact.
=> Feature: default to no external entity expansion with XML parsing

openlibrary/i18n/messages.pot, openlibrary/templates/books/custom_carousel.html
Closes #9614
Prevents `None` entries from being added to the `author_names` list.
=> Exclude `None` in `author_names` list

openlibrary/components/BulkSearch/components/BulkSearchControls.vue
Closes #9620 
This PR switches our Bulk Search feature to use a cheaper ChatGPT model. 
Go to  ```/search/bulk```, and try it out. You'll need to provide your own OpenAI API key. 
@cdrini
=> Update BulkSearchControls.vue to use the new ChatGPT 4.o mini

openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/js/add-book.js, openlibrary/templates/books/add.html
Subtask of #9605.
Feature. Replaces jQuery `validate` required field and email validation with built-in HTML validation to improve performance, JS-disabled functionality, and internationalization. 
Also replaces the custom `publish-date` validation with a simple new on-blur function in `add-book.js` that reuses the same logic.
Most of it was quite simple! 
- Switched out the `class="required"` for the HTML `required` attribute where applicable
- Created a quick validation function to show/hide errors if the publish date is in the future, reusing this logic from `validate.js`:
https://github.com/internetarchive/openlibrary/blob/800bcabfc535142da3a2ba2b4f5f9e39f66e6ecb/openlibrary/plugins/openlibrary/js/validate.js#L23-L28
- Had to move the `i18n_strings` around a bit in the form so they …
=> Replace jQuery `validate` in book add form

.vscode/launch.json, openlibrary/plugins/admin/code.py, openlibrary/templates/admin/attach_debugger.html
Closes #9613 . The debugger now works again! 🥳 
- Update options to the latest APIs
- Fix JS issues causing button to be disabled
Follow the steps on https://github.com/internetarchive/openlibrary/wiki/Debugging-and-Performance-Profiling#using-a-debugger
The debugger should now attach at the end of that! You should see the little floating toolbar that allows for pause/skip/etc . And you can add a break point to the code via the VS Code UI, and it'll stop there :)
@benbdeitch
=> Fix debugger/debugpy not working

openlibrary/i18n/messages.pot, openlibrary/templates/account/reading_log.html, openlibrary/templates/search/searchbox.html, openlibrary/templates/type/author/view.html
Closes #9557
This PR fixes issue #9557 by implementing new search box in author and reading log pages
Replaced input tags with render_template() call
Go to My Books -> Reading log (left side menu) pages or go directly to any author's page
Author page
Reading log pages
@cdrini
=> Use new search box on reading log pages and author page

openlibrary/templates/admin/people/view.html
Closes #9652
Checks for `Account` object before seeing if the account has admin privileges.
=> Fix `/admin/people` pages for certain accounts

.github/workflows/new_comment_digest.yml, scripts/gh_scripts/issue_comment_bot.py
Closes #9513
Makes several changes to our daily `new_comment_digest` GitHub workflow and related scripts:
- Switch heavily rate-limited site-wide GitHub search call to more permissive repo issues search call
- Add additional issue filtering to compensate for reduced search faceting on new search endpoint
- Add guard to workflow so that it only runs from this repo
- Configured workflow to allow maintainers to provide the following inputs when manually triggering the workflow:
- Slack Channel
- Hours until issue is stale
- Verbose mode
- Disable labeling issues https://github.com/internetarchive/openlibrary/labels/Needs%3A%20Response 
- Introduces a second of wait time between all GitHub API calls
- Add fail-fast conditions when:
- A required token is not present in the environment (exit …
=> Update failing `new_comment_digest` workflow

openlibrary/core/ratings.py, openlibrary/solr/updater/author.py, openlibrary/tests/solr/updater/test_author.py
Closes #9359 
This PR adds summed counts for each of an authors's works' readinglog counts to the author, which will be useful for popularity measures later down the line. 
The request sent to Solr has been changed to use the Solr JSON endpoint, thus necessitating it to be a POST request rather than GET. This allows for aggregations like 'sum' to be easily executed within the request.  
A few changes to the return format were made, due to the way in which the Facet API returns data. Notably, each facet is now under the same category, with 'subject', 'place' and '
Simply edit an author's page or reindex their key via the Admin  Solr endpoint, and look for the new 'want_to_read_count' or 'readinglog_facets` categories upon requesting their Solr data. 
@cdrini
=> Aggregate want to read counts by author

openlibrary/solr/updater/author.py
Addendum to #9545 .
This one-line pull request fixes an attempt to access certain keys by dot notation, rather than via brackets. It's a simple fix, so no issue was created. 
@cdrini
=> Fix missing square brackets causing solr-updater error

openlibrary/macros/databarWork.html
Closes #9637
Added extra check before rendering download option to avoid it's visibility when the book is not present in Internet Archive
add same condition that was used to check if read button should be called in LoanStatus.html
```(availability.get('is_readable') or availability.get('status') == 'open')```
Assuming that If a book is no longer available on Internet Archive then it would be Not be readable anyways.
Create a Book, search for the book by it's name and open it, by default it shows Not In Library, and you'll see that Download Options are not visible, while If you open any of the other Book which are available you'll be able to see Download options.
@scottbarnes
=> Hide download options when book is unavailable.

openlibrary/plugins/worksearch/schemes/works.py, openlibrary/solr/query_utils.py, openlibrary/tests/solr/test_query_utils.py
Closes #9585 . Adds a new optional prefix to search fields, `edition.` to mirror our `work.` prefix. This allows you to apply a certain field only to the editions during search.
Before: https://openlibrary.org/search?q=first_publish_year%3A%5B*+TO+1953%5D+language%3Aukr+-id_wikisource%3A*&mode=everything&sort=old&subject_facet=Nationalism
After: https://testing.openlibrary.org/search?q=first_publish_year%3A%5B*+TO+1953%5D+language%3Aukr+-edition.id_wikisource%3A*&mode=everything&sort=old&subject_facet=Nationalism
=> Add "edition." prefix to search to only filter editions

.github/workflows/new_comment_digest.yml
When the new_comment_digest workflow is scheduled to run, it passes the Slack channel to the script without double quotes.  Since this string begins with a `#` character, the slack channel is being treated as a comment.  This, in turn, is causing the script to fail.
This PR quotes the default Slack channel that is passed to the script on scheduled, daily runs.
No change is needed for the code that overrides the Slack channel when this workflow is manually triggered, as the channel is quoted during that step.
As this bug only manifests during scheduled runs of the workflow, manually testing this branch will not suffice for QA.
A reviewer could include this branch in their repo, adjust the scheduled run time of the workflow [here](https://github.com/internetarchive/openlibrary/blob/79dccb33a …
=> Quote value of Slack channel in `new_comment_digest` workflow

openlibrary/components/BulkSearch/components/BulkSearchControls.vue, openlibrary/components/BulkSearch/utils/classes.js
Closes #9621
This code refactors Bulk Search to handle the extraction of authors and titles from a text in a different manner. Previously, these methods were located within the `BulkSearchControls.vue` file, which was somewhat messy. Now, they're abstracted to inherit from a common `AbstractExtractor` class, and are imported from a different file. 
Use Bulk Search, and test out the various samples. Each should function with at least one extraction algorithm. 
@cdrini
=> Altered BulkSearch to handle extractors in their own class

openlibrary/components/BulkSearch/utils/searchUtils.js, openlibrary/plugins/openlibrary/lists.py
Closes #9667
Currently, there's no endpoint to allow a logged-in user to add a new list without pattern-checking for their name. This poses a problem in the new Bulk Search feature, as it has to build the list in Vue, and getting access to the `web.ctx.site` variable (where that information is stored) is a non-trivial task in javascript. This PR sidesteps the problem, by creating a new endpoint in python to automatically redirect to the list creation endpoint for the currently logged in user. 
To test, perform a bulksearch and create a list. With the current structure of how the Bulk Search component works, it'll always try to link to the main Open Library page. This will be fixed in a future PR, but for now, just edit the `openlibrary.org` portion of the URL to `localhost:8080`, or …
=> Added new endpoint to create a user list from a link.

openlibrary/book_providers.py, openlibrary/i18n/messages.pot, openlibrary/plugins/worksearch/code.py, openlibrary/plugins/worksearch/schemes/works.py, openlibrary/plugins/worksearch/tests/test_worksearch.py, openlibrary/templates/book_providers/wikisource_download_options.html, openlibrary/templates/book_providers/wikisource_read_button.html
Closes #8545
Feature: Adds web support for Wikisource as a trusted book provider
The implementation itself is subject to change as I dig deeper into what options are available to us for importing. For example, Wikisource page titles are not necessarily static, but in this implementation they are effectively used as IDs.
No data to test with yet! Do I need to do anything besides verify that OL builds and runs locally without crashing?
All four of the links on the left hand side, as well as the read button, are fully functional upon testing with imported production data! I'm not sure how to test the read button toast, though.
@cdrini 
Attribution Disclaimer: By proposing this pull request, I affirm to have made a best-effort and exercised my discretion to make sure relevant sections of this …
=> Add wikisource trusted book provider

openlibrary/coverstore/code.py
Part of #7478 . We redirected all large covers in this range to their medium counterparts because taking them out of the tars was very slow. Hank converted the tars to zips, so now we can serve them large again!
On prod, covers work! And covers like http://covers.openlibrary.org/b/id/8000001.jpg are large.
=> Support covers in .zip in l_covers_0008

openlibrary/i18n/messages.pot, openlibrary/templates/type/author/edit.html
This PR updates the placeholder text for the author names input field to reflect the new guidelines. The updated text provides a clearer example and instructions for listing names.
- Updated the placeholder text to: "Does this author go by any other names? For example: Lev Nikolayevich Tolstoy was also known as Leo Tolstoy. Please list one name per line."
- Verified that the updated text appears correctly in the input field.
Fixes #9272
Apologies for the delay in raising this PR. Please let me know if any further changes are required.
=> Update description of Alternative names on Author Edit page

openlibrary/coverstore/code.py
=> All 8* covers now in zips

openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/code.py, openlibrary/templates/batch_import.html, openlibrary/templates/batch_import_view.html
Closes #9681
Add endpoint to view status of batch import (`/import/batch/<id>`).
* **New Class and Endpoint:**
- Add `BatchImportView` class in `openlibrary/plugins/openlibrary/code.py` for the path `/import/batch/(\d+)` with a `GET` handler.
- Implement the `GET` handler to retrieve batch import status from the database.
- Support pagination (`page` and `limit`) and sorting (`added_time`, `import_time`, `status`) in the handler.
- Perform a `GROUP BY` query by `status` to get the total number of rows for the batch.
* **Template for Batch Import View:**
- Create a new template file `openlibrary/templates/batch_import_view.html` to display the batch import status.
- Include a table with columns for all fields in the `import_item` table.
- Support pagination and sorting in the table.
- …
=> Add endpoint to view status of batch import

openlibrary/book_providers.py, openlibrary/templates/book_providers/direct_read_button.html
Closes #9639 
This PR stops non-DirectProvider web books from being matched as `DirectProvider`s.
It also stops every `DirectProvider` book on a page from triggering the same toast message.
With respect to the first issue:
The `Storage` objects that ultimately come from `SearchResponse` have `Acquisition` objects in their `providers` fields, so every web book search result will have a `providers` attribute.
This PR limits the matching for `DirectProvider` to cases where the `Acquisition` object has a value other than `None`, which is the default initialization value for `Acquisition.provider_name`.
More exploration will be needed to see whether a similar mis-match problem occurs when there is more than one `Acquisition` per `Work`.
With respect to the second issue:
The …
=> Fix web book toast message not matching the web book read

openlibrary/data/sitemap.py, openlibrary/templates/site/head.html
Closes #9634
This PR adds a `lang` attribute to the `<html>` tag to specify the primary language of the document. This attribute is crucial for accessibility, as it helps screen readers and other assistive technologies interpret the language correctly, ensuring proper pronunciation and comprehension for users. The `lang` attribute has been set to `"en"` for English, as this is the primary language of the content.
1. Open the modified HTML document in a browser.
2. Inspect the `<html>` tag to confirm the presence of the `lang="en"` attribute.
3. Use a screen reader or accessibility tool to verify that it recognizes the language of the document as English.
@cdrini
=> Add lang attribute to <html> tag for accessibility improvement.

openlibrary/i18n/messages.pot, openlibrary/templates/jsdef/LazyWorkPreview.html
Subtask of #9486.
Fix. Ensures issue count renders correctly in list edit page. 
As the result of a change in #9506 to improve the `i18n` in `LazyWorkPreview.html`, the list edit page displayed the following error and did not correctly substitute the variable in the `i18n` text:
I was able to clear the error with the first commit, by switching the `%(count)d` to `%(count)s` so as to correctly type the variable, but the incorrect text (`%(count)s editions`) was still rendering.
I confirmed by trying a variable substitution in the author field that the `jsdef` format does not seem to accept `%s` substitutions in `i18n` text, which would explain why for the author field the `by` is `i18n`-ed by itself, instead of following the more traditional `$_('by %(author)s', author=author.name)` …
=> Change `i18n` rendering for `edition_count` in lazy work preview

openlibrary/i18n/messages.pot, openlibrary/templates/recentchanges/merge/comment.html
This commit fixes string interpolation on the merge history comment.
Closes #9728 
Fix
See the following:
- This should have incorrect string interpolation in the comment: https://openlibrary.org/recentchanges/2024/08/07/merge-authors/135506063
- This should not: https://testing.openlibrary.org/recentchanges/2024/08/07/merge-authors/135506063
=> Fix: correct comment text on merge history

openlibrary/macros/CacheableMacro.html, openlibrary/plugins/upstream/utils.py
In support of: #9058, #8279
Creates new `CacheableMacro` macro, which is used for caching macros.
Usage:
```
$# Display a cached list of `/collections` page links:
{{CacheableMacro('PageList', '/collections')}}
$# Display cached carousel filled with classic Goosebumps books:
{{CacheableMacro('QueryCarousel', 'subject:"collectionID:goosebumps1"', title="Classic Goosebumps (1992-1997)")}}
```
To compare, here is how these same macros are called today:
```
$# Display a list of `/collections` page links:
{{PageList('/collections)}}
$# Display carousel filled with classic Goosebumps books:
{{QueryCarousel('subject:"collectionID:goosebumps1"', title="Classic Goosebumps (1992-1997)")}}
```
=> Create `CacheableMacro` macro

openlibrary/templates/books/edition-sort.html
Closes #9253 
hotfix
This pull request addresses the issue of the "in English" link in the editions list on the work page. The link has been converted to plain text to improve the user experience by removing unnecessary navigation. The changes were made in the template file to render the language text as plain text instead of a hyperlink.
1. Pull the latest changes from this branch.
2. Start the application using Docker Compose.
3. Navigate to a work page with editions listed in different languages.
4. Confirm that the "in English" text is displayed as plain text and is not a clickable link.
Before changes:
After changes:
@RayBB
=> #9253 Removed the "in English" link from the editions list on a work page.

openlibrary/templates/books/edit/edition.html
Closes #9731 
**Fix**: Set minimum values for book dimensions and weight inputs to prevent zero or negative values
Sets minimum values for the book's weight and dimensions inputs to ensure that users cannot enter zero or negative values.
Weight: Minimum value adjusted to 0.01
Dimensions: Minimum value set to 0.1
1. Verify Weight Input: 
Navigate to the book weight input field.
Ensure the minimum allowed value is set to 0.01
Try entering value below minimum and ensure they are not accepted.
Check that the input fields correctly accept values at or above the minimum.
2. Verify Dimensions Input:
Navigate to the book dimensions inputs (height, width, depth).
Ensure the minimum allowed value is set to 0.1
Try entering value below minimum and ensure they are not accepted.
Check that the input …
=> Fix: minimum values for book dimensions and weight to prevent zero or negative inputs

openlibrary/i18n/messages.pot, openlibrary/templates/account/readinglog_stats.html, openlibrary/templates/jsdef/LazyAuthorPreview.html, scripts/detect_missing_i18n.py
Closes #9718
It seems `jsdef` needs to use `sprintf` for `%s` string formatting, and the JavaScript implementation, unlike the Python one in `helpers.py`, doesn't support keywords, so multiple arguments must be passed with sequential `%s` replacements.
This also fixes
- titles not displaying in the author preview, which has apparently been broken for over... 15 years. :(
- the word "subjects" displaying when there are no subjects.
Edit a work, attempt to edit the authors, and ensure that the book count _and_ titles show up properly, and that singular and plurals are handled appropriately for the book count.
For some reason, finding an author with only one book proved a challenge.
- 1 book: `Javier Ruiz Sierra` ("1 book titled...")
- 0 books: `Felipe Palacios Sierra` ("No books …
=> Fix for jsdef not handling sprint style Python formatting

openlibrary/i18n/ar/messages.po
Translated with LLM. Reviewed and edited manually. "Open Library" is translated as "المكتبة المفتوحة", the same as the title of the article on [Arabic Wikipedia](https://ar.wikipedia.org/wiki/%D8%A7%D9%84%D9%85%D9%83%D8%AA%D8%A8%D8%A9_%D8%A7%D9%84%D9%85%D9%81%D8%AA%D9%88%D8%AD%D8%A9). However, I think it's a bit literal translation and "المكتبة الحرة" (~"Libre/Free library") is a better translation.
=> Add Arabic translation

openlibrary/templates/books/edit.html, openlibrary/templates/tag/add.html, openlibrary/templates/type/author/edit.html, openlibrary/templates/type/tag/edit.html
Subtask of #9605.
Feature. Replaces jQuery `validate` required field and email validation with built-in HTML validation to improve performance, JS-disabled functionality, and internationalization.
Quite simple! Just removed the `validate` class (which triggers the plugin), and replaced each `class="required"` with the HTML `required` attribute and each `class="email"` with the HTML `type="email"` attribute.
1. Go to one of the relevant forms, i.e. a book edit form
2. Enter a badly formatted email and/or leave a required field blank, hit submit
3. The submission should fail and you should see an HTML-native error message
@cdrini
=> Replace jQuery `validate` in book/author/tag edit forms

openlibrary/plugins/openlibrary/config/edition/identifiers.yml
LearnAwesome is no longer active and therefore, there is no need to maintain their identifiers any more. See #9747
Closes #9747
=> Fix #9747 Remove LearnAwesome from identifiers.yml

openlibrary/plugins/upstream/addtag.py
Closes #9684
Makes the following changes to our existing code for adding new Tags:
- Removes unused imports
- Removes unused logger
- Removes unused redirect
- Redirects patron to login on unauthenticated `/tag/add` request
- Raises unauthorized `HTTPError` when the patron makes a `/tag/add` request while not a member of either admin, super-librarian, or librarian usergroups.
Permissions were not modified on the [`Tag.create` method](https://github.com/internetarchive/openlibrary/blob/1a6fde92e3bbd921736d34581ad885c3e4d0e0a4/openlibrary/core/models.py#L1170), as I've noticed that our other models don't include methods for object creation.  I'm thinking that the `create` method can be replaced by some `Tag` creating object in `addtag.py` in the near future.
1. Ensure the `/addtag` page …
=> Small refactor of `Tag` code

openlibrary/coverstore/code.py
Closes #9560 (at least for critical items in the 8M range).
This does not update the database -- the `filename` field is the only field which requires an update, but they are kept as is in case there's any need to use the existing tar offsets. The zip filenames are automatically inferred by the cover id.
The following script can be used to generate db statements if we want to update the `filename` field:
```py
x = 10_000
for i in range(100):
p = str(i).zfill(2)
print(f"update cover set filename='covers_0008/covers_0008_{p}.zip' where id >={str(8_000_000 + (i * x))} and id < { str(8_000_000 + ((i+1) * x))};")
```
For the purpose of doing this in a non-breaking way, I've already added a field to the `coverstore.cover` table called `filename_old` which equals the current value of `filename` …
=> remove special case for 8M range covers

openlibrary/plugins/upstream/utils.py, openlibrary/plugins/worksearch/autocomplete.py
Closes #8146
Refactor the current [autocomplete_languages](https://github.com/internetarchive/openlibrary/blob/dc35977560ae0ca752eda36017769fdd82f15daa/openlibrary/plugins/upstream/utils.py#L717) util function to include a limit parameter as well as add prefix matching of inner language name words. For example, '/languages/_autocomplete?q=greek' will match with 'Ancient Greek', 'Modern Greek', and 'Greek' rather than just 'Greek' as it does now.
Consolidates existing match checks into a more generic matching function that allows for optional translation id.
A limit parameter was also added which controls how many results will be added to the returned iterator. Previously autocomplete_languages would return the total number of matches then was truncated down to a default limit of 5 when …
=> Refactor language search autocomplete and add inner word matching

bundlesize.config.json, openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/code.py, openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/js/search.js, openlibrary/plugins/worksearch/code.py, openlibrary/templates/search/work_search_facets.html, openlibrary/templates/search/work_search_selected_facets.html, openlibrary/templates/work_search.html
Closes #7271
Search facets sidebar and selected facets are now asynchronously loaded.  On initial page load, the sidebar will contain a number of loading indicators, and no selected facets.  Once the `/partials` call has successfully returned, the sidebar is replaced with a new sidebar that includes that facet counts, and the selected facets are displayed below the search bar.
`facet_map` no longer needs to be passed to the `work_search_facets` template, and is instead retrieved via a new `public` function.
The overridden `changequery` function has been updated to include a new `_path` keyword parameter.  When `_path` is present, it is used in place of the current `web.ctx` path.
=> Asynchronously load search facets sidebar

.pre-commit-config.yaml
Closes #9750
This commit adds the stubs necessary for `pre-commit run --all-files` to run successfully.
`types-all` has been deprecated and removed from PyPI: https://github.com/asottile-archive/types-all
See
https://mypy.readthedocs.io/en/stable/running_mypy.html#library-stubs-not-installed for more.
Tested with:
```
❯ pre-commit clean
❯ pre-commit run --all-files
```
@cdrini
=> Enumerate `mypy` stub dependencies for`pre-commit`

openlibrary/core/helpers.py
Related to #8028
Adds typehints in core/helpers.py
@scottbarnes
=> Add some typehints in core/helpers.py

openlibrary/plugins/upstream/addtag.py, openlibrary/templates/subjects.html, openlibrary/templates/tag/add.html
Addresses #9685
Passes Tag `name`, `type`, and optional `sub_type` (for subject type) from the subject page to the Tag creation template.
The `name` and `type` parameters are now required by the `/tag/add` GET handler.
Tag creation form is now prefilled with the `name` and `type`.  ReCaptcha has been removed from the "Add Tag" page, as this view is restricted to librarians.
While logged in as a `super-librarian` (this is important and checked on subject page --- will be fixed later):
1. Navigate to a subject page that __does not__ have a linked subject.
2. Click the "Edit" button.
3. Ensure that the "Add Tag" page is displayed, and that the form's name input the subject type option are prefilled/selected.
=> Prefill "Add Tag" form

openlibrary/i18n/messages.pot, openlibrary/plugins/upstream/addtag.py, openlibrary/templates/tag/add.html, openlibrary/templates/type/tag/edit.html
Closes #9780
Changes to require `tag_type` and `name` whenever a Tag is created or updated.
> [!IMPORTANT]
> Until #9776 is merged, validations will not occur when `?m=edit` is used to navigate to the edit view.
While logged in as a `librarian`, test the following:
1. Go to `/tag/add` page and attempt to submit the form without filling the Tag name input, or selecting a Tag type.  Expect to see "Required field" messages by these inputs.
2. Using your preferred tool, send some `POST` requests to the `/tag/add` endpoint.  Ensure that you receive a `400` when either the `name` or `tag_type` is missing from the request.
3. Repeat step 1 on an existing Tag's edit page.
4. Repeat step 2 on an existing Tag's edit page.
=> Require Tag type on creation, update

openlibrary/i18n/messages.pot, openlibrary/macros/ProlificAuthors.html, openlibrary/macros/PublishingHistory.html, openlibrary/macros/RelatedSubjects.html, openlibrary/templates/subjects.html
Closes #9785
Extracts three subject page components into macros:
- `ProlificAuthors.html`: The list of prolific authors on a subject
- `PublishingHistory.html`: The publishing history graph for a subject
- `RelatedSubjects.html`: Links to related subject pages
Additionally, removes unreferenced `renderPublishers` `jsdef` function.
The existing carousel is a `custom_carousel` template, and hasn't modified.
`renderSubjects` in the `RelatedSubjects` macro is no longer a `jsdef` function.  This function worked properly when called from the browser console, but wasn't referenced in our codebase.
The `renderAuthors` `jsdef` function was not included in the `ProlificAuthors` macro.  This function __did not__ work properly when called from the console, due to an `Uncaught ReferenceError: page is …
=> Create macros for subject pages

openlibrary/i18n/messages.pot, openlibrary/plugins/upstream/addtag.py, openlibrary/templates/tag/add.html, openlibrary/templates/type/tag/edit.html, openlibrary/templates/type/tag/tag_form_inputs.html
Addresses #9784
Creates a new template for our "Add Tag" and "Edit Tag" form inputs.  Now, the labels for each form will contain the same copy.  The "Add Tag" `POST` handler has been updated to set a tag's name using the `name` form data (updated from `tag_name`).
Other changes:
- Removed conditional [`not_logged`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/lib/not_logged.html) message from "Add Tag" form, as patrons must always be logged in to see this page.
- Removed Tag `name` and `type` validations from the "Add Tag" `GET` handler.  This allows us to navigate directly to the `/tag/add` page ("Bad Request" responses are raised, otherwise).
While logged in as a `super-librarian`:
1. Add a Tag.  Verify the new Tag's name, description, and type.
2. …
=> DRY `Tag` form inputs

openlibrary/core/imports.py, openlibrary/core/vendors.py, openlibrary/i18n/messages.pot, openlibrary/plugins/importapi/code.py, openlibrary/templates/history/sources.html, openlibrary/templates/showgoogle_books.html, openlibrary/views/showmarc.py, scripts/affiliate_server.py, scripts/promise_batch_imports.py, scripts/tests/test_affiliate_server.py
Closes #9574
Feature.
This PR adds the ability to fetch Google Books data by ISBN via BookWorm and stage the result for later import.
There is a hypothetical, unused, class named `BaseLookupWorker` that could function to allow different queues and threads for different backend APIs. Not sure if Amazon is a total outlier. We'd either want to use this or remove it prior to merging.
This PR changes the way Just In Time imports are handled, insofar as it disables that. The rationale here is that #9440 added the ability for incomplete records to be augmented with BookWorm data. This means if an import is attempted with an incomplete record, a `staged` record can be used to supplement the metadata. The JIT Candidates function marks all `staged` matches as `pending`, and because they can be …
=> Fetch metadata from Google Books by ISBN + stage

openlibrary/components/AuthorIdentifiers.vue, openlibrary/plugins/openlibrary/config/author/identifiers.yml
Closes https://github.com/internetarchive/openlibrary/issues/9791
feature
Adds Library of Congress Name Authority File (LC NAF) as an Author identifier in `author/identifiers.yml`.
The `label` has been shortened to just “Library of Congress” to avoid having an obscenely long label in the drop-down lists and also avoid obscure acronyms (“NAF”) in it that are likely to cause more confusion than clarity.
The URI identifiers given by LoC themselves start with “http://” but I have opted to use “https://” for the `url` so patrons etc. won’t need a redirect or similar to get to the page.
**Update:** Also added an entry for autoselection of LoC when added the ID on the author editing page.
1. Apply patch
2. Restart app
3. Check that “Library of Congress” appears in the Author identifier dropdown …
=> Add Library of Congress NAF as Author identifier

openlibrary/components/BulkSearch/components/BulkSearchControls.vue, openlibrary/components/BulkSearch/components/MatchTable.vue, openlibrary/components/BulkSearch/utils/classes.js, openlibrary/components/BulkSearch/utils/searchUtils.js
Closes #9679 
This pull request fixes an oversight with Bulk Search, that caused the 'create a list' button to generate a new URL only once all attempts to find books in the OpenLibrary catalogue failed.  Now, each time that that the Solr request returns a book present in our catalog, the 'create a list' URL will immediately update to contain the new seed. 
Select a sample in the BulkSearch, and click 'extract' and 'match'. Then, scroll down rapidly to the bottom of the page, and click 'create a list of full matches' before it finishes loading all of the books. 
@cdrini
=> Changed bulk search's 'Create a List' url to update continuously with new matched books

openlibrary/macros/StarRatings.html, openlibrary/macros/StarRatingsStats.html, openlibrary/macros/databarWork.html, openlibrary/templates/type/edition/modal_links.html, openlibrary/templates/type/edition/view.html, static/css/components/read-panel.less
Closes #9632.
Fix. Prevents the star ratings form (with corresponding id's) from being repeated 3x in the work page, which was a problem for accessibility and code organization/simplicity.
1. Go the page for any book, ideally one that already has at least one star rating
2. Expand to desktop view and inspect the page, confirming that the IDs `starRatingSection` and `ratingsForm` each only appear once
3. Confirm that clicking on the book's star ratings takes you to the star ratings form
4. Adjust the page width until it switches to mobile view, confirming that the IDs `starRatingSection--mobile` and `ratingsForm--mobile` each appear just once on the page
5. Confirm that clicking on the book's star ratings takes you to the star ratings form
@cdrini
=> Pass in mobile parameter to conditionally render star ratings form

openlibrary/plugins/importapi/code.py
Closes #9818 
Implements an error message when there is a JSON parsing error, when using `/api/import`.
To test, use this:
```
curl -X POST http://localhost:8080/api/import -H "Content-Type: application/json" -b ~/cookies.txt -d '{
"title": "Junk record",
"source_records": ["amazon:123456789"],
"authors": [{"name": "author mcauthor"}],
"publish_date": "2000",
}'
{"success": false, "error_code": "Expecting property name enclosed in double quotes: line 6 column 1 (char 148)", "error": "Failed to parse import data"}
```
@scottbarnes
=> add meaningful error messages for import errors

openlibrary/plugins/worksearch/schemes/works.py, openlibrary/solr/updater/edition.py, openlibrary/solr/updater/work.py
Closes #7276 . Fix.
| **DO NOT MERGE** Want to test this during a full reindex first for perf |
| --|
Do this by including a copy of author data at the edition level. This increases the storage cost and is somewhat redundant, but the search benefits are worth it.
Will only really take effect after the next full reindex.
- Main concern here is if this will add too much data into solr ; since this will duplicate a lot of info! Will need to test for perf once deploying, and then see.
I tested by copydocs-ing the two clive cussler examples below, and confirming they now matched on just authors in query!
Here's a simple example of searching for the author `greg`
| --- | --- |
| ![image](https://github.com/internetarchive/openlibrary/assets/6251786/9bdcbc0e-bec7-49c3-8bc3-2159 …
=> Make "All" search match books by an author

compose.yaml, conf/solr/haproxy.cfg, openlibrary/solr/updater/author.py, openlibrary/solr/updater/edition.py, openlibrary/solr/updater/list.py, openlibrary/solr/updater/work.py, openlibrary/tests/solr/updater/test_author.py, scripts/solr_builder/Dockerfile.olpython, scripts/solr_builder/build-cython.sh, scripts/solr_builder/compose.yaml, scripts/solr_builder/setup.py, scripts/solr_builder/solr_builder/index_subjects.py, setup.py
Closes #8234 
Puts an end to the stage of our solr stuck on the staging server! These are the settings that were used to run the solr reindex. Some of the features in the issue aren't correctly there because of how bumpy this reindex was, and might require another full reindex :(
- Increased some timeout for solr requests; was noticing a few things timing out during solr updater runs
- Switched lists solr updater to use POST to avoid url too long errors
- Remove `if solr_next` wrappers
- Reduce frequency of solr haproxy health checks to match our other services
=> Finalize solr reindex

openlibrary/solr/updater/author.py
Closes #9558 
This PR fixes a bug in the author Solr updater where both edition and work counts were mistakenly used instead of just work counts. By correcting this, author search results will be more accurate and meet user expectations, showing the correct number of works associated with each author rather than inflated counts that included editions.
PR involves updating the Solr query logic to correctly count works instead of editions for authors.
To verify the fix implemented in this PR, follow these steps:
1. Visit [this link](https://openlibrary.org/search/authors?q=chris+wiggins&mode=everything) on the Open Library website.
2. Observe that the author "Chris Wiggins" is currently shown to have 8 books.
3. After applying this PR, the author should correctly display only 2 books, …
=> Fix author indexing counting editions instead of works

openlibrary/components/MergeUI.vue
Closes #9760
Fix
Checks the status code of a works merge request and warns users that they may not have the correct permissions to do the merge. A 403 status code is returned by the function ```do_merge``` within ```components/MergeUI/utils.js``` if the user does not have the ```/usergroup/api``` assigned to their account.
Create a user account with only super librarian permissions (see Project Breakdown for instructions), and attempt to merge works.
@scottbarnes
=> Clearer message for merging works without correct permissions

openlibrary/components/BulkSearch/components/BulkSearchControls.vue, openlibrary/components/BulkSearch/utils/classes.js
Closes #9699
This PR adds another new child of the AbstractExtractor class. The TableExtractor allows for data to be copy-pasted from Google Sheets or other spreadsheet services, and extracts the contents of the 'title' column and the 'author' column, if they exist. 
Currently, the implementation allows for titles to be searched if the author column is empty. This has led to an odd interaction, where searching for 'Mark Twain' in the title ends up incorrectly pulling other books that he wrote.  I'll be debugging that over the next day or so, but I figured I might as well put it up for review. 
Create a table in Google Spreadsheets, then copy it into the input area of the `/search/bulk` page. Select the bottom extraction option, and click 'extract books'. Please ensure that you have titled …
=> Add Support for tabular data entry in Bulk Search

openlibrary/plugins/upstream/borrow.py, openlibrary/plugins/upstream/models.py
Closes #9829
Feature. Adds a new endpoint to redirect to a worldcat page based on identifier data provided for a given edition. Prioritizes oclc, then isbn 13, isbn 10, and finally title.
Adds an extra check to the `plugins/upstream/borrow.py` borrow class. If the endpoint /books/{olid}/{title}/borrow is reached with the parameter `action=locate`, a redirect URL is constructed and redirected to.
- Navigate to an edition page
- Add `/borrow?action=locate` to the end of the url
- Be redirected to worldcat, ensuring that the identifier with the highest priority has been chosen (oclc, isbn13, isbn10, title). If the edition has an oclc identifier, you should be directed to a book page, otherwise the search page.
@mekarpeles
=> Add 'locate' endpoint to borrow API

openlibrary/plugins/upstream/borrow.py
Closes #9829, followup to #9842
Before, the `action=locate` check took place after authentication check meaning it required patrons to be logged in before using this method. We want /borrow?action=locate to be public (not be blocked by auth)
Incognito: https://testing.openlibrary.org/books/OL7826547M/A_Game_of_Thrones/borrow?action=locate
=> Fix /borrow?action=locate not working for logged out users

openlibrary/plugins/openlibrary/js/compact-title/index.js
Closes #9584
Fix
Removes ```isTitleVisible``` boolean in favor of directly checking if the compact element does not contain the ```.hidden``` class for more reliable behavior.
Manually replicated erratic scrolling behavior as seen in #9584 
@RayBB
=> Fix compact title scrolling issue

openlibrary/i18n/messages.pot, openlibrary/i18n/pl/messages.po, openlibrary/i18n/test_po_files.py, openlibrary/templates/type/author/view.html
There were 54 xpassing tests (marked as expected to fail, but were passing).
They were caused by translation tests that had marked all messages.po Polish tests as failing, when most were passing.
Turns out there were 7 tests failing because quotation marks weren't present in the translated strings, and other minor XML closing / quoting issues.
This PR fixes them and enables all the tests to remove the xpassed count in the results.
BEFORE:
```
2099 passed, 9 skipped, 16 xfailed, 54 xpassed, 4842 warnings in 7.02s
```
AFTER:
```
2160 passed, 9 skipped, 9 xfailed, 4842 warnings in 6.72s
```
fix incorrectly quoted Polish translated strings
to remove xpassing test messages
Closes #
I noticed this in another PR where I was using xpassing tests to notify when I'd fixed the bug. The 54 constantly …
=> Fix Polish messages.po to remove xpassing test results (all tests now pass)

openlibrary/templates/search/searchbox.html
May fix issue where the incorrect placeholder text is cached for pages that use the new search box component.
To reproduce the bug:
1. Navigate to https://openlibrary.org/search and verify that the placeholder text is the same in both the top nav search box and the search box in the content area.
2. Use the language selector to switch to another language.  Expect the placeholder text in the top nav to be localized, and the other box's placeholder text to remain unchanged.
1. Navigate to https://openlibrary.org/search
2. Use the language selector to switch languages
3. Verify that the placeholder text is correct
=> Move `searchbox` default placeholder to body of template

openlibrary/catalog/add_book/__init__.py, openlibrary/catalog/add_book/match.py, openlibrary/catalog/add_book/tests/test_add_book.py, openlibrary/catalog/add_book/tests/test_match.py, openlibrary/plugins/upstream/models.py
Closes #9808
Closes #9794
After some investigation, this PR:
* removes the `exact match` check that was matching existing light records with only title + ISBN against MARC records _only_ on the title field, and skipped the more intelligent threshold match method that at least tries to score matches.
* Fixes a longstanding bug where authors were only being compared on edition level authors, even though in general authors only exist on Work records in OL. This problem was masked by most matches occurring on direct ISBN, or title string only matches.
* Renames the method to `find_threshold_match()` and makes sure it is used for performing edition matches
* Adds a specific test for #9808
* Fixes existing test data which had incorrect author data formats, and did not link editions to works. …
=> Fix MARC records incorrectly matching ISBN promise item records

openlibrary/plugins/openlibrary/config/author/identifiers.yml
Closes https://github.com/internetarchive/openlibrary/issues/9856
feature
Adds support for IMDb identifiers in the `author/identifiers.yml` file.
Edit an author and check that IMDb is available as an identifier.
@jimchamp maybe?
=> Add IMDb identifier support for Authors

openlibrary/templates/history/sources.html
Closes #
Adds a readable source for items imported from  Library and Archives Canada / Bibliothèque et Archives Canada
example record:
https://openlibrary.org/books/OL53668244M/Correspondence_and_papers_on_various_subjects_by_the_late_William_Edwards_of_Clarence_Ont._together_
=> Add Library and Archives Canada to MARC sources

scripts/partner_batch_imports.py, scripts/tests/test_partner_batch_imports.py
closes #9768
From looking at one recent data file, there were 264 titles containing "Dumpbin". Most of them were marked as 'Trade Paper'. 3 were marked as e-books.... so that kills my idea of having a format accept-list rather than the current NONBOOK reject list.
The data is not accurately annotated to be clear about what kind of item is being imported, which is disappointing.
This PR 
* rejects 'Dumpbin' and 'Copy bin' titles, and confirms that the supplied format codes aren't sufficient to filter accurately because dumpbins look like books in this field.
* Adds a new 'Product class' check where `OTH` is included in these dumpbin items
=> more ad-hoc title filtering to avoid non-book imports, and exclude OTHER product class

openlibrary/accounts/__init__.py, openlibrary/core/batch_imports.py, openlibrary/core/bookshelves.py, openlibrary/plugins/upstream/borrow.py, openlibrary/plugins/upstream/mybooks.py
Related to #8028 
Adds typehints to openlibrary.accounts and openlibrary.plugins.upstream.mybooks modules
@scottbarnes
=> Add typehints in openlibrary.accounts module

.gitignore, openlibrary/components/LibraryExplorer/components/BookRoom.vue, openlibrary/components/LibraryExplorer/components/BooksCarousel.vue, openlibrary/components/LibraryExplorer/components/FlatBookCover.vue, openlibrary/components/LibraryExplorer/components/LibraryToolbar.vue, openlibrary/components/LibraryExplorer/components/OLCarousel.vue, openlibrary/components/MergeUI.vue, openlibrary/components/MergeUI/MergeTable.vue, openlibrary/components/MergeUI/utils.js, openlibrary/components/README.md, openlibrary/components/configs.js, openlibrary/components/serve-component.js, package.json, vue.config.js
Work towards #9811
- Give MergeUI the same config url parameters that LibraryExplorer has for controlling data sources. This makes it easy to use the live-reloading dev environment, but have it hooked up to either prod or localhost to fetch data.
- Create a new script for testing vue components, `npm run serve --component=MergeUI`. No more needing to modify `_dev.js`!
- Note: made use of an npm feature I learned about: If you call an npm script with an argument, like `npm run serve --component=Foo`, it automatically sets an environment variable to `npm_config_component`! Very handy. You can then access this from the script using the language's normal environment variable features, e.g. `process.env.npm_config_component`.
- Fix some long-standing bugs preventing vue live server usage on …
=> Make MergeUI/all vue components easier to test locally

openlibrary/plugins/openlibrary/config/work/identifiers.yml, openlibrary/plugins/upstream/utils.py
Closes https://github.com/internetarchive/openlibrary/issues/9234
feature/fix/refactor
This is taking the same steps applied to editions[1] and authors[2] and applying it to works. `get_work_config()` is currently not used for anything, probably because we’re still waiting for an actual [interface to edit the Work identifiers](https://github.com/internetarchive/openlibrary/issues/3430), so this is more of a preliminary step to ensure that Works will be handled in the same way that Editions and Authors are. (And to allow for PRs to add Work identifiers while waiting for that UI, rather than limiting that to OL admins.)
[1] https://github.com/internetarchive/openlibrary/issues/9234
https://github.com/internetarchive/openlibrary/pull/9483
[2] …
=> Read Work identifiers from file

scripts/partner_batch_imports.py
Reverts some recently added title match strings -- dumpbins are not independently published. These strings are very unlikely to match, but there is another method to reject these still in place, the `OTH` product class test. This removes the strings to avoid any confusion about whether they are effective.
via @cdrini 's comment:
https://github.com/internetarchive/openlibrary/pull/9850/files/eb3f33645b247c8fe70c3a71215b05e272f42c61#r1752032348
Closes #
=> Remove ineffective strings in "Independently Published" exclusion list

openlibrary/plugins/openlibrary/pages/languages.page
Adds language codes:
* den / Slavey https://en.wikipedia.org/wiki/Slavey_language
* mga / Middle Irish, https://en.wikipedia.org/wiki/Middle_Irish
Recent partner MARC record imports included some books in these languages. The MARC 21 codes are valid and listed at 
https://www.loc.gov/marc/languages/language_code.html
I have already added the data to the live site.
This PR commits the codes as a record of what codes OL currently recognises.
Successfully imported `mga` record:
https://openlibrary.org/books/OL53772901M/The_Book_of_Ballymote
Successfully imported `den` record:
https://openlibrary.org/books/OL53772927M/Dictionnaire_de_la_langue_d%C3%A8n%C3%A8-dindji%C3%A9
=> Add two more MARC21 language codes: den and mga

openlibrary/templates/admin/people/index.html
The un-escaped $ was causing the `"` to effectively be ignored.
=> Fix find by IA id failing due to un-escaped $

openlibrary/i18n/messages.pot, openlibrary/macros/SearchResultsWork.html, openlibrary/macros/StarRatingsByline.html, openlibrary/macros/StarRatingsComponent.html, openlibrary/macros/StarRatingsStats.html, openlibrary/plugins/worksearch/code.py, openlibrary/plugins/worksearch/tests/test_worksearch.py, static/css/components/readerStats.less, static/css/components/search-result-item.less
Closes #9463 
Pulls ratings_count, ratings_average and want_to_read_count fields from Solr. 
Creates a new macro that accesses these fields and displays ratings_count in star graphic and ratings_count and want_to_read_count in Search Results cards. 
When testing in my local environment, I manually updated the star ratings on the books page to trigger the StarRatingsByline macro to display. 
I created a conditional that requires a minimum of 1 ratings_count and 1 want_to_read_count in order for the StarRatingsByline to display. Should I split up the conditional so that star ratings will display, even if there is no want_to_read_count ? 
@mekarpeles
=> Add Star Ratings & Want To Read counts to Search Result Cards

openlibrary/macros/RelatedSubjects.html, openlibrary/macros/SubjectTags.html, openlibrary/templates/publishers/view.html, openlibrary/templates/type/author/view.html, static/css/components/link-box.less
This request addresses issue #9636, where subject tags and headings were incorrectly marked with `h6` tags. The changes improve accessibility and SEO by updating heading structure to use `h3` instead of `h6`.
- Updated `h6` tags to `h3` in the following:
- `author/view.html`
- `publishers/view.html`
- `macros/SubjectTags.html`
- `macros/RelatedSubjects.html`
- Updated CSS in `link-box.less` to apply styles to `h3` instead of `h6`.
- Verified that tags are now h3 on local web.
- No visual changes in appearance.
=> Changed h6 to h3 in subject tags for better accessibility, and updated CSS

openlibrary/plugins/openlibrary/code.py, openlibrary/templates/site/alert.html, static/css/components/language.less
Works toward #9864
Fetches the current language and displays it in the top bar
=> add current language to topbar in alert.html

bundlesize.config.json, openlibrary/i18n/messages.pot, openlibrary/macros/FulltextSnippet.html, openlibrary/macros/FulltextSuggestionSnippet.html, static/css/components/fulltext-snippet.less, static/css/components/search-results-container.less, static/css/page-user.less
Closes #9479 
- Updates styling to Search Inside Result to match the Search Inside Suggestion Card #1001 
- Eliminates inconsistent footer messages. 
Merged in #9734 and combined the [fulltext-suggestion-snippet.less](https://github.com/internetarchive/openlibrary/blob/master/static/css/components/fulltext-suggestion-snippet.less) to [fulltext-snippet.less](https://github.com/merwhite11/openlibrary/blob/9479/standardize-search-inside-results/static/css/components/fulltext-snippet.less). 
When this PR gets merged in, there will be a merge conflict in page-user.less where the snippet styling files are being imported. 
I will need to resolve the conflict so that both [FulltextSuggestionSnippet.html](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/FulltextSuggesti …
=> Standardize Styling for Search Inside Results

openlibrary/core/cache.py, openlibrary/i18n/messages.pot, openlibrary/macros/QueryCarousel.html, openlibrary/macros/RawQueryCarousel.html, openlibrary/plugins/upstream/utils.py, openlibrary/templates/books/RelatedWorksCarousel.html, openlibrary/templates/home/index.html, openlibrary/tests/core/test_cache.py
Closes #9058
This branch does the following:
1. Updates the `QueryCarousel` macro template to, by default, request a cached copy of the carousel's markup
2. Updates the function that generates cache keys such that the cached function's `args` and `kwargs` are hashed
3. Adds a `use_cache` keyword argument to the `QueryCarousel` macro, which allows us to avoid caching select query carousel
4. Updated the book page's "Related Works" carousel and the home page's "Classic Books" carousel to __not__ be cached
5. Updates cache key prefix to include the macro name when macros are cached
The "Classic Books" carousel is not cached, as it appears on our cached homepage.  Also, both the homepage and our macros are cached for the same amount of time (five minutes).
The "Related Works" carousel is …
=> Cache all query carousels

openlibrary/catalog/marc/parse.py
A handful of partner MARC records imports failed due to unrecognised values is `041$a`
Some were caused by spacing padding characters `" "` and `-`, others where just typos or single instances of data entered in the wrong field e.g.
`041    $aspine title: return re provincial subsidies, 1906.`
In these cases it would be better just to skip the unrecognised language value but still import the rest of the record. Language is not a required field.
Previously, the entire record was being rejected with an `Invalid MARC` exception, which is too extreme (and not correct -- the MARC is otherwise totally valid)
@cdrini Is there an existing mechanism to log warnings somewhere to record when some of these unexpected values  are encountered? Sometimes they can indicate missing language codes we …
=> No longer fail importing MARC records on unrecognised lang code

openlibrary/macros/Profile.html
Adds the current page's path to the bottom of the component times table.  This may help when screenshots of the table are included with requests for assistance.
=> Add current page's path to component times table

openlibrary/plugins/openlibrary/js/bulk-tagger/BulkTagger.js
Closes #9891
Corrects misspelled tag property, which was preventing tags from being removed from the `tagsToRemove` array.
While logged-in with an account that can use the bulk tagger:
1. Navigate to a search result page.
2. Select at least one work.
3. Click the "Tag Works" button to open the bulk tagger.
4. Click on an existing menu option to stage the tag for removal.
5. Click the same menu option to stage the tag for addition.
6. Close the bulk tagger.
7. Open the bulk tagger again.  Verify that there are no duplicate menu options.
=> Fix `BulkTagger` menu option bug

openlibrary/plugins/openlibrary/code.py, openlibrary/templates/site/alert.html
Fixes bugs introduced in #9868
@cdrini
=> fix: add localized current language to topbar

compose.production.yaml, docker/covers_nginx.conf, docker/nginx.conf, docker/web_nginx.conf
Closes #9562 
Feature. Adds rate limiting. See https://blog.nginx.org/blog/rate-limiting-nginx and https://nginx.org/en/docs/http/ngx_http_limit_req_module.html
We may wish to rely on `429` and `403` as distinct status codes rather than commingle them in `444`.
We may also wish to revisit whether blocking CloudFront could actually increase load on our servers, given as a CDN it _may_ be closer to some patrons.
Additionally, and probably as distinct from this PR, we may wish to consider drastically increasing the `cache-control` value for cover images, as it's currently 10800 seconds, or 3 hours, when it could probably be a year, on the perhaps mistaken theory cover images don't change. Though perhaps that would just fill up patron's caches, unless we conditionally set the `cache-control` …
=> Nginx: add rate limiting

openlibrary/components/BulkSearch.vue, openlibrary/components/BulkSearch/components/BookCard.vue, openlibrary/components/BulkSearch/components/BulkSearchControls.vue, openlibrary/components/BulkSearch/components/MatchRow.vue, openlibrary/components/BulkSearch/components/MatchTable.vue, openlibrary/components/BulkSearch/components/NoBookCard.vue, openlibrary/components/BulkSearch/components/TableRow.vue, openlibrary/components/BulkSearch/utils/classes.js, openlibrary/components/BulkSearch/utils/samples.js
Closes #9841 
This PR implements the new Bulk Search v2 designs, providing users with a much improved user-interface, that packages in instructions of how to handle it in a simple to use form. 
Nothing much to note here. It's still made in Vue. I judged a new component   'no-book-card' necessary, as I didn't want to have to refactor 'book card' to handle two entirely separate tasks. 
Load up Bulk Search, and navigate to the page.  It should function. If sizing  is a bit off, edits will be incoming. 
@cdrini
=> Implementing Bulk Search v2 Designs

openlibrary/core/lists/model.py, openlibrary/core/models.py, openlibrary/macros/TableOfContents.html, openlibrary/plugins/upstream/models.py, openlibrary/plugins/upstream/table_of_contents.py, static/css/components/toc.less
Part of #8756
Update the UI to handler rendering a table of contents chapter's subtitle, author, and description.
- Also removed an unused argument, `highlighting`
- Create a dataclass to contain `TocEntry` logic. This will be expanded in future PRs as part of this project to handle things like markdown parsing, etc.
eg
- https://testing.openlibrary.org/books/OL9462467M/Great_Irish_Stories_of_Childhood
=> Add authors, subtitle, and description to TOC on books page

openlibrary/core/models.py, openlibrary/macros/TableOfContents.html, openlibrary/plugins/upstream/addbook.py, openlibrary/plugins/upstream/models.py, openlibrary/plugins/upstream/table_of_contents.py, openlibrary/plugins/upstream/tests/test_table_of_contents.py, openlibrary/plugins/upstream/utils.py, openlibrary/templates/type/edition/view.html
Part of #8756 . Refactor with no user-discernable effects to move the parsing into table_of_contents.py and create a new helper class to manage tables of contents. Stepping stone for the next piece which will support entry data like authors, etc.
~Depends on #9902 .~
- ✅ books without table of contents render correctly
- https://testing.openlibrary.org/books/OL10324632M/STOWELL_SYSTEMS_SCIENCE
- ✅ books with "normal" table of contents render correctly
- https://testing.openlibrary.org/works/OL27482W/The_Hobbit?edition=key%3A/books/OL27289715M
- ✅ books with table of contents + extra fields render correctly
- https://testing.openlibrary.org/books/OL9462467M/Great_Irish_Stories_of_Childhood
- ✅ books without table of contents can be edited/saved
- ✅ books with "normal" table of contents can …
=> Refactor/move TOC parsing/rendering code

openlibrary/core/vendors.py, openlibrary/tests/core/test_vendors.py
Closes #9879 
Prevents dvds from being imported from the Amazon API. They were previously being imported as books.
If Product_group OR Physical_format match 'dvd' it will not be imported.
unit tests included in tests_vendors.py 
@scottbarnes
=> reject Amazon dvd imports

openlibrary/accounts/model.py, openlibrary/core/bookshelves_events.py, openlibrary/core/processors/invalidation.py, openlibrary/core/yearly_reading_goals.py, openlibrary/mocks/mock_infobase.py, openlibrary/plugins/openlibrary/status.py, openlibrary/solr/updater/work.py, openlibrary/tests/core/test_processors_invalidation.py
DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
These warnings were appearing ~4000 times in test results, `datetime.utcnow()` is deprecated in Python 3.12
For some background: https://blog.miguelgrinberg.com/post/it-s-time-for-a-change-datetime-utcnow-is-now-deprecated
This fixes the warnings caused by code in this repo. I _think_ it doesn't introduce any new problems, but `utcnow()` was used in a range of places, having others review these changes would be helpful, in case there is a subtle impact from format changes I have missed.
**BEFORE:**
2162 passed, 9 skipped, 9 xfailed, 4891 warnings in 6.21s 
**AFTER:**
2162 passed, 9 …
=> Remove deprecated naive datetime warnings

openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/js/signup.js, openlibrary/templates/account/create.html
Closes #9603.
Feature. Reorganizes registration validation js to add a loading indicator at the correct point in the validation process and remove the delay between submission and validation.
Fairly simple! Involved moving the recaptcha info to a div with `data-size="invisible"` per the [recaptcha docs](https://developers.google.com/recaptcha/docs/invisible#programmatic_execute) and adjusting the order of the JS checks.
The original `grecaptcha.execute()` implementation was nested in a click handler rather than a submit handler, as the latter never actually fired, but I'm hoping that now that the recaptcha is no longer linked directly to the submit button a submit handler should work just fine.
1. Go to `/account/create`
2. Enter badly formatted and/or incomplete data and hit submit …
=> Reorganize JS for registration form and add loading indicator

openlibrary/plugins/openlibrary/js/bulk-tagger/BulkTagger.js, static/css/components/tagging-menu.less
Removes unreferenced style rules and JavaScript from the bulk tagger code.
=> Remove unreferenced `BulkTagger` code

openlibrary/plugins/openlibrary/js/bulk-tagger/BulkTagger.js, openlibrary/plugins/openlibrary/js/bulk-tagger/BulkTagger/MenuOption.js, openlibrary/plugins/openlibrary/js/bulk-tagger/index.js, openlibrary/plugins/openlibrary/js/bulk-tagger/models/Tag.js, static/css/components/tagging-menu.less
Adds new `collection` type to the bulk tagger.
_After adding new collection tag named `some-collection-identifier`._
When changes are submitted, the `collection` tags are added to the form, with the `collectionID:` prefix, in the `subjects` array.  For example, if the changes in the above image were submitted, there would be a `collectionID:some-collection-identifier` label in the affected works' `subjects` field.
_New label with prefix is appended to the work's `subjects` list (__underlined in red, above__)._
1. Create a new `collection` tag with the bulk tagger.
2. Add the tag to a work by pressing the "Submit" button.
3. View the updated work's `subjects` field, and verify that the new collection is present.
4. Verify that the new label has the `collectionID:` prefix.
5. Remove the new …
=> Update bulk tagger for collections

scripts/copydocs.py
Closes #8680
Prints `copydocs` script errors to the console.
=> Log error on `copydocs` failure

openlibrary/macros/StarRatingsStats.html
This is the result of investigating why we have so many docker errors -- followup to and re Closes #2405 
**Please squash :)** 
In certain cases where there were no star ratings, we were falling back to None and trying to format a None value as a string. This performs a `.get` with a fallback to empty string.
```
>>> stats_by_bookshelf = {}
>>> stats_by_bookshelf.get('want-to-read') and "{:,}".format(stats_by_bookshelf['want-to-read'])
>>> 
>>> stats_by_bookshelf = {'want-to-read': 1000}
>>> stats_by_bookshelf.get('want-to-read') and "{:,}".format(stats_by_bookshelf['want-to-read'])
>>> '1,000'
```
=> hotfix search star ratings null case

openlibrary/i18n/messages.pot, openlibrary/macros/TableOfContents.html, openlibrary/plugins/upstream/table_of_contents.py, openlibrary/plugins/upstream/tests/test_table_of_contents.py, openlibrary/templates/books/edit/edition.html, static/css/components/ol-message.less, static/css/page-user.less
Part of #8756
Adds the new fields to a new column in the markdown as JSON. This isn't a _great_ UI, but, more importantly, it makes it so that the extra fields aren't erased when someone edits an openlibrary record with authors/etc already in the TOC field.
~Depends on #9910 .~
- Add an `ol-message` CSS component for small messages; inspired by https://primevue.org/message/
- Add space indenting to table of contents editor for easier legilibity
- ✅ books without table of contents render correctly
- https://testing.openlibrary.org/books/OL10324632M/STOWELL_SYSTEMS_SCIENCE
- ✅ books with "normal" table of contents render correctly
- https://testing.openlibrary.org/works/OL27482W/The_Hobbit?edition=key%3A/books/OL27289715M
- ✅ books with "normal" table of contents don't show warning
- ✅ …
=> Add ability to sort of edit TOCs with authors/etc

openlibrary/templates/barcodescanner.html
Hotfix for #9873
Removes reference to deleted barcode scanner styles, fixing the barcode scanner page.
1. Navigate to the `/barcodescanner` page, and ensure that there is no `Unable to render this page` message.
=> Restore barcode scanner page

scripts/apply_offline_mode.sh
Creates script that, when executed, applies the [`offline-mode`](https://github.com/internetarchive/openlibrary/tree/offline-mode) branch's changes to the branch that is currently checked out.
To apply these changes locally, do the following:
1. Ensure that you are on the correct branch.
2. Run `docker compose exec -uroot web ./scripts/apply_offline_mode.sh`
The script will then download and apply the changes to your current branch.  To undo these changes, add a `--reverse` flag to the command:
`docker compose exec -uroot web ./scripts/apply_offline_mode.sh --reverse`
=> Add script for applying the `offline-mode` to the current branch

openlibrary/core/lending.py
Wraps ground_truth_api call to prevent errors if archive.org is down.
=> fix ground_truth WAF fallback

openlibrary/core/models.py, openlibrary/i18n/messages.pot, openlibrary/macros/AffiliateLinks.html, openlibrary/templates/covers/add.html
Disables prices rendering, wikidata fetching (which can cause timeouts), and cover add by url.
These requests were hanging around, timing out after like 30s, causing our haproxy's queue to fill up and resulting in a lot of 500s. Disabling them for now. Patch deployed this ~a week ago; not only this chunk, not the covers UI change has been patch deployed.
Also disabling the covers upload by URL UI, since it won't work for the time being.
@mekarpeles
=> Temporarily disable erroring network requests

openlibrary/templates/login.html
Since WAF or lack of http proxy to phone google is likely preventing google oauth, disable for now. Should open a new issue re: fixing recaptcha + oaugh XXX
=> temporarily disable google signin w/ info banner

openlibrary/components/BulkSearch/utils/classes.js
This PR adds the 'beta' tag to the Bulk Search AI selector. It's an extremely minor change, that should not have any effects on functionality or the rest of the codebase. 
Six characters were added within a string. 
Simply run up the local instance, head to '/search/bulk', and check to see that AI Extractor has been renamed to AI Extractor (Beta).
@cdrini
=> Added 'beta' tag to Bulk Search AI Extractor'

openlibrary/core/lending.py
Categorically fixes `IA_Lending_API` issue where Open Library breaks when `archive.org/services/openlibrary.php` not reachable
Was discovered when trying to hit https://openlibrary.org/account/loans. Because `archive.org/services/openlibrary.php` is currently blocked by mod_security WAF, the API was hitting non-json 403 response and dying.
Thie code path here was: `get_waitinglist_for_user` in `/openlibrary/openlibrary/core/waitinglist.py` which died while trying to call `waitlist.extend(WaitingLoan.query(userid=account.itemname))`. The `WaitingLoan.query` uses `core.lending.IA_Lending_API` which has a `_post` method https://github.com/internetarchive/openlibrary/compare/master...php-graceful-failure?quick_pull=1#diff-896c18b3ccfadfa425c7e24a86226343314fce7957d14a8023d3e159156b224bL1092 …
=> fail calls to openlibrary.php gracefully

openlibrary/book_providers.py
Closes #9064 
fixes the cover image visiblity on the authors page
In the `book_providers.py`, combining  the conditional statements `ed_or_solr['key'].startswith('/books/')` and `ed_or_solr.get('cover_i')` makes sure that if either of them fails, code continues to next `elif` block instead of returning `None` 
- Run the docker image with terminal using the command `docker compose exec web bash`
- load the book and author data using `PYTHONPATH=. python ./scripts/copydocs.py /books/OL45606286M /authors/OL12180252A`
- to see other book covers, change the covers url in `openlibrary.yml`
@scottbarnes
=> fix cover image loading on author page

static/css/components/header-bar.less
Shift padding from li wrapper to button element to increase clickable area of buttons in header browse menu.
Closes #9971 
Fixes an issue where some vertical space on button in the header Browse dropdown menu was unclickable.
Shifted padding from `li` wrapper to `a` inner element in `header-bar.less`
- Open the Browse menu on any screen
- Confirm that, for each button, the top and bottom 5px are now clickable (excluding the border)
Image shows the new boundaries of the `a` clickable element in the browse menu:
=> Fix Browse Menu Padding

conf/openlibrary.yml, openlibrary/plugins/openlibrary/code.py, openlibrary/templates/admin/people/view.html, openlibrary/templates/type/list/edit.html
Closes https://github.com/internetarchive/olsystem/issues/223
Also has parts:
- https://github.com/internetarchive/infogami/pull/224
- https://github.com/internetarchive/olsystem/pull/239
We have a `features` section in our openlibrary.yml, which has a `debug` feature which specifies the query parameter / value. But this was never being read from, and instead the literal value `true` was used. This lets the configuration work correctly so we can control the parameter from the openlibrary.yml file.
Note: This requires the infogami changes to be merged in first! Locally you can test this with the docker compose infogami local file.
Tested:
Add to openlibrary.yml:
```yaml
features:
debug:
filter: queryparam
name: debug
value: "true"  # Note the quotes are important! Otherwise it'll never …
```
=> Make debug=true use the features config in openlibrary.yml

renovate.json
Closes #9173 
Makes it so all our test requirements auto update.
This is very low risk because they're only test requirements and all but `debugpy` are used in CI so shouldn't break unexpectedly.
@scottbarnes @cdrini
=> renovate to auto merge requirements_test.txt

renovate.json
Reverts #10024 .
I think the `-r requirements.txt` in our `requirements_test.txt` is causing everything to be included! Eg this auto-merge enabled simplejson update, which shouldn't be auto-merge enabled.
=> Revert renovate.json changes -- causing too much auto-merging

docker/nginx.conf, docker/web_nginx.conf
Closes #10022 
Adds some rules that were uncommitted and probably useful. Also reorders some rules on the theory that matters.
Ensure the website still loads.
With these rules in place
@cdrini
=> Help slow down bots hitting /authors

openlibrary/plugins/openlibrary/js/my-books/CreateListForm.js
Closes #[9701](https://github.com/internetarchive/openlibrary/issues/9701)
Fixes the issue where lists created on search page initially appear checked in every dropper
- Minor changes made where `isActive` and `coverUrl's` order are swapped in `updateDroppersOnListCreation` to match `onListCreationSuccess(listKey, listTitle, isActive, coverUrl)`
- Go to the /search page, and ensure that there are multiple search results.
- Using the "My Books" dropper found in the first search result, create a new list.
- Expected behavior: The new list appears in each dropper, but is only checked in the first dropper.
=> Swap order of isActive and coverUrl in updateDroppersOnListCreation.

openlibrary/i18n/messages.pot, openlibrary/templates/account/create.html, openlibrary/templates/login.html
Closes #10042
Removes error message and re-enables Google sign-in on login and new account registration pages.
While logged out:
1. Attempt to login with your Google account.
=> Re-enable Google sign-in

static/offline.html
Closes #
I noticed the offline page always reflows when you refresh because the image height isn't fixed.
Set the image height to be fixed.
No visual changes.
=> set fixed image height for offline page

openlibrary/plugins/openlibrary/config/author/identifiers.yml
Closes https://github.com/internetarchive/openlibrary/issues/8037
feature
Using “Integrated Authority File” rather than the “Universal” from the ticket, since “Integrated” is [the translation the DNB themselves use](https://www.dnb.de/EN/Professionell/Standardisierung/GND/gnd_node.html).
DNB editions generally use DNB identifiers, which seem to be different from GND ones, so no need to add those for Editions; but GND is used for Works too, so this should also be added for them when we get those into code.
Note that there are still some potential Authors that are still using DNB identifiers, but the DNB’s plan is to transition all persons, organisations, etc. to use GND ids, so not adding DNB ids here for now unless it turns out they’re actually needed/desired for something.
Corresponds to …
=> Add support for Integrated Authority File (GND) identifiers on Authors

openlibrary/plugins/openlibrary/code.py
Closes #10002
Adds ability to configure `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` environment variables via `conf/openlibrary.yml` entries.
New configuration entry `http_proxy` is a string URL for an HTTP proxy.  If included in the configuration file, the `HTTPS_PROXY` and `HTTP_PROXY` environment variables will be set with this value.
The new `no_proxy_addresses` configuration is a list of addresses that should not be passed through the proxy.  If this configuration is present, the addresses will be combined in a comma-separated string and used to set the `NO_PROXY` environment variable.
https://github.com/internetarchive/openlibrary/labels/Needs%3A%20Special%20Deploy label added because new configuration entry is required.
=> Use proxy for external requests

openlibrary/core/vendors.py
Follow up to #3450
Removes `BETTERWORLDBOOKS_BASE_URL`, which is no longer referenced in the project, from `vendors.py`.
=> Remove unused variable

openlibrary/templates/search/authors.html, static/css/legacy.less
Closes: #10050 
1. Removes the unnecessary blank space on the author search page.
2. Ensures the layout is consistent with the rest of the pages.
1. Adjusted HTML by removing a div tag to remove excess margins and padding on the author search page.
2. Reused existing layout styles where possible to maintain consistency and reduce redundancy.
3. Verified that the changes do not affect other pages or components.
1. Use the automatic testing.
2. Confirm that the blank space is removed and the layout matches the rest of the pages.
3. Cross-check for any visual inconsistencies on related pages.
https://github.com/user-attachments/assets/8ab9b24f-e36a-4407-97f2-1eff78bc4d9a
@RayBB
=> Remove the extra blank under the Author's search

static/offline.html
Related to #10034 
1. If the user's device comes online (they connect to wifi/data/etc) then we automatically reload the page
I think this minor change will lead to a great improvement in the experience for users with intermittent connections (such as being on a metro).
@cdrini what do you think about this.
=> improve offline page by autoloading

scripts/deployment/are_servers_in_sync.sh, scripts/deployment/deploy.sh, scripts/deployment/restart_servers.sh
=> Fix deployment scripts

scripts/gh_scripts/issue_comment_bot.py
Part of #10075
I keep getting this error in my mypy locally
```
scripts/gh_scripts/issue_comment_bot.py:251: error: Module has no attribute
"ECOMM"  [attr-defined]
sys.exit(errno.ECOMM)
```
The reason the ECOMM isn't supported on mac (darwin)
This is a problem because I'm trying to update the imports with isort for the whole script.
Chatgpt recommended changing it to EPIPE. I don't think it matters much but it does work.
@jimchamp @cdrini
=> fix the issue comment bot mypy bug

openlibrary/plugins/openlibrary/js/SearchBar.js
Closes #7916 
I have implemented the suggested behaviors from #7916 but would like to know if there are additional navigation features/more preferred navigation flows for this component. 
I wasn't entirely sure what the intended behavior should be when a user presses Tab while focused on the Form input field and left it as the default behavior.
Fix
Implements the suggested keyboard functionality by attaching jQuery ```.on``` event handlers to listen for ```ArrowUp, ArrowDown, Escape, Tab, and Shift + Tab``` keycodes. ```tabindex``` has been attached to each ```li``` element to allow users to navigate the search bar results with their keyboard.
Go to ```localhost:8080``` and use a search term that returns at least 3 titles. 
The expected behaviors are:
Form input <ArrowUp/ArrowDown> - Goes …
=> Attach keydown listeners to searchbar

scripts/affiliate_server.py
Closes #
Ensures that the `setup_requests()` call happens when our affiliate server starts.
`setup_requests()` was added by #10008.
=> Set up `requests` environment variables for affiliate server

openlibrary/plugins/openlibrary/config/author/identifiers.yml, openlibrary/plugins/openlibrary/config/edition/identifiers.yml
Project Runeberg is similar to Project Gutenberg, but focuses on Nordic and Scandinavian authors and literature.
These identifiers basically correspond to
https://www.wikidata.org/wiki/Property:P3154 and
https://www.wikidata.org/wiki/Property:P3155
in Wikidata.
Closes https://github.com/internetarchive/openlibrary/issues/9981
feature
Adds additional blocks to identifier YAML files. Doesn’t touch any (logic) code otherwise.
* Edit an author, verify that the Project Runeberg identifier is present in the identifier dropdown list.
* Edit an edition, verify that the Project Runeberg identifier is present in the identifier dropdown list.
=> Add Project Runeberg author+edition identifiers

openlibrary/i18n/fr/messages.po
The welcome invite to set a yearly goal was missing in french
=> Add missing translation for yearly goal

static/css/components/read-panel.less
Closes #10060 
i have added the fix with fresh code bases
@RayBB hey can you resign me the fix and add this i have made the changes as needed without any issues :)
=> fix overflowing waitlist text

openlibrary/plugins/openlibrary/js/SearchBar.js, tests/unit/js/SearchBar.test.js
- **clear search results on tab**
- **stop rerending on focus of input**
- **fixed tabbing when on search results + working test**
Closes #10103
Added some tests but see video for demo
https://github.com/user-attachments/assets/4458081b-d160-401a-ad4a-5aef0c6caac0
=> improve searchbar keyboard input

openlibrary/plugins/openlibrary/js/team.js
Closes #10097 
Hey @jimchamp i have made the changes in innerHTML with textContent for security reasons as you mentioned. 
changes in the `team.js` file to increase the security.
no build errors and no other syntactical errors. all changes are preferable as per the documentations
=> changed the innerHTML with textContent for security reasons

openlibrary/plugins/openlibrary/js/edit.js, openlibrary/plugins/openlibrary/js/index.js
Closes #10126
Closes #10125
Since this was removed in #10032 , this is triggering an error which is causing issues for downstream JS
- Autocomplete appears for work, language on book edit page
- Can remove classification rows
=> Remove no longer needed identifier jquery repeat

openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/js/check-ins/index.js, openlibrary/templates/account/mybooks.html, openlibrary/templates/account/reading_log.html, openlibrary/templates/account/sidebar.html, openlibrary/templates/account/view.html, openlibrary/templates/check_ins/reading_goal_form.html, openlibrary/templates/check_ins/reading_goal_progress.html, static/css/components/check-in.less
Closes #10011  
Design
Moves the Yearly Reading Goal bar from the My Books and Reading Log pages into the sidebar, removes modal/alert banner from the My Books page, add Learn More redirect into the `reading_goal_form` modal.
1. Log in as a OL user and navigate to the My Books/Reading Log page.
2. If the account does not have a reading goal, `Set 2024 reading goal` should be shown underneath the Reading Goal section header.
3. Click on `Set 2024 reading goal` and input a valid reading goal value (1 - 10000). The reading goal progress bar and details should be visible.
4. Mark books within the OL catalogue as already read within 2024. Refresh the page to see the progress bar and reading goal details update.
5. Click on `Edit` and set the reading goal to 0, the reading goal progress bar and …
=> Move Yearly Reading Goal to sidebar

openlibrary/components/MergeUI/AuthorRoleTable.vue, openlibrary/components/MergeUI/MergeTable.vue, openlibrary/components/MergeUI/utils.js
Closes #9811 
Displaying the author’s name next to the OL...A identifier making it easier to distinguish between works by different authors.
**utils.js**
Added ```get_author_name``` function to fetch the name of the author associated with the id and append to the record. 
**AuthorRoleTable.vue**
Added p tag to display authors name, as well as class to formate with CSS.
**MergeTable.vue**
Created ```enhancedRecords``` to include author name and added to template in order to display. Added CSS to display name next to ID.
*** I've not added ```enhancedRecords``` to the ```merge``` function in this file as I couldn't verify if this would impact what is saved when merging works. Can someone please clarify?***
1. Run command  ```npm run serve --component=MergeUI```.
2. Open merge view …
=> Displays author name on merge

static/css/page-edit.less
Closes #10058 
This PR addresses a bug where the text area in the edit page was expected to be full width, but actually filled only half of it instead due to the conflicting textarea style defined in the component forms.olform.less.
This change increases the specificity of the textarea element in edit-pages.less by adding a class selector, ensuring that the text area for the edit page follows the style from page-edit.less.
1. Login & go to your profile page by clicking the hamburger icon and selecting "My Profile"
2. Click Edit
3. Scroll to Description section. Expect for the text area to take 100% width as shown in the screenshot.
Before:
After:
@RayBB
=> Make textarea on edit pages full width

.github/workflows/olbase.yaml
Add option to create olbase image with non-latest (ie master) tag for testing. Needed for testing the nginx changes in #10149
=> Allow publishing docker images from non-master branches for testing

openlibrary/macros/LocateButton.html
Closes #10144 
Makes the locate button open worldcat in a new tab
Added `target=_blank` to `macros/LocateButton.html`
1. Navigate to a Locate cta button
2. Ensure that clicking on it opens a worldcat link in a new tab
@mekarpeles
=> Make locate button open worldcat in new tab

openlibrary/catalog/utils/__init__.py, openlibrary/tests/catalog/test_utils.py
Closes #10128
Adds 'CreateSpace Independent Publishing Platform' to the list of independent publishers that should not be imported.
Besides rectifying the issue, I also Implemented tests and added casefold to the independent publisher list to prevent case errors in future updates.
Tests have been updated to include the new case.
@seabelis 
@scottbarnes 
@mekarpeles
=> Adding 'CreateSpace Independent Publishing Platform' to the list of independent publishers that should not be imported.

openlibrary/macros/Pager.html
Precedes #9742
Add analytics to the pager portion of the author search page prior to [redesign](https://github.com/internetarchive/openlibrary/issues/9742#issuecomment-2542166838). If the naming isn't quite right please let me know. I set the intermediate page links to their page numbers.
@RayBB
=> Add analytics to pager navigation buttons

openlibrary/plugins/upstream/forms.py
Ensures that we are only invalidating emails from `dispostable.com`. Without this change, emails from domains like `totally-not-dispostable.com` would be blocked.
In the long run, it may be nice if this validation compared against a list of disposable email domains (including the ones set in our admin console).
=> Update disposable email check

openlibrary/plugins/upstream/account.py
Ensures that we avoid redirecting to something like `not-really-openlibrary.org` on login.
=> Improve `refer` checks for `/account/login`

openlibrary/accounts/model.py, openlibrary/i18n/messages.pot, openlibrary/plugins/upstream/account.py
Addresses #10035
Adds new `request_timeout` authentication error message.  Updates `xauthn` to throw an error iff the authentication service returns a `504` during a `create` operation.
_The new error message._
=> Fail gracefully on account creation timeout

openlibrary/book_providers.py, openlibrary/i18n/messages.pot, openlibrary/macros/RawQueryCarousel.html, openlibrary/plugins/worksearch/code.py, openlibrary/plugins/worksearch/schemes/works.py, openlibrary/plugins/worksearch/tests/test_worksearch.py, openlibrary/templates/book_providers/runeberg_download_options.html, openlibrary/templates/book_providers/runeberg_read_button.html
Closes https://github.com/internetarchive/openlibrary/issues/9983
feature
**NOTE:** This depends on https://github.com/internetarchive/openlibrary/issues/9981 and as such builds on top of https://github.com/internetarchive/openlibrary/pull/9982 – hence the commit from there is in included in this PR currently. https://github.com/internetarchive/openlibrary/pull/9982 is a lot simpler than this PR though, so hopefully that will get merged before this one and this can be rebased on top of the main branch before getting undrafted.
This is mostly copy/pasting of existing support for Project Gutenberg, with a `s/[gG]utenberg/[rR]uneberg/` replacement, but some things have had additional adjustment (like the `download_options` HTML page).
=> Add Project Runeberg as a trusted book provider

scripts/expire_accounts.py
I noticed some deprecation warnings for `datetime.datetime.utcnow()` while looking through our logs today.  This PR updates the deprecated method, and makes the `expiry_date` object timezone-aware.
=> Update deprecated method in `expire_accounts.py`

openlibrary/plugins/inside/code.py, openlibrary/plugins/openlibrary/code.py
Closes # 10051
This PR achives reduction in time taken to show no results by about 0.5-0.8 s
- The modification is done in the openlibrary\plugins\openlibrary\code.py
- Added caching for search suggestion responses using `Cache-Control` header
- Set cache duration to 5 minutes (max-age=300)
1. Open browser developer tools (F12)
2. Go to Network tab
3. Perform a search query
4. Verify response headers:
- Should see `Cache-Control: public, max-age=300`
5. Changing the subsection of search
- Response should be served from browser cache
- The rendering of loading bar is not there while switching to different subsections (like Authors, Lists etc.)
I have worked on this issue with @jimchamp as lead.
=> Cache fulltext search results

.pre-commit-config.yaml
Fixes #10181 
@mekarpeles mentioned that our pre-commit hook for ruff isn't fixing stuff like it should.
So this will turn that on.
Following the example in https://github.com/astral-sh/ruff-pre-commit
=> enable fix flag for ruff precommit

scripts/manage-imports.py
Needed for #10187 
https://docs.astral.sh/ruff/rules/dict-get-with-none-default/#dict-get-with-none-default-sim910
Ruff suggests not setting none when doing a get as it's already the default.
=> fix ruff SIM910 by fixing kwargs get

docker/Dockerfile.oldev
Jenkins rebuilds the oldev image when pip dependencies change, so it needs to be able to set the nexus URL for package repos in the build.
=> Fix Jenkins oldev build

openlibrary/plugins/openlibrary/js/add-book.js
Closes #10148 - "Added Book IDs on new books aren't set"
Fix: This PR ensures that the "Internet Archive ID" field in the "Add Book" dialog is correctly persisted across different stages for regular users. 
->Fixed the issue where the "Internet Archive ID" field would not retain its value for regular users after switching steps in the "Add Book" form.
->Ensured that the value entered in the "Internet Archive ID" field is preserved when moving between steps in both admin and user portals.
Tested locally by logging in as both an admin and a regular user.
I have worked on this issue with @scottbarnes as lead
=> Fixed: Persist Book IDs Across Add Book Dialogs for Regular Users

openlibrary/i18n/messages.pot, openlibrary/plugins/admin/code.py, openlibrary/templates/admin/people/view.html
Closes #10201
Fix: Removed the legacy feature that allowed sending password reset emails from the pre-2017 system
->Removed the "send password reset email" button from the admin panel
->Deleted the corresponding backend function to ensure no unintended calls to this feature.
->Navigate to /admin/people/{username} and verify that the "send password reset email" button is no longer present.
What I Changed :-
@mekarpeles
=> Fix: Removed old password reset email feature from admin panel

openlibrary/i18n/messages.pot, openlibrary/templates/type/edition/view.html
Closes #10214
Adding a simple conditional to link to the correct section and have the right description.
Work: http://localhost:8080/works/OL54120W/The_wit_wisdom_of_Mark_Twain
Edition: http://localhost:8080/books/OL2058361M/The_wit_wisdom_of_Mark_Twain
Try clicking the edit buttons. Works well now.
@cdrini
=> fix edition description wording

openlibrary/catalog/add_book/__init__.py, openlibrary/plugins/importapi/import_validator.py, openlibrary/plugins/importapi/tests/test_import_validator.py
Closes #9440
Adds more tests to the import validator _and_ remove `publishers` as a required field for a complete record.
How is this looking for a first attempt? 
Ideally this makes the requirements more explicit. It is important to note this also removes `publishers` as required field for a complete record, to hopefully hew more closely to #9440.
Run the tests.
@hornc
=> Add more tests for import validator

openlibrary/plugins/openlibrary/js/editions-table/index.js, static/css/legacy-datatables.less
Closes #10210 
Fix: Hides the pager when there is only one page in the `legacy-datatables` UI. This prevents unnecessary pagination buttons that serve no purpose for users.
1. Navigate to any book and go to the "View Editions" tab.
2. If the allowed entries exceed the available data (e.g., only 8 entries), verify that the pager is hidden.
3. If the dataset exceeds the allowed entries, verify that the pager is displayed as expected.
**Pager Hidden (Single Page):**  
The pager is hidden because the allowed entries are more than the actual dataset (8 entries).  
**Pager Visible (Multiple Pages):**  
The pager is shown when the dataset exceeds the allowed entries.  
@RayBB
=> Fix(#10210):  Hide pager when there is only one page (#10210)

openlibrary/plugins/upstream/merge_authors.py
Addresses #10131
Part of the problem with completed author merges being stuck in the merge queue is that there's no way to remove these entries once they appear. I noticed that the problem entries were all using the deprecated /authors/merge?key=A001&key=A002&mrid=1 format. 
The code in merge_authors that redirects to the preferred /authors/merge?records=A001,A002 doesn't preserve the mrid parameter, which takes the merge out of the merge queue context so that the Reject Merge button isn't available to close the request.
This change preserves the mrid parameter in the redirect and maintains the merge queue context.
With this change in place, review one of the stuck author merges in the queue. The Reject Merge button should now appear and allow you to close the request.
@jimchamp
=> Preserve mrid when deprecated keys are passed in merge_authors

compose.override.yaml, openlibrary/i18n/messages.pot
Updates docker compose file to use a named volume for the postgres db service. Prevents test data being reset every time 
Ensure that the db container mounts to named volume after running docker compose instead of creating a new anonymous volume every time.
@mekarpeles
=> Update db service to use named volume

compose.production.yaml
Closes #10239 
Apparently node's fetch module does not respect the HTTP_PROXY environment variable -_- so getting that working is tricky. Disabling for now since the new security changes mean these requests fail, preventing solr restarter from working.
Even with changes to pass the HTTP_PROXY foreward, the Dockerfile that powers the solr-restarted can no longer build because it uses alpine `apk` commands, which isn't allowed through nexus.
=> Fix solr-restarter erroring/not working

openlibrary/core/admin.py, openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/home.py, openlibrary/plugins/openlibrary/js/graphs/plot.js
Closes #10118 
Fix
Checks if the current running instance is a dev environment using ```web.ctx.features``` and utilizes mock data to display the charts on the front page. Minor CSS styling issue fix for chart labels. 
1. Run ```docker compose up -d```
2. Open your browser's developer tools and select the Network tab before navigating to localhost:8080
3. Check how long it takes for the homepage to completely load
-   My local instance loading time dropped from roughly ~22 seconds to ~2 seconds, timings for other machines and browsers will most likely vary
Before
--- 
After
---
@jimchamp @RayBB
=> Use mock data for homepage charts to reduce startup loading time

conf/openlibrary.yml, openlibrary/utils/sentry.py
Closes #10270
Following https://docs.sentry.io/platforms/python/profiling/
Contributes to figure out the current performance issues.
Set the profiling rate to to 0.001 kinda arbitrarily thinking we don't really need that many.
@cdrini maybe you can throw this on testing and see if it does anything?
=> enable profiling in sentry

static/css/components/home.less
Closes #7848
Fix
Increases the text spacing between the header and subtitle text within the Onboarding carousel cards.
Changes the text color from grey hsl (330, 3%, 62%) to black hsl (0, 0%, 20%) to increase the contrast ratio
Navigate to localhost:8080 and use a web accessibility tool to verify that the contrast ratio should pass the WCAG 2.1 AA/AAA guidelines. 
Before
After
@mekarpeles
=> Implement accessibilty suggestions for Onboarding carousel

scripts/partner_batch_imports.py
Sets up `requests` to use a proxy before fetching the schema definition.
=> Set up `requests` for partner imports

.github/workflows/olbase.yaml
Closes #10255
Not sure why this seems to have fixed it... Had two successive olbase successfully push to docker hub :/
=> Fix deploys: Only have one docker/build-push-action block in olbase yml

openlibrary/components/IdentifiersInput.vue
Closes #10274
Allows the same ID of different types to be entered on the edition edit page.
All ID values were being checked previously. Now, only the ID values of the matching type will be checked.
- Navigate to edition edit page for any edition
- Add an ID of any type (ex. OCAID)
- Add the same ID under a different type (ex. LibriVox)
- Verify that the ID is added and no error is displayed
- Duplicate IDs for the same ID type should still be invalid
@seabelis
=> Fix duplicate IDs of different types not being accepted on edition edit page

openlibrary/plugins/openlibrary/js/readmore.js
---
This PR addresses an issue where the "Read more" button was displayed even when it extended the section beyond its fully expanded content. This led to a confusing user experience, as the "Read more" button was not serving its intended purpose. The following changes have been made to resolve this issue:
**Closes #9329**
1. **Capture "Read More" Button Height**:
- The height of the "Read more" button is now captured during initialization to ensure accurate layout calculations.
2. **Updated Condition in `reset` Method**:
- The logic determining whether the "Read more" button should be displayed has been updated to account for the button's height. This ensures the button is only shown when necessary.
- **Improved User Experience**: The "Read more" button is now displayed only when needed, …
=> Fixed Read More Button Display Logic to Avoid Unnecessary Display

compose.production.yaml
removing deleted /opt/olsystem/etc/cron-jobs.env removed in https://github.com/internetarchive/olsystem/pull/247/files
Related to #10065
=> Fix compose.production.yaml rm cron-jobs.env

static/css/components/carousel--js.less, static/css/components/cbox.less, static/css/lib/slick-theme.css
Closes #10134 
Align/Fix the navigation arrows, positioning them on the sides of the covers for better usability.
1) Go to the add-cover section of a book (eg. https://openlibrary.org/works/OL69166W/Italian_journeys/add-cover)
**Before:**
**After:**
@mekarpeles
=> Fixed arrow alignment in covers modal

static/css/components/buttonCta.less
Closes https://github.com/internetarchive/openlibrary/issues/8899
Fix: Fixes issue with the text overlapping in mobile
Changed css as directed in https://github.com/internetarchive/openlibrary/pull/9066, this seems to work to resize the text so that there is no issue with the overlap with the icon. 
docker compose up
// For running site
docker compose exec -e PYTHONPATH=. web bash -c "./scripts/copydocs.py --search 'author_key:OL9411725A' --search-limit 100"
// Adding data
http://localhost:8080/works/OL36891831W/
Start changing screen width
@cdrini
@RayBB
=> Changed CSS so that the audiobook text does not overlap with the icon

openlibrary/components/IdentifiersInput.vue, openlibrary/components/IdentifiersInput/utils/utils.js, openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/config/work/identifiers.yml, openlibrary/plugins/upstream/addbook.py, openlibrary/plugins/upstream/models.py, openlibrary/plugins/upstream/utils.py, openlibrary/templates/books/edit.html, openlibrary/templates/books/edit/edition.html, openlibrary/templates/merge/authors.html, openlibrary/templates/type/author/edit.html, openlibrary/templates/type/author/view.html
Closes #3430
Feature
DRY implementation of work identifiers but currently unable to save the changes made by users into Solr. 
The work identifiers currently displayed in this component are based off of this list: https://openlibrary.org/config/work
1. Navigate to a work/book and click on the edit button
2. Switch from the edition edit tab to the `Work Details` edit tab
3. Scroll to Work Identifiers section and add/remove work identifiers.
- ~~Duplicates are currently not allowed for work identifiers. Adding a duplicate will warn the user that an identifier already exists.~~
- ~~Work Identifiers should be saved as a list, allowing more than one ID per identifier. Duplicate ID numbers across different identifiers is not allowed i.e BookBrainz ID:123456 vs Amazon ID:123456.~~
4. After …
=> Use IdentifiersInput Vue component for work identifier UI

openlibrary/plugins/upstream/merge_authors.py
Closes #10131
Attempts to prevent hanging author merges by adding retry logic to the request status update.  This, plus @mheiman's improvement, #10237, should prevent this from being a problem any further.
The records involved in the merge are first updated and saved to the db. After, the merge request is updated with a new status reflecting the completed operation. Hanging merge requests were being created since the records could be merged and saved with the status update failing. Adding retries to the status update will hopefully give the record a better chance to be updated properly.
I separated the merge and status update apart into their own separate methods and added the existing [RetryStrategy](https://github.com/internetarchive/openlibrary/blob/dbd4d759adcb63c5b4f91f037264a63e24fe4 …
=> Add retry logic to author merge request status update

openlibrary/components/LibraryExplorer.vue, openlibrary/components/LibraryExplorer/components/BookCover3D.vue, openlibrary/components/LibraryExplorer/components/BooksCarousel.vue, openlibrary/components/LibraryExplorer/components/Bookshelf.vue, openlibrary/components/LibraryExplorer/components/ClassSlider.vue, openlibrary/components/LibraryExplorer/components/LibraryToolbar.vue, openlibrary/components/LibraryExplorer/components/Shelf.vue, openlibrary/components/ObservationForm.vue, openlibrary/components/ObservationForm/components/CardBody.vue, openlibrary/components/ObservationForm/components/SavedTags.vue, openlibrary/components/ObservationForm/components/ValueCard.vue
Implements part of #7547
This PR adds explicit `.vue` file extensions to component imports to ensure compatibility with Vite's module resolution requirements (see [Vite issue #178](https://github.com/vitejs/vite/issues/178)). While webpack is more lenient with extension resolution, Vite strictly requires these extensions.
This change is a prerequisite for the Vue 3 migration (#10298) and has been implemented incrementally to maintain code clarity. Similar changes have been previously made in other parts of the codebase (see [PR #10303](https://github.com/internetarchive/openlibrary/pull/10303/files#diff-8072cfd31b3fafb1534902ed7a78ca0a13e1d38ebaddf27efcd7b7b43003282aR97-R98)).
Type: refactor
- Adds explicit `.vue` extensions to all component imports
- No functional changes to component …
=> update vue import extensions to use .vue

openlibrary/core/vendors.py
Closes #10230
This commit allows BookWorm to use the HTTP proxy when fetching metadata from Amazon.
BookWorm relies on an Amazon API client that itself relies on `urllib3` which explicitly does not and will not support the HTTP_PROXY environment variable.
`urllib3` does support HTTP Proxies, but it needs a specific object, and the underlying code for the API does support all of this, but the library provides no way to pass the proxy value through to `urllib3`.
The workaround here is to create the `Configuration` object in the Amazon API client, add a proxy object after init, then use that to create a REST client, and then replace the original `api_client` object with this one, so that there is proxy support.
Note: if trying to create an `vendors.AmazonAPI` object in a REPL, one will need …
=> Support HTTP Proxy on BookWorm

scripts/dev-instance/dev_db.pg_dump
Closes #10295 
**Description:**
This PR adds the missing submitter column to the import_item table in the local development environment schema, ensuring compatibility with the production schema.
**Changes:**
Added submitter column to import_item table in `dev_db.pg_dump.`
**Testing:**
- Stopped the app, removed openlibrary_ol-postgres volume, and restarted.
- Verified http://localhost:8080/import/batch/pending loads without errors.
@jimchamp @RayBB
=> Include "Submitter" Column in Auto-Loaded Data for Local Environment

openlibrary/i18n/messages.pot, openlibrary/templates/account/privacy.html
Closes #10304
This PR addresses an issue with unclear wording on the privacy page. The previous text, "Public accounts can be seen and followed by others," implied that accounts could be hidden, which is incorrect.
=> Clarify Privacy Page Wording

openlibrary/plugins/upstream/mybooks.py
Uses correct variable `myloans` when counting patron's loans, rather than the uninitialized `loans` variable
Closes #10041 with @OutstandingWork 
What we know is that the problem occurs on the My Books page (e.g. https://openlibrary.org/people/mekBot/books) for a logged in patron.
When a patrons navigated to the My Books page, their request is matches and responded to by the mybooks plugin: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/mybooks.py#L43-L58
We see something strange going on in https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/mybooks.py#L62-L64 where we fetch `myloans` but then seemingly take the `len` of `loans` which is an empty list defined just above: …
=> Fix My Loans count for My Books #10041

openlibrary/plugins/upstream/code.py
Closes #10224 
fix
It simply changes the response returned for a authenticated user without the necessary clearance (admin, librarian or super-librarian) to see the /merge/works and adds a condition for responding to a request sent by unauthenticated users.
The PR affects two cases:
1. Attempt to access the http://localhost:8080/works/merge?records=OL15941796W,OL15400921W by logging into a user type that is not a super-librarian, librarian or admin. If a forbidden response is received, the PR works as expected.
2. Attempt to access the http://localhost:8080/works/merge?records=OL15941796W,OL15400921W without logging-in. If an "unauthorized" response is received, the PR works as expected.
Case 1 - Logged-in but not admin, librarian or super-librarian:
Case 2 - Not logged-in
@jimchamp
=> Added respective responses discerning between unauthorized (not logged-in) and forbidden responses.

openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/js/ile/utils/SelectionManager/SelectionManager.js
Closes #10246 
This fixes shift-clicking to select a range of editions in the ILE
I didn't dig deeply into the details, but it looks like a change to the HTML of the work page broke shift clicking for edition selection.
I resolved the problem by having the range selection algorithm search one more level up the DOM for the common parent of the clicked elements. I verified that this solves the problem and doesn't affect the behavior of shift-clicking other selectable types.
1. While logged in as a librarian, visit a work with multiple editions (e.g. https://openlibrary.org/works/OL63996W/The_Alhambra)
2. Click the first edition to select it.
3. Hold down the shift key and click an edition further down the page.
Expected behavior: All of the editions between the first and second clicks …
=> Increase search path for shift-click common parent

openlibrary/i18n/messages.pot, openlibrary/templates/type/edition/view.html
Closes #10302
1) Renamed "ID Numbers" to "Edition Identifiers"
2) Added a new section named "Work Identifiers" and also added "Work ID" as well
Visit any book page and scroll down to se "ID numbers"
@cdrini
=> Renamed Id numbers and added work identifiers with work id

openlibrary/plugins/worksearch/code.py
Reduce default response load for search.json
Patrons can still use `fields=*` to achieve the old results
Related to #7673 
Returns a `documentation_url` which ideally would return json but 🤷 
hit search.json and you should get less payload
=> Update search.json default fields to be more restrictive

openlibrary/core/lists/model.py
Closes #10322 
Fixes the `get_export_list()` for seeds that contain notes
The functionality and logic of the previous version and this PR remains the same. Using `_get_seed_details()` instead of `self.seeds`.
The export functionality now works as expected.
=> Fix seed retrieval to use seed strings from already defined fuctions 

openlibrary/plugins/openlibrary/home.py
Moves `("dev" in web.ctx.features)` check to a `devmode` function param so `web.ctx` is no longer needed within our cached function.
While the initial computer of the `get_homepage()` function works fine (because `web.ctx` is in scope) the `web.ctx` `ThreadedDict` may no longer be accessible once passed to a memcache thread for it's subsequent re-compute after timeout hit)
Closes #10318 
**Resolves** https://sentry.archive.org/organizations/ia-ux/issues/541018/?query=is%3Aunresolved+threadeddict&referrer=issue-stream&statsPeriod=14d
Addresses instance of #10341
See investigation here: https://github.com/internetarchive/openlibrary/issues/10318#issuecomment-2598903078
hotfix patch deploy should show a drop in errors on sentry and hopefully stats showing up again on prod.
@schu96 @cdrini …
=> Move web.ctx check outside of cached function #10318

openlibrary/catalog/add_book/__init__.py, openlibrary/catalog/add_book/load_book.py, openlibrary/catalog/add_book/tests/test_add_book.py, openlibrary/catalog/add_book/tests/test_load_book.py, openlibrary/catalog/utils/__init__.py, openlibrary/tests/catalog/test_utils.py
Closes #10141 Internet Archive imports often missing language 
**Fix**
Fixes language import issue by ensuring that language is correctly added to existing editions during import
**Technical**
Previously, the issue was that when importing an edition, the language field was not being correctly added to existing editions if it was missing, even if the import record contained a language.
To address this I added a helper function format_languages() to openlibrary/openlibrary/catalog/add_book/__init__.py,
to format the languages field, called by update_edition_with_rec_data() and build_query() in openlibrary/openlibrary/catalog/add_book/load_book.py, along with changes to both functions. 
**Testing**
Tested this issue locally and reproduced the bug by running the following commands (generate …
=> Language imports consistently on re-imports of books

docker/README.md
=> Update docker installation

openlibrary/catalog/add_book/__init__.py, openlibrary/catalog/add_book/tests/test_add_book.py, openlibrary/core/vendors.py, openlibrary/coverstore/code.py, openlibrary/plugins/openlibrary/code.py, openlibrary/plugins/upstream/utils.py, scripts/affiliate_server.py, scripts/partner_batch_imports.py
Closes #10230, #10316
Related: internetarchive/olsystem#253
This commit reenables `/isbn` on BookWorm and by extension openlibrary.org.
Note: this changes the signature of `vendors.AmazonAPI()` to add a `proxy_url` parameter for passing in an HTTP Proxy URL.
It will be passed by default when loaded by BookWorm, but if using `AmazonAPI()` in the REPL on `ol-home0`, then `proxy_url` will need to be passed when instantiating `AmazonAPI()`.
I checked 1000 `staged` items from Amazon and every one had the cover hosted at `m.media-amazon.com`. I had fewer Google Books items to check, but they _seem_ to all have covers coming from `books.google.com`.
The BookWorm/`/isbn` part of this was tested by visiting https://openlibrary.org/isbn/6610742898 with the relevant part of the code patch deployed …
=> BookWorm: allow imports via BookWorm again

conf/solr/haproxy.cfg
Researching w/ chatgpt, suggested to reduce queuing by increasing this number to ~200 and we choose 75 and monitored on sentry + grafana + cpu
Related to #7673
=> Increasing solr haproxy maxconn from 10 to 75

openlibrary/plugins/upstream/recentchanges.py
Small endpoint tweak to support gathering some tocky stats. `/recentchanges.json` supports the author field ([eg](https://openlibrary.org/recentchanges.json?author=/people/ScarTissue&limit=10)), but if you also specify the date prefix, eg `2025/01`, it will not support the author prefix. Extend the `/recentchanges/DATE` endpoint to also support the author parameter.
- https://testing.openlibrary.org/recentchanges/2025/01.json?limit=1000&offset=0&author=/people/ScarTissue now works!
=> Add support for author parameter to recentchanges/YEAR endpoint

Makefile, openlibrary/components/vite.config.mjs, openlibrary/plugins/upstream/utils.py, package-lock.json, package.json
Closes #10371
In short, this accomplishes two things:
1. Add support for legacy browsers (after ie 11)
2. Revamps the build process to be simpler
- This is only possible because we are moving away from one build of iife and to a modern build of es and a legacy build.
Here’s a clean and detailed before/after comparison table showcasing the file sizes and gzip sizes for each component:
| **Component**                       | **Before Size**   | **Before Gzip Size** | **After Size**    | **After Gzip Size** | **Size Reduction** | **Gzip Reduction** |
|-------------------------------------|-------------------|-----------------------|-------------------|----------------------|--------------------|--------------------|
| **ol-BarcodeScanner.js**            | 352.21 kB         | 120.60 kB …
=> vue 3 improve legacy builds

openlibrary/catalog/add_book/__init__.py
Needed for #10328
Fixes this issue detected by the ruff upgrade
That code was completely unused. I checked the git blame and it was added 14 years ago :)
=> fix unused else if for ruff upgrade

scripts/cron_wrapper.py
Addresses #10206
Adds a new script that will run a given script and arguments as a subprocess while adding additional monitoring:
1. Before the subprocess starts, a `statsd` `cron.{job_name}.start` count is incremented, and a `cron.{job_name}.duration` timer is started 
2. On subprocess error, the error is captured and sent to Sentry and a `cron.{job_name}.failure` count is incremented.  Also, the `cron.{job_name}.duration` timer is stopped and the duration is recorded.
3. On subprocess success, a `cron.{job_name}.stop` count is incremented and the `cron.{job_name}.duration` timer is stopped and the delta is recorded.
`job_name` is automatically set to be the wrapped script's name, with the file extension stripped off.
The subprocess's `STDOUT` and `STDERR` are forwarded to the wrapper …
=> Add `cron_wrapper` script to improve cron job monitoring

bundlesize.config.json, openlibrary/templates/site/alert.html, static/css/components/iaBar.less, static/css/components/page-banner.less
Closes #10063 
@mekarpeles check this out i have Fixed the AI toolbar overflow which gets warps on mobile as you have mentioned me to go ahead with where, `iabar-mobile` and create a mobile breakpoint where the `font-size` of these components becomes `.9em` and the padding of the `ghost-button` becomes padding: `5px 7px;` we get our desired effect on mobile.
=> FIxed IA toolbar overflows/wraps on mobile #10063

openlibrary/core/lending.py
Related to #10341
Seems to correct our most frequently logged [error](https://sentry.archive.org/organizations/ia-ux/issues/366884/events/?project=7&referrer=issue-stream&sort=freq&statsPeriod=14d) in Sentry.
Updates code such that `delegate.fakeload()` is called if `web.ctx.site` is not ready before a patron's waiting list is cached.
=> Ensure that context is loaded before caching waitlist

openlibrary/accounts/model.py, openlibrary/plugins/upstream/account.py, openlibrary/utils/sentry.py
Closes #10380
Logs `xauthn` response to Sentry whenever an `undefined_error` `OLAuthenticationError` is raised during account creation.
The `response` will be in the ["Additional Data"](https://sentry.archive.org/organizations/ia-ux/issues/541313/?environment=ol-dev&query=is%3Aunresolved&referrer=issue-stream#extra) section of such error logs. 
Due to a maximum of ten fields per error stack frame limit in Sentry, the `response` had to be added to the "Additional Details" section.
=> Expose account creation `xauthn` response to Sentry

static/robots.txt
Relates to #4485 
Decreases the rate we get crawled by bots by introducing a crawl delay
=> Add crawl delays to robots.txt

openlibrary/utils/ddc.py, openlibrary/utils/tests/test_ddc.py, pyproject.toml, scripts/detect_missing_i18n.py, scripts/tests/test_import_standard_ebooks.py, scripts/tests/test_isbndb.py
Part of #10196
https://docs.astral.sh/ruff/rules/ambiguous-unicode-character-string/
A nice rule that will prevent ambiguous characters from being committed by accident.
=> enable RUF001 - ambiguous-unicode-character-string

openlibrary/plugins/upstream/covers.py, openlibrary/templates/covers/add.html
Part of #7250
Turns out with PIL webp just works. No changes needed other than allowing the format.
Unfortunately, AVIF support just isn't there yet :/
https://github.com/python-pillow/Pillow/issues/7983 
Upload a cover that's webp, like: https://www.gstatic.com/webp/gallery/1.webp
@cdrini
=> add webp support to coverstore

openlibrary/templates/account/create.html
Removes extra double quote character from our account registration template.  This will fix some HTML validation errors on the `/account/create` page.
_Error present in Firefox's `view-source` view_
=> Fix malformed HTML in `/account/create` template

openlibrary/accounts/model.py, openlibrary/i18n/messages.pot, openlibrary/plugins/upstream/account.py, openlibrary/templates/account/create.html, openlibrary/templates/login.html
Closes #10035 
The errors in `get_login_error` need to be updated to include `bad_email`, `bad_password`
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/account.py#L64-L98
@jimchamp can you also investigate whether we may be able to add errors using the `add_flash_message` (some are currently hidden on the page) as per #10045 ?
=> Fix registration errors from xauthn

openlibrary/templates/lib/nav_head.html
Closes #10293 
This PR simply add librarians as a privileged user which allows them to see how many requests are pending to get merged so that they can have an eye on the merging work progress.
=> Added Librarian as privileged user

openlibrary/plugins/openlibrary/js/carousels_partials.js
Closes #10354
Implement lazy loading for Related Books Carousels to reduce unnecessary Solr API calls and improve page load performance.
- Used Intersection Observer API for viewport-based loading
- Added fallback mechanism for browsers without Intersection Observer support
- Modified `carousels_partials.js` to fetch carousel data only when visible
- Minimal changes to existing carousel initialization logic
1. Open book pages with Related Books Carousels
2. Verify carousels do not load immediately on page load
3. Scroll to trigger carousel loading
4. Check browser network tab for reduced initial API calls
5. Test anchor link navigation to carousels
6. Verify functionality in browsers with and without Intersection Observer
*No UI changes - performance optimization*
@RayBB @mekarpeles
Code …
=> perf(carousel): reduce Solr load via lazy loading Related Books Carousels (dev-mohit06)

scripts/cron_wrapper.py
While preparing to update our crontab, I found and corrected some errors in `cron_wrapper.py`:
1. A `_get_job_name` function was being passed an expected parameter
2. `cron_wrapper.py` was treating `--options` for wrapped scripts as if they applied to `cron_wrapper.py`
3. Script was missing a shebang
=> Fix `cron_wrapper.py` bugs

scripts/gh_scripts/issue_comment_bot.py
Updates the https://github.com/internetarchive/openlibrary/labels/Needs%3A%20Response labeler to include PRs.
The API that this script uses to fetch issues also returns PRs.  These changes remove the code that filtered out PRs from all fetched issues.
=> Add `Needs: Response` labels to PRs

scripts/deployment/deploy.sh
Closes #4382 faster parallel deploys
=> add tags, rm builder prune, background ssh

openlibrary/templates/book_providers/cita_press_download_options.html, openlibrary/templates/book_providers/gutenberg_download_options.html, openlibrary/templates/book_providers/ia_download_options.html, openlibrary/templates/book_providers/librivox_download_options.html, openlibrary/templates/book_providers/openstax_download_options.html, openlibrary/templates/book_providers/standard_ebooks_download_options.html, openlibrary/templates/book_providers/wikisource_download_options.html
Closes #9782 
Adds link tracks to all download options in sidebar so that we can have a baseline reading of patron activity. This reading will then be used to compare the effectiveness of the work-in-progress [Read dropdown redesign
](https://github.com/internetarchive/openlibrary/issues/5831). 
Click a download option and ensure that data for SideBar|Download is being recorded in stats. 
@cdrini @mekarpeles 
@SivanC -- just letting you know about this one for when you want to compare SideBar|Download with your eventual ReadDropper|Download feature.
=> Added link tracks to all download options

openlibrary/core/follows.py, openlibrary/macros/Follow.html, openlibrary/plugins/upstream/account.py, openlibrary/plugins/upstream/forms.py, openlibrary/templates/login.html
Closes #10338
This PR is a `feature`
Currently, the website does not allow users to follow a publisher if they are not logged in. After logging in, the user must manually return to the publisher's profile to follow them.
With this PR, the follow operation will be handled by the backend.
To test this, go to any user profile and try to follow them while logged out. You will be redirected to the login page, and after logging in, the backend will automatically complete the follow operation for you and display a flash message.
Before:
https://github.com/user-attachments/assets/ecbe24b8-719e-4091-a1b9-cf9aed49da9c
After:
https://github.com/user-attachments/assets/67138661-6a21-4660-8b6b-18965db6ed71
Already following: 
https://github.com/user-attachments/assets/d2a10ff7-ed7f-45b4-899f-cd2182b716 …
=> Add post login action - follow

openlibrary/plugins/upstream/borrow.py
Historically, we've only counted borrowing stats and not access to open materials.
One line improvement to track how often open access materials are read from Open Library.
=> add read stats in addition to borrows

openlibrary/templates/status.html
Excludes `debug` from features display.
Also fixes some indentation issues in the affected template.
=> exclude debug feature from status page

openlibrary/accounts/__init__.py, openlibrary/accounts/model.py, openlibrary/admin/numbers.py, openlibrary/catalog/add_book/__init__.py, openlibrary/code.py, openlibrary/core/ia.py, openlibrary/core/lending.py, openlibrary/core/models.py, openlibrary/core/stats.py, openlibrary/core/vendors.py, openlibrary/core/waitinglist.py, openlibrary/coverstore/code.py, openlibrary/coverstore/coverlib.py, openlibrary/coverstore/utils.py, openlibrary/plugins/openlibrary/stats.py
Part of #10196
Before embarking on a journey to fix (or ask people to open many PRs) all of the issues I decided to open a PR with some of the simple fixes. 
These were all suggested as "unsafe" fixes by ruff. They're unsafe because if the value was a tuple instead of a string then the f string behaves slightly differently. However, I've examined each of these examples pretty closely and don't see any cases where a tuple is likely to slip in.
https://docs.astral.sh/ruff/rules/printf-string-formatting/
I've clicked around on much of the site locally and didn't hit any errors but I didn't extensively check that all the code changed is triggered.
=> start UP031 by fixing simple %s strings

openlibrary/data/dump.py
Closes #9521
Reverts [recent changes](https://github.com/internetarchive/openlibrary/pull/10306
) to the `xopen` function, which were causing a closed file object to be returned in some cases.
=> Fix data dump script regression

.github/workflows/new_comment_digest.yml
Follow-up to #10411
Updates the `new_comment_digest` workflow such that it allows writing to PRs.  API calls that add the `Needs: Response` label to PRs will no longer fail once this is merged.
=> Permit `Needs: Response` labeling for PRs

openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/code.py, openlibrary/templates/internalerror.html
=> better internalerror page

openlibrary/data/dump.py
Related to #9521
Updates `dump.py` logging statements that are throwing `UnboundLocalError`s.  These `log` calls were each attempting to access a nonextant variable `i`.
For each of these cases, a new variable `total` was created at the appropriate scope.  `total` is incremented each time a record is processed, and replaces `i` in each failing logging statement.
=> Update data dump logging statements to avoid `UnboundLocalError`s

static/css/components/mybooks-menu.less
Fix; the underlines was a regression in a previous PR.
Before:
After (scrollbar appears on hover):
=> Make scrollbar thin on books page + fix link underlines regression

static/css/components/merge-request-table.less
Closes #10386
Fix
This PR addresses the issue by resolving The Clipping of heading title's in "Merge" Page
1. Pull this branch locally.
2. Start the development server using `make up`.
3. Navigate to [affected part of the app].
4. Verify that the bug described in #10386 no longer occurs.
=> Fixed The  Clipping of heading titles in 'merges' page

static/css/components/merge-request-table.less
Closes #10337
This PR aims to fix the buggy  UI on '/merges' page
Visit https://openlibrary.org/merges
Click on the icon and see the overlapping issue
Video of solution:
https://github.com/user-attachments/assets/2dc49fd3-bfd5-4f74-a966-ee4abce691ea
@jimchamp
=> fixed overlapping of logo in 'merges' page

.github/ISSUE_TEMPLATE/feature_request.yaml
Improvements, similar to #8894 
simple improvements
- merges proposal and justification sections
- puts justification and problem statement fist (hopefully, in a more logical order)
- adds Endpoints link next to related files
I wanted to add `relevant files` to the proposal section as I'd love if more contributors added files, though I felt ultimately it might make more sense at the top of `Breakdown`
On fork https://github.com/mekarpeles/openlibrary/issues/new?template=feature_request.yaml
=> merging proposal and justify sections of feature request template

openlibrary/plugins/upstream/account.py
Sets a default `email` input value for the account registration form.  This change may give us better insights into why [this type of error](https://sentry.archive.org/organizations/ia-ux/issues/96/?query=is%3Aunresolved+%2Faccount%2Fcreate&referrer=issue-stream&statsPeriod=14d&stream_index=0) is occurring.
=> Set default email value for account registration

openlibrary/utils/sentry.py
Closes #10381
This PR is a `fix`
Replaced the depreciated  `sentry_sdk.push_scope` with `sentry_sdk.new_scope` in [openlibrary/utils/sentry.py](openlibrary/utils/sentry.py) 
[I have replaced `sentry_sdk.push_scope` calls here](https://github.com/openlibrary/openlibrary/blob/a5d1648fb7b6bdd9fbfe44508fe84621ee17d7d5/openlibrary/utils/sentry.py#L85-L93)
Can view changed files to verify the changes.
No behavioural changes are expected as this is just updating to the new recommended Sentry SDK method.
@jimchamp @mekarpeles
=> replaced push_scope with new_scope in sentry.py

openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/js/SearchUtils.js, openlibrary/templates/work_search.html
relates to #9439
Closes #
It removes a non-functioning filter for a subject which no longer exists:
https://openlibrary.org/subjects/protected_daisy
It it unclear how this filter is supposed to work to display 'printdisabled' books, but the method of filtering by subject has not worked for some time. See #9439
Removing a UI element that does nothing to avoid clutter.
Before:
https://openlibrary.org/search?q=book&mode=printdisabled&has_fulltext=true&subject_facet=Protected+DAISY
After:
http://0.0.0.0:8080/search
=> Remove prominent but non-existent subject filter

scripts/deployment/deploy.sh
Feature; make the deploy script easier to use by (1) showing the `git diff` when there are changes on prod, and (2) offering the deploy-runner the option to ignore the changes in-line.
This also fixes a subtle bug, where you could add `IGNORE_CHANGES=1` after seeing errors on one node, but not realize that you're also blowing away changes on other nodes that haven't been displayed yet!
Tested on this latest deploy.
=> Add y/n for ignoring changes during deploy + show git diff

openlibrary/plugins/openlibrary/code.py, openlibrary/plugins/openlibrary/processors.py
Removes the `RequireLogoutProcessor`, which forces patrons to log out if they haven't logged in since some cutoff date.
This processor was originally added in #10005
=> Remove `RequireLogoutProcessor`

scripts/gh_scripts/weekly_status_report.mjs
Removes `is:issue` from links in the "Recent Comments" section of the weekly project management digest.  Once merged, clicking the `X issue(s) need response from lead` link will show both issues and PRs that need response.
=> Remove `is:issue` from links in "Recent Comments" section of weekly PM digests

openlibrary/core/helpers.py, openlibrary/macros/BookByline.html, openlibrary/tests/core/test_helpers.py
Closes #10352 
Fix: Display correct author dates when birth/death years contain non-numeric characters
-> Updated the `extract_year` method in `helpers.py` to handle non-numeric characters in birth/death dates.
-> Modified the `BookByline.html` template to ensure proper display of dates, even when non-numeric characters (e.g., "19xx") are present.
-> Added an optional `int_only` parameter to the `extract_year` method to avoid breaking changes in other parts of the codebase.
->  Verify that the author's dates are displayed correctly without empty brackets.
->  Run the test suite to ensure no regressions:
What I changed -:
@cdrini
=> Fix: Display correct author dates when birth/death years contain non-numeric characters

openlibrary/plugins/openlibrary/js/check-ins/index.js, openlibrary/templates/account/mybooks.html
Closes #10469
Makes the following changes to the `20XX Reading Goals` link in mobile "My Books" pages:
- Removes the `click` listener from the link whenever a reading goal is set
- Prevents the `click` listener from being added to the link when a goal is already set
The aforementioned `click` listener opens the "Yearly Reading Goal" modal, from which a patron can set a reading goal.
=> Disable mobile reading goal listener when goal is set

openlibrary/plugins/recaptcha/recaptcha.py
Closes #10474
Captures the `error-codes` field of any failing ReCaptcha verification in Sentry.
=> Log Recaptcha errors in Sentry

openlibrary/plugins/openlibrary/js/signup.js
=> Remove `grecaptcha` check when setting recaptcha submit callback

openlibrary/plugins/openlibrary/js/SearchBar.js
Closes #10359
fix
It changes the JS handler for displaying the autocomplete results.
1. Search for any keyword in the search bar.
2. Change the facet, if the autocomplete results for that facet are displayed, the PR works as expected.
<video src="https://github.com/user-attachments/assets/b011c860-4c7a-4fd5-b69d-b4baff22ab5d" width="320" height="240" controls></video>
@RayBB
=> Display autocomplete results on search facet change

openlibrary/plugins/recaptcha/recaptcha.py
Follow-up to #10476
Allows Open Library's ReCaptcha validations to pass whenever the verification call contains errors.
=> Pass ReCaptcha checks when verification calls fail

openlibrary/i18n/messages.pot, openlibrary/templates/merge_request_table/table_row.html
Closes #10333 
Separates "Review" translation for merge requests vs. book reviews in Spanish.
Added a unique string ID `$:_('Review ')` in `table_row.html`.
This allows translators to provide a separate translation (e.g., "Revisar") for merge requests.
I attempted to create a new author and generate a merge request locally but encountered 404 errors in my environment. As a result, I was unable to fully verify the “Review” button changes in a merge-request scenario. 
However, these changes were recommended by the maintainers, and the updated translation string (`"Review "`) is now in place.
N/A
@cdrini
=> Fix: Distinguish ‘Review’ for merge requests vs. book reviews

openlibrary/core/vendors.py, openlibrary/i18n/messages.pot, openlibrary/macros/EditionNavBar.html, openlibrary/plugins/openlibrary/js/edition-nav-bar/EditionNavBar.js, static/css/components/nav-bar.less
Closes #10240
Opposite direction arrow button for Omnibar:
1) Add's new arrow in HTML, CSS, and JS with functionality.
2) Avoid clipping of the first element due to the arrows.
3) Renamed arrows to "nav-arrow-left" and "nav-arrow-right" to avoid confusion in the future.
1)Go to any book page (eg. https://openlibrary.org/works/OL69166W/Italian_journeys)
2)Resize the screen and see the arrow only for one direction
Video of implementation:
https://github.com/user-attachments/assets/433cb952-d81e-4045-bb52-70e863e15083
Screenshot:
@cdrini
=> Opposite direction arrow button for Omnibar

openlibrary/i18n/messages.pot, openlibrary/templates/languages/language_list.html
Related to #9864 #9868
Now that we have a dictionary with the list of languages
https://github.com/internetarchive/openlibrary/blob/3b89202a3618dbc6c077f76da900f55a4ec024dd/openlibrary/plugins/openlibrary/code.py#L1255C1-L1269C6
We can refactor the language list
@mekarpeles
=> use dictionary to generate language list

openlibrary/plugins/openlibrary/js/SearchBar.js
Closes #10484
Closes #10485
Addendum to #10415 ; we only want to show the results if the user has focus in the search bar component.
https://testing.openlibrary.org/search?q=harry+potter&mode=everything does not auto-show the auto complete, but changing the search type selector _does_ cause them to appear.
=> Fix autocomplete results showing up on pageload

openlibrary/core/wikidata.py
Addresses #10444
Updates `_get_from_web()` such that any HTTP error responses from Wikidata API calls are captured by Sentry.
=> Capture Wikidata API errors in Sentry

openlibrary/plugins/upstream/account.py
Closes #10480 
Sets default `action` in `web.input` for the login `POST` handler.
=> Set default `action` value on login `POST`

openlibrary/core/fulltext.py, openlibrary/core/lending.py, openlibrary/plugins/upstream/borrow.py, openlibrary/plugins/upstream/models.py, openlibrary/tests/core/test_lending.py
The API call in get_availability is often a topic of interest, and it ends up being difficult to debug where it's used. Removing these wrappers will help make it a little easier, since now we can just search for get_availability
Closes #
=> Remove helper methods for get_availability to make code easier to trace

openlibrary/plugins/recaptcha/recaptcha.py
Ensures that legitimately invalid ReCaptcha tests cause account creation form validations to fail.
=> Tighten account creation validations

openlibrary/i18n/messages.pot, openlibrary/plugins/upstream/utils.py, openlibrary/plugins/worksearch/code.py, openlibrary/templates/work_search.html, static/css/components/ol-message.less
Some debugging utils added while working on #10405 .
If solr returns an error, all users will see a flash message:
Users with the debug=KEY parameter will see an exact error + url:
And regardless of error, all admins will now be able to view the full solr url used by clicking on the timing info at the bottom of the page:
=> Better handle/display solr errors/debug info on search

openlibrary/core/ia.py
Closes #7616
fix
The cover importing IA endpoint has been changed.
1. Go to any book's page.
2. Click on the "Add Cover Image" option.
3. Hover your mouse pointer on the cover imported from the Internet Archive.
4. If you see the url of the image beginning from ```archive.org/services/img```, the code works as expected.
@scottbarnes
=> Switched cover importing IA endpoint

openlibrary/catalog/add_book/__init__.py, openlibrary/catalog/add_book/match.py, openlibrary/catalog/add_book/tests/test_add_book.py, openlibrary/catalog/add_book/tests/test_match.py
Closes #10461
It turns out this scenario "importing a pre~1970, without ISBN, record into OpenLibrary, it should never be matched to _ANY_ post-1970 edition with an ISBN" was already covered, and seemingly has been since late 2024. 
This PR
* adds more tests to confirm this
* add typehints and documentation to related methods
* makes the difference between a record with a date and one without _more_ negative to potentially avoid false matches (although it was already making the correct determination..)
=> Reduce edition match score if one edition is missing a date

openlibrary/templates/account/view.html
Closes #10508
A non-indented block of logic was preventing all content from rendering whenever the patron was not the my books page owner.
While logged out, visit a list page.  Does it render correctly?
=> Fix `if` block indentation in template

openlibrary/templates/subjects.html
Closes #10502
HTML sanitation was stripping a required `data-config` attribute from tag body carousels on the subject page.  This branch reverses the order of operations such that tag body HTML is sanitized before any macros are rendered.
=> Sanitize tag body before rendering macros

openlibrary/plugins/upstream/models.py
Closes #10516
@mekarpeles provided a different approach: Normalize ISBNs before attempting to mask them.  This will significantly cut down the number of invalid ISBN events being logged, and help surface more problematic errors.
=> Normalize ISBN before masking

openlibrary/accounts/model.py, openlibrary/i18n/messages.pot, openlibrary/plugins/upstream/account.py
Creates new `security_error` authentication error code and message.  Throws `OLAuthenticationError` with the same status code whenever `InternetArchiveAccount.xauthn` calls return `403`s.
Providing a custom error code for these situations allows us to more easily find such errors in Sentry.
=> Throw `OLAuthenticationError` on `xauthn` `403` error

openlibrary/core/fulltext.py
Closes #10499
Ensures that `fulltext_search()` returns a `dict` when availability enrichment fails.
=> Return correct type on failed availability enrichment

openlibrary/i18n/__init__.py, openlibrary/i18n/messages.pot, scripts/i18n-messages
Closes #10489
Addendum to #9889 ; I realized that a few of our python files aren't being picked up the i18n script; so extended it to also grep for ` _(` which should find anything python file that needs to be processed.
- I tried adding `openlibrary/` to the `message_sources` list, but it was muuch slower. The grep approach is about the same amount of time, <5s.
=> Fix i18n not running for some python files

openlibrary/plugins/openlibrary/code.py
Guard against the `features.is_enabled` failures in cache (when recomputed in threads), check `hasattr(web, 'ctx')`
* should only work on testing/prod if queryparam matches `value` for `debug` feature.
Closes #10341
Tested on mek / staging.
See [technical notes here](https://github.com/internetarchive/openlibrary/issues/10341#issuecomment-2692826036)
Confirmed debug page still works (may require a few attempts to trigger solr timeout, requires correct debug key) https://openlibrary.org/search?q=language:eng&debug=xxx
=> guard against web.ctx.features AttributeError in cache contexts

openlibrary/i18n/messages.pot, openlibrary/templates/permission_denied.html
Closes #10524
See [Breakdown](https://github.com/internetarchive/openlibrary/issues/10524#:~:text=Breakdown) 
While logged out / incognito, go to https://openlibrary.org/books/OL51322877M/Averting_the_Digital_Dark_Age/edit
The `log in` link should redirect to something like: `https://openlibrary.org/account/login?redirect=/books/OL51322877M/Averting_the_Digital_Dark_Age/edit`
https://testing.openlibrary.org/books/OL51322877M/Averting_the_Digital_Dark_Age/edit
Considering out of scope for this PR; The `$path` now works correctly, but because the `$path` resolved to `/books/OL51322877M/edit`, the url preprocessor considers `edit` to be the (wrong) title and thus redirects the patron to https://openlibrary.org/books/OL51322877M/Averting_the_Digital_Dark_Age instead of …
=> Fix i18n redirect $path for book edit -> login

openlibrary/plugins/openlibrary/home.py, openlibrary/plugins/openlibrary/tests/test_home.py, openlibrary/templates/home/index.html
Closes #9043
Thriller Carousel in the homepage is populated based on a query instead of using presets based on specific authors.
=> Change Thriller + Textbooks query carousels (homepage) 

scripts/cron_wrapper.py
Whenever wrapped cron jobs fail today, we see the following message in our logs:
```
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
```
This is indicative of the script shutting down before all events can be sent to Sentry.
This PR uses `sentry_sdk.flush()` to wait until all events are sent after a monitored cron job has run.
=> Send all Sentry events before `cron_wrapper` script exits

openlibrary/templates/work_search.html
Closes #10541
On `/search` pages, checks for the existence of `search_response.time` before formatting the same as a number.  If this `search_response.time` does not exist, the `Search solr took {n} seconds` message will not be displayed.
This change should only affect admins.
=> Exclude search time from `/search` pages if no search occurred

scripts/cron_wrapper.py
Fixes failing `pre-commit` checks ([like this](https://results.pre-commit.ci/run/github/69609/1741208132.hVwaJ3GsRYareyUvMXKhKg)).
=> Remove trailing whitespace

openlibrary/templates/type/edition/view.html
Closes #10391
Prevents rendering of `ocaid` in books page "Details" section if the book it not readable nor lendable, regardless of privileges.
The `ocaid` continues to be rendered in the omnibar for members of `/usergroup/librarians`.
=> Hide book page `ocaid` if book not borrowable nor open

scripts/deployment/deploy.sh
Prints deployment script override hint before exiting when critical cron jobs are running.
=> Show deployment script override hint when critical crons are running

openlibrary/components/IdentifiersInput.vue, openlibrary/templates/books/edit.html, openlibrary/templates/books/edit/edition.html, openlibrary/templates/type/author/edit.html
Closes #10301 
Refactor
Remove computed ```isEdition``` variable and use ```saveIdentifiersAsList``` to ensure component still functions properly when saving Author identifiers vs Edition/Work identifiers.
Removes props initially used to create an ordered dropdown list for identifiers, add a popular identifier list within the IdentifiersInput.vue for easier future maintenance.
Run ```docker compose up -d``` and then ```docker-compose run --rm home npx vue-cli-service build --watch --no-clean --mode production --dest static/build/components/production --target wc --name ol-IdentifiersInput openlibrary/components/IdentifiersInput.vue```
Sign in using the OpenLibrary dev account or as a patron
Navigate to an edition and click on the edit button. Click on the identifiers component and check …
=> Clean up and rename computed variables

openlibrary/templates/home/index.html
/read is an old endpoint that sends you to the subject Accessible Books, which has like 12 books! Link to the default search results instead
=> Change "Classic Books" carousel on homepage to not link to /read

.github/workflows/olbase.yaml, .github/workflows/pm_stale_ticket_labeler.yml, .github/workflows/pr_update_labeler.yml, .github/workflows/weekly_status_report.yml
split from #10504
This PR:
*  Prevents internetarchive project only github workflows (slack bot integrations and github issue monitoring) from running on forks
=> Mark upstream only github workflows

.github/workflows/pm_stale_ticket_labeler.yml
Whenever a stale issue is commented upon by the GitHub action bot, the issue's `updated_at` date is updated, making the issue no longer stale.  As a result, the `Needs: Review Assignee` is automatically removed from such issues the next time the stale issue workflow runs.
By passing an empty string as [`stale-issue-message`](https://github.com/actions/stale?tab=readme-ov-file#stale-issue-message), this PR updates the workflow such that _no_ comment will be left by the GitHub actions bot.
=> Prevent comments when issues marked stale

bundlesize.config.json, openlibrary/macros/BookPreview.html, openlibrary/macros/SearchResultsWork.html, static/css/components/search-result-item.less
Closes #10199 #10366 
This modifies the Preview button so that each previewable book on the search results page has a preview link, styled like on the book page.
Squash
Please note that the css was changed between commit 1 and 2 in order to fix specificity but may now need to be quickly re-tested to ensure it's still doing the right thing.
=> On search results, show preview beneath cover

openlibrary/i18n/messages.pot, static/css/components/generic-dropper.less, static/css/components/language.less
Closes #10584 
Fix broken arrow styling on `summary` elements on iOS
@cdrini - Let me know if this works for you (if you are able)! I didn't actually use `summary::marker` in the read button update, so I added it and `summary::-webkit-details-marker` so hopefully that fixes it. Language selector was the only other place I found that only `summary::marker` was defined.
=> Fix broken dropper arrow on iOS

openlibrary/plugins/openlibrary/code.py
~Merge + vbump first: https://github.com/internetarchive/infogami/pull/225~
Closes #10341 
guard against web.ctx.features, not just web.ctx
=> Refix threadeddict #10341

openlibrary/core/schema.sql
Noticing ~1/3 of time of `/search` spent in db queries according to sentry profiles ([link](https://sentry.archive.org/organizations/ia-ux/performance/summary/profiles/?environment=production&project=7&statsPeriod=24h&transaction=%2Fsearch)):
I created 50k dummy data rows locally, and ran the 3 types of queries we run against this table. The one multi-index seems to have removed all Seq Scans and drastically dropped down the query time!
| Query | Time Before | Time After |
| ---- | ---- | ---- |
| Query 1 | 124.643 ms | 5.099 ms |
| Query 2 | 44.402 ms | 1.072 ms |
| Query 3 | 47.150 ms | 0.108 ms |
It might be worth experimenting with adding more indices, but this seems sufficient at the moment. And it would be good to run the below queries on ol-db1 as well before/after.
```sql
-- …
```
=> Create indices for bookshelves_events table

docker/nginx.conf, docker/web_nginx.conf
=> Set stricter rate limits for web requests

openlibrary/i18n/messages.pot, scripts/update_stale_ocaid_references.py
Closes #8343
Tested on `ol-dev1` on `ol-mek-web-1` with:
```
PYTHONPATH=. python ./scripts/update_dark_ocaid_references.py /olsystem/etc/openlibrary.yml --since "2025-03"
```
Then I modified the function `get_dark_ol_editions` to use `q = "openlibrary_edition:* AND identifier:a*"` which limited the results to a single page of about 120 instead of several thousand (for testing)
i.e. the equivalent of:
https://archive.org/services/search/v1/scrape?q=openlibrary_edition%3A*%20AND%20identifier:a*%20AND%20curatedate:[2025-03%20TO%20*]&scope=dark&service=metadata__dark&count=1000&fields=identifier,openlibrary_edition
Note, I added special s3 keys to our olsystem openlibrary.yml to get this to work because the `ia_ol_metadata_write_s3` keys don't have access to `dark`. We should discuss with …
=> (Closes #8343) Create update_stale_ocaid_references.py script

openlibrary/book_providers.py, openlibrary/i18n/messages.pot, openlibrary/macros/LoanStatus.html, openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/js/interstitial.js, openlibrary/plugins/upstream/borrow.py, openlibrary/templates/book_providers/cita_press_read_button.html, openlibrary/templates/book_providers/direct_read_button.html, openlibrary/templates/book_providers/gutenberg_read_button.html, openlibrary/templates/book_providers/librivox_read_button.html, openlibrary/templates/book_providers/openstax_read_button.html, openlibrary/templates/book_providers/runeberg_read_button.html, openlibrary/templates/book_providers/standard_ebooks_read_button.html, openlibrary/templates/book_providers/wikisource_read_button.html, openlibrary/templates/interstitial.html
Closes #10561 
Feature/refactor
Add new behavior to borrow API to redirect to an interstitial page in the case that a read/borrow action is requested on a non-IA provided edition. Also removes the existing toasts that are generated when using a direct provider read button link.
1. Click a read/borrow button for an edition provided by a trusted third party provider
2. Observe that you are now redirected to an interstitial page, and that you can observe the countdown timer, cancel the redirection, or immediately follow to the link.
3. Observe that there is no longer a toast on the original page after clicking the button.
@mekarpeles
=> Migrate to Interstitial for Trusted Book Provider read actions

openlibrary/i18n/messages.pot, openlibrary/templates/check_ins/check_in_form.html, openlibrary/templates/check_ins/check_in_prompt.html
**Problem:**  On my (older) Safari iOS mobile browser, the 'Check in' options, with lengthy description and 3 drop-downs, appears for _every_ item in a search result list, and cannot be hidden. This makes the results list considerably longer than it needs to be, and distracts from the useful page content.
**This PR:**
* Prevents the book check-in form from displaying on older mobile safari browsers. I'm not sure what other browsers are affected.
* Removes a duplicate `method` attribute from the form that broke HTML validation (not sure if it is directly related to the original rendering problem, but it may be?)
All lists of books in search results and author pages had a rendered check-in form for _every_ book.
It looks like the conditional for whether a book is currently being read was …
=> move check-in form inside conditionally hidden div

scripts/deployment/deploy.sh
Adds an additional `production` tag to the latest commit whenever Open Library is deployed to production.  The `deploy-YYYY-MM-DD` tags will remain unchanged.
Adding a `production` tag to the releae commit will allow us to use a static URL when doing our pre-deployment code checks:
https://github.com/internetarchive/openlibrary/compare/production...master
We could simplify this by pushing once with the `--tags` flag, but that will push _all_ local tags to the remote repo.  This would be problematic for maintains who use tags.
=> Add `production` git tag when code is deployed

openlibrary/core/bookshelves_events.py, openlibrary/plugins/upstream/mybooks.py, openlibrary/templates/account/view.html, openlibrary/templates/books/year_breadcrumb_select.html
The dropper was never actually displaying, since I think the header_title has been changed to include a count. This fixes it to use the `key`, and also switched it to use BookshelvesEvents, since people can log year read without necessarily using the yearly reading goals feature.
Tested the query on prod and no Seq Scans:
```
Sort  (cost=17.87..17.87 rows=1 width=9) (actual time=0.130..0.132 rows=5 loops=1)
Sort Key: ("substring"(event_date, 1, 4))
Sort Method: quicksort  Memory: 25kB
->  HashAggregate  (cost=17.84..17.86 rows=1 width=9) (actual time=0.106..0.109 rows=5 loops=1)
->  Index Only Scan using bookshelves_events_user_checkins_idx on bookshelves_events  (cost=0.42..17.76 rows=16 width=9) (actual time=0.032..0.089 rows=19 loops=1)
Index Cond: ((username = 'ScarTissue'::text) AND …
```
=> Enable Already Read year read drop-down

openlibrary/templates/type/list/view.html, openlibrary/templates/type/list/view_body.html
Global lists failing to render at all on prod.
~Before: https://openlibrary.org/lists/OL286201L/International_Booker_Prize_2025_Longlist~ Patch deployed, so no longer erroring.
After: https://testing.openlibrary.org/lists/OL286201L/International_Booker_Prize_2025_Longlist
Before:
After:
=> Fix global lists erroring when rendering

openlibrary/components/BulkSearch/components/BulkSearchControls.vue, openlibrary/components/BulkSearch/utils/searchUtils.js
- Fix the OpenAI API Key box being unclick-able
- Extends leading article removal to exclude more than just `the`
- The issue was that using `v-if` to render one input when `showPassword` is true, and another when it's false, causes the input element to be swapped out! This results in the input field just clicked on, losing focus, meaning you can't type in it :P
- The article thing was to handle a common metadata bug we observer with articles missing from imports. So stripping e.g. "The" and "A", etc from the query casts a wider net that's more likely to match books.
Tested locally, and articles are correctly removed, and the OpenAI API input can be clicked.
=> Fix some small Bulk Search bugs

openlibrary/plugins/worksearch/code.py
When a ListQuery carousel exhausts all its IDs, the query fallback to something that produces lots of results when instead none should be returned. This commit checks if no book keys remain in the list and falls back to a special query that will return no results.
Closes #7552
=> Fix list querying case when out of results

scripts/deployment/deploy.sh
`--profile` expects just the server name, eg `ol-www0`.
Tested running the steps on ol-www0 and worked like a charm!
=> Fix docker compose build not running during deploy

openlibrary/macros/SearchResultsWork.html
Small perf tweaks to avoid sending people to 301 redirects in search, authors pages, lists, etc. Eg no more `/works/OL123W`, no anchors list `/works/OL123W/Work_title` directly.
Before (prod):
After (testing):
=> Avoid redirect when clicking on books in search results by including title slug in URL

openlibrary/core/bookshelves.py
Closes #10623
Compare the books on my want to read on prod vs on testing.
Before:
After:
The exact edition I chose is presented. You can also see on hover, the edition ID that I chose is shown.
=> Make Want to Read also edition-specific to avoid language confusion

openlibrary/i18n/messages.pot, openlibrary/plugins/worksearch/code.py, openlibrary/plugins/worksearch/schemes/lists.py, openlibrary/templates/lists/preview.html, openlibrary/templates/search/lists.html
Closes #2723
Fix: Improves list search functionality to allow partial matches in list titles.
- Added a new `ListSearchScheme` to leverage Solr for list searches.
- Updated `/search/lists` controller to use the new Solr-backed search.
- Refactored the template (lists.html) to align with patterns used in other templates like authors.html and subjects.html to display improved search results.
- Added pagination support to /search/lists, allowing users to navigate through large sets of search results.
- Implemented error handling for list searches, displaying errors when they occur.
- Changes were made in:
- `openlibrary/plugins/worksearch/code.py`
- `openlibrary/plugins/worksearch/schemes/lists.py` (new file)
- `openlibrary/templates/search/lists.html`
1. Navigate to `/search/lists`.
2. …
=> Fix issue #2723: Improve list search functionality

scripts/dump-wikidata.sql, scripts/oldump.sh
Add wikidata dump to included dumps (#10383)
This adds support for generating Wikidata dumps alongside existing dumps like ratings and reading logs. The new dumps follow the ol_dump_wikidata_YYYY-MM-DD.txt.gz naming convention.
- Creates new dump-wikidata.sql script for TSV export
- Updates oldump.sh to include Wikidata dump generation
- Follows existing patterns for file naming and processing
Closes #10383
- Added a new SQL script (dump-wikidata.sql) that exports the wikidata table as TSV
- Modified oldump.sh to add a new step for generating the wikidata dump
- Used the same conditional logic as other dumps to prevent regenerating existing dumps
- Run the oldump.sh script locally with a test database
- Verify the wikidata dump is created with the correct naming convention
- Confirm the …
=> Add Wikidata table export to data dumps (#10383)

scripts/i18n-messages
Closes #10655
Use grep's `-w, --word-regexp` option to make the pattern only match between word boundaries.
Before:
1. Add `foo.append(_("FOO"))` to `openlibrary/core/db.py` 
2. Run `python ./scripts/i18n-messages extract --skip-untracked`
db.py does not get added to messages.pot
After:
db.py appears in messages.pot!
=> Update i18n-messages regex to match any word boundary

openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/js/book-page-lists.js, openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/partials.py, openlibrary/templates/type/edition/view.html
Closes #10653
Replaces initial book page "Lists" section with a loading indicator. Whenever a patron scroll withing `200px` of the "Lists" section, a `/partials` request is made for the section's content and the view is updated with the results.
If either the work or edition is on a list, the "See All" link becomes visible.  This link was previously conditionally rendered, but is now always rendered with the `hidden` class.
=> Lazy-load book page "Lists" section

openlibrary/plugins/openlibrary/partials.py
Follow-up to #10654 
As per this new Sentry [event](https://sentry.archive.org/organizations/ia-ux/issues/546262/events/f20e51d84cfe4390bb45d7e8cd6f8772/), some list section partial requests are failing when empty strings are passed to `web.ctx.site.get()`.  These changes ensure that a `work_id` or `edition_id` exist before making the `get()` call.
=> Ensure OLID exists before fetching book data

openlibrary/i18n/messages.pot, openlibrary/templates/account/view.html, openlibrary/templates/books/year_breadcrumb_select.html
Small refactor to make #10648 easier. Make `year_breadcrumb_select` more configurable so it can be used from other pages.
Please squash before merging.
Confirmed working on testing.
=> Refactor year breadcrumb select to take in yearly_reads

openlibrary/templates/home/index.html
Closes #10659
Restores Authors Alliance / MIT Press carousel by adding sorting criteria.  Without a value for `sorts`, the `/advancedsearch.php` request ended with `sort[]=`.  Such requests resulted in `400`s.
All other homepage `custom_ia_carousels` use `["lending___last_browse desc"]` as the sorts value.  Adding the same to the MIT Press carousel fixed the issue.  I'm not sure if this is exactly how we want to sort these books --- reviewers should feel free to suggest another way if they are so moved.
_Screenshot from testing environment_
=> Restore MIT Press carousel

openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/js/interstitial.js, openlibrary/templates/interstitial.html
Closed #10650
- Removed inline JavaScript from cancel button
- Added delegated event listener in `initInterstitial()`
- Implemented proper timer cleanup
- Added error handling for `window.close()`
=> Remove inline Javascript from interstitial template

openlibrary/plugins/openlibrary/partials.py
Followup to #10669 
Updates the /partials.json handler in hopes of making future partial development less error prone.
Each type of partial request is now handled by a subclass of `PartialDataHandler`, which has a `generate` method that returns a JSON-serializable `dict` containing the required data. Passing a valid `_component` key to `PartialRequestResolver.resolve()` will return the correct `PartialDataHandler.generate()` output.  If the `_component` key is unrecognized, a `PartialResolutionError` is raised.
With this in place, we can update the `/partials.json` handler to return new partials by doing the following:
1. Create a new subclass of `PartialDataHandler`
2. Write a `generate()` method for the new class
3. Add the new class and `_component` name to the …
=> Replace partials handler conditional with factory

openlibrary/catalog/marc/parse.py
Closes #10652
Import DOI (digital object identifier) from MARC records
=> Read DOI identifier from MARC 024 fields

openlibrary/i18n/messages.pot, openlibrary/plugins/upstream/addtag.py, openlibrary/templates/subjects.html, openlibrary/templates/type/tag/tag_form_inputs.html
Makes the following changes:
1. Adds a new `deputy` field to tag create and edit forms
2. Updates permissions for adding and editing tags
3. Changes validation order in tag editing handlers
4. Better denotes what fields are required in tag create/edit forms
New permissions are as follows:
| Action | Permitted Parties |
|---|---|
| Creating a new tag (any type) | `/usergroup/admin` members |
| Editing a non-subject type tag | `/usergroup/admin` members |
| Editing a subject tag | `/usergroup/admin` members and the tag's designated `deputy` |
`deputy` is not a required field for any tag type, so all tags can be created without one.  The `deputy` field stores a patron's `User` key (`/people/{person}`) if a deputy exists.
=> Update create and update permissions for Tags

openlibrary/plugins/openlibrary/js/editions-table/index.js, openlibrary/plugins/openlibrary/js/index.js, static/css/components/editions.less
Addresses #9853 Task 5
Fix
Initializes the ILE/SelectionManager classes before the Editions DataTable to allow the ILE to bind the click events and add class names to the relevant DOM elements. 
Prevents the Editions DataTable from re-initialization with .isDataTable method.
Utilizes the ```drawCallback``` option for DataTables to remove visual inconsistencies when a user selects editions from multiple pages, clicks on clear selection, and re-navigates to a page that had a previously selected edition by checking the sessionStorage object.
Sign in with the admin account and navigate to a work that has >3 editions (the more the better).
Verify that the magic select editions beyond the first page of the Editions Table.
Press the ```Clear Selection``` button within the magic select toolbar on …
=> Fix Magic Select binding for Editions DataTable

openlibrary/plugins/openlibrary/partials.py
Closes #
`offset` and `limit` are being added together in `cached_get_list_book_keys` calls ([here](https://github.com/internetarchive/openlibrary/blob/6897abce39bfa845f06fc99ff1a3a2779dc55ced/openlibrary/plugins/worksearch/code.py#L828)).  These changes ensure that `limit` is a number when this method is called while lazily-loading list carousels.
=> Fix lazily-loaded ListCarousels

openlibrary/macros/ListCarousel.html
Follow-up to:
#9807
#10669
Adds `use_cache` and `lazy` keyword parameters to the `ListCarousel` template.  These are passed through to the `QueryCarousel` call.
=> Add new `QueryCarousel` options to `ListCarousel`

openlibrary/plugins/upstream/mybooks.py, openlibrary/templates/account/readinglog_stats.html
Added filter by year dropdown to the "already read" stats page. Fixing a previous PR by using year_breadcrumb_select.html
Closes #10648
Adding dropdown to readinglog stats page so the user can be filtered by year
Edited the stats GET request in the mybooks.py file to also process the year that each book was read. I also edited the readinglog_stats.html template page to add in the year drop down and properly change the URL endpoint to filter the books. 
docker compose run --rm home make test
tested on my localhost -screenshots below
@cdrini
=> Add option to filter reading stats by year read

openlibrary/plugins/openlibrary/config/edition/identifiers.yml, openlibrary/plugins/openlibrary/config/work/identifiers.yml
fix/feature
This adds `goodreads` and `librarything` work identifier entries as well as some minor cleaning up of the `work/identifiers.yml` file (and also one minor thing in `edition/identifiers.yml`). (For further details, see individual commits.)
Check that Goodreads and LibraryThing show up in the identifier list for Works.
Check that MusicBrainz Work IDs link to MusicBrainz Works rather than Artists.
@cdrini (as lead of https://github.com/internetarchive/openlibrary/issues/497 which this will be a prerequisite of)
=> Improve work identifiers

openlibrary/plugins/upstream/account.py
Sets `pd` cookie in `/account/login.json` `POST` handler.  This handler is used by our Google sign-in flow.
This sets `pd` in the same way that it is set in the non-json `/account/login` `POST` handler, here:
https://github.com/internetarchive/openlibrary/blob/f0ec88c73e218d4d848825241501ec59a196ec1c/openlibrary/plugins/upstream/account.py#L482
1. Log in via Google sign-in using a print-disabled account
2. Verify that the `pd` cookie is set, and that it's value is as expected
3. Log out, then log in via Google sign-in using a _non_-print-disabled account
4. Verify that the `pd` cookie is set with an empty string `value`
=> Ensure `pd` cookie is set on login

openlibrary/plugins/importapi/code.py, openlibrary/plugins/importapi/tests/test_code.py
Closes #10716 
The error isn't super pretty, but it at least helps explain why an import fails.
Note: this applies the requirements from #9440, insofar as the record must be differentiable (i.e. complete or it has a strong identifier).
Hitherto, these IA imports have been evading that requirement.
Example:
```
curl -L -v -X POST "http://localhost:8080/api/import/ia" -b ~/cookies.txt -d "identifier=autonomicimbalan0000unse&require_marc=false&force_import=false"
{"success": false, "error_code": "not-differentiable", "error": "2 validation errors for CompleteBook\nauthors.0.name\n  String should have at least 1 characters [type=string_too_short, input_value='', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.4/v/string_too_short\npublishers\n  Field required …
```
=> Feature: better explain /api/import/ia errors

.github/workflows/python_tests.yml
Copilot suggests: The GitHub Actions environment for Python 3.12.2 has a broken pip preinstalled.
Specifically, pip internally vendors (bundles its own copy of) a library called resolvelib.
Somehow, the resolvelib inside that pip is missing or mismatched — it’s trying to import RequirementInformation, but it doesn’t exist.
So even before you install anything, the base pip in GitHub Actions is already corrupted.
Uses **copilot suggestion** to attempt to unbreak tests by pinning `pip` to stable version:
https://github.com/internetarchive/openlibrary/actions/runs/14699560888/job/41274914506#step:6:1
```
0s
Run pip install --upgrade pip setuptools wheel
ERROR: Exception:
File "/opt/hostedtoolcache/Python/3.[1](https://github.com/internetarchive/openlibrary/ac …
```
=> Unbreak tests, pin to stable pip

openlibrary/plugins/worksearch/code.py
Follows up #10680 ([comment](https://github.com/internetarchive/openlibrary/issues/10680#issuecomment-2813785988))
The list comprehension passed to the `work_search` `add_availability` call fails with an `IndexError` when `work.editions.docs` is an empty list.  This bug is being tracked in three separate Sentry issues ([1](https://sentry.archive.org/organizations/ia-ux/issues/545351/?environment=production&project=7&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D%20list%20index%20out%20of%20range&referrer=issue-stream&stream_index=1), [2](https://sentry.archive.org/organizations/ia-ux/issues/547719/?environment=production&project=7&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D%20list%20index%20out%20of%20range&referrer=issue-stream&stream_index=4), …
=> Avoid `IndexError` during `work_search` availability enrichment

openlibrary/catalog/marc/parse.py
https://www.loc.gov/marc/bibliographic/bd583.html
too holding specific, not relevant for a general record
Closes #
Example:
https://openlibrary.org/books/OL58796639M/NATO_a_%C4%8Cesk%C3%A1_republika
contains an overly specific https://www.loc.gov/marc/bibliographic/bd583.html Action Note
"committed to retain 20181001 in perpetuity ReCAP Shared Collection"
This PR add this notes field to the excluded notes list.
=> Exclude MARC notes field 583

openlibrary/plugins/upstream/account.py
Interim solution for #10731
Correctly captures the `checked` value of the `ia_newsletter` checkbox, found on the `/account/create` view.
This solution is a stopgap that is meant to avoid merge conflicts with #10724.  Once that branch has been merged, myself or others can work towards the solution outlined in #10731.
=> Capture `ia_newsletter` checkbox value

openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/js/signup.js, openlibrary/plugins/openlibrary/pd.py, openlibrary/plugins/upstream/account.py, openlibrary/plugins/upstream/forms.py, openlibrary/templates/account/create.html, openlibrary/templates/email/account/pd_request.html, static/css/page-signup.less, tests/unit/js/signup.test.js
Closes #10457
Adds new checkbox to account registration form which will allow patrons to self-identify as print-disabled.  When the checkbox is clicked, a selector containing all registered print-disability authorities appears below the checkbox.
When the form is submitted, the chosen authority is set as a `pda` cookie.  After verifying their account, a patron's `pda` cookie (should one exist) is added to their account and an email containing further instruction is sent to the patron.
=> PD registration flow

openlibrary/plugins/openlibrary/pd.py
Follow-up to #10724 
Corrects type hinting on `get_pd_org` function.
=> Fix `get_pd_org ` type hint

openlibrary/plugins/worksearch/languages.py, openlibrary/utils/solr.py
Fix /languages page timing out, and make it more performant by caching the results to avoid frequent solr hits of this expensive query.
Before: https://openlibrary.org/languages (times out, re-fetched every time)
After: https://testing.openlibrary.org/languages
Also not still works with i18n: https://testing.openlibrary.org/languages?lang=es
=> Fix /languages timing out + make it cache

openlibrary/core/lending.py
Instead of relying on Sentry to keep track of the number of availability errors from a service Open Library can't control, this instead opts to log a warning, increment a `statsd` counter at a 1% sample rate, and returns an empty dictionary.
Closes #10754
Feature.
This logs a warning rather than raising an error and increments a counter with a 1% sampling rate. This could then be graphed in Grafana.
Assuming this overall approach makes sense, it makes sense to take a moment to think about whether this should be logging a warning, an error, etc., and also the name should be for the counter that's incremented. Additionally, it's possible another sampling rate would make more sense.
Verify the counter increments when there are lending errors, and that they correspond to the logged warnings. …
=> Feature: use statsd for availability errors

openlibrary/plugins/upstream/tests/test_utils.py, openlibrary/plugins/upstream/utils.py
Closes #10749
This addresses the second most common error in Sentry at the moment.
The strategy is to handle the `UnknownLocaleError` from Babel and simply default to using English to commify the list.
It's entirely possible, perhaps even likely, the comma format will be wrong, but it's not clear we can easily correctly commify when Babel doesn't recognize the locale.
It may be that an incorrectly commified list is better than an error and no list at all for the patron, which is the production outcome at the moment.
If we are not looking at the logged warnings, we will have no sense of how often this is happening. Perhaps it should be logged with `statsd`?
See the unit tests.
@mekarpeles
=> Fix: handle and log UnknownLocale errors in commify_list

openlibrary/core/bookshelves.py, openlibrary/plugins/openlibrary/home.py, openlibrary/plugins/openlibrary/partials.py, openlibrary/plugins/worksearch/code.py, openlibrary/templates/type/list/view_body.html, openlibrary/views/loanstats.py
Closes #10762 : Make Trending carousel edition-aware
Closes #10742  : Fix IA carousel covers not edition-aware
Closes #2906 : Epic, make homepage carousels edition-aware
Closes #10710 : Fix second page of books not edition-aware
Note this also resulted in the trending pages themselves becoming edition-aware: https://testing.openlibrary.org/trending/daily?lang=es
Before:
After:
=> Make all homepage carousels edition-aware

openlibrary/components/MergeUI/MergeTable.vue
Closes #10292 ( #10297)
Adds author names next to the merged works in the merge view, improving clarity by making it easier to identify duplicate authors. It ensures author names are shown consistently throughout the process, not just next to unmerged works.
Technical
Added enhancedRecords to the merge function in MergeTable.vue
Stakeholders
@RayBB @cdrini
=> Show author names next to final result in author merge tool

bundlesize.config.json, static/css/components/search-result-item.less
Closes #10667
This PR attempts to fix the issue where the "Preview" button in the Author page was cropped off.
After going through the code, I figured a single CSS change to `openlibrary\static\css\components\search-result-item.less` should do the trick and prevent the "Preview" button from being clipped off.
What I did was essentially changed the `overflow` attribute of `.bookcover` from `hidden` to `visible`.
**Before:**
**After**
@RayBB
=> Fixed Preview button being cropped

openlibrary/book_providers.py, openlibrary/core/lending.py, openlibrary/plugins/openlibrary/code.py, openlibrary/plugins/openlibrary/home.py, openlibrary/plugins/upstream/utils.py, openlibrary/plugins/worksearch/schemes/works.py
Bots don't need real-time availability, so switch to serving ebook_access from solr, which avoids an extra network request.
Closes #
=> Serve solr-based availability for bots

openlibrary/accounts/model.py, openlibrary/core/bestbook.py, openlibrary/core/bookshelves.py, openlibrary/core/models.py, openlibrary/core/schema.sql, openlibrary/plugins/openlibrary/api.py, openlibrary/plugins/openlibrary/tests/test_bestbookapi.py
Closes #9520 
This PR introduces minimal MVP functionality for the best book award feature. The changes add new API endpoints, integrate award operations into the models, establish relevant tests, and update bookshelf methods for checking read status.
New tests for award addition, removal, and limit conditions.
New API endpoints for awarding and counting best book nominations.
Integration of award logic in models and implementation in a dedicated Bestbook class.
You can test on localhost through the browser developer console as a logged in patron with:
```
const params = new URLSearchParams({
topic: 'Fiction',
comment: 'Great book!',
op: 'add'
});
fetch(`http://localhost:8080/works/OL151880W/awards.json?${params.toString()}`, {
method: "POST",
credentials: "include"
})
.then(response => …
```
=> Add tables + APIs for bestbook feature

renovate.json
I noticed that when I updated bundlesize [a few years back](https://github.com/internetarchive/openlibrary/pull/8322/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L54) I didn't realize we also needed to update the name in the renovate config. So this PR does that!
After this PR is merged then #10789 will auto merge.
=> update bundlesize name for automerge config

openlibrary/plugins/openlibrary/js/covers.js, openlibrary/templates/covers/change.html, static/css/components/manage-covers.less
Very similar to #10778 
We avoid repainting by hiding this text until we're ready to init the page.
See video
https://github.com/user-attachments/assets/35d03421-3a5e-4465-a90e-da2cd2e48ab4
=> avoid repaint on manage covers page by hiding text until needed

openlibrary/core/models.py
Followup to #10776
See also: #10796
We were getting an error in some cases:
```
<class 'AssertionError'> at /books/OL32849056M
key account/ImportBot does not start with '/'
Python 	/openlibrary/infogami/infobase/client.py in get, line 324
Web 	GET http://testing.openlibrary.org/books/OL32849056M
Traceback (innermost first)
/openlibrary/infogami/infobase/client.py in get
assert key.startswith('/'), f"key {key} does not start with '/'" ...
▶ Local vars
/openlibrary/openlibrary/core/models.py in info
d['author'] = d['author'] and self._site.get(d['author']) ...
▶ Local vars
/openlibrary/openlibrary/core/models.py in get_aspect_ratio
info = self.info() ...
▶ Local vars
/openlibrary/openlibrary/plugins/upstream/models.py in get_cover_aspect_ratio
return cover.get_aspect_ratio() ...
▶ Local …
```
=> don't fetch author with cover aspect ratio

openlibrary/plugins/upstream/account.py
Makes the following changes to the PD flow when a patron first logs in:
- `unqualifed` `pda` values are captured on the account
- `pda` and `rpd` values are written to the account before the email is sent
- Adds a new `rpd` status code (this may require discussion), and encodes these as an `Enum`
1. Patron with `pda` cookie logs in.
2. The `pda` value is added to the patron's account
3. `rpd` is added to the account, with a value of `0` (signifying that they are requesting special access).
4. "Next steps" email is sent to patron.
5. Account's `rpd` value is updated to `1` (meaning that the email has been sent).
6. `pda` cookie is unset and expired.
=> Updates to PD registration flow

docker/README.md
I noticed several of our codeblocks in the docker docs don't have `sh` or `bash` and that stops syntax highlighting (see top is nice and bottom is missing highlighting)
PS: I chose to standardize on `sh` because we used it quite a few times in the doc and it's short.
If someone things we should use bash that's fine too.
=> fix codeblock languages in docker docs

openlibrary/core/lending.py
Towards closing #7726
Removes code that calls the ACS server from `lending.py`.
A separate PR will be created for removing ACS code from `/plugins/upstream/borrow.py`.
Marked as draft until failing CI/CD checks are addressed.
=> Remove ACS code and configuration from `lending.py`

openlibrary/templates/merge_request_table/table_row.html
Closes #10714 
This PR achieve to link each merge request listed to the resultant work.
I only added a link to `$review_url` by setting `<a href="$review_url" class="mr-title-link">`. This should create a link to the resultant work for now. If there's anything more that should be done, please leave a feedback. Thank you!
=> add a link to merged works

docker/nginx.conf
Fix requests for cover dimensions, uploads, being rate-limited.
=> Don't rate limit internal requests

requirements.txt
Closes https://github.com/internetarchive/openlibrary/pull/10809
I saw renovate was trying to upgrade this lib and hadn't seen it used anywhere.
So I took a look and it doesn't seem we use it anywhere at all so we can remove it.
Originally added and used in this PR https://github.com/internetarchive/openlibrary/pull/2865
=> remove unused Deprecated lib

scripts/deployment/deploy.sh
This doesn't close an issue but is related to #10394 and making it easier for the team to deploy and announce code without having to look up separate documentation.
For those who prefer the previous deploy style, the core 4 commands (`olsystem`, `openlibrary`, `review`, and `finalize` will still work.
Enhancements make it so one can run `./deploy.sh` and the flow will prompt in order:
- announcement
- do git pull? Y/n
- do docker image build (before openlibrary)
- proceed to olsystem deploy? Y/n
The commands are echo'd in the flow and so the docs are no longer needed for performing a deploy.
Adds function for cloning booklending utils (if/when needed)
=> Streamline deploy.sh

openlibrary/macros/StarRatingsStats.html
Closes #10812
Fix: Remove extra dot between ratings and want to read
remove line 21
=> Remove extra dot star rating stats component

docker/nginx.conf, docker/web_nginx.conf
A marker of suspicious traffic we see is veeeery old browsers making a ton of requests. Eg Firefox 4 pre-release :P So block those.
- Also re-jiggered / DRY'd our nginx files to make adding these sort of things easier.
- And DRY the authors location block, so our checks now also apply to author pages.
Patch deployed onto ol-www0 ; we see the new blocks in orange:
@scottbarnes
=> Add nginx blocks for older browsers + rejigger nginx conf

openlibrary/i18n/messages.pot, openlibrary/plugins/upstream/forms.py
Adds an asterisk after the word `apply` in the print disability access request checkbox's label.
=> Update Print Disability checkbox label copy

bundlesize.config.json, openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/code.py, openlibrary/plugins/openlibrary/js/index.js, openlibrary/plugins/openlibrary/js/librarian-dashboard/index.js, openlibrary/plugins/openlibrary/librarian_dashboard.py, openlibrary/templates/librarian_dashboard/data_quality_table.html, openlibrary/templates/type/author/view.html, openlibrary/templates/work_search.html, static/css/components/librarian-dashboard.less, static/css/components/work.less
Closes #7661
Adds a `details` element containing a book data quality table to work search and author pages.
Data quality queries criteria and queries are returned as a list by the `get_quality_criteria` public function.  Adding a new `dict` with the following key-value pairs to this list will auotmatically include the new quality criterion to the table:
`name`: Describes the criterion (e.g. "Has number of pages")
`apiUrl`: URL that will return books that fit the criteria
`searchPageUrl`: URL for a `/search` containing books that fit the criteria
Each row in the data quality table can have one of three states:
- __Pending:__ Shows a loading message.
- __Error:__ Shows an error message, and a retry affordance.
- __Success:__ Displays the number of quality books, a link to the `/search` page …
=> [Librarian Dashboard] Add data quality table to work search and author pages

Readme.md
Closes #10854
fix
This PR fixes broken language links in the `Readme.md` file and adds a missing link for the Vietnamese translation. The changes ensure that all language links correctly point to their respective sections.
1. Open `Readme.md` in preview mode on GitHub.
2. Verify that all the listed language links (including Vietnamese) are working and lead to the appropriate sections.
3. Confirm there are no broken anchors or markdown syntax issues.
N/A — This is a markdown file update only.
@internetarchive/openlibrary-maintainers
=> Fixes #10854: Added Vietnamese link and fixed broken language links in Readme.md

docker/Dockerfile.olbase
Small refactor/linting, keep seeing these warnings:
> docker: docker/Dockerfile.olbase#L6
> LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format
> More info: https://docs.docker.com/go/dockerfile/rule/legacy-key-value-format/
=> Update Dockerfile.olbase to use new ENV syntax

openlibrary/macros/RawQueryCarousel.html, openlibrary/templates/home/index.html
Small fix to make clicking the link for a query carousel persist the sort.
=> Persist sort when clicking on carousel

openlibrary/macros/FulltextResults.html, openlibrary/macros/SearchResultsWork.html, openlibrary/templates/account/loan_history.html, openlibrary/templates/account/reading_log.html, openlibrary/templates/stats/readinglog.html, openlibrary/templates/trending.html, openlibrary/templates/type/author/view.html, openlibrary/templates/type/list/view_body.html, openlibrary/templates/work_search.html
Closes #10864
Confirmed on testing, the covers requests now happen after you scroll down.
=> Lazy load below-the-fold covers in SearchResultWork

openlibrary/plugins/upstream/addbook.py, openlibrary/plugins/upstream/tests/test_addbook.py
Closes #10193 
This was a bit tricky to test, since it only happens on prod/testing. I think it's something to do with `self.work` being a lazy `Thing`, and hence not having any fields. I believe these lazy `Thing`s aren't fetch from the db until data is requests from via `__getattr__` or other methods (see https://github.com/internetarchive/infogami/blob/f9538c06003361ea22b0d23f278bee10250139e2/infogami/infobase/client.py#L901-L917 ).
I put these changes on testing and confirmed they work there :+1:  Tested copying just authors, authors and subjects, and just subjects. All worked now!
=> Fix copy authors/subjects when moving edition to new work

openlibrary/i18n/messages.pot, openlibrary/macros/WorldcatLink.html
Closes #10859 
This PR fixes a UI issue by commenting out the `<li>` tag that displays a link to a public inactive API. This prevents users from seeing or clicking on a broken or deprecated link.
- Commented out the `<li>` element in the relevant template to hide the inactive API link.
- No functional changes beyond UI adjustment.
- Verified locally that the link is no longer visible in the UI.
- Checked that no other UI elements are affected.
@mekarpeles
=> fix(#10859): commented the Library.linkd

openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/tests/test_home.py, openlibrary/templates/home/index.html
Extends #9043 whose solution was #10532 
Also related to #5858
=> Use OL for more homepage carousels

.github/workflows/olbase.yaml
Closes #10276
The solution is highly duplicative; in a future issue/PR we might want to see how we could potentially DRY up the approaches, but we need to ensure that the amd64 build finishes/pushes as quickly as possible! I think our best bet is seeing how can basically do `tag = 'latest' if master else branch_name`, and then the Master/Test duplication disappears.
To test locally:
- ✅ On an amd machine, run: `docker run --rm --pull always openlibrary/olbase:olbase-platforms echo Success`
- On an arm machine, run: `docker run --rm --pull always openlibrary/olbase:olbase-platforms echo Success`
The CI job passess!! https://github.com/internetarchive/openlibrary/actions/runs/15350887215/job/43198548359
And the docker hub lists both the arch's in its build! …
=> Add multiple platform support for olbase build

openlibrary/templates/books/add.html
Closes #10895
Expands privileges for adding web books to `librarians` and `super-librarians`.  Admin privileges remain unchanged.
=> Change privs for adding web books

openlibrary/templates/books/edit/edition.html
Closes #10895
This makes the following changes to the book edit form:
1. Includes `super-librarians` in `is_privileged_user` guard
2. Expands web book editing to `librarians` and `super-librarians`
=> Expand web book editing privileges

openlibrary/i18n/messages.pot, openlibrary/plugins/openlibrary/js/add-book.js, openlibrary/plugins/openlibrary/js/idValidation.js, openlibrary/templates/books/add.html
Closes https://github.com/internetarchive/openlibrary/issues/8719
feature
Adds another option to the dropdown, using the same ordering used in the [`$popular` array for adding identifiers on the book editing page](https://github.com/internetarchive/openlibrary/blob/0621e75c0cea30be3902b606198247d6c1b2dc23/openlibrary/templates/books/edit/edition.html#L444).
Validation is based on that of the LCCN identifiers, but also generalises the `displayLccnError()` function into a generic `displayIdentifierError()` since there wasn’t anything LCCN specific about it – and I didn’t want to WET the code by copy/pasting the code for an identical `displayOclcError()` function. :) (This PR already WETs a fair deal. A lot of the LCCN and OCLC could be abstracted a bit more to be usable for both case.)
1. …
=> Include OCLC ids on the Add Book page

openlibrary/core/pd.py, openlibrary/i18n/messages.pot, openlibrary/plugins/admin/code.py, openlibrary/plugins/openlibrary/pd.py, openlibrary/templates/admin/menu.html, openlibrary/templates/admin/pd_dashboard.html, scripts/detect_missing_i18n.py, static/css/components/pd-dashboard.less, static/css/page-admin.less
Related to #10724
Adds a new dashboard for tracking print disability access requests.  The new dashboard is available at `/admin/pd`, and can only be viewed by admins.
=> Print disability access request dashboard for admins

openlibrary/plugins/upstream/data.py
Now that the dump added in #10531 has run, we can add a link to it! This will make links like https://openlibrary.org/data/ol_dump_wikidata_latest.txt.gz resolve, matching our other dumps.
=> Add support for wikidata data dump link

openlibrary/components/MergeUI/EditionSnippet.vue
Small fix to make clicking on edition covers in the merge UI open the cover in a new window.
=> Make MergeUI edition covers link to enlarged covers

openlibrary/core/vendors.py, openlibrary/tests/core/test_vendors.py
Closes #10868 . Small fix, just check if 0.
Tested via unit tests; couldn't test this otherwise since the already-coerced metadata record is stored in the affiliate server cache, so can't have it be re-processed by my new code.
=> Don't save number of pages 0 from Amazon

openlibrary/plugins/upstream/tests/test_utils.py, openlibrary/plugins/upstream/utils.py
Closes #10893 .
Previously it only checked the first `name_translated` for each language. This makes it check everything, allowing us to have aliased like "Portuguese Brazilian" for Portuguese.
The previously failing import now works on testing:
=> Also check language aliases when checking for language names

openlibrary/plugins/openlibrary/js/edit.js
Closes #10401
- Fixed inconsistent return key behavior in Classifications editing
- Added proper event handling to prevent form submission
- Made behavior consistent with ID Numbers field functionality
Modified `initClassificationValidation()` in `edit.js`:
- Added `preventDefault()` to stop form submission on Enter
- Added `repeat('add')` call to trigger classification addition
- Returns `false` to prevent event bubbling
1. Go to any edition's edit page
2. Focus on Classifications input field
3. Type valid classification details
4. Press Enter/Return key
5. Verify:
Input is added as new classification
Page does not save/reload
Behavior matches ID Numbers field
@cdrini
=> added key interception to prevent form submission on enter key

openlibrary/core/models.py
Makes the following changes to `User` preference methods:
1. Adds a `use_store` keyword parameter to `preferences()`.  When `True`, we attempt to fetch a patron's preferences from the store.
2. Adds `use_store` keyword parameter to `save_preferences()`.  When `True`, we save the data to the store.  When `False`, we save the typical way, then recursively call `save_preferences(use_store=True)` to also save the preference to the store.
When this is merged, we will continue fetching from and saving to the business as usual (BAU) tables.  The only difference is that we will also save a copy of the preferences to the store when preferences are saved.
1. Run job to copy all existing preferences to the store
2. At this point, all existing and new patrons will have preferences in the store, so we …
=> Save preferences to store

openlibrary/catalog/add_book/__init__.py, openlibrary/catalog/add_book/load_book.py, openlibrary/catalog/add_book/tests/test_add_book.py, openlibrary/catalog/add_book/tests/test_load_book.py, openlibrary/i18n/messages.pot, openlibrary/plugins/importapi/code.py, openlibrary/plugins/importapi/import_ui.py, openlibrary/plugins/openlibrary/code.py, openlibrary/templates/import_preview.html
Closes #10885
Debugging amazon import flows is difficult, since the `/isbn/` endpoint silently swallows any errors (by design). You need to fully go into code, set up internal hooks to the prod affiliate server/etc. It's similarly next to impossible to find the error thrown when an import fails without trying to reconstruct the full request to our API endpoints. This PR adds an option to our imports to `preview`, and adds a simple UI at `/import/preview` to see this for amazon imports.
Roughly a step towards https://docs.google.com/document/d/1_djSM5BZIsg6zWkrILmbS3RjAEjqW5cFXh-DPXQ_ZVc/edit?disco=AAABkaEfwM4
Longer term vision:
- Make this something librarians can use to quickly improve records with the click of a button, and further garner trust and transparency into our import logic
- …
=> Add preview option/ui to import endpoints

openlibrary/i18n/messages.pot, openlibrary/templates/covers/add.html, static/css/page-form.less
- **set max height of pasted image to 200px**
- **improve IA upload button text**
- **move buttons above image and improve spacing**
Based on discussions with Drini I've made a few improvements to the cover uploading experience when pasting.
https://github.com/user-attachments/assets/cf1f0d73-d6a5-4b44-915e-c800df2d4917
=> Improve UX for pasting images to upload

openlibrary/i18n/messages.pot, openlibrary/templates/type/edition/admin_bar.html, static/css/components/work.less
Based on [this](https://internetarchive.slack.com/archives/C0119PRDV46/p1749718917414249?thread_ts=1749664106.262099&cid=C0119PRDV46) discussion I am proposing the following changes:
- Only show the add to staff picks button when there is an ocaid 
- Improved spacing
I've always wondered why that button was there and after some digging I learned it does nothing unless there's an ocaid. Which is quite often for me. So lets hide and and fix up spacing at the same time.
PS: This is just a PoC. Maybe we don't actually want this change?
| - | - |
| ![image](https://github.com/user-attachments/assets/e04e9630-d61e-4aeb-884f-49fb9e3edd10) | ![image](https://github.com/user-attachments/assets/0a8c0eeb-9430-47c0-9e30-bd0744970483) |
| …
=> improve admin bar spacing and conditional display

openlibrary/templates/admin/pd_dashboard.html
Follow-up to #10822
Makes the following updates to the print disability special access dashboard template:
1. Removes the "Requested" column from the table.  The total requested count __is still__ available in the summary section.
2. Request table totals are no longer calculated in the template.  Instead, the totals that are passed to the template are displayed in the table.
=> Admin PD dashboard improvements

pyproject.toml
Closes #10196
With this final PR, we can close that issue to open some old ruff rules.
I've gone through all the rules and added their description and why we're ok with them being disabled.
=> annotate disabled ruff rules

compose.override.yaml, docker/ol-covers-start.sh, docker/ol-home-start.sh, docker/ol-infobase-start.sh, docker/ol-solr-updater-start.sh, docker/ol-web-start.sh, openlibrary/utils/shutdown.py, scripts/infobase-server, scripts/openlibrary-server, scripts/solr_updater/solr_updater.py
Lately I've been restarting docker a lot (because I'm working with carousels that are cached).
It takes 10+ seconds to do a docker compose down.
So I asked why, and it turns out we just don't have our scripts setup to handle the sigint/sigterm and so we get the default docker timeout of 10 seconds before a force shutdown.
This PR updates it.
Run `docker compose up -d && docker compose stop` to test.
Before: 15+ seconds
After: ~3 seconds
Edit: Sometimes that fails for unclear reasons but if it sleeps for 2 seconds then shutdown happens right away. But for normal use cases this is still a success. `docker compose up -d && sleep 2 && docker compose sto`
We need to exec to pass down the sigint. Then handle the sigint in python.
=> make docker shutdown faster with graceful sigint handling

openlibrary/plugins/openlibrary/js/ia_thirdparty_logins.js, openlibrary/plugins/upstream/account.py, openlibrary/templates/login.html
Closes #10870
Supplants #10944
Updates code such that Google SSO authentication requests are routed to the HTML login handler.  Now, all logins via the `/account/login` page are handled by `account_login.POST`.
Any code that supported web application features has been removed from the JSON login handler (i.e. "Remember Me" option, `pd` cookies, etc.).
I believe that some CSP configurations are preventing us from using Google SSO in testing, so that will need to be updated before this can be properly tested.
I have tested submitting the form with the S3 key inputs filled, and that seemed to work as expected.
=> Route Google SSO authentication requests to `HTML` login handler

openlibrary/plugins/importapi/import_validator.py
Closes #
When running tests two of the warnings we get are:
```
openlibrary/plugins/importapi/import_validator.py:38 /openlibrary/openlibrary/plugins/importapi/import_validator.py:38: PydanticDeprecatedSince20: Pydantic V1 style @root_validator validators are deprecated. You should migrate to Pydantic V2 style @model_validator validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/ @root_validator(pre=True)
openlibrary/plugins/importapi/import_validator.py:53 /openlibrary/openlibrary/plugins/importapi/import_validator.py:53: PydanticDeprecatedSince20: Pydantic V1 style @root_validator validators are deprecated. You should migrate to Pydantic V2 style …
```
=> fix pydantic warnings

openlibrary/core/schema.sql
Closes #
(none opened)
Adds a missing semicolon to ol-db-init.sh, the startup process was failing to create openlibrary postgres user on a new development machine. Worked after this change.
Might be hard to reproduce without a machine that has never run OL locally before, but this happened when I was setting up for the first time in WSL2 Ubuntu (line endings are correct).
@cdrini 
Attribution Disclaimer: By proposing this pull request, I affirm to have made a best-effort and exercised my discretion to make sure relevant sections of this code which substantially leverage code suggestions, code generation, or code snippets from sources (e.g. Stack Overflow, GitHub) have been annotated with basic attribution so reviewers & contributors may have confidence and access to the correct context to …
=> fix: add semicolon to startup script

scripts/delete_merge_debug.py, scripts/migrations/README.md, scripts/migrations/delete_merge_debug.py
Addresses #10887 
Adds a script that will delete all `merge-authors-debug` entries from the store tables.
__I would prefer that this script be approved for execution, but not be merged into `master`__.  There's no point in maintaining a script that will only be used once.
=> Add script to delete `merge-authors-debug` store entries

openlibrary/core/wikidata.py, openlibrary/i18n/messages.pot, openlibrary/plugins/upstream/covers.py, openlibrary/templates/covers/add.html, openlibrary/templates/covers/external_image.html, openlibrary/tests/core/test_wikidata.py, static/css/components/cbox.less
- **add ability to upload author images from wikidata**
- **add template for external image**
Closes #10934
=> Wikidata images are now suggested for authors

Makefile
`docker build -f docker/Dockerfile.olbase -t openlibrary/olbase:latest .` was failing only on arm machines.
Removing this legacy python info in the makefile fixed it.
Also removed the old load prod data command because we recommend running it in docker now.
https://docs.openlibrary.org/2_Developers/misc/Loading-Production-Book-Data.html#loading-production-data-into-local-developer-environment
=> fix makefile for arm machines

openlibrary/templates/publishers/view.html, openlibrary/templates/subjects.html, static/css/legacy.less
This css isn't used.
Or rather, it has no meaningful impact.
Go see for yourself at and run `document.querySelectorAll(".spacer")` to find the element
https://openlibrary.org/publishers/Farshore
https://openlibrary.org/subjects/emotional_intelligence
=> remove unused spacer css

openlibrary/plugins/openlibrary/js/lists/ListService.js, openlibrary/plugins/openlibrary/lists.py, openlibrary/plugins/openlibrary/partials.py
Closes #10986 
This PR achieves to refactor the `partials.py` file to include `MyBooksDropperListsPartial` as an extension to `PartialDataHandler`.
The implementation is pretty straight forward and migrates the functionality of `get_lists` method to `MyBooksDropperListsPartial`
All tests have been passes the screenshot for the same have been attested.
=> Move `/lists/partials.json` handler to `partials.py`

openlibrary/accounts/model.py
The account anonymization function is sometimes not removing the associated `account-email` store entry, due to the email not being converted to lowercase in the store key.  Since 10 June 2014, all `account-email` store keys contain the lowercase email.
There are around 42,000 `account-email` store entries that a mixed-case `key`.  To be sure that these folks can successfully anonymize their accounts, the original `del web.ctx.site.store[f'account-email/{email}']` statement remains unchanged.
=> Ensure `account-email` store key is deleted on account anonymize

openlibrary/plugins/upstream/account.py
Closes #10965
The `work` we were getting back from infogami was actually a type `redirect` and was not hydrated by the core.models.Work class (and returned `Nothing`).
@cdrini
=> Closes #10965; fix resolve redirect chain in export

openlibrary/plugins/openlibrary/js/check-ins/index.js, openlibrary/plugins/openlibrary/partials.py, openlibrary/plugins/upstream/checkins.py
Closes #10985 
Refactors the codebase to migrate `/reading-goals/partials.json` handler to `partials.py`. 
- Created new `ReadingGoalProgressPartial` handler that extends from `PartialDataHandler` in `partials.py`
- Update `PartialRequestResolver.component_mapping`, adding the new handler
- Update existing `/reading-goal/partials.json` calls to use `/partials.json`
- Deleted `/reading-goal/partials.json` handler
- For testing the functionality one can navigate to `MyBooks` section on the main page.
- Then can toggle `set Reading Goal` from the left pane and notice `Networks` tab though inspect.
- After setting a goal value user can click [SET].
- A `reading-goal.json` object can be seen in the `networks` tab. Refer to Screenshot attached.
=> Migrating the /reading-goals/partials.json handler to /partials.py

scripts/migrations/delete_merge_debug.py, scripts/utils/graceful_shutdown.py
In support of #10887
Adds the following improvements to the `merge-authors-debug` data removal script:
- Infogami `ClientExceptions` are handled gracefully
- Shutdown signals are handled gracefully
The `ClientExceptions` are sometimes occurring when the store tables are queried for a count of remaining `merge-author-debug` while the `delete_merge_debug.py` script is running (client is sometimes unable to get a lock on the table).
=> Improve author debug data deletion script

openlibrary/core/bookshelves.py
Closes #10970
My Books reading log pages breaks when books deleted; a deletion should probably cascade and remove related books from reading log table (similar to how we update redirects). In the interim, this solution should unbreak book pages by changing the `assertion` to an `if` check.
Tested on testing.
=> unbreak my books for deleted books

openlibrary/core/bookshelves.py, openlibrary/i18n/messages.pot, openlibrary/templates/type/delete/view.html
Closes #11059
Addendum to #10970
- Also made sure the delete page UI shows the "View previous version link" for logged in users.
Now shows a stub record for a deletion:
Clicking on the link will take the user to a page like this:
=> Note book deletions in patron's reading log

openlibrary/components/LibraryExplorer/components/LibraryToolbar.vue, openlibrary/i18n/messages.pot, openlibrary/macros/QueryCarousel.html, openlibrary/macros/RawQueryCarousel.html, openlibrary/macros/SearchResultsWork.html, openlibrary/macros/TrendingBadge.html, openlibrary/plugins/openlibrary/js/lazy-carousel.js, openlibrary/plugins/worksearch/code.py, openlibrary/templates/books/RelatedWorksCarousel.html, openlibrary/templates/publishers/view.html, openlibrary/templates/search/sort_options.html, openlibrary/templates/subjects.html, static/css/components/carousel.less, static/css/components/search-result-item.less
Closes #8548 , but mainly continuation of #10947 .
- Adds "Trending" as a sort option to the search page
- Switches subjects/publishers pages to use `QueryCarousel` powered by the edition-aware search.json endpoint
- Sorts subjects/publishers pages by Trending by default
- Adds a librarian-only UI to the search results to verify trending 
Trending dropdown:
French users will now see French horror books:
https://testing.openlibrary.org/subjects/horror?lang=fr
| Before | After | 
| ---- | ---- |
| <img width="1398" height="549" alt="image" src="https://github.com/user-attachments/assets/97c07817-7fd0-4a9c-a812-028a9d873709" /> | <img width="1378" height="555" alt="image" src="https://github.com/user-attachments/assets/11510abd-2ff1-4c37-a6db-2367a5a7deaa" /> |
The Standard Ebooks publisher …
=> Add trending to sort options, sort subject pages by trending, and other trending tweaks

scripts/migrations/README.md, scripts/migrations/anonymous_store_remediation.py
Adds a script that finds and removes any `account-email` store entries that were not deleted during our account anonymization process.  The script does the following:
1. Fetches all `/people/{username}` `/type/delete` entries from the store, extracting `username`.
2. For each `username`, we check if the associated account has been deactivated by querying `store`
3. If the account was deactivated, we search for its `account-email` store key
4. Deletes the `account-email` store entry if a store key was found
=> Remediation script for anonymized `account-email` store entries

openlibrary/plugins/upstream/account.py
Addresses #10976
Adds new `POST` handler that can be used to anonymize Open Library accounts via archive.org.
`POST` requests to `/account/anonymize.json` containing valid `x-s3-access` and `x-s3-secret` headers trigger an account anonymization action on the associated account.
| Response | Meaning |
|---|---|
| `200 OK` | The account anonymization request was successful |
| `400 Bad Request` | The authorization header was malformed |
| `403 Forbidden` | The request did not originate from archive.org |
| `404 Not Found` | No account associated with the given S3 keys was not found |
| `500 Internal Server Error` | The account anonymization operation failed for some reason |
Adding `?test=true` to account anonymization requests will trigger the account anonymization in `test` mode, which …
=> Account anonymization `POST` handler

openlibrary/templates/lists/list_follow.html
Closes #11037 
Fixes the issue of handling `owner` in **GLOBAL LISTS** and **COMMUNITY LISTS**.
Added a check for `owner` present or not for a particular list. If not then don't render the bottom section.
For testing one can view a book that is in community list.
Earlier behavior before fix: Lists were not rendered due to owner not present
After fix: The list is rendering with the implementation as suggested.
https://testing.openlibrary.org/works/OL831059W/Pet_show!?edition=ia%3Apetshowreadingra0000unse#lists-section
@mekarpeles
=> Fixed the bug to handle global and community lists

static/robots.txt
Google keeps trying to index this page for some reason? I don't think we even link to this publicly... so not sure how or why...
=> Disallow crawling of /merges

.github/workflows/python_tests.yml
We can speed up our CI times a bit by using UV.
How I got the numbers.
Go to the history of the workflow runs [here](https://github.com/internetarchive/openlibrary/actions/workflows/python_tests.yml?page=2&query=is%3Asuccess).
Run some js to extract the times.
```js
Array.from(document.querySelectorAll(".octicon-stopwatch")).map(e=>e.nextElementSibling.innerText.trim()).map(str => (parseInt(str.match(/(\d+)\s*m/)?.[1] || 0) * 60) + parseInt(str.match(/(\d+)\s*s/)?.[1] || 0)).join("\n")
```
Plug the numbers into:
https://www.calculatorsoup.com/calculators/statistics/statistics.php
Without UV:
```
Minimum = 52
Maximum = 89
Range = 37
n = 50
sum = 3112
Mean = 62.24
Median = 60
mode = 56
```
With UV: it takes 50 or 53 seconds to run. So saving ~10 seconds on average.
I don't have a large …
=> use UV in GitHub Actions

pyproject.toml
Closes #
Ever notice how ruff always warns us about updated configs settings?
This fixes that!
Warning in question:
```
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
- 'mccabe' -> 'lint.mccabe'
- 'pylint' -> 'lint.pylint'
- 'per-file-ignores' -> 'lint.per-file-ignores'
```
=> use modern ruff config

scripts/sitemaps/sitemap.py
Fixes I/O error that is being thrown by [`generate_sitemaps()`](https://github.com/internetarchive/openlibrary/blob/386544244b9ec5b1cabe54d7be1201745aecd7e7/scripts/sitemaps/sitemap.py#L145-L160) during our sitemap generation process.
The generator `rows`, which lazily reads from a file, was being consumed outside of the `with` block (after the file was closed).
=> Fix I/O errors during sitemap generation

openlibrary/accounts/model.py
Adding typehints where we don't need to change things.
Closes #
=> add typehints to accounts/model.py

openlibrary/templates/lists/list_follow.html, static/css/components/list-follow.less
Closes #11081 
This PR fixes the overflowing `Follow` button when usernames were long. 
It also truncates usernames with ellipsis and adds a `hover tooltip`.
- The "Follow" button is now fully visible and not hidden by any gradient or overlay.
- The long usernames are displayed to truncate with ellipsis (...).
- Implemented a hover tooltip that shows the full username on mouse hover.
- Verified responsiveness so that UI elements (button, usernames) behave correctly on different screen sizes.
- Tested that the "Follow" button remains clickable and accessible after the fix.
- One can click on any `book`.
- Scroll down to `Lists` section.
- One can then see, long usernames are now truncated with ellipsis and follow button also does not overflow.
@mekarpeles
=> Fixed Follow button overflow

openlibrary/core/bestbook.py
Updates `Bestbook.PRIMARY_KEY` to `award_id`, which is the column name of the `bestbooks` table's primary key in production and local development environments.
Leaving `PRIMARY_KEY` unchanged may cause some `db.CommonExtras` methods to fail when they are invoked by a `Bestbooks` object (specifically, [`update_work_ids_individually`](https://github.com/internetarchive/openlibrary/blob/baf7303c2ee8d14c68ce02bb7f0232f467496e53/openlibrary/core/db.py#L65) and [`update_work_ids`](https://github.com/internetarchive/openlibrary/blob/baf7303c2ee8d14c68ce02bb7f0232f467496e53/openlibrary/core/db.py#L32)).
No change to [`core/schema.sql`](https://github.com/internetarchive/openlibrary/blob/baf7303c2ee8d14c68ce02bb7f0232f467496e53/openlibrary/core/schema.sql#L116) was needed.
=> Update `Bestbook.PRIMARY_KEY` to production value

static/css/components/book.less
Join waitlist had a padding error; i've added the join waitlist form as a specification of cta-button-group in book.less; this change should make all paddings uniform.
Issue #11036
Fix
The padding for all form buttons should be uniform after merging this fix.
Refer to https://github.com/internetarchive/openlibrary/issues/11036#issuecomment-3092714921
I am not entirely sure how to check the browser/UI implementation of the issue.
@RayBB @mekarpeles
=> Fix Waitlist button padding issue

openlibrary/i18n/messages.pot, openlibrary/templates/lists/list_follow.html, static/css/components/list-follow.less
Closes #11110 
This PR adds a _feature_ for showing an unclickable `Private` for lists by patrons who have Private accounts. 
- Added an **else** condition when patron account isn't public.
- Click on any book.
- Scroll down to `Lists`.
- For **private** accounts one can now see an unclickable Private button.
@ragipidavid
=> Added pvt button

openlibrary/core/cache.py, openlibrary/plugins/openlibrary/home.py, openlibrary/plugins/openlibrary/pd.py, openlibrary/tests/core/test_cache.py
Followup to https://github.com/internetarchive/openlibrary/pull/11003#issuecomment-3098468324
One of the things mentioned there was adding typed dicts. However, in some of the cases where I was trying I'd eventually run into the memoized functions that have no types.
I did a little research and learned that we can add typehints for memoized functions. And it turns out it works just fine to do so without much change.
The one change that is made here is removing the `_cache = 'delete'` option.
Basically, it's not possible to faithfully show the type of the function you're caching and allow for extra args.
Also, deleting manually is much better for separation of concerns. Besides, we only used that arg in a few places so it's not much to fix.
=> add typehints to memcache_memoize

openlibrary/plugins/upstream/account.py
Valid requests to `/account/anonymize.json` have been returning `500`s, and the affected accounts are only partially anonymized: The account object is not being updated, but the account's reading log, notes, likes, etc. _are_ being updated as expected.
I suspect that actions taken within [this block](https://github.com/internetarchive/openlibrary/blob/4be092163d6fa0e995917e40c0d6def29b7591e2/openlibrary/plugins/upstream/account.py#L368-L389) require `RunAs` to complete successfully.
Exceptions thrown during patron anonymization are written to our error logs, and will be available in Sentry when they occur.
=> Run account anonymization actions as the patron

openlibrary/solr/update.py
Closes #9710 (I think)
During solr_update, when editions are identified as having no base works (orphaned), the script checks for a (nonexistent) `works` key using that edition's ID. Later, when it is looping through works to update, it detects that this "fake" work does not exist and just flags it for deletion. Orphaned editions continue to not show up in search results.
This PR adds some logic to detect when a work key was created by an orphaned edition, and create a "dummy" base work for it using information extracted from the edition. This makes the book show up in search results.
I ran `copydocs` on the orphaned edition originally identified for testing in the issue ticket (`/books/OL10021046M`). In my local solr admin UI, it did not show up in search results.
Then, with my updates …
=> fix: support "dummy" works for orphaned editions

static/css/components/list-follow.less
Closes #11055 
This PR fixes the overflowing texts in Global Lists title **by using ellipsis in a single line**.
- There are up to 1 line of text
- If it overflows beyond 1 line, it is truncated with ellipsis (...)
- The full title is visible as a tooltip (hover tip) when the user hovers over it.
- Click on any book of your choice.
- Navigate down to `Lists` section.
- If the length of the `title` is big, then it appears in two lines and truncated with ellipsis.
- Hover over it to view complete title.
@mekarpeles
=> Titles under a single line

scripts/migrations/write_prefs_to_store.py
Makes the following changes to `write_prefs_to_store.py`:
- Sets `username` to the actual username in `copy_preferences_to_store()`
- Removes each batch from the list of `affected_pref_keys` 
These two bugs caused the script to endlessly attempt to get the account of a nonexistent patron having username `preferences`.
=> Fix bugs in preference migration script

compose.production.yaml, compose.yaml, conf/solr/conf/solrconfig.xml, scripts/solr_builder/compose.yaml
Closes #11168
- In 9.8, they deprecated the `<lib>` option from solrconfig.xml for security in favour of explicitly recognized modules via eg `SOLR_MODULES` environment variable. See https://solr.apache.org/guide/solr/latest/upgrade-notes/major-changes-in-solr-9.html#solr-9-8
- Also note now that solr is part of our normal deploy flow, it would be quite a problem to have the compose.yaml change go out onto our prod solr! That container isn't for it. So I took just the `solr` service out by tagging it with the profile `ol-never`. 
Locally seems to work as per usual
=> Update solr to latest version, 9.9.0

openlibrary/catalog/add_book/load_book.py, openlibrary/catalog/utils/__init__.py, openlibrary/catalog/utils/tests/test_catalog_utils.py
Allow author records with just `death_date` to count as _dated_ for the purposes of author possible match comparisons.
fixes #10736
Previously when one record had `birth_date` and the other didn't, we chose to assume they couldn't be the same.
This needs to be changed to not just look at `birth_date`, but `death_date` also, because some incoming records provide _just_ a `death_date` (example in #10736)
This is the summary of the existing intended logic when comparing a single incoming `author` record against a list of existing authors pulled out via a search query  https://github.com/internetarchive/openlibrary/blob/dee6fb024af906c0b0d9d14969c15ea15b68d103/openlibrary/catalog/add_book/load_book.py#L194-L205
* **Both records are dateless**: assume a (potential) match (based on previous …
=> Allow author records with just 'death_date' to count as "dated"

openlibrary/catalog/add_book/__init__.py, openlibrary/catalog/add_book/tests/test_add_book.py
Closes #10757 
Validates every IA record. This is more broad than what is required due to the assumption that open library should be able to import anything that is in the Internet Archive.
I'm aware that some logic is duplicated. I opted for this approach to make the code more resilient. If the function order is changed down the road, this structure helps prevent breakages.
Try to import a book such as this one: http://localhost:8080/import/preview?source=ia:seventhmanlargep0000maxb
Before this error was fixed:
After fix applied:
End result:
@cdrini @scottbarnes
=> Allow independently published IA imports

openlibrary/accounts/model.py, openlibrary/core/lending.py, openlibrary/core/waitinglist.py, openlibrary/plugins/admin/tests/test_code.py, openlibrary/plugins/upstream/account.py, openlibrary/tests/accounts/test_models.py
This is a followup to the note we put here:
https://github.com/internetarchive/openlibrary/pull/10999/files#diff-884f3a712a7e51cce625ca19060335684272f33a967702b19e66e48dbdd1be69R495
Turns out raising by default isn't probably the ideal behavior for our codebase because we call the method fairly often and expect a None to get back.
As such, I added 
Changes:
- Replace most usages of generic `.get` method with `.get_by_*` methods which are better defined.
- Removed the `.get` method, we can use `.get_or_raise` when we want to raise.
- Refactored `.get_or_raise` to accept just a value and a literal for the type of value
- Removed the unused `test=` from the get methods
- Fixed a bug on the internal audit endpoint where we weren't checking all the ways to get a user
PS: This refactor my seem …
=> refactor account get method

openlibrary/core/pd.py, openlibrary/plugins/openlibrary/pd.py, openlibrary/templates/admin/pd_dashboard.html
Supports #11009
Depends on #11173
Updates query used to populate the `/admin/pd` page to source data from the store.
Total counts are now calculated within the `get_pd_dashboard_data` python function.
=> Updates query for `pd` fulfillment statistics

docker/web_nginx.conf
Part of #11277
meta-externalagent does not seem to follow our crawl rates in https://openlibrary.org/robots.txt and so we're blocking them.
=> Add meta-externalagent to user agent deny checks

openlibrary/components/IdentifiersInput.vue
Follows #11283
Follows #11208
For some reason, setting `isAdmin` in the `created` lifecycle hook works as expected in my local environment, but _does not work_ on testing.  Changing `isAdmin` to a computed property appears to make things work as expected in both local dev and testing environments.
=> Identifiers : Reinstate `isAdmin` as computed property

scripts/dev-instance/dev_db.pg_dump
Related to #11296
Updates `pg_dump` file, which is used to initially populate the database in local development instances of Open Library.
- Added new `/usergroup/curators` page
- Added `bestbooks` table
- Added `wikidata` table
=> Updates local `pg_dump` file

openlibrary/utils/solr.py
=> Fix solr get_many erroring for no ids

openlibrary/plugins/upstream/account.py
Follows #10899
Our `/admin/pd` stats tell us that ~10 patrons have had their special access requests fulfilled (meaning their `rpd` preference has a value of `2`). However, there are over 1,000 patrons who have an `rpd: 2`, but no `pda` authority in the store.
Whenever _any_ patron logs in, we check the `xauthn` response to see if they have special access.  If they do, we update their `rpd` status to fulfilled.  This is done even if the patron __did not__ request special access via Open Library.  Such patrons can be identified by having a fulfilled `rpd` value, but no `pda` value in their preferences (this stores the patron's chosen print disability qualifying authority).
This branch will prevent an `rpd` value from being saved to a patron's preference object if they do not already have a …
=> Only update `rpd` value if patron requested access via Open Library

openlibrary/core/models.py, openlibrary/plugins/openlibrary/code.py
Closes #11280 . This remove the auto-import of the `/isbn`. Note the greatest fix long term. We should create a separate issue to investigate how to re-enable. But this did appear to resolve our traffic issues, while still keeping the `/isbn` point up for finding books.
=> Don't hit affiliate server on /isbn

openlibrary/macros/RawQueryCarousel.html, openlibrary/plugins/openlibrary/partials.py, openlibrary/plugins/upstream/models.py, openlibrary/plugins/worksearch/code.py, openlibrary/plugins/worksearch/languages.py, openlibrary/plugins/worksearch/publishers.py, openlibrary/plugins/worksearch/subjects.py, openlibrary/utils/solr.py, scripts/monitoring/solr_logs_monitor.py
We were today hit with high traffic to our subject and author pages, but were unable to see the labelled requests in our solr dashboards. The pages are now labelled with:
- `SUBJECT_ENGINE_PAGE` and `SUBJECT_ENGINE_API`. Note this also includes `/publisher` pages, which are in essence the same.
- `AUTHOR_BOOKS_PAGE` for author pages
- `GET_WORK_SOLR_DATA` has been added to label when solr data is fetched via the `Work._solr_data()` model method. This happens on a lot of pages, but is fast.
`UNLABELLED` has also been modified to suffix with the type of request made, eg `UNABELLED_SELECT`, `UNLABELLED_GET`, etc.
- Refactors `SubjectEngine` to have a simpler class hierarchy by removing the `SubjectMeta` class. Now there is only one `SubjectEngine` class that is sub-classed for publishers and …
=> Label more solr queries for monitoring + some SubjectEngine, QueryLabel refactoring

openlibrary/i18n/messages.pot, openlibrary/macros/Follow.html
Follows #11311
Addresses bug mentioned [here](https://github.com/internetarchive/openlibrary/pull/11311/files#r2395805233)
While the original code worked, our `messages.pot` file has an entry for `UnfollowFollow` due to the way this is written.
- Ensure that the "Follow" button copy is as expected (either `Follow` or `Unfollow`).
- Ensure that the `UnfollowFollow` entry is removed from `messages.pot` after the file is generated (by `pre-commit ci`)
=> Fix button label translation for "Follow" buttons

scripts/migrations/update_legacy_preferences.py
Follows #11310
Fixes failing [`web.ctx.site.save()` calls](https://github.com/internetarchive/openlibrary/blob/8d46fa4df1e49be008865cddac2a0cdb6214f8b6/scripts/migrations/update_legacy_preferences.py#L59) in legacy preference updater script by setting a default IP address.  When no IP address is set, inserts into the `transaction` table fail.
Now, when the script is being initialized, `127.0.0.1` is set by default.  A similar thing was done in `update_stale_ocaid_references.py`, [here](https://github.com/internetarchive/openlibrary/blob/8d46fa4df1e49be008865cddac2a0cdb6214f8b6/scripts/update_stale_ocaid_references.py#L138).
=> Ensure default IP set in preference update script

openlibrary/core/models.py
Follow-up from #11332 . The issue was exacerbated by the web nodes becoming saturated when covers was slow, due to this request, which did not have a timeout. 
Tested locally by adding a sleep to coverstore:
```diff
--- a/openlibrary/coverstore/code.py
+++ b/openlibrary/coverstore/code.py
@@ -6,6 +6,7 @@ import json
import logging
import os
import textwrap
+from time import sleep
from typing import cast
import requests
@@ -403,6 +404,7 @@ def parse_tarindex(file):
class cover_details:
def GET(self, category, key, value):
+        sleep(10)
d = _query(category, key, value)
if key == 'id':
```
And observed that on loading a book page, the page did not wait 10 seconds, but instead responded after ~3 , and without the `style="aspect-ratio: ..."` tag on the image.
=> set timeout for Image.info check to avoid site going down if covers is slow
